<?php

// Language definitions used in admin-groups.php
// Polish (UTF-8 v1.4.2): kumiech [kumiech@gmail.com] (Polish FluxBB Support - fluxbb.orge.pl)
$lang_admin_groups = array(

'Must enter title message'		=>	'Należy wprowadzić nazwę grupy.',
'Title already exists message'	=>	'Już istnieje grupa o nazwie <strong>%s</strong>.',
'Default group redirect'		=>	'Grupa domyślna została ustawiona. Przekierowywanie…',
'Cannot remove default message'	=>	'Grupa domyślna nie może zostać usunięta. W celu usnięcia tej grupy, ustaw inną grupę domyślną.',
'Group removed redirect'		=>	'Grupa została usunięta. Przekierowywanie…',
'Group added redirect'			=>	'Grupa została dodana. Przekierowywanie…',
'Group edited redirect'			=>	'Grupa została zaktualizowana. Przekierowywanie…',

'Add groups head'				=>	'Grupy użytkowników',
'Add group subhead'				=>	'Dodaj nową grupę',
'New group label'				=>	'Bazuj na grupie',
'New group help'				=>	'Wybierz grupę użytkowników, z której odziedziczone zostaną ustawienia uprawnień dla nowej grupy. Na następnej stronie możesz dokonać zmian i zatwierdzić nową grupę.',
'Default group subhead'			=>	'Ustaw domyślną grupę',
'Default group label'			=>	'Wybierz grupę',
'Default group help'			=>	'To jest domyślna grupa użytkowników, do której automatycznie przydzielani są nowo zarejestrowani użytkownicy. Ze względów bezpieczeństwa, grupą domyślną nie może być grupa administratorów, bądź moderatorów forum.',
'Existing groups head'			=>	'Grupy już istniejące',
'Edit groups subhead'			=>	'Edytuj/usuń grupy',
'Edit groups info'				=>	'Odgórnie zdefiniowane grupy użytkowników, tj. Goście, Administratorzy, Moderatorzy, Użytkownicy, nie mogą być usunięte, co najwyżej można edytować ich ustawienia. W niektórych grupach, pewne opcje są niedostępne (np. <em>edytowanie postów</em> dla gości). Administratorzy posiadają zawsze pełne uprawnienia.',
'Edit link'						=>	'Edytuj',
'Delete link'					=>	'Usuń',
'Group delete head'				=>	'Usuwanie grupy',
'Confirm delete subhead'		=>	'Potwierdź usunięcie grupy',
'Confirm delete info'			=>	'Czy jesteś pewny, że chcesz usunąć grupę <strong>%s</strong>?',
'Confirm delete warn'			=>	'<strong>OSTRZEŻENIE!</strong> Po usunięciu grupy nie można jej ponownie przywrócić!',
'Delete group head'				=>	'Usuwanie grupy',
'Move users subhead'			=>	'Przenoszenie użytkowników',
'Move users info'				=>	'Grupa <strong>%s</strong> posiada obecnie <strong>%s</strong> użytkowników. Wybierz grupę, do której zostaną przypisani użytkownicy po usunięciu wybranej grupy.',
'Move users label'				=>	'Przenieś do',
'Delete group'					=>	'Usuń',

'Group settings head'			=>	'Ustawienia grupy',
'Group settings subhead'		=>	'Ustaw preferencje i uprawnienia',
'Group settings info'			=>	'Poniższe ustawienia są domyślnymi opcjami grupy, automatycznie przydzielanymi przy jej tworzeniu.',
'Group title label'				=>	'Nazwa grupy',
'User title label'				=>	'Tytuł użytkownika',
'User title help'				=>	'Ten tytuł zastąpi rangi użytkowników, którzy zostaną przydzieleni do tej grupy. Pozostaw to pole puste, aby nadać domyślny tytuł lub rangę.',
'Mod privileges label'			=>	'Nadaj przywileje moderatora',
'Mod privileges help'			=>	'Użytkownicy tej grupy otrzymają uprawnienia moderatora, jeśli będą moderatorami co najmniej jednego z for (zakładka "Administracja" w profilu użytkownika).',
'Edit profile label'			=>	'Edycja profili użytkowników',
'Edit profile help'				=>	'Jeśli przywileje moderatora są włączone, zezwalaj użytkownikom tej grupy na edytowanie profili użytkowników.',
'Rename users label'			=>	'Zmiana nazw użytkowników',
'Rename users help'				=>	'Jeśli przywileje moderatora są włączone, zezwalaj użytkownikom tej grupy na zmienianie nazw użytkowników.',
'Change passwords label'		=>	'Zmiana haseł użytkowników',
'Change passwords help'			=>	'Jeśli przywileje moderatora są włączone, zezwalaj użytkownikom tej grupy na zmienianie haseł użytkowników.',
'Ban users label'				=>	'Banowanie użytkowników',
'Ban users help'				=>	'Jeśli przywileje moderatora są włączone, zezwalaj użytkownikom tej grupy na banowanie użytkowników.',
'Read board label'				=>	'Czytanie forum',
'Read board help'				=>	'Zezwalaj użytkownikom tej grupy na czytanie forum. To ustawienie ma wyższy priorytet, nie może być nadpisane przez specyficzne ustawienia for. Jeśli opcja jest ustawiona na "Nie", użytkownicy tej grupy mogą jedynie zarejestrować, zalogować lub wylogować się na forum.',
'View user info label'			=>	'Pokazywanie profilu użytkownika',
'View user info help'			=>	'Zezwalaj użytkownikom tej grupy na przeglądanie listy i profili użytkowników.',
'Post replies label'			=>	'Odpowiadanie w wątkach',
'Post replies help'				=>	'Zezwalaj użytkownikom tej grupy na odpowiadanie w wątkach.',
'Post topics label'				=>	'Tworzenie wątków',
'Post topics help'				=>	'Zezwalaj użytkownikom tej grupy na tworzenie nowych wątków.',
'Edit posts label'				=>	'Edytowanie postów',
'Edit posts help'				=>	'Zezwalaj użytkownikom tej grupy na edytowanie własnych postów.',
'Delete posts label'			=>	'Usuwanie postów',
'Delete posts help'				=>	'Zezwalaj użytkownikom tej grupy na usuwanie własnych postów.',
'Delete topics label'			=>	'Usuwanie wątków',
'Delete topics help'			=>	'Zezwalaj użytkownikom tej grupy na usuwanie własnych wątków (wraz ze wszystkimi odpowiedziami).',
'Set own title label'			=>	'Ustawianie własnego tytułu',
'Set own title help'			=>	'Zezwalaj użytkownikom tej grupy na ustawianie własnego tytułu.',
'User search label'				=>	'Używanie wyszukiwarki',
'User search help'				=>	'Zezwalaj użytkownikom tej grupy na korzystanie z wyszukiwarki.',
'User list search label'		=>	'Wyszukiwanie użytkowników',
'User list search help'			=>	'Zezwalaj użytkownikom tej grupy na wyszukiwanie użytkowników.',
'Send e-mails label'			=>	'Wysyłanie wiadomości e-mail',
'Send e-mails help'				=>	'Zezwalaj użytkownikom tej grupy na wysyłanie wiadomości e-mail do innych użytkowników.',
'Post flood label'				=>	'Blokada czasowa pisania postów',
'Post flood help'				=>	'Liczba sekund, po których użytkownicy tej grupy mogą ponownie odpowiadać w wątkach. Ustaw 0, aby wyłączyć blokadę.',
'Search flood label'			=>	'Blokada czasowa wyszukiwania',
'Search flood help'				=>	'Liczba sekund, po których użytkownic tej grupy mogą ponownie korzystać z wyszukiwarki. Usatw 0, aby wyłączyć blokadę.',
'E-mail flood label'			=>	'Blokada czasowa wysyłania wiadomości e-mail',
'E-mail flood help'				=>	'Liczba sekund, po których użytkownicy tej grupy mogą ponownie wysłać wiadomość e-mail. Ustaw 0, aby wyłączyć blokadę.',
'Moderator info'				=>	'Użytkownicy należący do grupy Moderator mogą moderować fora tylko wtedy, gdy zostaną przypisani do jednego lub więcej for. Można to zrobić poprzez zakładkę Administracja w profilu użytkownika.',

);
