<?php

// Language definitions used in admin_bans.php
// Polish (UTF-8 v1.4.2): kumiech [kumiech@gmail.com] (Polish FluxBB Support - fluxbb.orge.pl)
$lang_admin_bans = array(

'No user message'			=>	'Brak zarejestrowanego użytkownika o podanej nazwie. Jeśli nie chcesz dodać bana konkretnemu użytkownikowi, pozostaw to pole puste.',
'No user ID message'		=>	'Brak zarejestrowanego użytkownika o podanym ID.',
'User is admin message'		=>	'Użytkownik %s jest Administratorem, więc nie może zostać zbanowany. Jeśli chcesz dodać bana Administratorowi, najpierw musi on zostać zdegradowany do grupy Moderatora lub Użytkownika.',
'Must enter message'		=>	'Należy wprowadzić co najmniej nazwę użytkownika, adres IP lub adres e-mail.',
'Cannot ban guest message'	=>	'Konto Gościa nie może zostać zbanowane.',
'Invalid IP message'		=>	'Wprowadziłeś niepoprawny adres IP, bądź zakres adresów IP.',
'Invalid e-mail message'	=>	'Wprowadziłeś niepoprawny adres e-mail, bądź domenę.',
'Invalid date message'		=>	'Wprowadziłeś niepoprawną datę wygaśnięcia bana.',
'Invalid date reasons'		=>	'Format daty powinien wyglądać następująco: RRRR-MM-DD. Data bana musi być ustawiona co najmniej jeden dzień do przodu.',
'Ban added redirect'		=>	'Ban został dodany. Przekierowywanie…' ,
'Ban edited redirect'		=>	'Ban został zaktualizowany. Przekierowywanie…',
'Ban removed redirect'		=>	'Ban został usunięty. Przekierowywanie…',

'New ban head'				=>	'Banowanie użytkowników',
'Add ban subhead'			=>	'Dodaj nowy ban',
'Username label'			=>	'Nazwa użytkownika',
'Username help'				=>	'Wprowadź nazwę użytkownika do zbanowania (wielkość liter nie ma znaczenia).',
'Username advanced help'	=>	'Wprowadź nazwę użytkownika do zbanowania (wielkość liter nie ma znaczenia). Na następnej stronie możesz wprowadzić wybrany adres IP, bądź e-mail do zbanowania. Jeśli chcesz zbanować jedynie adres IP lub zakres adresów IP, pozostaw to pole puste.',

'Ban search head'			=>	'Wyszukiwanie banów',
'Ban search subhead'		=>	'Kryteria wyszukiwania',
'Ban search info'			=>	'Wyszukiwarka banów w bazie forum. Możesz wprowadzić jedno lub więcej kryteriów wyszukiwania. Znak (*) zastępuje dowolny ciąg znaków.',
'Date help'					=>	'(rrrr-mm-dd)',
'Message label'				=>	'Wiadomość',
'Expire after label'		=>	'Data wygaśnięcia po',
'Expire before label'		=>	'Data wygaśnięcia przed',
'Order by label'			=>	'Sortuj według',
'Order by username'			=>	'nazwa użytkownika',
'Order by ip'				=>	'IP',
'Order by e-mail'			=>	'e-mail',
'Order by expire'			=>	'data wygaśnięcia',
'Ascending'					=>	'rosnąco',
'Descending'				=>	'malejąco',
'Submit search'				=>	'Szukaj',

'E-mail label'				=>	'E-mail',
'E-mail help'				=>	'Adres e-mail lub domena do zbanowania (np. email@domena.pl lub domena.pl). Zobacz "Zezwalaj na zbanowane adresy e-mail" w Uprawnieniach, w celu uzyskania dodatkowych informacji.',
'IP label'					=>	'Adres IP/Zakres adresów IP',
'IP help'					=>	'Adres IP lub zakres adresów IP do zbanowania (np. 150.11.110.1 lub 150.11.110). Adresy oddzielaj pojedynczą spacją. Jeśli wprowadzony adres IP jest już zbanowany, poprzednie bany nie ulegną zmianie.','IP help link'				=>	'Kliknij %s, aby sprawdzić statystyki adresów IP dla tego użytkownika.',
'Ban advanced head'			=>	'Zaawansowane ustawienia bana',
'Ban advanced subhead'		=>	'Uzupełnianie danych',
'Ban message label'			=>	'Wiadomość',
'Ban message help'			=>	'Wiadomość zostanie wyświetlona użytkownikowi, gdy odwiedzi forum.',
'Message expiry subhead'	=>	'Wiadomość i data wygaśnięcia bana',
'Ban IP range info'			=>	'OSTRZEŻENIE! Bądź ostrożny przy banowaniu zakresu adresów IP, gdyż rózni użytkownicy mogą korzystać z tego samego zakresu.',
'Expire date label'			=>	'Data wygaśnięcia',
'Expire date help'			=>	'Data, kiedy ban zostanie automatycznie zdjęty (format: rrrr-mm-dd). Jeśli chcesz ręcznie usunąć bana, pozostaw to pole puste.',

'Results head'				=>	'Wyniki wyszukiwania',
'Results username head'		=>	'Nazwa użytkownika',
'Results e-mail head'		=>	'E-mail',
'Results IP address head'	=>	'Adres IP/Zakres adresów IP',
'Results expire head'		=>	'Data wygaśnięcia',
'Results message head'		=>	'Wiadomość',
'Results banned by head'	=>	'Zbanowany przez',
'Results actions head'		=>	'Akcje',
'No match'					=>	'Brak wyników',
'Unknown'					=>	'Nieznany',

);
