<?php

// Language definitions used in admin_index.php
// Polish (UTF-8 v1.4.2): kumiech [kumiech@gmail.com] (Polish FluxBB Support - fluxbb.orge.pl)
$lang_admin_index = array(

'fopen disabled message'			=>	'Nie udało się sprawdzić aktualizacji, gdyż funkcja \'allow_url_fopen\' została wyłączona na serwerze.',
'Upgrade check failed message'		=>	'Sprawdzenie aktualizacji nie powiodło się.',
'Running latest version message'	=>	'Korzystasz z najnowszej wersji FluxBB.',
'New version available message'		=>	'Nowa wersja FluxBB jest dostępna. Możesz ją pobrać pod adresem %s.',
'PHPinfo disabled message'			=>	'Funkcja phpinfo() została wyłączona na tym serwerze.',
'Not available'						=>	'Niedostępne',
'Forum admin head'					=>	'Administracja forum',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'Witamy w panelu administracyjnym FluxBB. Z tego miejsca możesz kontrolować głównymi ustawieniami i preferencjami forum. W zależności od tego, czy jesteś administratorem, czy moderatorem, możesz:',
'Welcome 1'							=>	'organizować kategorie i fora,',
'Welcome 2'							=>	'dostosowywać ustawienia i preferencje,',
'Welcome 3'							=>	'kontrolować dostęp dla użytkowników i gości,',
'Welcome 4'							=>	'sprawdzać statystyki użytkowników,',
'Welcome 5'							=>	'banować użytkowników,',
'Welcome 6'							=>	'cenzurować słowa,',
'Welcome 7'							=>	'ustawiać rangi dla użytkowników,',
'Welcome 8'							=>	'czyścić stare posty,',
'Welcome 9'							=>	'zarządzać raportami.',
'Statistics head'					=>	'Informacje ogólne',
'FluxBB version label'				=>	'Wersja FluxBB',
'Check for upgrade'					=>	'Sprawdź aktualizacje',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'Serwer',
'Server load data'					=>	'%s - %s użytkownik(ów) online',
'Environment label'					=>	'Środowisko',
'Environment data OS'				=>	'System operacyjny: %s',
'Show info'							=>	'Pokaż info',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Akcelerator: %s',
'Turck MMCache'						=>	'Turk MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Baza danych',
'Database data rows'				=>	'Rekordów: %s',
'Database data size'				=>	'Rozmiar: %s',

);