<?php

// Language definitions used in admin-users.php
// Polish (UTF-8 v1.4.2): kumiech [kumiech@gmail.com] (Polish FluxBB Support - fluxbb.orge.pl)
$lang_admin_users = array(

'Non numeric message'		=>	'Wprowadzono niepoprawny znak w kolumnie numerycznej.',
'Invalid date time message'	=>	'Wprowadzono niepoprawną datę lub czas.',
'Not verified'				=>	'Niezweryfikowany',
'User search head'			=>	'Wyszukiwanie użytkowników',
'User search subhead'		=>	'Wprowadź kryteria wyszukiwania',
'User search info'			=>	'Wyszukiwanie użytkowników w bazie. Wprowadź jedno lub więcej kryteriów. Znak (*) zastępuje dowolny ciąg znaków.',
'Username label'			=>	'Nazwa użytkownika',
'E-mail address label'		=>	'Adres e-mail',
'Title label'				=>	'Tytuł',
'Real name label'			=>	'Prawdziwe imię',
'Website label'				=>	'Strona WWW',
'Jabber label'				=>	'Jabber',
'ICQ label'					=>	'ICQ',
'MSN label'					=>	'MSN Messenger',
'AOL label'					=>	'AOL IM',
'Yahoo label'				=>	'Yahoo Messenger',
'Location label'			=>	'Lokalizacja',
'Signature label'			=>	'Sygnatura',
'Admin note label'			=>	'Notka administratora',
'Posts more than label'		=>	'Liczba postów większa niż',
'Posts less than label'		=>	'Liczba postów mniejsza niż',
'Last post after label'		=>	'Ostatni post po',
'Date help'					=>	'(rrrr-mm-dd hh:mm:ss)',
'Last post before label'	=>	'Ostatni post przed',
'Registered after label'	=>	'Zarejestrowany po',
'Registered before label'	=>	'Zarejestrowany przed',
'Order by label'			=>	'Sortuj według',
'Order by username'			=>	'nazwa użytkownika',
'Order by e-mail'			=>	'e-mail',
'Order by posts'			=>	'liczba postów',
'Order by last post'		=>	'ostatni post',
'Order by registered'		=>	'data rejestracji',
'Ascending'					=>	'rosnąco',
'Descending'				=>	'malejąco',
'User group label'			=>	'Grupa',
'All groups'				=>	'Wszystkie grupy',
'Unverified users'			=>	'Niezweryfikowani',
'Submit search'				=>	'Szukaj',
'IP search head'			=>	'Wyszukiwanie IP',
'IP search subhead'			=>	'Wyszukiwanie IP',
'IP address label'			=>	'Adres IP',
'IP address help'			=>	'Wprowadź adres IP do wyszukania w bazie postów.',
'Find IP address'			=>	'Szukaj',

'Results head'				=>	'Wyniki wyszukiwania',
'Results username head'		=>	'Nazwa użytkownika',
'Results e-mail head'		=>	'Adres e-mail',
'Results title head'		=>	'Tytuł/Ranga',
'Results posts head'		=>	'Liczba postów',
'Results admin note head'	=>	'Notka administratora',
'Results actions head'		=>	'Akcje',
'Results IP address head'	=>	'Adres IP',
'Results last used head'	=>	'Ostatnio używany',
'Results times found head'	=>	'Znaleziony razy',
'Results action head'		=>	'Akcja',
'Results find more link'	=>	'Znajdź więcej użytkowników z tym IP',
'Results no posts found'	=>	'Nie znaleziona żadnych postów użytkownika na forum.',
'Bad IP message'			=>	'Wprowadzono niepoprawny adres IP.',
'Results view IP link'		=>	'Zobacz IP',
'Results show posts link'	=>	'Pokaż posty',
'Results guest'				=>	'Gość',
'Results no IP found'		=>	'Nie znaleziono podanego IP w bazie.',
'No match'					=>	'Brak wyników',

);