<?php

// Language definitions used in admin_maintenance.php
$lang_admin_maintenance = array(

'Maintenance head'				=>	'Konserwacja forum',
'Rebuild index subhead'			=>	'Przebudowa indeksu wyszukiwania',
'Rebuild index info'			=>	'Jeżeli występują problemy z wyszukiwaniem lub edytowałeś/kasowałeś posty bezpośrednio w bazie danych, to należy przebudować indeks wyszukiwarki. Dla uzyskania lepszej wydajności, włącz na forum %s podczas przebudowy indeksu. <strong>Przebudowywanie indeksu potrwa dość długi czas i zwiększy obciążenie serwera!</strong>',
'Posts per cycle label'			=>	'Postów na cykl',
'Posts per cycle help'			=>	'Liczba postów na jeden cykl odświeżania, np. jeśli wprowadzisz liczbę 300, trzysta postów zostanie przetworzonych zanim strona zostanie odświeżona. Ustawienie to ma zapobiec przekroczeniu czasu wykonywania skryptu.',
'Starting post label'			=>	'Początkowe ID',
'Starting post help'			=>	'Numer ID postu, od którego rozpocznie się przebudowywanie indeksu. Domyślną wartością jest pierwsze dostępne ID w bazie.',
'Empty index label'				=>	'Wyczyść indeks',
'Empty index help'				=>	'Zaznacz to pole, jeśli chcesz wyczyścić indeks przed przebudową (patrz poniżej).',
'Rebuild completed info'		=>	'Po zakończeniu procesu przebudowywania, zostaniesz przekierowany z powrotem na tą stronę. Zalecane jest, aby w Twojej przeglądarce była włączona obsługa skryptów JavaScript (do automatycznego przekierowywania po zakończeniu cyklu). Jeśli jesteś zmuszony do przerwania procesu, zapamiętaj ostatni ID, który był przetwarzany. Następnie wprowadź numer ID+1 w polu "Początkowe ID", aby kontynuować proces przebudowy (pole "Wyczyść indeks" musi być odznaczone).',
'Rebuild index'					=>	'Przebuduj indeks',
'Rebuilding search index'		=>	'Przebudowa indeksu wyszukiwania - proces w trakcie...',
'Rebuilding index info'			=>	'Przebudowywanie indeksu. Zrób sobie przerwę na kawę :-)',
'Processing post'				=>	'Przebudowywanie w trakcie - post ID <strong>%s</strong>',
'Click here'					=>	'Kliknij tutaj',
'Javascript redirect failed'	=>	'Przekierowanie za pomocą skryptu JavaScript nie powiodło się. %s, aby kontynuować...',
'Posts must be integer message'	=>	'Liczba postów na cykl musi być liczbą całkowitą.',
'Days must be integer message'	=>	'Liczba dni musi być liczbą całkowitą.',
'No old topics message'			=>	'Nie ma żadnych postów starszych niż %s dni. Zwiększ liczbę dni i spróbuj ponownie.',
'Posts pruned redirect'			=>	'Posty usunięte. Przekierowywanie …',
'Prune head'					=>	'Usuń',
'Prune subhead'					=>	'Czyszczenie forum',
'Days old label'				=>	'Usuń posty starsze niż (dni)',
'Days old help'					=>	'Starsze posty niż podana liczba dni zostaną usunięte.',
'Prune sticky label'			=>	'Usuń przyklejone tematy',
'Prune sticky help'				=>	'Kiedy zaznaczone, przyklejone tematy także zostaną usunięte.',
'Prune from label'				=>	'Forum do wyczyszczenia',
'All forums'					=>	'Wszystkie fora',
'Prune from help'				=>	'Forum, z którego chcesz usunąć stare posty.',
'Prune info'					=>	'Używaj tej funkcji z rozwagą. <strong>Po usunięciu nie będzie możliwości odzyskania postów.</strong> Dla najlepszej wydajności, powinieneś włączyć %s.',
'Confirm prune subhead'			=>	'Potwierdź usunięcie postów',
'Confirm prune info'			=>	'Jesteś pewny, że chcesz usunąć posty starsze niż %s z forum %s (%s tematów).',
'Confirm prune warn'			=>	'OSTRZEŻENIE! Czyszczenie spowoduje trwałe usunięcie postów.',

);
