<?php

// Language definitions used in both profile.php and register.php
// Polish (UTF-8 v1.4.2): kumiech [kumiech@gmail.com] (Polish FluxBB Support - fluxbb.orge.pl)
$lang_prof_reg = array(

'Email legend'				=>	'Ustawienia adresu e-mail',
'Email legend 2'			=>	'Wprowadź i potwierdź adres e-mail',
'Localisation legend'		=>	'Ustawienia lokalizacji',
'Time zone'					=>	'Strefa czasowa',
'Time zone info'			=>	'Wybierz swoją lokalną strefę czasową, aby poprawnie wyświetlać czas na forum. Jeżeli aktualnie panuje czas letni, zaznacz poniższą opcję zmiany czasu na letni, aby przesunąć go o 1 godzinę do przodu.',
'DST'						=>	'Zmiana czasu na letni (przesunięcie o 1 godzinę).',
'Time format'				=>	'Format czasu',
'Date format'				=>	'Format daty',
'Default'					=>	'Domyślny',
'Language'					=>	'Język forum',
'Email setting info'		=>	'Wybierz, czy chcesz, aby Twój adres e-mail był widoczny dla innych użytkowników oraz czy zezwalasz na kontakt z Tobą za pomocą wiadomości e-mail.',
'Email setting 1'			=>	'Wyświetlaj adres e-mail.',
'Email setting 2'			=>	'Ukryj adres e-mail, ale zezwalaj na wysyłanie wiadomości e-mail.',
'Email setting 3'			=>	'Ukryj adres e-mail i nie zezwalaj na wysyłanie wiadomości e-mail.',
'Privacy options legend'	=>	'Ustawienia prywatności',
'Confirm pass'				=>	'Potwierdź hasło',

'Username too short'		=>	'Nazwa użytkownika musi składać się z co najmniej 2 znaków. Wybierz inną (dłuższą) nazwę użytkownika.',
'Username too long'			=>	'Nazwa użytkownika nie może składać się z więcej niż 25 znaków. Wybierz inną (krótszą) nazwę użytkownika.',
'Username guest'			=>	'Nazwa użytkownika Gość (Guest) jest zastrzeżona. Wybierz inną nazwę użytkownika.',
'Username IP'				=>	'Nazwa użytkownika nie może mieć postaci adresu IP. Wybierz inną nazwę użytkownika.',
'Username reserved chars'	=>	'Nazwa użytkownika nie może zawierać znaków \', ", [ i ] jednocześnie. Wybierz inną nazwę użytkownika.',
'Username BBCode'			=>	'Nazwa użytkownika nie może zawierać tagów BBCode. Wybierz inną nazwę użytkownika.',
'Banned username'			=>	'Wprowadzona nazwa użytkownika jest zbanowana na forum. Wybierz inną nazwę użytkownika.',
'Pass too short'			=>	'Hasło użytkownika muzi składać się z co najmniej 4 znaków. Wybierz inne (dłuższe) hasło.',
'Pass not match'			=>	'Podane hasła nie pasują do siebie.',
'Banned email'				=>	'Wprowadzony adres e-mail jest zbanowany na forum. Wybierz inny adres e-mail.',
'Dupe email'				=>	'Na forum jest już zarejestrowany użytkownik z podanym adresem e-mail. Wybierz inny adres e-mail.',
'Sig too long'              =>  'Podpis użytkownika nie może być dłuższy niż %1$s znaków. Skróć podpis o co najmniej %2$s znaków.',
'Sig too many lines'        =>  'Podpis użytkownika nie może składać się z więcej niż %s linii.',
'Bad ICQ'					=>	'Wprowadzono nieprawidłowy numer ICQ. Wróć i popraw numer.',

'UTC-12:00'					=>	'(UTC -12:00) Międzynarodowa Linia Zmiany Daty',
'UTC-11:00'					=>	'(UTC -11:00) Niue, Samoa, Samoa Amerykańskie',
'UTC-10:00'					=>	'(UTC -10:00) Hawaje, Aleuty, Wyspy Cooka',
'UTC-09:30'					=>	'(UTC -09:30) Markizy',
'UTC-09:00'					=>	'(UTC -09:00) Alaska, Wyspy Gambiera',
'UTC-08:30'					=>	'(UTC -08:30) Wyspy Pitcairn',
'UTC-08:00'					=>	'(UTC -08:00) Ocean Spokojny, USA (zachodnie wybrzeże)',
'UTC-07:00'					=>	'(UTC -07:00) Meksyk (Sonora), USA (Arizona)',
'UTC-06:00'					=>	'(UTC -06:00) Honduras, Kostaryka, USA (środkowy wschód)',
'UTC-05:00'					=>	'(UTC -05:00) Ekwador, Haiti, Kuba, Peru, USA (wschód)',
'UTC-04:00'					=>	'(UTC -04:00) Brazylia, Chile, Dominikana, Paragwaj, Portoryko',
'UTC-03:30'					=>	'(UTC -03:30) Nowa Fundlandia',
'UTC-03:00'					=>	'(UTC -03:00) Argentyna, Brazylia (wschód), Grenlandia, Urugwaj',
'UTC-02:00'					=>	'(UTC -02:00) Brazylia (wyspy atlantyckie), Georgia Południowa',
'UTC-01:00'					=>	'(UTC -01:00) Azory, Grenlandia (wschód), Republika Zielonego Przylądka',
'UTC'						=>	'(UTC) Europa Zachodnia, Greenwich',
'UTC+01:00'					=>	'(UTC +01:00) Europa Centralna (Polska), Afryka Wschodnia',
'UTC+02:00'					=>	'(UTC +02:00) Europa Wschodnia, Afryka Centralna',
'UTC+03:00'					=>	'(UTC +03:00) Rosja (Moskwa), Afryka Wschodnia',
'UTC+03:30'					=>	'(UTC +03:30) Iran',
'UTC+04:00'					=>	'(UTC +04:00) Armenia, Gruzja, Seszele',
'UTC+04:30'					=>	'(UTC +04:30) Afganistan',
'UTC+05:00'					=>	'(UTC +05:00) Pakistan, Rosja (Jekaterynburg), Uzbekistan',
'UTC+05:30'					=>	'(UTC +05:30) Indie, Sri Lanka',
'UTC+05:45'					=>	'(UTC +05:45) Nepal',
'UTC+06:00'					=>	'(UTC +06:00) Bangladesz, Bhutan, Rosja (Nowosybirsk)',
'UTC+06:30'					=>	'(UTC +06:30) Birma, Wyspy Kokosowe',
'UTC+07:00'					=>	'(UTC +07:00) Indonezja (zachód), Rosja (Krasnojarsk), Tajlandia, Wietnam',
'UTC+08:00'					=>	'(UTC +08:00) Chiny, Australia Zachodnia, Rosja (Irkuck)',
'UTC+08:45'					=>	'(UTC +08:45) Australia Zachodnia (część wschodnia)',
'UTC+09:00'					=>	'(UTC +09:00) Japonia, Korea, Palau',
'UTC+09:30'					=>	'(UTC +09:30) Austalia Centralna',
'UTC+10:00'					=>	'(UTC +10:00) Australia Wschodnia, Rosja (Władywostok)',
'UTC+10:30'					=>	'(UTC +10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC +11:00) Mikronezja (wchód), Wyspy Salomona',
'UTC+11:30'					=>	'(UTC +11:30) Norfolk',
'UTC+12:00'					=>	'(UTC +12:00) Nowa Zelandia, Fidżi, Rosja (Kamczatka)',
'UTC+12:45'					=>	'(UTC +12:45) Wyspy Chatham',
'UTC+13:00'					=>	'(UTC +13:00) Tonga, Wyspy Feniks',
'UTC+14:00'					=>	'(UTC +14:00) Kiribati (Line Islands)',

);