<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'Wyszukiwarka użytkownika',
'No search permission'				=>	'Nie posiadasz uprawnień do korzystania z wyszukiwarki.',
'Search flood'						=>	'Musisz odczekać co najmniej %s sekund pomiędzy wyszukiwaniami. Odczekaj jeszcze %s sekund, a następnie spróbuj ponownie.',
'Search'							=>	'Wyszukiwarka',
'Search criteria legend'			=>	'Wprowadź kryteria wyszukiwania',
'Search info'						=>	'Przy wyszukiwaniu za pomocą słów kluczowych, wprowadź jedno lub więcej słów, oddzielając je przecinkami, które chcesz znaleźć. Możesz użyć AND (i), OR (lub) i NOT (nie), aby szczegółowo zdefiniować wyszukiwanie. Przy szukaniu autora wprowadź nazwę użytkownika, którego posty chcesz znaleźć. Znak (*) zastępuje dowolny ciąg znaków.',
'Keyword search'					=>	'Szukaj słowa kluczowe',
'Author search'						=>	'Szukaj autora',
'Search in legend'					=>	'Wybierz forum do przeszukania',
'Search in info'					=>	'Wybierz forum, które chcesz przeszukać i wybierz miejsce, gdzie mają być szukane słowa (temat wątku, treść posta).',
'Search multiple forums info'		=>	'Jeśli żadne fora nie zostaną zaznaczone, to wszystkie fora zostaną przeszukane.',
'Forum search'						=>	'Forum',
'Search in'							=>	'Szukaj w',
'Message and subject'				=>	'Treść posta i temat wątku',
'Message only'						=>	'Tylko treść posta',
'Topic only'						=>	'Tylko temat wątku',
'Sort by'							=>	'Sortuj według',
'Sort order'						=>	'Kolejność',
'Search results legend'				=>	'Wybierz sposób wyświetlania wyników',
'Search results info'				=>	'Wybierz jak mają być posortowane i w jaki sposób wyświetlone wyniki wyszukiwania.',
'Sort by post time'					=>	'Data',
'Sort by author'					=>	'Autor',
'Sort by subject'					=>	'Temat',
'Sort by forum'						=>	'Forum',
'Ascending'							=>	'Rosnąco',
'Descending'						=>	'Malejąco',
'Show as'							=>	'Pokaż wyniki jako',
'Show as topics'					=>	'Wątki',
'Show as posts'						=>	'Posty',

// Results
'Search'							=>	'Szukaj',
'Search results'					=>	'Wyniki wyszukiwania',
'Quick search show_new'				=>	'nowe',
'Quick search show_recent'			=>	'aktywne',
'Quick search show_unanswered'		=>	'bez odpowiedzi',
'Quick search show_replies'			=>	'z odpowiedzią',
'Quick search show_user_topics'		=>	'wątki napisane przez %s',
'Quick search show_user_posts'		=>	'posty napisane przez %s',
'Quick search show_subscriptions'	=>	'subskrybowane przez %s',
'By keywords show as topics'		=>	'wątki z postami ze słowami kluczowymi \'%s\'',
'By keywords show as posts'			=>	'posty ze słowami kluczowymi \'%s\'',
'By user show as topics'			=>	'wątki z postami użytkownika %s',
'By user show as posts'				=>	'posty napisane przez %s',
'By both show as topics'			=>	'wątki ze słowami kluczowymi \'%s\' w postach użytkownika %s',
'By both show as posts'				=>	'posty ze słowami kluczowymi \'%s\' użykownika %s',
'No terms'							=>	'Należy wprowadzić co najmniej jedno słowo kluczowe i/lub nazwę autora do wyszukania.',
'No hits'							=>	'Brak wyników wyszukiwania.',
'No user posts'						=>	'Na forum nie ma żadnych postów tego użytkownika.',
'No user topics'					=>	'Na forum nie ma żadnych wątków tego użytkownika.',
'No subscriptions'					=>	'Użytkownik aktualnie nie subskrybuje żadnych wątków.',
'No new posts'						=>	'Od Twojej ostatniej wizyty na forum nie pojawiły się nowe posty.',
'No recent posts'					=>	'W ciągu ostatnich 24h na forum nie pojawiły się nowe posty.',
'No unanswered'						=>	'Na forum nie ma żadnych wątków bez odpowiedzi.',
'Go to post'						=>	'Przejdź do postów',
'Go to topic'						=>	'Przejdź do wątku',

);
