<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'			=>	'No hi ha cap usuari registrat amb aquest nom. Si vols afegir una prohibició que no estigui vinculada a un nom d\'usuari específic simplement deixa en blanc el nom d\'usuari.',
'No user ID message'		=>	'Ni hi ha cap usuari registrat amb aquesta ID.',
'User is admin message'		=>	'L\'usuari %s és un administrador i no pot ser expulsat. Per a expulsar a un administrador cal degradar-lo a moderador o usuari.',
'User is mod message'		=>	'L\'usuari %s és un moderador i no pot ser expulsat. Per a expulsar a un administrador cal degradar-lo a usuari.',
'Must enter message'		=>	'Almenys cal introduïr un nom d\'usuari, un adreça IP o un email.',
'Cannot ban guest message'	=>	'Un convidat no pot ser expulsat.',
'Invalid IP message'		=>	'Has introduït una IP no vàlida.',
'Invalid e-mail message'	=>	'L\'email (ej. usuari@domini.com) o el domini de l\'adreça (ex. domini.com) que has introduït no és vàlid.',
'Invalid date message'		=>	'Has introduït una data d\'expiració no vàlida.',
'Invalid date reasons'		=>	'El format ha de ser DD-MM-YYYY i la data ha de ser almenys d\'un dia posterior (demà).',
'Ban added redirect'		=>	'Expulsió afegida. Redirigint …' ,
'Ban edited redirect'		=>	'Editant expulsió. Redirigint …',
'Ban removed redirect'		=>	'Eliminant expulsió. Redirigint …',

'New ban head'				=>	'Nou expulsat',
'Add ban subhead'			=>	'Afegir expulsat',
'Username label'			=>	'Usuari',
'Username help'				=>	'Usuari a expulsar (distingueix entre majúscules/minúscules).',
'Username advanced help'	=>	'L\'usuari a expulsar distingueix entre majúscules i minúscules. A la pàgina següent podras introduïr un email i una adreça IP personalitzada. Si només vols expulsari una IP específica, un Rang-IP o un email, deixa-ho en blanc.',

'Ban search head'			=>	'Cerca d\'expulsats',
'Ban search subhead'		=>	'Introdueix els criteris de cerca',
'Ban search info'			=>	'Cerca d\'expulsats a la base de dades. Pots introduïr un o més termes a cercar. Els comodins asterisc (*) estan permesos.',
'Date help'					=>	'(dd-mm-yyyy)',
'Message label'				=>	'Missatge',
'Expire after label'		=>	'Expira després de',
'Expire before label'		=>	'Expira abans de',
'Order by label'			=>	'Ordenar per',
'Order by username'			=>	'Usuari',
'Order by ip'				=>	'IP',
'Order by e-mail'			=>	'Email',
'Order by expire'			=>	'Data d\'expiració',
'Ascending'					=>	'Ascendent',
'Descending'				=>	'Descendent',
'Submit search'				=>	'Enviar cerca',

'E-mail label'				=>	'Email',
'E-mail help'				=>	'El correu electrònic o el domini del correu que vols expulsar (ex. nom@domini.com o domini.com). Consulta la secció "Permetre emails d\'expulsats" en els Permisos per a més informació.',
'IP label'					=>	'Adreces IP / Rangs IP',
'IP help'					=>	'L\'adreça IP o el rang-IP que vols expulsar (ex. 150.11.110.1 ó 150.11.110). Separa les adreces amb espais. Si introdueixes una IP aquesta serà sempre l\'última IP coneguda pel sistema per a aquell usuari a la base de dades.',
'IP help link'				=>	'Clicar a %s per veure les estadístiques IP d\'aquest usuari.',
'Ban advanced head'			=>	'Configuració avançada d\'expulsions',
'Ban advanced subhead'		=>	'Expulsió suplementària amb IP i correu electrònic',
'Ban message label'			=>	'Missatge d\'expulsió',
'Ban message help'			=>	'Missatge que se li mostrarà a l\'usuari expulsat quan visiti el fòrum.',
'Message expiry subhead'	=>	'Missatge d\'expulsió i expiració',
'Ban IP range info'			=>	'Cal tenir molta cura en prohibir una rang IP a causa de la possibilitat de què diversos usuaris coincideixin parcialment amb la mateixa IP',
'Expire date label'			=>	'Vàlid fins',
'Expire date help'			=>	'La data en la que aquesta expulsió serà automàticament eliminada (format: dd-mm-aaaa). Deixa-ho en blanc per a eliminar-ho manualment.',

'Results head'				=>	'Resultats de la cerca',
'Results username head'		=>	'Usuari',
'Results e-mail head'		=>	'Email',
'Results IP address head'	=>	'IP/rangs-IP',
'Results expire head'		=>	'Expira',
'Results message head'		=>	'Missatge',
'Results banned by head'	=>	'Expulsat per',
'Results actions head'		=>	'Accions',
'No match'					=>	'No hi ha resultats',
'Unknown'					=>	'Desconegut',

);
