<?php

// Language definitions used in admin-options.php
$lang_admin_options = array(

'Bad HTTP Referer message'			=>	'Mal HTTP_REFERER. Si has mogut aquest fòrum d\'un cantó a un altre o ha canviat de domini, és necessari actualtzar manualment l\'adreça base URL a la base de dades (busca o_base_url a la taula de configuració) i llavors buida la caché eliminant tots els arxius .php del directori /cache.',
'Must enter title message'			=>	'Cal introduïr un títol al fòrum.',
'Invalid e-mail message'			=>	'L\'email que has entrat del\'administrador no és vàlid.',
'Invalid webmaster e-mail message'	=>	'L\'email que has entrat del webmaster no és vàlid.',
'SMTP passwords did not match'		=>	'Cal que entris la contrasenya SMTP dues vegades exactament igual per a poder canviar-la.',
'Enter announcement here'			=>	'Posa el teu anunci aquí.',
'Enter rules here'					=>	'Introdueix les normes aquí.',
'Default maintenance message'		=>	'El fòrum està temporalment fora de servei per manteniment. Si us plau, intenta-ho uns minuts més tard. Disculpa les molèsties.',
'Timeout error message'				=>	'El valor del "Tems d\'espera en línia" cal que sigui menor que el valor del "Temps d\'espera de la visita".',
'Options updated redirect'			=>	'Opcions actualitzades. Redireccionant …',
'Options head'						=>	'Opcions',

// Essentials section
'Essentials subhead'				=>	'Essencials',
'Board title label'					=>	'Titol del fòrum',
'Board title help'					=>	'El títol d\'aquest fòrum (mostrat en la part superior de cada pàgina). Aquest camp <strong>no</strong> pot contenir HTML.',
'Board desc label'					=>	'Descripció del fòrum',
'Board desc help'					=>	'Introdueix una breu descripció d\'aquest fòrum serà mostrada a la part superior de cada pàgina. Aquest camp admet contingut en HTML.',
'Base URL label'					=>	'URL Base',
'Base URL help'						=>	'L\'adreça URL completa del fòrum sense la barra final (ex. http://www.elmeudomini/forums). <strong>Cal</strong> que sigui correcta per a què tots els administradors i moderadors funcionin. Si reps errors "Mal referer", probablement és perquè l\'adreça és incorrecta.',
'Timezone label'					=>	'Zona horària por defecte',
'Timezone help'						=>	'La zona horària per defecte per als convidats i usuaris que es registrin al fòrum.',
'DST label'							=>	'Ajustar a l\'horari d\'estiu',
'DST help'							=>	'Comprova si l\'horari d\'estiu està en vigor (avanços de temps en 1 hora).',
'Language label'					=>	'Idioma per defecte',
'Language help'						=>	'L\'idioma per defecte per als convidats i usuaris que no l\'hagin canviat des del seu perfil. Si elimines un paquet d\'idioma, hauran d\'actualitzar-se.',
'Default style label'				=>	'Estil per defecte',
'Default style help'				=>	'La plantilla per defecte per als convidats i usuaris que no l\'hagin canviat des del seu perfil.',

// Essentials section timezone options
'UTC-12:00'							=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'							=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'							=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'							=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'							=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'							=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'							=>	'(UTC-08:00) Pacific',
'UTC-07:00'							=>	'(UTC-07:00) Mountain',
'UTC-06:00'							=>	'(UTC-06:00) Central',
'UTC-05:00'							=>	'(UTC-05:00) Eastern',
'UTC-04:00'							=>	'(UTC-04:00) Atlantic',
'UTC-03:30'							=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'							=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'							=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'							=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'								=>	'(UTC) Western European, Greenwich',
'UTC+01:00'							=>	'(UTC+01:00) España, Europa Central, Africa Oeste',
'UTC+02:00'							=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'							=>	'(UTC+03:00) Eastern African',
'UTC+03:30'							=>	'(UTC+03:30) Iran',
'UTC+04:00'							=>	'(UTC+04:00) Moscow, Gulf, Samara',
'UTC+04:30'							=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'							=>	'(UTC+05:00) Pakistan',
'UTC+05:30'							=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'							=>	'(UTC+05:45) Nepal',
'UTC+06:00'							=>	'(UTC+06:00) Bangladesh, Bhutan, Yekaterinburg',
'UTC+06:30'							=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'							=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'							=>	'(UTC+08:00) Greater China, Australian Western, Krasnoyarsk',
'UTC+08:45'							=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'							=>	'(UTC+09:00) Japan, Korea, Chita, Irkutsk',
'UTC+09:30'							=>	'(UTC+09:30) Australian Central',
'UTC+10:00'							=>	'(UTC+10:00) Australian Eastern',
'UTC+10:30'							=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'							=>	'(UTC+11:00) Solomon Island, Vladivostok',
'UTC+11:30'							=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'							=>	'(UTC+12:00) New Zealand, Fiji, Magadan',
'UTC+12:45'							=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'							=>	'(UTC+13:00) Tonga, Phoenix Islands, Kamchatka',
'UTC+14:00'							=>	'(UTC+14:00) Line Islands',

// Timeout Section
'Timeouts subhead'					=>	'Horaris i temps d\'espera',
'Time format label'					=>	'Format d\'hora',
'PHP manual'						=>	'PHP manual',
'Time format help'					=>	'[Format actual: %s]. Veure %s per a les opcions de format.',
'Date format label'					=>	'Format de dia',
'Date format help'					=>	'[Current format: %s]. See %s for formatting options.',
'Visit timeout label'				=>	'Temps d\'espera Visita',
'Visit timeout help'				=>	'Nombre de segons que un usuari ha d\'estar inactiu abans de què s\'actualitzin les dades de la seva última visita (afecta principalment als indicadors dels nous missatges).',
'Online timeout label'				=>	'Temps d\'espera en línia',
'Online timeout help'				=>	'Nombre de segons que un usuari ha d\'estar inactiu abans de ser eliminat de la llista d\'usuaris en línia.',
'Redirect time label'				=>	'Temps de redirecció',
'Redirect time help'				=>	'Nombre de segons d\'espera al redirigir. Si s\'estableix a 0, no mostrarà la pàgina de redireccionament (no recomanat).',

// Display Section
'Display subhead'					=>	'Mostrar',
'Version number label'				=>	'Versió número',
'Version number help'				=>	'Mostrar el número de versió en el peu de pàgina.',
'Info in posts label'				=>	'Informació de l\'usuari en els missatges',
'Info in posts help'				=>	'Mostra informació de l\'usuari qui ho ha publicat en la vista del tema (sota el nom d\'usuari en vista de temes). La informació afectada les la ubicació, data de registre, nombre de missatges i enllaços de contacte (e-mail i URL).',
'Post count label'					=>	'Nombre de missatges d\'aquest usuari',
'Post count help'					=>	'Mostra el nombre de missatges que ha publicat un usuari (afecta a Vista de tema, perfil i llista d\'usuarios).',
'Smilies label'						=>	'Emoticones en missatges',
'Smilies help'						=>	'Converteix les emoticones en petites icones gràfiques.',
'Smilies sigs label'				=>	'Emoticones a les signatures',
'Smilies sigs help'					=>	'Converteix les emoticones en petites icones gràfiques en les signatures dels usuaris.',
'Clickable links label'				=>	'Poder clicar sobre els enllaços',
'Clickable links help'				=>	'Quan està actiu, el sistema detecta automàticament qualsevol adreça web en els missatges i la converteix en un hipervincle polsable.',
'Topic review label'				=>	'Tema de revisió',
'Topic review help'					=>	'El nombre màxim de missatges a mostrar al publicar (els més actuals primer). S\'estableix en 0 para deshabilitar-ho.',
'Topics per page label'				=>	'Temes per pàgina',
'Topics per page help'				=>	'El nombre de temes per defecte que es mostraran per pàgina en un fòrums. Els usuaris poden personalitzar-se aquesta configuració.',
'Posts per page label'				=>	'Missatges per pàgina',
'Posts per page help'				=>	'El nombre de missatges per defecte que es mostraran per pàgina en un fòrumpor página en un foro. Els usuaris poden personalitzar-se aquesta configuració.',
'Indent label'						=>	'Mida de sangria',
'Indent help'						=>	'Si s\'estableix a 8, una etiqueta rgular serà utilitzada quan es mostri el text dins les etiquetes [code][/code]. Del contrari molts espais s\'utilitzaran per a sangrar el text.',
'Quote depth label'					=>	'Anidació màxima de [quote]',
'Quote depth help'					=>	'Les vegades màximes que una etiqueta [quote] pot anar dins d\'una altra etiqueta [quote]. Es descartaran nivells de profunditat superiors.',

// Features section
'Features subhead'					=>	'Característiques',
'Quick post label'					=>	'Resposta ràpida',
'Quick post help'					=>	'Quan està actiu, el sistema afegirà un formulari de resposta ràpida en la part inferior dels temes. D\'aquesta manera els usuaris poden respondre directament des de la "vista del tema".',
'Users online label'				=>	'Usuaris en línia',
'Users online help'					=>	'Mostra informació a la pàgina d\'inici dels convidats i uuaris registrats que estàn navegant els fòrums.',
'Censor words label'				=>	'Paraules censurades',
'Censor words help'					=>	'Cal habilitar-ho per a poder censurar paraules específiques en els fòrums. Visita la secció %s per a més informació.',
'Signatures label'					=>	'Signatures',
'Signatures help'					=>	'Permetre als usuaris adjuntar una signatura personalitzada al peu de cadascún dels seus missatges.',
'User has posted label'				=>	'L\'usuari ha publicat anteriorment',
'User has posted help'				=>	'Aquesta funció mostra un punt davant dels temes a viewforum.php en cas de què l\'usuari que està actualment en línia hagi publicat abans en aquest tema. Desactivar si s\'experimenta una alta càrrega del servidor.',
'Topic views label'					=>	'Temes visitats',
'Topic views help'					=>	'És un registre el nombre de cops que un tema ha sigut visitat. Desactivar si s\'experimenta una alta càrrega del servidor.',
'Quick jump label'					=>	'Salt ràpid',
'Quick jump help'					=>	'Habilitar el salt ràpid (Salta a) en la llista desplegable.',
'GZip label'						=>	'GZip de sortida',
'GZip help'							=>	'Si està activat, el sistema utilitzarà gzip com a sortida a enviar als navegadors. Això reduirà l\'ús d\'amplada de banda però aumentarà una mica més l\'ús de la CPU. Aquesta funció requereix que PHP es configuri amb zlib (- with-zlib). Nota: Si ja tens un dels mòdols Apache mod_gzip o mod_deflate creat per comprimir scripts PHP, has de desactivar aquesta funció.',
'Search all label'					=>	'Cercar en tots els fòrums',
'Search all help'					=>	'Quan està desactivada, només es permetran cerques d\'un fòrum a la vegada. Desactivar si la càrrega del servidor és alta per excessos en les cerques.',
'Menu items label'					=>	'Elements de menú addicionals',
'Menu items help'					=>	'Al participar en hipervíncles HTML en aquest quadre de text, qualsevol nombre d\'elements es poden afegir al menú de navegació en la part superior de totes les pàgines. El format per afegir nous enllaços és X = &lt;a href="URL"&gt;LINK&lt;/a&gt;  La X és la posició en la qual l\'enllaç ha d\'estar insertat. (Ex. 0 per a insertar al principi i 2 per a insertar després de la "Llsta d\'usuaris"). Separa les entrades amb un salt de línia.',

// Feeds section
'Feed subhead'						=>	'Sindicació',
'Default feed label'				=>	'Tipus de feed per defecte',
'Default feed help'					=>	'Selecciona el tipus de sindicació feed a mostrar. Nota: cap elecció no deshabilitarà els feed. Només els ocultarà de manera predeterminada.',
'None'								=>	'Cap',
'RSS'								=>	'RSS',
'Atom'								=>	'Atom',
'Feed TTL label'					=>	'Temps d\'emmagatzematge dels feeds a la caché',
'Feed TTL help'						=>	'Els feeds poden emmagatzemar-se en la memòria cau (caché) per reduir l\'ús de recursos de feeds.',
'No cache'							=>	'No emmagatzemar en caché',
'Minutes'							=>	'%d minuts',

// Reports section
'Reports subhead'					=>	'Informes',
'Reporting method label'			=>	'Mètode d\'informes',
'Internal'							=>	'Intern',
'By e-mail'							=>	'Email',
'Both'								=>	'Ambdós',
'Reporting method help'				=>	'Selecciona el mètode per a la manipulació de temes/missatges reportats. Pots escollir si el tema/missatge reportat ha de gestionar-se pel sistema d\'informes intern, per email a les adreces en la llista de correu (més avall) o ambdós.',
'Mailing list label'				=>	'Llista de correus',
'Mailing list help'					=>	'Una llista separada per comes dels subscriptors. La gent d\'aquesta llista són els destinataris dels informes.',

// Avatars section
'Avatars subhead'					=>	'Avatars',
'Use avatars label'					=>	'Avatar d\'usuari',
'Use avatars help'					=>	'Quan està activada, els usuaris podran pujar una imatge que es mostri sota el títol/rang.',
'Upload directory label'			=>	'Directori de pujada',
'Upload directory help'				=>	'El directori de pujada per als avatars (relativa al directori arrel del sistema). PHP ha de tenir permisos d\'escriptura per a aquest directori.',
'Max width label'					=>	'Amplada màxima',
'Max width help'					=>	'L\'amplada màxima permesa dels avatars píxels (60 és el recomanat).',
'Max height label'					=>	'Altura màxima',
'Max height help'					=>	'L\'altura màxima permesa dels avatars en píxels (60 és el recomanat).',
'Max size label'					=>	'Mida màxima',
'Max size help'						=>	'La mida màxima permesa d\'avatars en bytes (10240 és el recomanat).',

// E-mail section
'E-mail subhead'					=>	'Email',
'Admin e-mail label'				=>	'Email de l\'Administrador',
'Admin e-mail help'					=>	'L\'adreça de correu electrònic de l\'administrador del fòrum.',
'Webmaster e-mail label'			=>	'Email del Webmaster',
'Webmaster e-mail help'				=>	'Aquesta és la adreça que es mostrarà en tots els correus electrònics enviats pel fòrum.',
'Forum subscriptions label'			=>	'Subscripcions',
'Forum subscriptions help'			=>	'Permetre als usuaris subscriure\'s als fòrums (rebre emails quan algú respongui).',
'Topic subscriptions label'			=>	'Subscripcions als temes',
'Topic subscriptions help'			=>	'Permetre als usuaris subscriure\'s als temes (rebre emails quan algú respongui).',
'SMTP address label'				=>	'Adreça del servidor SMTP',
'SMTP address help'					=>	'L\'adreça per a un servidor extern SMTP per a podern enviar emails per mitjà de la mateixa. Pots especificar un número de port presonalitzat si el servidor SMTP no s\'executa en el port per defecte 25. (Exemple: correu.servidor.com:3580). Deixa-ho en blanc per a utilitzar l\'aplicació de correu local.',
'SMTP username label'				=>	'Nom d\'usuari SMTP',
'SMTP username help'				=>	'És el nom d\'usuari per al servidor de sortida SMTP. Introdueix-\'ho només si és requerit pel servidor SMTP (la majoria dels servidors <strong>no</strong> requereixen autenticació).',
'SMTP password label'				=>	'Contrasenya SMTP',
'SMTP change password help'			=>	'Canviar o esborrar una contrasenya emmagatzemada actualment.',
'SMTP password help'				=>	'Contrasenya del sevidor SMTP. Només introdueix una contrasenya si és requerida pel servidor SMTP (la majoria dels servidors <strong>no</strong> requereixen autenticació).',
'SMTP SSL label'					=>	'Encriptar SMTP utilitzant SSL',
'SMTP SSL help'						=>	'Encriptar la connexión al servidor SMTP utilitzant SSL. Nómes hauria d\'utilitzar-se si el servidor SMTP ho requereix i la seva versió de PHP soporta SSL.',

// Registration Section
'Registration subhead'				=>	'Registre',
'Allow new label'					=>	'Permetre nous registres',
'Allow new help'					=>	'Controla si aquest fòrum accepta nous registres. Deshabilitar-ho només en circunstàncies especials.',
'Verify label'						=>	'Verificar registres',
'Verify help'						=>	'Quan està activat, s\'envia als usuaris una contrasenya al atzar quan es registren. A continuació, pots iniciar sessió i canviar la contrasenya en el teu perfil si ho consideres oportú. Aquesta funció també requereix que els usuaris verifiquin les adreces de correu electròniques noves, si decideixen canviar l\'email amb el qual es van registrar en el seu moment. Per tant, és una manera efectiva d\'evitar l\'abús de registres, i permet assegurar-se de què tots els usuaris tenen una "correcta" adreça de correu electrònic en el seu perfil.',
'Report new label'					=>	'Reportar nous registres',
'Report new help'					=>	'Si està activat, el sistema notificarà als usuaris de la llista de correu (veure més amunt) quan un nou usuari es registri en els fòrums.',
'Use rules label'					=>	'Regles del fòrum per a l\'usuari',
'Use rules help'					=>	'Quan està activada, els usuaris han d\'estar d\'acord amb un conjunt de normes al registrar-se. (Introduïr text més amunt). Les normes estaran sempre disponibles per mitjà d\'un enllaç al menú principal de navegació situat a la part superior de cada pàgina.',
'Rules label'						=>	'Introdueix les teves regles aquí',
'Rules help'						=>	'Aquí pots introduïr qualsevol norma o informació que l\'usuari hagi de revisar i estar d\'acord en el moment de registrar-se. Si vas habilitar normes anteriors, hauràs d\'introduïr quelcom aquí, del contrari es desactivarà. Aquest text s\'analitza com llocs de plantilla i per tant pot contindre HTML.',
'E-mail default label'				=>	'Configuració per defecte del email',
'E-mail default help'				=>	'Escull la configuració de privacitat per defecte per al registre de nous usuaris.',
'Display e-mail label'				=>	'Mostra l\'email als altres usuaris.',
'Hide allow form label'				=>	'Oculta l\'email però permetre els formularis per email.',
'Hide both label'					=>	'Oculta l\'email i desactiva els formularis per email.',

// Announcement Section
'Announcement subhead'				=>	'Anuncis',
'Display announcement label'		=>	'Mostrar anuncis',
'Display announcement help'			=>	'Habilitar aquesta opció per a mostrar el següent missatge en el fòrum.',
'Announcement message label'		=>	'Missatge per a l\'anunci',
'Announcement message help'			=>	'Aquest text no serà analitzat com a missatge i per tant pot contindre HTML.',

// Maintenance Section
'Maintenance subhead'				=>	'Manteniment',
'Maintenance mode label'			=>	'Mode de manteniment',
'Maintenance mode help'				=>	'Quan està activat, el fòrum només estarà disponible per als administradors. Cal utilitzar-ho si el vol desactivar el fòrum temporalment per manteniment. <strong>ATENCIÓ! No tanquis la sessió quan el fòrum estigui en mode de manteniment.</strong> Podries no tornar-te a connectar de nou.',
'Maintenance message label'			=>	'Missatge de manteniment',
'Maintenance message help'			=>	'El missatge que es mostrarà als usuaris quan el fòrum estigui en mode de manteniment. Si es deixa en blanc, es mostrarà un missatge per defecte. Aquest text no serà analitzat com a missatge i per tant pot contindre HTML.',

);
