<?php
//REVISADO
// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'No serà possible comprovar actualitzacions fins que \'allow_url_fopen\' estigui deshabilitat en el sistema.',
'Upgrade check failed message'		=>	'Comprovació d\'actualització fallida per motius desconeguts.',
'Running latest version message'	=>	'Estàs utilitzant l\'última versió de l\'aplicació.',
'New version available message'		=>	'Hi ha una nova versió disponible. Pots descarregar-la a %s.',
'PHPinfo disabled message'			=>	'La funció PHP phpinfo() ha sigut deshabilitada en aquest servidor.',
'Not available'						=>	'No disponible',
'Forum admin head'					=>	'Administració del Fòrum',
'NA'								=>	'N/D',
'Welcome to admin'					=>	'Benvingut al tauler de control  d\'administració del fòrum. Desde d\'aquí pots controlar els aspectes vitals dels fòrums. Depenent si ets un administrador o un moderador pots:',
'Welcome 1'							=>	'Organitzar categories i fòrums.',
'Welcome 2'							=>	'Ajustar opcions i preferències dels fòrums.',
'Welcome 3'							=>	'Controlar permisos d\'usuaris i convidats.',
'Welcome 4'							=>	'Veure les adreces IP dels usuaris.',
'Welcome 5'							=>	'Expulsar usuaris.',
'Welcome 6'							=>	'Censurar pareules.',
'Welcome 7'							=>	'Ajustar els rangs dels usuaris.',
'Welcome 8'							=>	'Depurar missatges antics.',
'Welcome 9'							=>	'Gestionar missatges denunciats.',
'Statistics head'					=>	'Estadístiques',
'FluxBB version label'				=>	'Versió',
'Check for upgrade'					=>	'Comprovar actualitzacions',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'Càrrega del servidor',
'Server load data'					=>	'%s - %s usuari(s) en línia',
'Environment label'					=>	'Entorn',
'Environment data OS'				=>	'Sistema operatiu: %s',
'Show info'							=>	'Mostrar info',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Accelerador: %s',
'Turck MMCache'						=>	'Turk MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Base de dades',
'Database data rows'				=>	'Registres: %s',
'Database data size'				=>	'Mida: %s',

);
