<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Escriu un email vàlid',
'Email legend 2'			=>	'Escriu i confirma un email vàlid',
'Localisation legend'		=>	'Estableix les teves opcions de localització',
'Time zone'					=>	'Zona horària',
'Time zone info'			=>	'Has d\'introduïr la teva zona horària per a què els fòrums mostrin l\'hora correctament. Si l\'horari d\'estiu està activat, comprova-ho a fi d\'adelantar en el temps en 1 hora.',
'DST'						=>	'Horari d\'estiu activat (adelanta el temps en 1 hora).',
'Time format'				=>	'Format d\'hora',
'Date format'				=>	'Format de data',
'Default'					=>	'Per defecte',
'Language'					=>	'Idioma',
'Email setting info'		=>	'Selecciona-ho si vols que el teu email sigui visible als altres usuaris, i si vols que aquests puguin enviar-te emails per mitjà del fòrum (Formulari).',
'Email setting 1'			=>	'Mostrar email.',
'Email setting 2'			=>	'Ocultar email però permetre que et contactin des del formulari.',
'Email setting 3'			=>	'Ocultar email i prohibir que et contactin des del formulari.',
'Privacy options legend'	=>	'Estableix les teves opcions de privadesa',
'Confirm pass'				=>	'Confirmar contrasenya',

'Username too short'		=>	'Els noms d\'usuari han de tenir almenys 2 caracters de longitut. Si us plau, utilitza un altre nom d\'usuari més llarg.',
'Username too long'			=>	'Els noms d\'usuari no poden ser superiors a 25 caracters de longitut. Si us plau, utilitza un altre nom d\'usuari més curt.',
'Username guest'			=>	'El nom d\'usuari (convidat) està reservat. Si us plau, escull un altre nom d\'usuari.',
'Username IP'				=>	'Els noms d\'usuari no poden contindre forma d\'adreça IP. Si us plau, escull un altre nom d\'usuari.',
'Username reserved chars'	=>	'Els noms d\'usuari no poden contindre tos els caracters \ ", i [ o ] a la plegada. Si us plau, escull un altre nom d\'usuari.',
'Username BBCode'			=>	'Els noms d\'usuari no poden contindre cap de les etiquetes de format de text (BBCode) utilitzades pel fòrum. Si us plau, escull un altre nom d\'usuari.',
'Banned username'			=>	'El nom d\'usuari que acabes d\'introduïr està prohibit en aquest fòrum. Si us plau, escull un altre nom d\'usuari.',
'Pass too short'			=>	'Les contrasenyes han de tindre almenys 4 caracters de longitut. Si us plau, escull una altra contrasenya més llarga.',
'Pass not match'			=>	'Les contrasenyes no coincideixen.',
'Banned email'				=>	'L\'email que acabes d\'introduïr està prohibit en aquest fòrum. Si us plau, escull un altre email.',
'Dupe email'				=>	'Una altra persona ja està registrada amb aquest email. Si us plau, escull-ne un altre.',
'Sig too long'				=>	'Les signatures no poden ser més llargues de %1$s caracters. Si us plau, redueix-la a %2$s caracters.',
'Sig too many lines'		=>	'Les signatures no poden tenir més de %s línies.',
'Bad ICQ'					=>	'Has introduït un ICQ UIN invàlid. Si us plau, torna enrere i corregeix-ho.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) (Catalunya) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Moscow, Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Yekaterinburg',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Krasnoyarsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita, Irkutsk',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Vladivostok',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Magadan',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands, Kamchatka',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
