<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'Menú del perfil',
'Section essentials'			=>	'Essencials',
'Section personal'				=>	'Personal',
'Section messaging'				=>	'Missatgeria',
'Section personality'			=>	'Personalitat',
'Section display'				=>	'Mostrar',
'Section privacy'				=>	'Privacitat',
'Section admin'					=>	'Administrar',

// Miscellaneous
'Username and pass legend'		=>	'Introdueix el teu nom d\'usuari i contrasenya',
'Personal details legend'		=>	'Introdueix els teus detalls personals',
'Contact details legend'		=>	'Introdueix les dades de missatgeria',
'User activity'					=>	'Activitat de l\'usuari',
'Paginate info'					=>	'Especifica el nombre de temes i missatges que vols que es mostrin per cada pàgina.',

// Password stuff
'Pass key bad'					=>	'La clau d\'activació per a la contrasenya és incorrecta o ha caducat. Si us plau, torna a sol·licitar una nova contrasenya. Si això no funciona, contacta amb l\'administrador del fòrum a',
'Pass updated'					=>	'La teva contrasenya s\'ha actualitzat. Ja pots entrar al fòrum amb la nova contrasenya.',
'Pass updated redirect'			=>	'Contrasenya actualitzada. Redireccionant …',
'Wrong pass'					=>	'Antiga contrasenya incorrecta.',
'Change pass'					=>	'Canviar contrasenya',
'Change pass legend'			=>	'Inicia una nova sessió i confirma la teva nova contrasenya',
'Old pass'						=>	'Antiga contrasenya',
'New pass'						=>	'Nova contrasenya',
'Confirm new pass'				=>	'Confirmar nova contrasenya',
'Pass info'						=>	'Cal que les contrasenyes almenys tinguin 4 caracters de longitut. Les contrasenyes distingeixen entre majúscules i minúscules.',

// Email stuff
'Email key bad'					=>	'La clau d\'activació per a la contrasenya és incorrecta o ha expirat. Si us plau, torna a sol·licitar una nova contrasenya. Si això no funciona, contacta amb l\'administrador del fòrum a',
'Email updated'					=>	'S\'ha actualitzat la teva adreça de correu electrònic.',
'Activate email sent'			=>	'Un correo electrónico ha sido enviado a la dirección especificada con instrucciones sobre cómo activar la nueva dirección de email. Si no llega usted puede comunicarse con el administrador del foro en',
'Email legend'					=>	'Introdueix la teva nova adreça de correu electrònic',
'Email instructions'			=>	'Un correu electrònic serà enviat a la teva nova adreça de correu electrònic amb un enllaç d\'activació. Cal que facis clic sobre l\'enllaç del correu electrònic que rebis per a activar la nova adreça.',
'Change email'					=>	'Canviar adreça de correu electrònic',
'New email'						=>	'Nova adreça de correu electrònic',

// Avatar upload stuff
'Avatars disabled'				=>	'L\'administrador a desactivat l\'ús d\'avatars.',
'Too large ini'					=>	'L\'arxiu seleccionat és massa gran per a pujar-se. El servidor no permet la càrrega.',
'Partial upload'				=>	'L\'arxiu seleccionat només s\'ha pujat parcialment. Si us plau, intenta-ho de nou.',
'No tmp directory'				=>	'PHP no ha pogut desar l\'arxiu pujat a una ubicació temporal.',
'No file'						=>	'No has seleccionat cap arxiu a pujar.',
'Bad type'						=>	'L\'arxiu que estàs intentant pujar no és d\'un tipus permès. El tipus permesos son gif, jpeg i png.',
'Too wide or high'				=>	'L\'arxiu que proves de pujar és massa ample i/o major del màxim permès',
'Too large'						=>	'L\'arxiu que proves de pujar és major que el màxim permès',
'pixels'						=>	'píxels',
'bytes'							=>	'bytes',
'Move failed'					=>	'El servidor no ha pogut desar l\'arxiu pujat. Si us plau, contacta amb l\'administrador del fòrum a',
'Unknown failure'				=>	'Hi ha hagut un error desconegut. Si us plau, intenta-ho de nou.',
'Avatar upload redirect'		=>	'Avatar pujat. Redireccionant …',
'Avatar deleted redirect'		=>	'Avatar eliminat. Redireccionant …',
'Avatar desc'					=>	'Un avatar és una petita imatge que es mostrarà a sota del nom de l\'usuari en els seus missatges. No pot ser més gran que',
'Upload avatar'					=>	'Pujar avatar',
'Upload avatar legend'			=>	'Introdueix una imatge d\'avatar a pujar',
'Delete avatar'					=>	'Eliminar avatar', // only for admins
'File'							=>	'Arxiu',
'Upload'						=>	'Pujar', // submit button

// Form validation stuff
'Forbidden title'				=>	'El títol que has introduït conté una paraula prohibida. Cal que escullis un títol diferent.',
'Profile redirect'				=>	'Perfil actualitzat. Redireccionant …',

// Profile display stuff
'Users profile'					=>	'Perfil de %s',
'Username info'					=>	'Usuari: %s',
'Email info'					=>	'Email: %s',
'Posts info'					=>	'Missatges: %s',
'Registered info'				=>	'Data d\'alta (data de registre): %s',
'Last post info'				=>	'Últim missatge: %s',
'Last visit info'				=>	'Última visita: %s',
'Show posts'					=>	'Mostrar tots els missatges',
'Show topics'					=>	'Mostrar tots els temes',
'Show subscriptions'			=>	'Mostrar totes les subscripcions',
'Realname'						=>	'Nom real',
'Location'						=>	'Localització',
'Website'						=>	'Pàgina Web',
'Invalid website URL'			=>	'La URL de la pàgina web que has introduït no és vàlida.',
'Website not allowed'			=>	'Encara no pots afegir un lloc web al teu perfil.',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'MSN Messenger',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'Avatar',
'Signature'						=>	'Firma',
'Sig max size'					=>	'Longitut màx: %s caracters / línies màx: %s',
'Avatar legend'					=>	'Estableix las teves opcions d\'avatar',
'Avatar info'					=>	'Un avatar és una petita imatge que es mostrarà en totes les entradeses. Pots pujar una imatge clicant en l\'enllaç de sota.',
'Change avatar'					=>	'Canviar avatar',
'Signature legend'				=>	'Redacta la teva signatura',
'Signature info'				=>	'Una signatura o una firma és un petit trosset de text que s\'adjunta als teus missatges. En ell, pots escriure gairebé qualsevol cosa que t\'agradi. Potser t\'agradaria escriure la teva cita favorita o  el teu signe zodiacal. Tot depèn de tú! A la teva signatura firma pots utilitzar BBCode, sempre que sigui permès en cada fòrum en particular. Pots veure les característiques permeses i que figuren a continuació sempre que etitis la teva signatura.',
'Sig preview'					=>	'Vista prèvia de la signatura:',
'No sig'						=>	'Actualment no hi ha cap signatura desada en el teu perfil.',
'Signature quote/code/list/h'	=>	'Els quote, code, list i altres BBCodes no són permesos a les signatures.',
'Topics per page'				=>	'Temes',
'Posts per page'				=>	'Missatges',
'Leave blank'					=>	'Deixa-ho en blanc per a utilitzar la predeterminada del fòrum.',
'Subscription legend'			=>	'Estableix les teves opcions de subscripció',
'Notify full'					=>	'Incloeix una versió de text sense format per als nous temes en els correus de notificació de les subscripcions.',
'Auto notify full'				=>	'Subscriure\'t automàticament a tots els temes publicats per tú.',
'Show smilies'					=>	'Mostrar emoticones con icones gràfiques.',
'Show images'					=>	'Mostrar imatges en els temes.',
'Show images sigs'				=>	'Mostrar imatges a la signatura dels usuaris.',
'Show avatars'					=>	'Mostrar avatars dels usuaris als temes.',
'Show sigs'						=>	'Mostrar signature dels usuaris.',
'Style legend'					=>	'Selecciona la teva plantilla preferida',
'Styles'						=>	'Plantilles',
'Admin note'					=>	'Nota de l\'administrador',
'Pagination legend'				=>	'Introdueix les opcions de paginació',
'Post display legend'			=>	'Defineix les opcions de visualització dels missatges',
'Post display info'				=>	'Si tens una connexió lenta desactiva aquestes opcions, especialment mostrar imatges en els missatges i signatures. Això farà que les pàgines es carreguin més ràpid.',
'Instructions'					=>	'Al actualitzar el teu perfil, se\'t redirigeix de nou a aquesta mateixa pàgina.',

// Administration stuff
'Group membership legend'		=>	'Escollir grup d\'usuaris',
'Save'							=>	'Desar',
'Set mods legend'				=>	'Estableix l\'accés del moderador',
'Moderator in info'				=>	'Escull quin fòrum pot moderar aquest usuari. Nota: Això només s\'aplica als moderadors. Els adminstradors tenen permisos totals en tots els fòrums.',
'Update forums'					=>	'Actualitzar fòrums',
'Delete ban legend'				=>	'Eliminar (només per a administradors) o expulsar usuari',
'Delete user'					=>	'Eliminar usuari',
'Ban user'						=>	'Expulsar usuari',
'Confirm delete legend'			=>	'Important: llegir abans d\'eliminar un usuari',
'Confirm delete user'			=>	'Confirmar l\'eliminació de l\'usuari',
'Confirmation info'				=>	'Si us plau, confirma que vols eliminar l\'usuari', // the username will be appended to this string
'Delete warning'				=>	'Atenció! Els usuaris eliminats i/o temes no podran ser restaurats. Si decideixes no eliminar els missatges d\'aquest usuari, aquests missatges només podran eliminar-se després de forma manual.',
'Delete posts'					=>	'Elimina els missatges i els temes publicats per aquest usuari.',
'Delete'						=>	'Eliminar', // submit button (confirm user delete)
'User delete redirect'			=>	'Usuari eliminat. Redireccionant …',
'Group membership redirect'		=>	'Pertinença a grup desada. Redireccionant …',
'Update forums redirect'		=>	'Drets del moderador del fòrum actualitzats. Redireccionant …',
'Ban redirect'					=>	'Redireccionant …',
'No delete admin message'		=>	'Els administradors mai poden ser eliminats. A fi d\'eliminar aquest usuari, primer cal moure\'l a un grup d\'usuaris diferent.',

);
