<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'Cercar usuari',
'No search permission'				=>	'No disposes de permisos per utilitzar la funció de cerca.',
'Search flood'						=>	'Almenys calen %s segons entre cada cerca. Si us plau, espera un moment i torna-ho a provar.',
'Search'							=>	'Cercar',
'Search criteria legend'			=>	'Introdueix el criteri de cerca',
'Search info'						=>	'Per cercar per paraules clau, introdueix un tema o temes a cercar. Separa els temes amb espais. Utilitza AND (i), OR (o) i NOT (no) per a detallar la cerca. Per cercar per autor introdueix el nom d\'usuari de l\'autor dels missatges que vols cercar. Utilitza el caracter asterisc * per a coincidències parcials.',
'Keyword search'					=>	'Cercar paraula clau',
'Author search'						=>	'Cercar autor',
'Search in legend'					=>	'Escull on cercar',
'Search in info'					=>	'Selecciona els fòrums on cercar i si vols cercar també als assumptes dels missatges, al text dels missatges o a ambdós',
'Search multiple forums info'		=>	'Si no selecciones cap fòrum en particular, es cercarà en tots ells.',
'Forum search'						=>	'Fòrum',
'All forums'						=>	'Tots els fòrums',
'Search in'							=>	'Cercar en',
'Message and subject'				=>	'Text i assumpte del tema',
'Message only'						=>	'Només text',
'Topic only'						=>	'Només assumpte',
'Sort by'							=>	'Filtrar per',
'Sort order'						=>	'Ordenar',
'Search results legend'				=>	'Selecciona com veure els resultats de la cerca',
'Search results info'				=>	'Pots escollir com vols ordenar i veure els resultats.',
'Sort by post time'					=>	'Data',
'Sort by author'					=>	'Autor',
'Sort by subject'					=>	'Assumpte',
'Sort by forum'						=>	'Fòrum',
'Ascending'							=>	'Ascendent',
'Descending'						=>	'Descendent',
'Show as'							=>	'Mostrar resultats como',
'Show as topics'					=>	'Temes',
'Show as posts'						=>	'Missatges',

// Results
'Search'							=>	'Cercar',
'Search results'					=>	'Resultats de la cerca',
'Quick search show_new'				=>	'Temes nous',
'Quick search show_recent'			=>	'Temes actius',
'Quick search show_unanswered'		=>	'Temes sense respondre',
'Quick search show_replies'			=>	'Temes publicats per mi',
'Quick search show_user_topics'		=>	'Temes de %s',
'Quick search show_user_posts'		=>	'Missatges de %s',
'Quick search show_subscriptions'	=>	'Subscrit per %s',
'By keywords show as topics'		=>	'Temes amb posts que continguin \'%s\'',
'By keywords show as posts'			=>	'Missatges que continguin \'%s\'',
'By user show as topics'			=>	'Temes amb missatges de %s',
'By user show as posts'				=>	'Missatges de %s',
'By both show as topics'			=>	'Temes amb missatges que continguin \'%s\', de %s',
'By both show as posts'				=>	'Missatges que continguin \'%s\', de %s',
'No terms'							=>	'Cal indicar una paraula clau i/o un autor per a cercar.',
'No hits'							=>	'La cerca no ha obtingut resultats.',
'No user posts'						=>	'Aquest fòrum no conté missatges publicats per aquest usuari.',
'No user topics'					=>	'Aquest fòrum no conté temes publicats per aquest usuari.',
'No subscriptions'					=>	'Actualment no estàs subscrit a cap tema.',
'No new posts'						=>	'No hi ha temes amb nous missatges des de la teva última visita.',
'No recent posts'					=>	'No hi ha missatges nous en les últimes 24 hores.',
'No unanswered'						=>	'No hi ha missatges sense resposta a aquest fòrum.',
'Go to post'						=>	'Anar al missatge',
'Go to topic'						=>	'Anar al tema'

);
