<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'آدرس ايميل معتبري را وارد كنيد',
'Email legend 2'			=>	'آدرس ايميل معتبري را وارد و تائيد كنيد',
'Localisation legend'		=>	'گزينه هاي بومي سازي خود را تنظيم كنيد',
'Time zone'					=>	'منطقه زماني',
'Time zone info'			=>	'براي اينكه انجمن زمان را بدرستي نمايش دهد شما بايد منطقه زماني محلي خود را به درستي انتخاب كنيد . اگر ساعت تابستاني در زمان شما تاثير دارد شما بايد گزينه ارائه شده براي پيشرفت 1 ساعته زمان را تيك بزنيد.',
'DST'						=>	'ساعت تابستاني تاثيرگذار است ( پيبشرفت زمان 1 ساعت ).',
'Time format'				=>	'فرمت زمان',
'Date format'				=>	'فرمت تاريخ',
'Default'					=>	'پيش فرض',
'Language'					=>	'زبان',
'Email setting info'		=>	'انتخاب كنيد آيا آدرس ايميل شما قابل مشاهده توسط ديگر كاربران باشيد يا خير و همچنين آيا مايل هستيد ديگر كاربران قادر باشند از طريق انجمن ( فرم ايميل ) براي شما ايميل ارسال كنند يا خير.',
'Email setting 1'			=>	'نمايش ايميل شما به کاربران ديگر.',
'Email setting 2'			=>	'عدم نمايش آدرس ايميل ولي اجازه براي ارسال ايميل از طريق انجمن.',
'Email setting 3'			=>	'عدم نمايش آدرس ايميل واجازه ندادن براي ارسال ايميل از طريق انجمن.',
'Privacy options legend'	=>	'گزينه هاي حريم خصوصي خود را تنظيم كنيد',
'Confirm pass'				=>	'تائيد پسورد',

'Username too short'		=>	'نام کاربری باید حداقل بیشتر از 2 کاراکتر باشد . لطفاً نام کاربری (بلندتر) دیگری انتخاب کنید.',
'Username too long'			=>	'نام کاربری نباید بیشتر از 25 کاراکتر باشد . لطفاً نام کاربری (کوتاهتر) دیگری انتخاب کنید.',
'Username guest'			=>	'نام کاربری guest رزرو شده است . لطفاً نام کاربری دیگری انتخاب کنید.',
'Username IP'				=>	'نام کاربری نباید شبیه یک آدرس IP باشد . لطفاً نام کاربری دیگری انتخاب کنید.',
'Username reserved chars'	=>	'نام کاربری نمیتواند شامل کاراکترهای \'، " و ] یا   [ باشد. لطفاً نام کاربری دیگری انتخاب کنید.',
'Username BBCode'			=>	'نام کاربری نباید شامل هر یک از فرمتهای تگ (BBCode) که انجمن از آن استفاده میکند باشد . لطفاً نام کاربری دیگری انتخاب کنید.',
'Banned username'			=>	'نام كاربري كه وارد كرده ايد در اين انجمن مسدود ميباشد . لطفا ً نام كاربري ديگري را انتخاب كنيد.',
'Pass too short'			=>	'پسورد بايد حداقل 6 كاراكتر باشد . لطفا ً پسورد (بلندتر) ديگري را انتخاب كنيد.',
'Pass not match'			=>	'پسورد ها با هم مطابقت ندارند.',
'Banned email'				=>	'آدرس ايميلي كه شما وارد كرده ايد در اين انجمن مسدود ميباشد . لطفا ً آدرس ايميل ديگري را انتخاب كنيد.',
'Dupe email'				=>	'شخص ديگري هم اكنون با اين آدرس ايميل ثبت نام كرده است . لطفا ً آدرس ايميل ديگري را انتخاب كنيد.',
'Sig too long'				=>	'متن امضاء نميتواند بيشتر از %1$s كاراكتر طولاني تر باشد . لطفا ً %2$s كاراكتر از متن امضاء خود كاهش دهيد.',
'Sig too many lines'		=>	'امضاء نيمتواند بيشتر از %s خط داشته باشد.',
'Bad ICQ'					=>	'شما ICQ UIN نامعتبري را وارد كرده ايد . لطفا ً بازگشته و آن را تصحيح كنيد.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Moscow, Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Yekaterinburg',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Krasnoyarsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita, Irkutsk',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Vladivostok',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Magadan',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands, Kamchatka',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
