<?php

/* Translation Notice:
	Copyright Kaeden
   Last revision: 7th of December 2012 */
   

// Language definitions used in admin_users.php
$lang_admin_users = array(

'Non numeric message'		=>	'Ai introdus o valoare non-numerică pentru o coloană numerică.',
'Invalid date time message'	=>	'Ai completat o dată/oră nevalidă.',
'Not verified'				=>	'Neverificat',

// Actions: mass delete/ban etc.
'No users selected'			=>	'Niciun utilizator selectat.',
'No move admins message'	=>	'Din motive de securitate, nu poți muta mai mulți administratori simultan în alt grup. Dacă dorești să muți acești administratori, poți realiza această acțiune vizitând profilurile lor individuale.',
'No delete admins message'	=>	'Administratorii nu pot fi șterși. Pentru a șterge administratori, trebuie întâi să îi muți în alt grup.',
'No ban admins message'		=>	'Administratorii nu pot fi suspendați. Pentru a suspenda administratori, trebuie întâi să îi muți în alt grup.',
'No ban mods message'		=>	'Moderatorii nu pot fi suspendați. Pentru a suspenda moderatori, trebuie întâi să îi muți în alt grup.',
'Move users'				=>	'Schimbă grup',
'Move users subhead'		=>	'Selectează grup nou',
'New group label'			=>	'Grup nou',
'New group help'			=>	'Selectează grupul în care utilizatorii selectați vor fi mutați. Din motive de securitate, nu este posibil să muți mai mulți utilizatori simultan în grupul administratorilor.',
'Invalid group message'		=>	'ID grup nevalid.',
'Users move redirect'		=>	'Grup de utilizator schimbat. Redirecționare …',
'Delete users'				=>	'Ștergere utilizatori',
'Confirm delete legend'		=>	'Important: citește înainte de a șterge utilizatori',
'Confirm delete info'		=>	'Te rugăm să confirmi că dorești ștergerea acestor utilizatori.',
'Delete posts'				=>	'Șterge toate mesajele/subiectele trimise de acești utilizatori.',
'Delete warning'			=>	'Atenție! Ștergerea utilizatorilor și/sau a mesajelor nu poate fi remediată. Dacă alegi să nu ștergi mesajele trimise de acești utilizatori, le vei putea șterge manual la o dată ulterioară.',
'Users delete redirect'		=>	'Utilizatori șterși. Redirecționare …',
'Ban users'					=>	'Suspendare utilizatori',
'Message expiry subhead'	=>	'Motivare suspendare și dată expirare',
'Ban message label'			=>	'Motivare suspendare',
'Ban message help'			=>	'Un mesaj care va fi afișat utilizatorilor suspendați la vizitarea forumului.',
'Expire date label'			=>	'Dată expirare',
'Expire date help'			=>	'Data la care aceste suspendări vor fi ridicate automat (format: aaaa-ll-zz). Lasă necompletat pentru a ridica suspendarea manual.',
'Ban IP label'				=>	'Suspendare adrese IP',
'Ban IP help'				=>	'Suspendă, de asemenea, adresele IP pentru utilizatorii blocați pentru a face reînregistrarea unor conturi mai dificilă pentru ei.',
'Invalid date message'		=>	'Ai introdus o dată de expirare nevalidă.',
'Invalid date reasons'		=>	'Formatul ar trebui să fie AAAA-LL-ZZ și data ar trebui să fie cel puțin o zi în viitor.',
'Users banned redirect'		=>	'Utilizatori suspendați. Redirecționare …',

'User search head'			=>	'Căutare utilizatori',
'User search subhead'		=>	'Completează criteriile de căutare',
'User search info'			=>	'Caută utilizatori în baza de date. Poți completa unul sau mai mulți termeni de căutare. Căutările parțiale sunt admise sub forma înlocuirii termenilor cu asterisk: *.',
'Username label'			=>	'Nume utilizator',
'E-mail address label'		=>	'Adresă e-mail',
'Title label'				=>	'Titlu',
'Real name label'			=>	'Nume real',
'Website label'				=>	'Website',
'Jabber label'				=>	'Jabber',
'ICQ label'					=>	'ICQ',
'MSN label'					=>	'Microsoft Account',
'AOL label'					=>	'AOL IM',
'Yahoo label'				=>	'Yahoo Messenger',
'Location label'			=>	'Locație',
'Signature label'			=>	'Semnătură',
'Admin note label'			=>	'Notă administrativă',
'Posts more than label'		=>	'Număr mesaje mai mare ca',
'Posts less than label'		=>	'Număr mesaje mai mic decât',
'Last post after label'		=>	'Ultimul mesaj trimis după',
'Date help'					=>	'(aaaa-ll-zz hh:mm:ss)',
'Last post before label'	=>	'Ultimul mesaj trimis înainte de',
'Last visit after label'	=>	'Ultima vizită după',
'Last visit before label'	=>	'Ultima vizită înainte de',
'Registered after label'	=>	'Înregistrat după',
'Registered before label'	=>	'Înregistrat înainte de',
'Order by label'			=>	'Ordonează după',
'Order by username'			=>	'Nume utilizator',
'Order by e-mail'			=>	'E-mail',
'Order by posts'			=>	'Număr mesaje',
'Order by last post'		=>	'Ultimul mesaj',
'Order by last visit'		=>	'Ultima vizită',
'Order by registered'		=>	'Dată înregistrare',
'Ascending'					=>	'Ascendent',
'Descending'				=>	'Descendent',
'User group label'			=>	'Grup',
'All groups'				=>	'Toate grupurile',
'Unverified users'			=>	'Utilizatori neverificați',
'Submit search'				=>	'Caută',
'IP search head'			=>	'Căutare IP',
'IP search subhead'			=>	'Completează un IP pentru căutare',
'IP address label'			=>	'Adresă IP',
'IP address help'			=>	'Adresa IP care se va căuta în baza de date.',
'Find IP address'			=>	'Găsește adresă IP',

'Results head'				=>	'Rezultate căutare',
'Results username head'		=>	'Nume utilizator',
'Results e-mail head'		=>	'E-mail',
'Results title head'		=>	'Titlu/Status',
'Results posts head'		=>	'Mesaje',
'Results admin note head'	=>	'Notă Administrativă',
'Results actions head'		=>	'Acțiuni',
'Results IP address head'	=>	'Adresă IP',
'Results last used head'	=>	'Ultima reținută',
'Results times found head'	=>	'Număr identificări',
'Results action head'		=>	'Acțiune',
'Results find more link'	=>	'Găsește mai mulți utilizatori pentru acest IP',
'Results no posts found'	=>	'Momentan nu se găsesc mesaje trimise de acest utilizator în forum.',
'Select'					=>	'Selectează',
'Select all'				=>	'Selectează tot',
'Unselect all'				=>	'Deselectează tot',
'Ban'						=>	'Suspendă',
'Delete'					=>	'Șterge',
'Change group'				=>	'Schimbă grup',
'Bad IP message'			=>	'Adresa IP furnizată nu respectă formatul valid.',
'Results view IP link'		=>	'Vizualizează statistici IP',
'Results show posts link'	=>	'Arată mesaje',
'Results guest'				=>	'Vizitator',
'Results no IP found'		=>	'Adresa IP furnizată nu a putut fi găsită în baza de date.',
'No match'					=>	'Niciun rezultat'

);
