<?php

/* Translation Notice:
	Copyright Kaeden
   Last revision: 7th of December 2012 */
   

// Language definitions used in admin-groups.php
$lang_admin_groups = array(

'Must enter title message'		=>	'Trebuie să completezi un titlu pentru grup.',
'Title already exists message'	=>	'Există deja un grup denumit <strong>%s</strong>.',
'Default group redirect'		=>	'Grup standard stabilit. Redirecționare …',
'Cannot remove default message'	=>	'Grupul standard nu poate fi șters. Pentru a șterge acest grup, trebuie întâi să stabilești un grup standard diferit.',
'Group removed redirect'		=>	'Grup șters. Redirecționare …',
'Group added redirect'			=>	'Grup adăugat. Redirecționare  …',
'Group edited redirect'			=>	'Grup modificat. Redirecționare …',

'Add groups head'				=>	'Adăugare sau Stabilire grupuri',
'New group label'				=>	'Moștenire setări de la',
'Add group subhead'				=>	'Adaugă un nou grup',
'New group help'				=>	'Selectează grupul de la care noul grup va moșteni permisiunile. Următoarea pagină oferă posibilitatea ajustării acestor permisiuni.',
'Default group subhead'			=>	'Stabilește grup standard',
'Default group label'			=>	'Grup standard',
'Default group help'			=>	'Acesta este grupul standard. De exemplu: utilizatorii sunt adăugați acestui grup la înregistrare. Din motive de securitate, utilizatorii nu pot fi repartizați în grupurile de moderatori sau administratori implicit.',
'Existing groups head'			=>	'Grupuri existente',
'Edit groups subhead'			=>	'Modificare sau Ștergere grupuri',
'Edit groups info'				=>	'Grupurile predefinite: Vizitatori (Guests), Administratori (Administrators), Moderatori (Moderators) și Membri (Members) nu pot fi șterse. Cu toate acestea, ele pot fi modificate. Te rugăm să iei aminte că pentru anumite grupuri, unele opțiuni nu sunt disponibile (ex: <em>modificare permisiuni publicare mesaje</em> pentru vizitatori). Administratorii vor avea întotdeauna permisiuni complete.',
'Edit link'						=>	'Modifică',
'Delete link'					=>	'Șterge',
'Group delete head'				=>	'Ștergere grup',
'Confirm delete subhead'		=>	'Confirmă ștergerea grupului',
'Confirm delete info'			=>	'Ești sigur că dorești să ștergi grupul <strong>%s</strong>?',
'Confirm delete warn'			=>	'ATENȚIE! După ștergerea unui grup, acesta nu poate fi restaurat.',
'Delete group head'				=>	'Ștergere grup',
'Move users subhead'			=>	'Mută utilizatorii din grup',
'Move users info'				=>	'Grupul <strong>%s</strong> are momentan <strong>%s</strong> membri. Te rugăm să selectezi grupul în care vor fi mutați acești utilizatori după ștergere.',
'Move users label'				=>	'Mută în',
'Delete group'					=>	'Șterge grup',

'Group settings head'			=>	'Setări grup',
'Group settings subhead'		=>	'Stabilește opțiunile și permisiunile grupului',
'Group settings info'			=>	'Opțiunile și permisiunile situate mai jos sunt cele implicite pentru acest grup. Acestea se aplică dacă nu sunt deja active permisiuni specifice fiecărui forum.',
'Group title label'				=>	'Titlu Grup',
'User title label'				=>	'Titlu Utilizator',
'User title help'				=>	'Acest titlu va suprascrie orice alt titlu un utilizator repartizat acestui grup ar putea deține. Lasă necompletat pentru a folosi titlul standard.',
'User title help'				=>	'The rank users in this group have attained. Leave blank to use default title ("%s").',
'Promote users label'			=>	'Promovare utilizatori',
'Disable promotion'				=>	'Dezactivare Promovare',
'Promote users help'			=>	'Poți promova automat utilizatorii la un nou grup dacă aceștia ating un anumit cumul de mesaje. Selectează "%s" pentru dezactivare. Din motive de securitate, nu poți selecta un grup cu permisiuni de Administrator aici. De asemenea, te rugăm să notezi că schimbarea grupului pentru utilizatorii afectați de această limită se va face la momentul în care cumulul specificat este depășit.',
'Mod privileges label'			=>	'Permite privilegii moderare',
'Mod privileges help'			=>	'Pentru ca un utilizator din acest grup să aibă opțiuni de moderare, acesta trebuie să fie repartizat ca moderator cel puțin unui forum. Poți realiza acest lucru din pagina de editare a profilului individual.',
'Edit profile label'			=>	'Permite moderatorilor să modifice profilurile utilizatorilor',
'Edit profile help'				=>	'Dacă privilegiile de moderare sunt activate, permite utilizatorilor din acest grup să altereze profilurile utilizatorilor.',
'Rename users label'			=>	'Permite moderatorilor să redenumească utilizatori',
'Rename users help'				=>	'Dacă privilegiile de moderare sunt activate, permite utilizatorilor din acest grup să redenumească utilizatorii.',
'Change passwords label'		=>	'Permite moderatorilor să schimbe parole',
'Change passwords help'			=>	'Dacă privilegiile de moderare sunt activare, permite utilizatorilor din acest grup să schimbe parolele utilizatorilor.',
'Ban users label'				=>	'Permite moderatorilor să suspende utilizatori',
'Ban users help'				=>	'Dacă privilegiile de moderare sunt activate, permite utilizatorilor din acest grup să suspende utilizatori.',
'Read board label'				=>	'Acces Forum',
'Read board help'				=>	'Permite utilizatorilor din acest grup să vizualizeze forumurile. Această setare se aplică oricărui aspect al forumului și de aceea nu poate fi suprascrisă de permisiunile individuale fiecărui forum. Stabilită la "Nu", utilizatorii acestui grup vor putea doar să se autentifice, deconecteze și să înregistreze noi conturi.',
'View user info label'			=>	'Vizualizare informații utilizatori',
'View user info help'			=>	'Permite utilizatorilor să vadă lista utilizatorilor și profilurile acestora.',
'Post replies label'			=>	'Publicare mesaje',
'Post replies help'				=>	'Permite utilizatorilor din acest grup să trimită răspunsuri în subiectele de discuție.',
'Post topics label'				=>	'Publicare subiecte de discuție',
'Post topics help'				=>	'Permite utilizatorilor din acest grup să deschidă noi subiecte de discuție.',
'Edit posts label'				=>	'Modificare mesaje',
'Edit posts help'				=>	'Permite utilizatorilor din acest grup să își modifice mesajele.',
'Delete posts label'			=>	'Ștergere răspunsuri',
'Delete posts help'				=>	'Permite utilizatorilor din acest grup să își șteargă răspunsurile.',
'Delete topics label'			=>	'Ștergere subiecte',
'Delete topics help'			=>	'Permite utilizatorilor din acest grup să șteargă subiectele de discuție inițiate (inclusiv orice răspunsuri trimise în acestea).',
'Post links label'				=>	'Publicarea legăturilor (links)',
'Post links help'				=>	'Permite utilizatorilor acestui grup să includă legături în mesajele trimise. Această opțiune se aplică și semnăturilor și câmpul pentru website din profilurile utilizatorilor.',
'Set own title label'			=>	'Stabilire titulatură individuală',
'Set own title help'			=>	'Permite utilizatorilor din acest grup să își stabilească propria titulatură.',
'User search label'				=>	'Folosirea căutării',
'User search help'				=>	'Permite utilizatorilor din acest grup să utilizeze sistemul de căutare.',
'User list search label'		=>	'Căutare listă utilizatori',
'User list search help'			=>	'Permite utilizatorilor din acest grup să caute utilizatori în lista membrilor.',
'Send e-mails label'			=>	'Trimitere e-mail',
'Send e-mails help'				=>	'Permite utilizatorilor acestui grup să trimită mesaje e-mail altor utilizatori.',
'Post flood label'				=>	'Interval așteptare publicare',
'Post flood help'				=>	'Numărul de secunde pe care utilizatorii acestui grup trebuie să îl aștepte între trimiterea mesajelor. Completează 0 pentru dezactivare.',
'Search flood label'			=>	'Interval așteptare căutare',
'Search flood help'				=>	'Numărul de secunde pe care utilizatorii acestui grup trebuie să îl aștepte între căutări. Completează 0 pentru dezactivare.',
'E-mail flood label'			=>	'Interval așteptare trimitere e-mail',
'E-mail flood help'				=>	'Numărul de secunde pe care utilizatorii acestui grup trebuie să îl aștepte între trimiterea de mesaje e-mail. Completează 0 pentru dezactivare.',
'Report flood label'			=>	'Interval așteptare raportări',
'Report flood help'				=>	'Numărul de mesaje pe care utilizatorii acestui grup trebuie să îl aștepte între raportări. Completează 0 pentru dezactivare.',
'Moderator info'				=>	'Te rugăm să reții că pentru privilegiile de moderare, utilizatorii trebuie să fie repartizați ca moderatori cel puțin unui forum. Acest lucru se realizează prin intermediul paginii de editare al profilului utilizatorului în cauză.',

);
