<?php

/* Translation Notice:
	Copyright Kaeden
   Last revision: 8th of May 2012 */
   

// Language definitions used in install.php, localized by adaur

$lang_install = array(

'Choose install language'		=>	'Selectează limba utilizată la instalare',
'Choose install language info'	=>	'Limba folosită de utilitarul de instalare. Limba standard a forumului poate fi stabilită mai jos.',
'Install language'				=>	'Limbă instalare',
'Change language'				=>	'Schimbă limba',
'Next'							=>	'Pasul următor',
'Already installed'				=>	'Se pare că FluxBB este deja instalat. Ar trebui să mergi <a href="index.php">aici</a> în loc.',
'You are running error'			=>	'Utilizezi %1$s versiunea %2$s. FluxBB %3$s necesită cel puțin %1$s %4$s pentru a funcționa corect. Trebuie să actualizezi versiunea %1$s înainte de a putea continua.',
'My FluxBB Forum'				=>	'Forumul meu FluxBB',
'Description'					=>	'Din păcate, nu se poate explica ce reprezintă, de fapt, FluxBB - trebuie să vezi de unul singur.',
'Username 1'					=>	'Numele de utilizator trebuie să conțină cel puțin 2 caractere.',
'Username 2'					=>	'Numele de utilizator nu trebuie să depășească 25 caractere.',
'Username 3'					=>	'Numele de utilizator  guest/vizitator este rezervat.',
'Username 4'					=>	'Numele de utilizator nu trebuie să fie sub formatul unei adrese IP.',
'Username 5'					=>	'Numele de utilizator nu pot conține simultan caracterele \', " și [ sau ].',
'Username 6'					=>	'Numele de utilizator nu pot conține etichetele BBCode utilizate de forum.',
'Short password'				=>	'Parolele trebuie să conțină minim 4 caractere.',
'Passwords not match'			=>	'Parolele nu sunt identice.',
'Wrong email'					=>	'Adresa de e-mail completată pentru administrator este nevalidă.',
'No board title'				=>	'Trebuie să completezi un titlu pentru forum.',
'Error default language'		=>	'Limba standard aleasă nu pare să existe.',
'Error default style'			=>	'Tema grafică standard aleasă nu pare să existe.',
'No DB extensions'				=>	'Această configurație PHP pare să nu aibă suport pentru niciunul dintre tipurile de bază de date utilizate de FluxBB. PHP trebuie să aibă suport fie pentru MySQL, PostgreSQL sau SQLite pentru instalarea FluxBB.',
'Administrator username'		=>	'Nume utilizator Administrator',
'Administrator password 1'		=>	'Parolă Administrator 1',
'Administrator password 2'		=>	'Parolă Administrator 2',
'Administrator email'			=>	'E-mail Administrator',
'Board title'					=>	'Titlu Forum',
'Base URL'						=>	'URL Principal fară slash-ul de final. Acesta trebuie să fie corect pentru ca forumul să funcționeze',
'Required field'				=>	'este un câmp obligatoriu.',
'FluxBB Installation'			=>	'Instalare FluxBB',
'Welcome'						=>	'Ești pe cale să instalezi FluxBB. Pentru a realiza instalarea, trebuie să completezi grupul de formulare situat inferior. Dacă întâmpini dificultăți cu instalarea, te rugăm să consulți documentația.',
'Install'						=>	'Instalare FluxBB %s',
'Errors'						=>	'Următoarele erori trebuie corectate:',
'Database setup'				=>	'Configurare Bază Date',
'Info 1'						=>	'Toate infomațiile necesare pentru conexiunea la baza de date.',
'Select database'				=>	'Selectează tipul bazei de date',
'Info 2'						=>	'Tipul bazei de date. FluxBB poate fi instalat cu SQLite, MySQL sau PostgreSQL.',
'Database type'					=>	'Tip bază date',
'Required'						=>	'(Necesar)',
'Database hostname'				=>	'Completează numele serverului bazei de date',
'Info 3'						=>	'Adresa serverului bazei de date (exemple: localhost, db.myhost.com sau 192.168.0.15).',
'Database server hostname'		=>  'Nume bază date',
'Database enter name'			=>	'Completează numele bazei tale de date',
'Info 4'						=>	'Numele bazei de date pe care va instalat FluxBB.',
'Database name'					=>	'Nume bază date',
'Database enter informations'	=>	'Completează utilizatorul și parola bazei de date',
'Database username'				=>	'Nume utilizator bază date',
'Info 5'						=>	'Completează utilizatorul și parola cu care dorești să te conectezi la baza de date. Ignoră câmpurile pentru SQLite.',
'Database password'				=>	'Parolă bază date',
'Database enter prefix'			=>	'Completează prefix tabele',
'Info 6'						=>	'Dacă dorești, poți specifica un prefix pentru tabele. În acest mod, poți rula simultan mai multe copii FluxBB pe o bază de date (exemplu: foo_).',
'Table prefix'					=>	'Prefix tabele',
'Administration setup'			=>	'Configurare Administrare',
'Info 7'						=>	'Te rugăm să completezi informațiile solicitate pentru a stabili un administrator al forumului tău FluxBB.',
'Info 8'						=>	'Numele de utilizator trebuie să conțină între 2 și 25 de caractere. Parola trebuie să conțină cel puțin 4 caractere. Parolele sunt sensibile la diferența dintre (M)ajuscule și (m)inuscule.',
'Password'						=>	'Parolă',
'Confirm password'				=>	'Confirmare parolă',
'Admin enter email'				=>	'Completează e-mail-ul Administratorului',
'Info 10'						=>	'Adresa e-mail a administratorului forumului.',
'Board setup'					=>	'Configurare Forum',
'Info 11'						=>	'Configurare forum. Poți modifica opțiunile ulterior.',
'General information'			=>	'Completează numele și descrierea forumului tău.',
'Board description'				=>	'Descriere forum(poți utiliza HTML)',
'Appearance'					=>	'Aspect',
'Info 15'						=>	'Personalizează-ți forumul. Alege limba și aspectul grafic.',
'Default language'				=>	'Limbă standard',
'Default style'					=>	'Temă grafică standard',
'Start install'					=>	'Începe instalarea',
'DB type not valid'				=>	'\'%s\' nu este un tip de bază de date valid',
'Table prefix error'			=>	'Prefixul \'%s\' conține caractere nepermise sau este prea lung. Prefixul poate conține toate literele de la a la z, oricare cifre și caracterul underscore. Cu toate acestea, prefixul nu poate începe cu cifre. Lungimea maximă a unui prefix este de 40 caractere. Te rugăm să alegi un alt prefix.',
'Prefix reserved'				=>	'Prefixul \'sqlite_\' este rezervat suportului SQLite. Te rugăm să alegi un alt prefix.',
'Existing table error'			=>	'O tabelă denumită \'%susers\' este deja prezentă în baza de date \'%s\'. Aceasta ar putea însemna că FluxBB este deja instalat sau un alt software este instalat și ocupă cel puțin un tabel cu un nume similar utilizat de FluxBB. Dacă dorești să instalezi mai multe copii FluxBB pe aceeași bază de date, trebuie să alegi un prefix diferit.',
'InnoDB off'					=>	'InnoDB nu pare să fie activat. Te rugăm să alegi un alt tip de tabelă care nu are suportul InnoDB, sau să activezi InnoDB pe serverul tău MySQL.',
'Administrators'				=>	'Administratori',
'Administrator'					=>	'Administrator',
'Moderators'					=>	'Moderatori',
'Moderator'						=>	'Moderator',
'Guests'						=>	'Vizitatori',
'Guest'							=>	'Vizitator',
'Members'						=>	'Membri',
'Announcement'					=>	'Completează anunțul tău aici.',
'Rules'							=>	'Completează regulile tale aici.',
'Maintenance message'			=>	'Forumul este închis temporar pentru întreținere. Te rugăm să revii în câteva minute.',
'Test post'						=>	'Subiect de test',
'Message'						=>	'Dacă parcurgi acest text (ceea ce presupun că faci), instalarea copiei tale FluxBB pare că a funcționat! Acum autentifică-te și îndreaptă-te înspre panoul de administrare pentru a configura forumul tău.',
'Test category'					=>	'Categorie de test',
'Test forum'					=>	'Forum de test',
'This is just a test forum'		=>	'Acesta este doar un forum de test',
'Alert cache'					=>	'<strong>Directorul cache nu poate fi momentan suprascris!</strong> Pentru ca FluxBB să poată funcționa optim, directorul <em>%s</em> trebuie să poată fi suprascris de PHP. Folosește setările CHMOD potrivite pentru permisiunile directorului. Dacă ești în dubiu, utilizează chmod 0777.',
'Alert avatar'					=>	'<strong>Directorul de avatare nu poate fi momentan suprascris!</strong> Dacă dorești ca utilizatorii să își poată încărca propriile imagini, trebuie să te asiguri că directorul <em>%s</em> poate fi suprascris de PHP. Poți alege ulterior să salvezi avatarele într-un director diferit (vezi Admin/Opțiuni). Folosește setările CHMOD potrivite pentru permisiunile directorului. Dacă ești în dubiu, utilizează chmod 0777.',
'Alert upload'					=>	'<strong>Încărcarea fișierelor pare să fie dezactivată pe acest server!</strong> Dacă dorești ca utilizatorii să își poată încărca propriile avatare trebuie să activezi opțiunea file_uploads din configurația PHP. Odată ce directiva este activată, încărcarea avatarelor poate fi pornită în Administrare/Opțiuni.',
'FluxBB has been installed'		=>	'FluxBB a fost instalat. Pentru a finaliza instalarea, te rugăm să urmezi instrucțiunile de mai jos.',
'Final instructions'			=>	'Instrucțiuni finale',
'Info 17'						=>	'Pentru încheierea instalării, trebuie să dai click pe butonul de dedesubt pentru a descărca un fișier numit config.php. Va trebui să încarci acest fișier în directorul principal al copiei tale FluxBB.',
'Info 18'						=>	'Odată ce ai încărcat config.php, FluxBB va fi instalat complet! În acel moment, poți <a href="index.php">naviga la pagina principală</a>.',
'Download config.php file'		=>	'Descarcă fișierul config.php',
'FluxBB fully installed'		=>	'FluxBB a fost instalat cu succes! Poți <a href="index.php">naviga la pagina principală</a>.',

);
