<?php

/* Translation Notice:
	Copyright Kaeden
   Last revision: 25th of February 2012 */
   

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Completează o adresă e-mail validă',
'Email legend 2'			=>	'Completează și confirmă o adresă e-mail validă',
'Localisation legend'		=>	'Stabilește opțiunile de localizare',
'Time zone'					=>	'Fus orar',
'Time zone info'			=>	'Pentru ca forumul să afișeze timpul corect trebuie să selectezi fusul tău orar. Dacă momentan este stabilită Ora de Vară, ar trebui să marchezi acest lucru prin opțiunea pusă la dispoziție, care va devansa ceasul cu o oră.',
'DST'						=>	'Ora de Vară este activă (devansare cu 1 oră).',
'Time format'				=>	'Format timp',
'Date format'				=>	'Format dată',
'Default'					=>	'Standard',
'Language'					=>	'Limbă',
'Email setting info'		=>	'Alege dacă dorești ca adresa ta de e-mail să fie vizibilă pentru ceilalți utilizatori sau nu și dacă dorești ca ceilalți utilizatori să îți poată trimite mesaje e-mail din forum (formular e-mail) sau nu.',
'Email setting 1'			=>	'Afișează adresa e-mail.',
'Email setting 2'			=>	'Ascunde adresa e-mail, dar permite trimiterea de mesaje prin formularul e-mail.',
'Email setting 3'			=>	'Ascunde adresa e-mail și dezactivează trimiterea de mesaje prin formularul e-mail.',
'Privacy options legend'	=>	'Stabilește setările de intimitate',
'Confirm pass'				=>	'Confirmă parola',

'Username too short'		=>	'Numele de utilizator trebuie să conțină cel puțin 2 caractere. Te rugăm să alegi un alt nume de utilizator.',
'Username too long'			=>	'Numele de utilizator nu trebuie să conțină mai mult de 25 caractere. Te rugăm să alegi un alt nume de utilizator.',
'Username guest'			=>	'Numele de utilizator guest/vizitator este rezervat. Te rugăm să alegi un alt nume de utilizator.',
'Username IP'				=>	'Numele de utilizator nu trebuie să fie de formatul unei adrese IP. Te rugăm să alegi un alt nume de utilizator.',
'Username reserved chars'	=>	'Numele de utilizator nu trebuie să conțină simultan caracterele \', " și [ or ]. Te rugăm să alegi un alt nume de utilizator.',
'Username BBCode'			=>	'Numele de utillizator nu trebuie să conțină BBCode utilizat de forum. Te rugăm să alegi un alt nume de utilizator.',
'Banned username'			=>	'Numele de utilizator introdus este interzis de acest forum. Te rugăm să alegi un alt nume de utilizator.',
'Pass too short'			=>	'Parolele trebuie să conțină minim 4 caractere. Te rugăm să alegi o altă parolă.',
'Pass not match'			=>	'Parolele nu se potrivesc.',
'Banned email'				=>	'Adresa de e-mail introdusă este interzisă de acest forum. Te rugăm să alegi o alta adresă de e-mail.',
'Dupe email'				=>	'Această adresă de e-mail este deja utilizată. Te rugăm să alegi o altă adresă de e-mail.',
'Sig too long'				=>	'Semnăturile nu pot conține mai mult de  %1$s caractere. Te rugăm să elimini %2$s caractere din semnătura ta.',
'Sig too many lines'		=>	'Semnăturile nu pot avea mai mult de %s linii.',
'Bad ICQ'					=>	'Ai completat un ICQ UIN nevalid. Te rugăm să corectezi această eroare.',

'UTC-12:00'					=>	'(UTC-12:00) Linia Temporală Internațională de Vest',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Insula Cook',
'UTC-09:30'					=>	'(UTC-09:30) Insulele Marcheze',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Insula Gambier',
'UTC-08:30'					=>	'(UTC-08:30) Insulele Pitcairn',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Montan',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Estic',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Groenlanda Centrală',
'UTC-02:00'					=>	'(UTC-02:00) Atlanticul Central',
'UTC-01:00'					=>	'(UTC-01:00) Azore, Capul Verde, Groenlanda Estică',
'UTC'						=>	'(UTC) Vest-European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central-European, Vest-African',
'UTC+02:00'					=>	'(UTC+02:00) Est-European, Central-African',
'UTC+03:00'					=>	'(UTC+03:00) Est-African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Moscova, Golf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladeș, Bhutan, Yekaterinburg',
'UTC+06:30'					=>	'(UTC+06:30) Insulele Cocos, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'					=>	'(UTC+08:00) Marea Chină, Vestul Australian, Krasnoyarsk',
'UTC+08:45'					=>	'(UTC+08:45) Vestul Sud-Estic Australian',
'UTC+09:00'					=>	'(UTC+09:00) Japonia, Coreea, Chita, Irkutsk',
'UTC+09:30'					=>	'(UTC+09:30) Central-Australian',
'UTC+10:00'					=>	'(UTC+10:00) Est-Australian',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Insula Solomon, Vladivostok',
'UTC+11:30'					=>	'(UTC+11:30) Insula Norfolk',
'UTC+12:00'					=>	'(UTC+12:00) Noua Zeelandă, Fiji, Magadan',
'UTC+12:45'					=>	'(UTC+12:45) Insulele Chatham',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Insulele Phoenix, Kamchatka',
'UTC+14:00'					=>	'(UTC+14:00) Insulele Line'

);
