<?php

// Language definitions used in admin-groups.php
$lang_admin_groups = array(

'Must enter title message'		=>	'您必須輸入會員群組名稱。',
'Title already exists message'	=>	'會員群組名稱 <strong>%s</strong> 已經存在。',
'Default group redirect'		=>	'預設會員群組設定成功。重新導向中 …',
'Cannot remove default message'	=>	'預設會員群組無法刪除。要刪除這個會員群組，您必須先設定其他會員群組為預設會員群組。',
'Group removed redirect'		=>	'會員群組移除成功。重新導向中 …',
'Group added redirect'			=>	'會員群組增加成功。重新導向中 …',
'Group edited redirect'			=>	'會員群組編輯成功。重新導向中 …',

'Add groups head'				=>	'增加/設定會員群組',
'Add group subhead'				=>	'增加新的會員群組',
'New group label'				=>	'新的會員群組基於',
'New group help'				=>	'選擇一個會員群組作為新會員群組權限設定繼承的參考。下一頁將讓您對其權限進行微調。',
'Default group subhead'			=>	'設定預設會員群組',
'Default group label'			=>	'預設會員群組',
'Default group help'			=>	'預設會員群組是訪客註冊時將會歸入的會員群組。出於安全考慮，不能將版主(moderator)或管理員(administrator)設定為預設會員群組。',
'Existing groups head'			=>	'現有會員群組',
'Edit groups subhead'			=>	'編輯/刪除會員群組',
'Edit groups info'				=>	'預設的會員群組包括訪客(Guests)，管理員(Administrators)，版主(Moderators)以及一般會員(Members)不允許移除。但是允許您編輯他們的權限。雖然如此，但請注意某些會員群組中有些權限選項是停用的(例如訪客(Guests)群組中的<em>編輯文章</em>權限)。管理員群組總是擁有全權。',
'Edit link'						=>	'編輯',
'Delete link'					=>	'刪除',
'Group delete head'				=>	'刪除會員群組',
'Confirm delete subhead'		=>	'確認刪除會員群組',
'Confirm delete info'			=>	'您確定要刪除會員群組 <strong>%s</strong> 嗎？',
'Confirm delete warn'			=>	'警告！會員群組刪除後將不可恢復。',
'Delete group head'				=>	'刪除會員群組',
'Move users subhead'			=>	'轉移目前會員到會員群組',
'Move users info'				=>	'會員群組 <strong>%s</strong> 目前有 <strong>%s</strong> 位會員。刪除時請為這些會員選擇一個會員群組。',
'Move users label'				=>	'轉移會員至',
'Delete group'					=>	'刪除會員群組',

'Group settings head'			=>	'會員群組設定',
'Group settings subhead'		=>	'設定會員群組選項及權限',
'Group settings info'			=>	'下列選項和權限是會員群組的預設值。各版面的具體權限設定不與此處衝突時，這些設定才會生效。',
'Group title label'				=>	'會員群組頭銜',
'User title label'				=>	'會員頭銜',
'User title help'				=>	'頭銜會取代群組成員的所有等級名稱。如果您要使用預設的頭銜或使用等級名稱，請在此處留空。',
'Mod privileges label'			=>	'允許行使版主權限',
'Mod privileges help'			=>	'要允許某會員行使版主權限，您必須指派他/她為一個或多個版面的版主。這項設定在這位會員的個人資料欄下的管理頁面中。',
'Edit profile label'			=>	'允許版主編輯會員的個人資料',
'Edit profile help'				=>	'如果已開啟群組的版主權限，這項設定將允許群組成員編輯其他會員的個人資料。',
'Rename users label'			=>	'允許版主編輯會員的會員名稱',
'Rename users help'				=>	'如果已開啟群組的版主權限，這項設定將允許群組成員修改其他會員的會員名稱。',
'Change passwords label'		=>	'允許版主變更會員的密碼',
'Change passwords help'			=>	'如果已開啟群組的版主權限，這項設定將允許群組成員修改其他會員的登入密碼。',
'Ban users label'				=>	'允許版主封鎖會員',
'Ban users help'				=>	'如果已開啟群組的版主權限，這項設定將允許群組成員封鎖其他會員。',
'Read board label'				=>	'閱讀論壇',
'Read board help'				=>	'允許群組會員閱讀論壇文章。這項設定將影響論壇的所有版面，即使特定的版面設定為允許閱讀權限也不能覆蓋此處的封鎖閱讀論壇權限。當此處設定為「否」時，群組會員將只能使用論壇的登入/登出或者註冊功能。',
'View user info label'			=>	'檢視會員資訊',
'View user info help'			=>	'允許群組會員檢視會員列表及其他會員個人資料。',
'Post replies label'			=>	'發表回覆',
'Post replies help'				=>	'允許群組會員在主題下發表回覆。',
'Post topics label'				=>	'發表主題',
'Post topics help'				=>	'允許群組會員發表新主題。',
'Edit posts label'				=>	'編輯文章',
'Edit posts help'				=>	'允許群組會員編輯自己發表的文章。',
'Delete posts label'			=>	'刪除文章',
'Delete posts help'				=>	'允許群組會員刪除自己發表的文章。',
'Delete topics label'			=>	'刪除主題',
'Delete topics help'			=>	'允許群組會員刪除自己發表的主題(包括主題下的所有回覆)。',
'Set own title label'			=>	'自訂頭銜',
'Set own title help'			=>	'允許群組會員自訂個性的頭銜。',
'User search label'				=>	'使用搜尋',
'User search help'				=>	'允許群組會員使用搜尋功能。',
'User list search label'		=>	'搜尋會員列表',
'User list search help'			=>	'允許群組會員在會員列表中使用文字搜尋功能搜尋會員名稱。',
'Send e-mails label'			=>	'發送電子郵件',
'Send e-mails help'				=>	'允許群組會員向其他會員發送電子郵件。',
'Post flood label'				=>	'發文間隔時間',
'Post flood help'				=>	'群組會員兩次發文間必須間隔的秒數。停用請輸入0。',
'Search flood label'			=>	'搜尋間隔時間',
'Search flood help'				=>	'群組會員兩次搜尋間必須間隔的秒數。停用請輸入0。',
'E-mail flood label'			=>	'郵件發送間隔時間',
'E-mail flood help'				=>	'群組會員兩次發送電子郵件間必須間隔的秒數。停用請輸入0。',
'Report flood label'			=>	'舉報間隔時間',
'Report flood help'				=>	'群組會員兩次舉報操作間必須間隔的秒數。停用請輸入0。',
'Moderator info'				=>	'特別提醒您要允許群組的某會員行使版主權限，您必須指派他/她為一個或多個版面的版主。這項設定在這位會員的個人資料欄下的管理頁面中。',

);
