<?php

// Language definitions used in admin-groups.php
$lang_admin_groups = array(

'Must enter title message'		=>	'您必須填寫一個用戶組名。',
'Title already exists message'	=>	'用戶組名 <strong>%s</strong> 已經存在。',
'Default group redirect'		=>	'默認用戶組設置成功。正在跳轉 …',
'Cannot remove default message'	=>	'默認用戶組無法刪除。要想刪除該用戶組，您必須首先設置其他用戶組為默認用戶組。',
'Group removed redirect'		=>	'用戶組移除成功。正在跳轉 …',
'Group added redirect'			=>	'用戶組添加成功。正在跳轉 …',
'Group edited redirect'			=>	'用戶組編輯成功。正在跳轉 …',

'Add groups head'				=>	'添加/設置用戶組',
'Add group subhead'				=>	'添加新用戶組',
'New group label'				=>	'新用戶組基於',
'New group help'				=>	'選擇一個用戶組作為新用戶組權限設置的參考。下一頁將要您對其參考權限進行微調。',
'Default group subhead'			=>	'設置默認用戶組',
'Default group label'			=>	'默認用戶組',
'Default group help'			=>	'默認用戶組是新用戶註冊時將會歸入的用戶組。出於安全考慮，不能將版主(moderator)或管理員(administrator)設置為默認用戶組。',
'Existing groups head'			=>	'現有用戶組',
'Edit groups subhead'			=>	'編輯/刪除用戶組',
'Edit groups info'				=>	'內置的用戶組包括訪客(Guests)，管理員(Administrators)，版主(Moderators)以及會員(Members)不允許移除。但是允許您編輯他們的權限。雖然如此，但請注意某些用戶組中有些權限選項是不可用的（例如訪客(Guests)組中的<em>編輯帖子</em>權限）。管理員組總是擁有全權。',
'Edit link'						=>	'編輯',
'Delete link'					=>	'刪除',
'Group delete head'				=>	'刪除用戶組',
'Confirm delete subhead'		=>	'確認刪除用戶組',
'Confirm delete info'			=>	'您確信要刪除用戶組 <strong>%s</strong> 嗎？',
'Confirm delete warn'			=>	'警告！用戶組刪除後將不可恢復。',
'Delete group head'				=>	'刪除用戶組',
'Move users subhead'			=>	'轉移當前用戶到用戶組',
'Move users info'				=>	'用戶組 <strong>%s</strong> 當前有 <strong>%s</strong> 位成員。刪除時請為這些成員選擇分配一個用戶組。',
'Move users label'				=>	'轉移用戶至',
'Delete group'					=>	'刪除用戶組',

'Group settings head'			=>	'用戶組設置',
'Group settings subhead'		=>	'設置用戶組選項及權限',
'Group settings info'			=>	'下列選項和權限是該用戶組的默認設置值。各版塊的具體權限設置不與此處衝突時，這些設置才會生效。',
'Group title label'				=>	'用戶組名',
'User title label'				=>	'用戶頭銜',
'User title help'				=>	'這個頭銜會取代該組成員的所有級別名稱。如果您要使用默認的頭銜或使用級別名稱，請在此處留空。',
'Mod privileges label'			=>	'允許行使版主權限',
'Mod privileges help'			=>	'要允許某用戶行使版主權限，您必須分配他/她為一個或多個版塊的版主。該設置在該用戶的個人資料欄下的管理頁面中。',
'Edit profile label'			=>	'允許版主編輯用戶的個人資料',
'Edit profile help'				=>	'如果已開啟該組的版主權限，該設置將允許該組成員編輯其他用戶的個人資料。',
'Rename users label'			=>	'允許版主編輯用戶的用戶名',
'Rename users help'				=>	'如果已開啟該組的版主權限，該設置將允許該組成員修改其他用戶的用戶名。',
'Change passwords label'		=>	'允許版主變更用戶的密碼',
'Change passwords help'			=>	'如果已開啟該組的版主權限，該設置將允許該組成員修改其他用戶的登錄密碼。',
'Ban users label'				=>	'允許版主封禁用戶',
'Ban users help'				=>	'如果已開啟該組的版主權限，該設置將允許該組成員封禁其他用戶。',
'Read board label'				=>	'閱讀論壇',
'Read board help'				=>	'允許該組用戶閱讀論壇帖子。該設置將影響論壇的所有版塊，即使特定的版塊設置為允許閱讀權限也不能覆蓋此處的禁止閱讀論壇權限。當此處設置為「否」時，該組用戶將只能使用論壇的登錄/註銷或者註冊功能。',
'View user info label'			=>	'查看用戶信息',
'View user info help'			=>	'允許該組用戶查看用戶列表及其他用戶個人資料。',
'Post replies label'			=>	'發表回復',
'Post replies help'				=>	'允許該組用戶在主題下發表回復。',
'Post topics label'				=>	'發表主題',
'Post topics help'				=>	'允許該組用戶發表新主題。',
'Edit posts label'				=>	'編輯帖子',
'Edit posts help'				=>	'允許該組用戶編輯自己發表的帖子。',
'Delete posts label'			=>	'刪除帖子',
'Delete posts help'				=>	'允許該組用戶刪除自己發表的帖子。',
'Delete topics label'			=>	'刪除主題',
'Delete topics help'			=>	'允許該組用戶刪除自己發表的主題（包括主題下的所有回復）。',
'Set own title label'			=>	'自定義頭銜',
'Set own title help'			=>	'允許該組用戶自定義個性的頭銜。',
'User search label'				=>	'使用搜索',
'User search help'				=>	'允許該組用戶使用搜索功能。',
'User list search label'		=>	'搜索用戶列表',
'User list search help'			=>	'允許該組用戶在用戶列表中使用文本搜索功能搜索用戶名。',
'Send e-mails label'			=>	'發送電子郵件',
'Send e-mails help'				=>	'允許該組用戶向其他用戶發送電子郵件。',
'Post flood label'				=>	'發帖間隔時間',
'Post flood help'				=>	'該組用戶兩次發帖間必須間隔的秒數。禁用請填寫0。',
'Search flood label'			=>	'搜索間隔時間',
'Search flood help'				=>	'該組用戶兩次搜索間必須間隔的秒數。禁用請填寫0。',
'E-mail flood label'			=>	'郵件發送間隔時間',
'E-mail flood help'				=>	'該組用戶兩次發送電子郵件間必須間隔的秒數。禁用請填寫0。',
'Moderator info'				=>	'特別提醒您要允許該組的某用戶行使版主權限，您必須分配他/她為一個或多個版塊的版主。該設置在該用戶的個人資料欄下的管理頁面中。',

);
