<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'系統 \'allow_url_fopen\' 停用導致無法檢查升級。',
'Upgrade check failed message'		=>	'未知原因導致升級檢查失敗。',
'Running latest version message'	=>	'您使用的是FluxBB的最新版本。',
'New version available message'		=>	'已經有新的FluxBB版本發佈。您可在 %s 下載。',
'PHPinfo disabled message'			=>	'伺服器停用PHP函數 phpinfo()。',
'Not available'						=>	'停用',
'Forum admin head'					=>	'論壇管理設定',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'歡迎來到 FluxBB 論壇管理設定面板。在這裡您可以控制整個論壇的重要設定。以下功能的可用性將取決於您是論壇管理員還是版主：',
'Welcome 1'							=>	'組織版面及分區。',
'Welcome 2'							=>	'設定論壇開放度的選項及偏好設定。',
'Welcome 3'							=>	'設定會員及訪客的各項權限。',
'Welcome 4'							=>	'檢視使用者的 IP 統計資訊。',
'Welcome 5'							=>	'封鎖惡意的使用者。',
'Welcome 6'							=>	'過濾敏感詞彙。',
'Welcome 7'							=>	'自訂會員的等級。',
'Welcome 8'							=>	'清理舊文章。',
'Welcome 9'							=>	'處理舉報訊息。',
'Statistics head'					=>	'統計',
'FluxBB version label'				=>	'FluxBB版本',
'Check for upgrade'					=>	'檢查升級',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'伺服器負荷',
'Server load data'					=>	'%s - 目前有 %s 人在線上',
'Environment label'					=>	'環境',
'Environment data OS'				=>	'作業系統： %s',
'Show info'							=>	'顯示詳細資訊',
'Environment data version'			=>	'PHP： %s - %s',
'Environment data acc'				=>	'加速器(Accelerator)： %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'資料庫',
'Database data rows'				=>	'列: %s',
'Database data size'				=>	'大小: %s',

);
