<?php

$lang_admin_categories = array (
  'Must enter name message' => '您必須輸入一個名稱的類別',
  'Category added redirect' => '刪除分類。重定向... ',
  'Category deleted redirect' => '分類已刪除。重定向... ',
  'Delete category head' => '刪除類別（連同所有論壇和帖子包含） ',
  'Confirm delete subhead' => '確認刪除類別',
  'Confirm delete info' => '你確定要刪除該類別<strong>%s？</strong> ',
  'Delete category warn' => ' <strong>警告：</strong>刪除一個類別將刪除所有論壇和文章（如果有）在這個類別！ ',
  'Must enter integer message' => '位置必須是一個正整數。 ',
  'Categories updated redirect' => '分類更新。重定向... ',
  'Add categories head' => '新增類別',
  'Add categories subhead' => '新增類別',
  'Add category label' => '添加一個新的類別',
  'Add new submit' => '添加新',
  'Add category help' => '新的名稱要添加類別。您可以編輯該類別的名稱後（見下文）。到%s至論壇添加到您的新類別。 ',
  'Delete categories head' => '刪除類別',
  'Delete categories subhead' => '刪除類別',
  'Delete category label' => '刪除類別',
  'Delete category help' => '選擇該類別的名稱，你想刪除。你會被要求確認您所選擇的類別為刪除之前被刪除。 ',
  'Edit categories head' => '編輯類別',
  'Edit categories subhead' => '編輯類別',
  'Category position label' => '位置',
  'Category name label' => '名稱',
);