<?php

// Language definitions used in admin-users.php
$lang_admin_users = array(

'Non numeric message'		=>	'您在一個僅接受數值的列中填寫了非數值字符。',
'Invalid date time message'	=>	'日期/時間格式不正確。',
'Not verified'				=>	'未驗證',

// Actions: mass delete/ban etc.
'No users selected'			=>	'未選擇用戶。',
'No move admins message'	=>	'出於安全原因，不允許移動多位管理員到另一個組。如果您確實需要移動這些管理員，請前往他們各自的用戶資料頁面移動。',
'No delete admins message'	=>	'管理員不能被刪除。如果您需要刪除管理員，您必須先將其移動到另一個組。',
'No ban admins message'		=>	'管理員不能被阻止。如果您需要阻止管理員，您必須先將其移動到另一個組。',
'No ban mods message'		=>	'版主不能被阻止。如果您需要阻止版主，您必須先將其移動到另一個組。',
'Move users'				=>	'更改用戶組',
'Move users subhead'		=>	'選擇新的用戶組',
'New group label'			=>	'新的用戶組',
'New group help'			=>	'為所選的用戶選擇將要移往的用戶組。出於安全原因，不允許同時將多位用戶移動到管理員組。',
'Invalid group message'		=>	'無效的組名。',
'Users move redirect'		=>	'用戶組已更改。正在跳轉 …',
'Delete users'				=>	'刪除用戶',
'Confirm delete legend'		=>	'重要：刪除用戶前請仔細閱讀',
'Confirm delete info'		=>	'請確認您準備刪除這些用戶。',
'Delete posts'				=>	'刪除這些用戶所發表的所有主題和帖子。',
'Delete warning'			=>	'警告！刪除用戶和/或帖子將無法恢復。如果您選擇了不刪除這些用戶所發表的帖子，這些帖子以後將只能被手動刪除。',
'Users delete redirect'		=>	'用戶已刪除。正在跳轉 …',
'Ban users'					=>	'阻止用戶',
'Message expiry subhead'	=>	'阻止說明及撤銷',
'Ban message label'			=>	'阻止說明',
'Ban message help'			=>	'當被阻止的用戶來訪時將會看到的一條信息。',
'Expire date label'			=>	'撤銷日期',
'Expire date help'			=>	'阻止操作自動撤銷的日期 (格式: yyyy-mm-dd)。留空則需要手動撤銷。',
'Ban IP label'				=>	'阻止IP地址',
'Ban IP help'				=>	'同時阻止被阻止用戶所使用的IP地址以防止他們註冊新賬戶。',
'Invalid date message'		=>	'您填寫了一個無效的撤銷日期。',
'Invalid date reasons'		=>	'日期的格式是 YYYY-MM-DD 並且必須設為至少一天後的未來。',
'Users banned redirect'		=>	'用戶已阻止。正在跳轉 …',

'User search head'			=>	'用戶搜索',
'User search subhead'		=>	'填寫搜索條件',
'User search info'			=>	'在數據庫中搜索用戶。您可填寫一個或多個條件進行搜索。搜索條件中允許使用通配符 * 模糊匹配。',
'Username label'			=>	'用戶名',
'E-mail address label'		=>	'電子信箱地址',
'Title label'				=>	'頭銜',
'Real name label'			=>	'真實姓名',
'Website label'				=>	'個人網站',
'Jabber label'				=>	'Jabber',
'ICQ label'					=>	'ICQ',
'MSN label'					=>	'MSN Messenger',
'AOL label'					=>	'AOL IM',
'Yahoo label'				=>	'Yahoo Messenger',
'Location label'			=>	'所在地',
'Signature label'			=>	'簽名',
'Admin note label'			=>	'管理員注',
'Posts more than label'		=>	'發帖數大於',
'Posts less than label'		=>	'發帖數小於',
'Last post after label'		=>	'最新帖子晚於',
'Date help'					=>	'(yyyy-mm-dd hh:mm:ss)',
'Last post before label'	=>	'最新帖子早於',
'Registered after label'	=>	'註冊時間晚於',
'Registered before label'	=>	'註冊時間早於',
'Order by label'			=>	'排列依據',
'Order by username'			=>	'用戶名',
'Order by e-mail'			=>	'電子信箱',
'Order by posts'			=>	'發帖數',
'Order by last post'		=>	'最後發表',
'Order by registered'		=>	'註冊時間',
'Ascending'					=>	'升序',
'Descending'				=>	'降序',
'User group label'			=>	'用戶組',
'All groups'				=>	'所有組',
'Unverified users'			=>	'未驗證用戶',
'Submit search'				=>	'提交搜索',
'IP search head'			=>	'IP搜索',
'IP search subhead'			=>	'填寫IP進行搜索',
'IP address label'			=>	'IP地址',
'IP address help'			=>	'在發帖數據庫中搜索IP地址。',
'Find IP address'			=>	'查找IP地址',

'Results head'				=>	'搜索結果',
'Results username head'		=>	'用戶名',
'Results e-mail head'		=>	'電子信箱',
'Results title head'		=>	'頭銜/身份',
'Results posts head'		=>	'發帖',
'Results admin note head'	=>	'管理員注',
'Results actions head'		=>	'操作',
'Results IP address head'	=>	'IP地址',
'Results last used head'	=>	'最後使用',
'Results times found head'	=>	'發現次數',
'Results action head'		=>	'操作',
'Results find more link'	=>	'查找該IP的更多用戶',
'Results no posts found'	=>	'當前該版塊尚無該用戶的帖子。',
'Select'					=>	'選擇',
'Select all'				=>	'全選',
'Unselect all'				=>	'全不選',
'Ban'						=>	'阻止',
'Delete'					=>	'刪除',
'Change group'				=>	'更改用戶組',
'Bad IP message'			=>	'所提供的IP地址格式不正確。',
'Results view IP link'		=>	'查看IP統計信息',
'Results show posts link'	=>	'顯示帖子',
'Results guest'				=>	'訪客',
'Results no IP found'		=>	'數據庫中找不到所提供的IP地址。',
'No match'					=>	'無匹配項'

);
