<?php

$lang_admin_common = array (
  'Admin menu' => '管理菜單',
  'Plugins menu' => ' Plugins菜單',
  'Moderator menu' => '主持人菜單',
  'Index' => '指數',
  'Categories' => '分類',
  'Forums' => '論壇',
  'Users' => '用戶',
  'User groups' => '用戶組',
  'Options' => '選項',
  'Permissions' => '權限',
  'Censoring' => '截',
  'Ranks' => '隊伍建設',
  'Bans' => '禁令',
  'Prune' => '修剪',
  'Maintenance' => '維護',
  'Reports' => '報告',
  'Admin' => '管理',
  'Go back' => '回去',
  'Delete' => '刪除',
  'Update' => '更新',
  'Add' => '新增',
  'Edit' => '編輯',
  'Remove' => '刪除',
  'Yes' => '是的',
  'No' => '無',
  'Save changes' => '保存更改',
  'Save' => '保存',
  'here' => '這裡',
  'Action' => '行動',
  'None' => '無',
  'Maintenance mode' => '維護模式',
  'No plugin message' => '沒有所謂的%s個插件插件目錄。 ',
  'Plugin failed message' => '加載的插件- <strong>%s</strong> -失敗。',
);