<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'			=>	'尚無用戶以該用戶名註冊。如果您想添加一個非針對指定用戶的封禁請將用戶名欄留空。',
'No user ID message'		=>	'尚無用戶註冊該用戶名。',
'User is admin message'		=>	'用戶 %s 是管理員不可被封禁。如果您要封禁一個管理員，請先將他/她降級為版主或普通用戶。',
'Must enter message'		=>	'您必須填寫一個用戶名，一個IP地址或者一個電子信箱（至少其中一項）。',
'Cannot ban guest message'	=>	'訪客無法被封禁。',
'Invalid IP message'		=>	'您填寫了一個無效的IP/IP段。',
'Invalid e-mail message'	=>	'您填寫的電子信箱地址（如：user@domain.com）或局部的電子信箱域名（如：domain.com）無效。',
'Invalid date message'		=>	'您填寫了一個無效的屆滿日期。',
'Invalid date reasons'		=>	'正確的格式是YYYY-MM-DD並且日期必須在今天之後或更遠。',
'Ban added redirect'		=>	'封禁添加成功。正在跳轉 …' ,
'Ban edited redirect'		=>	'封禁編輯成功。正在跳轉 …',
'Ban removed redirect'		=>	'封禁解除成功。正在跳轉 …',

'New ban head'				=>	'更新封禁',
'Add ban subhead'			=>	'添加封禁',
'Username label'			=>	'用戶名',
'Username help'				=>	'填寫一個用戶名以將其加入封禁用戶（不區分大小寫）。',
'Username advanced help'	=>	'填寫一個用戶名以將其加入封禁用戶（不區分大小寫）。下一頁將讓您輸入一個自定義的IP和電子信箱。如果你只是想封禁特定的IP/IP段或電子郵件，此處請留空。',

'Ban search head'			=>	'封禁搜索',
'Ban search subhead'		=>	'填寫搜索標準',
'Ban search info'			=>	'在數據庫中搜索封禁用戶。您可填寫一項或多項條件以進行搜索。條件中可使用星號(*)作通配符。',
'Date help'					=>	'(yyyy-mm-dd)',
'Message label'				=>	'Message',
'Expire after label'		=>	'過期晚於',
'Expire before label'		=>	'過期早於',
'Order by label'			=>	'排列依據',
'Order by username'			=>	'用戶名',
'Order by ip'				=>	'IP',
'Order by e-mail'			=>	'電子信箱',
'Order by expire'			=>	'過期日期',
'Ascending'					=>	'升序',
'Descending'				=>	'降序',
'Submit search'				=>	'提交搜索',

'E-mail label'				=>	'電子信箱',
'E-mail help'				=>	'填寫您要封禁用戶的電子信箱或電子信箱域名（例如：someone@somewhere.com或somewhere.com）。查看功能權限設置中「允許已封禁的電子信箱」可瞭解更多信息。',
'IP label'					=>	'IP/IP段',
'IP help'					=>	'填寫您要封禁用戶的IP或IP段（例如：150.11.110.1或150.11.110）。IP地址間以空格分隔。此處自動填寫的IP（如果存在）是從數據庫中取得的該用戶的最後IP。',
'IP help link'				=>	'點擊%s查看該用戶的IP統計。',
'Ban advanced head'			=>	'封禁高級設置',
'Ban advanced subhead'		=>	'通過IP地址和電子信箱添加封禁',
'Ban message label'			=>	'封禁通知',
'Ban message help'			=>	'填寫一條消息，當被封禁的該用戶再次來訪時他/她將會接收到該通知。',
'Message expiry subhead'	=>	'封禁通知與屆滿',
'Ban IP range info'			=>	'封禁IP段時請務必謹慎，因為極有可能會有多個用戶匹配相同的IP段。',
'Expire date label'			=>	'屆滿日期',
'Expire date help'			=>	'填寫該封禁自動解除的日期（格式：yyyy-mm-dd）。留空表示須手動解封。',

'Results head'				=>	'搜索結果',
'Results username head'		=>	'用戶名',
'Results e-mail head'		=>	'Email',
'Results IP address head'	=>	'IP/IP段',
'Results expire head'		=>	'過期',
'Results message head'		=>	'通知',
'Results banned by head'	=>	'封禁操作人',
'Results actions head'		=>	'Actions',
'No match'					=>	'無匹配',
'Unknown'					=>	'未知',

);
