<?php

$lang_admin_permissions = array (
  'Perms updated redirect' => '權限更新。重定向... ',
  'Permissions head' => '權限',
  'Posting subhead' => '發布',
  'BBCode label' => '的BBCode ',
  'BBCode help' => '允許在文章的BBCode（推薦）。 ',
  'Image tag label' => '圖片標籤',
  'Image tag help' => '允許的BBCode [圖] [/ img]標籤中的職位。 ',
  'All caps message label' => '全部大寫消息',
  'All caps message help' => '允許一個信息，只包含大寫字母。 ',
  'All caps subject label' => '全部大寫主題',
  'All caps subject help' => '允許一個主題只包含大寫字母。 ',
  'Require e-mail label' => '要求來賓電子郵件',
  'Require e-mail help' => '要求客人提供電子郵件地址時，張貼。 ',
  'Signatures subhead' => '簽名',
  'BBCode sigs label' => ' BBCodes在簽名',
  'BBCode sigs help' => '在用戶允許 BBCodes簽名。 ',
  'Image tag sigs label' => '在簽名圖片標籤',
  'Image tag sigs help' => '允許的BBCode [圖] [/ img]標籤的用戶簽名（不推薦）。 ',
  'All caps sigs label' => '所有簽名帽',
  'All caps sigs help' => '允許一個簽名只包含大寫字母。',
  'Max sig length label' => '最大簽名長度',
  'Max sig length help' => '最大字符數可能包含用戶簽名。 ',
  'Max sig lines label' => '最大簽名行',
  'Max sig lines help' => '行的最大數量的用戶簽名可能包含的內容。 ',
  'Registration subhead' => '登記',
  'Banned e-mail label' => '允許禁止電子郵件地址',
  'Banned e-mail help' => '允許用戶註冊，或改變被禁止的電子郵件地址/域名。如果離開了它的默認設置（是），這一行動將是允許的，但警報的電子郵件將被發送到郵件列表（一種有效的方法檢測多次登記）。 ',
  'Duplicate e-mail label' => '允許重複的電子郵件地址',
  'Duplicate e-mail help' => '控制用戶是否應該允許註冊一個電子郵件地址，其他用戶已經如此。如果允許，警報電子郵件將被發送到郵件列表中，如果檢測到一個重複的。',
);