<?php

// Language definitions used in admin-options.php
$lang_admin_options = array(

'Bad HTTP Referer message'			=>	'HTTP_REFERER錯誤。如果您將論壇從一個目錄轉移到另一個目錄或是變更了域名，您需要在資料庫中手動更新根目錄URL(尋找config資料表中的o_base_url)然後刪除/cache目錄下的所有.php檔以清空cache。',
'Must enter title message'			=>	'您必須輸入論壇標題。',
'Invalid e-mail message'			=>	'您輸入了一個無效的管理信箱位址。',
'Invalid webmaster e-mail message'	=>	'您輸入了一個無效的郵件服務信箱位址。',
'SMTP passwords did not match'		=>	'您需要輸入並確認有效的SMTP密碼以變更密碼。',
'Enter announcement here'			=>	'請在此輸入公告。',
'Enter rules here'					=>	'請在此輸入條款。',
'Default maintenance message'		=>	'論壇維護中暫時關閉。請稍後訪問。',
'Timeout error message'				=>	'「在線逾時」的數值必須比「訪問逾時」小。',
'Options updated redirect'			=>	'設定已更新。重新導向中 …',
'Options head'						=>	'選項',

// Essentials section
'Essentials subhead'				=>	'概要',
'Board title label'					=>	'論壇標題',
'Board title help'					=>	'論壇的名稱(顯示在每個頁面的頂部)。這個欄位<strong>不可</strong>包含HTML標記。',
'Board desc label'					=>	'論壇敘述',
'Board desc help'					=>	'關於論壇的簡短敘述(顯示在每個頁面的頂部)。這個欄位可包含HTML標記。',
'Base URL label'					=>	'網址的根目錄',
'Base URL help'						=>	'不包含結尾斜線 的完整網址(例如：http://www.mydomain.com/forums)。此處<strong>必須</strong>輸入正確才能使所有管理及版主功能運作。如果您收到「錯誤引用」的報錯，此處很可能未輸入正確。',
'Timezone label'					=>	'預設時區',
'Timezone help'						=>	'訪客以及會員準備在論壇註冊時顯示的時區。',
'DST label'							=>	'日光節約時間調整',
'DST help'							=>	'檢查日光節約時間是否生效(時間提前1小時)。',
'Language label'					=>	'預設語言',
'Language help'						=>	'訪客以及未在其個人資料中更改過語言設定的會員的預設語言。如果您移除了一個語言包，此處必須更新。',
'Default style label'				=>	'預設風格',
'Default style help'				=>	'訪客以及未在其個人資料中更改過風格設定的會員的預設風格。',

// Essentials section timezone options
'UTC-12:00'							=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'							=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'							=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'							=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'							=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'							=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'							=>	'(UTC-08:00) Pacific',
'UTC-07:00'							=>	'(UTC-07:00) Mountain',
'UTC-06:00'							=>	'(UTC-06:00) Central',
'UTC-05:00'							=>	'(UTC-05:00) Eastern',
'UTC-04:00'							=>	'(UTC-04:00) Atlantic',
'UTC-03:30'							=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'							=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'							=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'							=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'								=>	'(UTC) Western European, Greenwich',
'UTC+01:00'							=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'							=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'							=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'							=>	'(UTC+03:30) Iran',
'UTC+04:00'							=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'							=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'							=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'							=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'							=>	'(UTC+05:45) Nepal',
'UTC+06:00'							=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'							=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'							=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'							=>	'(UTC+08:00) 大中華, Australian Western, Irkutsk',
'UTC+08:45'							=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'							=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'							=>	'(UTC+09:30) Australian Central',
'UTC+10:00'							=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'							=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'							=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'							=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'							=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'							=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'							=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'							=>	'(UTC+14:00) Line Islands',

// Timeout Section
'Timeouts subhead'					=>	'時間與逾時',
'Time format label'					=>	'時間格式',
'PHP manual'						=>	'PHP手冊',
'Time format help'					=>	'[目前格式： %s]. 請至%s查看格式選項。',
'Date format label'					=>	'日期格式',
'Date format help'					=>	'[目前格式： %s]. 請至%s查看格式選項。',
'Visit timeout label'				=>	'訪問逾時',
'Visit timeout help'				=>	'使用者前次訪問的資料更新後要計算新訪問必須閒置的秒數(主要影響新文章提示功能)。',
'Online timeout label'				=>	'在線逾時',
'Online timeout help'				=>	'會員被移出線上會員列表前必須閒置的秒數。',
'Redirect time label'				=>	'重新導向的時間',
'Redirect time help'				=>	'重新導向前必須等待的秒數。如果設定為0，重新導向頁面將不顯示(不推薦)。',

// Display Section
'Display subhead'					=>	'顯示',
'Version number label'				=>	'版本號',
'Version number help'				=>	'在頁尾顯示FluxBB的版本號。',
'Info in posts label'				=>	'發文者相關資訊',
'Info in posts help'				=>	'在發表文章中的會員名稱下顯示發文者的相關資訊。這些資訊包括所在地，註冊日期，發文數以及聯繫連結(電子信箱和網址)。',
'Post count label'					=>	'會員發文數統計',
'Post count help'					=>	'顯示會員所發表的文章數目統計(涉及瀏覽文章頁面，個人資料頁面以及會員列表頁面)。',
'Smilies label'						=>	'文章內表情符號',
'Smilies help'						=>	'將文章中的特定符號轉換為表情圖。',
'Smilies sigs label'				=>	'簽名內表情符號',
'Smilies sigs help'					=>	'將會員簽名中的特定符號轉換為表情圖。',
'Clickable links label'				=>	'轉換網址為連結',
'Clickable links help'				=>	'啟用後，FluxBB將自動偵測發文中包含的所有網址格式並將其轉換為超連結。',
'Topic review label'				=>	'主題回顧',
'Topic review help'					=>	'發文時顯示舊文的最大數目(最新文章於最前面)。設為0則停用。',
'Topics per page label'				=>	'每頁主題',
'Topics per page help'				=>	'一個版面中每頁預設顯示的主題數。會員可自訂數值。',
'Posts per page label'				=>	'每頁文章',
'Posts per page help'				=>	'一個主題中每頁預設顯示的文章數。會員可自訂數值。',
'Indent label'						=>	'縮排大小',
'Indent help'						=>	'如果設為8，在[code][/code]標籤中的文字顯示時將使用規則的tab，否則即以設定數值的空格縮排文字。',
'Quote depth label'					=>	'[quote] 標籤引用的最大層次',
'Quote depth help'					=>	'[quote] 標籤能夠包含更多 [quote] 標籤的最大層次，當引用層次超出設定值時將被捨棄。',

// Features section
'Features subhead'					=>	'功能',
'Quick post label'					=>	'快速回覆',
'Quick post help'					=>	'啟用後，FluxBB將在主題下增加快速回覆的表單。使用者便可在瀏覽主題時直接發表回覆。',
'Users online label'				=>	'線上統計',
'Users online help'					=>	'在首頁顯示正在瀏覽論壇的訪客及註冊會員統計資訊。',
'Censor words label'				=>	'詞彙過濾',
'Censor words help'					=>	'這個功能可幫助論壇過濾敏感詞彙。參見%s檢視更多資訊。',
'Signatures label'					=>	'簽名',
'Signatures help'					=>	'允許會員在文章下附加簽名。',
'User ranks label'					=>	'會員等級',
'User ranks help'					=>	'啟用它以使會員等級生效。參見%s檢視更多資訊。',
'User has posted label'				=>	'會員參與討論的主題',
'User has posted help'				=>	'讓目前登入的會員通過主題前面的小點識別已參與過的主題。伺服器負荷過高時建議停用。',
'Topic views label'					=>	'主題瀏覽次數',
'Topic views help'					=>	'跟蹤主題被瀏覽的次數。伺服器負荷過高時建議停用。',
'Quick jump label'					=>	'快速轉移',
'Quick jump help'					=>	'啟用快速轉移(轉移至版面)下拉式清單。',
'GZip label'						=>	'GZip壓縮輸出',
'GZip help'							=>	'啟用後，FluxBB會先將輸出作gzip壓縮後再發送至瀏覽器。這將會節約頻寬使用，但是會稍耗點CPU。此功能要求PHP設定zlib (--with-zlib)。注意：如果您的Apache已經有mod_gzip模組或mod_deflate模組設定為壓縮PHP指令碼，您應停用這功能。',
'Search all label'					=>	'搜尋所有版面',
'Search all help'					=>	'停用後，每次搜尋只可針對一個版面。當過度搜尋導致伺服器負荷過高時應停用這功能。',
'Menu items label'					=>	'附加選單項',
'Menu items help'					=>	'在文字框中輸入HTML超連結，可任意將選單項數增加到所有頁面頂端的導覽選單。增加新連結的格式為X = &lt;a href="URL"&gt;LINK&lt;/a&gt;，X表示在第幾行插入這個連結(例如：0表示插入到最前面而2表示插入到「會員列表」的後面)。每行輸入一條。',

// Feeds section
'Feed subhead'						=>  '新聞訂閱',
'Default feed label'				=>	'預設訂閱類型',
'Default feed help'					=>	'選擇要顯示的新聞訂閱摘要的類型。注意：選擇無時並不能關閉訂閱，只表示預設不顯示。',
'None'								=>	'無',
'RSS'								=>	'RSS',
'Atom'								=>	'Atom',
'Feed TTL label'					=>	'新聞暫存的持續時間',
'Feed TTL help'						=>	'新聞暫存可以降低新聞使用資源',
'No cache'							=>	'不要暫存',
'Minutes'							=>	'%d 分',

// Reports section
'Reports subhead'					=>	'舉報',
'Reporting method label'			=>	'接受舉報模式',
'Internal'							=>	'內部',
'By e-mail'							=>	'電子信箱',
'Both'								=>	'兼選',
'Reporting method help'				=>	'選擇主題/文章舉報的處理方式。您可選擇以內部舉報系統處理舉報，也可選擇將舉報發送到信箱列表(參見下文)，或者兩者兼選。',
'Mailing list label'				=>	'信箱列表',
'Mailing list help'					=>	'以逗號分隔接受郵件的信箱列表。這份名單是舉報的收件人。',

// Avatars section
'Avatars subhead'					=>	'頭像',
'Use avatars label'					=>	'使用頭像',
'Use avatars help'					=>	'啟用後，會員可上傳頭像，頭像顯示在會員的頭銜/等級之下。',
'Upload directory label'			=>	'上傳目錄',
'Upload directory help'				=>	'頭像上傳目錄(相對於FluxBB的根目錄)。必須為PHP設定此目錄的寫入權限。',
'Max width label'					=>	'最大寬度',
'Max width help'					=>	'頭像寬度允許的最大像素(建議設60)。',
'Max height label'					=>	'最大高度',
'Max height help'					=>	'頭像高度允許的最大像素(建議設60)。',
'Max size label'					=>	'最大尺寸',
'Max size help'						=>	'頭像尺寸允許的最大byte(建議設10240)。',

// E-mail section
'E-mail subhead'					=>	'電子郵件',
'Admin e-mail label'				=>	'管理電子信箱',
'Admin e-mail help'					=>	'網站管理員電子信箱位址。',
'Webmaster e-mail label'			=>	'網站管理員郵件服務信箱',
'Webmaster e-mail help'				=>	'網站發出的郵件將會使用這個位址為發件人。',
'Forum subscriptions label'			=>	'訂閱版面',
'Forum subscriptions help'			=>	'允許會員訂閱版面(版面有新主題時接收通知郵件)。',
'Topic subscriptions label'			=>	'訂閱主題',
'Topic subscriptions help'			=>	'允許會員訂閱主題(主題有新回覆時接收通知郵件)。',
'SMTP address label'				=>	'SMTP伺服器位址',
'SMTP address help'					=>	'發送郵件的外部SMTP位址。如果某SMTP伺服器沒有使用預設的25連接埠號，您可指定一個自訂連接埠號(如：mail.myhost.com:3580)。要使用本機郵件程式請留空。',
'SMTP username label'				=>	'SMTP使用者名稱',
'SMTP username help'				=>	'登入SMTP伺服器的使用者名稱。當SMTP伺服器要求您提供使用者名稱時請輸入(很多伺服器<strong>並不</strong>需要身份驗證)。',
'SMTP password label'				=>	'SMTP密碼',
'SMTP change password help'			=>	'當您需要準備修改或者刪除目前所存儲的密碼前請檢查此項。',
'SMTP password help'				=>	'登入SMTP伺服器的密碼。當SMTP伺服器要求您提供密碼時請輸入(很多伺服器<strong>並不</strong>需要身份驗證)。輸入密碼後需重複輸入以進行確認。',
'SMTP SSL label'					=>	'SMTP使用SSL加密',
'SMTP SSL help'						=>	'為與SMTP伺服器的連接使用SSL加密。僅當您的SMTP伺服器要求時才需使用並且您的PHP版本支援SSL。',

// Registration Section
'Registration subhead'				=>	'註冊',
'Allow new label'					=>	'允許新會員註冊',
'Allow new help'					=>	'控制論壇是否允許新會員註冊。若無特殊情況應該開放。',
'Verify label'						=>	'註冊驗證',
'Verify help'						=>	'啟用後，會員註冊時將會收到一組隨機密碼。如果他們認為需要，隨後他們便可在其個人資料中修改密碼。當會員準備將註冊時輸入的電子信箱更換為新信箱時，這個功能也會要求會員驗證新信箱。這是避免濫用註冊的有效方法，並且可保證所有會員在其個人資料中輸入了「正確的」電子信箱。',
'Report new label'					=>	'報告新註冊',
'Report new help'					=>	'啟用後，當有新會員在論壇註冊時FluxBB將向信箱列表(參見上文)發送通知郵件。',
'Use rules label'					=>	'論壇服務條款',
'Use rules help'					=>	'啟用後，會員註冊時將被要求必須接受的相關條款(內容請在下方輸入)。服務條款的連結將一直顯示在每個頁面的導覽欄中。',
'Rules label'						=>	'請在此處輸入您的條款',
'Rules help'						=>	'您可在此輸入任何需要讓使用者在註冊前閱讀並接受的條款或其他資訊。如果您在上面啟用了論壇服務條款功能您至少需在這裡寫些文字，否則它會被停用。這段文字不會被當作正常的文章解析所以是可以包含HTML語法的。',
'E-mail default label'				=>	'預設電子信箱設定',
'E-mail default help'				=>	'選擇新會員註冊時預設的隱私設定。',
'Display e-mail label'				=>	'向其他會員公開您的電子信箱。',
'Hide allow form label'				=>	'隱藏電子信箱，但允許其他會員通過論壇向您發送郵件。',
'Hide both label'					=>	'隱藏電子信箱，並阻止其他會員通過論壇向您發送郵件。',

// Announcement Section
'Announcement subhead'				=>	'公告',
'Display announcement label'		=>	'顯示公告',
'Display announcement help'			=>	'啟用後可將下列消息發佈在論壇佈告欄。',
'Announcement message label'		=>	'公告內容',
'Announcement message help'			=>	'這段文字不會被當作一般的文章解析所以可包含HTML語法。',

// Maintenance Section
'Maintenance subhead'				=>	'維護',
'Maintenance mode label'			=>	'維護模式',
'Maintenance mode help'				=>	'啟用後，論壇只對管理員開放。這個功能用於論壇需要暫時關閉維護時。<strong>警告！論壇處於維護模式時請勿登出。</strong>那會讓您再也無法登入。',
'Maintenance message label'			=>	'維護時顯示的訊息',
'Maintenance message help'			=>	'當論壇處於維護模式時訪問論壇會看到此訊息。如果留空，將顯示一條預設訊息。這段文字不會被當作一般的文章解析所以可包含HTML語法。',

);
