<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'系統 \'allow_url_fopen\' 失效導致無法檢查升級。',
'Upgrade check failed message'		=>	'未知原因導致升級檢查失敗。',
'Running latest version message'	=>	'您使用的是FluxBB的最新版本。',
'New version available message'		=>	'已經有新的FluxBB版本發佈。您可在以下地址下載最新版 %s.',
'PHPinfo disabled message'			=>	'該服務器的PHP函數 phpinfo() 失效。',
'Not available'						=>	'不可用',
'Forum admin head'					=>	'論壇管理設置',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'歡迎來到 FluxBB 管理設置面板。從這裡您可以控制整個論壇設置的方方面面。以下功能的可用性將取決於您是論壇管理員還是版主：',
'Welcome 1'							=>	'組織版塊及版塊的類別。',
'Welcome 2'							=>	'設置論壇開放度的選項及偏好。',
'Welcome 3'							=>	'控制用戶及訪客的各項權限。',
'Welcome 4'							=>	'查看用戶的 IP 統計信息。',
'Welcome 5'							=>	'封禁惡意用戶。',
'Welcome 6'							=>	'過濾敏感詞彙。',
'Welcome 7'							=>	'自定義用戶的級別。',
'Welcome 8'							=>	'清理舊帖子。',
'Welcome 9'							=>	'處理舉報信息。',
'Statistics head'					=>	'統計',
'FluxBB version label'				=>	'FluxBB版本',
'Check for upgrade'					=>	'檢查升級',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'服務器負載',
'Server load data'					=>	'%s - 當前有 %s 人在線',
'Environment label'					=>	'環境',
'Environment data OS'				=>	'操作系統： %s',
'Show info'							=>	'顯示詳細信息',
'Environment data version'			=>	'PHP： %s - %s',
'Environment data acc'				=>	'加速器： %s',
'Turck MMCache'						=>	'Turk MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'數據庫',
'Database data rows'				=>	'Rows: %s',
'Database data size'				=>	'Size: %s',

);
