<?php

// Language definitions used in install.php, localized by adaur

$lang_install = array(

'Install message'				=>	'文件 \'config.php\' 已損壞或不存在。這表明FluxBB尚未架設。',
'Choose install language'		=>	'選擇安裝腳本的語言',
'Choose install language info'	=>	'本安裝腳本所使用的語言。論壇所使用的默認語言將在接下來的安裝過程中設置。',
'Install language'				=>	'安裝使用語言',
'Change language'				=>	'變更語言',
'Next'							=>	'下一步',
'Already installed'				=>	'FluxBB 似乎已安裝。請點擊<a href="index.php">此鏈接</a>前往。',
'You are running error'			=>	'您的 %1$s 版本為 %2$s。 FluxBB %3$s 至少需要 %1$s %4$s 方可正確運行。您在繼續之前，必須升級您的 %1$s 設置。',
'My FluxBB Forum'				=>	'My FluxBB Forum',
'Description'					=>	'Unfortunately no one can be told what FluxBB is - you have to see it for yourself.',
'Username 1'					=>	'用戶名長度不可少於2個字符。',
'Username 2'					=>	'用戶名長度不可超過25個字符。',
'Username 3'					=>	'guest 是保留的用戶名。',
'Username 4'					=>	'用戶名的格式不允許是 IP 地址式。',
'Username 5'					=>	'用戶名不可一次包含字符 \'、 " 與 [ 或 ] 。請重新選擇用戶名。',
'Username 6'					=>	'用戶名不可包含本論壇所使用的文本樣式標籤(BBCode)。',
'Short password'				=>	'密碼長度不可少於4個字符。',
'Passwords not match'			=>	'密碼不匹配。',
'Wrong email'					=>	'您填寫的管理員電子信箱地址無效。',
'No board title'				=>	'您必須填寫論壇標題。',
'Error default language'		=>	'所選的默認語言似乎不存在。',
'Error default style'			=>	'所選的默認風格似乎不存在。',
'No DB extensions'				=>	'現有 PHP 環境不具備 FluxBB 所需的任何格式的數據庫。為使 FluxBB 能被安裝，PHP 必須已包含 MySQL、PostgreSQL或SQLite。',
'Administrator username'		=>	'管理員用戶名',
'Administrator password 1'		=>	'管理員密碼1',
'Administrator password 2'		=>	'管理員密碼2',
'Administrator email'			=>	'管理員電子信箱',
'Board title'					=>	'論壇標題',
'Base URL'						=>	'根目錄網址',
'Required field'				=>	'在該表格中是必填項。',
'FluxBB Installation'			=>	'FluxBB 安裝嚮導',
'Welcome'						=>	'您將要安裝 FluxBB。繼續安裝前您必須完成填寫以下表格。遇到任何安裝問題，請參考幫助文檔。',
'Install'						=>	'安裝 FluxBB 1.4',
'Errors'						=>	'下列錯誤須要修正：',
'Database setup'				=>	'數據庫設置',
'Info 1'						=>	'請填寫必須信息以安裝 FluxBB 所需的數據庫。在開始安裝前，您必須瞭解所要求內容的全部信息。',
'Select database'				=>	'選擇數據庫類型',
'Info 2'						=>	'FluxBB 目前支持 MySQL， PostgreSQL 以及 SQLite。如果選擇數據庫的下拉菜單不可用，便表示該 PHP 環境不支持所需的數據庫。各數據庫特定版本的更多相關資料可查看常見問題。',
'Dual MySQL'					=>	'FluxBB 檢測到您的 PHP 環境支持 MySQl 的兩種不同通訊方式。兩個選項分別為標準(standard)與改進(improved)。如果您不確定該如何選擇，建議您選擇改進(improved)，如不能完成再改試標準(standard)。',
'InnoDB'						=>	'FluxBB 檢測到您的 MySQL 也許支持 <a href="http://dev.mysql.com/doc/refman/5.0/en/innodb.html">InnoDB</a>。它對運行大型論壇有益處。如果您不很確定是否該使用 InnoDB，建議您不要使用。',
'Database type'					=>	'數據庫類型',
'Required'						=>	'(必需)',
'Database hostname'				=>	'填寫數據庫服務器的主機名',
'Info 3'						=>	'數據庫服務器的地址(例如：localhost, db.myhost.com 或 192.168.0.15)。如果您的數據庫未使用指定端口，您可指定自定義端口(例如：localhost:3580)。如使用 SQLite 數據庫，此處可填寫任意字符或直接用\'localhost\'。',
'Database server hostname'		=>'數據庫服務器主機名',
'Database enter name'			=>	'填寫數據庫名',
'Info 4'						=>	'安裝 FluxBB 即將使用的數據庫的名稱。該數據庫必須存在。如使用 SQLite 數據庫，這裡便是數據庫文件的相對路徑。如 SQLite 數據庫文件不存在，FluxBB 將嘗試創建它。',
'Database name'					=>	'數據庫名',
'Database enter informations'	=>	'填寫您數據庫的用戶名及密碼',
'Database username'				=>	'數據庫用戶名',
'Info 5'						=>	'填寫您所要連接的數據庫的用戶名及密碼。如使用 SQLite 此處忽略。',
'Database password'				=>	'數據庫密碼',
'Database enter prefix'			=>	'填寫數據庫表前綴',
'Info 6'						=>	'如果您喜歡，您可指定數據表的前綴。這個方式可讓您在同一數據庫中使用多個 FluxBB 副本(例如：foo_)。',
'Table prefix'					=>	'數據表前綴',
'Administration setup'			=>	'管理員設置',
'Info 7'						=>	'請填寫所需信息以給您的 FluxBB 安裝設置一個管理員。',
'Admin enter username'			=>	'填寫管理員用戶名',
'Info 8'						=>	'論壇管理員的用戶名。稍後您還可以設置更多管理員以及版主。用戶名長度須在2至25字符之間。',
'Admin enter password'			=>	'填寫並確認管理員密碼',
'Info 9'						=>	'密碼長度至少須4字符。密碼區分大小寫。',
'Password'						=>	'密碼',
'Confirm password'				=>	'確認密碼',
'Admin enter email'				=>	'填寫管理員電子信箱',
'Info 10'						=>	'論壇管理員的電子信箱地址。',
'Board setup'					=>	'論壇設置',
'Info 11'						=>	'請填寫所需信息設置您的 FluxBB 論壇。',
'Enter board title'				=>	'填寫您論壇的標題',
'Info 12'						=>	'該論壇的標題(將在每頁頂部顯示)。',
'Enter board description'		=>	'填寫您論壇的描述',
'Info 13'						=>	'關於本論壇的簡短描述(將在每頁頂部顯示)。該字段可包含 HTML。',
'Board description'				=>	'論壇描述',
'Enter base URL'				=>	'填寫您安裝的 FluxBB 論壇的根目錄網址',
'Info 14'						=>	'您的 FluxBB 論壇的 URL (無需結尾的斜槓)地址(示例： http://forum.myhost.com 或 http://myhost.com/~myuser)。此處<strong>必須</strong>填寫正確，否則，管理員和版主都將無法提交任何更改。請注意此處的預設值只是 FluxBB 的一個猜測結果。',
'Choose the default language'		=>	'選擇默認語言',
'Info 15'						=>	'訪客以及未在個人資料中修改設置的用戶使用的默認語言。',
'Default language'				=>	'默認語言',
'Choose the default style'		=>	'選擇默認風格',
'Info 16'						=>	'訪客以及未在個人資料中修改設置的用戶使用的默認風格。',
'Default style'					=>	'默認風格',
'Start install'					=>	'開始安裝',
'DB type not valid'				=>	'\'%s\' 不是一個有效的數據庫類型',
'Table prefix error'			=>	'數據表前綴 \'%s\' 包含非法字符或過長。表前綴可包含字母 a 至 z，任何數字以及下劃線。並且不能以數字開頭。長度不超過40個字符。請另選表前綴',
'Prefix reserved'				=>	'數據表前綴 \'sqlite_\' 是專為 SQLite 引擎保留的名稱。請另選表前綴',
'Existing table error'			=>	'數據庫 \'%s\'中已經存在數據表 \'%susers\'。這可能表示 FluxBB 已曾安裝或另一個已安裝的軟件佔用了 FluxBB 所需的一個或多個數據表名稱。如您準備在同一數據庫中安裝多個 FluxBB 副本，您必須選擇一個不同的表前綴。',
'InnoDB off'					=>	'InnoDB 似乎不可用。請另選一個無 InnoDB 支持的數據庫層，或在您的 MySQL服務器上啟用 InnoDB',
'Administrators'				=>	'管理員',
'Administrator'					=>	'管理員',
'Moderators'					=>	'版主',
'Moderator'						=>	'版主',
'Guest'							=>	'訪客',
'New member'					=>	'新用戶',
'Member'						=>	'用戶',
'Announcement'					=>	'在此填寫您要發佈的公告。',
'Rules'							=>	'在此填寫論壇服務條款',
'Maintenance message'			=>	'論壇維護中。請稍後訪問。<br />\\n<br />\\n/管理員',
'Test post'						=>	'示例帖子',
'Message'						=>	'如果您在閱讀這個帖子(我猜正是如此)，安裝的 FluxBB 已經開始工作！現在您可以登錄，並進入頂部的管理設置面板來配置您的論壇。',
'Test category'					=>	'測試分類',
'Test forum'					=>	'測試版塊',
'This is just a test forum'		=>	'這只是一個測試版塊',
'Alert cache'					=>	'<strong>緩存所在目錄不可寫！</strong>為使 FluxBB 功能正常，必須為目錄 <em>%s</em> 開啟 PHP 寫入權限。使用 chmod 命令設置恰當的目錄權限。如有疑問，用 chmod 設為0777。',
'Alert avatar'					=>	'<strong>頭像所在目錄不可寫！</strong>如果您準備允許用戶上傳自定義頭像，您必須確認已為目錄 <em>%s</em> 開啟了 PHP 寫入權限。稍後您可為用戶上傳的頭像文件選擇指定的目錄(見 管理設置/配置選項)。使用 chmod 命令設置恰當的目錄權限。如有疑問，用 chmod 設為0777。',
'Alert upload'					=>	'<strong>該服務器似乎不允許上傳文件！</strong>如果您準備允許用戶上傳自定義頭像，您必須開啟 PHP 中的 file_uploads 配置設置。上傳功能一旦可用，可在 管理設置/配置選項/頭像 中開啟。',
'FluxBB has been installed'		=>	'FluxBB 已安裝結束。請遵循以下指示完成安裝嚮導。',
'Final instructions'			=>	'最後一步',
'Info 17'						=>	'為完成安裝，您需要點擊下示按鈕以下載名為 config.php 的文件。然後上傳它至您已安裝的 FluxBB 程序的根目錄下。',
'Info 18'						=>	'一旦您上傳完 config.php，FluxBB 就安裝成功了！隨後您便可 <a href="index.php">進入論壇首頁</a>。',
'Download config.php file'		=>	'下載 config.php 文件',
'FluxBB fully installed'		=>	'FluxBB 已經安裝成功！您現在可 <a href="index.php">點此訪問論壇首頁</a>。',

);
