<?php

$lang_post = array (
  'No subject' => '主題必須包含一個主題。 ',
  'Too long subject' => '主體長度不能超過 70個字符。 ',
  'No message' => '您必須輸入消息。 ',
  'Too long message' => '篇不能長於 %s個字節。 ',
  'All caps subject' => '主體不能只包含大寫字母。 ',
  'All caps message' => '篇不能只包含大寫字母。 ',
  'Empty after strip' => '看來你的職位包括空BBCodes只。很可能發生這種情況，比如，因為發自內心的報價被丟棄，因為深度的最高報價水平。 ',
  'Post errors' => ' POST錯誤',
  'Post errors info' => '下面的錯誤需要改正之前可以發布的消息： ',
  'Post preview' => '發布預覽',
  'Guest name' => '名稱',
  'Post redirect' => '後進入。重定向... ',
  'Post a reply' => '發表回复',
  'Post new topic' => '發表新主題',
  'Hide smilies' => '表情符號不顯示為圖標為這個職位',
  'Subscribe' => '訂閱此主題',
  'Stay subscribed' => '留訂閱此主題',
  'Topic review' => '主題回顧（最新一） ',
  'Flood start' => '至少',
  'flood end' => '秒，崗位之間傳遞。請稍等一會兒，並嘗試發布一次。',
  'Preview' => '預覽',
  'Edit post legend' => '編輯文章和提交更改',
  'Silent edit' => '沉默的編輯（不顯示“編輯 ...”在主題視圖） ',
  'Edit post' => '編輯文章',
  'Edit redirect' => '郵政更新。重定向...',
);