<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'填寫一個有效的電子信箱',
'Email legend 2'			=>	'填寫並重複填寫一個有效的電子信箱',
'Localisation legend'		=>	'設置您的本地化選項',
'Time zone'					=>	'時區',
'Time zone info'			=>	'要使論壇顯示正確的時間，您必須正確地選擇當地時區。如果需要，您還須檢查是否啟用夏令時，以讓時間提前1小時。',
'DST'						=>	'夏令時生效 (時間提前1小時)。',
'Time format'				=>	'時間格式',
'Date format'				=>	'日期格式',
'Default'					=>	'默認',
'Language'					=>	'語言',
'Email setting info'		=>	'選擇您的電子信箱對其他用戶是否可見以及您是否允許其他用戶通過論壇(經由電子信箱)向您發送郵件。',
'Email setting 1'			=>	'向其他用戶公開您的電子信箱。',
'Email setting 2'			=>	'隱藏電子信箱，但允許其他用戶通過論壇向您發送郵件。',
'Email setting 3'			=>	'隱藏電子信箱，並阻止其他用戶通過論壇向您發送郵件。',
'Privacy options legend'	=>	'設置隱私選項',
'Confirm pass'				=>	'重複密碼',

'Username too short'		=>	'用戶名長度至少需要2字節。請重新選擇(更長的)用戶名。',
'Username too long'			=>	'用戶名長度不可超過25字節。請重新選擇(更短的)用戶名。',
'Username guest'			=>	'該用戶名已被訪客佔用。請重新選擇用戶名。',
'Username IP'				=>	'用戶名不得設為 IP 地址格式。請重新選擇用戶名。',
'Username reserved chars'	=>	'Usernames may not contain all the characters \', " and [ or ] at once. Please choose another username.',
'Username BBCode'			=>	'用戶名不得包含論壇所使用的樣式標籤格式 (BBCode) 。請重新選擇用戶名。',
'Banned username'			=>	'該用戶名已被論壇阻止。請重新選擇用戶名。',
'Pass too short'			=>	'密碼長度至少需要4字節。請重新選擇(更長的)密碼。',
'Pass not match'			=>	'密碼不匹配。',
'Banned email'				=>	'該電子信箱已被論壇阻止。請重新選擇電子信箱。',
'Dupe email'				=>	'該電子信箱已被其他用戶使用。請重新選擇電子信箱。',
'Sig too long'				=>	'簽名長度不能超過 %1$s 字符。請將您的簽名去掉 %2$s 個字符。',
'Sig too many lines'		=>	'簽名行數不能超過 %s 行。',
'Bad ICQ'					=>	'您填寫了一個無效的 ICQ UIN 號碼。請返回修正。',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
