<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'會員搜尋',
'No search permission'				=>	'您沒有使用搜尋功能的權限。',
'Search flood'						=>	'您所在的會員群組兩次搜尋之間至少需要間隔 %s 秒。請稍等一會後再嘗試搜尋。',
'Search'							=>	'搜尋',
'Search criteria legend'			=>	'輸入搜尋準則',
'Search info'						=>	'按關鍵詞搜尋時，可輸入一個或多個詞語。多個關鍵詞請以空格分隔。支援使用 AND, OR 和 NOT 以縮小搜尋範圍。按作者搜尋時請輸入您希望搜尋的內容的作者名稱。可使用萬用字元 * 作部分符合。',
'Keyword search'					=>	'關鍵詞搜尋',
'Author search'						=>	'作者搜尋',
'Search in legend'					=>	'選擇要搜尋的版面',
'Search in info'					=>	'選擇您要搜尋哪個版面的內容，並選擇是要在標題、文章中還是包括標題及文章中搜尋符合項。',
'Search multiple forums info'		=>	'如未選擇任何版面，則將搜尋整個論壇。',
'Forum search'						=>	'版面',
'All forums'						=>	'所有版面',
'Search in'							=>	'搜尋於',
'Message and subject'				=>	'包括標題和文章',
'Message only'						=>	'只搜尋文章',
'Topic only'						=>	'只搜尋標題',
'Sort by'							=>	'排序依據',
'Sort order'						=>	'排序順序',
'Search results legend'				=>	'選擇搜尋結果的樣式',
'Search results info'				=>	'您可以選擇搜尋結果的排序方式及顯示樣式。',
'Sort by post time'					=>	'發文時間',
'Sort by author'					=>	'作者',
'Sort by subject'					=>	'主題',
'Sort by forum'						=>	'版面',
'Ascending'							=>	'遞增',
'Descending'						=>	'遞減',
'Show as'							=>	'顯示樣式',
'Show as topics'					=>	'主題式',
'Show as posts'						=>	'文章式',

// Results
'Search'							=>	'搜尋',
'Search results'					=>	'搜尋結果',
'Quick search show_new'				=>	'已更新的主題',
'Quick search show_recent'			=>	'最近的主題',
'Quick search show_unanswered'		=>	'未回覆的主題',
'Quick search show_replies'			=>	'您參與的主題',
'Quick search show_user_topics'		=>	'由 %s 發表的主題',
'Quick search show_user_posts'		=>	'由 %s 發表的文章',
'Quick search show_subscriptions'	=>	'被 %s 訂閱的内容',
'By keywords show as topics'		=>	'包含 \'%s\' 的主題文章',
'By keywords show as post'			=>	'包含 \'%s\' 的文章',
'By user show as topics'			=>	'包含由 %s 發表的主題',
'By user show as posts'				=>	'由 %s 發表的文章',
'By both show as topics'			=>	'包含 \'%s\' 由 %s 發表的主題文章', 
'By both show as posts'				=>	'包含 \'%s\' 由 %s 發表的文章', 
'No terms'							=>	'您至少需要輸入一個關鍵詞和/或一個作者名稱才能進行搜尋。',
'No hits'							=>	'您的搜尋沒有符合的項目。',
'No user posts'						=>	'指定版面中沒有這位會員發表的文章。',
'No user topics'					=>	'指定版面中沒有這位會員發表的主題。',
'No subscriptions'					=>	'這位會員目前尚未訂閱任何主題。',
'No new posts'						=>	'自您上次登入後沒有新文章。',
'No recent posts'					=>	'最近24小時內沒有任何新文章。',
'No unanswered'						=>	'暫無未回覆的主題。',
'Go to post'						=>	'前往文章',
'Go to topic'						=>	'前往主題'

);
