<?php

$lang_topic = array (
  'Post reply' => '發表回复',
  'Topic closed' => '關閉主題',
  'From' => '來自： ',
  'IP address logged' => ' IP地址登錄',
  'Note' => '注意： ',
  'Posts' => '貼文： ',
  'Registered' => '註冊： ',
  'Replies' => '回复： ',
  'Website' => '網站',
  'Guest' => '客戶',
  'Online' => '在線',
  'Offline' => '離線',
  'Last edit' => '最後編輯',
  'Report' => '報告',
  'Delete' => '刪除',
  'Edit' => '編輯',
  'Quote' => '報價',
  'Is subscribed' => '您目前訂閱此主題',
  'Unsubscribe' => '取消訂閱',
  'Subscribe' => '訂閱此主題',
  'Quick post' => '快速發帖',
  'Mod controls' => '主持人控制',
  'New icon' => '新員額',
  'Re' => '回复： ',
  'Preview' => '預覽',
);