<?php

// Language definitions used in admin-users.php
$lang_admin_users = array(

'Non numeric message'		=>	'您在一个仅接受数值的列中填写了非数值字符。',
'Invalid date time message'	=>	'日期/时间格式不正确。',
'Not verified'				=>	'未验证',
'User search head'			=>	'用户搜索',
'User search subhead'		=>	'填写搜索条件',
'User search info'			=>	'在数据库中搜索用户。您可填写一个或多个条件进行搜索。搜索条件中允许使用通配符 * 模糊匹配。',
'Username label'			=>	'用户名',
'E-mail address label'		=>	'电子信箱地址',
'Title label'				=>	'头衔',
'Real name label'			=>	'真实姓名',
'Website label'				=>	'个人网站',
'Jabber label'				=>	'Jabber',
'ICQ label'					=>	'ICQ',
'MSN label'					=>	'MSN Messenger',
'AOL label'					=>	'AOL IM',
'Yahoo label'				=>	'Yahoo Messenger',
'Location label'			=>	'所在地',
'Signature label'			=>	'签名',
'Admin note label'			=>	'管理员注',
'Posts more than label'		=>	'发帖数大于',
'Posts less than label'		=>	'发帖数小于',
'Last post after label'		=>	'最新帖子晚于',
'Date help'					=>	'(yyyy-mm-dd hh:mm:ss)',
'Last post before label'	=>	'最新帖子早于',
'Registered after label'	=>	'注册时间晚于',
'Registered before label'	=>	'注册时间早于',
'Order by label'			=>	'排列依据',
'Order by username'			=>	'用户名',
'Order by e-mail'			=>	'电子信箱',
'Order by posts'			=>	'发帖数',
'Order by last post'		=>	'最后发表',
'Order by registered'		=>	'注册时间',
'Ascending'					=>	'升序',
'Descending'				=>	'降序',
'User group label'			=>	'用户组',
'All groups'				=>	'所有组',
'Unverified users'			=>	'未验证用户',
'Submit search'				=>	'提交搜索',
'IP search head'			=>	'IP搜索',
'IP search subhead'			=>	'填写IP进行搜索',
'IP address label'			=>	'IP地址',
'IP address help'			=>	'在发帖数据库中搜索IP地址。',
'Find IP address'			=>	'查找IP地址',

'Results head'				=>	'搜索结果',
'Results username head'		=>	'用户名',
'Results e-mail head'		=>	'电子信箱',
'Results title head'		=>	'头衔/身份',
'Results posts head'		=>	'发帖',
'Results admin note head'	=>	'管理员注',
'Results actions head'		=>	'操作',
'Results IP address head'	=>	'IP地址',
'Results last used head'	=>	'最后使用',
'Results times found head'	=>	'发现次数',
'Results action head'		=>	'操作',
'Results find more link'	=>	'查找该IP的更多用户',
'Results no posts found'	=>	'当前该版块尚无该用户的帖子。',
'Bad IP message'			=>	'所提供的IP地址格式不正确。',
'Results view IP link'		=>	'查看IP统计信息',
'Results show posts link'	=>	'显示帖子',
'Results guest'				=>	'访客',
'Results no IP found'		=>	'数据库中找不到所提供的IP地址。',
'No match'					=>	'无匹配项'

);
