<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'系统 \'allow_url_fopen\' 失效导致无法检查升级。',
'Upgrade check failed message'		=>	'未知原因导致升级检查失败。',
'Running latest version message'	=>	'您使用的是FluxBB的最新版本。',
'New version available message'		=>	'已经有新的FluxBB版本发布。您可在以下地址下载最新版 %s.',
'Not available'						=>	'不可用',
'Forum admin head'					=>	'论坛管理设置',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'欢迎来到 FluxBB 管理设置面板。从这里您可以控制整个论坛设置的方方面面。以下功能的可用性将取决于您是论坛管理员还是版主：',
'Welcome 1'							=>	'组织版块及版块的类别。',
'Welcome 2'							=>	'设置论坛开放程度的选项及偏好。',
'Welcome 3'							=>	'控制用户及访客的各项权限。',
'Welcome 4'							=>	'查看用户的 IP 统计信息。',
'Welcome 5'							=>	'封禁恶意用户。',
'Welcome 6'							=>	'过滤敏感词汇。',
'Welcome 7'							=>	'设定用户组和晋升。',
'Welcome 8'							=>	'清理旧帖子。',
'Welcome 9'							=>	'处理举报信息。',
'About head'						=>	'关于FluxBB',
'FluxBB version label'				=>	'FluxBB版本',
'Check for upgrade'					=>	'检查升级',
'FluxBB version data'				=>	'v%s - %s',
'Server statistics label'			=>	'服务器统计',
'View server statistics'			=>	'查看服务器统计',
'Support label'						=>	'支持',
'Forum label'						=>	'论坛',
'IRC label'							=>	'IRC频道',

// Language definitions used in admin_statistics.php
'PHPinfo disabled message'			=>	'The PHP function phpinfo() has been disabled on this server.',
'Server statistics head'			=>	'Server statistics',
'Server load label'					=>	'服务器负载',
'Server load data'					=>	'%s - 当前有 %s 人在线',
'Environment label'					=>	'环境',
'Environment data OS'				=>	'操作系统： %s',
'Show info'							=>	'显示详细信息',
'Environment data version'			=>	'PHP： %s - %s',
'Environment data acc'				=>	'加速器： %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'数据库',
'Database data rows'				=>	'Rows: %s',
'Database data size'				=>	'Size: %s',

);
