<?php

// Language definitions used in admin-options.php
$lang_admin_options = array(

'Bad HTTP Referer message'			=>	'HTTP_REFERER错误。如果您将论坛从一个目录转到另一个目录或是变更了域名，您需要在数据库中手动更新根目录URL(在config表中的查找o_base_url)然后删除/cache目录下的所有.php文件以清空cache。',
'Must enter title message'			=>	'您必须填写论坛标题。',
'Invalid e-mail message'			=>	'您填写了一个无效的管理信箱地址。',
'Invalid webmaster e-mail message'	=>	'您填写了一个无效的邮件服务信箱地址。',
'SMTP passwords did not match'		=>	'您需要填写并确认有效的SMTP密码以变更密码。',
'Enter announcement here'			=>	'请在此填写公告。',
'Enter rules here'					=>	'请在此填写条款。',
'Default maintenance message'		=>	'论坛维护临时关闭。请稍后访问。',
'Timeout error message'				=>	'“在线超时”的数值必须比“访问超时”小。',
'Options updated redirect'			=>	'配置已更新。正在跳转 …',
'Options head'						=>	'选项',

// Essentials section
'Essentials subhead'				=>	'概要',
'Board title label'					=>	'论坛标题',
'Board title help'					=>	'该论坛的名称(将会显示在每个页面的顶部)。该栏<strong>不可</strong>包含HTML标记。',
'Board desc label'					=>	'论坛描述',
'Board desc help'					=>	'关于该论坛的简短描述(将会显示在每个页面的顶部)。该栏可包含HTML标记。',
'Base URL label'					=>	'根目录网址',
'Base URL help'						=>	'不包含结尾斜杠的完整网址(例如：http://www.mydomain.com/forums)。此处<strong>必须</strong>填写正确才能使所有管理及版主功能运行。如果您收到“错误引用”的报错，此处很可能未填写正确。',
'Base URL problem'          		=>  '您的安装不支持国际域自动转换。因为你的根目录网址包含特殊字符，您<strong>必须</strong>使用在线转换工具来避免 “错误引用” 的错误',
'Timezone label'					=>	'默认时区',
'Timezone help'						=>	'访客以及用户准备在论坛注册时看到的论坛显示时区。',
'DST label'							=>	'夏令时调整',
'DST help'							=>	'检查夏令时是否生效(时间提前1小时)。',
'Language label'					=>	'默认语言',
'Language help'						=>	'访客以及未在其个人资料中更改过语言设置的用户所看到的默认语言。如果您移除了一个语言包，此处必须更新。',
'Default style label'				=>	'默认风格',
'Default style help'				=>	'访客以及未在其个人资料中更改过风格设置的用户所看到的默认风格。',

// Essentials section timezone options
'UTC-12:00'							=>	'(UTC-12:00) 国际日期变更线以西',
'UTC-11:00'							=>	'(UTC-11:00) 纽埃岛，萨摩亚(Niue, Samoa)',
'UTC-10:00'							=>	'(UTC-10:00) 夏威夷阿留申群岛，库克岛(Hawaii-Aleutian, Cook Island)',
'UTC-09:30'							=>	'(UTC-09:30) 马克萨斯群岛(Marquesas Islands)',
'UTC-09:00'							=>	'(UTC-09:00) 阿拉斯加岛，甘比尔(Alaska, Gambier Island)',
'UTC-08:30'							=>	'(UTC-08:30) 皮特凯恩群岛(Pitcairn Islands)',
'UTC-08:00'							=>	'(UTC-08:00) 美国太平洋(Pacific)',
'UTC-07:00'							=>	'(UTC-07:00) 美国山地(Mountain)',
'UTC-06:00'							=>	'(UTC-06:00) 美国中部(Central)',
'UTC-05:00'							=>	'(UTC-05:00) 美国东部(Eastern)',
'UTC-04:00'							=>	'(UTC-04:00) 大西洋(Atlantic)',
'UTC-03:30'							=>	'(UTC-03:30) 纽芬兰(Newfoundland)',
'UTC-03:00'							=>	'(UTC-03:00) 亚马逊，格陵兰中部(Amazon, Central Greenland)',
'UTC-02:00'							=>	'(UTC-02:00) 大西洋中部(Mid-Atlantic)',
'UTC-01:00'							=>	'(UTC-01:00) 亚速尔群岛，佛得角，格陵兰东部(Azores, Cape Verde, Eastern Greenland)',
'UTC'								=>	'(UTC) 西欧，格林尼治(Western European, Greenwich)',
'UTC+01:00'							=>	'(UTC+01:00) 欧洲中部，非洲西部(Central European, West African)',
'UTC+02:00'							=>	'(UTC+02:00) 东欧，非洲中部(Eastern European, Central African)',
'UTC+03:00'							=>	'(UTC+03:00) 莫斯科，非洲东部(Moscow, Eastern African)',
'UTC+03:30'							=>	'(UTC+03:30) 伊朗(Iran)',
'UTC+04:00'							=>	'(UTC+04:00) 萨马拉湾(Gulf, Samara)',
'UTC+04:30'							=>	'(UTC+04:30) 阿富汗(Afghanistan)',
'UTC+05:00'							=>	'(UTC+05:00) 巴基斯坦，叶卡捷琳堡(Pakistan, Yekaterinburg)',
'UTC+05:30'							=>	'(UTC+05:30) 印度，斯里兰卡(India, Sri Lanka)',
'UTC+05:45'							=>	'(UTC+05:45) 尼泊尔(Nepal)',
'UTC+06:00'							=>	'(UTC+06:00) 孟加拉国，不丹，新西伯利亚(Bangladesh, Bhutan, Novosibirsk)',
'UTC+06:30'							=>	'(UTC+06:30) 科科斯群岛，缅甸(Cocos Islands, Myanmar)',
'UTC+07:00'							=>	'(UTC+07:00) 印度支那，克拉斯诺亚尔斯克(Indochina, Krasnoyarsk)',
'UTC+08:00'							=>	'(UTC+08:00) 中国，澳大利亚西部，伊尔库茨克(Greater China, Australian Western, Irkutsk)',
'UTC+08:45'							=>	'(UTC+08:45) 澳大利亚东南部和西部(Southeastern Western Australia)',
'UTC+09:00'							=>	'(UTC+09:00) 日本，韩国，赤塔(Japan, Korea, Chita)',
'UTC+09:30'							=>	'(UTC+09:30) 澳大利亚中部(Australian Central)',
'UTC+10:00'							=>	'(UTC+10:00) 澳大利亚东部，海参崴(Australian Eastern, Vladivostok)',
'UTC+10:30'							=>	'(UTC+10:30) 豪勋爵岛(Lord Howe)',
'UTC+11:00'							=>	'(UTC+11:00) 所罗门岛，马加丹(Solomon Island, Magadan)',
'UTC+11:30'							=>	'(UTC+11:30) 诺福克岛(Norfolk Island)',
'UTC+12:00'							=>	'(UTC+12:00) 新西兰，斐济，堪察加半岛(New Zealand, Fiji, Kamchatka)',
'UTC+12:45'							=>	'(UTC+12:45) 查塔姆群岛(Chatham Islands)',
'UTC+13:00'							=>	'(UTC+13:00) 汤加，凤凰群岛(Tonga, Phoenix Islands)',
'UTC+14:00'							=>	'(UTC+14:00) 莱恩群岛(Line Islands)',

// Timeout Section
'Timeouts subhead'					=>	'时间与超时',
'Time format label'					=>	'时间格式',
'PHP manual'						=>	'PHP手册',
'Time format help'					=>	'[当前格式： %s]. 请至%s查看格式选项。',
'Date format label'					=>	'日期格式',
'Date format help'					=>	'[当前格式： %s]. 请至%s查看格式选项。',
'Visit timeout label'				=>	'访问超时',
'Visit timeout help'				=>	'用户前次访问数据更新后要计算新访问必须空闲的秒数(主要影响新帖提示功能)。',
'Online timeout label'				=>	'在线超时',
'Online timeout help'				=>	'用户被移出在线列表前必须空闲的秒数。',
'Redirect time label'				=>	'重定向时间',
'Redirect time help'				=>	'跳转前必须等待的秒数。如果设置为0，跳转页面将不会出现(不推荐)。',

// Display Section
'Display subhead'					=>	'显示',
'Version number label'				=>	'版本号',
'Version number help'				=>	'在页脚显示FluxBB的版本号。',
'Info in posts label'				=>	'发帖用户相关信息',
'Info in posts help'				=>	'在用户所发帖子中的用户名下显示发帖用户的相关信息。这些信息包括所在地，注册日期，发帖数以及联系链接(电子信箱和网址)。',
'Post count label'					=>	'用户发帖数统计',
'Post count help'					=>	'显示用户所发表的帖子数目统计(涉及浏览帖子页面，个人资料页面以及用户列表页面)。',
'Smilies label'						=>	'帖内表情',
'Smilies help'						=>	'将帖子中的特定符号转换为表情小图标。',
'Smilies sigs label'				=>	'签名内表情',
'Smilies sigs help'					=>	'将用户签名中的特定符号转换为表情小图标。',
'Clickable links label'				=>	'转换网址为链接',
'Clickable links help'				=>	'启用后，FluxBB将自动侦测发帖中包含的所有网址格式并将其转换为超链接。',
'Topic review label'				=>	'主题回顾',
'Topic review help'					=>	'发帖时显示旧帖回放的最大数目(最新帖子靠前)。设为0禁用。',
'Topics per page label'				=>	'每页主题',
'Topics per page help'				=>	'一个版块中每页面默认显示的主题数目。用户可自定义该数值。',
'Posts per page label'				=>	'每页帖子',
'Posts per page help'				=>	'一个主题中每页面默认显示的帖子数目。用户可自定义该数值。',
'Indent label'						=>	'缩进宽度',
'Indent help'						=>	'如果设为8，在[code][/code]标签中的文本显示时将使用一个规则的tab，否则即以设置值数个空格缩进文本。',
'Quote depth label'					=>	'[quote] 标签引用深度',
'Quote depth help'					=>	'[quote] 标签能够包含更多 [quote] 标签的最大次数，当引用深度超出设置值时将被丢弃。',

// Features section
'Features subhead'					=>	'特征',
'Quick post label'					=>	'快速回复',
'Quick post help'					=>	'启用后，FluxBB将在主题下添加一个快速发表回复的表单。通过它用户便可在查看主题时直接发表回复。',
'Users online label'				=>	'在线统计',
'Users online help'					=>	'在首页显示正在浏览论坛的访客及注册用户统计信息。',
'Censor words label'				=>	'词汇过滤',
'Censor words help'					=>	'该功能可帮助论坛过滤敏感词汇。参见%s查看更多信息。',
'Signatures label'					=>	'签名',
'Signatures help'					=>	'允许用户在他们的帖子下附加签名。',
'User has posted label'				=>	'已参与帖子标记',
'User has posted help'				=>	'该功能可实现让当前登录用户通过主题前面的小点识别已参与过的主题。服务器负载过高时建议禁用。',
'Topic views label'					=>	'主题浏览次数',
'Topic views help'					=>	'跟踪主题被浏览的次数。论坛繁忙服务器负载过高时建议禁用。',
'Quick jump label'					=>	'快速跳转',
'Quick jump help'					=>	'启用快速跳转(跳转版块)下拉列表。',
'GZip label'						=>	'GZip压缩输出',
'GZip help'							=>	'启用后，FluxBB会将输出经gzip压缩后再发送给浏览器。这将会节约宽带使用，但是会稍耗点CPU。此功能要求PHP以zlib (--with-zlib)配置。注意：如果您已经有一个Apache的mod_gzip模块或mod_deflate模块设置为压缩PHP脚本，您应禁用该功能。',
'Search all label'					=>	'搜索所有版块',
'Search all help'					=>	'禁用后，每次搜索只可针对一个版块。当过度搜索导致服务器负载过高时应禁用该功能。',
'Menu items label'					=>	'附加菜单项',
'Menu items help'					=>	'在文本框中填写HTML超链接，可实现将菜单项添加到所有页面的导航菜单中的任一排位数。添加新链接的格式为X = &lt;a href="URL"&gt;LINK&lt;/a&gt;，X表示在第几位插入该链接(例如：0表示插入到最前面而2表示插入到“用户列表”的后面)。每行填写一条。',

// Feeds section
'Feed subhead'						=>	'联合供稿',
'Default feed label'				=>	'默认订阅类型',
'Default feed help'					=>	'选择要显示的供稿订阅的类型。注意：选择无并不能关闭订阅，只表示默认不显示。',
'None'								=>	'无',
'RSS'								=>	'RSS',
'Atom'								=>	'Atom',
'Feed TTL label'					=>	'订阅的缓存时间',
'Feed TTL help'						=>	'订阅可使用缓存，以减少订阅所消耗的资源。',
'No cache'							=>	'不使用缓存',
'Minutes'							=>	'%d 分',

// Reports section
'Reports subhead'					=>	'举报',
'Reporting method label'			=>	'接受举报模式',
'Internal'							=>	'内部',
'By e-mail'							=>	'电子信箱',
'Both'								=>	'兼选',
'Reporting method help'				=>	'选择主题/帖子举报的处理方式。您可选择以内部举报系统处理举报，也可选择将举报发送到信箱列表(参见下文)，或者两者兼选。',
'Mailing list label'				=>	'信箱列表',
'Mailing list help'					=>	'以逗号分隔的用来接受邮件的信箱列表。这份名单是举报的收件人。',

// Avatars section
'Avatars subhead'					=>	'头像',
'Use avatars label'					=>	'用户头像',
'Use avatars help'					=>	'启用后，用户可上传头像，头像显示在用户的头衔之下。',
'Upload directory label'			=>	'上传目录',
'Upload directory help'				=>	'头像上传存在目录(相对于FluxBB的根目录)。必须为PHP开启该目录的写入权限。',
'Max width label'					=>	'最大宽度',
'Max width help'					=>	'头像宽度允许的最大像素(建议设60)。',
'Max height label'					=>	'最大高度',
'Max height help'					=>	'头像高度允许的最大像素(建议设60)。',
'Max size label'					=>	'最大尺寸',
'Max size help'						=>	'头像尺寸允许的最大字节数(建议设10240)。',

// E-mail section
'E-mail subhead'					=>	'电子邮件',
'Admin e-mail label'				=>	'管理信箱',
'Admin e-mail help'					=>	'站点管理员电子信箱地址。',
'Webmaster e-mail label'			=>	'邮件服务信箱',
'Webmaster e-mail help'				=>	'网站发出的所有邮件将会使用该地址为发件人。',
'Forum subscriptions label'			=>	'订阅版块',
'Forum subscriptions help'			=>	'允许用户订阅版块(版块有新主题时接收到提醒邮件)。',
'Topic subscriptions label'			=>	'订阅主题',
'Topic subscriptions help'			=>	'允许用户订阅主题(主题有新回复时接收到提醒邮件)。',
'SMTP address label'				=>	'SMTP服务器地址',
'SMTP address help'					=>	'用来发送邮件的外部SMTP地址。如果某SMTP服务器没有使用默认的25端口，您可指定一个自定义端口号(如：mail.myhost.com:3580)。要使用本地邮件程序请留空。',
'SMTP username label'				=>	'SMTP用户名',
'SMTP username help'				=>	'登录SMTP服务器的用户名。当SMTP服务器要求您提供用户名时请填写(很多服务器<strong>并不</strong>需要身份认证)。',
'SMTP password label'				=>	'SMTP密码',
'SMTP change password help'			=>	'当您需要准备修改或者删除当前所存储的密码前请查看此项。',
'SMTP password help'				=>	'登录SMTP服务器的密码。当SMTP服务器要求您提供密码时请填写(很多服务器<strong>并不</strong>需要身份认证)。填写密码后需重复填写进行确认。',
'SMTP SSL label'					=>	'SMTP使用SSL加密',
'SMTP SSL help'						=>	'为与SMTP服务器的连接使用SSL加密。仅当您的SMTP服务器要求时才需使用并且要您的PHP版本支持SSL。',

// Registration Section
'Registration subhead'				=>	'注册',
'Allow new label'					=>	'允许新用户注册',
'Allow new help'					=>	'控制论坛是否允许新用户注册。若无特殊情况应该开启。',
'Verify label'						=>	'注册验证',
'Verify help'						=>	'启用后，用户注册时将会收到一个随机密码。如果他们认为需要，随后他们便可在其个人资料中修改密码。当用户准备将注册时填写的电子信箱更换为新信箱时，该功能也会要求用户验证新信箱。这是避免滥用注册的有效方法，并且可保证所有用户在其个人资料中填写了“正确的”电子信箱。',
'Report new label'					=>	'报告新注册',
'Report new help'					=>	'启用后，当有新用户在论坛注册时FluxBB将向信箱列表(参见上文)发送通知邮件。',
'Use rules label'					=>	'论坛服务条款',
'Use rules help'					=>	'启用后，用户注册时将被要求必须接受设定的相关条款(内容请在下方填写)。可打开该条款的链接将一直显示在每个页面上方的导航栏中。',
'Rules label'						=>	'请在此处填写您的条款',
'Rules help'						=>	'您可在此填写任何需要让用户在注册前阅读并接受的规则或其他信息。如果您在上面启用了论坛服务条款功能您至少需在这里写点文字，否则它会被关闭。这段文字不会被当作正常的帖子解析所以是可以包含HTML语法的。',
'E-mail default label'				=>	'电子信箱默认设置',
'E-mail default help'				=>	'选择新用户注册时默认的隐私设置。',
'Display e-mail label'				=>	'向其他用户公开您的电子信箱。',
'Hide allow form label'				=>	'隐藏电子信箱，但允许其他用户通过论坛向您发送邮件。',
'Hide both label'					=>	'隐藏电子信箱，并阻止其他用户通过论坛向您发送邮件。',

// Announcement Section
'Announcement subhead'				=>	'公告',
'Display announcement label'		=>	'显示公告',
'Display announcement help'			=>	'启用该功能可将下列消息发布在论坛布告栏。',
'Announcement message label'		=>	'公告内容',
'Announcement message help'			=>	'这段文字不会被当作正常的帖子解析所以是可以包含HTML语法的。',

// Maintenance Section
'Maintenance subhead'				=>	'维护',
'Maintenance mode label'			=>	'维护模式',
'Maintenance mode help'				=>	'启用后，论坛只对管理员开放。该功能用于论坛需要临时挂起维护之时。<strong>警告！论坛处于维护模式时请勿登出。</strong>那会让您再也登录不进来。',
'Maintenance message label'			=>	'维护通知',
'Maintenance message help'			=>	'当论坛处于维护模式时用户访问论坛会看到该消息。如果留空，将显示一条默认通知。这段文字不会被当作正常的帖子解析所以是可以包含HTML语法的。',

);
