<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'			=>	'尚无用户以该用户名注册。如果您想添加一个非针对指定用户的封禁请将用户名栏留空。',
'No user ID message'		=>	'尚无用户注册该用户名。',
'User is admin message'		=>	'用户 %s 是管理员不可被封禁。如果您要封禁一个管理员，请先将其降级。',
'User is mod message'		=>	'用户 %s 是版主不可被封禁。如果您要封禁一个版主，请先将其降级。',
'Must enter message'		=>	'您必须填写一个用户名，一个IP地址或者一个电子信箱(至少其中一项)。',
'Cannot ban guest message'	=>	'访客无法被封禁。',
'Invalid IP message'		=>	'您填写了一个无效的IP/IP段。',
'Invalid e-mail message'	=>	'您填写的电子信箱地址(如：user@domain.com)或局部的电子信箱域名(如：domain.com)无效。',
'Invalid date message'		=>	'您填写了一个无效的届满日期。',
'Invalid date reasons'		=>	'正确的格式是YYYY-MM-DD并且日期必须在今天之后或更远。',
'Ban added redirect'		=>	'封禁添加成功。正在跳转 …' ,
'Ban edited redirect'		=>	'封禁编辑成功。正在跳转 …',
'Ban removed redirect'		=>	'封禁解除成功。正在跳转 …',

'New ban head'				=>	'更新封禁',
'Add ban subhead'			=>	'添加封禁',
'Username label'			=>	'用户名',
'Username help'				=>	'填写一个用户名以将其加入封禁用户(不区分大小写)。',
'Username advanced help'	=>	'填写一个用户名以将其加入封禁用户(不区分大小写)。下一页将让您输入一个自定义的IP和电子信箱。如果你只是想封禁特定的IP/IP段或电子邮件，此处请留空。',

'Ban search head'			=>	'封禁搜索',
'Ban search subhead'		=>	'填写搜索标准',
'Ban search info'			=>	'在数据库中搜索封禁用户。您可填写一项或多项条件以进行搜索。条件中可使用星号(*)作通配符。要显示所有封禁用户请留空。',
'Date help'					=>	'(yyyy-mm-dd)',
'Message label'				=>	'Message',
'Expire after label'		=>	'过期晚于',
'Expire before label'		=>	'过期早于',
'Order by label'			=>	'排列依据',
'Order by username'			=>	'用户名',
'Order by ip'				=>	'IP',
'Order by e-mail'			=>	'电子信箱',
'Order by expire'			=>	'过期日期',
'Ascending'					=>	'升序',
'Descending'				=>	'降序',
'Submit search'				=>	'提交搜索',

'E-mail label'				=>	'电子信箱',
'E-mail help'				=>	'填写您要封禁用户的电子信箱或电子信箱域名(例如：someone@somewhere.com或somewhere.com)。查看功能权限设置中“允许已封禁的电子信箱”可了解更多信息。',
'IP label'					=>	'IP/IP段',
'IP help'					=>	'填写您要封禁用户的IP或IP段(例如：150.11.110.1或150.11.110)。IP地址间以空格分隔。此处自动填写的IP(如果存在)是从数据库中取得的该用户的最后IP。',
'IP help link'				=>	'点击%s查看该用户的IP统计。',
'Ban advanced head'			=>	'封禁高级设置',
'Ban advanced subhead'		=>	'通过IP地址和电子信箱添加封禁',
'Ban message label'			=>	'封禁通知',
'Ban message help'			=>	'填写一条消息，当被封禁的该用户再次来访时他/她将会接收到该通知。',
'Message expiry subhead'	=>	'封禁通知与届满',
'Ban IP range info'			=>	'封禁IP段时请务必谨慎，因为极有可能会有多个用户匹配相同的IP段。',
'Expire date label'			=>	'届满日期',
'Expire date help'			=>	'填写该封禁自动解除的日期(格式：yyyy-mm-dd)。留空表示须手动解封。',

'Results head'				=>	'搜索结果',
'Results username head'		=>	'用户名',
'Results e-mail head'		=>	'Email',
'Results IP address head'	=>	'IP/IP段',
'Results expire head'		=>	'过期',
'Results message head'		=>	'通知',
'Results banned by head'	=>	'封禁操作人',
'Results actions head'		=>	'Actions',
'No match'					=>	'无匹配',
'Unknown'					=>	'未知',

);
