<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'个人资料',
'Section essentials'			=>	'基本设置',
'Section personal'				=>	'身份信息',
'Section messaging'				=>	'即时通讯',
'Section personality'			=>	'个性设置',
'Section display'				=>	'外观显示',
'Section privacy'				=>	'隐私设置',
'Section admin'					=>	'管理',

// Miscellaneous
'Username and pass legend'		=>	'填写您的用户名和密码',
'Personal details legend'		=>	'填写您的身份信息',
'Contact details legend'		=>	'填写您的即时通讯信息',
'User activity'					=>	'用户活动',
'Paginate info'					=>	'填写数字以设置每页显示的主题和帖子的数目。',

// Password stuff
'Pass key bad'					=>	'该密码激活不正确或已过期。请重新申请一个密码。如操作失败请联系论坛管理员',
'Pass updated'					=>	'您的密码已更新。现在您已可用新密码登录。',
'Pass updated redirect'			=>	'密码已更新。正在跳转 …',
'Wrong pass'					=>	'原密码填写错误。',
'Change pass'					=>	'更改密码',
'Change pass legend'			=>	'填写并重复填写您的新密码',
'Old pass'						=>	'原密码',
'New pass'						=>	'新密码',
'Confirm new pass'				=>	'重复新密码',
'Pass info'						=>	'密码长度至少必需4个字符。并且字符区分大小写。',

// Email stuff
'Email key bad'					=>	'该电子信箱激活密钥不正确或已过期。请重新更改电子信箱。如操作失败请联系论坛管理员',
'Email updated'					=>	'您的电子信箱已更新。',
'Activate email sent'			=>	'一封邮件已发送至您指定的电子信箱，说明如何启用新的电子信箱。如未收到请联系论坛管理员',
'Email legend'					=>	'填写您的新电子信箱',
'Email instructions'			=>	'一封包含激活链接的邮件将会发送至您的新电子信箱。您必须点击该邮件中的链接才能激活您的新电子信箱。',
'Change email'					=>	'更改电子信箱',
'New email'						=>	'新电子信箱',

// Avatar upload stuff
'Avatars disabled'				=>	'管理员已禁用了头像功能。',
'Too large ini'					=>	'指定文件大小超出限制。服务器不允许上传。',
'Partial upload'				=>	'指定文件未能上传完成。请重试。',
'No tmp directory'				=>	'找不到上传文件时必须的PHP临时目录。',
'No file'						=>	'请选定一个文件后再上传。',
'Bad type'						=>	'不支持您正试图上传文件的格式。支持的文件格式为gif, jpeg及png。',
'Too wide or high'				=>	'您尝试上传的文件高度和/或宽度超出允许限制',
'Too large'						=>	'您尝试上传的文件大小超出允许限制',
'pixels'						=>	'像素',
'bytes'							=>	'字节',
'Move failed'					=>	'服务器无法储存上传的文件。请联系论坛管理员',
'Unknown failure'				=>	'未知错误。请重新尝试。',
'Avatar upload redirect'		=>	'头像已上传。正在跳转 …',
'Avatar deleted redirect'		=>	'头像已删除。正在跳转 …',
'Avatar desc'					=>	'头像在您的帖子里会显示在您的用户名下方。它的规格不能大于',
'Upload avatar'					=>	'上传头像',
'Upload avatar legend'			=>	'选定一个头像文件后上传',
'Delete avatar'					=>	'删除用户头像', // only for admins
'File'							=>	'文件',
'Upload'						=>	'上传', // submit button

// Form validation stuff
'Forbidden title'				=>	'您填写的头衔含有禁用词汇。请重新选择头衔名称。',
'Profile redirect'				=>	'个人资料已更新。正在跳转 …',

// Profile display stuff
'Users profile'					=>	'%s 的个人资料',
'Username info'					=>	'用户名： %s',
'Email info'					=>	'电子信箱： %s',
'Posts info'					=>	'帖子： %s',
'Registered info'				=>	'注册时间： %s',
'Last post info'				=>	'上次发帖： %s',
'Last visit info'				=>	'上次登录： %s',
'Show posts'					=>	'显示该用户的所有帖子',
'Show topics'					=>	'显示该用户的所有主题',
'Show subscriptions'			=>	'显示该用户的所有订阅',
'Realname'						=>	'姓名',
'Location'						=>	'所在地',
'Website'						=>	'个人网站',
'Invalid website URL'			=>	'您填写了一个无效的个人网站。',
'Website not allowed'			=>	'您尚未拥有添加网站到您的个人资料的权限。',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'微软账户',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'头像',
'Signature'						=>	'签名',
'Sig max size'					=>	'长度限制： %s 字节 / 行数限制： %s',
'Avatar legend'					=>	'设置您的头像显示选项',
'Avatar info'					=>	'头像是一幅显示在您的帖子中的小图片。您可以点击下面的链接上传一个头像。',
'Change avatar'					=>	'更改头像',
'Signature legend'				=>	'撰写您的签名',
'Signature info'				=>	'签名是一段附加在您的帖子下的文字。您可以填写任何您喜欢的内容。也许您想在这里填写您的座右铭或者您的星座。由您决定啦！如果可用，您可以在您的签名里使用BBCode等功能。在编辑签名前，您应该查看下列功能是可用还是禁用。',
'Sig preview'					=>	'当前签名预览：',
'No sig'						=>	'(暂无签名)',
'Signature quote/code/list/h'	=>	'签名中不允许使用BBCodes的 quote, code, list, 及 heading(h) 标签。',
'Topics per page'				=>	'每页主题',
'Posts per page'				=>	'每页帖子',
'Leave blank'					=>	'留空则使用论坛默认设置。',
'Subscription legend'			=>	'设置您的订阅选项',
'Notify full'					=>	'在邮件订阅通知中包含新帖子的纯文本内容。',
'Auto notify full'				=>	'自动订阅所有您参与过的主题。',
'Show smilies'					=>	'显示表情。',
'Show images'					=>	'显示帖子中的图片。',
'Show images sigs'				=>	'显示签名中的图片。',
'Show avatars'					=>	'显示用户的头像。',
'Show sigs'						=>	'显示用户的签名。',
'Style legend'					=>	'设置您的默认风格',
'Styles'						=>	'风格列表',
'Admin note'					=>	'管理员注',
'Pagination legend'				=>	'填写您的分页选项',
'Post display legend'			=>	'设置浏览帖子选项',
'Post display info'				=>	'如果网速缓慢，禁用这些选项，尤其是禁止显示帖子和签名中的图片，将加快页面的载入速度。',
'Instructions'					=>	'当您提交更新个人资料后，您将被重定向回此页面。',

// Administration stuff
'Group membership legend'		=>	'选择用户组',
'Save'							=>	'保存',
'Set mods legend'				=>	'设置版主权限',
'Moderator in info'				=>	'选择相应的论坛版块以允许该用户行使版主权限。注意：该设置仅对版主有效。管理员是默认拥有所有版块的全部管理权限的。',
'Update forums'					=>	'更新论坛设置',
'Delete ban legend'				=>	'删除 (administrators only) 或阻止用户',
'Delete user'					=>	'删除用户',
'Ban user'						=>	'阻止用户',
'Confirm delete legend'			=>	'重要：删除用户前必读',
'Confirm delete user'			=>	'确认删除用户',
'Confirmation info'				=>	'请确认您要删除该用户', // the username will be appended to this string
'Delete warning'				=>	'警告：删除用户和/或帖子的操作将无法恢复。如果您此时不删除该用户的帖子，这些帖子将只能通过手动删除。',
'Delete posts'					=>	'删除该用户发表的所有主题和帖子。',
'Delete'						=>	'删除', // submit button (confirm user delete)
'User delete redirect'			=>	'用户已删除。正在跳转 …',
'Group membership redirect'		=>	'用户组成员已保存。正在跳转 …',
'Update forums redirect'		=>	'论坛管理员已成功更新。正在跳转 …',
'Ban redirect'					=>	'正在跳转 …',
'No delete admin message'		=>	'管理员组中的成员不能删除。如要删除该用户，您必须先将其转移到另一个用户组中。'

);
