<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'填写一个有效的电子信箱',
'Email legend 2'			=>	'填写并重复填写一个有效的电子信箱',
'Localisation legend'		=>	'设置您的本地化选项',
'Time zone'					=>	'时区',
'Time zone info'			=>	'要使论坛显示正确的时间，您必须正确地选择当地时区。如果需要，您还须检查是否启用夏令时，以让时间提前1小时。',
'DST'						=>	'夏令时生效 (时间提前1小时)。',
'Time format'				=>	'时间格式',
'Date format'				=>	'日期格式',
'Default'					=>	'默认',
'Language'					=>	'语言',
'Email setting info'		=>	'选择您的电子信箱对其他用户是否可见以及您是否允许其他用户通过论坛(经由电子信箱)向您发送邮件。',
'Email setting 1'			=>	'向其他用户公开您的电子信箱。',
'Email setting 2'			=>	'隐藏电子信箱，但允许其他用户通过论坛向您发送邮件。',
'Email setting 3'			=>	'隐藏电子信箱，并阻止其他用户通过论坛向您发送邮件。',
'Privacy options legend'	=>	'设置隐私选项',
'Confirm pass'				=>	'重复密码',

'Username too short'		=>	'用户名长度至少需要2字节。请重新选择(更长的)用户名。',
'Username too long'			=>	'用户名长度不可超过25字节。请重新选择(更短的)用户名。',
'Username guest'			=>	'该用户名已被访客占用。请重新选择用户名。',
'Username IP'				=>	'用户名不得设为 IP 地址格式。请重新选择用户名。',
'Username reserved chars'	=>	'用户名不可一次包含字符 \'、 " 与 [ 或 ] 。请重新选择用户名。',
'Username BBCode'			=>	'用户名不得包含论坛所使用的样式标签格式 (BBCode) 。请重新选择用户名。',
'Banned username'			=>	'该用户名已被论坛阻止。请重新选择用户名。',
'Pass too short'			=>	'密码长度至少需要4字节。请重新选择(更长的)密码。',
'Pass not match'			=>	'密码不匹配。',
'Banned email'				=>	'该电子信箱已被论坛阻止。请重新选择电子信箱。',
'Dupe email'				=>	'该电子信箱已被其他用户使用。请重新选择电子信箱。',
'Sig too long'				=>	'签名长度不能超过 %1$s 字符。请将您的签名去掉 %2$s 个字符。',
'Sig too many lines'		=>	'签名行数不能超过 %s 行。',
'Bad ICQ'					=>	'您填写了一个无效的 ICQ UIN 号码。请返回修正。',

'UTC-12:00'					=>	'(UTC-12:00) 国际日期变更线以西',
'UTC-11:00'					=>	'(UTC-11:00) 纽埃岛，萨摩亚(Niue, Samoa)',
'UTC-10:00'					=>	'(UTC-10:00) 夏威夷阿留申群岛，库克岛(Hawaii-Aleutian, Cook Island)',
'UTC-09:30'					=>	'(UTC-09:30) 马克萨斯群岛(Marquesas Islands)',
'UTC-09:00'					=>	'(UTC-09:00) 阿拉斯加岛，甘比尔(Alaska, Gambier Island)',
'UTC-08:30'					=>	'(UTC-08:30) 皮特凯恩群岛(Pitcairn Islands)',
'UTC-08:00'					=>	'(UTC-08:00) 美国太平洋(Pacific)',
'UTC-07:00'					=>	'(UTC-07:00) 美国山地(Mountain)',
'UTC-06:00'					=>	'(UTC-06:00) 美国中部(Central)',
'UTC-05:00'					=>	'(UTC-05:00) 美国东部(Eastern)',
'UTC-04:00'					=>	'(UTC-04:00) 大西洋(Atlantic)',
'UTC-03:30'					=>	'(UTC-03:30) 纽芬兰(Newfoundland)',
'UTC-03:00'					=>	'(UTC-03:00) 亚马逊，格陵兰中部(Amazon, Central Greenland)',
'UTC-02:00'					=>	'(UTC-02:00) 大西洋中部(Mid-Atlantic)',
'UTC-01:00'					=>	'(UTC-01:00) 亚速尔群岛，佛得角，格陵兰东部(Azores, Cape Verde, Eastern Greenland)',
'UTC'						=>	'(UTC) 西欧，格林尼治(Western European, Greenwich)',
'UTC+01:00'					=>	'(UTC+01:00) 欧洲中部，非洲西部(Central European, West African)',
'UTC+02:00'					=>	'(UTC+02:00) 东欧，非洲中部(Eastern European, Central African)',
'UTC+03:00'					=>	'(UTC+03:00) 莫斯科，非洲东部(Moscow, Eastern African)',
'UTC+03:30'					=>	'(UTC+03:30) 伊朗(Iran)',
'UTC+04:00'					=>	'(UTC+04:00) 萨马拉湾(Gulf, Samara)',
'UTC+04:30'					=>	'(UTC+04:30) 阿富汗(Afghanistan)',
'UTC+05:00'					=>	'(UTC+05:00) 巴基斯坦，叶卡捷琳堡(Pakistan, Yekaterinburg)',
'UTC+05:30'					=>	'(UTC+05:30) 印度，斯里兰卡(India, Sri Lanka)',
'UTC+05:45'					=>	'(UTC+05:45) 尼泊尔(Nepal)',
'UTC+06:00'					=>	'(UTC+06:00) 孟加拉国，不丹，新西伯利亚(Bangladesh, Bhutan, Novosibirsk)',
'UTC+06:30'					=>	'(UTC+06:30) 科科斯群岛，缅甸(Cocos Islands, Myanmar)',
'UTC+07:00'					=>	'(UTC+07:00) 印度支那，克拉斯诺亚尔斯克(Indochina, Krasnoyarsk)',
'UTC+08:00'					=>	'(UTC+08:00) 中国，澳大利亚西部，伊尔库茨克(Greater China, Australian Western, Irkutsk)',
'UTC+08:45'					=>	'(UTC+08:45) 澳大利亚东南部和西部(Southeastern Western Australia)',
'UTC+09:00'					=>	'(UTC+09:00) 日本，韩国，赤塔(Japan, Korea, Chita)',
'UTC+09:30'					=>	'(UTC+09:30) 澳大利亚中部(Australian Central)',
'UTC+10:00'					=>	'(UTC+10:00) 澳大利亚东部，海参崴(Australian Eastern, Vladivostok)',
'UTC+10:30'					=>	'(UTC+10:30) 豪勋爵岛(Lord Howe)',
'UTC+11:00'					=>	'(UTC+11:00) 所罗门岛，马加丹(Solomon Island, Magadan)',
'UTC+11:30'					=>	'(UTC+11:30) 诺福克岛(Norfolk Island)',
'UTC+12:00'					=>	'(UTC+12:00) 新西兰，斐济，堪察加半岛(New Zealand, Fiji, Kamchatka)',
'UTC+12:45'					=>	'(UTC+12:45) 查塔姆群岛(Chatham Islands)',
'UTC+13:00'					=>	'(UTC+13:00) 汤加，凤凰群岛(Tonga, Phoenix Islands)',
'UTC+14:00'					=>	'(UTC+14:00) 莱恩群岛(Line Islands)',

);
