<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'用户查找',
'No search permission'				=>	'您不具备使用搜索功能的权限。',
'Search flood'						=>	'您所在的用户组两次搜索之间至少需要间隔 %s 秒。请稍等一会后重新尝试搜索。',
'Search'							=>	'搜索',
'Search criteria legend'			=>	'填写搜索标准',
'Search info'						=>	'按关键词搜索时，可填写一个或多个词语。多个关键词请以空格分隔。支持使用 AND, OR 和 NOT 以缩小搜索范围。按作者搜索时请填写您希望搜索的内容的作者用户名。使用通配符 * 可模糊匹配。',
'Keyword search'					=>	'关键词搜索',
'Author search'						=>	'作者搜索',
'Search in legend'					=>	'选择要搜索的区域',
'Search in info'					=>	'选择您要搜索哪个版块的内容，并选择是要在标题中、帖子中还是包括标题及帖子中搜索匹配项。',
'Search multiple forums info'		=>	'如未选择任何版块，则将搜索整个论坛。',
'Forum search'						=>	'论坛',
'All forums'						=>	'所有版块',
'Search in'							=>	'搜索深度',
'Message and subject'				=>	'包括标题和帖子',
'Message only'						=>	'只搜索帖子',
'Topic only'						=>	'只搜索标题',
'Sort by'							=>	'排列依据',
'Sort order'						=>	'排列次序',
'Search results legend'				=>	'选择搜索结果的样式',
'Search results info'				=>	'您可以选择搜索结果的排序方式及显示样式。',
'Sort by post time'					=>	'发帖时间',
'Sort by author'					=>	'作者',
'Sort by subject'					=>	'标题',
'Sort by forum'						=>	'版块',
'Ascending'							=>	'升序',
'Descending'						=>	'降序',
'Show as'							=>	'显示样式',
'Show as topics'					=>	'主题式',
'Show as posts'						=>	'帖子式',

// Results
'Search'							=>	'搜索',
'Search results'					=>	'搜索结果',
'Quick search show_new'				=>	'已更新',
'Quick search show_recent'			=>	'活跃中',
'Quick search show_unanswered'		=>	'无回复',
'Quick search show_replies'			=>	'已参与',
'Quick search show_user_topics'		=>	'%s 发表的主题',
'Quick search show_user_posts'		=>	'%s 发表的帖子',
'Quick search show_subscriptions'	=>	'%s 订阅的内容',
'By keywords show as topics'		=>	'包含关键词 \'%s\' 的主题',
'By keywords show as posts'			=>	'包含关键词 \'%s\' 的帖子',
'By user show as topics'			=>	'由 %s 发表的主题',
'By user show as posts'				=>	'由 %s 发表的帖子',
'By both show as topics'			=>	'由 %s 发表的、包含关键词 \'%s\' 的主题',
'By both show as posts'				=>	'由 %s 发表的、包含关键词 \'%s\' 的帖子',
'No terms'							=>	'您至少需要填写一个关键词和/或一个作者用户名才能进行搜索。',
'No hits'							=>	'您的搜索没有返回结果。',
'No user posts'						=>	'指定版块中没有该用户的帖子。',
'No user topics'					=>	'指定版块中没有该用户的主题。',
'No subscriptions'					=>	'该用户目前尚未订阅任何主题。',
'No new posts'						=>	'自您上次登录后未出现新帖子。',
'No recent posts'					=>	'最近24小时内未出现任何新帖子。',
'No unanswered'						=>	'暂无未回复的主题。',
'Go to post'						=>	'前往帖子',
'Go to topic'						=>	'前往主题'

);
