<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'			=>	'Engin notandi með þessu notendanafni er skráður. Ef þú vilt bæta við banni sem er ekki tengt ákveðnu notendanafni hafðu þá notendanafnið autt.',
'No user ID message'		=>	'Engin notandi með þetta ID skráður.',
'User is admin message'		=>	'Notandinn %s er stjórnandi og ekki er hægt að banna hann. Ef þú vilt banna stjórnandi þarftu fyrst að lækka hann í tign niður í umsjónarmann eða almennan notanda.',
'Must enter message'		=>	'Þú þarft annað hvort að slá inn notendanafn, IP tölu eða netfang.',
'Cannot ban guest message'	=>	'Ekki er hægt að banna gesta notandann.',
'Invalid IP message'		=>	'Þú slóst inn ógilda IP tölu/IP tölubil.',
'Invalid e-mail message'	=>	'Netfangið (s.s. user@domain.com) eða netfangshlutinn (s.s. domain.com) sem þú slóst inn er ógildur.',
'Invalid date message'		=>	'Þú slóst inn ógilda dagsetningu.',
'Invalid date reasons'		=>	'Sniðið ætti að vera ÁÁÁÁ-MM-DD og dagsetningin þarf að vera a.m.k. einn dag fram í tímann.',
'Ban added redirect'		=>	'Banni bætt við. Áframsendi …' ,
'Ban edited redirect'		=>	'Banni breytt. Áframsendi …',
'Ban removed redirect'		=>	'Bann fjarlægt. Áframsendi …',

'New ban head'				=>	'Nýtt bann',
'Add ban subhead'			=>	'Bæta við banni',
'Username label'			=>	'Notendanafn',
'Username help'				=>	'Notendanafnið sem á að banna (há- og lágstafir skipta ekki máli).',
'Username advanced help'	=>	'Notendanafnið sem á að banna (há- og lágstafir skipta ekki máli). Næsta síðan leyfir þér að slá inn IP tölu og netfang. Ef þú vilt banna ákveðna IP tölu/IP svið eða netfang skyldu það þá eftir tómt.',

'Ban search head'			=>	'Leita að banni',
'Ban search subhead'		=>	'Sláðu inn leitarskilyrði',
'Ban search info'			=>	'Leita að bönnum í gagnagrunninum. Þú getur slegið inn eitt eða fleiri gildi til að leita eftir. Gosar (e.wildcards) á forminu stjörnur (*) eru leyfðir.',
'Date help'					=>	'(áááá-mm-dd)',
'Message label'				=>	'Skilaboð',
'Expire after label'		=>	'Fyrnist eftir',
'Expire before label'		=>	'Fyrnist fyrir',
'Order by label'			=>	'Raða eftir',
'Order by username'			=>	'Notendanafni',
'Order by ip'				=>	'IP tölu',
'Order by e-mail'			=>	'Netfang',
'Order by expire'			=>	'Fyrningardagsetningu',
'Ascending'					=>	'Hækkandi',
'Descending'				=>	'Lækkandi',
'Submit search'				=>	'Leita',

'E-mail label'				=>	'Netfang',
'E-mail help'				=>	'Netfangið eða lénið sem þú vilt banna (t.d. someone@somewhere.com or somewhere.com). Sjá "Leyfa bönnuð netföng" í Aðgangur fyrir nánari upplýsingar.',
'IP label'					=>	'IP tala/IP svið',
'IP help'					=>	'IP talan eða IP sviðið sem þú vilt banna (t.d. 150.11.110.1 eða 150.11.110). Aðskildu tölurnar með bili. Ef að IP tala er nú þegar útfyllt þá er það síðasta þekkta IP tala notandans í gagnagrunninum.',
'IP help link'				=>	'Smelltu á %s til að sjá IP tölfræði notandans.',
'Ban advanced head'			=>	'Nánari stillingar banns',
'Ban advanced subhead'		=>	'Auka við bann með IP tölu og netfangi',
'Ban message label'			=>	'Bann skilaboð',
'Ban message help'			=>	'Skilaboð sem birtast bönnuðum notanda þegar hann reynir að heimsækja spjallborðið.',
'Message expiry subhead'	=>	'Bann skilaboð og fyrningardagur',
'Ban IP range info'			=>	'Þú þarft að vera varkár þegar IP svið er bannað vegna möguleikans á að margir notendur sé með hluta af sömu IP tölunni.',
'Expire date label'			=>	'Fyrningardagur',
'Expire date help'			=>	'Dagurinn sem bannið er sjálfkrafa fjarlægt (snið: áááá-mm-dd). Skiljið eftir tómt ef fjarlægja á bannið handvirkt.',

'Results head'				=>	'Leitarniðurstöður',
'Results username head'		=>	'Notendanafn',
'Results e-mail head'		=>	'Netfang',
'Results IP address head'	=>	'IP tala/IP svið',
'Results expire head'		=>	'Fyrnist',
'Results message head'		=>	'Skilaboð',
'Results banned by head'	=>	'Bannað af',
'Results actions head'		=>	'Aðgerðir',
'No match'					=>	'Engin samsvörun',
'Unknown'					=>	'Óþekkt',

);
