<?php

// Language definitions used in admin-users.php
$lang_admin_users = array(

'Non numeric message'		=>	'Þú slóst inn gildi sem var ekki tala í dálk sem tekur bara tölur.',
'Invalid date time message'	=>	'Þú slóst inn ógilda dagsetningu/tíma.',
'Not verified'				=>	'Leit að notanda',
'User search head'			=>	'Leit að notanda',
'User search subhead'		=>	'Sláðu inn leitarskilyrði',
'User search info'			=>	'Leit að notendum í gagnagrunninum. Þú getur slegið inn eitt eða fleiri gildi til að leita eftir. Gosar (e.wildcards) í formi stjörnu (*) eru leyfðir.',
'Username label'			=>	'Notandanafn',
'E-mail address label'		=>	'Netfang',
'Title label'				=>	'Titill',
'Real name label'			=>	'Nafn',
'Website label'				=>	'Vefsíða',
'Jabber label'				=>	'Jabber',
'ICQ label'					=>	'ICQ',
'MSN label'					=>	'MSN Messenger',
'AOL label'					=>	'AOL IM',
'Yahoo label'				=>	'Yahoo Messenger',
'Location label'			=>	'Frá',
'Signature label'			=>	'Undirskrift',
'Admin note label'			=>	'Stjórnandi ath',
'Posts more than label'		=>	'Fjöldi pósta meira en',
'Posts less than label'		=>	'Fjöldi pósta færri en',
'Last post after label'		=>	'Síðasti póstur er eftir',
'Date help'					=>	'(yyyy-mm-dd hh:mm:ss)',
'Last post before label'	=>	'Síðasti póstur er fyrir',
'Registered after label'	=>	'Skráður eftir',
'Registered before label'	=>	'Skráður fyrir',
'Order by label'			=>	'Raða eftir',
'Order by username'			=>	'Notendanafni',
'Order by e-mail'			=>	'Netfangi',
'Order by posts'			=>	'Fjölda pósta',
'Order by last post'		=>	'Síðasta pósti',
'Order by registered'		=>	'Skráningu',
'Ascending'					=>	'Hækkandi',
'Descending'				=>	'Lækkandi',
'User group label'			=>	'Notendahópi',
'All groups'				=>	'Allir hópar',
'Unverified users'			=>	'Óstaðfestir notendur',
'Submit search'				=>	'Leita',
'IP search head'			=>	'IP leit',
'IP search subhead'			=>	'Sláðu inn IP tölu til að leita eftir',
'IP address label'			=>	'IP tala',
'IP address help'			=>	'IP talan til að leita eftir í gagnagrunninum.',
'Find IP address'			=>	'Finna IP tölu',

'Results head'				=>	'Leitarniðurstöður',
'Results username head'		=>	'Notendanafn',
'Results e-mail head'		=>	'Netfang',
'Results title head'		=>	'Titill/Staða',
'Results posts head'		=>	'Póstar',
'Results admin note head'	=>	'Stjórnandi ath',
'Results actions head'		=>	'Aðgerðir',
'Results IP address head'	=>	'IP tala',
'Results last used head'	=>	'Síðast notað',
'Results times found head'	=>	'Fjöldi skipta',
'Results action head'		=>	'Aðgerð',
'Results find more link'	=>	'Finna fleiri notendur með þessa IP tölu',
'Results no posts found'	=>	'Eins og er þá eru engir póstar eftir notandann í spjallborðinu.',
'Bad IP message'			=>	'Uppgefna IP talan er ekki á réttu sniði.',
'Results view IP link'		=>	'Sýna IP tölfræði',
'Results show posts link'	=>	'Sýna pósta',
'Results guest'				=>	'Gestur',
'Results no IP found'		=>	'Ekki tókst að finna IP töluna í gagnagrunninum.',
'No match'					=>	'Engin samsvörun'

);
