<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'Ekki tókst að kanna með uppfærslu þar sem \'allow_url_fopen\' er óvirkt á vefþjóninum.',
'Upgrade check failed message'		=>	'Könnun á uppfærslu mistókst af óþekktum ástæðum.',
'Running latest version message'	=>	'Þú ert að keyra nýjustu útgáfuna af FluxBB.',
'New version available message'		=>	'Ný útgáfa af FluxBB hefur verið gefin út. Þú getur niðurhalað nýjustu útgáfunni frá %s.',
'PHPinfo disabled message'			=>	'PHP fallið phpinfo() er óvirkt á vefþjóninum.',
'Not available'						=>	'Ekki í boði',
'Forum admin head'					=>	'Stjórnun spjallborðs',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'Velkomin(n) í stjórnendahluta FluxBB. Héðan getur þú stjórnað mikilvægum hlutum spjallsins. Eftir því hvort þú ert stjórnandi eða umsjónarmaður getur þú:',
'Welcome 1'							=>	'Skipulagt flokka og spjallborð.',
'Welcome 2'							=>	'Stjórnað stillingum spjallborðsins.',
'Welcome 3'							=>	'Stjórnað aðgangi notenda og gesta.',
'Welcome 4'							=>	'Séð IP tölfræði notenda.',
'Welcome 5'							=>	'Bannað notendur.',
'Welcome 6'							=>	'Ritskoðað orð.',
'Welcome 7'							=>	'Stillt stöður notenda.',
'Welcome 8'							=>	'Tekið til í eldri póstum.',
'Welcome 9'							=>	'Unnið með tilkynningar.',
'Statistics head'					=>	'Tölfræði',
'FluxBB version label'				=>	'FluxBB útgáfa',
'Check for upgrade'					=>	'Kanna uppfærslu',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'Álag á vefþjón',
'Server load data'					=>	'%s - %s notendur innskráðir',
'Environment label'					=>	'Umhverfi',
'Environment data OS'				=>	'Stýrikerfi: %s',
'Show info'							=>	'Sýna upplýsingar',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Hraðall: %s',
'Turck MMCache'						=>	'Turk MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Gagnagrunnur',
'Database data rows'				=>	'Raðir: %s',
'Database data size'				=>	'Stærð: %s',

);
