<?php

// Language definitions used in admin-groups.php
$lang_admin_groups = array(

'Must enter title message'		=>	'Þú verður að skýra notendahópinn.',
'Title already exists message'	=>	'Það er nú þegar hópur með þessu nafni <strong>%s</strong>.',
'Default group redirect'		=>	'Sjálfgefin hópur stilltur. Áframsendi …',
'Cannot remove default message'	=>	'Ekki er hægt að fjarlægja sjálfgefin hóp. Til að eyða þessum hópi verðurðu fyrst að gera annan hóp að þeim sjálfgefna.',
'Group removed redirect'		=>	'Hópur fjarlægður. Áframsendi …',
'Group added redirect'			=>	'Hóp bætt við. Áframsendi …',
'Group edited redirect'			=>	'Hóp breytt. Áframsendi …',

'Add groups head'				=>	'Uppsetning hópa',
'Add group subhead'				=>	'Bæta við nýjum hóp',
'New group label'				=>	'Byggja nýjan hóp á',
'New group help'				=>	'Veldu notendahóp sem nýji hópurinn erfir réttindi frá. Næsta síða leyfir þér að fínstilla réttindin.',
'Default group subhead'			=>	'Velja sjálfgefin hóp',
'Default group label'			=>	'Sjálfgefin hópur',
'Default group help'			=>	'Þetta er sjálfgefin notendahópur, s.s. hópurinn sem notendur eru settir í þegar þeir skrá sig. Af öryggis ástæðum er ekki hægt að setja notendur sjálfgefið í umsjónarmanna- eða stjórnendahópa.',
'Existing groups head'			=>	'Núverandi hópar',
'Edit groups subhead'			=>	'Breyta/eyða hópum',
'Edit groups info'				=>	'Fyrirfram skilgreindu hóparnir Guests, Administrators, Moderators og Members er ekki hægt að fjarlægja. Hins vegar er hægt að breyta þeim. Vinsamlegast athugið að í sumum hópum eru ekki allir möguleikarnir í boði, t.d. <em>breyta póstum</em> möguleikinn fyrir gesti. Stjórnendur hafa alltaf full réttindi.',
'Edit link'						=>	'Breyta',
'Delete link'					=>	'Eyða',
'Group delete head'				=>	'Hóp eytt',
'Confirm delete subhead'		=>	'Staðfesta eyðingu hóps',
'Confirm delete info'			=>	'Ertu viss um að þú viljir eyða hópnum <strong>%s</strong>?',
'Confirm delete warn'			=>	'AÐVÖRUN! Eftir að þú eyðir hóp getur þú ekki endurvakið hann.',
'Delete group head'				=>	'Eyða hóp',
'Move users subhead'			=>	'Færa notendur sem eru í hópnum',
'Move users info'				=>	'Hópurinn <strong>%s</strong> hefur núna <strong>%s</strong> notendur. Vinsamlegast veldu hóp sem þessir notendur verða settir í við eyðingu.',
'Move users label'				=>	'Færa notendur í',
'Delete group'					=>	'Eyða hóp',

'Group settings head'			=>	'Hópstillingar',
'Group settings subhead'		=>	'Uppsetning stillinga og aðgangs fyrir hópa',
'Group settings info'			=>	'Fyrir neðan stillingar og aðgang eru sjálfgefni aðgangurinn fyrir notendahópinn. Þessar stillingar taka gildi ef engin ákveðinn aðgangur er í gildi.',
'Group title label'				=>	'Nafn hóps',
'User title label'				=>	'Titill notenda',
'User title help'				=>	'Þessi titill yfirskrifar þá stöðu sem notandi í þessum hópi hefur. Fyllið ekki út til að nota sjálfgefin titil eða stöðu.',
'Mod privileges label'			=>	'Gefa notendum umsjónarmannaréttindi',
'Mod privileges help'			=>	'Til að notandi í þessum hópi fái umsjónarmannaréttindi þá þarf að úthluta honum einu eða fleiru spjalli. Þetta er gert í stjórnendahluta fyrir stillingar viðkomandi notanda.',
'Edit profile label'			=>	'Leyfa umsjónarmönnum að breyta stillingum notenda',
'Edit profile help'				=>	'Ef umsjónarmannastillingar eru leyfðar þá geta meðlimir í þessum hópi breytt stillingum notenda.',
'Rename users label'			=>	'Leyfa umsjónarmönnum að endurskíra notendur',
'Rename users help'				=>	'Ef umsjónarmannastillingar eru leyfðar þá geta meðlimir í þessum hópi endurskírt notendur.',
'Change passwords label'		=>	'Leyfa umsjónarmönnum að breyta lykilorðum',
'Change passwords help'			=>	'Ef umsjónarmannastillingar eru leyfðar þá geta meðlimir í þessum hópi breytt lykilorðum notenda.',
'Ban users label'				=>	'Leyfa umsjónarmönnum að banna notendur',
'Ban users help'				=>	'Ef umsjónarmannastillingar eru leyfðar þá geta meðlimir í þessum hópi bannað notendur.',
'Read board label'				=>	'Lesa spjall',
'Read board help'				=>	'Leyfa meðlimum í þessum hóp að skoða spjallið. Þessi stilling á við allt borðið og þess vegna er ekki hægt að yfirskrifa með stillingum fyrir ákveðin spjallborð. Ef þetta er sett á "Nei" þá geta meðlimir í þessum hóp einungis innskráð/útskráð og nýskráð sig.',
'View user info label'			=>	'Skoða notendaupplýsingar',
'View user info help'			=>	'Leyfa meðlimum í þessum hóp að skoða notendalista og stillingar.',
'Post replies label'			=>	'Pósta svörum',
'Post replies help'				=>	'Leyfa meðlimum í þessum hóp að pósta svörum við þráðum.',
'Post topics label'				=>	'Pósta þráðum',
'Post topics help'				=>	'Leyfa meðlimum í þessum hóp að pósta þráðum.',
'Edit posts label'				=>	'Breyta póstum',
'Edit posts help'				=>	'Leyfa meðlimum í þessum hóp að breyta sínum eigin póstum.',
'Delete posts label'			=>	'Eyða póstum',
'Delete posts help'				=>	'Leyfa meðlimum í þessum hóp að eyða sínum eigin póstum.',
'Delete topics label'			=>	'Eyða þráðum',
'Delete topics help'			=>	'Leyfa meðlimum í þessum hóp að eyða sínum þráðum(og öllum svörum).',
'Set own title label'			=>	'Breyta eigin titli',
'Set own title help'			=>	'Leyfa meðlimum í þessum hóp að breyta eigin titli.',
'User search label'				=>	'Nota leitina',
'User search help'				=>	'Leyfa meðlimum í þessum hóp að að nota leitina.',
'User list search label'		=>	'Leita í notendalista',
'User list search help'			=>	'Leyfa meðlimum í þessum hóp að leita að notendum í notendalistanum.',
'Send e-mails label'			=>	'Senda tölvupóst',
'Send e-mails help'				=>	'Leyfa meðlimum í þessum hóp að senda tölvupóst til annara notenda.',
'Post flood label'				=>	'Póstflóðabil',
'Post flood help'				=>	'Fjöldi sekúndna sem meðlimir í þessum hóp þurfa að bíða á milli pósta. Stillið á 0 til að gera óvirkt.',
'Search flood label'			=>	'Leitarflóðabil',
'Search flood help'				=>	'Fjöldi sekúndna sem meðlimir í þessum hóp þurfa að bíða á milli leita. Stillið á 0 til að gera óvirkt.',
'E-mail flood label'			=>	'Tölvupóstflóðabil',
'E-mail flood help'				=>	'Fjöldi sekúndna sem meðlimir í þessum hóp þurfa að bíða á milli tölvupóstsendinga. Stillið á 0 til að gera óvirkt.',
'Moderator info'				=>	'Til að notandi í þessum hópi fái umsjónarmannaréttindi þá þarf að úthluta honum einu eða fleiru spjalli. Þetta er gert í stjórnendahluta fyrir stillingar viðkomandi notanda.',

);