<?php

// Language definitions used in admin-options.php
$lang_admin_options = array(

'Bad HTTP Referer message'			=>	'Bad HTTP_REFERER. Ef þú hefur fært spjallborðið frá einni staðsetningu til annarrar eða skipt um lén þá þarftu að uppfæra Base URL handvirkt í gagnagrunninum (leitaðu að o_base_url í config töflunni) og eyddu svo úr biðminninum með því að eyða öllum .php skrám í /cache möppunni.',
'Must enter title message'			=>	'Þú verður að fylla út nafn spjallsins.',
'Invalid e-mail message'			=>	'Netfang stjórnanda sem þú slóst inn er ekki gilt.',
'Invalid webmaster e-mail message'	=>	'Netfang vefstjóra sem þú slóst inn er ekki gilt.',
'Enter announcement here'			=>	'Settu tilkynninguna þína hér.',
'Enter rules here'					=>	'Settu reglurnar þínar hér.',
'Default maintenance message'		=>	'Spjallborðið liggur niðri vegna viðhalds. Vinsamlegast reynið aftur eftir nokkrar mínútur.',
'Timeout error message'				=>	'Gildi "Timeout online" þarf að vera minna en "Timeout visit".',
'Options updated redirect'			=>	'Stillingar uppfærðar. Áframsendi …',
'Options head'						=>	'Stillingar',

// Essentials section
'Essentials subhead'				=>	'Nauðsynjar',
'Board title label'					=>	'Nafn spjalls',
'Board title help'					=>	'Nafn spjallsins (birtist efst á hverri síðu). Hér má <strong>ekki</strong> nota HTML.',
'Board desc label'					=>	'Lýsing spjallsins',
'Board desc help'					=>	'Stutt lýsing á spjallinu (birtist efst á hverri síðu).Hér má nota HTML.',
'Base URL label'					=>	'Base URL',
'Base URL help'						=>	'Öll vefslóð spjallins án skástriks (t.d. http://www.mydomain.com/forums). Þetta <strong>verður</strong> að vera rétt svo stjórnunar- og umsjónarhlutir virki. Ef þú sérð "Bad referer" villur þá er þetta sennilega vitlaust.',
'Timezone label'					=>	'Sjálfgefið tímabelti',
'Timezone help'						=>	'Sjálfgefið tímabelti fyrir gesti og notendur sem reyna að skrá sig á spjallið.',
'DST label'							=>	'Lagfæra vegna DST(dagljósatími)',
'DST help'							=>	'Hakið við ef dagljósatími er í gildi (flýtir klukkunni um 1 klukkutíma).',
'Language label'					=>	'Sjálfgefið tungumál',
'Language help'						=>	'Sjálfgefið tungumál fyrir gesti og notendur sem hafa ekki breytt sjálfgefnu gildi í sínum stillingum. Ef þú fjarlægir tungumálapakka þá þarf að uppfæra þetta.',
'Default style label'				=>	'Sjálfgefinn stíll',
'Default style help'				=>	'Sjálfgefinn stíll fyrir gesti go notendur sem hafa ekki breytt sjálfgefnu gildí í sínum stillingum.',

// Essentials section timezone options
'UTC-12:00'							=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'							=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'							=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'							=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'							=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'							=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'							=>	'(UTC-08:00) Pacific',
'UTC-07:00'							=>	'(UTC-07:00) Mountain',
'UTC-06:00'							=>	'(UTC-06:00) Central',
'UTC-05:00'							=>	'(UTC-05:00) Eastern',
'UTC-04:00'							=>	'(UTC-04:00) Atlantic',
'UTC-03:30'							=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'							=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'							=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'							=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'								=>	'(UTC) Ísland, Western European, Greenwich',
'UTC+01:00'							=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'							=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'							=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'							=>	'(UTC+03:30) Iran',
'UTC+04:00'							=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'							=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'							=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'							=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'							=>	'(UTC+05:45) Nepal',
'UTC+06:00'							=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'							=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'							=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'							=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'							=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'							=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'							=>	'(UTC+09:30) Australian Central',
'UTC+10:00'							=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'							=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'							=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'							=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'							=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'							=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'							=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'							=>	'(UTC+14:00) Line Islands',

// Timeout Section
'Timeouts subhead'					=>	'Tími og tímamörk',
'Time format label'					=>	'Tímasnið',
'PHP manual'						=>	'PHP handbók',
'Time format help'					=>	'[Núverandi snið: %s]. Sjá %s fyrir sniðmöguleika.',
'Date format label'					=>	'Dagsnið',
'Date format help'					=>	'[Núverandi snið: %s]. Sjá %s fyrir sniðmöguleika.',
'Visit timeout label'				=>	'Tímamörk heimsóknar',
'Visit timeout help'				=>	'Fjöldi sekúndna sem notandi þarf að vera iðjulaus áðurn en upplýsingar um síðustu heimsókn hans eru uppfærðar (hefur aðallega áhrif á ný skilaboð merkingarnar).',
'Online timeout label'				=>	'Tímamörk innskráningarlista',
'Online timeout help'				=>	'Fjöldi sekúndna sem notandi þarf að vera iðjulaus áðurn en hann er fjarlægður úr innskráningarlistanum.',
'Redirect time label'				=>	'Áframsendingartími',
'Redirect time help'				=>	'Fjöldi sekúndna til að bíða þegar notandi er áframsendur. Ef þetta er stillt á 0 þá er engin áframsendingarsíða birt (ekki mælt með).',

// Display Section
'Display subhead'					=>	'Birta',
'Version number label'				=>	'Útgáfunúmer',
'Version number help'				=>	'Sýna útgáfunúmer FluxBB í fætinum.',
'Info in posts label'				=>	'Sýna notendaupplýsingar í póstum',
'Info in posts help'				=>	'Sýnir upplýsingar um póstarann undir notendanafninu í þráðasýninni. Upplýsingarnar sem þetta hefur áhrif á eru: frá, skráningardagur, póstfjöldi og tengslatenglarnir (netfang og veffang).',
'Post count label'					=>	'Póstfjöldi notanda',
'Post count help'					=>	'Sýnir fjölda pósta sem notandi hefur gert (hefur áhrif á þráðasýn, stillingar og notendalista).',
'Smilies label'						=>	'Bros í póstum',
'Smilies help'						=>	'Breytir brosum í lítil grafísk tákn.',
'Smilies sigs label'				=>	'Bros í undirskriftum',
'Smilies sigs help'					=>	'Breytir brosum í lítil grafísk tákn í undirskriftum.',
'Clickable links label'				=>	'Gera tengla smellanlega',
'Clickable links help'				=>	'Ef virkt þá mun FluxBB sjálfkrafa skynja vefslóðir í póstum og gera þær að smellanlegum tenglum.',
'Topic review label'				=>	'Forsýn þráða',
'Topic review help'					=>	'Hámarksfjöldi pósta til að sýna þegar verið er að pósta (nýjasti fyrst). Stillið á 0 til að gera óvirkt.',
'Topics per page label'				=>	'Þræðir á síðu',
'Topics per page help'				=>	'Sjálfgefin fjöldi þráða til að birta á síðu í spjallinu. Notendur geta breytt þessari stillingu.',
'Posts per page label'				=>	'Póstar á síðu',
'Posts per page help'				=>	'Sjálfgefin fjöldi pósta til að birta á síðu í þráðum. Notendur geta breytt þessari stillingu.',
'Indent label'						=>	'Lengd inndráttar',
'Indent help'						=>	'Ef þetta er stillt á 8 þá er venjulegt tab notað þegar textinn er birtur innan [code][/code] tagsins. Annars eru þetta mörg bil notuð til að draga textann inn.',
'Quote depth label'					=>	'Hámarksdýpt [quote]',
'Quote depth help'					=>	'Hámarksfjöldi skipta sem quote] tag getur verið innan í öðru [quote] tagi, önnur tög dýpri en þetta verður hent.',

// Features section
'Features subhead'					=>	'Möguleikar',
'Quick post label'					=>	'Flýtipóstur',
'Quick post help'					=>	'Þegar þetta er virkt þá setur FluxBB inn flýtipóst form neðst í þráðunum. Þá geta notendur póstað beint frá þráðasýninni.',
'Users online label'				=>	'Innskráðir notendur',
'Users online help'					=>	'Birtir upplýsingar á forsíðunni um gesti og innskráða notendur sem eru að skoða spjallið þá stundina.',
'Censor words label'				=>	'Ritskoða orð',
'Censor words help'					=>	'Virkjaðu þetta til að ritskoða viss orð á spjallinu. Sjá %s fyrir nánari upplýsingar.',
'Signatures label'					=>	'Undirskriftir',
'Signatures help'					=>	'Leyfa notendum að vera með undirskriftir við sína pósta.',
'User ranks label'					=>	'Staða notenda',
'User ranks help'					=>	'Virkið þetta til að nota stöður notenda. Sjá %s fyrir nánari upplýsingar.',
'User has posted label'				=>	'Notandi hefur póstað áður',
'User has posted help'				=>	'Þessi möguleiki birtir lítinn punkt fyrir framan þræði í viewforum.php ef að innskráður notandi hefur áður póstað í þeim þræði. Aftengið ef vart verður við mikið álag á vefþjóninn.',
'Topic views label'					=>	'Þráða skoðanir',
'Topic views help'					=>	'Heldur utan um fjölda skoðanna sem þráður hefur. Aftengið ef vart verður við mikið álag á vefþjóninn.',
'Quick jump label'					=>	'Hoppa í',
'Quick jump help'					=>	'Virkja hopp möguleikann (hoppa í) í fellivalmyndinni.',
'GZip label'						=>	'GZip sendingar',
'GZip help'							=>	'Ef virkt þá sendir FluxBB gagnastrauminn gzip til vafranna. Þetta dregur úr notkun á bandvíddinni en notar örlítið meira af reiknigetu örgjörvans. Þessi möguleiki þarfnast þess að PHP sé stillt með zlib (--with-zlib). Ath: If þú hefur nú þegar einn af Apache viðbótunum mod_gzip eða mod_deflate uppsetta til að þjappa PHP kóða þá ættirðu ekki að nota þennan möguleika.',
'Search all label'					=>	'Leita í öllum spjallborðum',
'Search all help'					=>	'Þegar þetta er ekki leyft þá er eingöngu hægt að leita í einu spjallborði í einu. Aftengið ef vart verður við mikið álag á vefþjóninn vegna leita.',
'Menu items label'					=>	'Viðbótar valmyndartenglar',
'Menu items help'					=>	'Með því að slá inn HTML tengla í textaboxið þá er hægt að bæta við hvaða fjölda sem er í valmyndina sem er efst á öllum síðum. Sniðið til að bæta við nýjum tenglum er X = &lt;a href="URL"&gt;LINK&lt;/a&gt; þar sem X er staðan sem setja á tengilinn inn á (t.d. 0 til að setja hann fremst og 2 til að setja hann á eftir "Notendur"). Aðskiljið færslur með línubili.',
'Default feed label'				=>	'Sjálfgefin efnisveita',
'Default feed help'					=>	'Veljið gerð sjálfgefinnar efnisveitu. Ath: Ef ekkert er valið þá gerir það efnisveitur ekki óvirkar, það felur þær bara sjónum.',
'None'								=>	'Ekkert',
'RSS'								=>	'RSS',
'Atom'								=>	'Atom',

// Reports section
'Reports subhead'					=>	'Tilkynningar',
'Reporting method label'			=>	'Tilkynningaraðferð',
'Internal'							=>	'Innanvefs',
'By e-mail'							=>	'Tölvupóstur',
'Both'								=>	'Bæði',
'Reporting method help'				=>	'Veldu aðferðina til að meðhöndla tilkynningar um þræði/pósta. Þú getur valið hvort að tilkynningar um þræði/pósta eru meðhöndlaðar innanvefs, sendar á póstlistann (sjá neðar) eða hvort tveggja.',
'Mailing list label'				=>	'Póstlisti',
'Mailing list help'					=>	'Kommu aðskilin listi af áskrifendum. Aðilar á þessum lista fá tilkynningar.',

// Avatars section
'Avatars subhead'					=>	'Passamyndir',
'Use avatars label'					=>	'Nota passamyndir',
'Use avatars help'					=>	'Ef þetta er virkja þá geta notendur upphlaðið passamynd sem birtist undir titli/stöðu þeirra.',
'Upload directory label'			=>	'Upphleðslumappa',
'Upload directory help'				=>	'Upphleðslumappan fyrir passamyndir (í tengslum við FluxBB rótarmöppuna). PHP verður að hafa skrifréttindi í þessa möppu.',
'Max width label'					=>	'Hámarksbreidd',
'Max width help'					=>	'Hámarksbreidd passamyndir í pixlum (mælt með 60).',
'Max height label'					=>	'Hámarkshæð',
'Max height help'					=>	'Hámarkshæð passamynda í pixlum [mælt með 60).',
'Max size label'					=>	'Hámarksstærð',
'Max size help'						=>	'Hámarksstærð passamynda í byte-um (mælt með 10240).',

// E-mail section
'E-mail subhead'					=>	'Tölvupóstur',
'Admin e-mail label'				=>	'Netfang stjórnandi',
'Admin e-mail help'					=>	'Netfang stjórnanda spjallborðsins.',
'Webmaster e-mail label'			=>	'Netfang vefstjóra',
'Webmaster e-mail help'				=>	'Þetta er netfangið sem allir tölvupóstar frá spjallinu er stílaðir frá.',
'Subscriptions label'				=>	'Áskriftir',
'Subscriptions help'				=>	'Leyfa notendum að vera áskrifendur að þráðum (fá tölvupóst þegar einhver svarar).',
'SMTP address label'				=>	'SMTP server address',
'SMTP address help'					=>	'Slóð utanhús SMTP þjóns til að senda tölvupóst með. Hægt er að nota sérstök port númer ef SMTP þjóninn notar ekki sjálfgefna port 25 (dæmi: mail.myhost.com:3580). Skiljið þetta eftir tómt til að nota póstforritið á þessum vefþjón.',
'SMTP username label'				=>	'SMTP notendanafn',
'SMTP username help'				=>	'Notendanafn fyrir SMTP þjóninn. Notið aðeins notendanafn ef SMTP þjóninn biður um það (flestir þjónar <strong>krefjast ekki</strong> auðkenningar).',
'SMTP password label'				=>	'SMTP lykilorð',
'SMTP password help'				=>	'Lykilorð fyrir SMTP þjóninn. Notið aðeins lykilorð ef SMTP þjóninn biður um það (flestir þjónar <strong>krefjast ekki</strong> auðkenningar).',
'SMTP SSL label'					=>	'Dulkóða SMTP með SSL',
'SMTP SSL help'						=>	'Dulkóðar tenginguna við SMTP þjóninn með SSL. Ætti aðeins að notast ef SMTP þjóninn þarfnar auðkenningar og þín útgáfa af PHP styður SSL.',

// Registration Section
'Registration subhead'				=>	'Skráningar',
'Allow new label'					=>	'Leyfa nýskráningar',
'Allow new help'					=>	'Stjórnar því hvort að spjallborðið samþykkir nýskráningar. Aftengið aðeins undir sérstökum kringumstæðum.',
'Verify label'						=>	'Staðfesta skráningar',
'Verify help'						=>	'Þegar þetta er virkjað þá fá notendur sent handahófskennt lykilorð við skráningu. Þeir geta svo skráð sig inn og breytt lykilorðinu ef þeim sýnist svo. Þessi möguleiki krefst þess einnig að notendur staðfest nýtt netfang ef þeir breyta frá netfanginu sem þeir skráðu sig með. Þetta er áhrifarík leið til að koma í veg fyrir mistnotkun á nýskráningum og til að vera viss um að allir notendur séu með "rétt" netfang í stillingunum sínum.',
'Report new label'					=>	'Tilkynna um nýskráningar',
'Report new help'					=>	'Ef þetta er virkjað þá mun FluxBB láta notednur póstlistans (sjá að ofan) vita þegar nýskráningar fara fram.',
'Use rules label'					=>	'Reglur spjallborðsins',
'Use rules help'					=>	'Þegar þetta er virkjað þá þarf notandinn að samþykkja reglur við skráningu (sláið inn texta hér að neðan). Reglurnar eru aðgengilegar í gegnum tengil í valmyndinni sem er efst á hverri síðu.',
'Rules label'						=>	'Skrifaðu reglurnar þínar hér',
v'Rules help'						=>	'Hér geturðu skráð reglur og aðrar upplýsingar sem notandinn þarf að skoða við skráningu og samþykja. Ef þú virkjar reglurnar þá þarftu að skrifa eitthvað hér annars verður það gert óvirkt. Þessi texti verður ekki meðhöndlaður(e.parsed) eins og venjulegir póstar og því má nota HTML.',
'E-mail default label'				=>	'Sjálfgefin netfangastilling',
'E-mail default help'				=>	'Veldu sjálfgefna einkastillingu fyrir nýskráningar.',
'Display e-mail label'				=>	'Sýna netfang öðrum notendum.',
'Hide allow form label'				=>	'Fela netfang en leyfa tölvupóst úr formum.',
'Hide both label'					=>	'Fela netfang og ekki leyfa form tölvupóst.',

// Announcement Section
'Announcement subhead'				=>	'Tilkynningar',
'Display announcement label'		=>	'Birta tilkynningar',
'Display announcement help'			=>	'Virkið þetta til að birta skilaboðin hér að neðan á spjallborðinu.',
'Announcement message label'		=>	'Tilkynning',
'Announcement message help'			=>	'Þessi texti verður ekki meðhöndlaður(e.parsed) eins og venjulegir póstar og því má nota HTML.',

// Maintenance Section
'Maintenance subhead'				=>	'Viðhald',
'Maintenance mode label'			=>	'Viðhaldshamur',
'Maintenance mode help'				=>	'Þegar þetta er virkjað þá er spjallið eingöngu opið stjórnendum. Þetta ætti að nota ef taka þarf spjallið niður tímabundið vegna viðhalds. <strong>AÐVÖRUN! Ekki skrá þig út þegar spjallið er í viðhaldsham.</strong> Þú munt ekki geta loggað þig inn aftur.',
'Maintenance message label'			=>	'Tilkynning',
'Maintenance message help'			=>	'Skilaboð sem verða birt notendum þegar spjallborðið er í viðhaldsham. Ef þetta er skilið eftir tómt þá verða sjálfgefin skilaboð notuð. Þessi texti verður ekki meðhöndlaður(e.parsed) eins og venjulegir póstar og því má nota HTML.',

);