<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Sláið inn löglegt netfang',
'Email legend 2'			=>	'Sláið inn og staðfestið löglegt netfang',
'Localisation legend'		=>	'Setja staðfærslu valmöguleika',
'Time zone'					=>	'Tímabelti',
'Time zone info'			=>	'Til að spjallborðið birti réttar tímasetningar þá þarft þú að velja tímabeltið sem þú ert í (00 GMT á Íslandi).',
'DST'						=>	'Dagljósatími er í gangi(klukkan flýtir sér um klukkutíma).',
'Time format'				=>	'Tímasnið',
'Date format'				=>	'Dagssnið',
'Default'					=>	'Sjálfgefið',
'Language'					=>	'Tungumál',
'Email setting info'		=>	'Veldu hvort að þú vilt að netfangið þitt sé sýnilegt hverjum sem er eða ekki og ef þú vilt að aðrir notendur geti sent þér tölvupóst í gegnum formin eður ei.',
'Email setting 1'			=>	'Birtu netfangið þitt.',
'Email setting 2'			=>	'Feldu netfangið þitt en leyfðu póst úr formum.',
'Email setting 3'			=>	'Feldu netfangið þitt og bannaðu póst úr formum.',
'Privacy options legend'	=>	'Valmöguleikar',
'Confirm pass'				=>	'Staðfesta lykilorð',

'Username too short'		=>	'Notendanafn þarf að vera amk. 2 stafir á lengd. Vinsamlegast veldu annað(lengra) notendanafn.',
'Username too long'			=>	'Notendanafnið getur ekki verið meira en 25 stafir á lengd. Vinsamlegast veldu annað(styttra) notendanafn.',
'Username guest'			=>	'Notendanafnið guest er frátekið. Vinsamlegast veldu annað notendanafn.',
'Username IP'				=>	'Notendanafn má ekki vera í formi IP tölu. Vinsamlegast veldu annað notendanafn.',
'Username reserved chars'	=>	'Notendanafn má ekki innihalda \', " og [ eða ] á sama tíma. Vinsamlegast veldu annað notendanafn.',
'Username BBCode'			=>	'Notendanafn má ekki innihalda neitt form taga(BBKóði) sem spjallborðið notar. Vinsamlegast veldu annað notendanafn.',
'Banned username'			=>	'Þetta notendanafn er bannað á spjallborðinu. Vinsamlegast veldu annað notendanafn.',
'Pass too short'			=>	'Lykilorð verður að vera amk. 4 stafir á lengd. Vinsamlegast velið annað(lengra) lykilorð.',
'Pass not match'			=>	'Lykilorðin eru ekki eins.',
'Banned email'				=>	'Netfangið sem þú slóst inn er bannað á þessu spjallborði. Vinsamlegast veldu annað netfang.',
'Dupe email'				=>	'Einhver annar er nú þegar skráður með þetta netfang. Vinsamlegast veldu annað netfang.',
'Sig too long'				=>	'Undirskrift getur ekki verið lengri en %1$s stafir. Vinsamlegast styttu undirskriftina um %2$s stafi.',
'Sig too many lines'		=>	'Undirskriftir geta ekki haft fleiri en %s línur.',
'Bad ICQ'					=>	'Þetta ICQ UIN er ekki löglegt. Vinsamlegast farið og leiðréttið það.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Ísland, Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);