<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'Valmöguleikar',
'Section essentials'			=>	'Grunnupplýsingar',
'Section personal'				=>	'Um mig',
'Section messaging'				=>	'Spjallforrit',
'Section personality'			=>	'Sjálfið',
'Section display'				=>	'Útlit',
'Section privacy'				=>	'Gagnaaðgangur',
'Section admin'					=>	'Stjórnun',

// Miscellaneous
'Username and pass legend'		=>	'Sláðu inn notendanafn og lykilorð',
'Personal details legend'		=>	'Vinsamlegast sláðu inn upplýsingar um þig',
'Contact details legend'		=>	'Sláðu inn upplýsingar um þau spjallforrit sem þú notar',
'User activity'					=>	'Virkni notanda',
'Paginate info'					=>	'Sláðu inn fjölda þráða og pósta sem þú vilt sjá á hverri síðu.',

// Password stuff
'Pass key bad'					=>	'Þetta staðfestingartákn lykilorðsins var vitlaust eða útrunnið. Vinsamlegast biðjið aftur um nýtt lykilorð. Ef það klikkar hafið þá samband við stjórnandann',
'Pass updated'					=>	'Lykilorðið þitt hefur uppfært. Þú getur núna skráð þig inn með nýja lykilorðinu.',
'Pass updated redirect'			=>	'Lykilorð uppfært. Áframsendi …',
'Wrong pass'					=>	'Gamla lykilorðið er vitlaust.',
'Change pass'					=>	'Breyta lykilorði',
'Change pass legend'			=>	'Sláðu inn og staðfestu nýja lykilorðið',
'Old pass'						=>	'Gamla lykilorðið',
'New pass'						=>	'Nýja lykilorðið',
'Confirm new pass'				=>	'Staðfesta nýja lykilorðið',
'Pass info'						=>	'Lykilorð þurfa að vera a.m.k. 4 stafa löng. Há- og lágstafir skipta máli.',

// Email stuff
'Email key bad'					=>	'Þetta staðfestingartákn netfangsins var vitlaust eða útrunnið. Vinsamlegast biðjið aftur um breytingu á netfangi. Ef það klikkar hafið þá samband við stjórnanda',
'Email updated'					=>	'Netfangið þitt hefur verið uppfært.',
'Activate email sent'			=>	'Tölvupóstur hefur verið sendur á netfangið sem þú gafst upp með leiðbeiningum um það hvernig þú virkjar nýja netfangið. Ef tölvupósturinn skilar sér ekki þá getur þú haft samband við stjórnanda',
'Email legend'					=>	'Sláðu inn nýja netfangið þitt',
'Email instructions'			=>	'Tölvupóstur hefur verið sendur á nýja netfangið með staðfestingartengli. Þú verður að smella á tengilinn í tölvupóstinum til að virkja nýja netfangið.',
'Change email'					=>	'Breyta netfangi',
'New email'						=>	'Nýtt netfang',

// Avatar upload stuff
'Avatars disabled'				=>	'Stjórnandinn hefur aftengt stuðning við passamyndir.',
'Too large ini'					=>	'Valin skrá var of stór til að upphlaða. Vefþjóninn leyfði ekki upphleðsluna.',
'Partial upload'				=>	'Valda skráin var bara að hluta upphlaðinn. Vinsamlegast reynið aftur.',
'No tmp directory'				=>	'PHP tókst ekki að vista myndina í bráðabirgðamöppu.',
'No file'						=>	'Þú valdir ekki skrá til að upphlaða.',
'Bad type'						=>	'Skráin sem þú reyndir að senda inn er ekki leyfð. Leyfðar skrár eru gif, jpeg og png.',
'Too wide or high'				=>	'Skráin sem þú reyndir að upphlaða er víðari og/eða hærri heldur en leyfð hámarksstærð',
'Too large'						=>	'Skráin sem þú reyndir að senda inn er stærri heldur en leyfð hámarksstærð',
'pixels'						=>	'pixlar',
'bytes'							=>	'bæti',
'Move failed'					=>	'Vefþjóninum tókst ekki að vista skrána. Vinsamlegast hafið samband við stjórnanda',
'Unknown failure'				=>	'Óþekkt villa kom upp. Vinsamlegast reynið aftur.',
'Avatar upload redirect'		=>	'Passamynd upphlaðin. Áframsendi …',
'Avatar deleted redirect'		=>	'Passamynd eytt. Áframsendi …',
'Avatar desc'					=>	'Passamynd er smámynd sem er birt undir notendanafni þínu í póstum. Hún má ekki vera stærri heldur en',
'Upload avatar'					=>	'Upphlaða passamynd',
'Upload avatar legend'			=>	'Veldu skrá til að senda inn sem passamynd',
'Delete avatar'					=>	'yða passamynd', // only for admins
'File'							=>	'Skrá',
'Upload'						=>	'Upphlaða', // submit button

// Form validation stuff
'Forbidden title'				=>	'Fyrirsögnin sem þú slóst inn, innhélt bönnuð orð. Þú verður að velja aðra fyrirsögn.',
'Profile redirect'				=>	'Stillingum breytt. Áframsendi …',

// Profile display stuff
'Users profile'					=>	'%s\'s profile',
'Username info'					=>	'Notendanafn: %s',
'Email info'					=>	'Netfang: %s',
'Posts info'					=>	'Póstar: %s',
'Registered info'				=>	'Skráður: %s',
'Last post info'				=>	'Síðasti póstur: %s',
'Show posts'					=>	'Sýna alla pósta',
'Realname'						=>	'Fullt nafn',
'Location'						=>	'Staðsetning',
'Website'						=>	'Vefsíða',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'MSN Messenger',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'Passamynd',
'Signature'						=>	'Undirskrift',
'Sig max size'					=>	'Hámarkslengd: %s stafir / Hámarksfjöldi lína: %s',
'Avatar legend'					=>	'Veldu birtingarmöguleika passamyndar',
'Avatar info'					=>	'Passamynd(e.avatar) er smámynd sem er birt með póstunum þínum. Þú getur upphlaðið passamynd með því að smella á tengilinn hér að neðan.',
'Change avatar'					=>	'Breyta passamynd',
'Signature legend'				=>	'Undirskriftin þín',
'Signature info'				=>	'Undirskrift er smá textabútur sem fylgir póstunum þínum. Þú getur haft nokkurn veginn hvað sem er í henni. Kannski uppáhalds tilvitnunin þín eða stjörnumerki. Þú ræður! Þú getur notað BBKóða eftir því hvað er leyft á spjallþráðunum. Þú sérð hvað er leyft hér fyrir neðan þegar að þú breytir undirskriftinni.',
'Sig preview'					=>	'Forsýn undirskriftar:',
'No sig'						=>	'Engin undirskrift er skráð í þínum stillingum.',
'Signature quote/code/list/h'	=>	'Tögin quote, code, list, og heading eru ekki leyfð í undirskriftum.',
'Topics per page'				=>	'Þræðir',
'Posts per page'				=>	'Póstar',
'Leave blank'					=>	'Skilja eftir auða og nota sjálfgefin gildi.',
'Subscription legend'			=>	'Stilltu áskriftarmöguleika',
'Notify full'					=>	'Sendu textaútgáfu af nýjum póstum með í tilkynningarskeytinu.',
'Auto notify full'				=>	'Skrá sjálfkrafa áskrift að öllum þráðum sem þú póstar í.',
'Show smilies'					=>	'Sýna broskarla sem grafískar táknmyndir.',
'Show images'					=>	'Sýna myndir í pósti.',
'Show images sigs'				=>	'Sýna myndir í undirskrift notenda.',
'Show avatars'					=>	'Sýna passamynd notenda í póstum.',
'Show sigs'						=>	'Sýna undirskriftir notenda.',
'Style legend'					=>	'Veldu hentugt stílsnið',
'Styles'						=>	'Stílsnið',
'Admin note'					=>	'Stjórnandi ath',
'Pagination legend'				=>	'Sláðu inn fjölda síðna/pósta',
'Post display legend'			=>	'Valmöguleikar til að skoða pósta',
'Post display info'				=>	'Ef þú ert á hægvirkri tengingu, þá getur aftenging þessara valmöguleika, sérstaklega að sýna myndir í póstum og undirskriftum hjálpað til að við að hlaða spjallinu hraðar.',
'Instructions'					=>	'Þegar þú uppfærir stillingarnar þínar þá verður þú sendur til baka á þessa síðu.',

// Administration stuff
'Group membership legend'		=>	'Veldu notendahóp',
'Save'							=>	'Vista',
'Set mods legend'				=>	'Umsjónarmaður á',
'Moderator in info'				=>	'Veldur hvaða spjallborð þessi notandi má hafa umsjón með. Þetta á bara við umsjónarmenn. Stjórnendur hafa ávallt full réttindi á öllum spjallborðum.',
'Update forums'					=>	'Uppfæra spjallborð',
'Delete ban legend'				=>	'Eyddu (eingöngu stjórnandi) eða bannaðu notandann',
'Delete user'					=>	'Eyða notanda',
'Ban user'						=>	'Banna notanda',
'Confirm delete legend'			=>	'Áríðandi: Lesist áður en notanda er eytt',
'Confirm delete user'			=>	'Staðfestu eyðingu notanda',
'Confirmation info'				=>	'Vinsamlegast staðfestu að þú viljir eyða þessum notanda', // the username will be appended to this string
'Delete warning'				=>	'Viðvörun! Eyðing notenda og/eða pósta er óafturkallanleg. Ef þú velur að eyða ekki póstum  eftir þennan notanda þá verður eingöngu hægt að eyða þeim handvirkt eftir ákveðin tíma.',
'Delete posts'					=>	'Eyða öllum póstum og þráðum sem þessi notandi hefur gert.',
'Delete'						=>	'Eyða', // submit button (confirm user delete)
'User delete redirect'			=>	'Notanda eytt. Áframsendi …',
'Group membership redirect'		=>	'Hópaðild vistuð. Áframsendi …',
'Update forums redirect'		=>	'Réttindi umsjónarmanns uppfærð. Áframsendi …',
'Ban redirect'					=>	'Áframsendi …',
'No delete admin message'		=>	'Það er ekki hægt að eyða Stjórnendum. Til að eyða þessum notanda þarftu fyrst að færa hann yfir í annan notendahóp.',

);
