<?php

// Language definitions used in admin_maintenance.php
$lang_admin_maintenance = array(

'Maintenance head'				=>	'論壇維護',
'Rebuild index subhead'			=>	'重建搜尋索引',
'Rebuild index info'			=>	'如果您在資料庫中手動增加、編輯或移除文章或者論壇的搜尋出現問題，您應該重建搜尋索引。為了獲得最佳性能，在重建索引前應該將論壇設定為%s。<strong>重建索引可能會需要較長時間並且重建過程會加重伺服器負荷！</strong>',
'Posts per cycle label'			=>	'每個週期處理的文章數',
'Posts per cycle help'			=>	'每個頁面處理的文章數量。例如，輸入300時，每處理三百篇文章將會自動重新整理頁面。這樣做是為了防止在重建索引過程中出現指令碼逾時。',
'Starting post label'			=>	'起始文章的ID',
'Starting post help'			=>	'要重建索引的起始文章ID。預設是從資料庫中存在的第一篇文章開始。一般您不需要修改。',
'Empty index label'				=>	'清空索引',
'Empty index help'				=>	'若您準備在重建索引前清空搜尋索引請勾選此項(參見下文)。',
'Rebuild completed info'		=>	'一旦這個過程結束，您將被重新導向回此頁面。強烈建議您在操作過程中開啟瀏覽器的JavaScript功能(以使一個週期完成後能夠自動重新導向)。如果重建過程被迫中止，您也可以記下已處理的最後一篇文章的ID然後將「起始文章的ID」輸入為此ID+1再繼續建立索引(此時不得勾選「清空索引」選項)。',
'Rebuild index'					=>	'重建索引',
'Rebuilding search index'		=>	'重建搜尋索引',
'Rebuilding index info'			=>	'正在重建索引。正是喝咖啡的好時機 :-)',
'Processing post'				=>	'正在處理文章 <strong>%s</strong> …',
'Click here'					=>	'點選這裡',
'Javascript redirect failed'	=>	'JavaScript重新導向失敗。 %s 繼續 …',
'Posts must be integer message'	=>	'每個週期的文章數必須設定為正整數。',
'Days must be integer message'	=>	'清理文章的天數必須是一個正整數值。',
'No old topics message'			=>	'沒有 %s 天之前的主題。請減小天數的值，然後重試。',
'Posts pruned redirect'			=>	'文章已清理。重新導向中 …',
'Prune head'					=>	'清理文章',
'Prune subhead'					=>	'清理舊文章',
'Days old label'				=>	'幾天前',
'Days old help'					=>	'超過這個天數的主題必須要清理。例如：輸入 30，則每個主題內超過 30 天的文章會被刪除。',
'Prune sticky label'			=>	'清理置頂主題',
'Prune sticky help'				=>	'啟用後，置頂主題也會被清理。',
'Prune from label'				=>	'由版面清理',
'All forums'					=>	'所有版面',
'Prune from help'				=>	'您要清理文章的版面。',
'Prune info'					=>	'謹慎使用此功能。<strong>清理文章可能永遠無法恢復。</strong>為了獲得最佳性能，清理時應當關閉論壇 %s。',
'Confirm prune subhead'			=>	'確定清理文章',
'Confirm prune info'			=>	'您確定要清理超過 %s 天[由 %s (%s 個主題)] 的所有主題。',
'Confirm prune warn'			=>	'警告！清理文章會永久刪除。',

);
