<?php

// Language definitions used in install.php, localized by adaur

$lang_install = array(

'Choose install language'		=>	'選擇安裝指令碼的語言',
'Choose install language info'	=>	'本安裝指令碼所使用的語言。論壇所使用的預設語言將在安裝過程中設定。',
'Install language'				=>	'安裝語言',
'Change language'				=>	'變更語言',
'Next'							=>	'下一步',
'Already installed'				=>	'FluxBB 似乎已安裝。請點選<a href="index.php">此連結</a>前往。',
'You are running error'			=>	'您的 %1$s 版本為 %2$s。 FluxBB %3$s 至少需要 %1$s %4$s 方可正確執行。在繼續之前，必須升級您的 %1$s 設定。',
'My FluxBB Forum'				=>	'我的 FluxBB 論壇',
'Description'					=>	'Unfortunately no one can be told what FluxBB is - you have to see it for yourself.',
'Username 1'					=>	'會員名稱長度不可少於2個字元。',
'Username 2'					=>	'會員名稱長度不可超過25個字元。',
'Username 3'					=>	'guest 是保留的會員名稱。',
'Username 4'					=>	'會員名稱的格式不允許是 IP 位址式。',
'Username 5'					=>	'會員名稱不可一次包含字元 \'、 " 與 [ 或 ] 。請重新選擇會員名稱。',
'Username 6'					=>	'會員名稱不可包含本論壇所使用的文字樣式標籤(BBCode)。',
'Short password'				=>	'密碼長度不可少於4個字元。',
'Passwords not match'			=>	'密碼不符合。',
'Wrong email'					=>	'您輸入的管理員電子信箱位址無效。',
'No board title'				=>	'您必須輸入論壇標題。',
'Error default language'		=>	'所選的預設語言似乎不存在。',
'Error default style'			=>	'所選的預設風格似乎不存在。',
'No DB extensions'				=>	'現有 PHP 環境不具備 FluxBB 所需的任何格式的資料庫。為使 FluxBB 能被安裝，PHP 必須支援 MySQL、PostgreSQL或SQLite。',
'Administrator username'		=>	'管理員名稱',
'Administrator password 1'		=>	'管理員密碼1',
'Administrator password 2'		=>	'管理員密碼2',
'Administrator email'			=>	'管理員電子信箱',
'Board title'					=>	'論壇標題',
'Base URL'						=>	'您的 FluxBB 論壇 URL (無需後面斜線）。必須填寫正確。 ',
'Required field'				=>	'在這個表格中是必填欄位。',
'FluxBB Installation'			=>	'FluxBB 安裝',
'Welcome'						=>	'您將要安裝 FluxBB。繼續安裝前您必須完成底下表格。遇到任何安裝問題，請參考說明文件。',
'Install'						=>	'安裝 FluxBB %s',
'Errors'						=>	'下列錯誤須要修正：',
'Database setup'				=>	'資料庫設定',
'Info 1'						=>	'我們需要建立與您的資料庫連接的所有資訊。',
'Select database'				=>	'選擇資料庫類型',
'Info 2'						=>	'選擇一個資料庫。我們支援 SQLite，MySQL 和 PostgreSQL。',
'Database type'					=>	'資料庫類型',
'Required'						=>	'(必需)',
'Database hostname'				=>	'輸入資料庫伺服器的主機名稱',
'Info 3'						=>	'您應該能夠從您的網頁主機(web host)獲取此資訊，如果 <code>本地主機</code> 沒有運作。',
'Database server hostname'		=>'資料庫伺服器主機名稱',
'Database enter name'			=>	'輸入資料庫名稱',
'Info 4'						=>	'要安裝 FluxBB 的資料庫名稱。',
'Database name'					=>	'資料庫名稱',
'Database enter informations'	=>	'輸入您資料庫的使用者名稱及密碼',
'Database username'				=>	'資料庫使用者名稱',
'Info 5'						=>	'您的MySQL資料庫的使用者名稱及密碼。如使用 SQLite 此處忽略。',
'Database password'				=>	'資料庫密碼',
'Database enter prefix'			=>	'輸入資料庫的資料表前置字元',
'Info 6'						=>	'如果您要在同一資料庫中安裝多個 FluxBB ，更改此預設值。',
'Table prefix'					=>	'資料表前置字元',
'Administration setup'			=>	'管理員設定',
'Info 7'						=>	'於您的論壇建立第一個帳號(管理員)。',
'Info 8'						=>	'管理員名稱長度須在2至25個字元之間。密碼必須至少 4 個字元長。請記住密碼區分大小寫。',
'Password'						=>	'密碼',
'Confirm password'				=>	'確認密碼',
'Board setup'					=>	'論壇設定',
'Info 11'						=>	'設置論壇。以後仍可更改。',
'General information'			=>	'輸入您論壇的標題、敘述',
'Board description'				=>	'論壇敘述(支援 HTML)',
'Appearance'					=>	'外觀',
'Info 15'						=>	'佈置您的版面。為您的論壇選擇語言和風格。',
'Default language'				=>	'預設語言',
'Default style'					=>	'預設風格',
'Start install'					=>	'開始安裝',
'DB type not valid'				=>	'\'%s\' 不是一個有效的資料庫類型',
'Table prefix error'			=>	'資料表前置字元 \'%s\' 包含不合法字元或過長。資料表前置字元可包含字母 a 至 z，任何數字以及字元 _。並且不能以數字開頭。長度不超過40個字元。請另選資料表前置字元',
'Prefix reserved'				=>	'資料表前置字元 \'sqlite_\' 是專為 SQLite 引擎保留的名稱。請另選資料表前置字元',
'Existing table error'			=>	'資料庫 \'%s\'中已經存在資料表 \'%s的使用者\'。這可能表示 FluxBB 已曾安裝或另一個已安裝的軟體佔用了 FluxBB 所需的一個或多個資料表名稱。如您準備在同一資料庫中安裝多個 FluxBB，您必須選擇不同的資料表前置字元。',
'InnoDB off'					=>	'InnoDB 似乎停用。請另選一個無 InnoDB 支援的資料庫層，或在您的 MySQL伺服器上啟用 InnoDB',
'Administrators'				=>	'管理員',
'Administrator'					=>	'管理員',
'Moderators'					=>	'版主',
'Moderator'						=>	'版主',
'Guests'						=>	'訪客',
'Guest'							=>	'訪客',
'Members'						=>	'一般會員',
'Announcement'					=>	'在此輸入您要發佈的公告。',
'Rules'							=>	'在此輸入論壇服務條款',
'Maintenance message'			=>	'論壇維護中暫時關閉，請稍後訪問。',
'Test post'						=>	'測試主題',
'Message'						=>	'如果您在閱讀這篇文章(我猜正是如此)，安裝的 FluxBB 已經開始運作！現在您可以登入，並進入頂部的論壇管理設定面板來設定論壇。',
'Test category'					=>	'測試用分區',
'Test forum'					=>	'測試用版面',
'This is just a test forum'		=>	'這只是一個測試版面',
'Alert cache'					=>	'<strong>快取所在目錄不可寫！</strong>為使 FluxBB 功能正常，必須為目錄 <em>%s</em> 設定 PHP 寫入權限。使用 chmod 命令設定恰當的目錄權限。如有疑問，用 chmod 設為0777。',
'Alert avatar'					=>	'<strong>頭像所在目錄不可寫！</strong>如果您準備允許會員上傳自訂頭像，您必須確認已為目錄 <em>%s</em> 設定了 PHP 寫入權限。稍後您可為會員上傳的頭像檔選擇指定的目錄(見 論壇管理設定/選項)。使用 chmod 命令設定恰當的目錄權限。如有疑問，用 chmod 設為0777。',
'Alert upload'					=>	'<strong>這個伺服器似乎不允許上傳檔案！</strong>如果您準備允許會員上傳自訂頭像，您必須設定 PHP 中的 file_uploads 設定。上傳功能一旦啟用，可在 論壇管理設定/選項/頭像 中啟用。',
'FluxBB has been installed'		=>	'FluxBB 已安裝。請遵循以下指示完成安裝。',
'Final instructions'			=>	'最後一步',
'Info 17'						=>	'為完成安裝，您需要點選底下按鈕以下載 config.php 檔。然後上傳它至您已安裝的 FluxBB 根目錄下。',
'Info 18'						=>	'一旦您上傳完 config.php，FluxBB 就安裝成功了！隨後您便可 <a href="index.php">進入論壇首頁</a>。',
'Download config.php file'		=>	'下載 config.php 檔',
'FluxBB fully installed'		=>	'FluxBB 已經安裝成功！您現在可 <a href="index.php">訪問論壇首頁</a>。',

);
