<?php

// Language definitions used in admin-users.php
$lang_admin_users = array(

'Non numeric message'		=>	'Você digitou um valor não-numérico em uma coluna que só aceita números.',
'Invalid date time message'	=>	'Você digitou uma data/hora inválida.',
'Not verified'				=>	'Não verificado',
'User search head'			=>	'Pesquisa de usuário',
'User search subhead'		=>	'Digite o critério de pesquisa',
'User search info'			=>	'Pesquisar por usuários no banco de dados. Você pode digitar um ou mais termos para pesquisar. Curingas na forma de asteriscos (*) são aceitos.',
'Username label'			=>	'Nome de usuário',
'E-mail address label'		=>	'Endereço de email',
'Title label'				=>	'Título',
'Real name label'			=>	'Nome real',
'Website label'				=>	'Website',
'Jabber label'				=>	'Jabber',
'ICQ label'					=>	'ICQ',
'MSN label'					=>	'MSN Messenger',
'AOL label'					=>	'AOL IM',
'Yahoo label'				=>	'Yahoo Messenger',
'Location label'			=>	'Localização',
'Signature label'			=>	'Assinatura',
'Admin note label'			=>	'Nota do administrador',
'Posts more than label'		=>	'Número de mensagens maior que',
'Posts less than label'		=>	'Número de mensagens menor que',
'Last post after label'		=>	'Última mensagem após',
'Date help'					=>	'(aaaa-mm-dd hh:mm:ss)',
'Last post before label'	=>	'Última mensagem antes de',
'Registered after label'	=>	'Registrado após',
'Registered before label'	=>	'Registrado antes de',
'Order by label'			=>	'Ordenar por',
'Order by username'			=>	'Nome de usuário',
'Order by e-mail'			=>	'Email',
'Order by posts'			=>	'Número de mensagens',
'Order by last post'		=>	'Última mensagem',
'Order by registered'		=>	'Registrado',
'Ascending'					=>	'Ascendente',
'Descending'				=>	'Descendente',
'User group label'			=>	'Grupo de usuário',
'All groups'				=>	'Todos os grupos',
'Unverified users'			=>	'Usuários não confirmados',
'Submit search'				=>	'Enviar pesquisa',
'IP search head'			=>	'Pesquisa de IP',
'IP search subhead'			=>	'Digite o IP a ser pesquisado',
'IP address label'			=>	'Endereço IP',
'IP address help'			=>	'O endereço IP a ser pesquisado no banco de dados de mensagens.',
'Find IP address'			=>	'Encontrar endereço IP',

'Results head'				=>	'Resultados da Pesquisa',
'Results username head'		=>	'Nome de usuário',
'Results e-mail head'		=>	'Email',
'Results title head'		=>	'Título/Estado',
'Results posts head'		=>	'Mensagens',
'Results admin note head'	=>	'Nota do administrador',
'Results actions head'		=>	'Ações',
'Results IP address head'	=>	'Endereço IP',
'Results last used head'	=>	'Último uso',
'Results times found head'	=>	'Vezes encontrado',
'Results action head'		=>	'Ação',
'Results find more link'	=>	'Encontrar mais usuários com este IP',
'Results no posts found'	=>	'Atualmente não existem mensagens deste usuário no fórum.',
'Bad IP message'			=>	'O endereço IP fornecido não está corretamente formatado.',
'Results view IP link'		=>	'Visualizar estatísticas de IP',
'Results show posts link'	=>	'Exibir mensagens',
'Results guest'				=>	'Visitante',
'Results no IP found'		=>	'O endereço de IP fornecido não pode ser encontrado no banco de dados.',
'No match'					=>	'Nenhuma combinação'

);
