<?php

// Language definitions used in admin_options.php
$lang_admin_options = array(

'Bad HTTP Referer message'			=>	'HTTP_REFERER ruim. Se você moveu este fórum para um novo servidor ou alterou o domínio, você precisa atualizar a URL Base manualmente no banco de dados (procure por o_base_url na tabela config) e então limpe o cache excluindo todos os arquivos .php na pasta /cache.',
'Must enter title message'			=>	'Você deve definir um título para o site.',
'Invalid e-mail message'			=>	'O endereço de email de administrador que você digitou é inválido.',
'Invalid webmaster e-mail message'	=>	'O endereço de email de webmaster que você digitou é inválido.',
'SMTP passwords did not match'		=>	'Você deve digitar a senha SMTP duas vezes exatamente iguais para alterá-la.',
'Enter announcement here'			=>	'Digite seu anúncio aqui.',
'Enter rules here'					=>	'Digite suas regras aqui.',
'Default maintenance message'		=>	'O fórum está temporariamente desativado para manutenção. Por favor, tente novamente daqui alguns minutos.',
'Timeout error message'				=>	'O valor de "Tempo limite online" deve ser menor que o valor de "Tempo limite de visita".',
'Options updated redirect'			=>	'Opções atualizadas. Redirecionando …',
'Options head'						=>	'Opções',

// Essentials section
'Essentials subhead'				=>	'Essenciais',
'Board title label'					=>	'Título do site',
'Board title help'					=>	'O título deste fórum (exibido no topo de todas as páginas). Este campo <strong>não</strong> pode conter HTML.',
'Board desc label'					=>	'Descrição do fórum',
'Board desc help'					=>	'Uma breve descrição deste fórum (exibido no topo de todas as páginas). Este campo podem conter HTML.',
'Base URL label'					=>	'URL Base',
'Base URL help'						=>	'A URL completa do fórum sem a barra final (ex. http://www.meudominio.com.br/forum). Isto <strong>deve</strong> estar correto para que todas as funções de administração e moderação funcionem. Se você ver erros "Referenciador ruim", é provável que esteja incorreto.',
'Base URL problem'					=>  'Sua instalção não suporta a conversão automática de nomes de domínio internacionalizados. Já que sua URL base contém caracteres especiais, você <strong>deve</strong> usar um conversor online para evitar erros de "Bad referer".',
'Timezone label'					=>	'Fuso horário padrão',
'Timezone help'						=>	'O fuso horário padrão para usuários e visitantes tentando se registrar no fórum.',
'DST label'							=>	'Ajuste de Horário de Verão',
'DST help'							=>	'Ative caso o horário de verão esteja em efeito (avança o horário em 1 hora).',
'Language label'					=>	'Idioma padrão',
'Language help'						=>	'O idioma padrão para visitantes e usuários que não alteraram o ajuste padrão em seu perfil. Se você remover um pacote de idioma, isto precisa ser atualizado.',
'Default style label'				=>	'Estilo padrão',
'Default style help'				=>	'O estilo padrão para visitantes e usuários que não alteraram o ajuste padrão em seu perfil.',

// Essentials section timezone options
'UTC-12:00'							=>	'(UTC-12:00) Linha de Data Internacional do Oeste',
'UTC-11:00'							=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'							=>	'(UTC-10:00) Hawaii-Aleutian, Ilhas Cook',
'UTC-09:30'							=>	'(UTC-09:30) Arquipélago das Marquesas',
'UTC-09:00'							=>	'(UTC-09:00) Alasca, Arquipélago de Gambier',
'UTC-08:30'							=>	'(UTC-08:30) Ilhas Pitcairn',
'UTC-08:00'							=>	'(UTC-08:00) Pacífico',
'UTC-07:00'							=>	'(UTC-07:00) Montanha',
'UTC-06:00'							=>	'(UTC-06:00) Central',
'UTC-05:00'							=>	'(UTC-05:00) Oriental',
'UTC-04:00'							=>	'(UTC-04:00) Atlântico',
'UTC-03:30'							=>	'(UTC-03:30) Terra Nova',
'UTC-03:00'							=>	'(UTC-03:00) Brasil, Groenlândia Central',
'UTC-02:00'							=>	'(UTC-02:00) Médio Atlântico',
'UTC-01:00'							=>	'(UTC-01:00) Açores, Cabo Verde, Groenlândia Oriental',
'UTC'								=>	'(UTC) Europa Ocidental, Greenwich',
'UTC+01:00'							=>	'(UTC+01:00) Europa Central, África Ocidental',
'UTC+02:00'							=>	'(UTC+02:00) Europa Oriental, África Central',
'UTC+03:00'							=>	'(UTC+03:00) África Oriental',
'UTC+03:30'							=>	'(UTC+03:30) Irã',
'UTC+04:00'							=>	'(UTC+04:00) Moscou, Golfo, Samara',
'UTC+04:30'							=>	'(UTC+04:30) Afeganistão',
'UTC+05:00'							=>	'(UTC+05:00) Paquistão',
'UTC+05:30'							=>	'(UTC+05:30) Índia, Sri Lanka',
'UTC+05:45'							=>	'(UTC+05:45) Nepal',
'UTC+06:00'							=>	'(UTC+06:00) Bangladesh, Butão, Ecaterimburgo',
'UTC+06:30'							=>	'(UTC+06:30) Ilhas Cocos (Keeling), Myanmar',
'UTC+07:00'							=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'							=>	'(UTC+08:00) Grande China, Austrália Ocidental, Krasnoyarsk',
'UTC+08:45'							=>	'(UTC+08:45) Austrália Ocidental Sul',
'UTC+09:00'							=>	'(UTC+09:00) Japão, Korea, Chita, Irkutsk',
'UTC+09:30'							=>	'(UTC+09:30) Austrália Central',
'UTC+10:00'							=>	'(UTC+10:00) Austrália Oriental',
'UTC+10:30'							=>	'(UTC+10:30) Arquipélago de Lorde Howe',
'UTC+11:00'							=>	'(UTC+11:00) Ilha de Santa Isabel, Vladivostok',
'UTC+11:30'							=>	'(UTC+11:30) Ilha Norfolk',
'UTC+12:00'							=>	'(UTC+12:00) Nova Zelândia, Fiji, Magadan',
'UTC+12:45'							=>	'(UTC+12:45) Ilha Chatham',
'UTC+13:00'							=>	'(UTC+13:00) Tonga, Ilhas Fênix, Península de Kamchatka',
'UTC+14:00'							=>	'(UTC+14:00) Ilhas da Linha',

// Timeout Section
'Timeouts subhead'					=>	'Hora e limites de tempo',
'Time format label'					=>	'Formato de hora',
'PHP manual'						=>	'Manual PHP',
'Time format help'					=>	'[Formato atual: %s]. Veja %s para opções de formatação.',
'Date format label'					=>	'Formato de data',
'Date format help'					=>	'[Formato atual: %s]. Veja %s para opções de formatação.',
'Visit timeout label'				=>	'Tempo limite de visita',
'Visit timeout help'				=>	'Número em segundos que um usuário precisa ficar inativo antes que seus últimos dados de visita sejam atualizados (afeta primariamente os indicadores de novas mensagens).',
'Online timeout label'				=>	'Tempo limite online',
'Online timeout help'				=>	'Número em segundos que um usuário precisa ficar inativo antes de ser removido da lista de usuários online.',
'Redirect time label'				=>	'Tempo de redirecionamento',
'Redirect time help'				=>	'Número em segundos a se esperar durante o redirecionamento. Se definido como 0, nenhuma página de redirecionamento será exibida (isso não é recomendado).',

// Display Section
'Display subhead'					=>	'Visualização',
'Version number label'				=>	'Número de versão',
'Version number help'				=>	'Exibir o número de versão do FluxBB no rodapé.',
'Info in posts label'				=>	'Informações dos usuários nas mensagens',
'Info in posts help'				=>	'Exibir informações do autor da mensagem abaixo do nome de usuário na visualização de tópico. A informação afetada é localização, data de registro, contagem de mensagens e links de contato (email e URL).',
'Post count label'					=>	'Contagem de mensagens do usuário',
'Post count help'					=>	'Exibir o número de mensagens que o usuário já enviou (afeta visualização de tópico, perfil e lista de usuários).',
'Smilies label'						=>	'Emoticons nas mensagens',
'Smilies help'						=>	'Converter Emoticons como ícones gráficos.',
'Smilies sigs label'				=>	'Emoticons nas assinaturas',
'Smilies sigs help'					=>	'Converter Emoticons em pequenos ícones gráficos na assinatura dos usuários.',
'Clickable links label'				=>	'Tornar endereços em links clicáveis',
'Clickable links help'				=>	'Quando ativo, o FluxBB irá detectar automaticamente qualquer endereço URL nas mensagens e o converterá em um hyperlink clicável.',
'Topic review label'				=>	'Revisão do tópico',
'Topic review help'					=>	'Número máximo de mensagens a exibir na página de resposta (mais novas primeiro). Defina como 0 para desabilitar.',
'Topics per page label'				=>	'Tópicos por página',
'Topics per page help'				=>	'O número padrão de tópicos a exibir por página em um fórum. Usuários podem personalizar esta configuração.',
'Posts per page label'				=>	'Mensagens por página',
'Posts per page help'				=>	'O número padrão de mensagens a exibir por página em um tópico. Usuários podem personalizar esta configuração.',
'Indent label'						=>	'Tamanho de indentação',
'Indent help'						=>	'Se definido como 8, um tab comum será usado quando exibir textos com a tag [code][/code]. Caso contrário esta quantia de espaços será usada para indentar o texto.',
'Quote depth label'					=>	'Profundidade máxima de citações [quote]',
'Quote depth help'					=>	'O número máximo de vezes que a tag [quote] pode ser inserida dentro de outra tag [quote], todas as tags excedentes serão eliminadas.',

// Features section
'Features subhead'					=>	'Funções',
'Quick post label'					=>	'Resposta rápida',
'Quick post help'					=>	'Quando ativo, o FluxBB irá adicionar um formulário de resposta rápida no rodapé dos tópicos. Deste modo os usuários podem responder diretamente da página de visualização do tópico.',
'Users online label'				=>	'Usuários online',
'Users online help'					=>	'Exibir na página principal informações sobre visitantes e usuários registrados navegando o site atualmente.',
'Censor words label'				=>	'Palavras censuradas',
'Censor words help'					=>	'Ative isso para censurar palavras específicas no site. Veja %s para mais informações.',
'Signatures label'					=>	'Assinaturas',
'Signatures help'					=>	'Permitir que os usuários anexem uma assinatura às suas mensagens.',
'User has posted label'				=>	'O usuário publicou anteriormente',
'User has posted help'				=>	'Esta função exibe um ponto em frente aos tópicos no viewforum.php caso o usuário autenticado tenha publicado no tópico anteriormente. Desative se estiver experimentando sobrecarga no servidor.',
'Topic views label'					=>	'Visualizações de tópico',
'Topic views help'					=>	'Acompanhe o número de visualizações de cada tópico. Desative se estiver experimentando sobrecarga no servidor.',
'Quick jump label'					=>	'Troca rápida',
'Quick jump help'					=>	'Ativar troca rápida com a lista (trocar de fórum).',
'GZip label'						=>	'Saída GZip',
'GZip help'							=>	'Se ativo, o FluxBB irá compactar em gzip a saída enviada para o navegador dos usuários. Isto irá reduzir o consumo de banda, mas irá usar um pouco mais de processamento do servidor. Esta função requer que o PHP esteja configurado com zlib (--with-zlib). Nota: Se você já possui um dos módulos Apache mod_gzip ou mod_deflate configurados para compactar scripts PHP, você deve desativar esta função.',
'Search all label'					=>	'Pesquisar todos os fóruns',
'Search all help'					=>	'Quando desativado, pesquisas só serão permitidas em um fórum por vez. Desative se o servidor estiver sobrecarregado devido ao excesso de pesquisas.',
'Menu items label'					=>	'Itens de menu adicionais',
'Menu items help'					=>	'Ao inserir hyperlinks HTML nesta caixa de texto, qualquer número de itens pode ser adicionado ao menu de navegação no topo de todas as páginas. O formato para adicionar novos links é X = &lt;a href="URL"&gt;LINK&lt;/a&gt; onde X é a posição na qual o link deverá ser inserido (ex. 0 para inserir no início e 2 para inserir após "Lista de usuários"). Separe cada item com uma quebra de linha.',

// Feeds section
'Feed subhead'						=>	'Feeds',
'Default feed label'				=>	'Tipo de feed padrão',
'Default feed help'					=>	'Selecione o tipo de feed de distribuição a ser utilizado. Nota: Não escolher nenhum não irá desativar os feeds, apenas ocultá-los por padrão.',
'None'								=>	'Nenhum',
'RSS'								=>	'RSS',
'Atom'								=>	'Atom',
'Feed TTL label'					=>	'Duração de cache dos feeds',
'Feed TTL help'						=>	'Os feeds podem ter um cache para reduzir o uso de recursos com os feeds.',
'No cache'							=>	'Não usar cache',
'Minutes'							=>	'%d minutos',

// Reports section
'Reports subhead'					=>	'Relatórios',
'Reporting method label'			=>	'Método de relatório',
'Internal'							=>	'Interno',
'By e-mail'							=>	'Email',
'Both'								=>	'Ambos',
'Reporting method help'				=>	'Selecione o método de gerenciamento de relatórios de tópicos/mensagens. Você pode escolher se os relatórios de tópicos/mensagens devem ser gerenciadas pelo sistema de relatórios interno, enviados por email para os endereços na lista de correio (veja abaixo) ou ambos.',
'Mailing list label'				=>	'Lista de correio',
'Mailing list help'					=>	'Uma lista de assinantes separada por virgulas. As pessoas nesta lista irão receber os relatórios.',

// Avatars section
'Avatars subhead'					=>	'Avatares',
'Use avatars label'					=>	'Usar avatares',
'Use avatars help'					=>	'Quando ativo, os usuários poderão enviar um avatar que será exibido abaixo de seu título.',
'Upload directory label'			=>	'Diretório de envio',
'Upload directory help'				=>	'O diretório de armazenamento de avatares (relativo ao diretório base do FluxBB). O PHP precisa ter permissões de escrita neste diretório.',
'Max width label'					=>	'Largura máxima',
'Max width help'					=>	'A largura máxima permitida para avatares, em pixels (60 é o recomendado).',
'Max height label'					=>	'Altura máxima',
'Max height help'					=>	'A altura máxima permitida para avatares, em pixels (60 é o recomendado).',
'Max size label'					=>	'Tamanho máximo',
'Max size help'						=>	'O tamanho máximo permitido para avatares, em  bytes (10240 é o recomendado).',

// E-mail section
'E-mail subhead'					=>	'Email',
'Admin e-mail label'				=>	'Email do Administrador',
'Admin e-mail help'					=>	'O endereço de email do administrador do site.',
'Webmaster e-mail label'			=>	'Email do Webmaster',
'Webmaster e-mail help'				=>	'Este é o endereço usado como remetente em todos os emails enviados pelo site.',
'Forum subscriptions label'			=>	'Inscrições de fóruns',
'Forum subscriptions help'			=>	'Permitir que os usuários se inscrevam em fóruns (recebem um email quando alguém criar um novo tópico).',
'Topic subscriptions label'			=>	'Inscrições de tópicos',
'Topic subscriptions help'			=>	'Permitir que os usuários se inscrevam em tópicos (recebem um email quando alguém responder o tópico).',
'SMTP address label'				=>	'Endereço do servidor SMTP',
'SMTP address help'					=>	'O endereço de um servidor SMTP externo pelo qual serão enviados os emails. Você pode especificar um número de porta personalizado se o servidor SMTP não utilizar a porta padrão 25 (ex: mail.meuhost.com.br:3580). Deixe em branco para usar o programa de email local.',
'SMTP username label'				=>	'Nome de usuário SMTP',
'SMTP username help'				=>	'Nome de usuário do servidor SMTP. Apenas digite um nome de usuário se for exigido pelo servidor SMTP (a maioria dos servidores <strong>não</strong> exigem autenticação).',
'SMTP password label'				=>	'Senha SMTP',
'SMTP change password help'			=>	'Ative isso se deseja alterar ou excluir a senha atualmente armazenada.',
'SMTP password help'				=>	'Senha do servidor SMTP. Apenas digite uma senha se for exigida pelo servidor SMTP (a maioria dos servidores <strong>não</strong> exigem autenticação). Por favor, digite sua senha duas vezes para confirmar.',
'SMTP SSL label'					=>	'Criptografar SMTP usando SSL',
'SMTP SSL help'						=>	'Criptografa a conexão ao servidor SMTP usando SSL. Só deve ser utilizado caso seu servidor SMTP exija isso e sua versão do PHP suporte SSL.',

// Registration Section
'Registration subhead'				=>	'Registro',
'Allow new label'					=>	'Permitir novos registros',
'Allow new help'					=>	'Controla se o site aceita novos registros. Desative apenas sob circunstâncias especiais.',
'Verify label'						=>	'Verificar registro',
'Verify help'						=>	'Quando ativo, os usuários recebem um email com uma senha aleatória quando se registram. Podem então autenticar-se no site e alterar a senha em seu perfil se desejarem. Esta função também exige que os usuários verifiquem novos endereços de email caso decidam trocar para um endereço diferente do qual usaram durante o registro. Este é um modo efetivo de evitar abuso de registros e SPAM, além de garantir que todos os usuários possuam um endereço de email "correto" em seus perfis.',
'Report new label'					=>	'Notificar novos registros',
'Report new help'					=>	'Se ativo, o FluxBB irá notificar os usuários na lista de correio (veja acima) quando um novo usuário se registrar no fórum.',
'Use rules label'					=>	'Regras de uso do fórum',
'Use rules help'					=>	'Quando ativo, os usuários devem concordar com as regras para poder se registrar (defina-as na caixa de texto abaixo). As regras sempre estarão disponíveis em um link no menu de navegação no topo do site.',
'Rules label'						=>	'Defina suas regras aqui',
'Rules help'						=>	'Aqui você pode definir quaisquer regras e outras informações que os usuários precisem saber ao se registrarem. Se você ativou as regras acima, você deverá digitar algo, caso contrário ela será desativada. Este texto não será processado como mensagens comuns e, portanto, podem conter HTML.',
'E-mail default label'				=>	'Configuração padrão de email',
'E-mail default help'				=>	'Escolha a configuração de privacidade padrão para o registro de novos usuários.',
'Display e-mail label'				=>	'Exibir endereços de email para outros usuários.',
'Hide allow form label'				=>	'Ocultar endereços de email, mas permitir o formulário de email.',
'Hide both label'					=>	'Ocultar endereços de email e desabilitar formulário de email.',

// Announcement Section
'Announcement subhead'				=>	'Anúncios',
'Display announcement label'		=>	'Exibir anúncios',
'Display announcement help'			=>	'Ative isso para exibir a mensagem abaixo como um anúncio geral no site.',
'Announcement message label'		=>	'Mensagem de anúncio',
'Announcement message help'			=>	'Este texto não será processado como uma mensagem comum e, portanto, pode conter HTML.',

// Maintenance Section
'Maintenance subhead'				=>	'Manutenção',
'Maintenance mode label'			=>	'Modo de manutenção',
'Maintenance mode help'				=>	'Quando ativado, o site estará disponível apenas para administradores. Isto deve ser usado caso o site precise ser desativado temporariamente para manutenção. <strong>AVISO! Não saia do site enquanto estiver no modo de manutenção.</strong> Você não poderá autenticar-se novamente.',
'Maintenance message label'			=>	'Mensagem de manutenção',
'Maintenance message help'			=>	'A mensagem que será exibida aos usuários quando o fórum estiver em modo de manutenção. Se deixado em branco, uma mensagem padrão será usada. Este texto não será processado como mensagens comuns e, portanto, pode conter HTML.',

);
