<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'Não foi possível procurar atualizações já que \'allow_url_fopen\' está desativado no sistema.',
'Upgrade check failed message'		=>	'Procura de atualizações falhou por causas desconhecidas.',
'Running latest version message'	=>	'Você está utilizando a versão mais recente do FluxBB.',
'New version available message'		=>	'Uma nova versão do FluxBB foi lançada. Você pode baixar a última versão em %s.',
'Not available'						=>	'Não disponível',
'Forum admin head'					=>	'Administração do fórum',
'NA'								=>	'N/D',
'Welcome to admin'					=>	'Bem-vindo ao painel de controle administrativo do FluxBB. A partir daqui você pode controlar aspectos vitais do site. Dependendo se você é um administrador ou um moderador você pode:',
'Welcome 1'							=>	'Organizar categorias e fóruns.',
'Welcome 2'							=>	'Definir opções e preferências para todo o fórum.',
'Welcome 3'							=>	'Controle de permissões para usuários e visitantes.',
'Welcome 4'							=>	'Visualizar estatísticas de IP para usuários.',
'Welcome 5'							=>	'Banir usuários.',
'Welcome 6'							=>	'Censurar palavras.',
'Welcome 7'							=>	'Definir grupos e promoções de usuários.',
'Welcome 8'							=>	'Eliminar mensagens antigas.',
'Welcome 9'							=>	'Gerenciar relatórios de mensagens.',
'About head'						=>	'Sobre o FluxBB',
'FluxBB version label'				=>	'FluxBB versão',
'Check for upgrade'					=>	'Procurar por atualizações',
'FluxBB version data'				=>	'v%s - %s',
'Server statistics label'      		=>  'Estatísticas do servidor',
'View server statistics'      		=>  'Visualizar estatísticas do servidor',
'Support label'            			=>  'Suporte',
'Forum label'            			=>  'Fórum',
'IRC label'              			=>  'Canal IRC',

// Language definitions used in admin_statistics.php
'PHPinfo disabled message'			=>	'A função PHP phpinfo() foi desativada neste servidor.',
'Server statistics head'			=>	'Estatísticas do servidor',
'Server load label'					=>	'Carga do servidor',
'Server load data'					=>	'%s - %s usuário(s) online',
'Environment label'					=>	'Ambiente',
'Environment data OS'				=>	'Sistema operacional: %s',
'Show info'							=>	'Exibir informações',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Acelerador: %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Cache PHP Alternativo (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Otimizador Zend',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Banco de dados',
'Database data rows'				=>	'Linhas: %s',
'Database data size'				=>	'Tamanho: %s',
);
