<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Forneça um endereço de email válido',
'Email legend 2'			=>	'Digite e confirme um endereço de email válido',
'Localisation legend'		=>	'Defina suas opções de localização',
'Time zone'					=>	'Fuso horário',
'Time zone info'			=>	'Para que o fórum exiba os horários corretamente você deve selecionar seu fuso horário. Se o horário de verão estiver em efeito você também deverá selecionar a opção em questão, que irá avançar os horários em 1 hora.',
'DST'						=>	'O horário de verão está em efeito (avança o horário em 1 hora).',
'Time format'				=>	'Formato de hora',
'Date format'				=>	'Formato de data',
'Default'					=>	'Padrão',
'Language'					=>	'Idioma',
'Email setting info'		=>	'Escolha se prefere que seus endereços de email estejam visíveis para outros usuários ou não e se deseja que outros usuários possam lhe enviar emails a partir do fórum (formulário de email) ou não.',
'Email setting 1'			=>	'Exibir seu endereço de email.',
'Email setting 2'			=>	'Ocultar seu endereço de email mas permitir o formulário de email.',
'Email setting 3'			=>	'Ocultar seu endereço de email e desativar formulário de email.',
'Privacy options legend'	=>	'Definir suas opções de privacidade',
'Confirm pass'				=>	'Confirmar senha',

'Username too short'		=>	'Nomes de usuários devem ter ao menos 2 caracteres. Por favor, escolha um nome de usuário mais longo.',
'Username too long'			=>	'Nomes de usuários devem ter menos de 25 caracteres. Por favor, escolha um nome de usuário mais curto.',
'Username guest'			=>	'O nome de usuário visitante é reservado. Por favor, escolha outro nome de usuário.',
'Username IP'				=>	'Nomes de usuários não podem ter a forma de um endereço IP. Por favor, escolha outro nome de usuário.',
'Username reserved chars'	=>	'Nomes de usuários não podem usar todos os caracteres \', " e [ ou ] de uma vez. Por favor escolha outro nome de usuário.',
'Username BBCode'			=>	'Nomes de usuários não podem conter nenhuma das tags de formatação de texto (BBCode) que o fórum usa. Por favor escolha outro nome de usuário.',
'Banned username'			=>	'The username you entered is banned in this forum. Please choose another username.',
'Pass too short'			=>	'Passwords must be at least 4 characters long. Please choose another (longer) password.',
'Pass not match'			=>	'Passwords do not match.',
'Banned email'				=>	'The email address you entered is banned in this forum. Please choose another email address.',
'Dupe email'				=>	'Alguém já se registrou com este endereço de email. Por favor, escolhe outro endereço de email.',
'Sig too long'				=>	'Assinaturas não podem conter mais que %1$s caracteres. Por favor, reduza sua assinatura por %2$s caracteres.',
'Sig too many lines'		=>	'Assinaturas não podem conter mais que %s linhas.',
'Bad ICQ'					=>	'Você digitou um UIN ICQ inválido. Por favor, volte e o corrija.',

'UTC-12:00'					=>	'(UTC-12:00) Linha de Data Internacional do Oeste',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Ilhas Cook',
'UTC-09:30'					=>	'(UTC-09:30) Arquipélago das Marquesas',
'UTC-09:00'					=>	'(UTC-09:00) Alasca, Arquipélago de Gambier',
'UTC-08:30'					=>	'(UTC-08:30) Ilhas Pitcairn',
'UTC-08:00'					=>	'(UTC-08:00) Pacífico',
'UTC-07:00'					=>	'(UTC-07:00) Montanha',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Oriental',
'UTC-04:00'					=>	'(UTC-04:00) Atlântico',
'UTC-03:30'					=>	'(UTC-03:30) Terra Nova',
'UTC-03:00'					=>	'(UTC-03:00) Brasil, Groenlândia Central',
'UTC-02:00'					=>	'(UTC-02:00) Médio Atlântico',
'UTC-01:00'					=>	'(UTC-01:00) Açores, Cabo Verde, Groenlândia Oriental',
'UTC'						=>	'(UTC) Europa Ocidental, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Europa Central, África Ocidental',
'UTC+02:00'					=>	'(UTC+02:00) Europa Oriental, África Central',
'UTC+03:00'					=>	'(UTC+03:00) África Oriental',
'UTC+03:30'					=>	'(UTC+03:30) Irã',
'UTC+04:00'					=>	'(UTC+04:00) Moscou, Golfo, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afeganistão',
'UTC+05:00'					=>	'(UTC+05:00) Paquistão',
'UTC+05:30'					=>	'(UTC+05:30) Índia, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Butão, Ecaterimburgo',
'UTC+06:30'					=>	'(UTC+06:30) Ilhas Cocos (Keeling), Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'					=>	'(UTC+08:00) Grande China, Austrália Ocidental, Krasnoyarsk',
'UTC+08:45'					=>	'(UTC+08:45) Austrália Ocidental Sul',
'UTC+09:00'					=>	'(UTC+09:00) Japão, Korea, Chita, Irkutsk',
'UTC+09:30'					=>	'(UTC+09:30) Austrália Central',
'UTC+10:00'					=>	'(UTC+10:00) Austrália Oriental',
'UTC+10:30'					=>	'(UTC+10:30) Arquipélago de Lorde Howe',
'UTC+11:00'					=>	'(UTC+11:00) Ilha de Santa Isabel, Vladivostok',
'UTC+11:30'					=>	'(UTC+11:30) Ilha Norfolk',
'UTC+12:00'					=>	'(UTC+12:00) Nova Zelândia, Fiji, Magadan',
'UTC+12:45'					=>	'(UTC+12:45) Ilha Chatham',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Ilhas Fênix, Península de Kamchatka',
'UTC+14:00'					=>	'(UTC+14:00) Ilhas da Linha'

);
