<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'Menu do perfil',
'Section essentials'			=>	'Essenciais',
'Section personal'				=>	'Pessoal',
'Section messaging'				=>	'Comunicação',
'Section personality'			=>	'Personalidade',
'Section display'				=>	'Exibição',
'Section privacy'				=>	'Privacidade',
'Section admin'					=>	'Administração',

// Miscellaneous
'Username and pass legend'		=>	'Digite seu nome de usuário e senha',
'Personal details legend'		=>	'Digite seus dados pessoais',
'Contact details legend'		=>	'Digite seus detalhes de comunicação',
'User activity'					=>	'Atividade do usuário',
'Paginate info'					=>	'Digite o número de tópicos e mensagens que deseja visualizar em cada página.',

// Password stuff
'Pass key bad'					=>	'A chave de ativação de senha especificada está incorreta ou expirou. Por favor faça outra solicitação de nova senha. Se isto falhar, contate o administrador do fórum em',
'Pass updated'					=>	'Sua senha foi atualizada. Você pode agora se autenticar usando a nova senha.',
'Pass updated redirect'			=>	'Senha atualizada. Redirecionando …',
'Wrong pass'					=>	'Senha antiga errada.',
'Change pass'					=>	'Alterar senha',
'Change pass legend'			=>	'Digite e confirme a sua nova senha',
'Old pass'						=>	'Antiga senha',
'New pass'						=>	'Nova senha',
'Confirm new pass'				=>	'Confirmar nova senha',
'Pass info'						=>	'Senhas devem ter ao menos 4 caracteres. Senhas são sensíveis à caixa.',

// Email stuff
'Email key bad'					=>	'A chave de ativação de email especificada está errada ou expirou. Por favor faça outra solicitação de alteração de email. Se isto falhar, contate o administrador do fórum em',
'Email updated'					=>	'Seu endereço de email foi atualizado.',
'Activate email sent'			=>	'Um email foi enviado para o endereço especificado com instruções sobre como ativar seu novo endereço de email. Caso não o receba, você pode contatar o administrador do fórum em',
'Email legend'					=>	'Digite seu novo endereço de email',
'Email instructions'			=>	'Um email será enviado ao seu novo endereço com um link de ativação. Você deve clicar no link no email para ativar seu novo endereço.',
'Change email'					=>	'Alterar endereço de email',
'New email'						=>	'Novo email',

// Avatar upload stuff
'Avatars disabled'				=>	'O administrador desativou o suporte a avatares.',
'Too large ini'					=>	'O arquivo selecionado é muito grande para ser enviado. O servidor não permitiu o envio.',
'Partial upload'				=>	'O arquivo selecionado foi apenas parcialmente enviado. Por favor tente novamente.',
'No tmp directory'				=>	'O PHP não pode salvar o arquivo enviado em um local temporário.',
'No file'						=>	'Você não selecionou um arquivo para enviar.',
'Bad type'						=>	'O arquivo que você tentou enviar é de um formato não permitido. Formato permitidos são gif, jpeg e png.',
'Too wide or high'				=>	'O arquivo que você tentou enviar é mais largo e/ou alto que o máximo permitido',
'Too large'						=>	'O arquivo que você tentou enviar é mais largo que o máximo permitido',
'pixels'						=>	'pixels',
'bytes'							=>	'bytes',
'Move failed'					=>	'O servidor não pode salvar o arquivo enviado. Por favor contate o administrador do fórum em',
'Unknown failure'				=>	'Um erro desconhecido ocorreu. Por favor tente novamente.',
'Avatar upload redirect'		=>	'Avatar enviado. Redirecionando …',
'Avatar deleted redirect'		=>	'Avatar excluído. Redirecionando …',
'Avatar desc'					=>	'Um avatar é uma pequena imagem que será exibida abaixo do seu nome de usuário nas suas mensagens. Não pode ser maior que',
'Upload avatar'					=>	'Enviar avatar',
'Upload avatar legend'			=>	'Escolha um arquivo para enviar e usar como avatar',
'Delete avatar'					=>	'Excluir avatar', // only for admins
'File'							=>	'Arquivo',
'Upload'						=>	'Enviar', // submit button

// Form validation stuff
'Forbidden title'				=>	'O título que você digitou contém uma palavra proibida. Você deve escolher um título diferente.',
'Profile redirect'				=>	'Perfil atualizado. Redirecionando …',

// Profile display stuff
'Users profile'					=>	'Perfil de %s',
'Username info'					=>	'Nome de usuário: %s',
'Email info'					=>	'Email: %s',
'Posts info'					=>	'Mensagens: %s',
'Registered info'				=>	'Registrado: %s',
'Last post info'				=>	'Última mensagem: %s',
'Last visit info'				=>	'Última visita: %s',
'Show posts'					=>	'Exibir todas as mensagens',
'Show topics'					=>	'Exibir todos os tópicos',
'Show subscriptions'			=>	'Exibir todas as inscrições',
'Realname'						=>	'Nome real',
'Location'						=>	'Localização',
'Website'						=>	'Website',
'Invalid website URL'			=>  'A URL do website que você digitou é inválida.',
'Website not allowed'			=>  'Você ainda não tem permissão para adicionar um website ao seu perfil.',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'Conta Microsoft',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'Avatar',
'Signature'						=>	'Assinatura',
'Sig max size'					=>	'Comprimento máximo: %s caracteres / Máximo de linhas: %s',
'Avatar legend'					=>	'Defina suas opções de exibição de avatar',
'Avatar info'					=>	'Um avatar é uma pequena imagem que será exibida em todas as suas mensagens. Você pode enviar um avatar clicando no link abaixo.',
'Change avatar'					=>	'Trocar avatar',
'Signature legend'				=>	'Componha sua assinatura',
'Signature info'				=>	'Uma assinatura é um pequeno texto que é anexado abaixo de suas mensagens. Nele, você pode inserir qualquer coisa que desejar. Talvez você queira inserir sua citação favorita ou seu signo. Você decide! Na sua assinatura você pode usar BBCode se for permitido pela administração do fórum. Você pode ver as funções que são permitidas listadas abaixo do campo de edição da sua assinatura.',
'Sig preview'					=>	'Prévia da assinatura atual:',
'No sig'						=>	'Não há uma assinatura definida no seu perfil.',
'Signature quote/code/list/h'	=>	'As tags BBCode quote, code, list, e heading não são permitidos em assinaturas.',
'Topics per page'				=>	'Tópicos',
'Posts per page'				=>	'Mensagens',
'Leave blank'					=>	'Deixe em branco para usar o padrão do fórum.',
'Subscription legend'			=>	'Defina suas opções de inscrição',
'Notify full'					=>	'Inclua uma versão em texto simples das novas mensagens em emails de notificação de inscrições.',
'Auto notify full'				=>	'Inscrever-me automaticamente em todos os tópicos onde eu participar.',
'Show smilies'					=>	'Exibir emoticons em forma de ícones gráficos.',
'Show images'					=>	'Exibir imagens nas mensagens.',
'Show images sigs'				=>	'Exibir imagens nas assinaturas dos usuários.',
'Show avatars'					=>	'Exibir avatares dos usuários nas mensagens.',
'Show sigs'						=>	'Exibir assinaturas dos usuários.',
'Style legend'					=>	'Selecione seu estilo preferido',
'Styles'						=>	'Estilos',
'Admin note'					=>	'Nota do administrador',
'Pagination legend'				=>	'Digite suas opções de paginação',
'Post display legend'			=>	'Defina suas opções de visualização de mensagens',
'Post display info'				=>	'Se você usa uma conexão lenta, desabilitar estas opções, principalmente a exibição de imagens nas mensagens e assinaturas, fará com que as páginas carreguem mais rapidamente.',
'Instructions'					=>	'Quando atualizar seu perfil, você será redirecionado para esta página.',

// Administration stuff
'Group membership legend'		=>	'Escolha o grupo de usuário',
'Save'							=>	'Salvar',
'Set mods legend'				=>	'Definir acesso de moderador',
'Moderator in info'				=>	'Escolha os fóruns que este usuário poderá moderar. Nota: Isto se aplica apenas a moderadores. Administradores sempre possuem permissões completas em todos os fóruns.',
'Update forums'					=>	'Atualizar fóruns',
'Delete ban legend'				=>	'Excluir (administradores apenas) ou banir usuário',
'Delete user'					=>	'Excluir usuário',
'Ban user'						=>	'Banir usuário',
'Confirm delete legend'			=>	'Importante: leia antes de excluir o usuário',
'Confirm delete user'			=>	'Confirmar exclusão do usuário',
'Confirmation info'				=>	'Por favor confirma que deseja excluir o usuário', // the username will be appended to this string
'Delete warning'				=>	'Aviso! Usuários e/ou mensagens excluídas não podem ser recuperados. Se você escolher não excluir as mensagens feitas por este usuário, as mensagens só poderão ser excluídas manualmente mais tarde.',
'Delete posts'					=>	'Excluir quaisquer mensagens e tópicos que este usuário tenha criado.',
'Delete'						=>	'Excluir', // submit button (confirm user delete)
'User delete redirect'			=>	'Usuário excluído. Redirecionando …',
'Group membership redirect'		=>	'Adesão ao grupo salva. Redirecionando …',
'Update forums redirect'		=>	'Direitos de moderação do fórum atualizados. Redirecionando …',
'Ban redirect'					=>	'Redirecionando …',
'No delete admin message'		=>	'Administradores não podem ser excluídos. Para poder excluir este usuário, você primeiro deverá movê-lo para outro grupo de usuários.',

);
