<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'Nije moguće proveriti nadogradǌu posto \'allow_url_fopen\' je iskǉučen na ovom sistemu.',
'Upgrade check failed message'		=>	'Provera za nadogradǌu je bila nesupešna iz poznatih razloga.',
'Running latest version message'	=>	'Koristite posledǌu verziju FluxBB-a.',
'New version available message'		=>	'Nova verzija FluxBB-a je izdata. Možete preuzeti posledǌu verziju na %s.',
'Deleted install.php redirect'		=>	'Fajl je uspešno uklonjen. Preusmeravam...',
'Delete install.php failed'			=>	'Nije moguće ukloniti install.php. Molimo Vas da to uradite ručno.',
'Not available'						=>	'Nije dostupno',
'Forum admin head'					=>	'Administracija foruma',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'Dobrodošli na administratorsku kontrolnu tablu FluxBB-a. Odavde možete kontrolisati bitne aspekte foruma. U zavinosti od toga da li ste Vi administrator ili moderator možete:',
'Welcome 1'							=>	'Organizujete kategorije i forum.',
'Welcome 2'							=>	'Postavite sveobuhvatne opcije i podešavaǌa foruma.',
'Welcome 3'							=>	'Kontrolu dozvola za korisnike i goste.',
'Welcome 4'							=>	'Vidite IP statistike za korisnike.',
'Welcome 5'							=>	'Zabranite korisnike.',
'Welcome 6'							=>	'Cenzurišete reči.',
'Welcome 7'							=>	'Postavite korisničke grupe i unapređeǌa.',
'Welcome 8'							=>	'Odrežete stare poruke.',
'Welcome 9'							=>	'Rukujete sa izveštajima o porukama.',
'Alerts head'						=>	'Upozorenja',
'Install file exists'				=>	'Fajl install.php postoji, a trebalo bi da bude uklonjen. %s.',
'Delete install file'				=>	'Obrišite ga',
'About head'						=>	'O FluxBB-u',
'FluxBB version label'				=>	'FluxBB verzija',
'Check for upgrade'					=>	'Provera za nadogradǌu',
'FluxBB version data'				=>	'v%s - %s',
'Server statistics label'			=>	'Statistike servera',
'View server statistics'			=>	'Vidi statistike servera',
'Support label'						=>	'Podrška',
'Forum label'						=>	'Forum',
'IRC label'							=>	'IRC kanal',

// Language definitions used in admin_statistics.php
'PHPinfo disabled message'			=>	'PHP funkcija phpinfo() je iskǉučena na ovom serveru.',
'Server statistics head'			=>	'Statistike servera',
'Server load label'					=>	'Opterećeǌe servera',
'Server load data'					=>	'%s - %s korisnik(a) je prijavǉen(o)',
'Environment label'					=>	'Okružeǌe',
'Environment data OS'				=>	'Operativni sistem: %s',
'Show info'							=>	'Prikaži informacije',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Accelerator: %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Baza podataka',
'Database data rows'				=>	'Redovi: %s',
'Database data size'				=>	'Veličina: %s',
);
