<?php

// Language definitions used in admin_options.php
$lang_admin_options = array(

'Bad HTTP Referer message'			=>	'Loš HTTP_REFERER. Ako ste pomerili ove forume sa jedne lokacije na drugu ili ste promenili domene, morate da ažurirate Osnovni URL ručno u bazi podataka (potražite o_base_url u tabeli za konfiguraciju - config table) i onda očistite keš sa brisaǌem svih .php fajlova u /cache direktorijumu.',
'Must enter title message'			=>	'Morate uneti naziv foruma.',
'Invalid e-mail message'			=>	'Administratorska email adresa koju ste uneli je nevažeća.',
'Invalid webmaster e-mail message'	=>	'Webmaster email adresa koju ste uneli je nevažeća.',
'SMTP passwords did not match'		=>	'Morate uneti dva puta potpuno istu SMTP šifru da bi ste je promenili.',
'Enter announcement here'			=>	'Unesite Vašu objavu ovde.',
'Enter rules here'					=>	'Unesite Vaša pravila ovde.',
'Default maintenance message'		=>	'Forumi su trenutno oboreni zbog održavaǌa. Pokušajte ponovo za nekoliko minuta.',
'Timeout error message'				=>	'Vrednost "Vreme isteka na mreži" mora biti maǌa od vrednosti "Vreme isteka posete".',
'Options updated redirect'			=>	'Opcije su ažurirane. Preusmeravam …',
'Options head'						=>	'Opcije',

// Essentials section
'Essentials subhead'				=>	'Osnove',
'Board title label'					=>	'Naziv foruma',
'Board title help'					=>	'Naziv ove oglasne table (koji se prikazuje na vrhu svake strane). Ovo poǉe <strong>ne</strong> sme sadržati HTML.',
'Board desc label'					=>	'Opis foruma',
'Board desc help'					=>	'Kratak opis ove oglasne table (koji se prikazuje na vrhu svake strane). Ovo poǉe može sadržati HTML.',
'Base URL label'					=>	'Osnovni URL',
'Base URL help'						=>	'Kompletan URL foruma bez suvišnih kosih crta (npr. http://www.mydomain.com/forums). Ovo <strong>mora</strong>  da bude tačno kako bi sve administratorske i moderatorske karakteristike radile. Ako dobijete "Bad referer" greške, razlog je neispravan URL.',
'Base URL problem'          =>  'Vaša instalacija ne podržava automatsku konverziju internacionalnih domenskih imena. Kako Vaš osnovni URL sadrži specijalne karaktere, Vi <strong>morate</strong> da koristite internet konverter kako bi izbegli "Bad referer" greške.',
'Timezone label'					=>	'Podrazumevana vremeska zona',
'Timezone help'						=>	'Podrazumevana vremeska zona za goste i korisnike koji pokušavaju da se registruju na forum.',
'DST label'							=>	'Podešavaǌe za DST',
'DST help'							=>	'Proveri da li je pomereno vreme na snazi (unapred jedan sat).',
'Language label'					=>	'Podrazumevani jezik',
'Language help'						=>	'Podrazumevani jezik za goste i korisnike koji nisu promenili podrazumevani jezik u ǌihovim profilima. Ako uklonite jezički paket, ovo mora biti ažurirano.',
'Default style label'				=>	'Podrazumevani stil',
'Default style help'				=>	'Podrazumevani stil za goste i korisnike koji promene podrazumevani stil u ǌihovim profilima.',

// Essentials section timezone options
'UTC-12:00'							=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'							=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'							=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'							=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'							=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'							=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'							=>	'(UTC-08:00) Pacific',
'UTC-07:00'							=>	'(UTC-07:00) Mountain',
'UTC-06:00'							=>	'(UTC-06:00) Central',
'UTC-05:00'							=>	'(UTC-05:00) Eastern',
'UTC-04:00'							=>	'(UTC-04:00) Atlantic',
'UTC-03:30'							=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'							=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'							=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'							=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'								=>	'(UTC) Western European, Greenwich',
'UTC+01:00'							=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'							=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'							=>	'(UTC+03:00) Eastern African',
'UTC+03:30'							=>	'(UTC+03:30) Iran',
'UTC+04:00'							=>	'(UTC+04:00) Moscow, Gulf, Samara',
'UTC+04:30'							=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'							=>	'(UTC+05:00) Pakistan',
'UTC+05:30'							=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'							=>	'(UTC+05:45) Nepal',
'UTC+06:00'							=>	'(UTC+06:00) Bangladesh, Bhutan, Yekaterinburg',
'UTC+06:30'							=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'							=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'							=>	'(UTC+08:00) Greater China, Australian Western, Krasnoyarsk',
'UTC+08:45'							=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'							=>	'(UTC+09:00) Japan, Korea, Chita, Irkutsk',
'UTC+09:30'							=>	'(UTC+09:30) Australian Central',
'UTC+10:00'							=>	'(UTC+10:00) Australian Eastern',
'UTC+10:30'							=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'							=>	'(UTC+11:00) Solomon Island, Vladivostok',
'UTC+11:30'							=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'							=>	'(UTC+12:00) New Zealand, Fiji, Magadan',
'UTC+12:45'							=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'							=>	'(UTC+13:00) Tonga, Phoenix Islands, Kamchatka',
'UTC+14:00'							=>	'(UTC+14:00) Line Islands',

// Timeout Section
'Timeouts subhead'					=>	'Vreme i vremena isteka',
'Time format label'					=>	'Format vremena',
'PHP manual'						=>	'PHP priručnik',
'Time format help'					=>	'[Trenutni format: %s]. Pogledajte %s za opcije formatiraǌa.',
'Date format label'					=>	'Format datuma',
'Date format help'					=>	'[Trenutni format: %s]. Pogledajte %s za opcije formatiraǌa.',
'Visit timeout label'				=>	'Vreme isteka poseti',
'Visit timeout help'				=>	'Broj sekundi koje korisnik mora da čeka pre nego što ǌegova/ǌena posledǌa poseta bude ažurirana (primarno utiče na indikatore novih poruka).',
'Online timeout label'				=>	'Vreme isteka na mreži',
'Online timeout help'				=>	'Broj sekundi koje korisnik mora da čeka pre nego što bude pomeren sa liste korisnika koji su na mreži.',
'Redirect time label'				=>	'Vreme za preusmeravaǌe',
'Redirect time help'				=>	'Broj sekundi za čekaǌe prilikom preusmeravaǌa. Ako je postavǉeno na 0, neće biti prikazana strana za preusmeravaǌe (nije preporučeno).',

// Display Section
'Display subhead'					=>	'Prikaz',
'Version number label'				=>	'Broj verzije',
'Version number help'				=>	'Prikaži FluxBB verziju u zaglavǉu na dnu.',
'Info in posts label'				=>	'Korisničke informacije u porukama',
'Info in posts help'				=>	'Prikaži informacije o korisniku koji je poslao poruku ispod korisničkog imena u pregledu teme. Informacija utiče na lokaciju, datum registrovaǌa, broj poruke i kontakt linkove (email i URL).',
'Post count label'					=>	'Broj korisničke poruke',
'Post count help'					=>	'Prikaži broj poruka koje poslao korisnik (utiče na izgled teme, profil i korisničku listu).',
'Smilies label'						=>	'Smeškovi u porukama',
'Smilies help'						=>	'Konvertuj smeškove u male grafičke ikonice.',
'Smilies sigs label'				=>	'Smeškovi u potpisima',
'Smilies sigs help'					=>	'Konvertuj smeškove u male grafičke ikonice u potpisima korisnika.',
'Clickable links label'				=>	'Učini linkove klikabilnim',
'Clickable links help'				=>	'Kada je ukǉučeno, FluxBB će automatski detektovati svaki URL u porukama i napraviti ih klikabilnim.',
'Topic review label'				=>	'Pregled teme',
'Topic review help'					=>	'Maksimalni broj poruka za prikazivaǌe kada se piše poruka (najnovije prvo). Postavite na 0 da bi iskǉučili.',
'Topics per page label'				=>	'Teme po strani',
'Topics per page help'				=>	'Podrazumevani broj tema za prikazivaǌe po strani na forumu. Korisnici mogu personalizovati ovo podešavaǌe.',
'Posts per page label'				=>	'Poruke po strani',
'Posts per page help'				=>	'Podrazumevani broj poruka za prikazivaǌe po strani u temi. Korisnici mogu personalizovati ovo podešavaǌe.',
'Indent label'						=>	'Veličina uvlačeǌa',
'Indent help'						=>	'Ako je postavǉeno na 8, običan tab će biti korišćen kada se prikazuje tekst unutar [code][/code] oznake. Inače ovi prazni karakteri će biti korišćeni za uvlačeǌe teksta.',
'Quote depth label'					=>	'Maksimalna dubina [quote]',
'Quote depth help'					=>	'Maksimalni broj puta koji [quote] oznaka može ići unutar druge [quote] oznake, svaka oznaka dubǉa od navedenog će biti odbačena.',

// Features section
'Features subhead'					=>	'Karakteristike',
'Quick post label'					=>	'Brz odgovor',
'Quick post help'					=>	'Kada je ukǉučen, FluxBB će dodati formu brzog odgovora na dno tema. Na ovaj način korisnici mogu da napišu poruku direktno sa pregleda teme.',
'Users online label'				=>	'Prijavǉeni korisnici',
'Users online help'					=>	'Prikaži informacije na indikator strani o gostima i registrovanim korisnicima koji trenutno pregledaju forum.',
'Censor words label'				=>	'Cenzurisane reči',
'Censor words help'					=>	'Ukǉucite ovo da bi cenzurisali reči na forumu. Pogledajte %s za više informacija.',
'Signatures label'					=>	'Potpisi',
'Signatures help'					=>	'Dozvoli korisnicima da dodaju automatski potpis na kraju svake poruke.',
'User has posted label'				=>	'Korisnik je pisao ranije',
'User has posted help'				=>	'Ova karakteristika pokazuje tačku na početku tema u viewforum.php u slučaju da je trenutno prijavǉen korisnik več pisao na temi ranije. Iskǉučite, ako vidite da postoji veliko opterećeǌe servera.',
'Topic views label'					=>	'Pregledi teme',
'Topic views help'					=>	'Pratite broj pregleda teme. Iskǉučite ako vidite da postoji veliko opterećeǌe servera.',
'Quick jump label'					=>	'Brz skok',
'Quick jump help'					=>	'Ukǉuči brzi skok (skok na forum) padajuću listu.',
'GZip label'						=>	'GZip izlaz',
'GZip help'							=>	'Ako je ukǉučeno, FluxBB će gzip izlaz poslati na pretraživač. Ovo će smaǌiti iskorišćenost propusnog opsega, ali će koristiti malo više procesorskog vremena. Ova karakteristika zahteva da je PHP konfigurisan sa zlib (--with-zlib). Primedba: Ako već imate jedan od  Apache modula mod_gzip ili mod_deflate postavǉene da kompresuju PHP skripte, trebalo bi da iskǉučite ovu opciju.',
'Search all label'					=>	'Pretraži sve forume',
'Search all help'					=>	'Kada je iskǉučeno, pretraživaǌa će biti jedino dozvoǉena na jednom forumu u jednom trenutku. Iskǉučite ako je optrećeǌe servera visoko zbog zahtevnog pretraživaǌa.',
'Menu items label'					=>	'Dodatne stavke u meniju',
'Menu items help'					=>	'Sa dodavaǌem HTML hiperlinkova u ovom okviru za tekst, bilo koji broj stavki može biti dodat u meniju za navigaciju na vrhu svih stranica. Format za dodavaǌe novih linkova je X = &lt;a href="URL"&gt;LINK&lt;/a&gt; gde je X pozicija na koju bi link trebalo da bude ubačen (npr. 0 za ubacivaǌe na početku i 2 za ubacivaǌe posle "Liste korisnika"). Odvojite ulaze sa prelomom reda.',

// Feeds section
'Feed subhead'						=>	'Agregacija poruka',
'Default feed label'				=>	'Podrazumevani tip agregiranih poruka',
'Default feed help'					=>	'Odaberi tip agregiranih poruka za prikazivaǌe. Napomena: Agregirane poruke neće biti iskǉučene ako ništa nije izabrano, samo će podrazumevano biti sakrivene.',
'None'								=>	'Nijedan',
'RSS'								=>	'RSS',
'Atom'								=>	'Atom',
'Feed TTL label'					=>	'Trajaǌe skladišteǌa agregiranih poruka',
'Feed TTL help'						=>	'Agregirane poruke mogu biti skladištene kako bi maǌe koristile resurse.',
'No cache'							=>	'Ne skladišti',
'Minutes'							=>	'%d minuta',

// Reports section
'Reports subhead'					=>	'Izveštaji',
'Reporting method label'			=>	'Metod za izveštavaǌe',
'Internal'							=>	'Interni',
'By e-mail'							=>	'Email',
'Both'								=>	'Oba',
'Reporting method help'				=>	'Odaberi metod za obrađivaǌe izveštaja za temu/poruku. Možete odabrati da li izveštaji tema/poruka treba da budu obrađeni internim sistemom za izveštaje, ili poslati email-om na adrese mailing liste (pogledati ispod) ili oba.',
'Mailing list label'				=>	'Mailing lista',
'Mailing list help'					=>	'Zarezom odvojiti prijavǉene za izveštaje. ǈudi na ovoj listi su primaoci izveštaja.',

// Avatars section
'Avatars subhead'					=>	'Avatar',
'Use avatars label'					=>	'Koristi avatare',
'Use avatars help'					=>	'Kada je ukǉučeno, korisnici će moći da otpreme avatar koji će biti prikazan ispod ǌihovog naziva.',
'Upload directory label'			=>	'Otpremi direktorijum',
'Upload directory help'				=>	'Otpremi direktorijum za avatare (relativno u odnosu na FluxBB osnovni direktorijum). PHP mora imati mogućnost pisaǌa u ovom direktorijumu.',
'Max width label'					=>	'Maksimalna širina',
'Max width help'					=>	'Maksimalno dozvoǉena širina avatara u pikselima (60 je preproručeno).',
'Max height label'					=>	'Maksimalna visina',
'Max height help'					=>	'Maksimalno dozvoǉena visina avatara u pikselima (60 je preproručeno).',
'Max size label'					=>	'Maksimalna veličina',
'Max size help'						=>	'Maksimalno dozvoǉena veličina avatara u bajtovima (10240 je preproručeno).',

// E-mail section
'E-mail subhead'					=>	'Email',
'Admin e-mail label'				=>	'Administratorski email',
'Admin e-mail help'					=>	'Email adresa administratora foruma.',
'Webmaster e-mail label'			=>	'Webmaster email',
'Webmaster e-mail help'				=>	'Ovo je adresa na koju će biti adresirani svi email-ovi poslati od strane foruma.',
'Forum subscriptions label'			=>	'Prijave na forum',
'Forum subscriptions help'			=>	'Omogući korisnicima da se prijave na forum (dobiti email kada neko kreira novu temu).',
'Topic subscriptions label'			=>	'Prijave na temu',
'Topic subscriptions help'			=>	'Omogući korisnicima da se prijave teme (dobiti email kada neko odgovori).',
'SMTP address label'				=>	'SMTP serverska adresa',
'SMTP address help'					=>	'Adresa eksternog SMTP servera sa koga se šaǉu email-ovi. Možete specificirati neki drugi broj porta ako SMTP server ne koristi predefinisani port 25 (primer: mail.mojhost.com:3580). Ostavite prazno ako želite da koristite lokalni mail program.',
'SMTP username label'				=>	'SMTP korisničko ime',
'SMTP username help'				=>	'Korisničko ime za SMTP server. Unesite korisničko ime samo ako je zahtevano od SMTP servera (većina servera <strong>ne</strong> zahtevaju proveru indentiteta).',
'SMTP password label'				=>	'SMTP šifra',
'SMTP change password help'			=>	'Proverite ovo ako ako želite da promenite ili obrišete trenutno sačuvanu šifru.',
'SMTP password help'				=>	'Šifra za SMTP server. Unesite šifru samo ako je zahtevana od SMTP servera (većina servera <strong>ne</strong> zahtevaju proveru indentiteta). Molim Vas unesite Vašu šifru dvaput kako biste je potvrdili.',
'SMTP SSL label'					=>	'Enkriptuj SMTP korišćeǌem SSL',
'SMTP SSL help'						=>	'Enkriptuj konekciju ka SMTP serveru korišćeǌem SSL. Ovo treba koristiti samo ako to SMTP server zahteva i ako Vaša verzija PHP-a podržava SSL.',

// Registration Section
'Registration subhead'				=>	'Registracija',
'Allow new label'					=>	'Dozvoli nove registracije',
'Allow new help'					=>	'Kontrole da li da ovaj forum prihvata nove registracije. Iskǉuči samo u slučaju posebnih okolnosti.',
'Verify label'						=>	'Verifikuj registracije',
'Verify help'						=>	'Kada je ukǉučeno, korisnici dobijaju slučajne šifre putem email-a kada se registruju. Oni se mogu prijaviti i promeniti šifru na ǌihovom profilu ako to smatraju potrebnim. Ova karakteristika takođe zahteva od korisnika da se prijave, kako bi verifikovali email adresu ako odluče da promene onu sa kojom su se registrovali. Ovo je efikasan način za sprečavaǌe zloupotrebe registracije i omogućava da svi korisnici imaju "tačnu" email adresu u svojim profilima.',
'Report new label'					=>	'Prijavi nova registrovaǌa',
'Report new help'					=>	'Ako je ukǉučeno, FluxBB će obavestiti korisnike sa mailing liste (pogledati ispod) kada se novi korisnik registrovao na forumu.',
'Use rules label'					=>	'Korisnička pravila foruma',
'Use rules help'					=>	'Kada je ukǉučeno, korisnici se moraju složiti sa kompletom pravila kada se registruju (unesi tekst ispod). Pravila će uvek biti dostupna putem linka na navigacionoj tabli na vrhu svake strane.',
'Rules label'						=>	'Unesite Vaša pravila ovde',
'Rules help'						=>	'Ovde možete uneti pravila ili informacije koje korisnik mora da pregleda i prihvati kada se registruje. Ako omogućite ovu opciju, onda morate uneti nešto u navedeno polje ili će ova opcija ostati onemogućena. Ovaj tekste neće biti razčlaǌivan kao obična poruka i prema tome može sadržati HTML.',
'E-mail default label'				=>	'Podrazumevana podešavaǌa za email',
'E-mail default help'				=>	'Izaberi podrazumevana podešavaǌa privatnosti za nove registrovane korisnike.',
'Display e-mail label'				=>	'Prikaži email adresu drugim korisnicima.',
'Hide allow form label'				=>	'Sakrij email adresu, ali dozvoli formiraǌe e-mail-a.',
'Hide both label'					=>	'Sakrij email adresu, ali ne dozvoli formiraǌe e-mail-a.',

// Announcement Section
'Announcement subhead'				=>	'Najave',
'Display announcement label'		=>	'Prikaži najave',
'Display announcement help'			=>	'Ukǉuči ovo da bi se prikazala poruka ispod na forumu.',
'Announcement message label'		=>	'Poruka najave',
'Announcement message help'			=>	'Ovaj tekst neće biti rasčlaǌen kao obična poruka i prema tome može sadržati HTML.',

// Maintenance Section
'Maintenance subhead'				=>	'Održavaǌe',
'Maintenance mode label'			=>	'Mod za održavaǌe',
'Maintenance mode help'				=>	'Kada je ukǉučeno, forum će jedino biti dostupan Administratorima. Ovo treba biti korišćeno ako forum zbog održavaǌa mora da bude privremeno stopiran. <strong>UPOZOREǋE! Nemojte se odjaviti kada je forum u modu za održavaǌe.</strong> Nećete biti u mogućnosti da se ponovo prijavite na forum.',
'Maintenance message label'			=>	'Poruka održavaǌa',
'Maintenance message help'			=>	'Poruka koja će biti prikazana korisnicima kada je forum u modu za održavaǌe. Ako se ostavi prazno, podrazumevana poruka će biti korišćena. Ovaj tekst neće biti rasčlaǌen kao obična poruka i prema tome može sadržati HTML.',

);
