<?php

// Language definitions used in admin_maintenance.php
$lang_admin_maintenance = array(

'Maintenance head'				=>	'Održavaǌe foruma',
'Rebuild index subhead'			=>	'Ponovo izgraditi indeks pretraživaǌa',
'Rebuild index info'			=>	'Ako ste dodali, izmenili ili uklonili poruke ručno u bazi podataka ili ako imate problema sa pretraživaǌem, treba ponovo izgraditi indeks pretražuvaǌa. Za najboǉe performanse, treba staviti forum u %s tokom ponovnog izgrađivaǌa. <strong>Ponovno izgrađivaǌe indeksa za pretraživaǌe može dugo trajati i povećati opterećeǌe servera u toku procesa ponovne izgradǌe!</strong>',
'Posts per cycle label'			=>	'Poruke po ciklusu',
'Posts per cycle help'			=>	'Broj poruka za procesiranje po strani. Npr. ako ste uneli 300, trista poruka bi se procesiralo i onda bi se tek strana osvežila. Ovo sprečava isticanje vremenske validnosti skripte u toku procesa ponovnog izgrađivaǌa.',
'Starting post label'			=>	'Startovaǌe indentifikacije poruke',
'Starting post help'			=>	'ID poruke od koje počinje izgrađivanje baze. Podrazumevana vrednost je prva dostupna indentifikacija u bazi podataka. Obično ovo ne biste želeli da promenite.',
'Empty index label'				=>	'Prazan indeks',
'Empty index help'				=>	'Odaberite ovo ako želite da indeks za pretraživaǌe bude ispražǌen pre ponovne izgradǌe (pogledajte ispod).',
'Rebuild completed info'		=>	'Kada se proces završi, biće te preusmereni nazad na ovu stranu. Preporučuje se da imate omogućen JavaScript u vašem  web pregledaču za vreme procesa ponovnog izgrađivaǌa (za automatsko preusmeravaǌe kada se ciklus završi). Ako ste prisiǉeni da prekinite proces ponovnog izgrađivaǌa, zabeležite posledǌu indentifikaciju poruke i unesite tu indetifikaciju+1 u "Startovaǌe na osnovu indetifikacije poruke" kada/ako želite da nastavite ("Prazan indeks" ne sme biti odabran).',
'Rebuild index'					=>	'Ponovno izgrađivaǌe sadržaja',
'Rebuilding search index'		=>	'Ponovno izgrađivaǌe indeksa za pretraživaǌe',
'Rebuilding index info'			=>	'Ponovno izgrađivaǌe sadržaja. Ovo je možda pravi trenutak da skuvate kafu :-)',
'Processing post'				=>	'Procesiraǌe poruke <strong>%s</strong> …',
'Click here'					=>	'Kliknite ovde',
'Javascript redirect failed'	=>	'JavaScript preusmeravaǌe neuspešno. %s da bi ste nastavili …',
'Posts must be integer message'	=>	'Broj poruka po ciklusu mora biti pozitivan ceo broj.',
'Days must be integer message'	=>	'Broj dana za smaǌivaǌe mora biti pozitivan ceo broj.',
'No old topics message'			=>	'Nema tema koje su stare %s dana. Molimo Vas smaǌite vrednost "Broj dana" i pokušajte ponovo.',
'Posts pruned redirect'			=>	'Poruke su smaǌene. Preusmeravam …',
'Prune head'					=>	'Smaǌi',
'Prune subhead'					=>	'Smaǌi stare poruke',
'Days old label'				=>	'Dana stare',
'Days old help'					=>	'Broj dana "stare" znači da će smaǌiti i teme. Npr. ako ste uneli 30, svaka tema koja nije sadržala poruku mlađu od 30 dana bi bila obrisana.',
'Prune sticky label'			=>	'Odreži lepljive teme',
'Prune sticky help'				=>	'Kada je ukǉučen, lepljive teme će takođe biti odrezane.',
'Prune from label'				=>	'Odreži sa foruma',
'All forums'					=>	'Svi forumi',
'Prune from help'				=>	'Forum na kojem želite da odrežete poruke.',
'Prune info'					=>	'Koristite ovu osobinu sa pažǌom. <strong>Odrezane poruke ne mogu nikad biti povraćene.</strong> Za najboǉe perfomanse, trebalo bi da postavite forum u %s za vreme smaǌivaǌa.',
'Confirm prune subhead'			=>	'Potvrdi odrezivanje poruka',
'Confirm prune info'			=>	'Jeste li sigurni da želite da odrežete sve teme starije od %s dana sa %s (%s tema).',
'Confirm prune warn'			=>	'UPOZOREǋE! Odrezivanje poruka ih briše trajno.',

);
