<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'			=>	'Ne postoji korisnik registrovan sa tim korisničkim imenom. Ako želite da dodate zabranu vezanu za spefično korisničko ime, samo ostavite polje za korisničko ime prazno.',
'No user ID message'		=>	'Ne postoji registrovani korisnik sa tom indentifikacijom.',
'User is admin message'		=>	'Korisnik %s je administrator i ne može biti zabraǌen. Ako želite da zabranite administratora, morate prvo sniziti ǌegove/ǌene privilegije.',
'User is mod message'		=>	'Korisnik %s je moderator i ne može biti zabraǌen. Ako želite da zabranite moderatora, morate prvo sniziti ǌegove/ǌene privilegije.',
'Must enter message'		=>	'Morate uneti ili korisničko ime ili IP adresu ili email adresu (najmaǌe).',
'Cannot ban guest message'	=>	'Korisnik gost ne može biti zabraǌen.',
'Invalid IP message'		=>	'Uneli ste pograšan IP/IP-opseg.',
'Invalid e-mail message'	=>	'email adresa (npr. korisnik@domain.com) ili deo domena email adrese (npr. domain.com) koji ste uneli je pogrešan.',
'Invalid date message'		=>	'Uneli ste pogrešan datum isteka.',
'Invalid date reasons'		=>	'Format bi trebalo biti YYYY-MM-DD i datum mora biti najmaǌe jedan dan u budućnosti.',
'Ban added redirect'		=>	'Zabrana dodata. Preusmeravam …' ,
'Ban edited redirect'		=>	'Zabrana izmeǌena. Preusmeravam …',
'Ban removed redirect'		=>	'Zabrana ukloǌena. Preusmeravam …',

'New ban head'				=>	'Nova zabrana',
'Add ban subhead'			=>	'Dodaj zabranu',
'Username label'			=>	'Korisničko ime',
'Username help'				=>	'Korisničko ime koje želite da zabranite (neosetǉivo na velika i mala slova).',
'Username advanced help'	=>	'Korisničko ime koje želite da zabranite (neosetǉivo na velika i mala slova). Sledeća strana će Vam dozvoliti da unesete prilagođen IP i email adresu. Ako želite da zabranite specifičan IP/IP-opseg ili specifični email samo ostavite prazno.',

'Ban search head'			=>	'Pretraži zabrane',
'Ban search subhead'		=>	'Unesite kriterijum za pretragu',
'Ban search info'			=>	'Pretraži zabrane u bazi podataka. Možete uneti jedan ili više termina za pretraživaǌe. ǅoker znaci u formi zvezdica (*) su prihvatǉivi. Da bi se pokazale sve zabrane ostavite poǉa prazna.',
'Date help'					=>	'(yyyy-mm-dd)',
'Message label'				=>	'Poruka',
'Expire after label'		=>	'Ističe posle',
'Expire before label'		=>	'Ističe pre',
'Order by label'			=>	'Poredak prema',
'Order by username'			=>	'Korisničkom imenu',
'Order by ip'				=>	'IP',
'Order by e-mail'			=>	'Email',
'Order by expire'			=>	'Datumu isticaǌa',
'Ascending'					=>	'Uzlazni',
'Descending'				=>	'Silazni',
'Submit search'				=>	'Potvrdi tražeǌe',

'E-mail label'				=>	'Email',
'E-mail help'				=>	'Email ili email domen koji želite da zabranite (npr. neko@negde.com ili negde.com). Pogledajte "Dozvoli zabraǌene adrese" u Dozvolama za više informacija.',
'IP label'					=>	'IP adresa/IP-opseg',
'IP help'					=>	'IP adresa ili IP-opseg koji želite da zabranite (npr. 150.11.110.1 ili 150.11.110). Odvojite adrese sa razmacima. Ako je neki IP već unet onda je posledǌi poznat IP za tog korisnika u bazi podataka.',
'IP help link'				=>	'Kliknite %s da vidite statički IP za ovog korisnika.',
'Ban advanced head'			=>	'Napredǌa podešavaǌa za zabrane',
'Ban advanced subhead'		=>	'Dodatak za zabrane sa IP adresom i email-om',
'Ban message label'			=>	'Poruka zabrane',
'Ban message help'			=>	'Poruka će biti prikazana koriniku koji je zabraǌen kada on/ona posete forum.',
'Message expiry subhead'	=>	'Poruka zabrane i isticaǌe',
'Ban IP range info'			=>	'Trebalo bi da budete jako oprezni prilikom zabraǌivaǌa IP-opsega zbog mogućnosti da se kod više korinika poklapa deo IP adrese.',
'Expire date label'			=>	'Datum isticaǌa',
'Expire date help'			=>	'Datum kada bi ova zabrana trebala biti automatski ukloǌena (format: yyyy-mm-dd). Ostaviti prazno za ručno uklaǌaǌe.',

'Results head'				=>	'Pretraži Rezultate',
'Results username head'		=>	'Korisničko ime',
'Results e-mail head'		=>	'Email',
'Results IP address head'	=>	'IP/IP-opsezi',
'Results expire head'		=>	'Ističe',
'Results message head'		=>	'Poruka',
'Results banned by head'	=>	'Zabraǌen od',
'Results actions head'		=>	'Akcije',
'No match'					=>	'Nema poklapaǌa',
'Unknown'					=>	'Nepoznato',

);
