<?php

// Language definitions used in install.php, localized by adaur

$lang_install = array(

'Choose install language'		=>	'Izaberite instalacioni skript jezik',
'Choose install language info'	=>	'Jezik korišćen za ovu instalacionu skriptu. Osnovni jezik korisćen za sam forum može se izabrati ispod.',
'Install language'				=>	'Instalacioni jezik',
'Change language'				=>	'Promeni jezik',
'Already installed'				=>	'Čini se da je FluxBB već instaliran. Trebalo bi da odete <a href="index.php">ovde</a>.',
'You are running error'			=>	'Koristite %1$s verziju %2$s. FluxBB %3$s zahteva najmaǌe %1$s %4$s da bi radio kako treba. Morate ažurirati Vašu %1$s  instalaciju pre nego što možete da nastavite.',
'My FluxBB Forum'				=>	'Moj FluxBB Forum',
'Description'					=>	'Nažalost niko Vam ne može reći šta je FluxBB - moraćete da vidite sami.',
'Username 1'					=>	'Korisnička imena moraju da budu najmaǌe 2 karaktera dužine.',
'Username 2'					=>	'Korisnička imena ne smeju da budu duža od 25 karaktera.',
'Username 3'					=>	'Korisničko ime gosta je rezervisano.',
'Username 4'					=>	'Korisničko ime ne može biti u formi IP adrese.',
'Username 5'					=>	'Korisničko ime ne može da sadži sve karaktere  \', " i [ ili ] odjednom.',
'Username 6'					=>	'Korisničko ime ne može da sadži tekst za oznake formatiraǌa (BBCode) koje forum koristi.',
'Short password'				=>	'Šifra mora biti najmaǌe 6 karaktera dugačka.',
'Passwords not match'			=>	'Šifre se ne poklapaju.',
'Wrong email'					=>	'Administratorska email adresa koju ste uneli nije važeća.',
'No board title'				=>	'Morate uneti naziv foruma.',
'Error default language'		=>	'Izabrani podrazumevani jezik izgleda da ne postoji.',
'Error default style'			=>	'Izabrani podrazumevani stil izgleda da ne postoji.',
'No DB extensions'				=>	'Ovo PHP okružeǌe nema podršku za baze podataka koje FluxBB podržava. PHP treba da ima podršku za MySQL, PostgreSQL ili SQLite kako bi se FluxBB instarao.',
'Administrator username'		=>	'Korisničko ime administratora',
'Administrator email'			=>	'Email administratora',
'Board title'					=>	'Naziv foruma',
'Base URL'						=>	'URL (bez pratećih kosih crta) od Vašeg FluxBB foruma. Ovo mora biti tačno.',
'Required field'				=>	'je zahtevano poǉe u ovoj formi.',
'FluxBB Installation'			=>	'Instaliacija FluxBB-a',
'Welcome'						=>	'Spremate se da instalirate FluxBB. Kako bi instalirali FluxBB, morate kompletirati formu ispod. Ako se susretnete sa bilo kakvim poteškoćama sa instalicijom, molim Vas pogledajte dokumentaciju.',
'Install'						=>	'Instaliraj FluxBB %s',
'Errors'						=>	'Sledeće greške moraju biti popravǉene:',
'Database setup'				=>	'Podešavaǌe baze podataka',
'Info 1'						=>	'Sve informacije koje su nam potrebne da kreiramo konekciju sa Vašom bazom podataka.',
'Select database'				=>	'Odaberite tip Vaše baze podataka',
'Info 2'						=>	'Odaberite bazu podataka. Podržavamo SQLite, MySQL i PostgreSQL.',
'Database type'					=>	'Tip baze podataka',
'Required'						=>	'(Zahtevano)',
'Database hostname'				=>	'Unesite ime servera gde je Vaša baza podataka',
'Info 3'						=>	'Trebalo bi da možete da dobijete ovaj info od Vašeg web hosta, ako <code>localhost</code> ne radi.',
'Database server hostname'		=>	'Ime servera baze podataka',
'Database enter name'			=>	'Unesite ime Vaše baze',
'Info 4'						=>	'Ime baze podataka na koju želite da instalirate FluxBB.',
'Database name'					=>	'Ime baze podataka',
'Database enter informations'	=>	'Unesite korisničko ime i šifru Vaše baze podataka',
'Database username'				=>	'Korisničko ime za bazu podataka',
'Info 5'						=>	'Vaše MySQL korisničko ime i šifra (ignorisu se za SQLite).',
'Database password'				=>	'Šifra za bazu podataka',
'Database enter prefix'			=>	'Unesite prefiks tabele za bazu podataka',
'Info 6'						=>	'Ako želite da pokrenete višestruke FluxBB instalacije na jednoj bazi, promenite ovo.',
'Table prefix'					=>	'Prefiks tabele',
'Administration setup'			=>	'Podešavaǌe za administraciju',
'Info 7'						=>	'Kreiraj prvi nalog na Vašem forumu.',
'Info 8'						=>	'Vaše korisničko ime more biti između 2 i 25 karaktera dužine. Vaša šifra mora biti najmaǌe 6 karaktera dužine. Remember that passwords are case-sensitive.',
'Password'						=>	'Šifra',
'Confirm password'				=>	'Potvrdi šifru',
'Board setup'					=>	'Podešavaǌe foruma',
'Info 11'						=>	'Podešavaǌa za Vaš forum. Možete ga promeniti kasnije.',
'General information'			=>	'Unesite ime i opis Vašeg foruma.',
'Board description'				=>	'Opis foruma (podržava HTML)',
'Appearance'					=>	'Izgled',
'Info 15'						=>	'Napravite Vaš forum Vašim. Izaberite jezik i stil za Vaš forum.',
'Default language'				=>	'Podrazumevani jezik',
'Default style'					=>	'Podrazumevani stil',
'Start install'					=>	'Pokreni instalaciju',
'DB type not valid'				=>	'\'%s\' nije validan tip baze podataka',
'Table prefix error'			=>	'Prefik tabele \'%s\' sadrži ilegalne karaktere ili je previše dugačaka. Prefiks može sadržati slova a do š, bilo koji broj i doǌu crtu. Ali oni ipak ne smeju početi brojem. Maksimalna dužina je 40 karaktera. Molimo Vas odaberite drugačiji prefiks',
'Prefix reserved'				=>	'Prefiks tabele \'sqlite_\' je rezervisan za korišćeǌe od SQLite. Molim Vas odaberite drugačiji prefiks',
'Existing table error'			=>	'Tabela zvana \'%susers\' već postoji u bazi podataka \'%s\'. Ovo može značiti da je FluxBB već instaliran ili da je drugi softver već instaliran i da je zauzeo imena jedne ili više tabela koje FluxBB zahteva. Ako želite da instalirate više kopija FluxBB-a na istoj bazi podataka, morate izabrati drugačiji prefik za tabelu',
'InnoDB off'					=>	'InnoDB čini se da nije omogućen. Molim Vas odaberite sloj za bazu podataka koji nema podršku za InnoDB, ili omogućite InnoDB na Vašem MySQL serveru',
'Administrators'				=>	'Administratori',
'Administrator'					=>	'Administrator',
'Moderators'					=>	'Moderatori',
'Moderator'						=>	'Moderator',
'Guests'						=>	'Gosti',
'Guest'							=>	'Gost',
'Members'						=>	'Članovi',
'Announcement'					=>	'Unesite Vašu prijavu ovde.',
'Rules'							=>	'Unesite Vaša pravila ovde',
'Maintenance message'			=>	'Forumi privremeno ne rade zbog održavaǌa. Molim Vas probajte ponovo za nekoliko minuta.',
'Test post'						=>	'Testiraj sadžaj',
'Message'						=>	'Ako vidite ovo (pretpostavǉam da je tako), instalacija FluxBB radi! Sada se možete logovati i otići na kontrolni panel za administratora kako bi konfigurisali Vaš forum.',
'Test category'					=>	'Testiraj kategoriju',
'Test forum'					=>	'Testiraj forum',
'This is just a test forum'		=>	'Ovo je samo forum za testiraǌe',
'Alert cache'					=>	'<strong>Trenutno se ne može pisati u keš direktorijumu!</strong> Kako bi FluxBB odgovarajuće funkcionisao, PHP mora imati mogućnost da piše u direktorijumu <em>%s</em>. Koristite chmod kako biste postavili odgovarajuće permisije na direktorijumu. Ako ste u nedoumici, podesite chmod na 0777.',
'Alert avatar'					=>	'<strong>Trenutno se ne može pisati u avatar direktorijumu!</strong> Ako želite da korisnici budu u mogućnosti da otpreme ǌihove avatar slike morate omogućiti da PHP može pisati u direktorijumu <em>%s</em>. Kasnije možete odabrati da se avatar slike čuvaju u drugom direktorijumu (pogledati Admin/Opcije). Koristite chmod kako biste postavili odgovarajuće permisije na direktorijumu. Ako ste u nedoumici, podesite chmod na 0777.',
'Alert upload'					=>	'<strong>Otpremaǌe fajlova je onemogućeno na ovom serveru!</strong> Ako želite da korisnici budu u mogućnosti da otpreme ǌihove avatar slike morate omogućiti file_uploads konfiguraciono podešavaǌe u PHP. Jednom kada otpremaǌe fajlova bude omogućeno, otpremaǌe avatara može biti podešeno u Administracija/Opcije/Karakteristike.',
'FluxBB has been installed'		=>	'FluxBB je instaliran. Kako bi finalizirali instalaciju molim Vas pratite instrukcije ispod.',
'Final instructions'			=>	'Finalne instrukcije',
'Info 17'						=>	'Kako bi finalizirali instalaciju, potrebno je da kliknete na dugme ispod i preuzemete fajl config.php. Zatim je potrebno otpremiti ovaj fajl u bazni direktorijum Vaše FluxBB instalacije.',
'Info 18'						=>	'Kada otpremite config.php fajl, FluxBB će biti u potpunosti instaliran! U tom trenutku, možete <a href="index.php">otići na forum indeks</a>.',
'Download config.php file'		=>	'Preuzmite config.php fajl',
'FluxBB fully installed'		=>	'FluxBB je u potpunosti instaliran! Sada možete <a href="index.php">otići na forum indeks</a>.',

);
