<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Unesite validnu email adresu',
'Email legend 2'			=>	'Unesite i potvrdite validnu email adresu',
'Localisation legend'		=>	'Podesite opcije lokalizacije',
'Time zone'					=>	'Vremenska zona',
'Time zone info'			=>	'Da bi forum prikazao vremena ispravno morate odabrati lokalnu vremensku zonu. Ako Letǌe Računaǌe Vremena utiče na Vas, možete pogledati opciju koja pomera vreme za 1 sat.',
'DST'						=>	'Letǌe Računaǌe Vremena je na snazi (pomeri vreme unapred za jedan sat).',
'Time format'				=>	'Format vremena',
'Date format'				=>	'Format datuma',
'Default'					=>	'Podrazumevano',
'Language'					=>	'Jezik',
'Email setting info'		=>	'Odaberite da li želite da Vaš email adresa bude vidǉiva drugim korisnicima ili ne i ako zelite drugi korisnici da mogu da Vam pošaǉu email putem foruma (forumski email) ili ne.',
'Email setting 1'			=>	'Prikaži Vašu email adresu drugim korisnicima.',
'Email setting 2'			=>	'Sakrij Vašu email adresu ali omogući forumski email.',
'Email setting 3'			=>	'Sakrij Vašu email adresu i onemogući forumski email.',
'Privacy options legend'	=>	'Podesite opcije privatnosti',
'Confirm pass'				=>	'Potvrdite šifru',

'Username too short'		=>	'Korisničko ime mora biti dugačko najmanje 2 karaktera. Molim Vas izaberite drugo (duže) korisničko ime.',
'Username too long'			=>	'Korisničko ime ne sme biti duže od 25 karaktera. Molim Vas izaberite drugo (kraće) korisničko ime.',
'Username guest'			=>	'Korisničko ime gosta je rezervisano. Molim Vas izaberite drugo korisničko ime.',
'Username IP'				=>	'Korisničko ime ne može biti u obliku IP adrese. Molim Vas izaberite drugo korisničko ime.',
'Username reserved chars'	=>	'Korisničko ime ne može sadržati karaktere \', " i [ ili ] od jednom. Molim Vas izaberite drugo korisničko ime.',
'Username BBCode'			=>	'Korisničko ime ne može sadržati bilo koju oznaku za formatiraǌe teksta (BBCode) koju koristi forum. Molim Vas izaberite drugo korisničko ime.',
'Banned username'			=>	'Uneto korisničko ime je zabraǌeno na ovom forumu. Molim Vas izaberite drugo korisničko ime.',
'Pass too short'			=>	'Šifra mora biti dugačka najmaǌe 6 karaktera. Molim Vas izaberite drugu (dužu) šifru.',
'Pass not match'			=>	'Šifre se ne slažu.',
'Banned email'				=>	'email adresa koju ste uneli je zabraǌena na ovom forumu. Molim Vas izaberite drugu email adresu.',
'Dupe email'				=>	'Neko se već registrovao sa tom email adresom. Molim Vas izaberite drugu email adresu.',
'Sig too long'				=>	'Potpis ne može biti duži od %1$s karaktera. Molim Vas skratite Vaš potpis za %2$s karaktera.',
'Sig too many lines'		=>	'Potpis ne može imati više od %s linija.',
'Bad ICQ'					=>	'Uneli ste pogrešan ICQ UIN. Molim Vas vratite se nazad i popravite ga.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Moscow, Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Yekaterinburg',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Krasnoyarsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita, Irkutsk',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Vladivostok',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Magadan',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands, Kamchatka',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
