<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'Meni za profil',
'Section essentials'			=>	'Glavne stvari',
'Section personal'				=>	'Lični',
'Section messaging'				=>	'Poruke',
'Section personality'			=>	'Ličnost',
'Section display'				=>	'Prikaz',
'Section privacy'				=>	'Privatnost',
'Section admin'					=>	'Administracija',

// Miscellaneous
'Username and pass legend'		=>	'Unesite Vaše korisničko ime i šifru',
'Personal details legend'		=>	'Unesite Vaše lične detaǉe',
'Contact details legend'		=>	'Unesite Vaše detaǉe za poruke',
'User activity'					=>	'Aktivnost korisnika',
'Paginate info'					=>	'Unesite broj tema ili poruka koje želite da vidite na svakoj strani.',

// Password stuff
'Pass key bad'					=>	'Navedeni aktivacioni kǉuč je pogrešan ili je istekao. Molim Vas žatražite novi. Ako to ne uspe, kontaktirajte administratora foruma na',
'Pass updated'					=>	'Vaša šifra je ažurirana. Sada se možete prijaviti sa novom šifrom.',
'Pass updated redirect'			=>	'Šifra je ažurirana. Preusmeravam …',
'Wrong pass'					=>	'Pogrešna stara šifra.',
'Change pass'					=>	'Promeni šifru',
'Change pass legend'			=>	'Unesite i potvrdite Vašu novu šifru',
'Old pass'						=>	'Stara šifra',
'New pass'						=>	'Nova šifra',
'Confirm new pass'				=>	'Potvrdite novu šifru',
'Pass info'						=>	'Šifre moraju biti dužine najmanje 6 karaktera. Šifre su osetǉive na velika i mala slova.',

// Email stuff
'Email key bad'					=>	'Navedeni aktivacioni kǉuč je pogrešan ili je istekao. Molim Vas žatražite novi. Ako to ne uspe, kontaktirajte administratora foruma na',
'Email updated'					=>	'Vaša email adresa je ažurirana.',
'Activate email sent'			=>	'email sa instrukcijama kako aktivirati novu email adresu je poslat na naznačebz adresu. Ako ne stigne možete kontaktirati administratora foruma na',
'Email legend'					=>	'Unesite novu email adresu',
'Email instructions'			=>	'email će biti poslat na Vašu novu adresu sa aktivacionim linkom. Morate kliknuti na link u primǉenom emailu kako biste aktivirali novu adresu.',
'Change email'					=>	'Promeni email adresu',
'New email'						=>	'Nov email',

// Avatar upload stuff
'Avatars disabled'				=>	'Administrator je onemogućio podršku za avatar.',
'Too large ini'					=>	'Odabrani fajl je previše velik za otpremaǌe. Server nije dozvolio otpremaǌe fajla.',
'Partial upload'				=>	'Odabrani fajl je samo delimično otpremǉen. Molim Vas probajte ponovo.',
'No tmp directory'				=>	'PHP nije bio u mogućnosti da sačuva otpremǉen fajl na privremenu lokaciju.',
'No file'						=>	'Niste odabrali fajl za otpremaǌe.',
'Bad type'						=>	'Fajl koji ste pokušali da otpremite nije dozvoǉenog tipa. Dozvoǉeni tipovi su gif, jpeg i png.',
'Too wide or high'				=>	'Fajl koji ste pokušali da otpremite je širi i/ili viši nego sto je maksimalno dozvoǉeno',
'Too large'						=>	'Fajl koji ste pokušali da otpremite je veči nego sto je maksimalno dozvoǉeno',
'pixels'						=>	'pikseli',
'bytes'							=>	'bajtovi',
'Move failed'					=>	'Server nije bio u mogućnosti da sačuva otpremǉen fajl. Molim Vas kontaktirajte forum administratora na',
'Unknown failure'				=>	'Došlo je do nepoznate greške. Molim Vas probajte ponovo.',
'Avatar upload redirect'		=>	'Avatar je otpremǉen. Preusmeravam …',
'Avatar deleted redirect'		=>	'Avatar je obrisan. Preusmeravam …',
'Avatar desc'					=>	'Avatar je mala slika koja će biti prikazana sa Vašim imenom u Vašim porukama. Ne sme biti veća od',
'Upload avatar'					=>	'Otpremi avatar',
'Upload avatar legend'			=>	'Unesite avatar fajl za otpremaǌe',
'Delete avatar'					=>	'Obriši avatar', // only for admins
'File'							=>	'Fajl',
'Upload'						=>	'Otpremi', // submit button

// Form validation stuff
'Forbidden title'				=>	'Naslov koji ste uneli sadži zabraǌenu reč. Morate izabrati drugačiji naslov.',
'Profile redirect'				=>	'Profil je ažuriran. Preusmeravam …',

// Profile display stuff
'Users profile'					=>	'%s profil',
'Username info'					=>	'Korisničko ime: %s',
'Email info'					=>	'Email: %s',
'Posts info'					=>	'Poruke: %s',
'Registered info'				=>	'Registrovan: %s',
'Last post info'				=>	'Posledǌa poruka: %s',
'Last visit info'				=>	'Posledǌa poseta: %s',
'Show posts'					=>	'Prikaži sve poruke',
'Show topics'					=>	'Prikaži sve teme',
'Show subscriptions'			=>	'Prikaži sve prijave',
'Realname'						=>	'Stvarno ime',
'Location'						=>	'Lokacija',
'Website'						=>	'Website',
'Invalid website URL'			=>	'URL za website koji ste uneli je neispravan.',
'Website not allowed'			=>	'Još uvek Vam nije dozvoǉeno da dodate website na Vaš profil.',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'Microsoft Account',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'Avatar',
'Signature'						=>	'Potpis',
'Sig max size'					=>	'Maksimalna dužina: %s karaktera / Maksimalan broj linija: %s',
'Avatar legend'					=>	'Odaberite Vašem avataru opcije za prikazavaǌe',
'Avatar info'					=>	'Avatar je mala slika koja će biti prikazana u svim Vašim porukama. Možete otpremiti avatar sa klikom na link ispod.',
'Change avatar'					=>	'Promeni avatar',
'Signature legend'				=>	'Unesite Vaš potpis',
'Signature info'				=>	'Potpis je mali deo teksta koji je dodat Vašim porukama. U ǌemu, možete napisati šta god želite. Možda želite da unesete Vaše omiǉene citate ili Vaš zodijački znak. Sve je na Vama! U Vašem potpisu možete koristiti oznaku za BBCode ako je dozvoǉeno na ovom forumu. Možete videti izlistane karakteristike koje su dozvoǉene/omogućene svaki put kada izmenite Vaš potpis.',
'Sig preview'					=>	'Prikaz trenutnog potpisa:',
'No sig'						=>	'Nema sačuvanog potpisa trenutno u profilu.',
'Signature quote/code/list/h'	=>	'Citat, kod, lista, oznake za BBCode nisu dozvoǉeni u potpisu.',
'Topics per page'				=>	'Teme',
'Posts per page'				=>	'Poruke',
'Leave blank'					=>	'Ostavi prazno za korišćeǌe podrazumevanog podešavanja foruma.',
'Subscription legend'			=>	'Podesite Vaše opcije za prijavu',
'Notify full'					=>	'Ukǉuči običan tekst novih poruka u email obavešteǌa na teme gde ste upisani.',
'Auto notify full'				=>	'Automatski se upišite na svaku temu gde ste pisali.',
'Show smilies'					=>	'Prikaži smeškove kao grafičke ikonice.',
'Show images'					=>	'Prikaži slike u porukama.',
'Show images sigs'				=>	'Prikaži slike u potpisu korisnika.',
'Show avatars'					=>	'Prikaži avatar korisnika u porukama.',
'Show sigs'						=>	'Prikaži potpis korisnika.',
'Style legend'					=>	'Odaberite Vaš prioritetan stil',
'Styles'						=>	'Stilovi',
'Admin note'					=>	'Admin beleška',
'Pagination legend'				=>	'Podesiti Vaše opcije za obeležavaǌe strana',
'Post display legend'			=>	'Podesiti Vaše opcije za pregled poruka',
'Post display info'				=>	'Ako imate sporu vezu, iskǉučiti ove opcije, posebno prikaz slika u porukama i potpisima, ovo će prouzrokovati brže učitavaǌe stranica.',
'Instructions'					=>	'Kada ažurirate Vaš profil, bićete preusmereni nazad na ovu stranu.',

// Administration stuff
'Group membership legend'		=>	'Izaberite korisničku grupu',
'Save'							=>	'Sačuvaj',
'Set mods legend'				=>	'Podesi pristup moderatoru',
'Moderator in info'				=>	'Izaberi koji forumi će biti dozvoǉeni ovom korisniku da moderira. Obavešteǌe: Ovo se primeǌuje samo za moderatore. Administratori uvek imaju sve dozvole na svim forumima.',
'Update forums'					=>	'Ažuriraj forume',
'Delete ban legend'				=>	'Obriši (samo za administratore) ili zabrani korisnika',
'Delete user'					=>	'Obriši korisnika',
'Ban user'						=>	'Zabrani korisnika',
'Confirm delete legend'			=>	'Važno: pročitajte pre brisaǌa korisnika',
'Confirm delete user'			=>	'Potvrdi brisaǌe korisnika',
'Confirmation info'				=>	'Molim potvrdite da želite da obrišete korisnika', // the username will be appended to this string
'Delete warning'				=>	'Upozoreǌe! Obrisani korisnici i/ili poruke se ne mogu povratiti. Ako izaberete da ne obrišete poruke ovog korisnika, kasnije poruke mogu biti obrisane samo ručno.',
'Delete posts'					=>	'Obriši sve poruke i teme od ovog korisnika.',
'Delete'						=>	'Obriši', // submit button (confirm user delete)
'User delete redirect'			=>	'Korisnik je obrisan. Preusmeravam …',
'User promote redirect'			=>	'Korisnik je unapređen. Preusmeravam...',
'Group membership redirect'		=>	'Članstvo grupe je sačuvano. Preusmeravam …',
'Update forums redirect'		=>	'Prava moderatora foruma su ažurirana. Preusmeravam …',
'Ban redirect'					=>	'Preusmeravam …',
'No delete admin message'		=>	'Administratori se ne mogu obrisati. Kako bi obrisali ovog korisinika, prvo morate da pomerite ǌega/ǌu u drugu grupu.',

);
