<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'Pretraživaǌe korisnika',
'No search permission'				=>	'Nemate dozvolu za korišćeǌe pretraživaǌa.',
'Search flood'						=>	'Najmaǌe %s sekundi treba da prođe između pretraživǌa. Molim Vas sačekajte %s sekundi i probajte ponovo.',
'Search'							=>	'Pretraživaǌe',
'Search criteria legend'			=>	'Unesite kriterijum za pretraživaǌe',
'Search info'						=>	'Da biste pretraživali po kǉučnoj reči, unesite termin ili termine za pretraživaǌe. Odvojite termine praznim mestom. Koristite AND, OR i NOT da bi ste dobili detaǉniju pretragu. Da bi ste pretraživali po autoru unesite korisničko ime autora čije poruke želite da pretražujete.',
'Keyword search'					=>	'Pretraživaǌe po kǉučnoj reči',
'Author search'						=>	'Pretraživaǌe po autoru',
'Search in legend'					=>	'Izaberite gde da pretražujete',
'Search in info'					=>	'Izaberite na kom forumu želite da pretražujete i ako želite da pretražujete naslove tema, samo poruke ili i jedno i drugo.',
'Search multiple forums info'		=>	'Ako ni jedan forum nije odabran, svi forumi će biti pretraženi.',
'Forum search'						=>	'Forum',
'Search in'							=>	'Pretraži u',
'Message and subject'				=>	'Tekst poruke i naslov teme',
'Message only'						=>	'Samo tekst poruke',
'Topic only'						=>	'Samo naslov teme',
'Sort by'							=>	'Sortiraj po',
'Sort order'						=>	'Redosled sortiraǌa',
'Search results legend'				=>	'Izaberite kako želite da Vam se prikažu rezultati pretraživaǌa',
'Search results info'				=>	'Možete izabrati kako želite da sortirate i kako da Vam se prikažu rezultati.',
'Sort by post time'					=>	'Vremenu poruke',
'Sort by author'					=>	'Autoru',
'Sort by subject'					=>	'Naslovu',
'Sort by forum'						=>	'Forumu',
'Ascending'							=>	'Rastući',
'Descending'						=>	'Opadajući',
'Show as'							=>	'Prikaži rezultate kao',
'Show as topics'					=>	'Teme',
'Show as posts'						=>	'Poruke',

// Results
'Search'							=>	'Pretraži',
'Search results'					=>	'Pretraži rezultate',
'Quick search show_new'				=>	'Novo',
'Quick search show_recent'			=>	'Aktivno',
'Quick search show_unanswered'		=>	'Nije odgovoreno',
'Quick search show_replies'			=>	'Objavǉeno',
'Quick search show_user_topics'		=>	'Teme od %s',
'Quick search show_user_posts'		=>	'Poruke od %s',
'Quick search show_subscriptions'	=>	'Prijavǉeno od %s',
'By keywords show as topics'		=>	'Teme koje sadrže poruke \'%s\'',
'By keywords show as posts'			=>	'Sadrži poruke \'%s\'',
'By user show as topics'			=>	'Teme koje sadrže poruke od %s',
'By user show as posts'				=>	'Poruke od %s',
'By both show as topics'			=>	'Teme koje sadrže poruke \'%s\', od %s',
'By both show as posts'				=>	'Sadrži poruke \'%s\', od %s',
'No terms'							=>	'Morate uneti bar jednu kǉučnu reč i/ili autora da bi pretraživali.',
'No hits'							=>	'Nema rezultata Vaše pretrage.',
'No user posts'						=>	'Nema poruka od ovog korisnika na ovom forumu.',
'No user topics'					=>	'Nema tema od ovog korisnika na ovom forumu.',
'No subscriptions'					=>	'Ovaj korisnik trenutno nije prijavǉen ni na jednu temu.',
'No new posts'						=>	'Nema tema sa novim porukama od Vaše posledǌe posete.',
'No recent posts'					=>	'Nema novih poruka zadǌih 24 sata.',
'No unanswered'						=>	'Ne postoje poruke na koje nije odgovoreno na ovom forumu.',
'Go to post'						=>	'Idi na poruku',
'Go to topic'						=>	'Idi na temu'

);
