<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'			=>	'לא נמצא משתמש רשום עם שם משתמש זה. אם ברצונך להוסיף חסימה שלא קשורה לשם משתמש ספציפי, השאר שדה שם משתמש ריק.',
'No user ID message'			=>	'לא נמצא משתמש רשום עם ID זה.',
'User is admin message'		=>	'המשתמש %s הוא מנהל ראשי ולא ניתן לחסימה. בכדי לחסום מנהל ראשי קודם צריך להעבירו לקבוצת משתמשים נמוכה יותר.',
'User is mod message'    =>  'המשתמש %s הוא מנהל ולא ניתן לחסימה. בכדי לחסום מנהל קודם צריך להעבירו לקבוצת משתמשים נמוכה יותר.',
'Must enter message'		=>	'עליך להזין שם משתמש, כתובת אייפי או כתובת דואר אלקטרוני (לפחות אחת מהאפשרויות).',
'Cannot ban guest message'	=>	'שם משתמש אורח לא ניתן לחסימה.',
'Invalid IP message'		=>	'הזנת כתובת אייפי לא חוקית',
'Invalid e-mail message'	=>	'כתובת הדוא"ל (למשל user@domain.com) או תחום חלקי של כתובת דוא"ל (למשל domain.com) שהזנת אינה חוקית.',
'Invalid date message'		=>	'הזנת תאריך תפוגה לא חוקי.',
'Invalid date reasons'		=>	'התאריך חייב להיות בפורמט YYYY-MM-DD ויום אחד בעתיד מהיום לפחות.',
'Ban added redirect'		=>	'החסימה נוספה. מעביר &hellip;',
'Ban edited redirect'		=>	'החסימה נערכה. מעביר &hellip;',
'Ban removed redirect'		=>	'החסימה הוסרה. מעביר &hellip;',

'New ban head'				=>	'חסימה חדשה',
'Add ban subhead'			=>	'הוסף חסימה',
'Username label'			=>	'שם משתמש',
'Username help'				=>	'שם משתמש לחסימה (לא רגיש לאותיות גדולות וקטנות)',
'Username advanced help'	=>	'שם המשתמש לחסימה (לא רגיש לאותיות גדולות וקטנות). העמוד הבא יאפשר לך להזין כתובת אייפי ודוא"ל. אם ברצונך לחסום רק כתובת אייפי/טווחי אייפי או דוא"ל השאר שדה זה ריק.',

'Ban search head'			=>	'חיפוש חסימות',
'Ban search subhead'		=>	'הזן קריטריון חיפוש',
'Ban search info'			=>	'חיפוש חסימות במסד נתונים. באפשרותך להזין אחת או יותר מילות חיפוש. לחיפוש מורחב לפי מילה חלקית השתמש בתו כוכבית (*). להצגת כל החסימות נא להשאיר את כל השדות ריקים.',
'Date help'					=>	'(yyyy-mm-dd)',
'Message label'			=>	'הודעה',
'Expire after label'	=>	'פג אחרי',
'Expire before label'	=>	'פג לפני',
'Order by label'			=>	'סדר לפי',
'Order by username'			=>	'שם משתמש',
'Order by ip'			        =>	'כתובת אייפי',
'Order by e-mail'			=>	'דוא"ל',
'Order by expire'			=>	'תאריך תפוגה',
'Ascending'				=>	'סדר עולה',
'Descending'				=>	'סדר יורד',
'Submit search'				=>	'בצע חיפוש',

'E-mail label'				=>	'דוא"ל',
'E-mail help'				=>	'הדוא"ל או תחום דוא"ל שברצונך לחסום (למשל someone@somewhere.com או somewhere.com). ראה "אפשר כתובות דוא"ל חסומות" ב הרשאות למידע נוסף.',
'IP label'					=>	'כתובת אייפי/טווחי כתובות אייפי',
'IP help'					=>	'כתובת אייפי או טווחי אייפי שברצונך לחסום (למשל 150.11.110.1 או 150.11.110). הפרד כתובות עם רווחים. אם כתובת אייפי כבר רשומה זוהי כתובת אייפי הידועה האחרונה של משתמש זה במסד הנתונים. ',
'IP help link'				=>	'לחץ %s בכדי לראות סטטיסטיקת אייפי עבור משתמש זה.',
'Ban advanced head'			=>	'הגדרות חסימה מתקדמות',
'Ban advanced subhead'		=>	'השלמת חסימה עם כתובת אייפי ודוא"ל',
'Ban message label'			=>	'הודעת חסימה',
'Ban message help'			=>	'ההודעה שתוצג למשתמש החסום בעת ביקורו בפורום',
'Message expiry subhead'	=>	'הודעת חסימה ותפוגתה',
'Ban IP range info'			=>	'עלייך להיות זהיר מאוד בעת חסימת טווח כתובות אייפי, בשל האפשרות של חסימת משתמשים מרובה התואמים חלקית לכתובת האייפי.',
'Expire date label'			=>	'תאריך תפוגה',
'Expire date help'			=>	'תאריך שבו החסימה תוסר אוטומטית. (פורמט: yyyy-mm-dd). השאר ריק בכדי להסיר ידנית.',

'Results head'			=>	'תוצאות חיפוש',
'Results username head'		=>	'שם משתמש',
'Results e-mail head'		=>	'דוא"ל',
'Results IP address head'	=>	'כתובת אייפי/טווחי אייפי',
'Results expire head'	        =>	'פג תוקף',
'Results message head'	        =>	'הודעה',
'Results banned by head'        =>	'נחסם ע"י',
'Results actions head'		=>	'פעולות',
'No match'			=>	'אין התאמות',
'Unknown'			=>	'לא ידוע',

);
