<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'לא ניתך לבצע בדיקה לשדרוג גרסה כי \'allow_url_fopen\' מושבת על מערכת זו.',
'Upgrade check failed message'		=>	'בדיקה לשדרוג גרסה נכשלה מסיבות לא ידועות.',
'Running latest version message'	=>	'הינך מריץ את הגרסה האחרונה של FluxBB.',
'New version available message'		=>	'יצאה גרסה חדשה של FluxBB. ביכולתך להוריד אותה בכתובת %s.',
'PHPinfo disabled message'			=>	'פונקציית שפת PHP - phpinfo() מכובת על שרת זה.',
'Not available'						=>	'לא זמין',
'Forum admin head'					=>	'לוח בקרה ראשי',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'ברוכים הבאים ללוח בקרה ראשי של מערכת FluxBB. כאן תוכל לשלוט בהגדרות הראשיות של המערכת. בין האפשרויות:',
'Welcome 1'							=>	'ארגון קטגוריות ופורומים.',
'Welcome 2'							=>	'הגדרת אפשרויות פורום כלליות.',
'Welcome 3'							=>	'ניהול הרשאות למשתמשים ואורחים.',
'Welcome 4'							=>	'הצגת סטטיסטיקות לאייפי של משתמשים.',
'Welcome 5'							=>	'חסימת משתמשים.',
'Welcome 6'							=>	'צנזור מילים.',
'Welcome 7'							=>	'הגדרת דרגות משתמשים.',
'Welcome 8'							=>	'ניקוי פורום מהודעות ישנות.',
'Welcome 9'							=>	'ניהול דיווחים על הודעות',
'Statistics head'					=>	'סטטיסטיקות',
'FluxBB version label'				=>	'גרסת FluxBB',
'Check for upgrade'					=>	'בדיקה לשדרוג גרסה',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'עומס שרת',
'Server load data'					=>	'%s - %s משתמש(ים) מחובר(ים)',
'Environment label'					=>	'סביבת עבודה',
'Environment data OS'				=>	'מערכת הפעלה: %s',
'Show info'							=>	'הצגת מידע',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'מאיץ: %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'מסד הנתונים',
'Database data rows'				=>	'שורות: %s',
'Database data size'				=>	'גודל: %s',

);
