<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'				=>	'תפריט הפרופיל',
'Section essentials'				=>	'כללי',
'Section personal'				=>	'פרטים אישיים',
'Section messaging'				=>	'פרטי התקשרות',
'Section personality'				=>	'חתימה ואווטר',
'Section display'				=>	'תצוגה',
'Section privacy'				=>	'פרטיות',
'Section admin'				=>	'הנהלה ראשית',

// Miscellaneous
'Username and pass legend'			=>	'הזן את שם המשתמש והסיסמה שלך',
'Personal details legend'				=>	'הזן את הפרטים האישיים שלך',
'Contact details legend'				=>	'הזן את פרטי ההתקשרות שלך',
'User activity'				=>	'פעילות המשתמש',
'Paginate info'				=>	'הזן את מספר הנושאים וההודעות שברצונך לראות בכל עמוד.',

// Password stuff
'Pass key bad'				=>	'קישור הפעלת הסיסמה שצוין שגוי או פג תוקפו. אנא בקש סיסמה חדשה. אם גם פעולה זו נכשלת פנה אל מנהל הפורום בכתובת',
'Pass updated'				=>	'הסיסמה שלך עודכנה. כעת תוכל להתחבר עם הסיסמה החדשה שלך.',
'Pass updated redirect'				=>	'הסיסמה שונתה. מעביר &hellip;',
'Wrong pass'				=>	'סיסמה ישנה שגוייה.',
'Change pass'				=>	'שינוי סיסמה',
'Change pass legend'				=>	'הזן ואשר את הסיסמה החדשה',
'Old pass'					=>	'סיסמה ישנה',
'New pass'					=>	'סיסמה חדשה',
'Confirm new pass'				=>	'אישור סיסמה חדשה',
'Pass info'					=>	'הסיסמה חייבת להיות לפחות בת 4 תווים. סיסמאות רגישות להבדל בין אותיות גדולות וקטנות.',

// Email stuff
'Email key bad'			=>	'קישור הפעלת כתובת דוא"ל שצוין שגוי או פג תוקפו. אנא בקש שינוי כתובת דוא"ל מחדש. אם גם זה נכשל, פנה אל מנהל הפורומים בכתובת',
'Email updated'			=>	'כתובת הדוא"ל שלך עודכנה.',
'Activate email sent'			=>	'הודעת דוא"ל נשלחה לכתובת שציינת עם הוראות כיצד להפעיל את כתובת הדוא"ל החדשה. אם המכתב לא מגיע תוכל ליצור קשר עם מנהל הפורומים בכתובת',
'Email legend'			=>	'הזן את כתובת הדוא"ל החדשה שלך',
'Email instructions'			=>	'מכתב יישלח לכתובת החדשה שלך עם קישור ההפעלה. עליך ללחוץ על הקישור בתוך המכתב שתקבל על מנת להפעיל את הכתובת החדשה.',
'Change email'			=>	'שינוי כתובת דוא"ל',
'New email'				=>	'כתובת דוא"ל חדשה',

// Avatar upload stuff
'Avatars disabled'			=>	'מנהל הפורומים ביטל תמיכה באווטרים.',
'Too large ini'			=>	'הקובץ הנבחר היה גדול מדי כדי להעלותו. השרת לא אפשר להעלות.',
'Partial upload'			=>	'הקובץ הנבחר הועלה באופן חלקי בלבד. אנא נסה שנית.',
'No tmp directory'			=>	'PHP לא הצליח לשמור את הקובץ הטעון למיקום זמני.',
'No file'				=>	'לא בחרת קובץ להעלאה.',
'Bad type'				=>	'הקובץ שניסית להעלות הוא לא מסוג מורשה. סוגי קבצים מותרים הם gif, jpeg ו-png.',
'Too wide or high'			=>	'הקובץ שניסית להעלות הוא רחב ו/או גבוה מהמקסימום מותר',
'Too large'				=>	'הקובץ שניסית להעלות גדול יותר מהמרבי המותר',
'pixels'				=>	'פיקסלים',
'bytes'				=>	'בייטים',
'Move failed'				=>	'לשרת לא היתה אפשרות לשמור את הקובץ הטעון. אנא צור קשר עם מנהל הפורומים בכתובת',
'Unknown failure'			=>	'אירעה שגיאה לא ידועה. אנא נסה שנית.',
'Avatar upload redirect'			=>	'אווטר נטען. מעביר &hellip;',
'Avatar deleted redirect'			=>	'אווטר נמחק. מעביר &hellip;',
'Avatar desc'			=>	'אווטר זוהי תמונה קטנה שתוצג מתחת לשם המשתמש שלך בהודעות. גודלה חייב להיות לא יותר מ',
'Upload avatar'			=>	'העלאת אווטר',
'Upload avatar legend'			=>	'בחר קובץ אווטר להעלאה',
'Delete avatar'			=>	'מחק אווטר',	// only for admins
'File'				=>	'קובץ',
'Upload'				=>	'לחץ כאן להעלאה',	// submit button

// Form validation stuff
'Forbidden title'				=>	'הכותרת שהזנת מכילה מילה אסורה. אנא בחר כותרת אחרת.',
'Profile redirect'				=>	'הפרופיל עודכן. מעביר &hellip;',

// Profile display stuff
'Users profile'					=>	'פרופיל של %s',
'Username info'					=>	'שם משתמש: %s',
'Email info'					=>	'דוא"ל: %s',
'Posts info'					=>	'הודעות: %s',
'Registered info'				=>	'נרשם ב: %s',
'Last post info'				=>	'הודעה אחרונה: %s', 
'Last visit info'        =>  'ביקור אחרון: %s',
'Show posts'				=>	'הצג את כל ההודעות',
'Show topics'					=>	'הצג את כל הנושאים',
'Show subscriptions'			=>	'הצג את כל ההרשמות לקבלת עדכונים',
'Realname'					=>	'שם אמיתי',
'Location'					=>	'מיקום',
'Website'					=>	'אתר אינטרנט',
'Invalid website URL'          =>  'כתובת אתר אינטרנט שהזנת לא חוקית.',
'Jabber'					=>	'Jabber',
'ICQ'					=>	'ICQ',
'MSN'					=>	'MSN Messenger',
'AOL IM'					=>	'AOL IM',
'Yahoo'					=>	'Yahoo! Messenger',
'Avatar'					=>	'אווטר',
'Signature'					=>	'חתימה',
'Sig max size'				=>	'אורך מקסימלי: %s תווים / מקסימום שורות: %s',
'Avatar legend'				=>	'הגדרות תצוגת אווטר',
'Avatar info'					=>	'אווטר זוהי תמונה קטנה שתוצג בכל הודעה שלך מתחת לשם משתמש. ביכולתך להעלות אווטר ע"י לחיצה על הקישור להלן.',
'Change avatar'				=>	'שנה אווטר',
'Signature legend'				=>	'צור חתימה',
'Signature info'				=>	'חתימה היא פיסת טקסט קטנה המצורפת להודעותיך. בה ניתן לכתוב כל מה שתרצה. בחתימה שלך תוכל להשתמש ב BBCode אם הוא פעיל בפורום זה בפרט. ניתן לראות את התכונות המופעלות / מורשות הרשומות להלן בכל פעם שתערוך את חתימתך.',
'Sig preview'					=>	'תצוגה מקדימה של החתימה נוכחית:',
'No sig'					=>	'אין לך חתימה כרגע.',
'Signature quote/code/list/h'  =>	'תגי הציטוט, קוד ורשימות אסורים לשימוש בחתימות.',
'Topics per page'			=>	'נושאים',
'Posts per page'			=>	'הודעות',
'Leave blank'			=>	'השאר ריק בכדי להשתמש בברירת המחדל של הפורום',
'Subscription legend'	            	    	=>	'הגדרת אפשרויות קבלת עדכונים מנושאים בפורום',
'Notify full'				=>	'לכלול את טקסט ההודעה בתוך מכתב העדכון מנושא .',
'Auto notify full'			=>	'הרשם לקבלת עדכונים מנושא באופן אוטומטי בעת פרסום הודעה.',
'Show smilies'			=>	'הצג סמיילים כתמונות גרפיות.',
'Show images'			=>	'הצג תמונות בהודעות.',
'Show images sigs'			=>	'הצג תמונות בחתימות של משתמשים.',
'Show avatars'			=>	'הצג אווטרים של משתמשים.',
'Show sigs'				=>	'הצג חתימות של משתמשים.',
'Style legend'			=>	'בחר את העיצוב המועדף עליך',
'Styles'				=>	'עיצובים',
'Admin note'				=>	'הערת מנהל ראשי',
'Pagination legend'			=>	'הגדרות הצגת דפים, נושאים והודעות בפורום',
'Post display legend'			=>	'הגדרות עבור צפיית הודעות בפורום',
'Post display info'			=>	'אם הינך על חיבור אינטרנט איטי, השבתת אחת או יותר מהאפשרויות להלן, במיוחד תצוגת תמונות בהודעות וחתימות, יגרום לטעינה מהירה יותר של דפים.',
'Instructions'				=>	'לאחר עדכון הפרופיל, תועבר חזרה לדף זה.',

// Administration stuff
'Group membership legend'		=>	'בחר קבוצת משתמשים',
'Save'				=>	'שמור',
'Set mods legend'			=>	'הגדרת גישת מנהלים',
'Moderator in info'			=>	'בחר בפורום שמשתמש זה יוכל לנהל. הערה: אפשרות זו חלה רק על מנהלי פורומים. למנהלים ראשיים תמיד יש הרשאות מלאות בכל הפורומים.',
'Update forums'			=>	'עדכן פורומים',
'Delete ban legend'			=>	'מחיקה (מנהלים ראשיים בלבד) או חסימת המשתמש',
'Delete user'				=>	'מחק משתמש',
'Ban user'				=>	'חסום משתמש',
'Confirm delete legend'			=>	'חשוב: קרא לפני מחיקת משתמש',
'Confirm delete user'			=>	'אשר מחיקת משתמש',
'Confirmation info'			=>	'אנא אשר שברצונך למחוק את המשתמש',	// the username will be appended to this string
'Delete warning'			=>	'אזהרה! לא ניתן לשחזר משתמשים ו/או הודעות שנמחקו. אם תבחר שלא למחוק את ההודעות שנכתבו ע"י משתמש זה, ניתן יהיה למחקם במועד מאוחר יותר רק באופן ידני.',
'Delete posts'			=>	'מחק את כל הודעות והנושאים שמשתמש זה פרסם.',
'Delete'				=>	'מחק',		// submit button (confirm user delete)
'User delete redirect'			=>	'המשתמש נמחק. מעביר &hellip;',
'Group membership redirect'		=>	'חברות הקבוצה נשמרה. מעביר &hellip;',
'Update forums redirect'			=>	'זכויות מנהל הפורום עודכנו. מעביר &hellip;',
'Ban redirect'			=>	'מעביר &hellip;',
'No delete admin message'		=>	'לא ניתן למחוק מנהלים ראשיים. בכדי למחוק משתמש זה, עלייך קודם להעבירו לקבוצת משתמשים אחרת',

);
