<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'				=>	'חיפוש משתמש',
'No search permission'		=>	'אין לך הרשאה מתאימה לשימוש בתכונת החיפוש',
'Search flood'				=>	'לפחות %s שניות צריכות לעבור בין החיפושים. אנא המתן זמן מה ונסה לחפש שנית.',
'Search'					=>	'חיפוש',
'Search criteria legend'	=>	'הזן את קריטריון החיפוש שלך',
'Search info'				=>	'בכדי לחפש לפי מילות מפתח, הזן מונח או מונחים לחיפוש. הפרד מונחים עם רווחים. השתמש במילים ו, או ולא בכדי לצמצם את החיפוש שלך. בכדי לחפש לפי מחבר ההודעה הזן את שם המשתמש של המחבר אשר את הודעותיו ברצונך לחפש. השתמש בתווי * עבור התאמה חלקית.',
'Keyword search'			=>	'מילת חיפוש',
'Author search'				=>	'חיפוש לפי שם משתמש',
'Search in legend'			=>	'בחר איפה לחפש',
'Search in info'			=>	'בחר בפורום שבו אתה מעוניין לחפש ואם ברצונך לחפש בכותרות נושאים, טקסט הודעות או שניהם.',
'Search multiple forums info'    =>  'אם לא נבחרו פורומים לחיפוש, החיפוש יתבצע בכל הפורומים.',
'Forum search'				=>	'פורום',
'All forums'				=>	'כל הפורומים',
'Search in'					=>	'חפש ב',
'Message and subject'		=>	'כותרות נושאים וטקסט הודעות',
'Message only'				=>	'טקסט הודעות בלבד',
'Topic only'				=>	'כותרות נושאים בלבד',
'Sort by'					=>	'מיין לפי',
'Sort order'				=>	'סדר מיון',
'Search results legend'		=>	'בחר כיצד להציג את תוצאות החיפוש',
'Search results info'		=>	'ניתן לבחור איך ברצונך למיין ולהציג את תוצאות החיפוש.',
'Sort by post time'			=>	'זמן פרסום ההודעה',
'Sort by author'			=>	'מחבר ההודעה',
'Sort by subject'			=>	'כותרת ההודעה',
'Sort by forum'				=>	'פורום',
'Ascending'					=>	'עולה',
'Descending'				=>	'יורד',
'Show as'					=>	'הצג תוצאות כ',
'Show as topics'			=>	'נושאים',
'Show as posts'				=>	'הודעות',

// Results
'Search'              =>  'חיפוש',
'Search results'			=>	'תוצאות חיפוש',
'Quick search show_new'        =>  'חדשים',
'Quick search show_recent'      =>  'פעילים',
'Quick search show_unanswered'    =>  'שלא נענו',
'Quick search show_replies'      =>  'שפרסמת בהם',
'Quick search show_user_topics'    =>  'נושאים ע"י %s',
'Quick search show_user_posts'    =>  'הודעות ע"י %s',
'Quick search show_subscriptions'  =>  'נרשם לקבלת עדכונים ע"י %s',
'By keywords show as topics'    =>  'נושאים עם הודעות המכילות \'%s\'',
'By keywords show as posts'      =>  'הודעות המכילות \'%s\'',
'By user show as topics'      =>  'נושאים עם הודעות ע"י %s',
'By user show as posts'        =>  'הודעות ע"י %s',
'By both show as topics'      =>  'נושאים עם הודעות המכילות \'%s\' ע"י %s',
'By both show as posts'        =>  'הודעות המכילות \'%s\' ע"י %s',
'No terms'					=>	'עלייך להזין לפחות מילת חיפוש אחת ו/או מחבר כדי לבצע את החיפוש.',
'No hits'					=>	'לא נמצאו תוצאות לחיפוש שלך.',
'No user posts'				=>	'אין הודעות מאת משתמש זה בפורום זה.',
'No user topics'			=>	'אין נושאים מאת משתמש זה בפורום זה.',
'No subscriptions'			=>	'בשלב זה משתמש זה אינו רשום לקבלת עדכונים משום נושא.',
'No new posts'				=>	'אין נושאים עם הודעות חדשות מאז ביקורך האחרון.',
'No recent posts'			=>	'לא נוצרו הודעות חדשות ב 24 השעות האחרונות.',
'No unanswered'				=>	'אין הודעות ללא תגובה בפורום זה.',
'Go to post'				=>	'עבור להודעה',
'Go to topic'				=>	'עבור לנושא'

);
