<?php

// Language definitions used in admin-options.php
$lang_admin_options = array(

'Bad HTTP Referer message'			=>	'وصلة مرجعية خاطئة HTTP_REFERER. إذا قمت بنقل هذا المنتدى إلى موقع جديد أو نطاق آخر، أنت بحاجة إلى تعديل Base URL في قاعدة البيانات يدويا (أنظر إلى o_base_url في جدول config) و قم بتفريغ الـ cache بحذف كل ملفات الـ PHP الموجودة في الدليل/المجلد /cache.',
'Must enter title message'			=>	'يجب ادخال عنوان المنتدى.',
'Invalid e-mail message'			=>	'العنوان البريدي المدخل للمدير غير صحيح.',
'Invalid webmaster e-mail message'	=>	'العنوان البريدي المدخل مدير الموقع غير صحيح.',
'SMTP passwords did not match'		=>	'يجب ادخال كلمة مرور الخاصة بالـ SMTP مرتين متطابقتين ليتم تغييرها.',
'Enter announcement here'			=>	'أدخل بلاغك هنا.',
'Enter rules here'					=>	'أدخل القواعد هنا.',
'Default maintenance message'		=>	'المنتديات متوقفة مؤقتاً للإصلاحات. يرجى المحاولة في وقت آخر.',
'Timeout error message'				=>	'قيمة "زمن التواجد" يجب أن يكون أصغر من "زمن الزيارة".',
'Options updated redirect'			=>	'تم تحديث الخيارات. توجيه …',
'Options head'						=>	'الخيارات',

// Essentials section
'Essentials subhead'				=>	'أساسيات',
'Board title label'					=>	'العنوان الرئيسي',
'Board title help'					=>	'العنوان الرئيسي لهذا المنتدى (يظهر في أعلى كل صفحة). هذا الحقل <strong>لا يمكن</strong> أن يحتوي على HTML.',
'Board desc label'					=>	'الوصف الرئيسي',
'Board desc help'					=>	'وصف مختصر للمنتدى (يظهر في أعلى كل صفحة). هذا الحقل قد يحوي HTML.',
'Base URL label'					=>	'موقع المنتدى URL',
'Base URL help'						=>	'المسار الكامل لموقع المنتدى بدون أن ينتهي بعلامة التقسيم (مثال: http://www.mydomain.com/forums). من <strong>الواجب</strong> أن يكون صحيحا حتى تستطيع استخدام جميع مزايا الإدارة و الاشراف. إذا حصلت على خطأ "Bad referer", فهذا يعني أن القيمة غير صحيحة.',
'Timezone label'					=>	'المنطقة الزمنية الافتراضية',
'Timezone help'						=>	'المنطقة الزمنية الافتراضية من أجل الزوار أو المستخدمين المسجلين الجدد.',
'DST label'							=>	'تعديل التوقيت الصيفي',
'DST help'							=>	'التأكد من التوقيت الصيفي (يتم الزيادة بساعة واحدة).',
'Language label'					=>	'اللغة الافتراضية',
'Language help'						=>	'اللغة الافتراضية للزوار و للمستخدمين في حال لم يتم تغيير اللغة الخاصة بهم. إذا قمت بإلغاء تركيب اللغة من موقع منتداك قم بتحديث هذا الخيار.',
'Default style label'				=>	'المظهر الافتراضي',
'Default style help'				=>	'المظهر الافتراضي للزوار و للمستخدمين في حال لم يتم تغيير االمظهر لخاص بهم.',

// Essentials section timezone options
'UTC-12:00'							=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'							=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'							=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'							=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'							=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'							=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'							=>	'(UTC-08:00) Pacific',
'UTC-07:00'							=>	'(UTC-07:00) Mountain',
'UTC-06:00'							=>	'(UTC-06:00) Central',
'UTC-05:00'							=>	'(UTC-05:00) Eastern',
'UTC-04:00'							=>	'(UTC-04:00) Atlantic',
'UTC-03:30'							=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'							=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'							=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'							=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'								=>	'(UTC) Western European, Greenwich',
'UTC+01:00'							=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'							=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'							=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'							=>	'(UTC+03:30) Iran',
'UTC+04:00'							=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'							=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'							=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'							=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'							=>	'(UTC+05:45) Nepal',
'UTC+06:00'							=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'							=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'							=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'							=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'							=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'							=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'							=>	'(UTC+09:30) Australian Central',
'UTC+10:00'							=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'							=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'							=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'							=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'							=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'							=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'							=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'							=>	'(UTC+14:00) Line Islands',

// Timeout Section
'Timeouts subhead'					=>	'الوقت و الزمن',
'Time format label'					=>	'تنسيق الوقت',
'PHP manual'						=>	'دليل PHP',
'Time format help'					=>	'[التنسيق الحالي: %s]. أنظر %s من أجل خيارات التنسيق.',
'Date format label'					=>	'تنسيق التاريخ',
'Date format help'					=>	'[التنسيق الحالي: %s]. أنظر %s من أجل خيارات التنسيق.',
'Visit timeout label'				=>	'زمن الزيارة',
'Visit timeout help'				=>	'عدد الثوان التي يجب تمر و المستخدم في حالة سكون قبل أن يتم تحديث وقت آخر زيارة له (تؤثر على مؤشر الرسائل الغير مقرؤة).',
'Online timeout label'				=>	'زمن التواجد',
'Online timeout help'				=>	'عدد الثوان التي يجب أن يتوقف فيها المستخدم عن استعراض المنتدى ليعتبر بأنه غير متواجد في المنتدى.',
'Redirect time label'				=>	'زمن التوجيه',
'Redirect time help'				=>	'عدد الثوان للإنتظار عند إعادة التوجيه. إذا كانت القيمة صفر فلن تكون هنالك شاشة إعادة توجيه (وهو غير مفضل).',

// Display Section
'Display subhead'					=>	'عرض',
'Version number label'				=>	'رقم الإصدار',
'Version number help'				=>	'أظهر رقم الإصدار لـ FluxBB أسفل الصفحة.',
'Info in posts label'				=>	'معلومات المستخدم في المداخلات',
'Info in posts help'				=>	'أظهر معلومات عن كاتب المداخلة تحت اسم المستخدم عند قراءة المواضيع. المعلومات هي المنطقة و تاريخ التسجيل و عدد المداخلات و معلومات الاتصال (البريد و الموقع).',
'Post count label'					=>	'عدد المداخلات',
'Post count help'					=>	'أظهر عدد المداخلات التي قام بها المستحدم(تؤثر على عرض الموضوع و الهيئة و قائمة المستخدمين).',
'Smilies label'						=>	'الابتسامات في المداخلات',
'Smilies help'						=>	'قم بتحويل الابتسامات النصية إلى صور صغير.',
'Smilies sigs label'				=>	'الابتسامات في التواقيع',
'Smilies sigs help'					=>	'قم بتحويل الابتسامات النصية إلى صور صغير في التواقيع.',
'Clickable links label'				=>	'وصلات حيوية',
'Clickable links help'				=>	'إذا تم تفعيلها, سيتم إكتشاف تلقائي لأي موقع يتم إدراجه في المداخلة و تحويله إلى وصلة حيوية قابلة للنقر عليها.',
'Topic review label'				=>	'عرض الموضوع',
'Topic review help'					=>	'عدد المداخلات التي سيتم إظهارها عند إدخال مداخلة جديدة (الأحدث أولاً). ضع صفر لإلغاء العرض.',
'Topics per page label'				=>	'المواضيع بكل صفحة',
'Topics per page help'				=>	'العدد الافتراضي للمواضيع في كل صفحة في المنتدى، يستطيع المستخدم تغييره في إعداداته الخاصة.',
'Posts per page label'				=>	'المداخلات بكل صفحة',
'Posts per page help'				=>	'العدد الافتراضي للمداخلات في كل صفحة في الموضوع، يستطيع المستخدم تغييره في إعداداته الخاصة.',
'Indent label'						=>	'طول الإزاحة',
'Indent help'						=>	'إذا كانت القيمة 8, سوف يتم استعمال الإزاحة النظامية ضمن المصدر البرمجي عند استعمال [code][/code]. أو سيتم استعماله عدد الفراغات لعمل الإزاحة.',
'Quote depth label'					=>	'عمق الاقتباس [quote]',
'Quote depth help'					=>	'عدد المرات التي يمكن استعمال عملية الاقتباس داخل بعضها، يمكن استعمال [quote] داخل علامة [quote] أخرى, إذا تم استعمالها أكثر من هذه القيمة سيتم تجاهل الباقي.',

// Features section
'Features subhead'					=>	'مزايا',
'Quick post label'					=>	'مداخلة سريعة',
'Quick post help'					=>	'إذا تم تفعيله، سيتم إظهار إضافة سريعة للمداخلة أسفل الموضوع. بهذه الطريقة يستطيع المستخدمون إضافة مداخلاتهم مباشرة في الموضوع.',
'Users online label'				=>	'المستخدمين المتواجدين',
'Users online help'					=>	'إظهار معلومات أسفل الصفحة الرئيسية عن الزوار و المستخدمين المسجلين عند استعراضهم المنتدى.',
'Censor words label'				=>	'حجب الكلمات',
'Censor words help'					=>	'قم بتفعيله إذا أردت أن تحجب الكلمات الغير مرغوب بها في المنتدى. أنظر %s لمعلومات أكثر.',
'Signatures label'					=>	'التواقيع',
'Signatures help'					=>	'يسمح للمستخدمين بوضع توقيعاتهم أسفل المداخلات.',
'User ranks label'					=>	'رتب المستخدم',
'User ranks help'					=>	'قم بتفعليها ليتم احتساب رتب المستخدمين. أنظر %s لمعلومات أكثر.',
'User has posted label'				=>	'لديك مداخلة مؤخراً',
'User has posted help'				=>	'أثناء عرض المواضيع تظهر نقطة تدل المستخدم على أنه قام بكتابة مداخلة في هذا الموضوع مؤخراً، قم بإلغاء هذه الميزة إذا لاحظت أي إجهاد على المخدم.',
'Topic views label'					=>	'مشاهدة المواضيع',
'Topic views help'					=>	'احتسب عدد مرات المشاهدة للموضوع. قم بإلغاءه إذا لاحظت إجهاداً على المخدم.',
'Quick jump label'					=>	'انتقال سريع',
'Quick jump help'					=>	'قم بتفعليه لإظهار منسدلة الانتقال السريع (انتقال إلى المنتدى مباشرة).',
'GZip label'						=>	'ضغط المخرجات GZip',
'GZip help'							=>	'إذا تم تفعليه سوف يقوم FluxBB بضغط المخرجات المرسلة للمستعرض، هذا سوف يخفض من حجم البيانات المنتقلة من موقعك مما يوفر عليك حجم الحزمة، و لكنه سوف يرفع من استخدام المعالج الذي يشغل ملفات PHP التي تستخدم  zlib --with-zlib. ملاحظة: إذا كان الـ Apache يستخدم mod_gzip أو mod_deflate لضغط المخرجات، قم بإيقاف هذه الميزة.',
'Search all label'					=>	'بحث في كل المنتديات',
'Search all help'					=>	'إذا قمت بإلغاءه سوف لن يستطيع المستخدم البحث في المنتديات دفعة واحدة، قم بإلغاءه إذا لاحظت جهداً على المخدم عند عملية البحث.',
'Menu items label'					=>	'بنود إضافية للقائمة',
'Menu items help'					=>	'تستطيع إضافة وصلات HTML في هذا الحقل، أي عدد تريده من الوصلات لكي تمكن المستخدم من التجوال في موقعك، سوف تظهر الوصلات في القائمة في كل الصفحات. هنالك صيغة لإضافة الوصلة <SPAN dir = "ltr">X = &lt;a href="URL"&gt;LINK&lt;/a&gt; </SPAN>حيث X هو ترتيب البند في القائمة (مثال 0 يعني أول بند في القائمة، 2 يعني بعد "المستخدمين"). ضع كل بند في سطر.',
'Default feed label'				=>	'نوع التدفق الافتراضي',
'Default feed help'					=>	'اختر نوع التدفق القياسي للمعلومات. ملاحظة: اختيار بدون لن يلغي امكانية سحب المعلومات من الدفق, فقط يمنعه من الظهور.',
'None'								=>	'بدون',
'RSS'								=>	'RSS',
'Atom'								=>	'Atom',

// Reports section
'Reports subhead'					=>	'تقارير',
'Reporting method label'			=>	'طريقة التقارير',
'Internal'							=>	'داخلي',
'By e-mail'							=>	'بريد',
'Both'								=>	'كلاهما',
'Reporting method help'				=>	'اختر طريقة ارسال التقرير إليك المتضمن المداخلة أو الموضوع. يمكنك اختيار استلام التقرير داخليا أو عبر البريد أو كلا الطريقتين معاً، يمكن الارسال إلى عدة عناوين بريدية دفعة واحدة  ضمن القائمة في الأسفل.',
'Mailing list label'				=>	'القائمة البريدية',
'Mailing list help'					=>	'افصل العناوين بفاصلة. أصحاب العناوين البريدية هم من سيستلمون التقارير.',

// Avatars section
'Avatars subhead'					=>	'الصور الشخصية',
'Use avatars label'					=>	'استخدم الصور الشخصية',
'Use avatars help'					=>	'عند تفعيل هذا الخيار, سوف يستطيع المستخدمين رفع الصورة الشخصية التي ستوضع أسفل اللقب أو الرتبة.',
'Upload directory label'			=>	'مجلد التحميل',
'Upload directory help'				=>	'هو المجلد أو الفهرس الذي سيتم تحميل ملفات الصور الشخصية (يمكن أن يكون مرجعيا بالنسبة لمجلد  FluxBB). يجب أن يكون لديك صلاحيات الكتابة على هذا المجلد.',
'Max width label'					=>	'أقصى عرض',
'Max width help'					=>	'أقصى عرض للصورة الشخصية مسموح بها بالبكسل (يفضل 60).',
'Max height label'					=>	'أقصى صول',
'Max height help'					=>	'أقصى طول للصورة الشخصية مسموح بها بالبكسل (يفضل 60).',
'Max size label'					=>	'أقصى حجم',
'Max size help'						=>	'أقصى حجم للصورة الشخصية مسموح بها بالبايت (يفضل 10240).',

// E-mail section
'E-mail subhead'					=>	'البريد',
'Admin e-mail label'				=>	'بريد المدير',
'Admin e-mail help'					=>	'عنوان بريد مدير المنتدى.',
'Webmaster e-mail label'			=>	'بريد مدير الموقع',
'Webmaster e-mail help'				=>	'عنوان البريد الذي سيتم ارسال الرسائل منه.',
'Forum subscriptions label'			=>	'اشتراكات المنتدى',
'Forum subscriptions help'			=>	'تمكين المستخدمين من الاشتراك في المنتديات (سيستلم المستخدم رسالة عند إنشاء موضوع جديد).',
'Topic subscriptions label'			=>	'اشتراكات المنتدى',
'Topic subscriptions help'			=>	'تمكين المستخدمين من الاشتراك في المواضيع (سيستلم المستخدم رسالة عند الرد على الموضوع).',
'SMTP address label'				=>	'عنوان مخدم SMTP',
'SMTP address help'					=>	'مخدم الـ SMTP  الخارجي الذي سيتم ارسال الرسائل من خلاله، تستطيع تحديد رقم البوابة إذا لم يك المخدم يستعمل البوابة الافتراضية 25 (مثال mail.myhost.com:3580) اتركه فارغا إذا أردت استخدام المخدم المحلي.',
'SMTP username label'				=>	'مستخدم SMTP',
'SMTP username help'				=>	'اسم المستخدم للمخدم SMTP. فقط إذا كان المخدم يتطلب اسم مستخدم (أغلب المخدمات <strong>ليست</strong> بحاجة إليه)',
'SMTP password label'				=>	'كلمة مرور SMTP',
'SMTP change password help'			=>	'قم بتمكين هذا إذا كنت تريد تعديل أو حذف كلمة المرور الحالية.',
'SMTP password help'				=>	'كلمة المرور لمخدم SMTP. فقط عندما يتطلب المخدم ذلك، (أغلب المخدمات <strong>ليست</strong> بحاجة إليه)',
'SMTP SSL label'					=>	'تشفير SMTP يتطلب SSL',
'SMTP SSL help'						=>	'تشفير الاتصال مع مخدم SMTP باستخدام SSL. إذا كان مخدم الـ SMTP يتطلب ذلك، و الـ PHP تدعم هذا التشفير.',

// Registration Section
'Registration subhead'				=>	'التسجيل',
'Allow new label'					=>	'السماح بالتسجيل',
'Allow new help'					=>	'السماح بالتسجيل في المنتدى، قم بإلغاء هذا الخيار عند الظروف الخاصة.',
'Verify label'						=>	'التحقق من التسجيل',
'Verify help'						=>	'إذا تم تفعيله، ستصل للمستخدم الجديد رسالة عبر بريده تحوي كلمة المرور. يمكنه الدخول بها إلى المنتدى و تغيير كلمة المرور في الهيئة، هذه الميزة مهمة للتأكد من أن المستخدم يملك عنوان بريدي عند التسجيل أو عندما يقوم بتغيير عنوانه البريدي. مفيدة لمنع إجهاد المخدم بكثرة عملية التسجيل بواسطة عنوان بريدي واحد.',
'Report new label'					=>	'تقرير عن التسجيل',
'Report new help'					=>	'إذا تم تفعيله، المنتدى سوف يرسل تنبيهاً لقائمة العناوين البريدية (أنظر في الأعلى) عندما يتم تسجيل مستخدم جديد.',
'Use rules label'					=>	'قواعد استخدام المنتدى',
'Use rules help'					=>	'إذا تم تفعيله، المستخدم الجديد يجب أن يوافق على هذه القواعد عند عملية التسجيل (أنظر الحقل التالي). هذه القواعد سوف تظهر دائما كرابط في الأعلى في كل صفحة اثناء التجوال في المنتدى.',
'Rules label'						=>	'أدخل القواعد هنا',
'Rules help'						=>	'يمكنك هنا كتابة قواعد المنتدى و أي معلومات أخرى تريد من المستخدمين أن يقبلوها عند التسجيل. إذا قمت بتفعيل الخيار السابق يجب أن تقوم بتعبئة الحقل أو قم بإلغاء تفعيله. النص المكتوب سوف لن يعالج كمعالجة المداخلات و لكن يمكن استخدام HTML.',
'E-mail default label'				=>	'إظهار البريد الافتراضي',
'E-mail default help'				=>	'من أجل حماية الخصوصية اختر طريقة إظهار العنوان البريدي الافتراضية.',
'Display e-mail label'				=>	'أظهر العنوان البريدي للمستخدمين الآخرين.',
'Hide allow form label'				=>	'لا تظهر العنوان البريدي و لكن اسمح للمستخدمين بمراسلتك عبر المنتدى إلى بريدك.',
'Hide both label'					=>	'لاتظهر العنوان البريدي و لا تسمح للمستخدمين بمراسلتك.',

// Announcement Section
'Announcement subhead'				=>	'التبليغات',
'Display announcement label'		=>	'عرض التبليغ',
'Display announcement help'			=>	'قم بتفعيله لعرض الرسالة التالية.',
'Announcement message label'		=>	'نص رسالة التبليغ',
'Announcement message help'			=>	'النص المكتوب سوف لن يعالج كمعالجة المداخلات و لكن يمكن استخدام HTML.',

// Maintenance Section
'Maintenance subhead'				=>	'الصيانة',
'Maintenance mode label'			=>	'وضعية الصيانة',
'Maintenance mode help'				=>	'إذا تم تفعليه، سوف لن يستطيع استخدام المنتدى سوى المدراء فقط، يجب استخدام هذه الوضعية عند الحاجة إلى إيقاف المنتدى بشكل مؤقت لعملية الصيانة. <strong>تحذير! لا تقم بتسجيل خروج عندما تكون في وضيعة الصيانة</strong> لأنك لن تستطيع تسجيل الدخول ثانية.',
'Maintenance message label'			=>	'رسالة الصيانة',
'Maintenance message help'			=>	'سوف تظهر هذه الرسالة للمستخدمين في حال تفعيل وضعية الصيانة. إذا قمت بترك الرسالة فارغة سوف يستخدم المنتدى الرسالة الافتراضية. النص المكتوب سوف لن يعالج كمعالجة المداخلات و لكن يمكن استخدام HTML.',

);
