<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'لا يمكن تفحص الترقية طالما  \'allow_url_fopen\' غير فعال في هذا النظام.',
'Upgrade check failed message'		=>	'فشل في تفحص امكانية الترقية لأسباب غير معروفة.',
'Running latest version message'	=>	'الإصدار الحالي مطابق لآخر إصدار من FluxBB.',
'New version available message'		=>	'يوجد إصدار جديد من FluxBB. يمكنك تركيب آخر نسخة من %s.',
'PHPinfo disabled message'			=>	'تابع PHP phpinfo() غير فعال على المخدم.',
'Not available'						=>	'غير متوفر',
'Forum admin head'					=>	'إدارة المنتدى',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'أهلا بك في لوحة تحكم المدير لـ FluxBB. هنا يمكنك التحكم بأغلب جوانب المنتدى، ذلك يعتمد ما إذا كنت مدير أو مشرف:',
'Welcome 1'							=>	'تنظيم الأقسام و المنتديات.',
'Welcome 2'							=>	'ضبط واسع لخيارات و مزايا المنتدى.',
'Welcome 3'							=>	'تحكم بالصلاحيات للمستخدمين و الزوار.',
'Welcome 4'							=>	'استعراض احصائيات  عن IP الخاص بالمستخدمين.',
'Welcome 5'							=>	'طرد مستخدمين.',
'Welcome 6'							=>	'حجب الكلمات.',
'Welcome 7'							=>	'ضبط رتب المستخدمين.',
'Welcome 8'							=>	'تنظيف المداخات القديمة.',
'Welcome 9'							=>	'الوصول للتقارير/شكاوى المداخلات.',
'Statistics head'					=>	'احصائيات',
'FluxBB version label'				=>	'إصدار FluxBB',
'Check for upgrade'					=>	'تفحص إمكانية الترقية',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'إجهاد المخدم',
'Server load data'					=>	'%s - %s مستخدم متواجد',
'Environment label'					=>	'البيئة',
'Environment data OS'				=>	'نظام التشغيل: %s',
'Show info'							=>	'عرض المعلومات',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'المسرع: %s',
'Turck MMCache'						=>	'Turk MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'قواعد البيانات',
'Database data rows'				=>	'السجلات: %s',
'Database data size'				=>	'الحجم: %s',

);
