<?php

// Language definitions used in admin-users.php
$lang_admin_users = array(

'Non numeric message'		=>	'لقد قمت بادخال قيمة غير رقمية إلى عمود يحوي رقم فقط.',
'Invalid date time message'	=>	'لقد قمت بادخال تاريخ/وقت غير صحيح.',
'Not verified'				=>	'غير متحقق',
'User search head'			=>	'بحث عن نستخدم',
'User search subhead'		=>	'أدخل شروط البحث',
'User search info'			=>	'بحث عن مستخدمين في قاعدة البيانات. يمكن إدخال أكثر من شرط. يمكنك استعمال صيغ التجاوز مثل (*)',
'Username label'			=>	'اسم المستخدم',
'E-mail address label'		=>	'العنوان البريدي',
'Title label'				=>	'اللقب',
'Real name label'			=>	'الاسم الحقيقي',
'Website label'				=>	'الموقع',
'Jabber label'				=>	'Jabber',
'ICQ label'					=>	'ICQ',
'MSN label'					=>	'MSN Messenger',
'AOL label'					=>	'AOL IM',
'Yahoo label'				=>	'Yahoo Messenger',
'Location label'			=>	'المنطقة',
'Signature label'			=>	'التوقيع',
'Admin note label'			=>	'ملاحظة المدير',
'Posts more than label'		=>	'عدد المداخلات أكبر من',
'Posts less than label'		=>	'عدد المداخلات أقل من',
'Last post after label'		=>	'آخر مداخلة تمت بعد',
'Date help'					=>	'(yyyy-mm-dd hh:mm:ss)',
'Last post before label'	=>	'آخر مداخلة تمت قبل',
'Registered after label'	=>	'سجل بعد',
'Registered before label'	=>	'سجل قبل',
'Order by label'			=>	'ترتيب حسب',
'Order by username'			=>	'اسم المستخدم',
'Order by e-mail'			=>	'البريد',
'Order by posts'			=>	'عدد المداخلات',
'Order by last post'		=>	'آخر مداخلة',
'Order by registered'		=>	'التسجيل',
'Ascending'					=>	'تصاعدي',
'Descending'				=>	'تنازلي',
'User group label'			=>	'مجموعة المستخدم',
'All groups'				=>	'كل المجموعات',
'Unverified users'			=>	'مستخدمين غير متحقق منهم',
'Submit search'				=>	'أرسل البحث',
'IP search head'			=>	'بحث عن IP',
'IP search subhead'			=>	'أدخل عنوان IP للبحث عنه',
'IP address label'			=>	'عنوان IP',
'IP address help'			=>	'عنوان IP للبحث عن في قاعدة البيانات.',
'Find IP address'			=>	'إيجاد عنوان IP',

'Results head'				=>	'نتائج البحث',
'Results username head'		=>	'اسم المستخدم',
'Results e-mail head'		=>	'البريد',
'Results title head'		=>	'اللقب/الحالة',
'Results posts head'		=>	'المداخلات',
'Results admin note head'	=>	'ملاحظة المدير',
'Results actions head'		=>	'الأوامر',
'Results IP address head'	=>	'عنوان IP',
'Results last used head'	=>	'آخر استخدام',
'Results times found head'	=>	'مرة وجد',
'Results action head'		=>	'الأمر',
'Results find more link'	=>	'إيجاد مستخدمين أكثر من خلال الـ ip',
'Results no posts found'	=>	'لا يوجد مداخلات لهذا المستخدم في هذا المنتدى.',
'Bad IP message'			=>	'عنوان الـ IP المدرج غير صحيح الصيغة.',
'Results view IP link'		=>	'إظهار حالة IP',
'Results show posts link'	=>	'إظهار المداخلات',
'Results guest'				=>	'زائر',
'Results no IP found'		=>	'عنوان الـ IP المدرج غير موجود في قاعدة البيانات.',
'No match'					=>	'لا تطابق'

);
