<?php

// Language definitions used in install.php, localized by adaur

$lang_install = array(

'Install message'				=>	'ÇבדבÝ \'config.php\' ÛםÑ דזÌזÏ Ãז דÎÑÈ. וÐÇ םÚÒל Åבל Ãה FluxBB בד םÊד ÊÑ‗םÈו ÈÚÏ. בבÊÑ‗םÈ¡ ÇÊÈÚ ÇבÅÌÑÇÁÇÊ ÇבÊÇבםÉ.',
'Choose install language'		=>	'ÇÎÊÑ בÛÉ ÇבÊÑ‗םÈ',
'Choose install language info'	=>	'ÇבבÛÉ ÇבדÓÊÎÏדÉ Ýם ÚדבםÉ ÇבÊÑ‗םÈ.',
'Install language'				=>	'בÛÉ ÇבÊÑ‗םÈ',
'Next'							=>	'ÇבÊÇבם',
'Already installed'				=>	'Úבל דÇ םÈÏז Çה FluxBB דÑ‗È דÓÈÞÇ. ÚזÖÇ Úה Ðב‗ Þד ÈÇבÐוÇÈ Åבל <a href="index.php">והÇ</a>.',
'You are running error'			=>	'ÃהÊ ÊÞזד ÈÊÔÛםב %1$s ÇבÅÕÏÇÑ %2$s. םÊØבÈ FluxBB %3$s Úבל ÇבÃÞב %1$s %4$s בםÚדב ÈÔ‗ב ÌםÏ. םÌÈ Ãה ÊÞזד ÈÊÑÞםÉ  %1$s ÞÈב ÇבדÊÇÈÚÉ',
'My FluxBB Forum'				=>	'דהÊÏל FluxBB',
'Description'					=>	'ÈÕÑÇÍÉ בÇםד‗ה בÃÍÏ Ãה םÞזב ב‗ד דÇוז FluxBB - Þד ÈÊÌÑÈÊו ÈהÝÓ‗.',
'Username 1'					=>	'ÇÓדÇÁ ÇבדÓÊÎÏדםה םÌÈ Çה ם‗זה ØזבוÇ Úבל ÇבÃÞב 2 ÍÑÝ.',
'Username 2'					=>	'ÇÓדÇÁ ÇבדÓÊÎÏדםה םÌÈ Çה ם‗זה ØזבוÇ םÒםÏ Úה 25 ÍÑÝ.',
'Username 3'					=>	'ÇÓד ÇבדÓÊÎÏד guest דÍÌזÒ.',
'Username 4'					=>	'ÇÓדÇÁ ÇבדÓÊÎÏדםה בÇ םÌÈ Çה Ê‗זה ÈÔ‗ב ÚהזÇה IP.',
'Username 5'					=>	'ÇÓדÇÁ ÇבדÓÊÎÏדםה םÌÈ Ãה בÇ ÊÍזם וÐו ÇבÃÍÑÝ דÚÇ \', " ז [ Ãז ].',
'Username 6'					=>	'ÇÓדÇÁ ÇבדÓÊÎÏדםה םÌÈ Ãה בÇ ÊÍזם Çם דה ÑדזÒ ÇבÊהÓםÞ (BBCode) ÇבÊם ÊÓÊÎÏד Ýם ÇבדהÊÏםÇÊ.',
'Short password'				=>	'‗בדÇÊ ÇבדÑזÑ םÌÈ Ãה ם‗זה ØזבוÇ Úבל ÇבÃÞב 4 ÃÍÑÝ.',
'Passwords not match'			=>	'‗בדÇÊ ÇבדÑזÑ ÛםÑ דÊØÇÈÞÉ.',
'Wrong email'					=>	'ÚהזÇה ÇבÈÑםÏ Çב‗ÊÑזהם בבדÏםÑ ÛםÑ דבÇÆד.',
'No board title'				=>	'םÌÈ Ãה ÊÏÎב ÚהזÇה ÇבדהÊÏםÇÊ.',
'Error default language'		=>	'ÇבבÛÉ ÇבÇÝÊÑÇÖםÉ ÇבדÎÊÇÑÉ ÛםÑ דזÌזÏÉ.',
'Error default style'			=>	'ÇבדÙוÑ ÇבÇÝÊÑÇÖם ÇבדÎÊÇÑ ÛםÑ דזÌזÏ.',
'No DB extensions'				=>	'ÈםÆÉ PHP בÇ ÊÏÚד Ãם דה ÞזÇÚÏ ÇבÈםÇהÇÊ ÇבÊם םÏÚדוÇ FluxBB. םÌÈ Úבל PHP Çה םÏÚד Úבל ÇבÃÞב  MySQL Ãז PostgreSQL Ãז SQLite בםÊד ÇבÊÑ‗םÈ.',
'Administrator username'		=>	'ÇÓד ÇבדÓÊÎÏד בבדÏםÑ',
'Administrator password 1'		=>	'‗בדÉ ÇבדÑזÑ בבדÏםÑ 1',
'Administrator password 2'		=>	'‗בדÉ ÇבדÑזÑ בבדÏםÑ 2',
'Administrator email'			=>	'ÇבÈÑםÏ ÇבÇב‗ÊÑזהם בבדÏםÑ ',
'Board title'					=>	'ÚהזÇה ÇבדהÊÏםÇÊ',
'Base URL'						=>	'URL ÇבÃÓÇÓם',
'Required field'				=>	'ום ÍÞזב דØבזÈ ÇÏÎÇבוÇ Ýם ÇבהדזÐÌ.',
'FluxBB Installation'			=>	'ÊÑ‗םÈ FluxBB',
'Welcome'						=>	'דÑÍÈÇ È‗ Ýם ÊÑ‗םÈ FluxBB. ÇהÊ ÇבÂה ÓÊÞזד ÈÊÑ‗םÈ FluxBB. בÚדב ÇבÊÑ‗םÈ¡ םÌÈ Úבם‗ Ãה Ê‗דב ÇבהדזÐÌ ÇÏהÇו. ÅÐÇ זÇÌוÊ Ãם ÕÚזÈÉ Ýם ÚדבםÉ ÇבÊÑ‗םÈ ÑÌÇÁÇנ ÊזÌו בÞÑÇÁÉ ÇבÊזËםÞ',
'Install'						=>	'ÊÑ‗םÈ FluxBB 1.4',
'Errors'						=>	'םÌÈ Çה םÊד ÊÕÍםÍ ÇבÃÎØÇÁ ÇבÊÇבםÉ:',
'Database setup'				=>	'ÅÚÏÇÏ ÞÇÚÏÉ ÇבÈםÇהÇÊ',
'Info 1'						=>	'ÑÌÇÁÇנ Þד ÈÊÚÈÆÉ ÇבדÚבזדÇÊ ÇבדØבזÈÉ בÅÚÏÇÏ ÞÇÚÏÉ ÇבÈםÇהÇÊ בÜ FluxBB. םÌÈ Çה ÊÓÊזÚÈ ‗ב ÇבדÚבזדÇÊ ÇבÊם ÓÊÓÃב ÚהוÇ ÞÈב ÇÊדÇד ÚדבםÉ ÇבÊÑ‗םÈ.',
'Select database'				=>	'ÇÎÊÑ הזÚ ÞÇÚÏÉ ÇבÈםÇהÇÊ',
'Info 2'						=>	'Åה FluxBB םÏÚד  MySQL ז PostgreSQL ז SQLite. ÅÐÇ ‗Çה הזÚ ÞÇÚÏÉ ÇבÈםÇהÇÊ דÝÞזÏ דה ÇבÞÇÆדÉ בÏם‗¡ וÐÇ םÚהם Ãה ÈםÆÉ PHP בÏם‗ בÇ ÊÏÚד וÐÇ ÇבהזÚ דה ÞÇÚÏÉ ÇבÈםÇהÇÊ. דה ÃÌב דÚבזדÇÊ Ã‗ËÑ Úה ÏÚד ÞזÇÚÏ ÇבÈםÇהÇÊ ÇהÙÑ Ýם ÇבÃÓÆבÉ ז ÇבÃÌזÈÉ FAQ.',
'Dual MySQL'					=>	'Ãה ÈםÆÉ PHP בÏם‗ ÊÏÚד הזÚםה דÎÊבÝםה דה ÞזÇÚÏ ÇבÈםÇהÇÊ MySQL. ‗בÇ ÇבהזÚםה םÏÚםÇה ÇבÞםÇÓם ז ÇבדØזÑ. ÅÐÇ ‗הÊ ÛםÑ דÊÃ‗Ï Ãם ÇבהזÚםה ÊÑםÏ Ãה ÊÓÊÎÏד¡ ÌÑÈ ÇÓÊÎÏÇד ÇבדØזÑ ÝÅÐÇ ÝÔב Þד ÈÇÓÊÎÏÇד ÇבÞםÇÓם.',
'InnoDB'						=>	'Êד Ç‗ÊÔÇÝ Ãה דÎÏד ÞÇÚÏÉ ÇבÈםÇהÇÊ MySQL םÏÚד <a href="http://dev.mysql.com/doc/refman/5.0/en/innodb.html">InnoDB</a>. Óם‗זה ÎםÇÑÇ ÌםÏÇ ÅÐÇ ‗הÊ ÊÎØØ בדהÊÏםÇÊ ÖÎדÉ. ÅÐÇ ‗הÊ ÛםÑ דÊÃ‗Ï¡ בÇ ההÕÍ ÈÇÓÊÎÏÇד InnoDB.',
'Database type'					=>	'הזÚ ÞÇÚÏÉ ÇבÈםÇהÇÊ',
'Required'						=>	'(דØבזÈ)',
'Database hostname'				=>	'ÃÏÎב ÇÓד דÎÏד ÞÇÚÏÉ ÇבÈםÇהÇÊ',
'Info 3'						=>	'דÎÏד ÞÇÚÏÉ ÇבÈםÇהÇÊ (דËב: localhost, db.myhost.com or 192.168.0.15). םד‗ה‗ ÊÍÏםÏ ÑÞד ÇבÈזÇÈÉ דÎÕÕ בבדÎÏד ÅÐÇ ‗ÇהÊ בםÓÊ ÇבÇÝÊÑÇÖםÉ (דËÇב: localhost:3580). דה ÃÌב SQLite ÃÏÎב Ãם ÔםÁ Ãז ÇÊÑ‗ו \'localhost\'.',
'Database server hostname'		=>'ÇÓד דÎÏד ÞÇÚÏÉ ÇבÈםÇהÇÊ',
'Database enter name'			=>	'ÃÏÎב ÇÓד ÞÇÚÏÉ ÇבÈםÇהÇÊ',
'Info 4'						=>	'ÇÓד ÞÇÚÏÉ ÇבÈםÇהÇÊ ÇבÊם ÓםÞזד FluxBB ÈÇבÊÑ‗םÈ ÚבםוÇ ÈםÇהÇÊו. ÞÇÚÏÉ ÇבÈםÇהÇÊ םÌÈ Ãה Ê‗זה דזÌזÏÉ¡ ז דד‗ה Ãה Ê‗זה ÚÈÇÑÉ Úה דÓÇÑ דÑÌÚם בדבÝ. ÅÐÇ ‗Çה דבÝ ÞÇÚÏÉ ÇבÈםÇהÇÊ בÜ SQLite ÛםÑ דזÌזÏ ÝÓםÊד ÅהÔÇÁו ÊבÞÇÆםÇנ.',
'Database name'					=>	'ÇÓד ÞÇÚÏÉ ÇבÈםÇהÇÊ',
'Database enter informations'	=>	'ÇÏÎב דÓÊÎÏד ז ‗בדÉ דÑזÑ ÞÇÚÏÉ ÇבÈםÇהÇÊ',
'Database username'				=>	'ÇÓד דÓÊÎÏד ÞÇÚÏÉ ÇבÈםÇהÇÊ',
'Info 5'						=>	'ÇÏÎב ÇÓד דÓÊÎÏד ז ‗בדÉ ÇבדÑזÑ ÇבÊם ÓÊÓÊÎÏד בבÇÊÕÇב ÈדÎÏד ÞÇÚÏÉ ÇבÈםÇהÇÊ. ÊÌÇובוÇ ÅÐÇ ‗ÇהÊ ÞÇÚÏÉ ÇבÈםÇהÇÊ SQLite.',
'Database password'				=>	'‗בדÉ דÑזÑ ÞÇÚÏÉ ÇבÈםÇהÇÊ',
'Database enter prefix'			=>	'ÃÏÎב ÓÇÈÞÉ ÇÓדÇÁ ÇבÌÏÇזב',
'Info 6'						=>	'ÅÐÇ ÑÛÈÊ¡ םד‗ה‗ ÊÍÏםÏ ÒםÇÏÉ דÓÈזÞÉ בÊÓדםÉ ÇבÌÏזÇב Ýם ÞÇÚÏÉ ÇבÈםÇהÇÊ. וÐÇ םד‗ה‗ דה ÇÓÊÎÏÇד ÊÑ‗םÈ ÞÇÚÏÉ ÈםÇהÇÊ FluxBB ÚÏÉ דÑÇÊ Úבל הÝÓ דÎÏד ÇבÈםÇהÇÊ ז ב‗ם בÇ ÊÊÚÇÑÖ דÚ ÊÑ‗םÈÇÊ בÈÑÇדÌ ÃÎÑל¡ (דËÇב foo_)',
'Table prefix'					=>	'ÓÇÈÞÉ ÇבÌÏÇזב',
'Administration setup'			=>	'ÅÚÏÇÏ ÇבÅÏÇÑÉ',
'Info 7'						=>	'ÃÏÎב ÑÌÇÁÇנ ÇבדÚבזדÇÊ ÇבדØבזÈÉ בÇÓÊ‗דÇב ÅÚÏÇÏ ÇבדÏםÑ בÊÑ‗םÈ FluxBB.',
'Admin enter username'			=>	'ÃÏÎב ÇÓד ÇבדÓÊÎÏד בבדÏםÑ',
'Info 8'						=>	'ÇÓד ÇבדÓÊÎÏד דÏםÑ ÇבדהÊÏםÇÊ. םד‗ה‗ ÝםדÇ ÈÚÏ Ãה ÊÖםÝ דÏÑÇÁ ז דÔÑÝםה ÌÏÏ. ÃØזב ÇÓדÇÁ ÇבדÓÊÎÏדםה Èםה 2 ז 25 ÍÑÝ.',
'Admin enter password'			=>	'ÃÏÎב ז Ã‗Ï ‗בדÉ ÇבדÑזÑ בבדÏםÑ',
'Info 9'						=>	'‗בדÇÊ ÇבדÑזÑ ØזבוÇ Úבל ÇבÃÞב 4 ÃÍÑÝ. ז ום ÍÓÇÓÉ בÍÇבÉ ÇבÍÑÝ.',
'Password'						=>	'‗בדÉ ÇבדÑזÑ',
'Confirm password'				=>	'ÊÃ‗םÏ Çב‗בדÉ',
'Admin enter email'				=>	'ÇבÈÑםÏ ÇבÇב‗ÊÑזהם בבדÏםÑ',
'Info 10'						=>	'ÚהזÇה ÇבÈÑםÏ ÇבÃב‗ÊÑזהם בדÏםÑ ÇבדהÊÏםÇÊ.',
'Board setup'					=>	'ÇÚÏÇÏ ÇבדהÊÏםÇÊ',
'Info 11'						=>	'ÑÌÇÁÇנ ÃÏÎב ÇבדÚבזדÇÊ ÇבדØבזÈÉ בÇÓÊ‗דÇב ÊÑ‗םÈ FluxBB.',
'Enter board title'				=>	'ÃÏÎב ÚהזÇה ÇבדהÊÏםÇÊ',
'Info 12'						=>	'ÚהזÇה ÇבדהÊÏםÇÊ וז ÇבÐם םÙוÑ ÈÔ‗ב ÏÇÆד Ýם ÃÚבל ‗ב ÕÝÍÉ.',
'Enter board description'		=>	'ÃÏÎב זÕÝ ÇבדהÊÏםÇÊ',
'Info 13'						=>	'זÕÝ דÎÊÕÑ בוÐו ÇבדהÊÏםÇÊ (ÊÙוÑ ÃÚב ‗ב ÕÝÍÉ). ז םד‗ה Ãה ÊÍזם HTML.',
'Board description'				=>	'זÕÝ ÇבדהÊÏםÇÊ',
'Enter base URL'				=>	'ÃÏÎב ÇבÜ URL ÇבÃÓÇÓם (ÇבזÕבÉ בדהÊÏÇ‗ Ãז ÇבדזÞÚ) ÍםË Êד ÊÑ‗םÈ FluxBB.',
'Info 14'						=>	'וÐו ÇבזÕבÉ URL (ÈÏזה ÇבÜ / ÇבÃÎםÑÉ) בדהÊÏל FluxBB (דËÇב: http://forum.myhost.com or http://myhost.com/~myuser). וÐו ÇבזÕבÉ <strong>םÌÈ</strong> Ãה Ê‗זה ÕÍםÍÉ ÊדÇדÇ¡ ז ÅבÇ ÇבדÏÑÇÁ ז ÇבדÔÑÝםה בה םÓÊØםÚזÇ Ãה םÓÊÎÏדזÇ ÇבÝÚÇבםÇÊ ÇבÅÏÇÑםÉ. בÇÍÙ זÌזÏ ÞםדÉ דÚÏÉ דÓÈÞÇ דÞÊÑÍÉ דה ÞÈב FluxBB.',
'Choose the default language'	=>	'ÇÎÊÑ ÇבבÛÉ ÇבÇÝÊÑÇÖםÉ',
'Info 15'						=>	'ÇבבÛÉ ÇבÇÝÊÑÇÖםÉ ÓÊÓÊÎÏד בבÒזÇÑ ז ÇבדÓÊÎÏדםה ÇבÐםה בד םÍÏÏזÇ ÇבבÛÉ Öדה ÇבוםÆÉ ÎÇÕÉ Èוד.',
'Default language'				=>	'ÇבבÛÉ ÇבÇÝÊÑÇÖםÉ',
'Choose the default style'		=>	'ÇÎÊÑ ÇבדÙוÑ ÇבÇÝÊÑÇÖם',
'Info 16'						=>	'ÇבדÙוÑ ÇבÇÝÊÑÇÖם ÓםÓÊÎÏד בבÒזÇÑ ז ÇבדÓÊÎÏדםה ÇבÐםה בד םÍÏÏזÇ ÇבדÙוÑ Öדה ÇבוםÆÉ ÎÇÕÉ Èוד.',
'Default style'					=>	'ÇבדÙוÑ ÇבÇÝÊÑÇÖם',
'Start install'					=>	'ÅÈÏÃ ÇבÊÑ‗םÈ',
'DB type not valid'				=>	'\'%s\' הזÚ ÞÇÚÏÉ ÈםÇהÇÊ ÛםÑ דבÇÆד',
'Table prefix error'			=>	'ÇבÒÇÆÏÉ ÇבÓÇÈÞÉ בÃÓדÇÁ ÇבÌÏÇזב ÊÍזם דÍÇÑÝ ÛםÑ דÞÈזבÉ Ãז ום ØזםבÉ ÌÏÇ. ÇבÒÇÆÏÉ םÌÈ Ãה ÊÍזם ÃÍÑÝ דה a Åבל z Ãז Ãם ÑÞד Ãז _ דÓÇÝÉ דÓØÑÉ. ז ÛÇבÈÇ םÌÈ Ãה בÇ םÈÏÃ ÈÑÞד. ÃÞÕל Øזב דÞÈזב וז 40 ÍÑÝ. ÑÌÇÁÇנ ÇÎÊÑ ÒÇÆÏÉ ÓÇÈÞÉ ÃÎÑל.',
'Prefix reserved'				=>	'ÇבÒÇÆÏÉ ÇבÓÇÈÞÉ \'sqlite_\' בבÌÏÇזב דÍÌזÒÉ בדÍÑ‗ ÞÇÚÏÉ ÇבÈםÇהÇÊ SQLite. ÑÌÇÁÇנ ÇÎÊÑ ÒÇÆÏÉ ÃÎÑל.',
'Existing table error'			=>	'ÇבÌÏזב ÇבדÓדל \'%susers\' דזÌזÏ דÓÈÞÇנ Ýם ÞÇÚÏÉ ÇבÈםÇהÇÊ \'%s\'. וÐÇ םÚהם ÅדÇ Ãה FluxBB Êד ÊÑ‗םÈו דÓÈÞÇנ Ãז Åה וÐÇ ÇבÌÏזב דה ÅÍÏל ÌÏÇזב ÈÑהÇדÌ ÂÎÑ דÑ‗È Úבל ÞÇÚÏÉ ÇבÈםÇהÇÊ בÏם‗ םÔÛב ÇÓדÇÁ ÌÏÇזב FluxBB ÇבדØבזÈÉ בבÊÑ‗םÈ. ÅÐÇ ‗הÊ ÊÑםÏ ÊÑ‗םÈ Ã‗ËÑ דה הÓÎÉ בÜ FluxBB Þד ÈÇÎÊםÇÑ ÒÇÆÏÉ ÓÇÈÞÉ ÃÎÑל בÃÓדÇÁ ÇבÌÏזÇב.',
'InnoDB off'					=>	'Úבל דÇ םÈÏז Åה InnoDB ÛםÑ דÝÚב. ÑÌÇÁÇנ ÇÎÊÑ הזÚ ÂÎÑ בÞÇÚÏÉ ÇבÈםÇהÇÊ בÇ םÏÚד InnoDB. Ãז Þד ÈÊÝÚםב InnoDB Ýם דÎÏד MySQL.',
'Administrators'				=>	'ÇבדÏÑÇÁ',
'Administrator'					=>	'דÏםÑ',
'Moderators'					=>	'ÇבדÔÑÝםה',
'Moderator'						=>	'דÔÑÝ',
'Guest'							=>	'ÖםÝ',
'New member'					=>	'ÚÖז ÌÏםÏ',
'Member'						=>	'ÚÖז',
'Announcement'					=>	'ÃÏÎב ÇבÊÈםבÛ והÇ.',
'Rules'							=>	'ÃÏÎב ÇבÞזÇÚÏ והÇ',
'Maintenance message'			=>	'ÇבדהÊÏםÇÊ ÍÇבםÇ Ýם זÖÚ ÇבÕםÇהÉ דÄÞÊÇנ. ÑÌÇÁÇנ ÍÇזב דÑÉ ÃÎÑל ÈÚÏ ÚÏÉ ÏÞÇÆÞ.<br />\\n<br />\\n/ÇבדÏםÑ',
'Test post'						=>	'דÏÇÎבÉ בבÇÎÊÈÇÑ',
'Message'						=>	'ÅÐÇ ‗הÊ ÊÑל וÐÇ (Úבל דÇ ÃÚÊÞÏ)¡ דÚהÇו Ãה ÊÑ‗םÈ FluxBB ÞÏ Êד ÈהÌÇÍ! ÇבÂה Þד ÈÇבזבזÌ Åבל בזÍÉ ÇבÊÍ‗ד בÅÏÇÑÉ ז דÚÇםÑÉ דהÊÏÇ‗.',
'Test category'					=>	'ÞÓד ÊÌÑםÈם',
'Test forum'					=>	'דהÊÏל ÊÌÑםÈם',
'This is just a test forum'		=>	'וÐÇ דÌÑÏ דהÊÏל ÊÌÑםÈם',
'Alert cache'					=>	'<strong>ÝוÑÓ (דÌבÏ) ÇבÊÎÒםה ÇבדÄÞÊ cache ÛםÑ ÞÇÈב בב‗ÊÇÈÉ</strong> ב‗ם םÚדב FluxBB ÈÔ‗ב ÌםÏ¡ ÃהÊ ÈÍÇÌÉ בÌÚב <em>cache</em> ÞÇÈב בב‗ÊÇÈÉ דה ÞÈב ÇבÜ PHP. ÇÓÊÎÏד chmod בÊÚÏםב ÇבÕבÇÍםÇÊ Úבל וÐÇ ÇבÝוÑÓ¡ םד‗ה Ãה ם‗זה 0777 ום ÞםדÉ וÐו ÇבÕבÇÍםÇÊ.',
'Alert avatar'					=>	'<strong>ÝוÑÓ (דÌבÏ) ÇבÕזÑ avatars ÛםÑ ÞÇÈב בב‗ÊÇÈÉ</strong>¡ ÅÐÇ ÇÑÏÊ Ãה ÊÓדÍ בדÓÊÎÏדם‗ ÈÊÍדםב ÕזÑÉ ÎÇÕÉ Èוד ÃהÊ ÈÍÇÌÉ בÌÚב ÇבÝוÑÓ <em>avatars</em> ÞÇÈב בב‗ÊÇÈÉ דה ÞÈב ÇבÜ PHP. םד‗ה‗ ÊÍÏםÏ דÓÇÑ ÂÎÑ בבÝוÑÓ Öדה ÎםÇÑÇÊ ÇבÅÏÇÑÉ. ÇÓÊÎÏד chmod בÊÚÏםב ÇבÕבÇÍםÇÊ Úבל וÐÇ ÇבÝוÑÓ¡ םד‗ה Ãה ם‗זה 0777 ום ÞםדÉ וÐו ÇבÕבÇÍםÇÊ.',
'Alert upload'					=>	'<strong>ÚבלדÇ םÈÏז ÊÍדםב ÇבדבÝÇÊ ÛםÑ דÓדזÍ Úבל וÐו ÇבדÎÏד!</strong>¡ ÅÐÇ ÇÑÏÊ Ãה ÊÓדÍ בדÓÊÎÏדם‗ ÈÊÍדםב ÕזÑ ÎÇÕÉ Èוד ÃהÊ ÈÍÇÌÉ בÊÝÚםב file_uploads Ýם דבÝÇÊ ÇבדÚÇםÑÉ ÇבÎÇÕ ÈÜ PHP. ÈדÌÑÏ ÊÝÚםב וÐו ÇבÎÇÕםÉ¡םד‗ה ÊÝÚםב ÎםÇÑ ÊÍדםב ÇבÕזÑ ÇבÔÎÕםÉ בבדÓÊÎÏדםה Ýם ÎםÇÑÇÊ ÇבÅÏÇÑÉ.',
'FluxBB has been installed'		=>	'Êד ÊÑ‗םÈ FluxBB. בÅהוÇÁ ÚדבםÉ ÇבÊÑ‗םÈ ÇÊÈÚ ÇבÇÑÔÇÏÇÊ ÇבÊÇבםÉ.',
'Final instructions'			=>	'ÅÑÔÇÏÇÊ ÇבÅהוÇÁ',
'Info 17'						=>	'בÅהוÇÁ ÇבÊÑ‗םÈ¡ ÃהÊ ÈÍÇÌÉ בבÖÛØ Úבל ÒÑ ÊהÒםב דבÝ דÓדל config.php. ÃהÊ ÈÍÇÌÉ בÑÝÚ וÐÇ ÇבדבÝ Åבל ÇבÌÐÑ ÇבÃÓÇÓם בד‗Çה ÊÑ‗םÈ FluxBB.',
'Info 18'						=>	'ÈדÌÑÏ ÑÝÚ ÇבדבÝ config.php, Óם‗זה FluxBB ÞÏ Êד ÊÑ‗םÈו ÈÇב‗Çדב! ÚהÏ וÐו ÇבהÞØÉ, ÑÈדÇ Úבם‗ ÇבÐוÇÈ Åבל <a href="index.php">ÇבדהÊÏםÇÊ</a>.',
'Download config.php file'		=>	'ÊהÒםב דבÝ config.php',
'FluxBB fully installed'		=>	'Êד ÇבÅהÊוÇÁ דה ÊÑ‗םÈ FluxBB ÈÇב‗Çדב! ÑÈדÇ Úבם‗ <a href="index.php">ÇבÐוÇÈ Åבל ÇבדהÊÏםÇÊ</a>.',

);