<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'أدخل بريد الكتروني صالح',
'Email legend 2'			=>	'أدخل و أكد عنوان بريدي الالكتروني صالح',
'Localisation legend'		=>	'ضبط خيارات تواجدك المحلي',
'Time zone'					=>	'توقيت المنطقة',
'Time zone info'				=>	'لإظهار الوقت بشكل صحيح في المنتدى، عليك اختيار توقيت المنطقة التي تسكنها.',
'DST'						=>	'اعتماد التوقيت الصيفي (سيتم الزيادة بـ 1 ساعة).',
'Time format'				=>	'تنسيق الوقت',
'Date format'				=>	'تنسيق التاريخ',
'Default'					=>	'الافتراضي',
'Language'					=>	'اللغة',
'Email setting info'		=>	'اختر ما إذا كنت تريد أن يظهر عنوانك البريدي لباقي المستخدمين أم لا وإذا كنت تريد استقبال رسائل من باقي المستخدمين في المنتدى عبر نموذج الرسائل أم لا.',
'Email setting 1'			=>	'إظهارعنوانك البريدي.',
'Email setting 2'			=>	'اخفاء عنوانك البريدي و السماح باستقبال الرسائل عن طريق البريد.',
'Email setting 3'			=>	'اخفاء عنوانك البريدي و عدم السماح باستقبال الرسائل عن طريق البريد.',
'Privacy options legend'	=>	'ضبط خيارات خصوصيتك',
'Confirm pass'				=>	'تأكيد كلمة المرور',

'Username too short'		=>	' يجب أن يكون طول اسم المستخدم مكوّن من حرفين على الأقل. الرجاء اختيار اسم آخر (أطول).',
'Username too long'			=>	'اسم المستخدم يجب أن لا يزيد طوله عن 25 حرف. رجاءاً اختر اسم مستخدم أصغر.',
'Username guest'			=>	'اسم المستخدم الضيف محجوز. الرجاء اختيار اسم مستخدم جديد.',
'Username IP'				=>	'اسماء المستخدمين يجب ألا تكون بصيغة عنوان الـ IP. يرجى اختيار اسم مستخدم آخر.',
'Username reserved chars'	=>	'اسم المستخدم يجب أن لا يحتوي على \' أو " أو [ أو ] ولو لمرة واحدة. الرجاء اختيار اسم جديد.',
'Username BBCode'			=>	'يجب أن لا يحتوي اسم المستخدم على (BBCode) التي يستخدمها المنتدى. الرجاء اختيار اسم جديد.',
'Banned username'			=>	'اسم المستخدم هذا مطرود في هذا المنتدى. رجاءاً اختر اسم مستخدم آخر.',
'Pass too short'			=>	'كلمة المرور يجب أن تكون مؤلفة من 4 أحرف على الأقل. الرجاء اختيار كلمة مرور جديدة (أطول).',
'Pass not match'			=>	'كلمات المرور غير متطابقة. رجاءً عد للخلف و صححها.',
'Banned email'				=>	'العنوان البريدي الذي أدخلته محظور في هذا المنتدى. الرجاء اختيار عنوان بريدي آخر.',
'Dupe email'				=>	'شخص آخر قد سبق وسجل بهذا العنوان البريدي. الرجاء اختيار عنوان بريدي آخر.',
'Sig too long'				=>	'التوقيع يجب أن لا يكون أطول من %1$s حرف, يرجى تقليل عدد الأحرف مقدار %2$s حرف',
'Bad ICQ'					=>	'لقد أدخلت ICQ UIN غير صحيح. الرجاء عد للخلف و صحح.',

// I do not know how to translate this lines
'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
