<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'				=>	'بحث المستخدم',
'No search permission'		=>	'ليس لديك صلاحية لاستخدام ميزة البحث.',
'Search flood'				=>	'يجب أن يمر %s ثوان قبل أن تقوم بالبحث مرة أخرى. يرجى الانتظار قبل معاودة البحث.',
'Search'					=>	'ابحث',
'Search criteria legend'	=>	'أدخل شروط البحث',
'Search info'				=>	'للبحث بواسطة كلمة مفردة أو عدة مفردات، افصل بين المفردات بفراغ. استخدم AND أو OR أو NOT لتحسين عملية البحث، للبحث باستخدام الكاتب أدخل اسم المستخدم الذي قام بكتابة المداخلات التي تبحث عنها. استعمل محرف * للمطابقة الجزئية.',
'Keyword search'			=>	'كلمة البحث',
'Author search'				=>	'اسم الكاتب',
'Search in legend'			=>	'اختر أين ستبحث',
'Search in info'			=>	'اختر في أي منتدى ترغب البحث فيه أو فيما إذا ترغب بالبحث ضمن المواضيع أو نص الرسائل أو كلاهما.',
'Search multiple forums info'		=>	'إذا لم يتم تحديد أي منتدى سوف يتم البحث في كل المنتديات.',
'Forum search'				=>	'المنتدى',
'All forums'				=>	'كل المنتديات',
'Search in'					=>	'ابحث في',
'Message and subject'		=>	'نص الرسالة و عنوان الموضوع',
'Message only'				=>	'نص الرسالة فقط',
'Topic only'				=>	'عنوان الموضوع فقط',
'Sort by'					=>	'رتب حسب',
'Sort order'				=>	'طريقة الترتيب',
'Search results legend'		=>	'حدد طريقة عرض النتائج',
'Search results info'		=>	'اختر كيف ترغب في ترتيب و عرض النتائج',
'Sort by post time'			=>	'تاريخ المداخلة',
'Sort by author'			=>	'الكاتب',
'Sort by subject'			=>	'العنوان',
'Sort by forum'				=>	'المنتدى',
'Ascending'					=>	'تصاعدي',
'Descending'				=>	'تنازلي',
'Show as'					=>	'أظهر نتائج البحث كـ',
'Show as topics'			=>	'مواضيع',
'Show as posts'				=>	'ردود',

// Results
'Search'							=>	'بحث',
'Search results'			=>	'نتائج البحث',
'Quick search show_new'				=>	'جديد',
'Quick search show_recent'			=>	'النشطة',
'Quick search show_unanswered'		=>	'بدون رد',
'Quick search show_replies'			=>	'المدخلة',
'Quick search show_user_topics'		=>	'مواضيع %s',
'Quick search show_user_posts'		=>	'مداخلات %s',
'Quick search show_subscriptions'	=>	'المشترك بها %s',
'By keywords show as topics'		=>	'مواضيع مع مداخلات تحوي\'%s\'',
'By keywords show as posts'			=>	'مداخلات تحوي \'%s\'',
'By user show as topics'			=>	'مواضيع مع بمداخلات لـ %s',
'By user show as posts'				=>	'مداخلة لـ %s',
'By both show as topics'			=>	'مواضيع مع مداخلات \'%s\' في مداخلات %s',
'By both show as posts'				=>	'مداخلات تحوي \'%s\' بواسطة %s',
'No terms'					=>	'عليك إدخال على الأقل كلمة بحث أو اسم الكاتب للبحث.',
'No hits'					=>	'لا يوجد نتائج للبحث.',
'No user posts'				=>	'لا يوجد أي مداخلة متعلقة بهذا المستخدم في هذا المنتدى.',
'No user topics'			=>	'لا يوجد أي موضوع متعلق بهذا المستخدم في هذا المنتدى.',
'No subscriptions'			=>	'هذا المستخدم غير مشترك في أي موضوع.',
'No new posts'				=>	'لا يوجد مواضيع بمداخلات جديدة منذ آخر زيارة لك.',
'No recent posts'			=>	'لا يوجد مداخلات أجريت خلال 24 ساعة.',
'No unanswered'				=>	'لا يوجد مداخلات لم يردّ عليها في هذا المنتدى.',
'Go to post'				=>	'اذهب إلى المداخلة',
'Go to topic'				=>	'اذهب إلى الموضوع'

);