<?php

// Language definitions used in admin-users.php
// Untranslated: 35
// Czech (UTF-8 v1.4.5): MartinR [martin.ruzicka.cz(at)gmail.com]
$lang_admin_users = array(

'Non numeric message'				=>	'You entered a non-numeric value into a numeric only column.',
'Invalid date time message'			=>	'You entered an invalid date/time.',
'Not verified'						=>	'Not verified',

// Actions: mass delete/ban etc.
'No users selected'					=>	'No users selected.',
'No move admins message'	=>	'Z bezpečnostních důvodů není povoleno přesouvat více administrátorů do jiné skupiny. Pokud chcete přesunout tyto administrátory, můžete tak učinit v&nbsp;jejich uživatelských profilech.',
'No delete admins message'			=>	'Administrators cannot be deleted. In order to delete administrators, you must first move them to a different user group.',
'No ban admins message'				=>	'Administrators cannot be banned. In order to ban administrators, you must first move them to a different user group.',
'No ban mods message'				=>	'Moderators cannot be banned. In order to ban moderators, you must first move them to a different user group.',
'Move users'						=>	'Change user group',
'Move users subhead'				=>	'Select new user group',
'New group label'			=>	'Nová skupina',
'New group help'					=>	'Select the group to which the selected users will be moved. For security reasons, it is not possible to move multiple users to the administrator group.',
'Invalid group message'				=>	'Invalid group ID.',
'Users move redirect'		=>	'Uživatelská skupina změněna. Přesměrování…',
'Delete users'						=>	'Delete users',
'Confirm delete legend'				=>	'Important: read before deleting users',
'Confirm delete info'				=>	'Please confirm that you want to delete these users.',
'Delete posts'						=>	'Delete any posts and topics these users have made.',
'Delete warning'					=>	'Warning! Deleted users and/or posts cannot be restored. If you choose not to delete the posts made by these users, the posts can only be deleted manually at a later time.',
'Users delete redirect'				=>	'Users deleted. Redirecting …',
'Ban users'							=>	'Ban users',
'Message expiry subhead'			=>	'Ban message and expiry',
'Ban message label'					=>	'Ban message',
'Ban message help'					=>	'A message that will be displayed to the banned users when they visit the board.',
'Expire date label'					=>	'Expire date',
'Expire date help'					=>	'The date when these bans should be automatically removed (format: yyyy-mm-dd). Leave blank to remove manually.',
'Ban IP label'						=>	'Ban IP addresses',
'Ban IP help'						=>	'Also ban the IP addresses of the banned users to make registering a new account more difficult for them.',
'Invalid date message'				=>	'You entered an invalid expire date.',
'Invalid date reasons'				=>	'The format should be YYYY-MM-DD and the date must be at least one day in the future.',
'Users banned redirect'				=>	'Users banned. Redirecting …',

'User search head'			=>	'Hledat uživatele',
'User search subhead'		=>	'Zadejte kritéria hledání',
'User search info'			=>	'Vyledat uživatele v databázi. Pro vyhledávání můžete zadat jednu nebo více podmínek. Zástupné znaky v podobě hvězdičky (*) jsou akceptovány.',
'Username label'			=>	'Uživatelské jméno',
'E-mail address label'		=>	'E-mailová adresa',
'Title label'				=>	'Titul',
'Real name label'			=>	'Skutečné jméno',
'Website label'				=>	'Web',
'Jabber label'				=>	'Jabber',
'ICQ label'					=>	'ICQ',
'MSN label'					=>	'MSN Messenger',
'AOL label'					=>	'AOL IM',
'Yahoo label'				=>	'Yahoo Messenger',
'Location label'			=>	'Bydliště',
'Signature label'			=>	'Podpis',
'Admin note label'			=>	'Poznámka administátora',
'Posts more than label'		=>	'Počet příspěvků více než',
'Posts less than label'		=>	'Počet příspěvků méně než',
'Last post after label'		=>	'Poslední příspěvek po',
'Date help'					=>	'(rrrr-mm-dd hh:mm:ss)',
'Last post before label'	=>	'Poslední příspěvek před',
'Registered after label'	=>	'Registrován po',
'Registered before label'	=>	'Registrován před',
'Order by label'			=>	'Řadit podle',
'Order by username'			=>	'Uživatelské jméno',
'Order by e-mail'			=>	'E-mail',
'Order by posts'			=>	'Počet příspěvků',
'Order by last post'		=>	'Posledního příspěvku',
'Order by registered'		=>	'Registrace',
'Ascending'					=>	'Vzestupně',
'Descending'				=>	'Sestupně',
'User group label'			=>	'Uživatelská skupina',
'All groups'				=>	'Všechny skupiny',
'Unverified users'			=>	'Neověření uživatelé',
'Submit search'				=>	'Hledat', //zkraceno z Odeslat hledani
'IP search head'			=>	'Hledat IP adresu',
'IP search subhead'			=>	'Zadejte hledanou IP adresu',
'IP address label'			=>	'IP adresa',
'IP address help'			=>	'Hledaná IP adresa v databázi příspěvků.',
'Find IP address'			=>	'Hledat IP adresy',

'Results head'				=>	'Výsledky hledání',
'Results username head'		=>	'Uživatelské jméno',
'Results e-mail head'		=>	'E-mail',
'Results title head'				=>	'Title/Status',
'Results posts head'		=>	'Příspěvky',
'Results admin note head'	=>	'Poznámka administátora',
'Results actions head'		=>	'Akce',
'Results IP address head'	=>	'IP adresa',
'Results last used head'	=>	'Naposledy použito',
'Results times found head'			=>	'Times found',
'Results action head'		=>	'Akce',
'Results find more link'	=>	'Najít více uživatelů s touto IP adresou',
'Results no posts found'			=>	'There are currently no posts by that user in the forum.',
'Select'					=>	'Vybrat',
'Select all'				=>	'Vybrat vše',
'Unselect all'				=>	'Zrušit výběr všech',
'Ban'						=>	'Zákaz',
'Delete'					=>	'Odstranit',
'Change group'				=>	'Změnit skupinu',
'Bad IP message'					=>	'The supplied IP address is not correctly formatted.',
'Results view IP link'		=>	'Zobrazit IP statistiku',
'Results show posts link'	=>	'Zobrazit příspěvky',
'Results guest'						=>	'Guest',
'Results no IP found'				=>	'The supplied IP address could not be found in the database.',
'No match'							=>	'No match'

);
