<?php

// Language definitions used in install.php, localized by adaur
// Untranslated: 36
// Czech (UTF-8 v1.4.5): MartinR [martin.ruzicka.cz(at)gmail.com]

$lang_install = array(

'Install message'				=>	'Soubor \'config.php\' neexistuje nebo je poškozen. To znamená, že FluxBB dosud nebyl nainstalován.',
'Choose install language'		=>	'Zvolte jazyk instalace',
'Choose install language info'	=>	'Jazyk použitý pro instalační skript. Výchozí jazyk samotného fóra lze nastavit níže.',
'Install language'				=>	'Jazyk instalace',
'Change language'				=>	'Změnit jazyk',
'Next'							=>	'Další',
'Already installed'						=>	'It seems like FluxBB is already installed. You should go <a href="index.php">here</a> instead.',
'You are running error'					=>	'You are running %1$s version %2$s. FluxBB %3$s requires at least %1$s %4$s to run properly. You must upgrade your %1$s installation before you can continue.',
'My FluxBB Forum'						=>	'My FluxBB Forum',
'Description'							=>	'Unfortunately no one can be told what FluxBB is - you have to see it for yourself.',
'Username 1'							=>	'Usernames must be at least 2 characters long.',
'Username 2'							=>	'Usernames must not be more than 25 characters long.',
'Username 3'							=>	'The username guest is reserved.',
'Username 4'							=>	'Usernames may not be in the form of an IP address.',
'Username 5'							=>	'Usernames may not contain all the characters \', " and [ or ] at once.',
'Username 6'							=>	'Usernames may not contain any of the text formatting tags (BBCode) that the forum uses.',
'Short password'						=>	'Passwords must be at least 4 characters long.',
'Passwords not match'					=>	'Passwords do not match.',
'Wrong email'							=>	'The administrator email address you entered is invalid.',
'No board title'						=>	'You must enter a board title.',
'Error default language'				=>	'The default language chosen doesn\'t seem to exist.',
'Error default style'					=>	'The default style chosen doesn\'t seem to exist.',
'No DB extensions'						=>	'This PHP environment does not have support for any of the databases that FluxBB supports. PHP needs to have support for either MySQL, PostgreSQL or SQLite in order for FluxBB to be installed.',
'Administrator username'		=>	'Uživatelské jméno administrátora',
'Administrator password 1'		=>	'Heslo administrátora 1',
'Administrator password 2'		=>	'Heslo administrátora 2',
'Administrator email'			=>	'E-mail administrátora',
'Board title'					=>	'Název diskuzního fóra',
'Base URL'						=>	'Základní URL',
'Required field'						=>	'is a required field in this form.',
'FluxBB Installation'			=>	'Instalace FluxBB',
'Welcome'						=>	'Chystáte se nainstalovat FluxBB. Chcete-li nainstalovat FluxBB, je třeba vyplnit níže uvedený formulář. Pokud při instalaci narazíte na jakékoliv problémy, nahlédněte do dokumentace.',
'Install'						=>	'Instalace FluxBB 1.4',
'Errors'								=>	'The following errors need to be corrected:',
'Database setup'				=>	'Nastavení databáze',
'Info 1'						=>	'Zadejte požadované informace pro nastavení FluxBB databáze pro PunBB. Před pokračováním v&nbsp;instalaci musíte všechny tyto informace znát.',
'Select database'				=>	'Vyberte typ své databáze',
'Info 2'						=>	'FluxBB aktuálně podporuje MySQL, PostgreSQL a SQLite. Pokud vaše databáze není v rozevírací nabídce uvedena, pak toto prostředí PHP danou databázi nepodporuje. Více informací pro specifické verze konkrétních databází lze najít ve FAQ.',
'Dual MySQL'					=>	'FluxBB rozpoznal, že vaše prostředí PHP podporuje dva různé způsoby komunikace s MySQL. Tyto dvě možnosti mají název Standard (Standardní) a Improved (Zlepšený). Pokud si nejste jisti jakou možnost použít, vyzkoušejte Improved a pokud bude systém chybovat, tak zkuste Standardní.',
'InnoDB'						=>	'FluxBB rozpoznal, že MySQL server může podporovat <a href="http://dev.mysql.com/doc/refman/5.0/en/innodb.html">InnoDB</a>. Je to dobrá volba, pokud plánujete provozovat velké fórum. Pokud si nejste jisti, je doporučeno nepoužívat InnoDB.',
'Database type'					=>	'Typ databáze',
'Required'						=>	'(Povinné)',
'Database hostname'				=>	'Zadejte server databáze',
'Info 3'						=>	'Adresa databázového serveru (např.: localhost, db.mujserver.cz nebo 192.168.0.15). Jestliže není databáze přístupná na standardním portu, můžete určit číslo portu (např.: localhost:3580). Pro podporu SQLite ponechte pole prázdné, nebo ponechte \'localhost\'.',
'Database server hostname'		=>	'Server databáze',
'Database enter name'			=>	'Zadejte název své databáze',
'Info 4'						=>	'Název databáze, do které bude FluxBB nainstalován. Databáze musí existovat. Pro SQLite je to relativní cesta k&nbsp;databázovému souboru. Pokud je to možné, tak se z&nbsp;bezpečnostních důvodů doporučuje umístit databázi SQLite do soukromé (z&nbsp;webu nepřístupné) složky. Jestliže SQLite databázový soubor neexistuje, FluxBB se ho pokusí vytvořit.',
'Database name'					=>	'Název databáze',
'Database enter informations'	=>	'Zadejte uživatelské jméno své databáze a heslo',
'Database username'				=>	'Uživatelské jméno databáze',
'Info 5'						=>	'Zadejte uživatelské jméno a heslo pro připojení do databáze. Ignorujte pro SQLite.',
'Database password'				=>	'Heslo databáze',
'Database enter prefix'			=>	'Zadejte prefix (předponu) tabulek databáze',
'Info 6'						=>	'Pokud chcete, můžete zadat prefix tabulek. Toto umožní instalaci více aplikací do stejné databáze. Příklad předpony: flux_.',
'Table prefix'					=>	'Prefix tabulek',
'Administration setup'			=>	'Nastavení administrátora fóra',
'Info 7'						=>	'Zadejte požadované informace pro nastavení správce této instalace FluxBB.',
'Admin enter username'			=>	'Zadejte uživatelské jméno administrátora',
'Info 8'						=>	'Uživatelské jméno administrátora fóra. Později můžete vytvořit více administrátorů i moderátorů. Délka uživatelského jména může být v rozsahu 2 až 25 znaků.',
'Admin enter password'			=>	'Zadejte a potvrďte heslo administrátora',
'Info 9'						=>	'Heslo musí být dlouhé alespoň 4 znaky. V heslu se rozlišují malá a velká písmena.',
'Password'						=>	'Heslo',
'Confirm password'				=>	'Potvrzení hesla',
'Admin enter email'				=>	'Zadejte e-mailovou adresu administrátora',
'Info 10'						=>	'E-mailová adresa administrátora fóra.',
'Board setup'					=>	'Nastavení fóra',
'Info 11'						=>	'Zadejte požadované informace pro nastavení FluxBB diskuzního fóra.',
'Enter board title'				=>	'Zadejte název diskuzního fóra',
'Info 12'						=>	'Název diskuzního fóra (zobrazen v záhlaví každé stránky).',
'Enter board description'		=>	'Zadejte popis diskuzního fóra',
'Info 13'						=>	'Stručný popis diskuzního fóra (zobrazen v horní části každé stránky). Toto pole může obsahovat HTML.',
'Board description'				=>	'Popis diskuzního fóra',
'Enter base URL'				=>	'Zadejte základní URL této instalace FluxBB',
'Info 14'						=>	'URL (bez koncového lomítka) vašeho FluxBB fóra. Například: http://forum.mujposkytovatel.cz nebo http://mujposkytovatel.cz/~mauzivatelskaslozka. <strong>Musí</strong> se nastavit správně, jinak administrátoři a moderátoři nebudou schopni předložit žádné formuláře.	Uvědomte si, že předvolená hodnota je pouze odhad na základě zkušeností od FluxBB.',
'Choose the default language'	=>	'Zvolte výchozí jazyk',
'Info 15'								=>	'The default language used for guests and users who haven\'t changed from the default in their profile.',
'Default language'				=>	'Výchozí jazyk',
'Choose the default style'		=>	'Zvolte výchozí styl',
'Info 16'								=>	'The default style used for guests and users who haven\'t changed from the default in their profile.',
'Default style'					=>	'Výchozí styl',
'Start install'					=>	'Spustit instalaci',
'DB type not valid'						=>	'\'%s\' is not a valid database type',
'Table prefix error'					=>	'The table prefix \'%s\' contains illegal characters or is too long. The prefix may contain the letters a to z, any numbers and the underscore character. They must however not start with a number. The maximum length is 40 characters. Please choose a different prefix',
'Prefix reserved'						=>	'The table prefix \'sqlite_\' is reserved for use by the SQLite engine. Please choose a different prefix',
'Existing table error'					=>	'A table called \'%susers\' is already present in the database \'%s\'. This could mean that FluxBB is already installed or that another piece of software is installed and is occupying one or more of the table names FluxBB requires. If you want to install multiple copies of FluxBB in the same database, you must choose a different table prefix',
'InnoDB off'							=>	'InnoDB does not seem to be enabled. Please choose a database layer that does not have InnoDB support, or enable InnoDB on your MySQL server',
'Administrators'				=>	'Administrátoři',
'Administrator'					=>	'Administrátor',
'Moderators'					=>	'Moderátoři',
'Moderator'						=>	'Moderátor',
'Guests'						=>	'Hosté',
'Guest'							=>	'Host',
'New member'					=>	'Nový člen',
'Members'						=>	'Členové',
'Member'						=>	'Člen',
'Announcement'					=>	'Zde zadejte oznámení.',
'Rules'							=>	'Zde zadejte pravidla',
'Maintenance message'					=>	'The forums are temporarily down for maintenance. Please try again in a few minutes.',
'Test post'						=>	'Testovací příspěvek',
'Message'						=>	'Pokud je zobrazen tento příspěvek, pak je FluxBB fórum pravděpodobně nainstalováno a funkční. Nyní se můžete přihlásit a v administraci upravit nastavení fóra. Kontrola české diakritiky (pangram): Příliš žluťoučký kůň úpěl ďábelské ódy.',
'Test category'					=>	'Testovací kategorie',
'Test forum'					=>	'Testovací fórum',
'This is just a test forum'		=>	'To je jen testovcí fórum',
'Alert cache'							=>	'<strong>The cache directory is currently not writable!</strong> In order for FluxBB to function properly, the directory <em>%s</em> must be writable by PHP. Use chmod to set the appropriate directory permissions. If in doubt, chmod to 0777.',
'Alert avatar'							=>	'<strong>The avatar directory is currently not writable!</strong> If you want users to be able to upload their own avatar images you must see to it that the directory <em>%s</em> is writable by PHP. You can later choose to save avatar images in a different directory (see Admin/Options). Use chmod to set the appropriate directory permissions. If in doubt, chmod to 0777.',
'Alert upload'							=>	'<strong>File uploads appear to be disallowed on this server!</strong> If you want users to be able to upload their own avatar images you must enable the file_uploads configuration setting in PHP. Once file uploads have been enabled, avatar uploads can be enabled in Administration/Options/Features.',
'FluxBB has been installed'				=>	'FluxBB has been installed. To finalize the installation please follow the instructions below.',
'Final instructions'					=>	'Final instructions',
'Info 17'								=>	'To finalize the installation, you need to click on the button below to download a file called config.php. You then need to upload this file to the root directory of your FluxBB installation.',
'Info 18'								=>	'Once you have uploaded config.php, FluxBB will be fully installed! At that point, you may <a href="index.php">go to the forum index</a>.',
'Download config.php file'				=>	'Download config.php file',
'FluxBB fully installed'				=>	'FluxBB has been fully installed! You may now <a href="index.php">go to the forum index</a>.',

);
