<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'Unable to check for upgrade since \'allow_url_fopen\' is disabled on this system.',
'Upgrade check failed message'		=>	'Оновлення зірване з невідомих причин.',
'Running latest version message'	=>	'Ви використовуєте останню версію FluxBB.',
'New version available message'		=>	'Нова версія FluxBB доступна. Ви можете скачати останню версію %s.',
'PHPinfo disabled message'			=>	'Функція PHP phpinfo() була відключена на цьому сервері.',
'Not available'						=>	'Не доступно',
'Forum admin head'					=>	'Адміністрування форуму',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'Ласкаво просимо в панель управління FluxBB! Тут Ви можете налаштувати ключові параметри Вашого форуму. Залежно від того, Адміністратор Ви чи Модератор, Ви можете:',
'Welcome 1'							=>	'Налаштовувати категорії та розділи.',
'Welcome 2'							=>	'Встановити параметри за замовчуванням для форуму вцілому.',
'Welcome 3'							=>	'Контролювати права користувачів та гостей.',
'Welcome 4'							=>	'Переглядати статистику користувачів по IP.',
'Welcome 5'							=>	'Банити користувачів.',
'Welcome 6'							=>	'Налаштувати список цензурованих слів.',
'Welcome 7'							=>	'Встановити ранги користувачів.',
'Welcome 8'							=>	'Очистити старі повідомлення.',
'Welcome 9'							=>	'Реагувати на скарги користувачів.',
'Statistics head'					=>	'Статистика',
'FluxBB version label'				=>	'Версія FluxBB',
'Check for upgrade'					=>	'Шукати оновлення',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'Завантаження сервера',
'Server load data'					=>	'%s - %s користувачів online',
'Environment label'					=>	'Оточення',
'Environment data OS'				=>	'Операційна система: %s',
'Show info'							=>	'Дивитися деталі',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Прискорювач: %s',
'Turck MMCache'						=>	'Прискорювач Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'База даних',
'Database data rows'				=>	'Рядків: %s',
'Database data size'				=>	'Розмір: %s',

);
