<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'		=>		'Немає користувача з таким іменем. Якщо Ви хочете додати бан без привязки до імені, просто залиште нікнейм користувача порожнім.',	
'No user ID message'		=>		'Немає зареєстрованого користувача з таким ID.',	
'User is admin message'		=>		'Користувач %s є адміністратором і не може бути забаненим. Якщо Ви хочете забанити адміністратора, Ви повинні змінити його права.',	
'User is mod message'		=>		'Користувач %s є модератором и не може бути забаненим. Якщо Ви хочете забанити модератора, Ви повинні змінити його права.',	
'Must enter message'		=>		'Ви маєте ввести нікнейм користувача, IP чи email (хоча б одне з цього).',	
'Cannot ban guest message'		=>		'Гостя неможливо забанити.',	
'Invalid IP message'		=>		'Ви ввели невірний IP або IP-діапазон.',	
'Invalid e-mail message'		=>		'Email (тобто user@domain.com) або доменна частина (тобто domain.com) введена невірно.',	
'Invalid date message'		=>		'Ви ввели невірну дату закінчення.',	
'Invalid date reasons'		=>		'Дата має бути в форматі YYYY-MM-DD і повинна бути не раніше, аніж завтрашнє число.',	
'Ban added redirect'		=>		'Бан додано. Переадресація …',	
'Ban edited redirect'		=>		'Бан змінено. Переадресація …',	
'Ban removed redirect'		=>		'Бан видалено. Переадресація …',	

'New ban head'		=>		'Новий бан',	
'Add ban subhead'		=>		'Додавання бану',	
'Username label'		=>		'Користувач',	
'Username help'		=>		'Нікнейм користувача (регістр неважливий).',	
'Username advanced help'		=>		'Нікнейм користувача (регістр неважливий). На наступній сторінці Ви зможете ввести IP чи email. Якщо хочете забанити IP/IP-діапазон чи email просто залиште поле порожнім.',	

'Ban search head'		=>		'Пошук бана',	
'Ban search subhead'		=>		'Введіть критерії пошуку',	
'Ban search info'		=>		'Пошук бана по базі. Ви можете ввести одну чи кілька умов. Можливі маски виду зірочки (*). Залиште поляпорожніми аби побачити всі бани.',	
'Date help'		=>		'(yyyy-mm-dd)',	
'Message label'		=>		'Повідомлення',	
'Expire after label'		=>		'Застаріє після',	
'Expire before label'		=>		'Застаріє до',	
'Order by label'		=>		'Сортування за',	
'Order by username'		=>		'Нікнеймом користувача',	
'Order by ip'		=>		'IP',	
'Order by e-mail'		=>		'Email',	
'Order by expire'		=>		'Даті застаріння',	
'Ascending'		=>		'За збільшенням',	
'Descending'		=>		'За спаданням',	
'Submit search'		=>		'Шукати',	

'E-mail label'		=>		'Email',	
'E-mail help'		=>		'Email або цілий домен, який Ви можете забанити (тобто someone@somewhere.com або somewhere.com). Див. опцію \"Дозволити забанені Email\" в розділі Права.',	
'IP label'		=>		'IP адреса/IP-підмережа',	
'IP help'		=>		'IP або IP-підмережа, яку Ви будете банити (тобто 150.11.110.1 чи 150.11.110). Можна перерахувати кілька адрес через пробіл. Якщо поле IP вже заповнено, то це останній з використаних IP данного користувача.',	
'IP help link'		=>		'Клікніть %s аби переглянути статистику IP цього користувача.',	
'Ban advanced head'		=>		'Розширені налаштування',	
'Ban advanced subhead'		=>		'Додатково банити IP та email',	
'Ban message label'		=>		'Повідомлення забаненному',	
'Ban message help'		=>		'Цей текст буде показано забаненному користувачу, коли він/вона відвідає форум.',	
'Message expiry subhead'		=>		'Повідомлення і строк дії',	
'Ban IP range info'		=>		'Будьте дуже уважні з IP-діапазонами, оскільки під це правило може потрапити кілька користувачів.',	
'Expire date label'		=>		'Дата закінчення',	
'Expire date help'		=>		'Дата, коли бан автоматично знімається (формат: yyyy-mm-dd). Залиште порожнім якщо бан можна зняти лише вручну.',	

'Results head'		=>		'Результати пошуку',	
'Results username head'		=>		'Користувач',	
'Results e-mail head'		=>		'Email',	
'Results IP address head'		=>		'IP/IP-діапазон',	
'Results expire head'		=>		'Закінчення',	
'Results message head'		=>		'Повідомлення',	
'Results banned by head'		=>		'Ким забанено',	
'Results actions head'		=>		'Дії',	
'No match'		=>		'Не знайдено',	
'Unknown'		=>		'Невідомо',	

);
