<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'		=>		'Пошук користувачів',	
'No search permission'		=>		'У Вас немає прав на пошук.',	
'Search flood'		=>		'Хоча б %s сек. має пройти до наступного пошуку. Будь-ласка, зачекайте і спробуйте знову.',	
'Search'		=>		'Пошук',	
'Search criteria legend'		=>		'Введіть умови пошуку',	
'Search info'		=>		'Введіть одне чи кілька слів для пошуку. Відділяйте слова пробілами. Використовуйте умови AND, OR та NOT. Ви можете доповнити умову, вказавши автора повідомлення. Використовуйте символ * для пошуку за частиною слова.',	
'Keyword search'		=>		'Ключові слова',	
'Author search'		=>		'Автор',	
'Search in legend'		=>		'Де шукати',	
'Search in info'		=>		'Оберіть в якому розділі шукати і де: в заголовку, повідомленні чи там і там.',	
'Search multiple forums info'		=>		'Якщо жоден розділ не обрано, то пошук ведеться по всіх розділах.',	
'Forum search'		=>		'Форум',	
'Search in'		=>		'Шукати в',	
'Message and subject'		=>		'повідомленні і заголовку теми',	
'Message only'		=>		'лише в повідомленні',	
'Topic only'		=>		'лише в заголовку теми',	
'Sort by'		=>		'Сортування',	
'Sort order'		=>		'Порядок сортування',	
'Search results legend'		=>		'Оберіть, як виводити результати пошуку',	
'Search results info'		=>		'Ви можете вказати, як сортувати і показувати результати.',	
'Sort by post time'		=>		'час повідомлення',	
'Sort by author'		=>		'автор',
'Sort by subject'		=>		'тема',	
'Sort by forum'		=>		'розділ',	
'Ascending'		=>		'за зростанням',	
'Descending'		=>		'за спаданням',	
'Show as'		=>		'Показати як',	
'Show as topics'		=>		'теми',	
'Show as posts'		=>		'повідомлення',	

// Results
'Search'		=>		'Пошук',	
'Search results'		=>		'Результати пошуку',	
'Quick search show_new'		=>		'Теми з новими повідомленнями',	
'Quick search show_recent'		=>		'Активні теми',	
'Quick search show_unanswered'		=>		'Теми без відповіді',	
'Quick search show_replies'		=>		'Теми з Вашими повідомленнями',	
'Quick search show_user_topics'		=>		'Теми від %s',	
'Quick search show_user_posts'		=>		'Повідомлення від %s',	
'Quick search show_subscriptions'		=>		'Підписки від %s',	
'By keywords show as topics'		=>		'Ключові слова "%s" (теми)',	
'By keywords show as posts'		=>		'Ключові слова "%s" (повідомлення)',	
'By user show as topics'		=>		'Автор %s (теми)',	
'By user show as posts'		=>		'Автор %s (повідомлення)',	
'By both show as topics'		=>		'Ключові слова "%s" та автор %s (теми)',	
'By both show as posts'		=>		'Ключові слова "%s" та автор %s (повідомлення)',	
'No terms'		=>		'Вам потрібно ввести принаймі одне слово для пошуку та/або автора.',	
'No hits'		=>		'Нічого не знайдено.',	
'No user posts'		=>		'У цього користувача немає жодного повідомлення на форумі.',	
'No user topics'		=>		'У цього користувача немає жодної теми на форумі.',	
'No subscriptions'		=>		'Цей користувач поки не підписаний на жодну тему.',	
'No new posts'		=>		'Жодного нового повідомлення з часу Вашого останнього візиту.',	
'No recent posts'		=>		'Жодного повідомлення за останні 24 години.',	
'No unanswered'		=>		'Немає жодної теми без відповіді.',	
'Go to post'		=>		'Перейти до повідомлення',	
'Go to topic'		=>		'Перейти до теми',	

);
