<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'			=>	'이 사용자명으로 가입한 회원이 없다. 지정한 사용자명을 금지에 더하려는 것이 아니면 그냥 빈칸으로 두어라.',
'No user ID message'		=>	'이 ID로 가입한 회원이 없다',
'User is admin message'		=>	'회원 %s는 다룸이여서 금지시킬 수 없다. 다룸이를 금지시키려면 먼저 등급을 내려야 한다.',
'User is mod message'		=>	'회원 %s는 지킴이여서 금지시킬 수 없다. 지킴이를 금지시키려면 먼저 등급을 내려야 한다.',
'Must enter message'		=>	'사용자명, IP, Email에서 (적어도) 하나를 넣어야 한다.',
'Cannot ban guest message'	=>	'guest 회원을 금지시키지는 못한다.',
'Invalid IP message'		=>	'바르지 않은 IP/IP-range를 넣었다.',
'Invalid e-mail message'	=>	'넣은 email (예. user@domain.com) 이나 email의 도메인 부분 (예. domain.com)이 올바르지 않다.',
'Invalid date message'		=>	'바르지 않은 만료 날짜를 넣었다.',
'Invalid date reasons'		=>	'형식은 YYYY-MM-DD이고 날짜는 적어도 하루 뒤는 되어야 한다.',
'Ban added redirect'		=>	'금지를 더했다. Redirecting …' ,
'Ban edited redirect'		=>	'금지를 고첬다. Redirecting …',
'Ban removed redirect'		=>	'금지를 없앴다. Redirecting …',

'New ban head'				=>	'새로운 금지',
'Add ban subhead'			=>	'금지 더하기',
'Username label'			=>	'사용자명',
'Username help'				=>	'금지할 사용자명 (대/소문자 구분).',
'Username advanced help'	=>	'금지할 사용자명 (대/소문자 구분). 다음 쪽에서 맞는 IP와 Email을 넣게 될 것이다. 지정된 IP/IP-range 나 email을 금지하려면 기냥 빈칸으로 두어라.',

'Ban search head'			=>	'금지 찾기',
'Ban search subhead'		=>	'찾기 기준을 넣어라',
'Ban search info'			=>	'데이터베이스에서 금지를 찾는다. 찾기위해 하나 이상의 조건을 넣을 수 있다. 포럼에서 와일드카드로 별표 (*)를 쓴다. 모든 금지를 보려면 모든 칸을 비워두어라.',
'Date help'					=>	'(yyyy-mm-dd)',
'Message label'				=>	'쪽지',
'Expire after label'		=>	'끝나는 날짜 (이 날 뒤에)',
'Expire before label'		=>	'끝나는 날짜 (이 날  앞에)',
'Order by label'			=>	'정렬하기',
'Order by username'			=>	'사용자명',
'Order by ip'				=>	'IP',
'Order by e-mail'			=>	'Email',
'Order by expire'			=>	'끝나는 날짜',
'Ascending'					=>	'오름차순',
'Descending'				=>	'내림차순',
'Submit search'				=>	'찾기 제출',

'E-mail label'				=>	'Email',
'E-mail help'				=>	'금지시킬 email이나 email domain (즉. someone@somewhere.com / somewhere.com). 더 알려면 권한에서 "금지된 email 허용하기"를 보아라.',
'IP label'					=>	'IP/IP-ranges',
'IP help'					=>	'금지시킬 IP/IP-ranges (즉. 150.11.110.1 / 150.11.110). 주소를 빈칸으로 나누어라. 이미 IP가 넣어져 있다면, 데이터베이스에 있는 이 회원의 마지막 사용 IP다.',
'IP help link'				=>	'이 회원의 IP 통계를 보려면 %s를 눌러라.',
'Ban advanced head'			=>	'고급 금지 설정',
'Ban advanced subhead'		=>	'IP와 email로 금지를 보충한다',
'Ban message label'			=>	'금지 쪽지',
'Ban message help'			=>	'금지된 회원이 게시판에 들를 때 표시될 쪽지이다.',
'Message expiry subhead'	=>	'금지 쪽지와 끝나는 날짜',
'Ban IP range info'			=>	'IP의 일부가 같은 여러 회원이 있을 수 있기 때문에 IP-range를 금지할 때는 아주 조심해야 한다.',
'Expire date label'			=>	'끝나는 날짜',
'Expire date help'			=>	'이 금지가 자동으로 없어지는 날짜 (형식: yyyy-mm-dd). 손수 없애려면 빈칸으로 두어라.',

'Results head'				=>	'찾기 결과',
'Results username head'		=>	'사용자명',
'Results e-mail head'		=>	'Email',
'Results IP address head'	=>	'IP/IP-ranges',
'Results expire head'		=>	'끝날짜',
'Results message head'		=>	'쪽지',
'Results banned by head'	=>	'금지한 이',
'Results actions head'		=>	'동작',
'No match'					=>	'맞는게 없다',
'Unknown'					=>	'알 수 없다',

);
