<?php

// Language definitions used in admin-options.php
$lang_admin_options = array(

'Bad HTTP Referer message'			=>	'Bad HTTP_REFERER. 이 포럼을 다른 곳에서 옮겼거나 도메인을 바꾸었다면 데이터베이스에서 손수 "기본 URL"을 갱신해야 한다 (config 테이블에서 o_base_url을 찾아라). 그리고 /cache 디렉토리에서 모든 .php 파일을 지워서 캐시를 깨긋하게 해야 한다.',
'Must enter title message'			=>	'게시판 제목을 넣어야 한다.',
'Invalid e-mail message'			=>	'넣은 다룸이 email이 바르지 않다.',
'Invalid webmaster e-mail message'	=>	'넣은 웹마스터 email이 바르지 않다.',
'SMTP passwords did not match'		=>	'SMTP 비밀번호를 바꾸려면 정확하게 같은 값을 두번 넣어야 한다.',
'Enter announcement here'			=>	'여기에 알림말을 넣어라.',
'Enter rules here'					=>	'여기에 규칙을 넣어라.',
'Default maintenance message'		=>	'점검을 위해 포럼을 잠시 닫았다. 잠시 뒤에 다시 들러라.',
'Timeout error message'				=>	'"online 갱신시간" 값은 "방문 갱신시간" 값보다 적어야 한다.',
'Options updated redirect'			=>	'옵션을 갱신했다. Redirecting …',
'Options head'						=>	'옵션',

// Essentials section
'Essentials subhead'				=>	'필수 항목',
'Board title label'					=>	'게시판 제목',
'Board title help'					=>	'이 게시판의 제목 (모든 쪽의 꼭데기에 보여준다). 이 칸은 HTML을 넣으면 <strong>안 된다</strong>.',
'Board desc label'					=>	'게시판 설명',
'Board desc help'					=>	'이 게시판의 짧은 설명 (모든 쪽의 꼭데기에 보여준다). 이 칸은 HTML을 넣어도 된다.',
'Base URL label'					=>	'기본 URL',
'Base URL help'						=>	'마지막에 /가 없는 게시판의 완전한 URL (예,. http://www.mydomain.com/forums). 모든 다룸판과 다루이 기능을 돌아가게 하려면 이것이 바르게 <strong>되어야 한다</strong>. "Bad referer" 오류가 뜬다면 이것이 올바르지 않을 것이다.',
'Timezone label'					=>	'기본 시간대',
'Timezone help'						=>	'게시판에 가입하려는 손님과 회원의 기본 시간대.',
'DST label'							=>	'DST로 조정하기',
'DST help'							=>	'일광절약제가 발효되어 있다면 체크해라 (한 시간 빠그게 한다).',
'Language label'					=>	'기본 글말',
'Language help'						=>	'프로필에서 기본값을 바꾸지 않은 회원과 손님 기본 글말. 글말 꾸러미를 없애면 이것을 갱신될 것이다.',
'Default style label'				=>	'기본 모양새',
'Default style help'				=>	'프로필에서 기본값을 바꾸지 않은 회원과 손님의 기본 모양새.',

// Essentials section timezone options
'UTC-12:00'							=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'							=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'							=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'							=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'							=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'							=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'							=>	'(UTC-08:00) Pacific',
'UTC-07:00'							=>	'(UTC-07:00) Mountain',
'UTC-06:00'							=>	'(UTC-06:00) Central',
'UTC-05:00'							=>	'(UTC-05:00) Eastern',
'UTC-04:00'							=>	'(UTC-04:00) Atlantic',
'UTC-03:30'							=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'							=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'							=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'							=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'								=>	'(UTC) Western European, Greenwich',
'UTC+01:00'							=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'							=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'							=>	'(UTC+03:00) Eastern African',
'UTC+03:30'							=>	'(UTC+03:30) Iran',
'UTC+04:00'							=>	'(UTC+04:00) Moscow, Gulf, Samara',
'UTC+04:30'							=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'							=>	'(UTC+05:00) Pakistan',
'UTC+05:30'							=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'							=>	'(UTC+05:45) Nepal',
'UTC+06:00'							=>	'(UTC+06:00) Bangladesh, Bhutan, Yekaterinburg',
'UTC+06:30'							=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'							=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'							=>	'(UTC+08:00) Greater China, Australian Western, Krasnoyarsk',
'UTC+08:45'							=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'							=>	'(UTC+09:00) Japan, Korea, Chita, Irkutsk',
'UTC+09:30'							=>	'(UTC+09:30) Australian Central',
'UTC+10:00'							=>	'(UTC+10:00) Australian Eastern',
'UTC+10:30'							=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'							=>	'(UTC+11:00) Solomon Island, Vladivostok',
'UTC+11:30'							=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'							=>	'(UTC+12:00) New Zealand, Fiji, Magadan',
'UTC+12:45'							=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'							=>	'(UTC+13:00) Tonga, Phoenix Islands, Kamchatka',
'UTC+14:00'							=>	'(UTC+14:00) Line Islands',

// Timeout Section
'Timeouts subhead'					=>	'시간과 대기시간',
'Time format label'					=>	'시간 형식',
'PHP manual'						=>	'PHP 안내서',
'Time format help'					=>	'[현재 형식: %s]. 형식 옵션은 %s를 보아라.',
'Date format label'					=>	'날짜 형식',
'Date format help'					=>	'[현재 형식: %s]. 형식 옵션은 %s를 보아라.',
'Visit timeout label'				=>	'방문 갱신시간',
'Visit timeout help'				=>	'마지막 들든 날짜를 갱신하기 위해 회원이 쉬어야 하는 시간 (초). 주로 새로운 쪽지 표시기에 영향을 준다.',
'Online timeout label'				=>	'Online 갱신시간',
'Online timeout help'				=>	'접속 회원 목록에서 없어지기 전에 회원이 쉬어야 하는 시간 (초).',
'Redirect time label'				=>	'Redirect 시간',
'Redirect time help'				=>	'redirecting을 기다리는 시간 (초). "0"으로 설정하면 redirect 쪽이 표시되지 않는다 (추천 안함).',

// Display Section
'Display subhead'					=>	'표시',
'Version number label'				=>	'판번호',
'Version number help'				=>	'오른쪽 아래에 FluxBB 판번호를 보여준다.',
'Info in posts label'				=>	'글 올린 회원 정보',
'Info in posts help'				=>	'글타래 보기에서 사용자명 아래에 글쓴이의 정보를 보여준다. 보여주는 정보는 지역, 가입날짜, 올린 글 수, 연락 링크 (Email 과 URL).',
'Post count label'					=>	'회원의 올린 글 수',
'Post count help'					=>	'회원이 올린 글 수를 보여준다 (글타래 보기, 프로필, 회원 목록에서 보여준다).',
'Smilies label'						=>	'글 안의 Smilies',
'Smilies help'						=>	'웃음을 작은 표정 쪽그림으로 바꿔준다.',
'Smilies sigs label'				=>	'서명 안의 Smilies',
'Smilies sigs help'					=>	'서명에서 웃음을 작은 표정 쪽그림으로 바꿔준다.',
'Clickable links label'				=>	'누를 수 있는 링크 만들기',
'Clickable links help'				=>	'켜게되면 FluxBB는 글에 있는 모든 URL을 찾아내어 누를 수 있는 링크로 만든다.',
'Topic review label'				=>	'글타래 다시보기',
'Topic review help'					=>	'글을 올릴 때 표시할 최대 글 수 (최근 글 먼저). 끄려면 \'0\'으로 두어라.',
'Topics per page label'				=>	'쪽의 글타래 수',
'Topics per page help'				=>	'포럼에서 한 쪽에 나타낼 글타래 수의 기본값. 회원은 이 설정을 바꿀 수 있다.',
'Posts per page label'				=>	'쪽의 글 수',
'Posts per page help'				=>	'글타래에서 한 쪽에 나타낼 글 수의 기본값. 회원은 이 설정을 바꿀 수 있다.',
'Indent label'						=>	'들여쓰기 크기',
'Indent help'						=>	'8로 설정하면 글귀를 나타낼 때 [code][/code]와 함께 들여쓰기를 할 것이다. 그 밖에는 글귀를 여러칸 들여쓰는 데에 쓰일 것이다.',
'Quote depth label'					=>	'[quote] 최대 깊이',
'Quote depth help'					=>	'다른 [quote] 태그 안쪽에 들어갈 수 있는 [quote] 의 최대 횟수. 더 깊은 곳의 태그는 버려진다.',

// Features section
'Features subhead'					=>	'기능',
'Quick post label'					=>	'빠른 글 올리기',
'Quick post help'					=>	'FluxBB가 글타래의 아래에 빠른 글 쓰기 양식을 더한다. 이것은 회원이 글타래 보기에서 바로 글을 올릴 수 있는 방법이다.',
'Users online label'				=>	'회원 online',
'Users online help'					=>	'첫 쪽에 지금 게시판을 훑어보고 있는 손님과 가입한 회원의 정보를 표시한다.',
'Censor words label'				=>	'검열 단어',
'Censor words help'					=>	'게시판에서 지정된 단어를 겅열하게 한다. 더 알려면 %s를 보아라.',
'Signatures label'					=>	'서명',
'Signatures help'					=>	'회원이 올린 글에 서명을 붙일 수 있게 한다.',
//'User ranks label'					=>	'회원 등급',  <= 1.4
//'User ranks help'					=>	'회원 등급을 쓸 수 있게 한다. 더 알려면 %s를 보아라.',  <= 1.4
'User has posted label'				=>	'전에 글을 올렸었던 회원',
'User has posted help'				=>	'이 기능은 글타래에 글을 올렸던 회원이 로그인을 한 경우에 포럼보기에서 그 글타래 앞에 점을 표시한다. 서버 부하가 크다면 이 기능을 꺼라.',
'Topic views label'					=>	'글타래 읽은 횟수',
'Topic views help'					=>	'글타래의 읽은 수를 꾸준히 따라간다. 바쁜 포럼에서 서버 부하가 크다면 꺼라.',
'Quick jump label'					=>	'바로가기',
'Quick jump help'					=>	'바로가기 (포럼으로 바로가기) 목록을 켠다.',
'GZip label'						=>	'GZip output',
'GZip help'							=>	'켠다면 FluxBB는 브라우저로 가는 출력을 gzip으로 보낼 것이다. 이 것은 회선 사용량을 줄이지만 CPU를 조금 더 쓰게한다. 이 기능은 PHP가 zlib (--with-zlib)으로 구성되어야 쓸 수 있다. 알림: PHP 스크립트를 압축하기위해 이미 아파치 모둘 mod_gzip나 mod_deflate를 설정했다면 이 기능을 꺼야한다.',
'Search all label'					=>	'모든 포럼 찾기',
'Search all help'					=>	'껐을 때 찾기는 한 번에 하나의 포럼에서만 할 수 있다. 지나친 찾기로 서버 부하가 크다면 꺼라.',
'Menu items label'					=>	'덧붙이 메뉴 항목',
'Menu items help'					=>	'이 글상자에 HTML hyperlinks를 넣으면 모든 항목이 모든 쪽의 꼭데기에 있는 다닐이 메뉴에 더해진다. 더하는 새로운 링크의 형식은 X = &lt;a href="URL"&gt;LINK&lt;/a&gt; 이고 X는 링크가 들어갈 자리이다 (즉. 처음에 들어가려면 \'0\', "회원 목록" 뒤에 들어가려면 \'2\'). 각각을 줄내리기로 나누어라. 또한 링크는 상대/절대 경로 모두 가능하다.',

// Feeds section
'Feed subhead'						=>	'Syndication',
'Default feed label'				=>	'feed 기본 유형',
'Default feed help'					=>	'표시할 syndication feed 유형을 골라라. 알림: 없음을 고르면 feed를 숨겨서 표시되지 않는다.',
'None'								=>	'없음',
'RSS'								=>	'RSS',
'Atom'								=>	'Atom',
'Feed TTL label'					=>	'feed 저장 기간',
'Feed TTL help'						=>	'Feed의 자원 사용량을 줄이기위해 저장해 둘 수 있다.',
'No cache'							=>	'저장 안함',
'Minutes'							=>	'%d 분',

// Reports section
'Reports subhead'					=>	'신고',
'Reporting method label'			=>	'신고 방법',
'Internal'							=>	'내장기능',
'By e-mail'							=>	'Email',
'Both'								=>	'둘 다',
'Reporting method help'				=>	'글타래/글의 신고 방법을 골라라. 글타래/글의 신고를 내장 신고 기능으로 할 것인지 mailing list (아래를 보아라)로 메일을 보내게 할 지 두 가지 다 할 지 고를 수 있다.',
'Mailing list label'				=>	'Mailing list',
'Mailing list help'					=>	'받아보는 목록은 콤마(\,)로 나눈다. 이 목록에 있는 사람은 신고를 받아보는 사람이다.',

// Avatars section
'Avatars subhead'					=>	'아바타',
'Use avatars label'					=>	'아바타 쓰기',
//'Use avatars help'					=>	'켜면 회원은 칭호/등급 아래에 나타나는 아바타를 올려실을 수 있다.',  <= 1.4
'Use avatars help'					=>	'켜면 회원은 칭호 아래에 나타나는 아바타를 올려실을 수 있다.',
'Upload directory label'			=>	'올리싣기 디렉토리',
'Upload directory help'				=>	'아바타의 올려싣기 디렉토리 (FluxBB root 디렉토리부터의 경로). PHP가 이 디렉토리에 쓰기 권한을 가져야 한다.',
'Max width label'					=>	'최대 너비',
'Max width help'					=>	'아바타 너비의 최대 pixels (60 추천).',
'Max height label'					=>	'최대 높이',
'Max height help'					=>	'아바타 높이의 최대 pixels (60 추천).',
'Max size label'					=>	'최대 크기',
'Max size help'						=>	'아바타 크기의 최대 bytes (10240 추천 - 10 KB).',

// E-mail section
'E-mail subhead'					=>	'Email',
'Admin e-mail label'				=>	'다룸이 email',
'Admin e-mail help'					=>	'게시판 다룸이의 email.',
'Webmaster e-mail label'			=>	'웹마스터 email',
'Webmaster e-mail help'				=>	'이것은 게시판에서 보낸 모든 메일의 보낸이 주소이다.',
'Forum subscriptions label'			=>	'포럼 받아보기',
'Forum subscriptions help'			=>	'회원이 포럼에서 받아볼 수 있게 한다 (누군가 새로운 글타래를 올리면 메일로 받아본다).',
'Topic subscriptions label'			=>	'글타래 받아보기',
'Topic subscriptions help'			=>	'회원이 글타래에서 받아볼 수 있게 한다 (누군가 댓글을 달면 메일로 받아본다).',
'SMTP address label'				=>	'SMTP server address',
'SMTP address help'					=>	'메일을 보낼 외부 SMTP 서버 주소. SMTP 서버기 기본 포트인 25를 쓰지 않을 때 맞춤 포트를 지정할 수 있다  (예: mail.myhost.com:3580). 내부 메일 프로그램을 쓰려면 비워 두어라.',
'SMTP username label'				=>	'SMTP 사용자명',
'SMTP username help'				=>	'SMTP 서버의 사용자명. SMTP 서버가 요구할 때만 사용자명을 넣어라 (대부분의 서버는 인증을 요구하지 <strong>않는다</strong>).',
'SMTP password label'				=>	'SMTP 비밀번호',
'SMTP change password help'			=>	'지금 저장된 비밀번호를 바꾸거나 지우려면 이것을 체크해라.',
'SMTP password help'				=>	'SMTP 서버의 비밀번호. SMTP 서버가 요구할 때만 비밀번호를 넣어라 (대부분의 서버는 인증을 요구하지 <strong>않는다</strong>). 확인하기위해 비밀번호를 두 번 넣어라.',
'SMTP SSL label'					=>	'SSL을 써서 SMTP 암호화하기',
'SMTP SSL help'						=>	'SSL을 써서 SMTP 서버와의 연결을 암호화한다. SMTP 서버가 요구하고 너의 PHP가 SSL을 지원할 때만 써야 한다.',

// Registration Section
'Registration subhead'				=>	'가입',
'Allow new label'					=>	'새로운 가입 허용하기',
'Allow new help'					=>	'게시판에 새로운 가입을 할 수 있게 한다. 특별한 환경에서만 꺼라.',
'Verify label'						=>	'가입 확인하기',
'Verify help'						=>	'회원이 가입할 때 임의 비밀번호를 메일로 받게 한다. 그러면 로그인을 할 수 있고 프로필에서 비밀번호를 바꿀 수 있다. 또한 이 기능은 회원이 가입했을 때의 메일을 바꾸려고 한다면 새로운 Email을 확인하도록 한다. 이 기능은 무분별한 가입을 피하고 모든 회원이 프로필에 "올바른" 메일 주소를 갖게하는 효과적인 방법이다.',
'Report new label'					=>	'새로운 가입 알리기',
'Report new help'					=>	'켜면 FluxBB는 포럼에 새로운 회원이 가입했을 때 mailing list (아래를 보아라)의 회원에게 알릴 것이다.',
'Use rules label'					=>	'포럼의 회원 규칙',
'Use rules help'					=>	'켜면 회원이 가입할 때 규칙에 동의해야만 한다 (아래에 글귀를 넣어라). 이 규칙은 모든 쪽의 꼭데기에 있는 다닐이 메뉴를 거쳐서 볼 수 있다.',
'Rules label'						=>	'여기에 규칙을 넣어라',
'Rules help'						=>	'여기에 회원이 가입할 때 다시보고 받아들여야하는 모든 규칙이나 다른 정보를 넣을 수 있다. 위에서 규칙을 켰다면 여기에 뭔가를 넣어야 한다. 그렇지 않으면 규칙이 꺼질 것이다. 이 글귀는 일반 글과 달리 구문분석을 하지 않아서 HTML을 넣어도 된다.',
'E-mail default label'				=>	'email 기본 설정',
'E-mail default help'				=>	'새로운 가입 회원의 기본 개인 설정을 골라라.',
'Display e-mail label'				=>	'다른 회원에게 메일 주소를 보여준다.',
'Hide allow form label'				=>	'메일 주소는 숨기지만 메일을 보낼 수 있다.',
'Hide both label'					=>	'메일 주소를 숨기고 메일도 보낼 수 없다.',

// Announcement Section
'Announcement subhead'				=>	'알림말',
'Display announcement label'		=>	'알림말을 보여준다',
'Display announcement help'			=>	'게시판에서 아래 쪽지를 보여준다.',
'Announcement message label'		=>	'알림 쪽지',
'Announcement message help'			=>	'이 글귀는 일반 글과 달리 구문분석을 하지 않아서 HTML을 넣어도 된다.',

// Maintenance Section
'Maintenance subhead'				=>	'점검',
'Maintenance mode label'			=>	'점검 모드',
'Maintenance mode help'				=>	'켜면 게시판을 다룸이만 쓸 수 있다. 게시판을 점검을 위해 잠시 닫아야 한다면 이것을 써야 한다.  <strong>경고! 게시판이 점검 모드일 때 로그아웃을 하지 말아라.</strong> 다시 로그인을 할 수 없을 것이다.',
'Maintenance message label'			=>	'점검 쪽지',
'Maintenance message help'			=>	'게시판이 점검 모드일 때 회원에게 보여줄 쪽지. 빈칸으로 두면 기본 쪽지가 쓰인다. 이 글귀는 일반 글과 달리 구분분석을 하지 않아서 HTML을 넣어도 된다.',

);
