<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'이 시스템의 \'allow_url_fopen\'이 꺼져있어서 판올림을 확인할 수 없다.',
'Upgrade check failed message'		=>	'알 수 없는 이유로 판올림 확인이 실패했다.',
'Running latest version message'	=>	'FluxBB의 최신판을 쓰고 있다.',
'New version available message'		=>	'FluxBB의 새로운 판이 발표되었다. %s에서 최신판을 내려받을 수 있다.',
'PHPinfo disabled message'			=>	'이 서버에서는 PHP 함수 phpinfo()를 쓸 수 없다.',
'Not available'						=>	'쓸 수 없다',
'Forum admin head'					=>	'포럼 다룸판',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'FluxBB 다룸판에 잘 왔다. 여기서 게시판의 중요한 것들을 다룰 수 있다. 네가 다룸이인지 지킴이인지에 따라 할 수 있는 것:',
'Welcome 1'							=>	'범주와 포럼 구성하기.',
'Welcome 2'							=>	'포럼 전체의 선택과 선호를 설정하기.',
'Welcome 3'							=>	'회원과 손님의 권한 다루기.',
'Welcome 4'							=>	'회원들 IP 통계 보기.',
'Welcome 5'							=>	'회원 금지하기.',
'Welcome 6'							=>	'단어 검열하기.',
//'Welcome 7'							=>	'회원 등급 설정하기.',  <= 1.4
'Welcome 7'							=>	'회원 그룹과 승급 설정하기.',
'Welcome 8'							=>	'오래된 글 쳐내기.',
'Welcome 9'							=>	'신고된 글 처리하기.',
'Statistics head'					=>	'게시판 정보',
'FluxBB version label'				=>	'FluxBB 판번호',
'Check for upgrade'					=>	'판올림 확인하기',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'Server load',
'Server load data'					=>	'%s - %s 회원 접속',
'Environment label'					=>	'환경',
'Environment data OS'				=>	'운영체제: %s',
'Show info'							=>	'정보 보기',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'가속기: %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ionCube PHP 가속기',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'데이터베이스',
'Database data rows'				=>	'행: %s',
'Database data size'				=>	'크기: %s',

);
