<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'프로필 메뉴',
'Section essentials'			=>	'기본항목',
'Section personal'				=>	'개인정보',
'Section messaging'				=>	'메신저들',
'Section personality'			=>	'개인특성',
'Section display'				=>	'화면표시',
'Section privacy'				=>	'개인설정',
'Section admin'					=>	'다룸판',

// Miscellaneous
'Username and pass legend'		=>	'사용자명과 비밀번호를 넣어라',
'Personal details legend'		=>	'개인 정보를 넣어라',
'Contact details legend'		=>	'메신저 정보를 넣어라',
'User activity'					=>	'회원 활동',
'Paginate info'					=>	'한 쪽에 보길 바라는 글타래와 글의 수를 넣어라.',

// Password stuff
'Pass key bad'					=>	'지정된 비밀번호 활성키가 바르지 않거나 기한이 지났다. 새로운 비밀번호를 다시 요청해라. 요청이 실패하면 포럼 다룸이에게 연락해라:',
'Pass updated'					=>	'비밀번호가 갱신되었다. 이제 새로운 비밀번호로 로그인할 수 있다.',
'Pass updated redirect'			=>	'비밀번호를 갱신했다. Redirecting …',
'Wrong pass'					=>	'현재 비밀번호가 틀렸다.',
'Change pass'					=>	'비밀번호 바꾸기',
'Change pass legend'			=>	'새로운 비밀번호를 넣고 확인해라',
'Old pass'						=>	'현재 비밀번호',
'New pass'						=>	'새로운 비밀번호',
'Confirm new pass'				=>	'새로운 비밀번호 확인하기',
'Pass info'						=>	'비밀번호는 적어도 4 characters를 가져야 한다. 비밀번호는 대/소문자를 구분한다.',

// Email stuff
'Email key bad'					=>	'지정된 email 활성키가 바르지 않거나 기한이 지났다. 메일 변경을 다시 요청해라. 요청이 실패하면 포럼 다룸이에게 연락해라',
'Email updated'					=>	'email을 갱신했다.',
'Activate email sent'			=>	'새로운 메일을 활성시키는 방법을 가진 메일을 지정된 주소로 보냈다. 메일이 도착하지 않으면 포럼 다룸이에게 연락해라:',
'Email legend'					=>	'새로운 메일을 넣어라',
'Email instructions'			=>	'활성 링크를 가진 메일을 새로운 메일 주소로 보낼 것이다. 새로운 메일을 활성시키기위해 받은 메일에 있는 링크를 눌러야 한다.',
'Change email'					=>	'email 바꾸기',
'New email'						=>	'새로운 email',

// Avatar upload stuff
'Avatars disabled'				=>	'다룸이가 아바타 지원을 꺼버렸다.',
'Too large ini'					=>	'선택한 파일이 올려싣기에는 너무 크다. 서버가 올려싣기를 허용하지 않는다.',
'Partial upload'				=>	'선택한 파일의 일부만 올려졌다. 다시 해봐라.',
'No tmp directory'				=>	'PHP가 올려실은 파일을 임시 저장소에 저장할 수 없다.',
'No file'						=>	'올려실을 파일을 고르지 않았다.',
'Bad type'						=>	'올려실으려는 파일이 허용된 유형이 아니다. 허용된 유형은 gif, jpeg와 png이다.',
'Too wide or high'				=>	'올리실으려는 파일의 높이나 너비가 허용된 최대값보다 크다',
'Too large'						=>	'올려실으려는 파일의 크기가 허용된 최대값보다 크다',
'pixels'						=>	'pixels',
'bytes'							=>	'bytes',
'Move failed'					=>	'서버가 올려실은 파일을 저장하지 못했다. 포럼 다룸이에게 연락해라:',
'Unknown failure'				=>	'알 수 없는 오류가 생겼다. 다시 해보아라.',
'Avatar upload redirect'		=>	'아바타를 올려실었다. Redirecting …',
'Avatar deleted redirect'		=>	'아바타를 지웠다. Redirecting …',
'Avatar desc'					=>	'아바타는 네가 올린 글에서 사용자명 아래에 표시될 작은 그림이다. 다음 값보다 커서는 안된다:',
'Upload avatar'					=>	'아바타 올려싣기',
'Upload avatar legend'			=>	'올려실을 아바타 파일을 넣어라',
'Delete avatar'					=>	'아바타 지우기', // only for admins
'File'							=>	'파일',
'Upload'						=>	'올려싣기', // submit button

// Form validation stuff
'Forbidden title'				=>	'넣은 제목이 금지된 단어를 가지고 있다. 다른 제목을 골라야 한다.',
'Profile redirect'				=>	'프로필을 갱신했다. Redirecting …',

// Profile display stuff
'Users profile'					=>	'%s의 프로필',
'Username info'					=>	'사용자명: %s',
'Email info'					=>	'Email: %s',
'Posts info'					=>	'올린 글 수: %s',
'Registered info'				=>	'가입날짜: %s',
'Last post info'				=>	'마지막 올린 글: %s',
'Last visit info'				=>	'마지막 들른 때: %s',
'Show posts'					=>	'모든 글 보기',
'Show topics'					=>	'모든 글타래 보기',
'Show subscriptions'			=>	'모든 받아보기 보기',
'Realname'						=>	'진짜 이름',
'Location'						=>	'위치',
'Website'						=>	'Website',
'Invalid website URL'			=>	'넣은 URL이 올바르지 않다.',
'Website not allowed'           =>  '아직 프로필에 website를 더하도록 허용되지 않았다.',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'MSN Messenger',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'아바타',
'Signature'						=>	'서명',
'Sig max size'					=>	'최대 길이: %s characters / 최고 줄수: %s',
'Avatar legend'					=>	'아바타 표시 옵션 설정하기',
'Avatar info'					=>	'아바타는 모든 글과 함께 표시될 작은 그림이다. 아래 링크를 눌러서 아바타를 올려실을 수 있다.',
'Change avatar'					=>	'아바타 바꾸기',
'Signature legend'				=>	'서명 만들기',
'Signature info'				=>	'서명은 올린 글에 달라붙는 글귀의 일부이다. 무엇이든지 넣을 수 있다. 이 포럼에서 BBCode 가 허용되면 그것도 넣을 수 있다. 서명을 고칠 때 아래에서 허용한/켠 기능 목록을 볼 수 있다.',
'Sig preview'					=>	'서명 미리보기:',
'No sig'						=>	'아직 프로필에 저장된 서명이 없다.',
'Signature quote/code/list/h'	=>	'인용, 코드, 목록과 BBCodes는 서명에 허용되지 않는다.',
'Topics per page'				=>	'글타래',
'Posts per page'				=>	'글',
'Leave blank'					=>	'포럼 기본설정을 쓰려면 빈칸으로 두어라.',
'Subscription legend'			=>	'받아보기 옵션 설정하기',
'Notify full'					=>	'받아보기 알림 메일에 새로운 글의 글귀를 포함하기.',
'Auto notify full'				=>	'글을 올린 모든 글타래를 자동으로 받아보기.',
'Show smilies'					=>	'smilies 아이콘 보기.',
'Show images'					=>	'글에 있는 그림 보기.',
'Show images sigs'				=>	'서명에 있는 그림 보기.',
'Show avatars'					=>	'글에 있는 회원 아바타 보기.',
'Show sigs'						=>	'회원 서명 보기.',
'Style legend'					=>	'좋아하는 모양을 골라라',
'Styles'						=>	'모양새',
'Admin note'					=>	'다룸 알림',
'Pagination legend'				=>	'쪽매김 옵션을 넣어라',
'Post display legend'			=>	'글보기 옵션 설정하기',
'Post display info'				=>	'연결이 느리다면 이 옵션 (특히 글과 서명에 있는 그림 보기)을 끄는 것은 쪽읽기를 더 빠르게 할 것이다',
'Instructions'					=>	'프로필을 갱신할 때 이 쪽으로 되돌아올 것이다.',

// Administration stuff
'Group membership legend'		=>	'회원 그룹 고르기',
'Save'							=>	'저장하기',
'Set mods legend'				=>	'지킴이 접근 설정하기',
'Moderator in info'				=>	'이 회원이 다루도록 할 포럼을 골라라. 알림: 이것은 지킴이에게만 적용된다. 다룸이는 모든 포럼에서 언제나 모든 권한을 가진다.',
'Update forums'					=>	'포럼 갱신하기',
'Delete ban legend'				=>	'회원 지우기 (다룸이만) / 금지하기',
'Delete user'					=>	'회원 지우기',
'Ban user'						=>	'회원 금지하기',
'Confirm delete legend'			=>	'중요: 회원을 지우기에 앞서 이것을 읽어라',
'Confirm delete user'			=>	'회원 지우기 다시 확인하기',
'Confirmation info'				=>	'지우려는 회원이 맞는지 확인해라', // the username will be appended to this string
'Delete warning'				=>	'경고! 지운 회원이나 글은 복구할 수 없다. 이 회원이 올린 글 지우기를 고르지 않으면 나중에 글을 손수 지울 수 밖에 없다.',
'Delete posts'					=>	'이 회원이 만든 모든 글타래와 글을 지우기.',
'Delete'						=>	'지우기', // submit button (confirm user delete)
'User delete redirect'			=>	'회원을 지웠다. Redirecting …',
'Group membership redirect'		=>	'그룹 자격을 저장했다. Redirecting …',
'Update forums redirect'		=>	'포럼 지킴이 자격을 갱신했다. Redirecting …',
'Ban redirect'					=>	'Redirecting …',
'No delete admin message'		=>	'다룸이를 지울 수는 없다. 이 회원을 지우려면 먼저 다른 그룹으로 옮겨야 한다.',

);
