<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'올바른 email을 넣어라',
'Email legend 2'			=>	'올바른 메일 주소를 넣고 확인해라',
'Localisation legend'		=>	'지역 옵션 설정하기',
'Time zone'					=>	'시간대',
'Time zone info'			=>	'포럼이 제대로 시간을 표시하도록 지역 시간대를 골라야 한다. 일광절약 시간제가 발효되었다면, 1시간 앞선 시간을 제공하는 옵션을 표시해야 한다.',
'DST'						=>	'일광절약 시간제가 발효되었다 (1 시간 앞선 시간).',
'Time format'				=>	'시간 형식',
'Date format'				=>	'날짜 형식',
'Default'					=>	'기본',
'Language'					=>	'글말',
'Email setting info'		=>	'다른 회원에게 메일 주소를 보일지 안보일지와 다른 회원이 이 포럼 (양식 메일)을 통해서 너에게 메일을 보낼 수 있게 할지 안할지를 골라라',
'Email setting 1'			=>	'메일 주소 표시하기.',
'Email setting 2'			=>	'메일 주소를 숨기지만 양식 메일을 허용하기.',
'Email setting 3'			=>	'메일 주소를 숨기고 양식 메일을 허용하지 않기.',
'Privacy options legend'	=>	'개인설정 옵션 설정하기',
'Confirm pass'				=>	'비밀번호 확인하기',

'Username too short'		=>	'사용자명은 적어도 2 characters 길이를 가져야 한다. 다른 (더 긴) 사용자명을 골라라.',
'Username too long'			=>	'사용자명은 25 characters 보다 길면 안된다. 다른 (더 짧은) 사용자명을 골라라.',
'Username guest'			=>	'사용자명 guest는 미리 정해져 있다. 다른 사용자명을 골라라.',
'Username IP'				=>	'사용자명은 IP 형식이 아니어야 한다. 다른 사용자명을 골라라.',
'Username reserved chars'	=>	'사용자명은 \', ",  [, ] 를 가지면 안된다. 다른 사용자명을 골라라.',
'Username BBCode'			=>	'사용자명은 포럼에서 쓰이는 모든 형식 태그 (BBCode)를 가지면 안된다. 다른 사용자명을 골라라.',
'Banned username'			=>	'넣은 사용자명은 이 포럼에서 금지되었다. 다른 사용자명을 골라라.',
'Pass too short'			=>	'비밀번호는 적어도 4 characters 길이를 가져야 한다. 다른 (더 긴) 비밀번호를 골라라.',
'Pass not match'			=>	'비밀번호가 서로 맞지 않는다.',
'Banned email'				=>	'넣은 메일 주소는 이 포럼에서 금지되었다. 다른 메일 주소를 골라라.',
'Dupe email'				=>	'이 메일 주소로 다른 사람이 이미 가입했다. 다른 메일 주소를 골라라.',
'Sig too long'				=>	'서명은 %1$s characters 보다 길면 안된다. 서명을 %2$s characters 까지 줄여라.',
'Sig too many lines'		=>	'서명은 %s 줄을 넘을 수 없다.',
'Bad ICQ'					=>	'올바르지 않은 ICQ UIN를 넣었다. 되돌아가서 바르게 고쳐라.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Moscow, Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Yekaterinburg',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Krasnoyarsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita, Irkutsk',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Vladivostok',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Magadan',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands, Kamchatka',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
