<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'회원 찾기',
'No search permission'				=>	'찾기 기능을 쓸 권한이 없다.',
'Search flood'						=>	'찾기와 찾기 사이는 적어도 %s 초가 지나야 한다. 조금 기다렸다가 다시 찾기를 해보아라.',
'Search'							=>	'찾기',
'Search criteria legend'			=>	'찾기 기준을 넣어라',
'Search info'						=>	'키워드로 찾으려면 찾기위한 조건을 빈칸으로 나누어서 넣어라. 찾기를 깨끗하게 하기위해 AND, OR, NOT을 써라. 글쓴이로 찾으려면 찾으려는 글의 글쓴이를 넣어라. 부분 일치를 위해 와일드카드 문자 * 를 써라.',
'Keyword search'					=>	'키워드 찾기',
'Author search'						=>	'글쓴이 찾기',
'Search in legend'					=>	'찾을 곳을 골라라',
'Search in info'					=>	'찾을 포럼을 고르고 글타래의 제목이나 글귀로 찾을지 골라라.',
'Search multiple forums info'		=>	'포럼을 고르지 않으면, 모든 포럼에서 찾게 된다.',
'Forum search'						=>	'포럼',
'All forums'						=>	'모든 포럼',
'Search in'							=>	'찾기',
'Message and subject'				=>	'글귀와 글타래 제목',
'Message only'						=>	'글귀에서만',
'Topic only'						=>	'글타래 제목에서만',
'Sort by'							=>	'정렬하기',
'Sort order'						=>	'정렬순서',
'Search results legend'				=>	'찾기 결과를 볼 방법을 골라라',
'Search results info'				=>	'결과를 정렬하는 방법과 보는 방법을 고를 수 있다.',
'Sort by post time'					=>	'글 올린 시간',
'Sort by author'					=>	'글쓴이',
'Sort by subject'					=>	'제목',
'Sort by forum'						=>	'포럼',
'Ascending'							=>	'오름차순',
'Descending'						=>	'내림차순',
'Show as'							=>	'결과 보기',
'Show as topics'					=>	'글타래',
'Show as posts'						=>	'글',

// Results
'Search'							=>	'찾기',
//'Search results'					=>	'찾기 결과',
//'Search topics'						=>	'글타래 찾기',
'Search posts'						=>	'글 찾기',
'Quick search show_new'				=>	'새로운 글',
'Quick search show_recent'			=>	'살아있는 글',
'Quick search show_unanswered'		=>	'댓글없는 글',
'Quick search show_replies'			=>	'[sea]Posted',
'Quick search show_user_topics'		=>	'%s의 글타래',
'Quick search show_user_posts'		=>	'%s의 글',
'Quick search show_subscriptions'	=>	'Subscribed by %s',
'By keywords show as topics'		=>	'\'%s\' 글귀가 있는 글을 가진 글타래',
'By keywords show as posts'			=>	'\'%s\' 글귀가 있는 글',
'By user show as topics'			=>	'%s의 글이 있는 글타래',
'By user show as posts'				=>	'%s의 글',
'By both show as topics'			=>	'%2$s의 글 가운데에서, \'%1$s\' 글귀가 있는 글을 가진 글타래',
'By both show as posts'				=>	'%2$s의 글 가운데에서, \'%1$s\' 글귀가 있는 글',
'No terms'							=>	'찾기를 위해 적어도 하나의 키워드나 글쓴이를 넣어야 한다.',
'No hits'							=>	'찾은 것이 없다.',
'No user posts'						=>	'포럼에 이 회원이 쓴 글이 없다.',
'No user topics'					=>	'포럼에 이 회원이 쓴 글타래가 없다.',
'No subscriptions'					=>	'이 회원은 받아보는 글타래가 없다.',
'No new posts'						=>	'마지막 들른 뒤로 올라온 새로운 글이 있는 글타래가 없다.',
'No recent posts'					=>	'지난 24 시간 안에 올라온 새로운 글이 없다.',
'No unanswered'						=>	'포럼에 댓글없는 글이 없다.',
'Go to post'						=>	'글로 가기',
'Go to topic'						=>	'글타래로 가기'

);
