<?php

// Taaldefinities gebruikt in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'Kan niet controleren op update omdat \'allow_url_fopen\' is uitgeschakeld op dit systeem.',
'Upgrade check failed message'		=>	'Controleren op updates is gefaald om onbekende reden.',
'Running latest version message'	=>	'Je gebruikt de laatste versie van FluxBB.',
'New version available message'		=>	'Er is een nieuwe versie van FluxBB beschikbaar, je kan hem downloaden op %s.',
'Not available'						=>	'Niet beschikbaar',
'Forum admin head'					=>	'Forum administratie',
'NA'								=>	'NB',
'Welcome to admin'					=>	'Welkom op het FluxBB administratie controle paneel. Hier kan je het hele forum instellen. Enkele voorbeelden van wat je allemaal kan doen:',
'Welcome 1'							=>	'Orden categorieën en forums.',
'Welcome 2'							=>	'Stel je forum in.',
'Welcome 3'							=>	'Permissies aan gebruikers en gasten toekennen.',
'Welcome 4'							=>	'Bekijk IP statistieken van gebruikers.',
'Welcome 5'							=>	'Ban gebruikers.',
'Welcome 6'							=>	'Censureer woorden.',
'Welcome 7'							=>	'Stel groepen en promoties in.',
'Welcome 8'							=>	'Ruim je forum op.',
'Welcome 9'							=>	'Behandel gerapporteerde berichten.',
'About head'						=>	'Over FluxBB',
'FluxBB version label'				=>	'FluxBB versie',
'Check for upgrade'					=>	'Controleer op updates',
'FluxBB version data'				=>	'v%s - %s',
'Server statistics label'			=>	'Server statistieken',
'View server statistics'			=>	'Bekijk server statistieken voor dit forum',
'Support label'						=>	'Ondersteuning',
'Forum label'						=>	'Forum',
'IRC label'							=>	'IRC kanaal',

// Language definitions used in admin_statistics.php
'PHPinfo disabled message'			=>	'De PHP functie phpinfo() is uitgeschakelt op deze server.',
'Server statistics head'			=>	'Server statistieken',
'Server load label'					=>	'Server load',
'Server load data'					=>	'%s - %s gebruiker(s) online',
'Environment label'					=>	'Systeem',
'Environment data OS'				=>	'Besturingssysteem: %s',
'Show info'							=>	'Bekijk info',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Accelerator: %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Database',
'Database data rows'				=>	'Rijen: %s',
'Database data size'				=>	'Grootte: %s',
);
