<?php

// Taaldefinities gebruikt in admin_bans.php
$lang_admin_bans = array(

'No user message'			=>	'Er is geen member met deze gebruikersnaam. Als je en ban wilt instellen die niet gerelateerd is aan geen gebruikersnaam laat je dit veld leeg.',
'No user ID message'		=>	'Er is geen member met dit ID.',
'User is admin message'		=>	'De gebruiker %s is een admin en kan niet worden verbannen. Als je een admin wilt verbannen moet je hem in een andere gebruikersgroep verplaatsen.',
'User is mod message'		=>	'De gebruiker %s is een moderator en kan niet worden verbannen. Als je een admin wilt verbannen moet je hem in een andere gebruikersgroep verplaatsen.',
'Must enter message'		=>	'Je moet (minstens) een gebruikersnaam, IP of mailadres opgeven.',
'Cannot ban guest message'	=>	'De gebruiker \'Gast\' kan niet worden verbannen.',
'Invalid IP message'		=>	'Dit is een ongeldig IP adres.',
'Invalid e-mail message'	=>	'Dit mail adres (bv. gebruiker@domein.be) of het mail adres domein (bv. domein.be) is ongeldig.',
'Invalid date message'		=>	'Je hebt een ongeldige vervaldatum opgegeven.',
'Invalid date reasons'		=>	'Het formaat van een datum is JJJJ-MM-DD en moet minsens 1 dag later zijn.',
'Ban added redirect'		=>	'Ban toegevoegd. Doorverwijzen …' ,
'Ban edited redirect'		=>	'Ban bewerkt. Doorverwijzen …',
'Ban removed redirect'		=>	'Ban verwijderd. Doorverwijzen …',

'New ban head'				=>	'Nieuwe ban',
'Add ban subhead'			=>	'Ban toevoegen',
'Username label'			=>	'Gebruikersnaam',
'Username help'				=>	'De member die je wilt verbannen (niet-hoofdlettergevoelig).',
'Username advanced help'	=>	'De member die je wilt verbannen (niet-hoofdlettergevoelig). Op de volgende pagina kan je een IP adres of mail opgeven om ook te verhannen, laat die velden leeg als je dat niet wilt.',

'Ban search head'			=>	'Ban zoeken',
'Ban search subhead'		=>	'Geef zoekopdracht in',
'Ban search info'			=>	'Zoek naar verbannen members in de database. Je kan meerdere velden invullen om te zoeken. Jokertekens en sterretjes (*) zijn toegestaan. Om alle bans te weergeven laat je alle velden leeg.',
'Date help'					=>	'(jjjj-mm-dd)',
'Message label'				=>	'Reden',
'Expire after label'		=>	'Vervalt na',
'Expire before label'		=>	'Vervalt voor',
'Order by label'			=>	'Sorteer op',
'Order by username'			=>	'Gebruikersnaam',
'Order by ip'				=>	'IP',
'Order by e-mail'			=>	'Mail',
'Order by expire'			=>	'Vervaldatum',
'Ascending'					=>	'Oplopend',
'Descending'				=>	'Aflopend',
'Submit search'				=>	'Zoeken',

'E-mail label'				=>	'Email',
'E-mail help'				=>	'Het mail adres of mail domein dat je wilt verbannen (bv. naam@domein.be of domein.be). Bekijk "Verboden e-mailadressen toestaan" in Permissies voor meer info.',
'IP label'					=>	'IP adres',
'IP help'					=>	'Het IP adres of de IP-reeks die je wilt verbannen (bv. 150.11.110.1 of 150.11.110). Plaats een spatie tussen 2 adressen. Als een reeds ingevoerd IP adres al in de datbase staat wordt het laatste IP adres dat door de member is gebruikt gebruikt.',
'IP help link'				=>	'Klik %s om de IP statistieken te bekijken.',
'Ban advanced head'			=>	'Geavanceerde ban instellingen',
'Ban advanced subhead'		=>	'Verbannen met IP en mail adres',
'Ban message label'			=>	'Ban bericht',
'Ban message help'			=>	'Het bericht dat voor de verbanne member op het forum kot te staan.',
'Message expiry subhead'	=>	'Ban reden en vervaldatum',
'Ban IP range info'			=>	'Wees voorzichtig met het verbannen van IP-reeksen. Meerdere gebruikers kunnen binnen dezelfde IP-reeks vallen.',
'Expire date label'			=>	'Vervaldatum',
'Expire date help'			=>	'De datum waarop de ban automatisch vervlat (formaat: jjjj-mm-dd). Voer geen datum in om de ban handmatig te verwijderen.',

'Results head'				=>	'Zoek resultaten',
'Results username head'		=>	'Gebruikersnaam',
'Results e-mail head'		=>	'Mail',
'Results IP address head'	=>	'IP adres',
'Results expire head'		=>	'Vervalt',
'Results message head'		=>	'Reden',
'Results banned by head'	=>	'Verbannen door',
'Results actions head'		=>	'Acties',
'No match'					=>	'Geen resultaat',
'Unknown'					=>	'Onbekend',

);
