<?php

// Taaldefinities gebruikt in install.php

$lang_install = array(

'Choose install language'		=>	'Kies een taal',
'Choose install language info'	=>	'Dit past alleen de taal van de installatie procedure aan, die van het forum zelf kan later worden gewijzigd.',
'Install language'				=>	'Installeer taal',
'Change language'				=>	'Verander taal',
'Next'							=>	'Volgende',
'Already installed'				=>	'FluxBB is al geïnstalleerd en kan daarom dus niet nog maals worden geïnstalleerd. Klik <a href="index.php">hier</a> om verder te gaan.',
'You are running error'			=>	'Je gebruikt %1$s versie %2$s. FluxBB %3$s vereist minstens %1$s %4$s om goed te functioneren. Je moet je %1$s installatie update voordat je verder kan gaan.',
'My FluxBB Forum'				=>	'Mijn FluxBB Forum',
'Description'					=>	'Niemand kan je vertellen wat FluxBB is, je moet het zelf ontdekken.',
'Username 1'					=>	'Gebruikersnamen hebben een minimumlengte van 2 tekens.',
'Username 2'					=>	'Gebruikersnamen hebben een maximumlengte van 25 tekens.',
'Username 3'					=>	'De gebruikersnaam \'Gast\' is gereserveerd.',
'Username 4'					=>	'Een gebruikersnaam mag niet in de vorm van een IP-adres zijn.',
'Username 5'					=>	'Gebruikersnamen mogen \', " en [ of ] niet gebruiken.',
'Username 6'					=>	'Gebruikersnamen mogen geen BBcode bevatten die in dit forum worden gebruikt.',
'Short password'				=>	'Je wachtwoord moet minstens 4 tekens bevatten.',
'Passwords not match'			=>	'De wachtwoorden komen niet overeen.',
'Wrong email'					=>	'Het admin e-mail adres dat je hebt opgegeven komt niet overeen.',
'No board title'				=>	'Je moet een titel opgeven.',
'Error default language'		=>	'De gekozen taal lijkt niet te bestaan.',
'Error default style'			=>	'De gekozen template lijkt niet te bestaan.',
'No DB extensions'				=>	'Deze versie van PHP ondersteund geen database typen dat FluxBB ondersteund. PHP moet ondersteuning bieden voor MySQL, PostgreSQL of SQLite om FluxBB te installeren.',
'Administrator username'		=>	'Admin gebruikersnaam',
'Administrator password 1'		=>	'Admin wachtwoord 1',
'Administrator password 2'		=>	'Admin wachtwoord 2',
'Administrator email'			=>	'Admins mail adres',
'Board title'					=>	'Forum titel',
'Base URL'						=>	'Root URL (zonder slash aan het einde)',
'Required field'				=>	'dit is een verplicht veld.',
'FluxBB Installation'			=>	'FluxBB installatie',
'Welcome'						=>	'Welkom bij de installatie van FluxBB, vul onderstaande installatiegegevens in om FluxBB te installeren, indien je vragen hebt of tegen problemen aanloopt, raden wij je aan de documentatie te lezen of naar de FluxBB forums te gaan.',
'Install'						=>	'Installeer FluxBB %s',
'Errors'						=>	'De volgende problemen moeten worden hersteld:',
'Database setup'				=>	'Database setup',
'Info 1'						=>	'Alle informatie die we nodig hebben om een verbinding met de database te maken.',
'Info 1'						=>	'Vol onderstaande velden in om FluxBB toegang te geven tot een database, deze gegevens moeten correct zijn, anders kan FluxBB niet worden geïnstallerd.',
'Select database'				=>	'Selecteer je database typen',
'Info 2'						=>	'Selecteer een database, we ondersteunen SQLite, MySQL en PostgreSQL.',
'Database type'					=>	'Database type',
'Required'						=>	'(Verplicht)',
'Database hostname'				=>	'Geef je database server hostnaam',
'Info 3'						=>	'Je webhost zou deze informatie moeten kunnen geven als <code>localhost</code> niet werkt.',
'Database server hostname'		=>  'Database server hostnaam',
'Database enter name'			=>	'Geef de naam van je database',
'Info 4'						=>	'De naam van de database waarin je FluxBB wilt installeren.',
'Database name'					=>	'Database naam',
'Database enter informations'	=>	'Geef de database gebruikersnaam en het wachtwoord',
'Database username'				=>	'Database gebruikersnaam',
'Info 5'						=>	'Je MySQL gebruikersnaam en wachtwoord (negeer voor SQLite).',
'Database password'				=>	'Database wachtwoord',
'Database enter prefix'			=>	'Geef een prefix',
'Info 6'						=>	'Verander dit als je meerdere installaties van FluxBB draaien binnen dezelfde database (voorbeeld: abc_).',
'Table prefix'					=>	'Tabel voorvoegsel',
'Administration setup'			=>	'Administratie instellingen',
'Info 7'						=>	'Maak het aller eerste account op dit forum.',
'Info 8'						=>	'Je gebruikersnaam moet tussen de 2 en 25 tekens lang zijn. Je wachtwoord moet minstens 4 tekens lang zijn. Wachtwoorden zijn hoofdletter gevoelig.', 
'Info 9'						=>	'Wachtwoorden moeten minstens 4 tekens lang zijn en zijn hoofdletter gevoelig.',
'Password'						=>	'Wachtwoord',
'Confirm password'				=>	'Bevestig wachtwoord',
'Board setup'					=>	'Forum instellingen',
'Info 11'						=>	'Forum instellingen. Deze kunnen later altijd geweizigd worden.',
'General information'			=>	'Geef je forum een naam en beschrijving.',
'Board description'				=>	'Forum beschrijving (HTML)',
'Appearance'					=>	'Weergave',
'Info 15'						=>	'Kies een taal en stijl voor je forum.',
'Default language'				=>	'Standaard taal',
'Default style'					=>	'Standaard template',
'Start install'					=>	'Installeren',
'DB type not valid'				=>	'\'%s\' is geen correct datbase typen',
'Table prefix error'			=>	'Het tabel voorvoegsel \'%s\' bevat ongeldige tekens of is te lang. Het voorvoegsel mag de letters a tot z, alle getallen en _ bevatten. Het mag ook niet starten met een getal en heeft een maximum lengte van 40 tekens. Geef een ander voorvoegsel op.',
'Prefix reserved'				=>	'Het tabel voorvoegsel \'sqlite_\' is gereserveerd voor SQLite. Kies een ander voorvoegsel.',
'Existing table error'			=>	'Een tabel met de naam \'%susers\' is al in gebruik in database \'%s\'. Dit kan betekenen dan FluxBB al is geïnstalleerd of andere software gebruikt deze naam al. Om dit probleem op te lossen kan je het voorvoegsel aanpassen.',
'InnoDB off'					=>	'InnoDB is niet beschikbaar. Kies een andere database soort die geen ondersteuning voor InnoDB biedt.',
'Administrators'				=>	'Administrators',
'Administrator'					=>	'Administrator',
'Moderators'					=>	'Moderators',
'Moderator'						=>	'Moderator',
'Guests'						=>	'Gasten',
'Guest'							=>	'Gast',
'Members'						=>	'Gebruikers',
'Announcement'					=>	'Geef een aankondiging op.',
'Rules'							=>	'Geef regels op',
'Maintenance message'			=>	'Dit forum is momenteel niet beschikbaar door onderhoud, kom over enkele minuten nog eens terug.',
'Test post'						=>	'Test post',
'Message'						=>	'Als je hier naar kijkt (en ik denk dat je dat nu wel doet) is de installatie voor 100% voltooid en kan je aan de slag! Log in en ga naar het adminpaneel om je forum te configureren',
'Test category'					=>	'Test categorie',
'Test forum'					=>	'Test forum',
'This is just a test forum'		=>	'Dit is een test forum',
'Alert cache'					=>	'<strong>De cache map kan niet worden beschreven!</strong> Om FluxBB te laten werken moet de map <em>%s</em> beschrijfbaar zijn. Gebruik chmod om de permissies te wijzigen. Bij twijfel, chmod naar 0777.',
'Alert avatar'					=>	'<strong>De avatar map kan niet worden beschreven!</strong> Als je wilt dat gebruikers hun eigen avatars kunnen uploaden, moet je er voor zorgen dat de map <em>%s</em> beschrijfbaar is door PHP. Je kan er later voor kiezen om avatars in een andere map op te slaan (zie Admin/Opties). Gebruik chmod om de permissies te wijzigen. Bij twijfel, chmod naar 0777.',
'Alert upload'					=>	'<strong>Bestanden kunnen niet worden geüpload bij deze server!</strong> Als je wilt dat gebruikers hun eigen avatars kunnen uploaden, moet je er voor zorgen dat dat de instellingen in file_uploads correct zijn in PHP. Zodra het mogelijk is om avatars te uploaden, kan je dit weer uitschakelen bij Administratie/Opties/Features.',
'FluxBB has been installed'		=>	'FluxBB is geïnstalleerd, om de installatie af te ronden moet u de onderstaande stappen volgen.',
'Final instructions'			=>	'Een laatste stap',
'Info 17'						=>	'Om de installatie af te ronden moet je op onderstaande knop klikken om config.php te downloaden. Vervolgens moet je dit bestand uploaden naar de root map van je FluxBB installatie.',
'Info 18'						=>	'Zodra je config.php hebt geüpload is FluxBB volledig geïnstalleerd! Daarna kan je naar de <a href="index.php">forum index</a> gaan.',
'Download config.php file'		=>	'Download config.php',
'FluxBB fully installed'		=>	'FluxBB is met succes geïnstalleerd! Je kan nu naar de <a href="index.php">forum index</a> gaan.',

);
