<?php

// Taaldefinities gebruikt in profile.php en register.php
$lang_prof_reg = array(

'Email legend'				=>	'Geef een correct mail adres op',
'Email legend 2'			=>	'Geef en bevestig een correct mail adres',
'Localisation legend'		=>	'Bewerk de locatiegegevens',
'Time zone'					=>	'Tijd zone',
'Time zone info'			=>	'Om het forum de juiste tijd te laten weergeven is het belangrijk dat je de tijd zone waar je leeft opgeeft.',
'DST'						=>	'Daylight Savings Time is in effect (advance time by 1 hour).',
'Time format'				=>	'Tijd formaat',
'Date format'				=>	'Datum formaat',
'Default'					=>	'Standaard',
'Language'					=>	'Taal',
'Email setting info'		=>	'Geef aan of je wilt dat andere gebruikers je mail adres kunnen zien of niet. Geef ook aan of gebruikers toestemming hebben om je via het forum een mail te sturen.',
'Email setting 1'			=>	'Weergeef mail adres.',
'Email setting 2'			=>	'Verberg mail adres maar geef wel de optie om mails te sturen.',
'Email setting 3'			=>	'Verberg mail adres en geef geen optie om mails te sturen.',
'Privacy options legend'	=>	'Bewerk je privacy opties',
'Confirm pass'				=>	'Bevestig wachtwoord',

'Username too short'		=>	'Een gebruikersnaam moet minstens 2 tekens bevatten, kies een andere (langere) gebruikersnaam.',
'Username too long'			=>	'Een gebruikersnaam mag maximum 25 tekens bevatten, kies een andere (kortere) gebruikersnaam.',
'Username guest'			=>	'De gebruikersnaam gast is gereserveerd door het systeem, kies een andere gebruikersnaam.',
'Username IP'				=>	'Een gebruikersnaam mag geen IP adres zijn, kies een andere gebruikersnaam.',
'Username reserved chars'	=>	'Een gebruikersnaam mag geen \', " en [ of ] bevatten, kies een andere gebruikersnaam.',
'Username BBCode'			=>	'Een gebruikersnaam mag geen BBCode gebruiken die beschikbaar is op het forum, kies een andere gebruikersnaam.',
'Banned username'			=>	'De gebruikersnaam die je wilt registreren is verbannen op dit forum, kies een andere gebruikersnaam.',
'Pass too short'			=>	'Een wachtwoord moet minstens 4 tekens hebben, kies een ander (langer) wachtwoord.',
'Pass not match'			=>	'Wachtwoord komt niet overeen.',
'Banned email'				=>	'Het mail adres dat je gebruiker is verbannen van dit forum, kies een ander mail adres.',
'Dupe email'				=>	'Dit mail adres wordt al gebruikt door iemand, kies een ander mail adres.',
'Sig too long'				=>	'Je sig kan niet langer zijn dan %1$s tekens. Zorg ervoor dat je sig %2$s tekens korter wordt.',
'Sig too many lines'		=>	'Je sig mag maximum %s lijnen lang zijn.',
'Bad ICQ'					=>	'Je gaf een ongeldig ICQ UIN in. Ga terug en herstel de fout.',

'UTC-12:00'					=>	'(UTC-12:00) Internationale Datum Lijn (West)',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaï-Aleutian, Cook Eiland',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Eiland',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Eiland',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Eiland',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Centraal',
'UTC-05:00'					=>	'(UTC-05:00) Oost',
'UTC-04:00'					=>	'(UTC-04:00) Atlantica',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Centraal Groenland',
'UTC-02:00'					=>	'(UTC-02:00) Midden-Atlantica',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) West Europa, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Centraal Europa, West Afrika',
'UTC+02:00'					=>	'(UTC+02:00) Oost Europa, Centraal Afrika',
'UTC+03:00'					=>	'(UTC+03:00) Moskou, Oost Afrika',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Eiland, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, West Australië, Irkutsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern West Australië',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'					=>	'(UTC+09:30) Centraal Australië',
'UTC+10:00'					=>	'(UTC+10:00) Oost Australië, Vladivostok',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Eiland, Magadan',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Eiland',
'UTC+12:00'					=>	'(UTC+12:00) Nieuw Zeeland, Fiji, Kamchatka',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Eiland',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Eiland',
'UTC+14:00'					=>	'(UTC+14:00) Line Eiland'

);
