<?php

// Taaldefinities gebruikt in profile.php
$lang_profile = array(

// Navigatie
'Profile menu'					=>	'Profiel menu',
'Section essentials'			=>	'Algemeen',
'Section personal'				=>	'Persoonlijk',
'Section messaging'				=>	'E-mail adres',
'Section personality'			=>	'Avatar en sig',
'Section display'				=>	'Weergeven',
'Section privacy'				=>	'Privacy',
'Section admin'					=>	'Administratie',

// Diversen
'Username and pass legend'		=>	'Geef je gebruikersnaam en wachtwoord',
'Personal details legend'		=>	'Geef persoonlijke details',
'Contact details legend'		=>	'Geef een e-mail adres op',
'User activity'					=>	'Gebruikers activiteit',
'Paginate info'					=>	'Geef aan hoeveel posts en topics je wilt zien per pagina.',

// Wachtwoord
'Pass key bad'					=>	'Deze wachtwoord activatie sleutel is incorrect of verouderd. Vraag een nieuwe aanvraag aan om je wachtwoord te wijzigen. Als ook die poging niet lukt kan je een admin contacteren op',
'Pass updated'					=>	'Je wachtwoord is bijgewerkt. Je kan nu inloggen met je nieuwe wachtwoord.',
'Pass updated redirect'			=>	'Wachtwoord bijgewerkt. Doorverwijzen …',
'Wrong pass'					=>	'Fout oud wachtwoord.',
'Change pass'					=>	'Verander wachtwoord',
'Change pass legend'			=>	'Geef een nieuw wachtwoord op en bevestig.',
'Old pass'						=>	'Oud wachtwoord',
'New pass'						=>	'Nieuw wachtwoord',
'Confirm new pass'				=>	'Bevestig wachtwoord',
'Pass info'						=>	'Een wachtwoord moet minstens 4 tekens bevatten.',

// Mail
'Email key bad'					=>	'Deze e-mail activatie sleutel is incorrect of verouderd. Vraag een nieuwe aanvraag aan om je e-mail adres te wijzigen. Als ook die poging niet lukt kan je een admin contacteren op',
'Email updated'					=>	'Je e-mail adres is bijgewerkt.',
'Activate email sent'			=>	'Er is een e-mail verstuurd naar het opgegeven adres met instructies om het nieuwe adres te activeren. Als dit niet werkt kan je een admin contacteren op',
'Email legend'					=>	'Geef je nieuw e-mail adres op',
'Email instructions'			=>	'Er is een e-mail verstuurd naar je nieuw e-mail adres. Klik op de bijgevoegde link om je e-mail adres te wijzigen.',
'Change email'					=>	'Bewerk e-mail adres',
'New email'						=>	'Nieuwe e-mail',

// Avatar
'Avatars disabled'				=>	'De admin heeft ondersteuning voor avatars uitgeschakelt.',
'Too large ini'					=>	'De geselecteerde afbeelding was te groot. De avatar is niet geüpload.',
'Partial upload'				=>	'De geselecteerde afbeelding is deels geüpload. Probeer het opnieuw.',
'No tmp directory'				=>	'Het is niet gelukt om de afbeelding te verplaatsen naar de juiste map, probeer opnieuw.',
'No file'						=>	'Er is geen bestand geselecteerd.',
'Bad type'						=>	'Het bestandsformaat wordt niet ondersteund. Enkel jpg, png en gif afbeeldingen zijn toegestaan',
'Too wide or high'				=>	'De afbeelding die je probeerd te uploaden is breder of hoger dan wat is toegestaan',
'Too large'						=>	'De afbeelding die je probeerd te uploaden is groter dan wat is toegestaan',
'pixels'						=>	'pixels',
'bytes'							=>	'bytes',
'Move failed'					=>	'De server heeft de afbeelding niet kunnen opslaan. Contacteer een admin op',
'Unknown failure'				=>	'Er is een onbekend probleem, probeer het opnieuw.',
'Avatar upload redirect'		=>	'Avatar geüpload. Doorverwijzen …',
'Avatar deleted redirect'		=>	'Avatar verwijderd. Doorverwijzen …',
'Avatar desc'					=>	'Een avatar is een kleine afbeelding die wordt weergegeven onder je naam bij je posts. Ze mogen niet groter zijn dan',
'Upload avatar'					=>	'Upload een avatar',
'Upload avatar legend'			=>	'Geef een bestand op om te uplaoden',
'Delete avatar'					=>	'Verwijder avatar', // enkel voor admins
'File'							=>	'Bestand',
'Upload'						=>	'Upload', // verzenden

// Validatie
'Forbidden title'				=>	'De titel die je hebt opgegeven bevat een verboden woord, kies een andere titel',
'Profile redirect'				=>	'Profiel bijgewerkt. Doorverwijzen …',

// Profiel
'Users profile'					=>	'%s\'s profiel',
'Username info'					=>	'Gebruikersnaam: %s',
'Email info'					=>	'E-mail adres: %s',
'Posts info'					=>	'Posts: %s',
'Registered info'				=>	'Geregistreerd: %s',
'Last post info'				=>	'Laatste post: %s',
'Last visit info'				=>	'Laatste bezoek: %s',
'Show posts'					=>	'Bekijk alle posts',
'Show topics'					=>	'Bekijk alle topics',
'Show subscriptions'			=>	'Bekijk alle abonnementen',
'Realname'						=>	'Echte naam',
'Location'						=>	'Locatie',
'Website'						=>	'Website',
'Invalid website URL'			=>	'De website URL die je hebt opgegeven is niet geldig',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'Live Messenger',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'Avatar',
'Signature'						=>	'Sig',
'Sig max size'					=>	'Max lengte: %s tekens / Max aantal lijnen: %s',
'Avatar legend'					=>	'Bewerk je avatar opties',
'Avatar info'					=>	'Een avatar is een kleine afbeelding die wordt weergegeven onder je naam bij je posts. Je kan een avatar uploaden door op de volgende link te klikken.',
'Change avatar'					=>	'Bewerk avatar',
'Signature legend'				=>	'Bewerk je sig',
'Signature info'				=>	'Een sig is een klein stukje tekst (signature = handtekening) dat onder je posts wordt weergegeven. Je kan er in schrijven wat je maar wil: bijvoorbeeld een citaat, welke films je leuk vind, enz. Het is jou keuze! Je kan BBCode gebruiken indien dit is toegestaan door de forum admin. De opties die toegestaan zijn vind je altijd van onder tijdens het bewerken en bekijken.',
'Sig preview'					=>	'Voorbeeld van sig:',
'No sig'						=>	'Er is geen sig aan jou profiel gekoppelt.',
'Signature quote/code/list/h'	=>	'BBCodes zijn niet toegestaan in sigs.',
'Topics per page'				=>	'Topics',
'Posts per page'				=>	'Posts',
'Leave blank'					=>	'Laat leeg om standaard instellingen te gebruiken.',
'Subscription legend'			=>	'Bewerk je abonnements opties',
'Notify full'					=>	'Voeg een text-only versie toe in e-mails over abonnementen op topics.',
'Auto notify full'				=>	'Abonneer automatisch op iedere topic waarin je reageerd.',
'Show smilies'					=>	'Weergeef emoticons als afbeeldingen.',
'Show images'					=>	'Weergeef afbeeldingen in posts.',
'Show images sigs'				=>	'Weergeef afbeeldingen in sigs.',
'Show avatars'					=>	'Weergeef avatar bij posts.',
'Show sigs'						=>	'Weergeef sigs in topics.',
'Style legend'					=>	'Kies een template',
'Styles'						=>	'Templates',
'Admin note'					=>	'Admin nota',
'Pagination legend'				=>	'Bewerk je pagina opties',
'Post display legend'			=>	'Bewerk de opties omtrend het weergeven van posts',
'Post display info'				=>	'Als je werkt met een trage internetverbinding, raden we aan deze optie op verbergen te zetten, afbeeldingen zullen niet worden getoond waardoor een pagina sneller worden geladen.',
'Instructions'					=>	'Als je je profiel bewerkt, wordt je doorverwezen naar deze pagina.',

// Administratie
'Group membership legend'		=>	'Kies gebruikersgroep',
'Save'							=>	'Opslaan',
'Set mods legend'				=>	'Bewerk mod toegang',
'Moderator in info'				=>	'Kies welke forums deze gebruiker mag modereren. Opmerking: Admins hebben altijd alle rechten.',
'Update forums'					=>	'Update forums',
'Delete ban legend'				=>	'Verwijder (enkel voor admins) of verban gebruikers',
'Delete user'					=>	'Verwijder gebruiker',
'Ban user'						=>	'Verban gebruiker',
'Confirm delete legend'			=>	'Belangrijk: lees dit voor je een gebruiker verwijderd',
'Confirm delete user'			=>	'Bevestig het verwijderen van deze gebruiker',
'Confirmation info'				=>	'Bevestig dat je deze gebruiker wilt verwijderen',
'Delete warning'				=>	'Waarschuwing! Het verwijderen van een gebruiker en/of diens posts kan niet worden terug gedraaid. Indien je een gebruiker verwijderd zonder zijn posts te verwijderen kunnen de posts enkel manueel worden verwijderd.',
'Delete posts'					=>	'Verwijder alle posts en topic die gemaakt zijn door deze gebruiker.',
'Delete'						=>	'Verwijderen', // submit knop
'User delete redirect'			=>	'Gebruiker verwijderd. Doorverwijzen …',
'Group membership redirect'		=>	'Groep lidmaatschap verwijderd. Doorverwijzen …',
'Update forums redirect'		=>	'Mod rechten bijgewerkt. Doorverwijzen …',
'Ban redirect'					=>	'Doorverwijzen …',
'No delete admin message'		=>	'Admins kunnen niet worden verwijderd. Om dit toch te doen moet de gebruikersgroep van deze admin eerst worden aangepast.',

);
