<?php
// Taaldefinities gebruikt in search.php
$lang_search = array(

// Zoek veld
'User search'						=>	'Gebruiker zoeken',
'No search permission'				=>	'Je hebt niet het recht om de zoekmachine te gebruiken.',
'Search flood'						=>	'Je moet minstens %s seconden wachten tussen verschillende zoekopdrachten. Wacht even en probeer opnieuw.',
'Search'							=>	'Zoeken',
'Search criteria legend'			=>	'Geef een zoekopdracht',
'Search info'						=>	'Geef &#233;&#233;n of meerdere zoektermen op. Splits verschillende termen met een spatie. Geef een naam op om op gebruikers te zoeken.',
'Keyword search'					=>	'Zoekterm',
'Author search'						=>	'Gebruiker',
'Search in legend'					=>	'Kies waar er moet worden gezocht',
'Search in info'					=>	'Kies in welke forums er mag worden gezocht en of dit enkel in het onderwerp of bericht of allebei mag.',
'Search multiple forums info'		=>	'Als je geen forum kiest, worden alle forums doorzocht.',
'Forum search'						=>	'Forum',
'All forums'						=>	'Alle forums',
'Search in'							=>	'Zoek in',
'Message and subject'				=>	'Berichten en onderwerpen',
'Message only'						=>	'Enkel berichten',
'Topic only'						=>	'Enkel onderwerpen',
'Sort by'							=>	'Sorteer op',
'Sort order'						=>	'Volgorde',
'Search results legend'				=>	'Kies hoe de resultaten moeten worden weergegeven',
'Search results info'				=>	'Je kan hier kiezen hoe de resultaten moeten worden gerangschikt.',
'Sort by post time'					=>	'Tijd',
'Sort by author'					=>	'Auteur',
'Sort by subject'					=>	'Onderwerp',
'Sort by forum'						=>	'Forum',
'Ascending'							=>	'Oplopend',
'Descending'						=>	'Aflopend',
'Show as'							=>	'Weergeef resultaten als',
'Show as topics'					=>	'Topics',
'Show as posts'						=>	'Posts',

// Resultaten
'Search'							=>	'Zoeken',
'Search results'					=>	'Zoekresultaten',
'Quick search show_new'				=>	'Nieuw',
'Quick search show_recent'			=>	'Actief',
'Quick search show_unanswered'		=>	'Onbeantwoord',
'Quick search show_replies'			=>	'Posts',
'Quick search show_user_topics'		=>	'Topics van %s',
'Quick search show_user_posts'		=>	'Posts ban %s',
'Quick search show_subscriptions'	=>	'Abbonement van %s',
'By keywords show as topics'		=>	'Topics met posts over \'%s\'',
'By keywords show as posts'			=>	'Berichten over \'%s\'',
'By user show as topics'			=>	'Topics met berichten van %s',
'By user show as posts'				=>	'Posts van %s',
'By both show as topics'			=>	'Topics of posts met berichten van \'%s\', by %s',
'By both show as posts'				=>	'Posts van \'%s\', by %s',
'No terms'							=>	'Je moet minstens 1 zoekterm of gebruiker ingeven om op te zoeken.',
'No hits'							=>	'Geen resultaten gevonden.',
'No user posts'						=>	'Er zijn geen posts van deze gebruiker in dit forum.',
'No user topics'					=>	'Er zijn geen topics van deze gebruiker in dit forum.',
'No subscriptions'					=>	'Deze gebruiker heeft momenteel geen abonnement in dit forum.',
'No new posts'						=>	'Er zijn geen topics met nieuwe berichten sinds je laatste bezoek.',
'No recent posts'					=>	'Er zijn geen nieuwe posts gemaakt in de laatste 24 uur.',
'No unanswered'						=>	'Er zijn geen onbeantwoorde topics.',
'Go to post'						=>	'Ga naar post',
'Go to topic'						=>	'Ga naar topic'

);
