<?php

// Language definitions used in admin-users.php
$lang_admin_users = array(

'Non numeric message'			=>	'Vous avez indiqué une valeur non numérique dans une colonne n\'acceptant que des valeurs numériques.',
'Invalid date time message'		=>	'Vous avez indiqué une date, un horaire invalide.',
'Not verified'				=>	'Non vérifié',
'User search head'			=>	'Recherche d\'utilisateur',
'User search subhead'			=>	'Indiquer les critères de recherche',
'User search info'			=>	'Rechercher des utilisateurs dans la base de données. Vous pouvez indiquer un ou plusieurs termes à rechercher. Les jokers sous forme d\'astérisques (*) sont acceptés.',
'Username label'			=>	'Nom d\'utilisateur',
'E-mail address label'			=>	'Adresse électronique',
'Title label'				=>	'Titre',
'Real name label'			=>	'Nom réel',
'Website label'				=>	'Site Web',
'Jabber label'				=>	'Jabber',
'ICQ label'				=>	'ICQ',
'MSN label'				=>	'MSN Messenger',
'AOL label'				=>	'AOL IM',
'Yahoo label'				=>	'Yahoo Messenger',
'Location label'			=>	'Lieu',
'Signature label'			=>	'Signature',
'Admin note label'			=>	'Note d\'administrateur',
'Posts more than label'			=>	'Nombre de messages supérieur à',
'Posts less than label'			=>	'Nombre de messages inférieur à',
'Last post after label'			=>	'Dernier message publié après',
'Date help'				=>	'(dd-mm-yyyy hh:mm:ss)',
'Last post before label'		=>	'Dernier message publié avant',
'Registered after label'		=>	'Inscrit après',
'Registered before label'		=>	'Inscrit avant',
'Order by label'			=>	'Trier par&#160;…',
'Order by username'			=>	'nom d\'utilisateur',
'Order by e-mail'			=>	'e-mail',
'Order by posts'			=>	'nombre de messages',
'Order by last post'			=>	'dernier message',
'Order by registered'			=>	'inscrit',
'Ascending'				=>	'ascendant',
'Descending'				=>	'descendant',
'User group label'			=>	'Groupe d\'utilisateurs',
'All groups'				=>	'Tous les groupes',
'Unverified users'			=>	'Utilisateurs non vérifiés',
'Submit search'				=>	'Lancer la recherche',
'IP search head'			=>	'Recherche d\'IP',
'IP search subhead'			=>	'Indiquer l\'IP à rechercher',
'IP address label'			=>	'Adresse IP',
'IP address help'			=>	'L\'adresse IP à rechercher dans la base de données des messages.',
'Find IP address'			=>	'Rechercher l\'adresse IP',

'Results head'				=>	'Utilisateurs',
'Results username head'			=>	'Nom d\'utilisateur',
'Results e-mail head'			=>	'E-mail',
'Results title head'			=>	'Identité/état',
'Results posts head'			=>	'Messages',
'Results admin note head'		=>	'Note d\'administrateur',
'Results actions head'			=>	'Actions',
'Results IP address head'		=>	'Adresse IP',
'Results last used head'		=>	'Récemment utilisée',
'Results times found head'		=>	'Nombre de fois trouvé',
'Results action head'			=>	'Action',
'Results find more link'		=>	'Trouver davantage d\'utilisateurs pour cette IP',
'Results no posts found'		=>	'Aucun message n\'a été publié par cet utilisateur dans ce forum pour le moment.',
'Bad IP message'			=>	'L\'adresse IP indiquée n\'est pas correctement formatée.',
'Results view IP link'			=>	'Afficher les stats IP',
'Results show posts link'		=>	'Afficher les messages',
'Results guest'				=>	'Invité',
'Results no IP found'			=>	'L\'adresse IP indiquée est introuvable dans la base de données.',
'No match'				=>	'Aucune correspondance'

);