<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'		=>	'Impossible de vérifier la présence de nouvelles mises à jour puisque l\'option «&#160;allow_url_fopen&#160;» est désactivée sur ce système.',
'Upgrade check failed message'		=>	'La vérification de nouvelles mises à jour a échoué pour des raisons inconnues.',
'Running latest version message'	=>	'Vous utilisez la version la plus récente de FluxBB.',
'New version available message'		=>	'Une nouvelle version de FluxBB est disponible. Vous pouvez télécharger cette version ici&#160;: %s.',
'PHPinfo disabled message'		=>	'La fonction PHP phpinfo() a été désactivée sur ce serveur.',
'Not available'				=>	'Non disponible',
'Forum admin head'			=>	'Administration du forum',
'NA'					=>	'N/A',
'Welcome to admin'			=>	'Bienvenue dans le panneau d\'administration de FluxBB. À partir d\'ici vous pouvez gérer les aspects vitaux du forum. Selon que vous êtes administrateur ou modérateur, vous pouvez',
'Welcome 1'				=>	'Organiser les catégories et forums.',
'Welcome 2'				=>	'Définir les options et préférences pour chaque forum.',
'Welcome 3'				=>	'Gérer les permissions pour les utilisateurs et les invités.',
'Welcome 4'				=>	'Afficher les statistiques IP des utilisateurs.',
'Welcome 5'				=>	'Bannir des utilisateurs.',
'Welcome 6'				=>	'Censurer des mots.',
'Welcome 7'				=>	'Paramétrer les rangs d\'utilisateurs.',
'Welcome 8'				=>	'Supprimer d\'anciens messages.',
'Welcome 9'				=>	'Traiter les signalements de messages.',
'Statistics head'			=>	'Statistiques',
'FluxBB version label'			=>	'Version de FluxBB',
'Check for upgrade'			=>	'Vérification pour mise à niveau',
'FluxBB version data'			=>	'v%s - %s',
'Server load label'			=>	'Charge du serveur',
'Server load data'			=>	'%s - %s utilisateur(s) en ligne',
'Environment label'			=>	'Environnement',
'Environment data OS'			=>	'Système d\'exploitation&#160;: %s',
'Show info'				=>	'Afficher les infos',
'Environment data version'		=>	'PHP : %s - %s',
'Environment data acc'			=>	'Accélérateur&#160;: %s',
'Turck MMCache'				=>	'Turck MMCache',
'Turck MMCache link'			=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'		=>	'Accélérateur PHP ionCube PHP',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Cache alternatif PHP (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'			=>	'Optimiseur Zend',
'Zend Optimizer link'			=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'				=>	'eAccelerator',
'eAccelerator link'			=>	'www.eaccelerator.net/',
'XCache'				=>	'XCache',
'XCache link'				=>	'xcache.lighttpd.net/',
'Database label'			=>	'Base de données',
'Database data rows'			=>	'Lignes&#160;: %s',
'Database data size'			=>	'Taille&#160;: %s',

);