<?php

// Language definitions used in profile.php
$lang_profile = array(
 
// Navigation and sections
'Profile menu'			=>	'Menu profil',
'Section essentials'		=>	'Principal',
'Section personal'		=>	'Personnel',
'Section messaging'		=>	'Messagerie',
'Section personality'		=>	'Personnalité',
'Section display'		=>	'Affichage',
'Section privacy'		=>	'Vie privée',
'Section admin'			=>	'Administration',
 
// Miscellaneous
'Username and pass legend'	=>	'Nom d\'utilisateur et mot de passe',
'Personal details legend'	=>	'Informations personnelles',
'Contact details legend'	=>	'Informations sur les messageries instantanées',
'User activity'			=>	'Activité de l\'utilisateur',
'Paginate info'			=>	'Nombres de discussions et de messages à afficher par page.',
 
// Password stuff
'Pass key bad'			=>	'La clef d\'activation du mot de passe est incorrecte ou a expiré. Veuillez demander un nouveau mot de passe. Si cela ne marche pas, contactez l\'administrateur.',
'Pass updated'			=>	'Votre mot de passe a été mis à jour. Vous pouvez à présent vous identifier avec votre nouveau mot de passe.',
'Pass updated redirect'		=>	'Mot de passe mis à jour. Redirection&#160;…',
'Wrong pass'			=>	'Ancien mot de passe incorrect.',
'Change pass'			=>	'Changer de mot de passe',
'Change pass legend'		=>	'Saisissez et confirmez votre mot de passe',
'Old pass'			=>	'Ancien mot de passe',
'New pass'			=>	'Nouveau mot de passe',
'Confirm new pass'		=>	'Confirmez le nouveau mot de passe',
'Pass info'			=>	'Les mots de passe doivent comporter au moins 4 caractères. Ils sont sensibles à la casse.',
 
// E-mail stuff
'Email key bad'			=>	'La clef d\'activation d\'adresse électronique est incorrecte ou a expiré. Veuillez demander à nouveau un changement d\'adresse électronique. Si cela échoue, contactez l\'administrateur',
'Email updated'			=>	'Votre adresse électronique a été mise à jour.',
'Activate email sent'		=>	'Un e-mail comportant les instructions pour activer la nouvelle adresse électronique a été envoyé. S\'il n\'arrive pas, contactez l\'administrateur&#160;: ',
'Email legend'			=>	'Saisissez la nouvelle adresse électronique',
'Email instructions'		=>	'Indiquez la nouvelle adresse électronique. Un e-mail comportant un lien d\'activation y sera envoyé. Vous devrez cliquer sur ce lien pour activer l\'adresse.',
'Change email'			=>	'Changer l\'adresse électronique',
'New email'			=>	'Nouvelle adresse électronique',
 
// Avatar upload stuff
'Avatars disabled'		=>	'La prise en charge des avatars est désactivée.',
'Too large ini'			=>	'Fichier trop volumineux. Le serveur refuse son envoi.',
'Partial upload'		=>	'Fichier partiellement envoyé. Merci de réessayer.',
'No tmp directory'		=>	'Le serveur n\'a pas pu enregistrer temporairement le fichier envoyé.',
'No file'			=>	'Vous n\'avez pas sélectionné de fichier à envoyer.',
'Bad type'			=>	'Ce type de fichier n\'est pas autorisé. Voici les formats pris en charge&#160;:  *.gif, *.jpeg et *.png.',
'Too wide or high'		=>	'L\'image est plus large et/ou plus haute que le maximum autorisé',
'Too large'			=>	'La taille du fichier dépasse le maximum autorisé',
'pixels'			=>	'pixels',
'bytes'				=>	'octets',
'Move failed'			=>	'Le serveur n\'a pas pu enregistrer le fichier envoyé. Contactez l\'administrateur',
'Unknown failure'		=>	'Erreur inconnue. Merci de réessayer.',
'Avatar upload redirect'	=>	'Avatar envoyé. Redirection&#160;…',
'Avatar deleted redirect'	=>	'Avatar effacé. Redirection&#160;…',
'Avatar desc'			=>	'Un avatar est une petite image qui sera affichée sous votre nom d\'utilisateur dans vos messages. Il ne doit pas faire plus de',
'Upload avatar'			=>	'Envoyer un avatar',
'Upload avatar legend'		=>	'Sélectionnez un fichier avatar à envoyer',
'Delete avatar'			=>	'Effacer l\'avatar',	// only for admins
'File'				=>	'Fichier',
'Upload'			=>	'Envoyer',	// submit button
 
// Form validation stuff
'Forbidden title'		=>	'Votre titre contient un mot interdit. Choisissez un autre titre.',
'Profile redirect'		=>	'Profil mis à jour. Redirection&#160;…',
 
// Profile display stuff
'Users profile'			=>	'Profil de %s',
'Username info'			=>	'Nom d\'utilisateur&#160;: %s',
'Email info'			=>	'E-mail&#160;: %s',
'Posts info'			=>	'Messages&#160;: %s',
'Registered info'		=>	'Inscription&#160;: %s',
'Last post info'		=>	'Dernier message&#160;: %s',
'Last visit info'               =>      'Dernière visite&#160;: %s',
'Show posts'			=>	'Voir les messages de cet utilisateur',
'Show topics'			=>	'Afficher toutes les discussions',
'Show subscriptions'		=>	'Afficher toutes les discussions suivies',
'Realname'			=>	'Nom',
'Location'			=>	'Lieu',
'Website'			=>	'Site Web',
'Invalid website URL'          =>  'L\'URL de site Web saisie est invalide.',
'Jabber'			=>	'Jabber',
'ICQ'				=>	'ICQ',
'MSN'				=>	'MSN Messenger',
'AOL IM'			=>	'AOL IM',
'Yahoo'				=>	'Yahoo! Messenger',
'Avatar'			=>	'Avatar',
'Signature'			=>	'Signature',
'Sig max size'			=>	'%s caractères et %s lignes autorisés',
'Avatar legend'			=>	'Définissez vos options d\'affichage d\'avatar',
'Avatar info'			=>	'Un avatar est une petite image qui sera affichée avec chacun de vos messages. Vous pouvez envoyer un avatar en cliquant sur le lien ci-dessous.',
'Change avatar'			=>	'Changer d\'avatar',
'Signature legend'		=>	'Rédigez votre signature',
'Signature info'		=>	'Une signature est un petit texte ajouté à la suite de vos messages. Vous pouvez y inclure ce que vous voulez et y utiliser des balises BBCode, selon la configuration du forum. Les fonctionnalités actives apparaissent dans la marge lors de l\'édition de votre signature.',
'Sig preview'			=>	'Aperçu de la signature actuelle&#160;:',
'No sig'			=>	'Pas de signature dans le profil.',
'Signature quote/code/list/h'	=>	'L\'utilisation des balises BBCode [quote], [code], [list] et [h] n\'est pas autorisée dans les signatures.',
'Topics per page'		=>	'Discussions par page',
'Posts per page'		=>	'Messages par page',
'Leave blank'			=>	'Laisser vide pour utiliser la valeur par défaut du forum.',
'Subscription legend'	        =>	'Définit vos options de suivi de discussion',
'Notify full'			=>	'Inclure le message dans les e-mails de notification de réponse.',
'Auto notify full'		=>	'Suivre automatiquement les sujets auxquels on a répondu.',
'Show smilies'			=>	'Afficher les émoticônes sous forme d\'icônes',
'Show images'			=>	'Afficher les images.',
'Show images sigs'		=>	'Afficher les images dans les signatures des utilisateurs.',
'Show avatars'			=>	'Afficher les avatars des utilisateurs.',
'Show sigs'			=>	'Afficher les signatures.',
'Style legend'			=>	'Choisissez votre style favori',
'Styles'			=>	'Styles',
'Admin note'			=>	'Note de l\'administrateur',
'Pagination legend'		=>	'Définissez vos options de pagination',
'Post display legend'		=>	'Définissez vos options de visualisation des messages',
'Post display info'		=>	'En désactivant toutes les options d\'affichage des images et des signatures dans les messages, vous augmenterez la vitesse de chargement des pages.',
'Instructions'			=>	'Après avoir mis à jour le profil vous serez redirigé(e) vers cette page.',
 
// Administration stuff
'Group membership legend'	=>	'Choisissez un groupe d\'utilisateurs',
'Save'				=>	'Enregistrer',
'Set mods legend'		=>	'Définir l\'accès modérateur',
'Moderator in info'		=>	'Veuillez choisir les forums que cet utilisateur peut modérer. Remarque&#160;:  Ceci s\'applique seulement aux modérateurs. Les administrateurs ont toujours toutes les permissions pour tous les forums.',
'Update forums'			=>	'Mettre à jour',
'Delete ban legend'		=>	'Supprimer (administrateurs seulement) ou bannir un utilisateur',
'Delete user'			=>	'Supprimer l\'utilisateur',
'Ban user'			=>	'Bannir l\'utilisateur',
'Confirm delete legend'		=>	'Important&#160;: lisez avant de supprimer un utilisateur',
'Confirm delete user'		=>	'Confirmer la suppression de l\'utilisateur',
'Confirmation info'		=>	'Veuillez confirmer la suppression de l\'utilisateur',	// the username will be appended to this string
'Delete warning'		=>	'Attention&#160;! Les utilisateurs et/ou messages supprimés ne peuvent être récupérés. Si vous choisissez de ne pas supprimer les messages d\'un utilisateur, les messages pourront uniquement être supprimés manuellement plus tard.',
'Delete posts'			=>	'Supprimer tous les messages ou discussions de cet utilisateur.',
'Delete'			=>	'Supprimer',		// submit button (confirm user delete)
'User delete redirect'		=>	'Utilisateur supprimé. Redirection&#160;…',
'Group membership redirect'	=>	'Appartenance à un groupe enregistrée. Redirection&#160;…',
'Update forums redirect'	=>	'Droits du modérateur mis à jour. Redirection&#160;…',
'Ban redirect'			=>	'Redirection&#160;…',
'No delete admin message'	=>	'Les administrateurs ne peuvent être supprimés. Pour supprimer cet utilisateur, vous devez d\'abord le/la déplacer vers un groupe d\'utilisateurs différent.',
 
);