<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(
 
'Email legend'			=>	'Indiquez une adresse électronique valide',
'Email legend 2'		=>	'Saisissez et confirmez une adresse électronique valide',
'Localisation legend'		=>	'Définissez vos options géographiques',
'Time zone'			=>	'Fuseau horaire&#160;',
'Time zone info'		=>	'Afin que le forum affiche correctement l\'heure, vous devez sélectionner votre fuseau horaire.',
'DST'				=>	'Ajustement pour l\'heure d\'été&#160;: cochez cette case si nécessaire pour que les forums affichent correctement l\'heure.',
'Time format'			=>	'Format de l\'heure',
'Date format'			=>	'Format de la date',
'Default'			=>	'Par défaut',
'Language'			=>	'Langue&#160;',
'Email setting info'		=>	'Indiquez si vous souhaitez que votre adresse électronique soit visible par les autres utilisateurs ou non et si vous voulez que les autres utilisateurs puissent vous envoyer des e-mails via ces forums (formulaire d\'envoi d\'e-mail) ou non.',
'Email setting 1'		=>	'Divulguer votre adresse électronique.',
'Email setting 2'		=>	'Masquer votre adresse électronique mais autoriser l\'envoi via le formulaire d\'envoi d\'e-mail.',
'Email setting 3'		=>	'Masquer votre adresse électronique et interdire l\'utilisation du formulaire d\'envoi d\'e-mail.',
'Privacy options legend'	=>	'Définissez vos options de vie privée',
'Confirm pass'			=>	'Confirmez votre mot de passe',
 
'Username too short'		=>	'Les noms d\'utilisateur doivent comporter au moins 2 caractères. Veuillez choisir un autre nom d\'utilisateur.',
'Username too long'		=>	'Les noms d\'utilisateur ne doivent pas comporter plus de 25 caractères. Veuillez choisir un autre nom d\'utilisateur.',
'Username guest'		=>	'Le nom d\'utilisateur «&#160;invité&#160;» est réservé. Veuillez choisir un autre nom d\'utilisateur.',
'Username IP'			=>	'Les noms d\'utilisateur ne peuvent pas être au format d\'une adresse IP. Veuillez choisir un autre nom d\'utilisateur.',
'Username reserved chars'	=>	'Les noms d\'utilisateurs ne peuvent pas contenir les caractères \', " et [ ou ]. Veuillez choisir un autre nom d\'utilisateur.',
'Username BBCode'		=>	'Les noms d\'utilisateur ne peuvent pas contenir de balises (BBCode). Veuillez choisir un autre nom d\'utilisateur.',
'Banned username'		=>	'Le nom d\'utilisateur que vous avez indiqué est banni. Veuillez choisir un autre nom d\'utilisateur.',
'Pass too short'		=>	'Les mots de passe doivent comporter au moins 4 caractères. Veuillez choisir un autre mot de passe.',
'Pass not match'		=>	'Les mots de passe ne coïncident pas. Veuillez recommencer.',
'Banned email'			=>	'L\'adresse électronique saisie est bannie de ces forums. Veuillez en choisir une autre.',
'Dupe email'			=>	'Cette adresse électronique est déjà utilisée. Veuillez en choisir une autre.',
'Sig too long'			=>	'Les signatures ne peuvent pas contenir plus de %1$s caractères. Veuillez raccourcir votre signature de %2$s caractères.',
'Sig too many lines'		=>	'Les signatures ne peuvent pas comporter plus de %s lignes.',
'Bad ICQ'			=>	'Vous avez saisi un UIN ICQ invalide. Merci de corriger.',

'UTC-12:00'			=>	'(UTC-12:00) Ligne de changement de date OUEST',
'UTC-11:00'			=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'			=>	'(UTC-10:00) Hawaii et des îles Aléoutiennes, Îles Cook',
'UTC-09:30'			=>	'(UTC-09:30) Îles Marquises',
'UTC-09:00'			=>	'(UTC-09:00) Alaska, Îles Gambier',
'UTC-08:30'			=>	'(UTC-08:30) Îles Pitcairn',
'UTC-08:00'			=>	'(UTC-08:00) Pacifique',
'UTC-07:00'			=>	'(UTC-07:00) Montagnes, les Rocheuses',
'UTC-06:00'			=>	'(UTC-06:00) Centre',
'UTC-05:00'			=>	'(UTC-05:00) Est',
'UTC-04:00'			=>	'(UTC-04:00) Atlantique',
'UTC-03:30'			=>	'(UTC-03:30) Terre-Neuve',
'UTC-03:00'			=>	'(UTC-03:00) Amazone, Centre du Groenland',
'UTC-02:00'			=>	'(UTC-02:00) Milieu de l\'Atlantique',
'UTC-01:00'			=>	'(UTC-01:00) Açores, Cap Vert, Groenland de l\'Est',
'UTC'				=>	'(UTC) Europe Occidentale, Greenwich',
'UTC+01:00'			=>	'(UTC+01:00) Europe Centrale, Afrique Occidentale',
'UTC+02:00'			=>	'(UTC+02:00) Europe de l\'Est, Afrique Centrale',
'UTC+03:00'			=>	'(UTC+03:00) Afrique Orientale',
'UTC+03:30'			=>	'(UTC+03:30) Iran',
'UTC+04:00'			=>	'(UTC+04:00) Moscou, Golf, Samara',
'UTC+04:30'			=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'			=>	'(UTC+05:00) Pakistan',
'UTC+05:30'			=>	'(UTC+05:30) Inde, Sri Lanka',
'UTC+05:45'			=>	'(UTC+05:45) Népal',
'UTC+06:00'			=>	'(UTC+06:00) Bangladesh, Bhutan, Iekaterinbourg',
'UTC+06:30'			=>	'(UTC+06:30) Îles Cocos, Myanmar',
'UTC+07:00'			=>	'(UTC+07:00) Indochine, Novosibirsk',
'UTC+08:00'			=>	'(UTC+08:00) Grande Chin, Australie occidentale, Krasnoyarsk',
'UTC+08:45'			=>	'(UTC+08:45) Australie occidentale',
'UTC+09:00'			=>	'(UTC+09:00) Japon, Corée, Chine, Irkutsk',
'UTC+09:30'			=>	'(UTC+09:30) Australie Méridionale',
'UTC+10:00'			=>	'(UTC+10:00) Australie Orientale',
'UTC+10:30'			=>	'(UTC+10:30) Île Lord Howe',
'UTC+11:00'			=>	'(UTC+11:00) Île Salomon, , Vladivostok',
'UTC+11:30'			=>	'(UTC+11:30) Île Norfolk',
'UTC+12:00'			=>	'(UTC+12:00) Nouvelle Zélande, Fiji, Magadan',
'UTC+12:45'			=>	'(UTC+12:45) Îles Chatham',
'UTC+13:00'			=>	'(UTC+13:00) Tonga, Îles Phoenix, Kamchatka',
'UTC+14:00'			=>	'(UTC+14:00) Îles de la Ligne',

);