<?php
//**** [modif oto] File lang/French/search.php modified ****
//by the content of file lang/French/modif_oto/search_oto.php

$lang_search = array (
  'Ascending' => 'Croissant',
  'Author search' => 'Rechercher un auteur',
  'By both show as posts' => 'Messages de %s contenant «&#160;%s&#160;»',
  'By both show as topics' => 'Discussions avec messages de %s contenant «&#160;%s&#160;»',
  'By keywords show as posts' => 'Messages contenant «&#160;%s&#160;»',
  'By keywords show as topics' => 'Discussions avec messages contenant «&#160;%s&#160;»',
  'By user show as posts' => 'Messages de %s',
  'By user show as topics' => 'Discussions contenant des messages de %s',
  'Descending' => 'Décroissant',
  'Forum search' => 'Forum',
  'Go to post' => 'Aller au message',
  'Go to topic' => 'Aller à la discussion',
  'Keyword search' => 'Mots-clés',
  'Message and subject' => 'Le texte du message et du sujet',
  'Message only' => 'Le texte du message seulement',
  'No hits' => 'Désolé, aucun résultat n\'a été trouvé pour votre recherche.',
  'No new posts' => 'Il n\'y a pas de discussion avec de nouveaux messages depuis votre dernière visite.',
  'No recent posts' => 'Il n\'y a pas de discussion avec de nouveaux messages depuis les 10 derniers jours.',
  'No search permission' => 'Vous ne pouvez pas effectuer de recherche, vous n\'avez pas les permissions requises',
  'No subscriptions' => 'Cet utilisateur ne suit actuellement aucune discussion.',
  'No terms' => 'Vous devez saisir au moins un mot-clé et/ou un auteur à rechercher.',
  'No unanswered' => 'Il n\'y a pas de message sans réponse dans ce forum.',
  'No user posts' => 'Il n\'y a pas de message de cet utilisateur dans ce forum.',
  'No user topics' => 'Il n\'y a pas de discussion de cet utilisateur dans ce forum.',
  'Quick search show_new' => 'Nouveaux',
  'Quick search show_recent' => 'Récentes',
  'Quick search show_replies' => 'Publiés',
  'Quick search show_subscriptions' => 'Suivies par %s',
  'Quick search show_unanswered' => 'Sans réponse',
  'Quick search show_user_posts' => 'Messages de %s',
  'Quick search show_user_topics' => 'Discussions de %s',
  'Search' => 'Recherche',
  'Search criteria legend' => 'Choisissez vos critères de recherche',
  'Search flood' => 'Vous devez patienter au minimum %s secondes avant d\'effectuer une nouvelle recherche. Veuillez patienter un moment et essayer à nouveau.',
  'Search in' => 'Rechercher dans&#160;…',
  'Search in info' => 'Choisissez le forum dans lequel vous souhaitez lancer votre recherche et indiquez si vous souhaitez rechercher dans les sujets des discussions uniquement ou dans les textes des messages ou bien dans les deux à la fois.',
  'Search in legend' => 'Indiquez où la recherche doit s\'effectuer',
  'Search info' => 'Pour effectuer une recherche par mots-clés, indiquez le ou les termes à rechercher en les séparant par des espaces. Utilisez AND, OR, NOT pour affiner votre recherche. Pour rechercher par auteur, saisissez le nom d\'utilisateur auquel les messages appartiennent. Utilisez le joker * pour des recherches sur des fragments de mot.',
  'Search multiple forums info' => 'Si aucun forum n\'est sélectionné, la recherche s\'effectuera dans tous les forums.',
  'Search results' => 'Résultats de la recherche',
  'Search results info' => 'Vous pouvez choisir le mode de classement et d\'affichage des résultats.',
  'Search results legend' => 'Sélectionnez le mode d\'affichage des résultats',
  'Show as' => 'Afficher les&#160;…',
  'Show as posts' => 'Messages',
  'Show as topics' => 'Discussions',
  'Sort by' => 'Trier par&#160;…',
  'Sort by author' => 'Auteur',
  'Sort by forum' => 'Forum',
  'Sort by post time' => 'Date du message',
  'Sort by subject' => 'Sujet',
  'Sort order' => 'Ordre&#160;…',
  'Topic only' => 'Le texte du sujet seulement',
  'User search' => 'Rechercher un utilisateur',
);

?>
