<?php

// Language definitions used in admin-options.php
$lang_admin_options = array(

'Bad HTTP Referer message'			=>	'Bad HTTP_REFERER. Hvis du har flyttet disse fora fra et sted til et andet eller skiftet domæne, skal du opdatere Base URL manuelt i databasen (se efter o_base_url i config tabellen) og derefter rydde cachen ved at slette alle. Php filer i / cache mappen.',
'Must enter title message'			=>	'Du skal indtaste en forum titel',
'Invalid e-mail message'			=>	'Admin e-mail adressen du indtastede er ugyldig.',
'Invalid webmaster e-mail message'	=>	'Den webmaster email adresse du indtastede er ugyldig.',
'SMTP passwords did not match'		=>	'Du skal indtaste n samme SMTP-adgangskode to gange for at ændre den.',
'Enter announcement here'			=>	'Indtast din meddelelse her.',
'Enter rules here'					=>	'Indtast dine regler her.',
'Default maintenance message'		=>	'Fora er midlertidigt nede pga. vedligeholdelse. Prøv igen om et par minutter.',
'Timeout error message'				=>	'Værdien af ​​"Timeout online" skal være mindre end værdien af ​​"Timeout besøg".',
'Options updated redirect'			=>	'Indstillinger opdateret. Omdirigerer …',
'Options head'						=>	'Indstillinger',

// Essentials section
'Essentials subhead'				=>	'Essentielle',
'Board title label'					=>	'Forum titel',
'Board title help'					=>	'Titlen på dette forum (vist øverst på hver side). Dette felt kan <strong> ikke </ strong> indeholder HTML.',
'Board desc label'					=>	'Forum beskrivelse',
'Board desc help'					=>	'En kort beskrivelse af dette forum (vist øverst på hver side). Dette felt kan indeholde HTML.',
'Base URL label'					=>	'Base URL',
'Base URL help'						=>	'Den komplette URL til forummet uden efterfølgende skråstreg (dvs. http://www.mitdomæne.com/forum). Dette <strong> skal </ strong> være korrekt, for at alle administratore og moderatore funktioner fungerer. Hvis du får "Bad Referer" fejl, er den sandsynligvis forkert.',
'Timezone label'					=>	'Standard tidszone',
'Timezone help'						=>	'Standard tidszone for gæster og brugere, forsøger at tilmelde dig til forummet.',
'DST label'							=>	'Juster DST',
'DST help'							=>	'Kontroller, om sommertid er i kraft (forskyder tiden med 1 time).',
'Language label'					=>	'Standard sprog',
'Language help'						=>	'Standardsproget for gæster og brugere, som ikke har ændret sig fra standard i deres profil. Hvis du fjerner en sprogpakke, skal dette opdateres',
'Default style label'				=>	'Standard stil',
'Default style help'				=>	'Standard stil for gæster og brugere, som ikke har ændret sig fra standard i deres profil.',

// Essentials section timezone options
'UTC-12:00'							=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'							=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'							=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'							=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'							=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'							=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'							=>	'(UTC-08:00) Pacific',
'UTC-07:00'							=>	'(UTC-07:00) Mountain',
'UTC-06:00'							=>	'(UTC-06:00) Central',
'UTC-05:00'							=>	'(UTC-05:00) Eastern',
'UTC-04:00'							=>	'(UTC-04:00) Atlantic',
'UTC-03:30'							=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'							=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'							=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'							=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'								=>	'(UTC) Western European, Greenwich',
'UTC+01:00'							=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'							=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'							=>	'(UTC+03:00) Eastern African',
'UTC+03:30'							=>	'(UTC+03:30) Iran',
'UTC+04:00'							=>	'(UTC+04:00) Moscow, Gulf, Samara',
'UTC+04:30'							=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'							=>	'(UTC+05:00) Pakistan',
'UTC+05:30'							=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'							=>	'(UTC+05:45) Nepal',
'UTC+06:00'							=>	'(UTC+06:00) Bangladesh, Bhutan, Yekaterinburg',
'UTC+06:30'							=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'							=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'							=>	'(UTC+08:00) Greater China, Australian Western, Krasnoyarsk',
'UTC+08:45'							=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'							=>	'(UTC+09:00) Japan, Korea, Chita, Irkutsk',
'UTC+09:30'							=>	'(UTC+09:30) Australian Central',
'UTC+10:00'							=>	'(UTC+10:00) Australian Eastern',
'UTC+10:30'							=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'							=>	'(UTC+11:00) Solomon Island, Vladivostok',
'UTC+11:30'							=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'							=>	'(UTC+12:00) New Zealand, Fiji, Magadan',
'UTC+12:45'							=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'							=>	'(UTC+13:00) Tonga, Phoenix Islands, Kamchatka',
'UTC+14:00'							=>	'(UTC+14:00) Line Islands',

// Timeout Section
'Timeouts subhead'					=>	'Tid og timeouts',
'Time format label'					=>	'Tidsformat',
'PHP manual'						=>	'PHP manual',
'Time format help'					=>	'[Nuværende format: %s]. Se %s for formateringsindstillinger.',
'Date format label'					=>	'Datoformat',
'Date format help'					=>	'[Nuværende format: %s]. Se %s for formateringsindstillinger.',
'Visit timeout label'				=>	'Besøgende timeout',
'Visit timeout help'				=>	'Antal sekunder en bruger skal være inaktiv, før hans / hendes sidste besøg data er opdateret (påvirker primært nye meddelelsesindikatorer).',
'Online timeout label'				=>	'Online timeout',
'Online timeout help'				=>	'Antal sekunder en bruger skal være inaktiv, inden den fjernes fra online brugerlisten.',
'Redirect time label'				=>	'Omdirigering tid',
'Redirect time help'				=>	'Antal sekunder man skal vente, når siden omdirigere. Hvis sat til 0, vil ingen omdirigeringsside blive vist (anbefales ikke).',

// Display Section
'Display subhead'					=>	'Visning',
'Version number label'				=>	'Versionsnummer',
'Version number help'				=>	'Vis FluxBB versionsnummer i sidefoden.',
'Info in posts label'				=>	'Brugerinfo i indlæg',
'Info in posts help'				=>	'Vis information om forfatteren under brugernavn i emne visning. De berørte oplysninger er beliggenhed, registreringsdato, antal indlæg og kontaktlinks (e-mail og URL).',
'Post count label'					=>	'indlægstæller',
'Post count help'					=>	'Vis antallet af indlæg en bruger har lavet (påvirker emne Vis, profil og bruger listen).',
'Smilies label'						=>	'Smilies i indlæg',
'Smilies help'						=>	'Konverter smilies til grafiske ikoner.',
'Smilies sigs label'				=>	'Smilies i signatur',
'Smilies sigs help'					=>	'Konverter smilies til grafiske ikoner i signature.',
'Clickable links label'				=>	'Gør links klikbare',
'Clickable links help'				=>	'Når aktiveret, vil FluxBB automatisk registrerer alle URL\'er i indlæg , og gøre dem klikbare hyperlinks.',
'Topic review label'				=>	'Gennemgå emne',
'Topic review help'					=>	'Maksimalt antal af indlæg der vises, når man slår noget op (nyeste først). Sæt til 0 for at deaktivere.',
'Topics per page label'				=>	'Emner per side',
'Topics per page help'				=>	'Standard antal af emner der vises per side i et forum. Brugere kan tilpasse denne indstilling.',
'Posts per page label'				=>	'indlæg per side',
'Posts per page help'				=>	'Standard antal af opslag, der vises per side i et emne. Brugere kan tilpasse denne indstilling.',
'Indent label'						=>	'Indrykningsstørrelse',
'Indent help'						=>	'Hvis den er indstillet til 8, vil en regelmæssig tabulering bruges ved visning af tekst inden for [code] [/code] tag. Ellers så mange mellemrum vil blive anvendt til indrykning af teksten.',
'Quote depth label'					=>	'Maksimal [quote] dybde',
'Quote depth help'					=>	'De maksimale antal gange [quote] tag kan bruges inde i andre [quote] tags. Alle tags dybere end dette kasseres.',

// Features section
'Features subhead'					=>	'Egenskaber',
'Quick post label'					=>	'hurtig indlæg',
'Quick post help'					=>	'Når aktiveret, vil FluxBB tilføje en hurtig indlæg formular i bunden af emner. På denne måde kan brugere skrive direkte fra emnet.',
'Users online label'				=>	'Brugere online',
'Users online help'					=>	'Vis info på indekssiden om gæster og registrerede brugere som i øjeblikket kigger i forummet.',
'Censor words label'				=>	'Censorer ord',
'Censor words help'					=>	'Aktivér dette for at censurere specifikke ord i forummet. Se %s for mere info.',
'Signatures label'					=>	'Signature',
'Signatures help'					=>	'Tillad brugere at vedhæfte en signatur til deres indlæg.',
'User has posted label'				=>	'Brugeren har indsendt indlæg tidligere',
'User has posted help'				=>	'Denne funktion viser en prik foran emner i viewforum.php i tilfælde af den aktuelle indloggede bruger har posteret i dette emne tidligere. Deaktiver, hvis du oplever høj server belastning.',
'Topic views label'					=>	'Emne visninger',
'Topic views help'					=>	'Hold styr på antallet af visninger et emne har. Deaktiver, hvis du oplever høj server belastning i et travlt forum.',
'Quick jump label'					=>	'Hurtig visning',
'Quick jump help'					=>	'Aktiver hurtig visning (Gå til forum) rullelisten.',
'GZip label'						=>	'GZip output',
'GZip help'							=>	'Hvis aktiveret, vil FluxBB gzip output sendes til browseren. Dette vil reducere båndbredde, men bruge lidt mere CPU. Denne funktion kræver, at PHP er konfigureret med zlib (--with-zlib). Bemærk: Hvis du allerede har en af Apache-modulerne mod_gzip eller mod_deflate sat op til at komprimere PHP-scripts, bør du slå denne funktion fra.',
'Search all label'					=>	'Søg i alle fora',
'Search all help'					=>	'Når deaktiveret, vil søgninger kun tillades i et forum ad gangen. Deaktiver, hvis server belastningen er høj på grund af overdreven søgning.',
'Menu items label'					=>	'Yderlige menupunkter',
'Menu items help'					=>	'Ved at indtaste HTML-hyperlinks i dette tekstfelt, kan et vilkårligt antal punkter tilføjes til navigationsmenuen øverst på alle sider. Formatet for at tilføje nye links er X  = &lt;a href="URL"&gt;LINK&lt;/a&gt; hvor X er den position, hvor linket skal indsættes (f.eks 0 for at indsætte i begyndelsen og 2 for at indsætte efter "Bruger listen"). Adskil Særskilte links med et linieskift.',

// Feeds section
'Feed subhead'						=>	'Syndication',
'Default feed label'				=>	'Standard feed type',
'Default feed help'					=>	'Vælg den type syndication feed som skal vises. Bemærk: Er intet valgt vil det ikke deaktivere feeds, kun skjule dem som standard.',
'None'								=>	'Ingen',
'RSS'								=>	'RSS',
'Atom'								=>	'Atom',
'Feed TTL label'					=>	'Tid før feeds bliver cachet',
'Feed TTL help'						=>	'Feeds kan blive cachet for at nedsætte ressource bruget fra feeds.',
'No cache'							=>	'cache ikke',
'Minutes'							=>	'%d minutter',

// Reports section
'Reports subhead'					=>	'Rapporter',
'Reporting method label'			=>	'Rapporterings metode',
'Internal'							=>	'Intern',
'By e-mail'							=>	'Email',
'Both'								=>	'Begge',
'Reporting method help'				=>	'Vælg den metode som skal bruges til at rapportere emner/indlæg. Du kan vælge om emne/indlæg rapporter skal håndteres af det interne rapport system, sendt til adresser på mailinglisten (se nedenfor) eller begge dele.',
'Mailing list label'				=>	'Mailinglisten',
'Mailing list help'					=>	'En kommasepareret liste over abonnenter. brugerne på denne liste er modtagerne af rapporterne.',

// Avatars section
'Avatars subhead'					=>	'Avatars',
'Use avatars label'					=>	'Brug avatars',
'Use avatars help'					=>	'Når aktiveret, vil brugere være i stand til at uploade en avatar, der vil blive vist under deres titel.',
'Upload directory label'			=>	'Upload mappe',
'Upload directory help'				=>	'Upload mappe til avatarer (i forhold til FluxBB rodmappen). PHP skal have skriverettigheder til denne mappe.',
'Max width label'					=>	'Max bredde',
'Max width help'					=>	'Den maksimalt tilladte bredde af avatarer i pixels (60 anbefales).',
'Max height label'					=>	'Max højde',
'Max height help'					=>	'Den maksimalt tilladte højde på avatarer i pixel (60 anbefales).',
'Max size label'					=>	'Max størrelse',
'Max size help'						=>	'Den maksimale tilladte størrelse af avatarer i bytes (10240 anbefales).',

// E-mail section
'E-mail subhead'					=>	'Email',
'Admin e-mail label'				=>	'Admin email',
'Admin e-mail help'					=>	'Emailadressen til forummets administrator.',
'Webmaster e-mail label'			=>	'Webmaster email',
'Webmaster e-mail help'				=>	'Dette er den adresse, at alle e-mails sendt af forummet vil blive behandlet fra.',
'Forum subscriptions label'			=>	'Forum abonnementer',
'Forum subscriptions help'			=>	'Tillad brugere at abonnere på fora (modtage e-mail, når nogen opretter et nyt emne).',
'Topic subscriptions label'			=>	'Emne abonnementer',
'Topic subscriptions help'			=>	'Aktiver brugere at abonnere på emner (modtage e-mail, når nogen svare).',
'SMTP address label'				=>	'SMTP server adresse',
'SMTP address help'					=>	'Adressen til en ekstern SMTP server til at sende emails med. Du kan angive et brugerdefineret portnummer hvis SMTP serveren ikke køre på standard port 25 (eksempel: mail.myhost.com: 3580). Efterlad tomt for at bruge det lokale mail-program.',
'SMTP username label'				=>	'SMTP brugernavn',
'SMTP username help'				=>	'Brugernavn til SMTP serveren. Indtast kun et brugernavn, hvis det kræves af SMTP serveren (de fleste servere kræver <strong> ikke </ strong>  godkendelse).',
'SMTP password label'				=>	'SMTP kodeord',
'SMTP change password help'			=>	'Afkryds dette hvis du ønsker at ændre eller slette den aktuelt gemte adgangskode.',
'SMTP password help'				=>	'Adgangskode til SMTP serveren. Indtaste kun en adgangskode, hvis det kræves af SMTP-serveren (de fleste servere <strong> ikke </ strong> kræver godkendelse). Indtast venligst din adgangskode to gange for at bekræfte.',
'SMTP SSL label'					=>	'Krypter SMTP ved hjælp af SSL',
'SMTP SSL help'						=>	'Krypterer forbindelsen til SMTP serveren ved hjælp af SSL. Bør kun bruges hvis din SMTP server kræver det, og din version af PHP understøtter SSL.',

// Registration Section
'Registration subhead'				=>	'Registrering',
'Allow new label'					=>	'Tillad nye registreringer',
'Allow new help'					=>	'Kontrollerer om dette forum accepterer nye registreringer. Deaktiver kun under særlige omstændigheder.',
'Verify label'						=>	'Bekræft registreringer',
'Verify help'						=>	'Når aktiveret, bliver brugere sendt en tilfældig adgangskode når de tilmelder sig. De kan derefter logge ind og ændre adgangskoden i deres profil, hvis de ønsker det. Denne funktion kræver, at brugerne kontrollere nye mail-adresser, hvis de vælger at skifte fra den, de registrerede med. Dette er en effektiv måde at undgå registreringsmisbrug og for at sikre, at alle brugere har den "rigtige" email adresse i deres profiler.',
'Report new label'					=>	'Rapporter nye registreringer',
'Report new help'					=>	'If enabled, FluxBB will notify users on the mailing list (see above) when a new user registers in the forums.',
'Use rules label'					=>	'User forum rules',
'Use rules help'					=>	'Hvis aktiveret, vil FluxBB underrette brugerne på mailinglisten (se ovenfor), når en ny bruger registrerer i forummet.',
'Rules label'						=>	'Indtast dine regler her',
'Rules help'						=>	'Her kan du indtaste nogen regler eller andre oplysninger, som brugeren skal gennemgå og acceptere, når de registrerer. Hvis du har aktiveret ovenstående regler skal du indtaste noget her, ellers vil det blive deaktiveret. Denne tekst vil ikke blive fortolket som almindelige indlæg, og kan dermed indeholde HTML.',
'E-mail default label'				=>	'Standard e-mail indstilling',
'E-mail default help'				=>	'Vælg standard privatlivsindstillinger for nye bruger registreringer.',
'Display e-mail label'				=>	'Vis e-mail adresser til andre brugere.',
'Hide allow form label'				=>	'Skjul email adresse, men tillader formularen e-mail.',
'Hide both label'					=>	'Skjul email adresse og tillad ikke formularen e-mail.',

// Announcement Section
'Announcement subhead'				=>	'Meddelelser',
'Display announcement label'		=>	'Vis Meddelelser',
'Display announcement help'			=>	'Aktivér dette for at vise nedenstående besked i bestyrelsen.',
'Announcement message label'		=>	'Besked',
'Announcement message help'			=>	'Denne tekst vil ikke blive fortolket som almindelige indlæg, og  kan dermed indeholde HTML.',

// Maintenance Section
'Maintenance subhead'				=>	'Vedligeholdelse',
'Maintenance mode label'			=>	'Vedligeholdelse tilstand',
'Maintenance mode help'				=>	'Når aktiveret, vil forummet kun være tilgængeligt for administratorer. Dette bør bruges, hvis forummet skal tages ned midlertidigt for vedligeholdelse. <strong> ADVARSEL! log ikke ud, når forummet er i vedligeholdelsestilstand. </ Strong> Du vil ikke kunne logge ind igen.',
'Maintenance message label'			=>	'Vedligeholdelsesbesked',
'Maintenance message help'			=>	'Denne meddelelse, vil blive vist til brugerne, når bestyrelsen er i vedligeholdelsestilstand. Hvis tomt, vil en standard besked blive brugt. Denne tekst vil ikke blive fortolket som almindelige indlæg, og kan dermed indeholde HTML.',

);
