<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'Ude af stand til at opdatere siden \'allow_url_fopen\' er slået fra på dette systeme.',
'Upgrade check failed message'		=>	'Søgning efter opdateringer fejlede af ukendte årsager.',
'Running latest version message'	=>	'Du har den nyeste version af FluxBB.',
'New version available message'		=>	'En ny version af FluxBB er tilgængelig. Du kan hente den nyeste version på %s.',
'PHPinfo disabled message'			=>	'PHP funktionen phpinfo() er deaktiveret på serveren.',
'Not available'						=>	'Ikke tilgængelig',
'Forum admin head'					=>	'Forum administration',
'NA'								=>	'Ikke relevant',
'Welcome to admin'					=>	'Velkommen til FluxBB kontrolpanel. Herfra kan du styre vitale aspekter af forummet. Alt afhænging om du er en administrator eller moderator kan du:',
'Welcome 1'							=>	'Organisere kategorier og forummer.',
'Welcome 2'							=>	'Tilpasse forum bredde og konfigurationer.',
'Welcome 3'							=>	'Tilpasse bruger og gæsters rettigheder.',
'Welcome 4'							=>	'Se IP statistikker for brugere.',
'Welcome 5'							=>	'Banlyse brugere.',
'Welcome 6'							=>	'Censurere ord.',
'Welcome 7'							=>	'Oprette brugergrupper og forfremmelser.',
'Welcome 8'							=>	'Beskære gamle indlæg.',
'Welcome 9'							=>	'Håndtere rapporteringer.',
'Statistics head'					=>	'Statistik',
'FluxBB version label'				=>	'FluxBB version',
'Check for upgrade'					=>	'Søg efter opdateringer',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'Server belastning',
'Server load data'					=>	'%s - %s bruger(e) online',
'Environment label'					=>	'Miljø',
'Environment data OS'				=>	'Styresystem: %s',
'Show info'							=>	'Vis info',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Accelerator: %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Database',
'Database data rows'				=>	'Rækker: %s',
'Database data size'				=>	'Størrelse: %s',

);
