<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'Ude af stand til at opdatere siden \'allow_url_fopen\' er slået fra på dette systeme.',
'Upgrade check failed message'		=>	'Check for opdateringer fejlede af uafklarede grunde.',
'Running latest version message'	=>	'Du kører med den nyeste version af FluxBB.',
'New version available message'		=>	'En ny version af FluxBB er udkommet. Du kan downloade den nyeste version hos %s.',
'PHPinfo disabled message'			=>	'PHP funktionen phpinfo() er deaktiveret på serveren.',
'Not available'						=>	'Ikke tilænglig',
'Forum admin head'					=>	'Forum administration',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'Velkommen til FluxBB administrations kontrol panel. Herfra kan du styrer vitale aspekter af forummet. Alt afhænging om du er en administrator eller en moderator kan du:',
'Welcome 1'							=>	'Organisere kategorier og fora.',
'Welcome 2'							=>	'Set forum-wide options and preferences.',
'Welcome 3'							=>	'Control permissions for users and guests.',
'Welcome 4'							=>	'View IP statistics for users.',
'Welcome 5'							=>	'Ban users.',
'Welcome 6'							=>	'Censor words.',
'Welcome 7'							=>	'Set up user groups and promotions.',
'Welcome 8'							=>	'Prune old posts.',
'Welcome 9'							=>	'Handle post reports.',
'Statistics head'					=>	'Statistik',
'FluxBB version label'				=>	'FluxBB version',
'Check for upgrade'					=>	'Check for opdateringer',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'Server belastning',
'Server load data'					=>	'%s - %s bruger(e) online',
'Environment label'					=>	'Miljø',
'Environment data OS'				=>	'Styresystem: %s',
'Show info'							=>	'Vis info',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Accelerator: %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Database',
'Database data rows'				=>	'Rækker: %s',
'Database data size'				=>	'Størrelse: %s',

);
