<?php

// Language definitions used in install.php, localized by adaur

$lang_install = array(

'Install message'				=>	'Filen \'config.php\' eksistere ikke eller er beskadiget. Dette forudsætter dog at FluxBB endnu ikke er blevet installeret.',
'Choose install language'		=>	'Vælg sprog til installationen',
'Choose install language info'	=>	'Sproget til denne installation. Standard sproget for forummet tilpasses nedenfor.',
'Install language'				=>	'Installation sprog',
'Change language'				=>	'Skift sprog',
'Next'							=>	'Næste',
'Already installed'				=>	'Det ser ud til at FluxBB allerede er installeret. Du skal gå <a href="index.php">hertil</a> istedet.',
'You are running error'			=>	'Du kører version %1$s. FluxBB %3$s kræver mindst %1$s %4$s for at køre korrekt. Du skal opgradere din %1$s installation før du kan fortsætte.',
'My FluxBB Forum'				=>	'Mit FluxBB Forum',
'Description'					=>	'Desværre kan ingen sige hvad FluxBB er - du skal selv opleve det.',
'Username 1'					=>	'Brugernavne skal mindst være 2 karakterer langt.',
'Username 2'					=>	'Brugernavne må ikke være længere end 25 karakterer lange.',
'Username 3'					=>	'Brugernavnet gæst er reserveret.',
'Username 4'					=>	'Burgernavne må ikke være i form af en IP adresse.',
'Username 5'					=>	'Brugernavne må ikke indeholde tegnene \', " og [ eller ] på samme tid.',
'Username 6'					=>	'Brugernavne må ikke indeholde nogle af de tekst formattering tags (BBKode) som forummet anvender.',
'Short password'				=>	'Kodeord skal mindst være 4 tegn lange.',
'Passwords not match'			=>	'Kodeordene er ikke ens.',
'Wrong email'					=>	'Administrator e-mail adressen du har indtastet er ugyldig.',
'No board title'				=>	'Du skal indtaste en forum titel.',
'Error default language'		=>	'Standard sproget du har valgt ser ikke ud til at eksistere.',
'Error default style'			=>	'Standard temaet du har valgt ser ikke ud til at eksistere.',
'No DB extensions'				=>	'Dette PHP miljø understøtter ikke de database typer som FluxBB understøtter. PHP har brug for understøttelse af MySQL, PostgreSQL eller SQLite for at FluxBB kan blive installeret.',
'Administrator username'		=>	'Administrator brugernavn',
'Administrator password 1'		=>	'Administrator kodeord 1',
'Administrator password 2'		=>	'Administrator kodeord 2',
'Administrator email'			=>	'Administrator e-mail',
'Board title'					=>	'Forum titel',
'Base URL'						=>	'Grund URL',
'Required field'				=>	'er et obligatorisk felt i denne formular.',
'FluxBB Installation'			=>	'FluxBB Installation',
'Welcome'						=>	'Du er ved at installere FluxBB. For at installere FluxBB skal du udfylde formularen herunder. Hvis du oplever udfordringer med installationen bedes du gennemgå dokumentationen.',
'Install'						=>	'Installer FluxBB %s',
'Errors'						=>	'De følgende fejl skal rettes:',
'Database setup'				=>	'Database opsætning',
'Info 1'						=>	'Indtast venligst de nødvendige oplysninger, for at konfigurere din database til FluxBB. Du skal kende alle oplysningerne som påkræves før du fortsætter med installationen.',
'Select database'				=>	'Vælg din database type',
'Info 2'						=>	'FluxBB currently supports MySQL, PostgreSQL and SQLite. If your database of choice is missing from the drop-down menu below, it means this PHP environment does not have support for that particular database. More information regarding support for particular versions of each database can be found in the FAQ.',
'Dual MySQL'					=>	'FluxBB has detected that your PHP environment supports two different ways of communicating with MySQL. The two options are called standard and improved. If you are uncertain which one to use, start by trying improved and if that fails, try standard.',
'InnoDB'						=>	'FluxBB has detected that your MySQL server might support <a href="http://dev.mysql.com/doc/refman/5.0/en/innodb.html">InnoDB</a>. This would be a good choice if you are planning to run a large forum. If you are uncertain, it is recommended that you do not use InnoDB.',
'Database type'					=>	'Database type',
'Required'						=>	'(Påkrævet)',
'Database hostname'				=>	'Enter your database server hostname',
'Info 3'						=>	'The address of the database server (example: localhost, db.myhost.com or 192.168.0.15). You can specify a custom port number if your database doesn\'t run on the default port (example: localhost:3580). For SQLite support, just enter anything or leave it at \'localhost\'.',
'Database server hostname'		=>'Database server hostname',
'Database enter name'			=>	'Enter the name of your database',
'Info 4'						=>	'The name of the database that FluxBB will be installed into. The database must exist. For SQLite, this is the relative path to the database file. For security reasons, it is highly recommended to place the SQLite database in a private (not web accessible) directory whenever possible. If the SQLite database file does not exist, FluxBB will attempt to create it.',
'Database name'					=>	'Database navn',
'Database enter informations'	=>	'Indtast databasens brugernavn og kodeord',
'Database username'				=>	'Database brugernavn',
'Info 5'						=>	'Enter the username and password with which you connect to the database. Ignore for SQLite.',
'Database password'				=>	'Database kodeord',
'Database enter prefix'			=>	'Enter database table prefix',
'Info 6'						=>	'If you like, you can specify a table prefix. This way you can run multiple copies of FluxBB in the same database (example: foo_).',
'Table prefix'					=>	'Table prefix',
'Administration setup'			=>	'Administration setup',
'Info 7'						=>	'Please enter the requested information in order to setup an administrator for your FluxBB installation.',
'Admin enter username'			=>	'Indtast Administratorens brugernavn',
'Info 8'						=>	'The username of the forum administrator. You can later create more administrators and moderators. Usernames can be between 2 and 25 characters long.',
'Admin enter password'			=>	'Enter and confirm Administrator\'s password',
'Info 9'						=>	'Passwords must be at least 4 characters long. Passwords are case sensitive.',
'Password'						=>	'Kodeord',
'Confirm password'				=>	'Bekræft kodeord',
'Admin enter email'				=>	'Indtast Administratorens e-mail',
'Info 10'						=>	'The email address of the forum administrator.',
'Board setup'					=>	'Forum opsætning',
'Info 11'						=>	'Please enter the requested information in order to setup your FluxBB board.',
'Enter board title'				=>	'Enter your board\'s title',
'Info 12'						=>	'The title of this bulletin board (shown at the top of every page).',
'Enter board description'		=>	'Enter your board\'s description',
'Info 13'						=>	'A short description of this bulletin board (shown at the top of every page). This field may contain HTML.',
'Board description'				=>	'Board description',
'Enter base URL'				=>	'Enter the Base URL of your FluxBB installation',
'Info 14'						=>	'The URL (without trailing slash) of your FluxBB forum (example: http://forum.myhost.com or http://myhost.com/~myuser). This <strong>must</strong> be correct, otherwise, administrators and moderators will not be able to submit any forms. Please note that the preset value below is just an educated guess by FluxBB.',
'Choose the default language'	=>	'Choose the default language',
'Info 15'						=>	'The default language used for guests and users who haven\'t changed from the default in their profile.',
'Default language'				=>	'Standard sprog',
'Choose the default style'		=>	'Vælg et standard tema',
'Info 16'						=>	'The default style used for guests and users who haven\'t changed from the default in their profile.',
'Default style'					=>	'Standard tema',
'Start install'					=>	'Start installation',
'DB type not valid'				=>	'\'%s\' is not a valid database type',
'Table prefix error'			=>	'The table prefix \'%s\' contains illegal characters or is too long. The prefix may contain the letters a to z, any numbers and the underscore character. They must however not start with a number. The maximum length is 40 characters. Please choose a different prefix',
'Prefix reserved'				=>	'The table prefix \'sqlite_\' is reserved for use by the SQLite engine. Please choose a different prefix',
'Existing table error'			=>	'A table called \'%susers\' is already present in the database \'%s\'. This could mean that FluxBB is already installed or that another piece of software is installed and is occupying one or more of the table names FluxBB requires. If you want to install multiple copies of FluxBB in the same database, you must choose a different table prefix',
'InnoDB off'					=>	'InnoDB does not seem to be enabled. Please choose a database layer that does not have InnoDB support, or enable InnoDB on your MySQL server',
'Administrators'				=>	'Administratorer',
'Administrator'					=>	'Administrator',
'Moderators'					=>	'Moderatorer',
'Moderator'						=>	'Moderator',
'Guests'						=>	'Gæster',
'Guest'							=>	'Gæst',
'Members'						=>	'Medlemmer',
'Announcement'					=>	'Indtast din annoncering her.',
'Rules'							=>	'Indtast dine regler her',
'Maintenance message'			=>	'The forums are temporarily down for maintenance. Please try again in a few minutes.',
'Test post'						=>	'Test emne',
'Message'						=>	'If you are looking at this (which I guess you are), the install of FluxBB appears to have worked! Now log in and head over to the administration control panel to configure your forum.',
'Test category'					=>	'Test kategori',
'Test forum'					=>	'Test forum',
'This is just a test forum'		=>	'Dette er bare et test forum',
'Alert cache'					=>	'<strong>The cache directory is currently not writable!</strong> In order for FluxBB to function properly, the directory <em>%s</em> must be writable by PHP. Use chmod to set the appropriate directory permissions. If in doubt, chmod to 0777.',
'Alert avatar'					=>	'<strong>The avatar directory is currently not writable!</strong> If you want users to be able to upload their own avatar images you must see to it that the directory <em>%s</em> is writable by PHP. You can later choose to save avatar images in a different directory (see Admin/Options). Use chmod to set the appropriate directory permissions. If in doubt, chmod to 0777.',
'Alert upload'					=>	'<strong>File uploads appear to be disallowed on this server!</strong> If you want users to be able to upload their own avatar images you must enable the file_uploads configuration setting in PHP. Once file uploads have been enabled, avatar uploads can be enabled in Administration/Options/Features.',
'FluxBB has been installed'		=>	'FluxBB er blevet installeret. Følg instrukserne herunder for at færdiggøre installationen.',
'Final instructions'			=>	'Endelige instruktioner',
'Info 17'						=>	'To finalize the installation, you need to click on the button below to download a file called config.php. You then need to upload this file to the root directory of your FluxBB installation.',
'Info 18'						=>	'Once you have uploaded config.php, FluxBB will be fully installed! At that point, you may <a href="index.php">go to the forum index</a>.',
'Download config.php file'		=>	'Hent config.php fil',
'FluxBB fully installed'		=>	'FluxBB has been fully installed! You may now <a href="index.php">go to the forum index</a>.',

);
