<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Indtast en gyldig email adresse',
'Email legend 2'			=>	'Indtast og bekræft en gyldig email adresse',
'Localisation legend'		=>	'Sæt dine lokaliseringsmuligheder',
'Time zone'					=>	'Tidszone',
'Time zone info'			=>	'For at forumet skal kunne vise tiden korrekt er det nødvendigt at du vælger din lokale tidszone. Hvis det er sommertid skal du også huske at klikke på den mulighed, som automatisk vil sætte uret en time frem.',
'DST'						=>	'Det er sommertid (sætter uret en time frem).',
'Time format'				=>	'Tidsformat',
'Date format'				=>	'Datoformat',
'Default'					=>	'Standard',
'Language'					=>	'Sprog',
'Email setting info'		=>	'Vælg om du vil have at din email adresse skal være synlig for andre brugere og om du vil have at andre brugere kan sende emails til dig via forumet (Select whether you want your email address to be viewable to other users or not and if you want other users to be able to send you email (formular emails) via forummet .',
'Email setting 1'			=>	'Vis din email adresse.',
'Email setting 2'			=>	'Gem din email adresse, men tillad formular emails.',
'Email setting 3'			=>	'Gem din email adresse og tillad ikke formular emails.',
'Privacy options legend'	=>	'Sæt din privatindstillinger',
'Confirm pass'				=>	'Bekræft kodeord',

'Username too short'		=>	'Brugernavne skal være mindst 2 tegn lange. Vælg venligst et længere brugernavn.',
'Username too long'			=>	'Brugernavn må ikke være længere end 26 tegn. Væg venligst et kortere brugernavn.',
'Username guest'			=>	'Brugernavnet "gæst" er reserveret. Vælg venligst et andet brugernavn.',
'Username IP'				=>	'Brugernavne må ikke være i form af en IP adresse. Vælg venligst et andet brugernavn.',
'Username reserved chars'	=>	'Brugernavne må ikke indholde følgende tegn: \', " og [ eller ] på samme tid. Vælg venligst et andet brugernavn.',
'Username BBCode'			=>	'Brugernavne må ikke indholde nogle BBkoder som forumet bruger. Vælg venligst et andet brugernavn.',
'Banned username'			=>	'Brugernavnet som du har indtaste et blevet bannet fra forummet. Vælg venligst et andet brugernavn.',
'Pass too short'			=>	'Kodeord skal være mindst 4 tegn lange. Vælg venligst et længere kodeord.',
'Pass not match'			=>	'Koderordene er ikke de samme',
'Banned email'				=>	'Denne email adresse er bannet fra forummet. Vælg venligst en anden email.',
'Dupe email'				=>	'En anden bruger er allerede registreret med denne email adresse. Vælg venligst en anden email.',
'Sig too long'				=>	'Signatur må ikke være længere end %1$s tegn. Reducér venligst din signatur med %2$s tegn.',
'Sig too many lines'		=>	'Signature må ikke indholde mere end %s linier.',
'Bad ICQ'					=>	'Du har intastet en ugyldig ICQ UIN. Gå venligst til og ret dette.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Moscow, Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Yekaterinburg',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Krasnoyarsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita, Irkutsk',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Vladivostok',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Magadan',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands, Kamchatka',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
