<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'Søg på en bruger',
'No search permission'				=>	'Du har ikke rettigheder til at bruge denne søgefunktion.',
'Search flood'						=>	'Der skal gå mindst %s sekunder mellem søgninger. Vent venligst et øjeblik og prøv igen.',
'Search'							=>	'Søg',
'Search criteria legend'			=>	'Hvad vil du søge på',
'Search info'						=>	'For at søge på et søgeord, indtast et søgeord eller en sætning. Separate søgeord mellemrum. Brug AND, OR and NOT for at rafinere din søgning. For at søge på en forfatter indtast brugernavnet på forfatteren som har skrevet posteringen du ønsker at søge på. Brug wildcard karakteren * for et specifikt match.',
'Keyword search'					=>	'Søgeord',
'Author search'						=>	'Søg på forfatter',
'Search in legend'					=>	'Bestem hvor der skal søges',
'Search in info'					=>	'Vælg i hvilket forum du vil søge og om du vil søge på emner, indlæg eller begge.',
'Search multiple forums info'		=>	'Hvis ingen fora er valgt vil der blive søgt på alle fora.',
'Forum search'						=>	'Forum',
'All forums'						=>	'Alle fora',
'Search in'							=>	'Søg i',
'Message and subject'				=>	'Tekst og Emne',
'Message only'						=>	'Kun tekst',
'Topic only'						=>	'Kun emner',
'Sort by'							=>	'Sortér efter',
'Sort order'						=>	'Sortér orden',
'Search results legend'				=>	'Vælg hvordan du vil vise dine søgeresultater',
'Search results info'				=>	'Du kan vælge hvordan du ønsker at sortere og vise dine resultater.',
'Sort by post time'					=>	'Indlægs tid',
'Sort by author'					=>	'Forfatter',
'Sort by subject'					=>	'Emne',
'Sort by forum'						=>	'Forum',
'Ascending'							=>	'Stigende',
'Descending'						=>	'Faldende',
'Show as'							=>	'Vis resultater som',
'Show as topics'					=>	'Emner',
'Show as posts'						=>	'Indlæg',

// Results
'Search'							=>	'Søg',
'Search results'					=>	'Søgeresultater',
'Quick search show_new'				=>	'Ny',
'Quick search show_recent'			=>	'Aktiv',
'Quick search show_unanswered'		=>	'Ubesvaret',
'Quick search show_replies'			=>	'Opslået',
'Quick search show_user_topics'		=>	'Emne af %s',
'Quick search show_user_posts'		=>	'Indlæg af %s',
'Quick search show_subscriptions'	=>	'Abonner på %s',
'By keywords show as topics'		=>	'Emner med indlæg som indeholder \'%s\'',
'By keywords show as posts'			=>	'Indlæg indeholdende \'%s\'',
'By user show as topics'			=>	'Emner med posteringer af %s',
'By user show as posts'				=>	'Indlæg af %s',
'By both show as topics'			=>	'Emner med posteringer indeholdende \'%s\', by %s',
'By both show as posts'				=>	'Posteringer indeholdende \'%s\', by %s',
'No terms'							=>	'Du skal indtaste mindst eet søgeord og/eller en forfatter for at søge.',
'No hits'							=>	'Ding søgning har fundet 0 resultater.',
'No user posts'						=>	'Der er ingen indlæg af denne bruger i dette forum.',
'No user topics'					=>	'Der er ingen emner af denne bruger i dette forum.',
'No subscriptions'					=>	'Denne bruger abonnerer imidlertid ikke to nogen emner.',
'No new posts'						=>	'Der er ingen emner eller nye indlæg at vise siden dit sidste besøg.',
'No recent posts'					=>	'Ingen nye indlæg er blevet lavet ingenfor de sidste 24 timer.',
'No unanswered'						=>	'Der er ingan ubesvarede indlæg i dette forum.',
'Go to post'						=>	'Gå til indlæg',
'Go to topic'						=>	'Gå til emne'

);
