<?php

// Language definitions used in admin-users.php
$lang_admin_users = array(

'Non numeric message'		=>	'Ha introducido un valor no numérico en una columna solo numérica.',
'Invalid date time message'	=>	'Ha introducido una fecha/hora no valida.',
'Not verified'				=>	'No verificado',
'User search head'			=>	'Buscar usuario',
'User search subhead'		=>	'Introduzca los criterios de búsqueda',
'User search info'			=>	'Buscar usuarios en la base de datos. Puede introducir uno o más términos a buscar. Los comodines en forma de asteriscos (*) estan permitidos.',
'Username label'			=>	'Usuario',
'E-mail address label'		=>	'Dirección de e-mail',
'Title label'				=>	'Titulo',
'Real name label'			=>	'Nombre real',
'Website label'				=>	'Página Web',
'Jabber label'				=>	'Jabber',
'ICQ label'					=>	'ICQ',
'MSN label'					=>	'MSN Messenger',
'AOL label'					=>	'AOL IM',
'Yahoo label'				=>	'Yahoo Messenger',
'Location label'			=>	'Localización',
'Signature label'			=>	'Firma',
'Admin note label'			=>	'Nota del Admin',
'Posts more than label'		=>	'Numero de mensajes mayor que',
'Posts less than label'		=>	'Numero de mensajes menor que',
'Last post after label'		=>	'Último mensaje es después de',
'Date help'					=>	'(dd-mm-yyyy hh:mm:ss)',
'Last post before label'	=>	'Ultimo mensaje es antes de',
'Registered after label'	=>	'Registrado despues de',
'Registered before label'	=>	'Registrado antes de',
'Order by label'			=>	'Ordenar por',
'Order by username'			=>	'Usuario',
'Order by e-mail'			=>	'Email',
'Order by posts'			=>	'Numero de mensajes',
'Order by last post'		=>	'Ultimo mensaje',
'Order by registered'		=>	'Registrado',
'Ascending'					=>	'Ascendente',
'Descending'				=>	'Descendente',
'User group label'			=>	'Grupo de usuario',
'All groups'				=>	'Todos los grupos',
'Unverified users'			=>	'Usuarios sin verificar',
'Submit search'				=>	'Enviar busqueda',
'IP search head'			=>	'Buscar IP',
'IP search subhead'			=>	'Introduzca una IP a buscar',
'IP address label'			=>	'Dirección IP',
'IP address help'			=>	'La dirección IP a buscar en la base de datos de mensajes.',
'Find IP address'			=>	'Encontrar la dirección IP',

'Results head'				=>	'Resultados de la busqueda',
'Results username head'		=>	'Usuario',
'Results e-mail head'		=>	'Email',
'Results title head'		=>	'Titulo/Estado',
'Results posts head'		=>	'Mensajes',
'Results admin note head'	=>	'Nota del Admin',
'Results actions head'		=>	'Acciones',
'Results IP address head'	=>	'Dirección IP',
'Results last used head'	=>	'Ultima usada',
'Results times found head'	=>	'Veces encontrada',
'Results action head'		=>	'Acccion',
'Results find more link'	=>	'Encontrar mas usuarios con esta IP',
'Results no posts found'	=>	'Actualmente no hay mensajes de ese usuario en el foro.',
'Bad IP message'			=>	'La dirección IP suministrada no tiene el formato correcto.',
'Results view IP link'		=>	'Ver estadisticas de la IP',
'Results show posts link'	=>	'Mostrar mensajes',
'Results guest'				=>	'Invitado',
'Results no IP found'		=>	'La dirección IP suministrada no se ha encontrado en la base de datos.',
'No match'					=>	'No hay coincidencias'

);
