<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'			=>	'Ningún usuario con ese nombre registrado. Si desea agregar una prohibición que no esté vinculada a un nombre de usuario especifico deje en blanco el nombre de usuario.',
'No user ID message'		=>	'Ningún usuario registrado con esa ID.',
'User is admin message'		=>	'El usuario %s es un administrador y no puede ser expulsado. Si quiere expulsar un administrador, primero lo debe degradar a moderador o usuario.',
'Must enter message'		=>	'Usted debe de escribir un nombre de usuario, una dirección IP o una dirección de correo electrónico (al menos).',
'Cannot ban guest message'	=>	'Un invitado no puede ser expulsado.',
'Invalid IP message'		=>	'Ha introducido una IP no valida.',
'Invalid e-mail message'	=>	'La dirección de correo (ej. user@domain.com) o el dominio de la dirección (ej. domain.com) que ha introducido no es valido.',
'Invalid date message'		=>	'Ha introducido una fecha de expiración no valida.',
'Invalid date reasons'		=>	'El formato debe ser DD-MM-YYYY y la fecha debe ser al menos un dia futuro.',
'Ban added redirect'		=>	'Agregada expulsión. Continuando …' ,
'Ban edited redirect'		=>	'Editando expulsión. Continuando …',
'Ban removed redirect'		=>	'Borrando expulsión. Continuando …',

'New ban head'				=>	'Nuevo expulsado',
'Add ban subhead'			=>	'Añadir expulsado',
'Username label'			=>	'Usuario',
'Username help'				=>	'El usuario a expulsar distingue mayusculas/minusculas.',
'Username advanced help'	=>	'El usuario a expulsar distingue mayusculas/minusculas. La siguiente página le permitirá ingresar una IP y el correo electrónico personalizado. Si desea expulsar una IP especifica o correo electrónico, simplemente lo deja en blanco.',

'Ban search head'			=>	'Buscando expulsado',
'Ban search subhead'		=>	'Introduzca los criterios de búsqueda',
'Ban search info'			=>	'Búsqueda de expulsados en la base de datos. Puede introducir uno o más términos a buscar. Los comodines en forma de asteriscos (*) son aceptados.',
'Date help'					=>	'(dd-mm-yyyy)',
'Message label'				=>	'Mensaje',
'Expire after label'		=>	'Caduca despues',
'Expire before label'		=>	'Caduca antes',
'Order by label'			=>	'Ordenar por',
'Order by username'			=>	'Usuario',
'Order by ip'				=>	'IP',
'Order by e-mail'			=>	'Correo',
'Order by expire'			=>	'Valido hasta',
'Ascending'					=>	'Ascendente',
'Descending'				=>	'Descendente',
'Submit search'				=>	'Enviar busqueda',

'E-mail label'				=>	'Correo',
'E-mail help'				=>	'El correo electrónico o el dominio de correo que desea prohibir (ej. nombre@dominio.com o dominio.com). Consulte la sección "Permitir direcciones de correo electrónico expulsadas" en los permisos para más información.',
'IP label'					=>	'direcciones IP/IP-rangos',
'IP help'					=>	'La dirección IP o IP-rangos que desea expulsar (ej. 150.11.110.1 o 150.11.110). Separe las direcciones con espacios. Si una IP ya esta introducida esta es la última IP conocida de este usuario en la base de datos.',
'IP help link'				=>	'Pulse %s para ver las estadísticas de IP para este usuario.',
'Ban advanced head'			=>	'Configuración avanzada de expulsiones',
'Ban advanced subhead'		=>	'Expulsión suplementaria con IP y correo electronico',
'Ban message label'			=>	'Mensaje de expulsión',
'Ban message help'			=>	'Un mensaje que se mostrará al usuario expulsado cuando visite el foro.',
'Message expiry subhead'	=>	'Mensaje de expulsión y expiración',
'Ban IP range info'			=>	'Usted debe tener mucho cuidado cuando expulse un rango de IP debido a la posibilidad de que varios usuarios sean expulsado por la misma IP.',
'Expire date label'			=>	'Valido hasta',
'Expire date help'			=>	'La fecha en la que esta expulsión será automaticamente eliminada (formato: dd-mm-aaaa). Dejar en blanco para eliminar manualmente.',

'Results head'				=>	'Resultados de la busqueda',
'Results username head'		=>	'Usuario',
'Results e-mail head'		=>	'Correo',
'Results IP address head'	=>	'IP/IP-rangos',
'Results expire head'		=>	'Valido hasta',
'Results message head'		=>	'Mensaje',
'Results banned by head'	=>	'Expulsado por',
'Results actions head'		=>	'Acciones',
'No match'					=>	'No encontrado',
'Unknown'					=>	'Desconocido',

);
