<?php

// Language definitions used in admin_index.php
// Traducido al español por Javier Rivero (jarive) de FLUXBB HISPANO en http://www.fluxbbhispano.co.cc
$lang_admin_index = array(

'fopen disabled message'			=>	'No se puede comprobar la actualizacion desde \'allow_url_fopen\' esta deshabilitado en el sistema.',
'Upgrade check failed message'		=>	'Comprobación de actualización fallida por razones desconocidas.',
'Running latest version message'	=>	'Usted está usando la última versión de FluxBB.',
'New version available message'		=>	'Una nueva versión de FluxBB ha sido lanzada. Usted puede descargar la última versión en %s.',
'PHPinfo disabled message'			=>	'La función PHP phpinfo() ha sido deshabilitada en este servidor.',
'Not available'						=>	'No disponible',
'Forum admin head'					=>	'Administración del Foro',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'Bienvenido al panel de control de la administración FluxBB. Desde aquí usted puede controlar los aspectos vitales de los foros. Dependiendo de si usted es un administrador o un moderador puede:',
'Welcome 1'							=>	'Organizar categorías y foros.',
'Welcome 2'							=>	'Ajustar opciones y preferencias de los foros.',
'Welcome 3'							=>	'Controlar permisos de usuarios e invitados.',
'Welcome 4'							=>	'Ver las direcciones IP de los usuarios.',
'Welcome 5'							=>	'Expulsar usuarios.',
'Welcome 6'							=>	'Censurar palabras.',
'Welcome 7'							=>	'Ajustar los rangos de usuario.',
'Welcome 8'							=>	'Depurar mensajes antiguos.',
'Welcome 9'							=>	'Manejar reportes en mensajes.',
'Statistics head'					=>	'Estadisticas',
'FluxBB version label'				=>	'Versión de FluxBB',
'Check for upgrade'					=>	'Comprobar actualización',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'Carga del servidor',
'Server load data'					=>	'%s - %s usuario(s) conectado',
'Environment label'					=>	'Entorno',
'Environment data OS'				=>	'Sistema operativo: %s',
'Show info'							=>	'Mostrar info',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Acelerador: %s',
'Turck MMCache'						=>	'Turk MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Base de datos',
'Database data rows'				=>	'Filas: %s',
'Database data size'				=>	'Tamaño: %s',

);
