<?php

// Language definitions used in admin-groups.php
$lang_admin_groups = array(

'Must enter title message'		=>	'Debe introducir un titulo del grupo.',
'Title already exists message'	=>	'Ya existe un grupo con el título <strong>%s</strong>.',
'Default group redirect'		=>	'Grupo por defecto creado. Redireccionando …',
'Cannot remove default message'	=>	'El grupo por defecto no se puede eliminar. Con el fin de eliminar este grupo, primero debe configurar un grupo diferente como grupo por defecto.',
'Group removed redirect'		=>	'Grupo eliminado. Redireccionando …',
'Group added redirect'			=>	'Grupo añadido. Redireccionando …',
'Group edited redirect'			=>	'Grupo editado. Redireccionando …',

'Add groups head'				=>	'Añadir/configurar grupos',
'Add group subhead'				=>	'Añadir nuevo grupo',
'New group label'				=>	'Nuevo grupo base de',
'New group help'				=>	'Seleccione un grupo de usuarios del cual el nuevo grupo hereda su configuración de permisos. La siguiente página te permitirá afinar su configuración.',
'Default group subhead'			=>	'Establecer grupo por defecto',
'Default group label'			=>	'Grupo por defecto',
'Default group help'			=>	'Este es el grupo de usuario por defecto, ej. los usuarios del grupo se colocan en cuanto se registran. Por razones de seguridad, los usuarios no se pueden colocar en el grupo de moderador o administrador por defecto.',
'Existing groups head'			=>	'Grupos existentes',
'Edit groups subhead'			=>	'Editar/borrar grupos',
'Edit groups info'				=>	'Los grupos predefinidos Invitados, Administradores, Moderadores y Miembros no se pueden eliminar. Sin embargo, pueden ser editados. Tenga en cuenta que en algunos grupos, algunas opciones no están disponibles (ej. el permiso para <em>editar mensajes</em> para los invitados). Los administradores siempre tienen todos los permisos.',
'Edit link'						=>	'Editar',
'Delete link'					=>	'Eliminar',
'Group delete head'				=>	'Grupo eliminado',
'Confirm delete subhead'		=>	'Confirma eliminar grupo',
'Confirm delete info'			=>	'¿Está seguro que desea eliminar el grupo <strong>%s</strong>?',
'Confirm delete warn'			=>	'ATENCION! Después de que un grupo sea eliminado no se puede restaurar.',
'Delete group head'				=>	'Eliminar grupo',
'Move users subhead'			=>	'Mueva los usuarios actualmente en el grupo',
'Move users info'				=>	'El grupo <strong>%s</strong> tiene actualmente <strong>%s</strong> miembros. Por favor, seleccione un grupo al que estos miembros serán asignados tras la eliminación.',
'Move users label'				=>	'Mover usuarios a',
'Delete group'					=>	'Eliminar grupo',

'Group settings head'			=>	'Ajustes del grupo',
'Group settings subhead'		=>	'Opciones de configuración de grupo y permisos',
'Group settings info'			=>	'Bajo que opciones y permisos estarán los permisos por defectos para los usuarios del grupo. Estas opciones se aplican si no hay permisos de foro específico en vigor.',
'Group title label'				=>	'Titulo del grupo',
'User title label'				=>	'Titulo de usuario',
'User title help'				=>	'Este título anulará cualquier rango que el usuario haya alcanzado en este grupo. Deja en blanco para usar el título o rango predeterminado.',
'Mod privileges label'			=>	'Permitir a los usuarios privilegios de moderador',
'Mod privileges help'			=>	'Para que un usuario en este grupo para tener privilegios de moderador, el debe ser asignado para moderar uno o más foros. Esto se realiza mediante la página de administración de usuario del perfil del usuario.',
'Edit profile label'			=>	'Permitir a los moderadores editar perfiles de usuario',
'Edit profile help'				=>	'Si los privilegios de moderador están habilitados, permitirá a los usuarios de este grupo editar los perfiles de usuario.',
'Rename users label'			=>	'Allow moderators to rename users',
'Rename users help'				=>	'Si los privilegios de moderador están habilitados, permitirá a los usuarios de este grupo cambiar el nombre de los usuarios.',
'Change passwords label'		=>	'Permitir a los moderadores cambiar las contraseñas',
'Change passwords help'			=>	'Si los privilegios de moderador están habilitados, permitirá a los usuarios de este grupo cambniar las contraseñas.',
'Ban users label'				=>	'Permitir a los moderadores expulsar usuarios',
'Ban users help'				=>	'Si los privilegios de moderador están habilitados, permitirá a los usuarios de este grupo expulsar usuarios.',
'Read board label'				=>	'Leer foros',
'Read board help'				=>	'Permitir a los usuarios en este grupo ver los foros. Esta configuración se aplica a cada aspecto de los foros y por lo tanto no puede ser anulado por la configuración del foro específico. Si esto se establece en "No", los usuarios de este grupo sólo serán capaces de iniciar sesión/cerrar sesión y registrarse.',
'View user info label'			=>	'Ver información de usuario',
'View user info help'			=>	'Permitir a los usuarios ver la lista de usuarios y perfiles de usuario.',
'Post replies label'			=>	'Respuestas',
'Post replies help'				=>	'Permitir a los usuarios de este grupo responder a los temas.',
'Post topics label'				=>	'Publicar temas',
'Post topics help'				=>	'Permitir a los usuarios de este grupo publicar nuevos temas.',
'Edit posts label'				=>	'Editar mensajes',
'Edit posts help'				=>	'Permitir a los usuarios de este grupo editar sus propios mensajes.',
'Delete posts label'			=>	'Eliminar mensajes',
'Delete posts help'				=>	'Permitir a los usuarios de este grupo eliminar sus propios mensajes.',
'Delete topics label'			=>	'Eliminar temas',
'Delete topics help'			=>	'Permitir a los usuarios del grupo eliminar sus propios temas (incluyendo todas las respuestas).',
'Set own title label'			=>	'Ajustar su propio titulo de usuario',
'Set own title help'			=>	'Permitir a los usuarios de este grupo ajustar su propio titulo de usuario.',
'User search label'				=>	'Usar busqueda',
'User search help'				=>	'Permitir a los usuarios de este grupo usar la función de busqueda.',
'User list search label'		=>	'Buscar lista de usuarios',
'User list search help'			=>	'Permitir a los usuarios de este grupo buscar un usuario en la lista de usuarios.',
'Send e-mails label'			=>	'Enviar e-mails',
'Send e-mails help'				=>	'Permitir a los usuarios de este grupo enviar e-mails a otros usuarios.',
'Post flood label'				=>	'Intervalo entre publicaciones',
'Post flood help'				=>	'Número de segundos que los usuarios de este grupo tienen que esperar entre sus publicaciones. Ajustar a 0 para desactivar.',
'Search flood label'			=>	'Intervalo entre busquedas',
'Search flood help'				=>	'Número de segundos que los usuarios de este grupo tienen que esperar entre búsquedas. Ajustar a 0 para desactivar.',
'E-mail flood label'			=>	'Intervalo entre E-mails',
'E-mail flood help'				=>	'Número de segundos que los usuarios de este grupo tienen que esperar enviando correos. Ajustar a 0 para desactivar.',
'Moderator info'				=>	'Tenga en cuenta que para que un usuario de este grupo pueda tener capacidades de moderador, debe estar asignado como moderador en uno o mas foros. Esto se realiza mediante la página de administración de usuario del perfil del usuario.',

);
