<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Escriba una dirección válida de correo electrónico',
'Email legend 2'			=>	'Escriba y confirme una dirección válida de correo electrónico',
'Localisation legend'		=>	'Establece tus opciones de localización',
'Time zone'					=>	'Zona Horaria',
'Time zone info'			=>	'Tienes que introducir tu zona horaria para que los foros muestren la hora correctamente. Si el horario de verano esta en uso, usted debe comprobar esa opción lo que adelantara el tiempo 1 hora..',
'DST'						=>	'Horario de verano en uso (adelanta el tiempo 1 hora).',
'Time format'				=>	'Formato Hora',
'Date format'				=>	'Formato Fecha',
'Default'					=>	'Por defecto',
'Language'					=>	'Idioma',
'Email setting info'		=>	'Seleccione si desea que su dirección de correo electrónico sea visible para otros usuarios o no y si quiere que otros usuarios puedan enviar mensajes de correo electrónico a través del foro (Formulario) o no.',
'Email setting 1'			=>	'Muestra tu dirección de correo.',
'Email setting 2'			=>	'Ocultar dirección de correo pero permite contactarte por formulario.',
'Email setting 3'			=>	'Ocultar dirección de correo y no permitir contactarte por formulario.',
'Privacy options legend'	=>	'Establece tus opciones de privacidad',
'Confirm pass'				=>	'Confirmar contraseña',

'Username too short'		=>	'Los nombres de usuario deben tener al menos 2 caracteres de longitud. Por favor seleccione otro nombre de usuario más largo.',
'Username too long'			=>	'Los nombres de usuario no deben ser superiores a 25 caracteres de longitud. Por favor, elija otro nombre de usuario más corto.',
'Username guest'			=>	'El nombre de usuario (guest) está reservado. Por favor, elija otro nombre de usuario.',
'Username IP'				=>	'Los nombres de usuario no pueden ser en forma de una dirección IP. Por favor, elija otro nombre de usuario.',
'Username reserved chars'	=>	'Los nombres de usuario no puede contener todos los caracteres \ ", y [ o ] a la vez. Por favor, elija otro nombre de usuario.',
'Username BBCode'			=>	'Los nombres de usuario no pueden contener ninguna de las etiquetas de formato de texto (BBCode) que usa el foro. Por favor, elija otro nombre de usuario.',
'Banned username'			=>	'El nombre de usuario que ha introducido está prohibido en este foro. Por favor, elija otro nombre de usuario.',
'Pass too short'			=>	'Las contraseñas deben tener al menos 4 caracteres de longitud. Por favor, elija otra contraseña mas larga.',
'Pass not match'			=>	'Las contraseñas no coinciden.',
'Banned email'				=>	'La dirección de correo electrónico que ha introducido está prohibida en este foro. Por favor, elija otra dirección de correo electrónico.',
'Dupe email'				=>	'Otra persona ya está registrado con esa dirección de correo electrónico. Por favor, elija otra dirección de correo electrónico.',
'Sig too long'				=>	'Las firmas no pueden ser mas largas de %1$s caracteres. Por favor reduce tu firma a %2$s caracteres.',
'Sig too many lines'		=>	'Las firmas no pueden tener mas de %s lineas.',
'Bad ICQ'					=>	'Has introducido un ICQ UIN invalido. Por favor, regresa y corrigelo.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
