<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'Menú del perfil',
'Section essentials'			=>	'Esenciales',
'Section personal'				=>	'Personal',
'Section messaging'				=>	'Mensajería',
'Section personality'			=>	'Personalidad',
'Section display'				=>	'Mostrar',
'Section privacy'				=>	'Privacidad',
'Section admin'					=>	'Administración',

// Miscellaneous
'Username and pass legend'		=>	'Introduzca su nombre de usuario y contraseña',
'Personal details legend'		=>	'Introduzca sus detalles personales',
'Contact details legend'		=>	'Introduzca los datos de mensajería',
'User activity'					=>	'Actividad del usuario',
'Paginate info'					=>	'Ingrese el número de temas y mensajes que desea ver en cada página.',

// Password stuff
'Pass key bad'					=>	'La clave de activación para la contraseña es incorrecta o ha caducado. Por favor, vuelva a solicitar una nueva contraseña. Si eso no funciona, póngase en contacto con el administrador del foro en',
'Pass updated'					=>	'Su contraseña se ha actualizado. Ahora puede ingresar con su nueva contraseña.',
'Pass updated redirect'			=>	'Contraseña actualizada. Redireccionando …',
'Wrong pass'					=>	'Antigua contraseña incorrecta.',
'Change pass'					=>	'Cambiar contraseña',
'Change pass legend'			=>	'Ingrese y confirme su nueva contraseña',
'Old pass'						=>	'Antigua contraseña',
'New pass'						=>	'Nueva contraseña',
'Confirm new pass'				=>	'Confirmar nueva contraseña',
'Pass info'						=>	'Las contraseñas deben tener al menos 4 caracteres de longitud. Las contraseñas distinguen entre mayúsculas y minúsculas.',

// Email stuff
'Email key bad'					=>	'La clave de activación para la contraseña es incorrecta o ha caducado. Por favor, vuelva a solicitar una nueva contraseña. Si eso no funciona, póngase en contacto con el administrador del foro en',
'Email updated'					=>	'Su dirección de correo electrónico se ha actualizado.',
'Activate email sent'			=>	'Un correo electrónico ha sido enviado a la dirección especificada con instrucciones sobre cómo activar la nueva dirección de email. Si no llega usted puede comunicarse con el administrador del foro en',
'Email legend'					=>	'Introduzca su nueva dirección de correo',
'Email instructions'			=>	'Un correo electrónico será enviado a su nueva dirección con un enlace de activación. Debe hacer clic en el enlace del correo electrónico que reciba para activar la nueva dirección.',
'Change email'					=>	'Cambiar dirección de correo',
'New email'						=>	'Nueva dirección de correo',

// Avatar upload stuff
'Avatars disabled'				=>	'El administrador ha desactivado el uso de avatares.',
'Too large ini'					=>	'El archivo seleccionado es demasiado grande para cargar. El servidor no permite la carga.',
'Partial upload'				=>	'El archivo seleccionado fue sólo parcialmente cargado. Por favor, inténtelo de nuevo.',
'No tmp directory'				=>	'PHP no pudo guardar el archivo subido a una ubicación temporal.',
'No file'						=>	'Usted no ha seleccionado un archivo para subir.',
'Bad type'						=>	'TEl archivo que trata de subir no es de un tipo permitido. tipos permitidos son gif, jpeg y png.',
'Too wide or high'				=>	'El archivo que trata de subir es más ancho y/o mayore que el máximo permitido',
'Too large'						=>	'El archivo que trata de subir es mayor que el máximo permitido',
'pixels'						=>	'pixels',
'bytes'							=>	'bytes',
'Move failed'					=>	'El servidor no pudo guardar el archivo subido. Por favor, póngase en contacto con el administrador del foro en',
'Unknown failure'				=>	'Ocurrió un error desconocido. Por favor, inténtelo de nuevo.',
'Avatar upload redirect'		=>	'Avatar subido. Redireccionando …',
'Avatar deleted redirect'		=>	'Avatar borrado. Redireccionando …',
'Avatar desc'					=>	'Un avatar es una pequeña imagen que se mostrará bajo su nombre de usuario en sus mensajes. No debe ser más grande que',
'Upload avatar'					=>	'Cargar avatar',
'Upload avatar legend'			=>	'Introduzca una imagen de avatar para cargar',
'Delete avatar'					=>	'Borrar avatar', // only for admins
'File'							=>	'Archivo',
'Upload'						=>	'Cargar', // submit button

// Form validation stuff
'Forbidden title'				=>	'El título que introdujo contiene una palabra prohibida. Usted debe elegir un título diferente.',
'Profile redirect'				=>	'Perfil actualizado. Redireccionando …',

// Profile display stuff
'Users profile'					=>	'%s\'s perfil',
'Username info'					=>	'Usuario: %s',
'Email info'					=>	'Email: %s',
'Posts info'					=>	'Mensajes: %s',
'Registered info'				=>	'Registrado: %s',
'Last post info'				=>	'Ultimo mensaje: %s',
'Show posts'					=>	'Ver todos los mensajes',
'Realname'						=>	'Nombre real',
'Location'						=>	'Localización',
'Website'						=>	'Página Web',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'MSN Messenger',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'Avatar',
'Signature'						=>	'Firma',
'Sig max size'					=>	'Longitud máx: %s caracteres / lineas máx: %s',
'Avatar legend'					=>	'Establezca sus opciones de avatar',
'Avatar info'					=>	'Un avatar es una pequeña imagen que se mostrará en todas las entradas. Usted puede subir una imagen haciendo clic en el enlace de abajo.',
'Change avatar'					=>	'Cambiar avatar',
'Signature legend'				=>	'Redacte su firma',
'Signature info'				=>	'Una firma es un pequeño trozo de texto que se adjunta a sus mensajes. En él, usted puede escribir casi cualquier cosa que le guste. Tal vez le gustaría escribir tu cita favorita o tu signo zodiacal. Todo depende de usted! En su firma se puede usar BBCode, si se le permite en este foro en particular. Puedes ver las características que se permiten y que figuran a continuación siempre que edite su firma.',
'Sig preview'					=>	'Vista previa de la firma:',
'No sig'						=>	'No hay ninguna firma actualmente guardada en su perfil.',
'Signature quote/code/list/h'	=>	'El quote, code, list y otros BBCodes no se permiten en las firmas.',
'Topics per page'				=>	'Temas',
'Posts per page'				=>	'Mensajes',
'Leave blank'					=>	'Leave blank to use forum default.',
'Subscription legend'			=>	'Establezca sus opciones de suscripción',
'Notify full'					=>	'Incluye una versión de texto sin formato de nuevos temas en los correos de notificación de suscripción.',
'Auto notify full'				=>	'Automáticamente suscribirse a todos los temas que publique.',
'Show smilies'					=>	'Mostrar smilies como iconos gráficos.',
'Show images'					=>	'Mostrar imágenes en temas.',
'Show images sigs'				=>	'Mostrar imágenes en firma de usuario.',
'Show avatars'					=>	'Mostrar avatar de usuarios en los temas.',
'Show sigs'						=>	'Mostrar firmas de usuarios.',
'Style legend'					=>	'Selecciona tu plantilla preferida',
'Styles'						=>	'Plantillas',
'Admin note'					=>	'Nota del administrador',
'Pagination legend'				=>	'Introduzca las opciones de paginación',
'Post display legend'			=>	'Defina las opciones de visualización de los mensajes',
'Post display info'				=>	'Si usted tiene una conexión lenta, desactive estas opciones, sobre todo mostrar imágenes en los mensajes y firmas, harán que las páginas se carguen más rápido.',
'Instructions'					=>	'Al actualizar su perfil, se le redirige a esta página.',

// Administration stuff
'Group membership legend'		=>	'Elegir grupo de usuarios',
'Save'							=>	'Guardar',
'Set mods legend'				=>	'Establezca el acceso del moderador',
'Moderator in info'				=>	'Elija que foro se permite moderar a este usuario. Nota: Esto sólo se aplica a los moderadores. Administradores tienen permisos completos en todos los foros.',
'Update forums'					=>	'Actualizar foros',
'Delete ban legend'				=>	'Eliminar (sólo para administradores) o expulsar usuario',
'Delete user'					=>	'Eliminar usuario',
'Ban user'						=>	'Expulsar usuario',
'Confirm delete legend'			=>	'Importante: leer antes de eliminar un usuario',
'Confirm delete user'			=>	'Confirme eliminación de usuario',
'Confirmation info'				=>	'Por favor, confirme que desea eliminar el usuario', // the username will be appended to this string
'Delete warning'				=>	'¡Atención! los usuarios eliminados y/o temas no pueden ser restaurados. Si decide no borrar los mensajes de este usuario, los mensajes sólo se pueden eliminar manualmente en otro momento.',
'Delete posts'					=>	'Elimine los mensajes y los temas que este usuario ha realizado.',
'Delete'						=>	'Borrar', // submit button (confirm user delete)
'User delete redirect'			=>	'Usuario eliminado. Redireccionando …',
'Group membership redirect'		=>	'Pertenencia a grupo guardado. Redireccionando …',
'Update forums redirect'		=>	'Derechos del moderador del foro actualizados. Redireccionando …',
'Ban redirect'					=>	'Redireccionando …',
'No delete admin message'		=>	'Los administradores no pueden ser borrados. Con el fin de eliminar este usuario, primero debe moverlo a un grupo de usuarios diferentes.',

);
