<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'Buscar usuario',
'No search permission'				=>	'Usted no tiene permiso para utilizar la función de búsqueda.',
'Search flood'						=>	'Por lo menos %s segundos tienen que pasar entre cada búsqueda. Por favor, espere %s segundos y trate de buscar de nuevo.',
'Search'							=>	'Buscar',
'Search criteria legend'			=>	'Introduce el critero para buscar',
'Search info'						=>	'Para buscar una palabra clave, introduce un tema o temas a buscar. Separa los temas con espacios. Usa AND (y), OR (o) y NOT (no) para detallar la búesqueda. Para buscar por autor introduce el nombre de usuario del autor de los mensajes que quieres buscar. Usa el caracter asterisco * para coincidencias parciales.',
'Keyword search'					=>	'Buscar palabra clave',
'Author search'						=>	'Buscar autor',
'Search in legend'					=>	'Elegir donde buscar',
'Search in info'					=>	'Selecciona el foro donde quieres buscar y si quieres hacerlo a los asuntos de los mensajes, al texto de los mensajes o en ambos.',
'Search multiple forums info'		=>	'Si no selecciona un foro, se buscará en todos los foros.',
'Forum search'						=>	'Foro',
'All forums'						=>	'Todos los foros',
'Search in'							=>	'Buscar en',
'Message and subject'				=>	'Texto y asunto del tema',
'Message only'						=>	'Texto solo',
'Topic only'						=>	'Asunto solo',
'Sort by'							=>	'Filtrar por',
'Sort order'						=>	'Ordenar',
'Search results legend'				=>	'Selecciona cómo ver los resultados de la búsqueda',
'Search results info'				=>	'Puedes escoger como quieres ordenar y ver los resultados.',
'Sort by post time'					=>	'Fecha',
'Sort by author'					=>	'Autor',
'Sort by subject'					=>	'Asunto',
'Sort by forum'						=>	'Foro',
'Ascending'							=>	'Ascendente',
'Descending'						=>	'Descendente',
'Show as'							=>	'Mostrar resultados como',
'Show as topics'					=>	'Temas',
'Show as posts'						=>	'Mensajes',

// Results
'Search'							=>	'Buscar',
'Search results'					=>	'Resultados de la busqueda',
'Quick search show_new'				=>	'Nuevo',
'Quick search show_recent'			=>	'Activo',
'Quick search show_unanswered'		=>	'Sin respuesta',
'Quick search show_replies'			=>	'Publicado',
'Quick search show_user_topics'		=>	'Temas por %s',
'Quick search show_user_posts'		=>	'Mensajes por %s',
'Quick search show_subscriptions'	=>	'Suscrito por %s',
'By keywords show as topics'		=>	'Temas que los mensajes contengan \'%s\'',
'By keywords show as posts'			=>	'Mensajes que contengan \'%s\'',
'By user show as topics'			=>	'Temas con mensajes por %s',
'By user show as posts'				=>	'Mensajes por %s',
'By both show as topics'			=>	'Temas con mensajes que contengan \'%s\', por %s',
'By both show as posts'				=>	'Mensajes que contengan \'%s\', por %s',
'No terms'							=>	'Tiene que poner una palabra clave y/o un autor para buscar.',
'No hits'							=>	'Su búsqueda no ha dado resultados.',
'No user posts'						=>	'No hay mensajes de este usuario en este foro.',
'No user topics'					=>	'No hay temas de este usuario en este foro.',
'No subscriptions'					=>	'Actualmente no estás suscrito a ningún tema.',
'No new posts'						=>	'No hay temas con nuevos mensajes desde su última visita.',
'No recent posts'					=>	'No hay mensajes nuevos en las últimas 24 horas.',
'No unanswered'						=>	'No hay mensajes sin respuesta en este foro.',
'Go to post'						=>	'Ir al mensaje',
'Go to topic'						=>	'Ir al tema'

);
