<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	' \'allow_url_fopen\' sistemde aktif olmadığı için güncelleme denetimi aktif değil.',
'Upgrade check failed message'		=>	'Bilinmeyen nedenli güncelleme hatalarını kontrol et.',
'Running latest version message'	=>	'FluxBB son sürümünü kullanıyorsunuz.',
'New version available message'		=>	'FluxBB yeni bir sürümü mevcut. %s adresinden yeni sürümü indirebilirsiniz.',
'PHPinfo disabled message'			=>	'The PHP function phpinfo() sunucuda aktif değil.',
'Not available'						=>	'Mevcut değil',
'Forum admin head'					=>	'Forum Yönetimi',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'FluxBB administrator kontrol paneline hoşgeldiniz. Administrator veya moderator olmana bağlı olarak; buradan önemli forum içi görünüm değişikliklerini kontrol edebilirsiniz.  :',
'Welcome 1'							=>	'Forumları ve kategorileri düzenle.',
'Welcome 2'							=>	'Forum ayarlarını ve seçeneklerini düzenle.',
'Welcome 3'							=>	'Kullanıcı ve misafir yetkilerini yönet.',
'Welcome 4'							=>	'Kullanıcı IP istatistiklerini görüntüle.',
'Welcome 5'							=>	'Kullanıcı yasakla.',
'Welcome 6'							=>	'Kelime sansürle.',
'Welcome 7'							=>	'Kullanıcı gruplarını ve yetkilerini ayarla.',
'Welcome 8'							=>	'Eski gönderileri temizle.',
'Welcome 9'							=>	'Mesaj raporlarını sakla.',
'Statistics head'					=>	'İstatistikler',
'FluxBB version label'				=>	'FluxBB versiyon',
'Check for upgrade'					=>	'Güncellemeleri denetle',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'Sunucu yüklemesi',
'Server load data'					=>	'%s - %s kullanıcı çevrimiçi',
'Environment label'					=>	'Koşullar',
'Environment data OS'				=>	'Sistem yönetimi: %s',
'Show info'							=>	'Bilgileri göster',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Hızlandırıcı: %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ionCube PHP Hızlandırıcı',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternatif PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eHızlandırıcı',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Veri Tabanı',
'Database data rows'				=>	'Dizi: %s',
'Database data size'				=>	'Boyut: %s',

);
