<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'			=>	'Böyle bir kayıtlı kullanıcı mevcut değildir. Herhangi bir kullancıyı yasaklamak istiyorsan; özel bir kullanıcı eklemek yerine kullanıcı adı kısmını boş bırakınız.',
'No user ID message'		=>	'Böyle bir kayıtlı ID mevcut değildir.',
'User is admin message'		=>	'%s kullanıcı adı administratordur ve kesinlike yasaklanamaz. Eğer bir administratoru yasaklamak istiyorsanız, öncelikle yetkilerini indirgemelisiniz.',
'User is mod message'		=>	'%s kullanıcı adı moderatordur ve kesinlike yasaklanamaz. Eğer bir moderatoru yasaklamak istiyorsanız, öncelikle yetkilerini indirgemelisiniz.',
'Must enter message'		=>	'En azından bir kullanıcı adı, IP adresi veya e-mail adresi girmelisiniz.',
'Cannot ban guest message'	=>	'Misafir kullanıcı yasaklanamaz.',
'Invalid IP message'		=>	'Yanlış bir IP adresi girdiniz.',
'Invalid e-mail message'	=>	'Girdiğiniz e-mail adresi (ör:. user@domain.com) veya sınırlı e-mail adres alanı (e.g. domain.com) geçersizdir.',
'Invalid date message'		=>	'Girdiğiniz tarih geçmiş ve geçersiz bir tarihtir.',
'Invalid date reasons'		=>	'Tarih; Yıl-Ay-Gün şeklinde olmalıdır ve en azından gelecekden bir günü göstermelidir.',
'Ban added redirect'		=>	'Yasaklama eklendi. Yönlendiriliyorsunuz …' ,
'Ban edited redirect'		=>	'Yasaklama düzenlendi. Yönlendiriliyorsunuz …',
'Ban removed redirect'		=>	'Yasaklama silindi. Yönlendiriliyorsunuz …',

'New ban head'				=>	'Yeni yasaklama',
'Add ban subhead'			=>	'Yasaklama ekle',
'Username label'			=>	'Kullanıcı Adı',
'Username help'				=>	'Yasaklanacak Kullanıcı Adı.',
'Username advanced help'	=>	'Yasaklanacak Kullanıcı Adı. Bir sonraki sayfa\'da özel bir IP  yada e-mail adresi girebilirsiniz.Eğer özel bir IP yada e-mail adresi giricekseniz boş bırakınız.',

'Ban search head'			=>	'Yasaklama arama',
'Ban search subhead'		=>	'Arama kriterlerini giriniz',
'Ban search info'			=>	'Veritabanında yasaklama ara. Bir yada birden fazla terim girebilirsiniz. Forum içinde (*) özel karakteri geçerlidir. Bütün yasaklamaları görüntülemek için bütün boşlukları boş bırakınız.',
'Date help'					=>	'(Yıl-Ay-Gün)',
'Message label'				=>	'Mesaj',
'Expire after label'		=>	'Gününden sonra',
'Expire before label'		=>	'Gününden önce',
'Order by label'			=>	'Arama Alanı',
'Order by username'			=>	'Kullanıcı Adı',
'Order by ip'				=>	'IP',
'Order by e-mail'			=>	'Email',
'Order by expire'			=>	'Bitiş Tarihi',
'Ascending'					=>	'Artan',
'Descending'				=>	'Azalan',
'Submit search'				=>	'Aramayı Gerçekleştir',

'E-mail label'				=>	'Email',
'E-mail help'				=>	'Yasaklamak istediğiniz e-mail adresi (ör:. someone@somewhere.com veya somewhere.com).Daha fazla bilgi için; yetkiler bölümünde " Yasaklanan email adresler izinleri"\'ne bakınız.',
'IP label'					=>	'IP adresi/IP-ranges',
'IP help'					=>	'Yasaklamak istediğiniz IP adresi (ör:. 150.11.110.1 or 150.11.110). Boşluk tuşu ile ayırabilirsiniz. Eğer herhangi bir IP zaten girilmiş ise, Bu veritabanında kullanıcıya ait son IP adresi olarak bilinir.',
'IP help link'				=>	'Bu kullanıcıya ait IP istatistiklerini görüntülemek için %s tıklayınız.',
'Ban advanced head'			=>	'Gelişmiş yasaklama seçenekleri',
'Ban advanced subhead'		=>	'IP veya email ile yasaklama ekle',
'Ban message label'			=>	'Yasaklama mesajı',
'Ban message help'			=>	'Yasaklanan kullanıcı gönderdiğiniz mesajı forum a tekrar bağlandığı zaman alıcaktır.',
'Message expiry subhead'	=>	'Yasaklama mesajı ve sona erme tarihi',
'Ban IP range info'			=>	'Bir kullanıcıyı IP adresini kısıtlarayak yasaklarken, bu kısıtlanan alanın başka bir kullanıcıyla eşleşmesi durumuna çok dikkat edilmelidir.',
'Expire date label'			=>	'Sona erme tarihi',
'Expire date help'			=>	'Yasaklamanın sona ereceği tarih (Biçim: Yıl-Ay-Gün). Manuel olarak yasaklama kaldırmak için boş bırakınız.',

'Results head'				=>	'Sonuçları Görüntüle ',
'Results username head'		=>	'Kullanıcı Adı',
'Results e-mail head'		=>	'Email',
'Results IP address head'	=>	'IP/IP-Aralığı',
'Results expire head'		=>	'Bitiş Tarihi',
'Results message head'		=>	'Mesaj',
'Results banned by head'	=>	'Yasaklayan',
'Results actions head'		=>	'Hareketler',
'No match'					=>	'Eşlenme bulunamadı',
'Unknown'					=>	'Bilinmeyen',

);
