<?php

// Language definitions used in install.php, localized by adaur

$lang_install = array(

'Install message'				=>	' \'config.php\' dosyası mevcut değil veya bozulmuş. Bu FluxBB\'nin henuz kurulumu yapılmadığını ifade eder.',
'Choose install language'		=>	'Script kurulum dilini seçiniz',
'Choose install language info'	=>	'Script kurulum dili. Panel için kullanılan varsayılan dil ağaşıdan ayarlanabilir.',
'Install language'				=>	'Dil Kur',
'Change language'				=>	'Dil\'i değiştir',
'Next'							=>	'Sonraki',
'Already installed'				=>	'FluxBB zaten kurulmuş gözüküyor.  <a href="index.php">here</a> adresine gitmelisiniz.',
'You are running error'			=>	'You are running %1$s version %2$s. FluxBB %3$s requires at least %1$s %4$s to run properly. You must upgrade your %1$s installation before you can continue.',
'My FluxBB Forum'				=>	'My FluxBB Forum',
'Description'					=>	'Malesef hiçkimse FluxBB\'nin ne olduğunu antamaz - Bunu kendiniz görmelisiniz.',
'Username 1'					=>	'Kullanıcı Adı en azından 2 karakter uzunluğunda olmalıdır.',
'Username 2'					=>	'Kullanıcı Adı 25 karakterden fazla olmamalıdır.',
'Username 3'					=>	'Misafir kullanıcı adı kullanılamaz.',
'Username 4'					=>	'Kullanıcı Adı IP adresi biçiminde olmamalıdır.',
'Username 5'					=>	'Kullanıcı adı bütün karakterleri içermeyebilir. \', " gibi.',
'Username 6'					=>	'Kullanıcı adı forum içindeki herhangi bir etiketi içermemelidir. Ör: (BBCode) .',
'Short password'				=>	'Şifre en azından 4 karakterden uzun olmalıdır.',
'Passwords not match'			=>	'Şireler eşleşmiyor.',
'Wrong email'					=>	'Girdiğiniz yönetici e-mail\'i geçersizdir.',
'No board title'				=>	'Panel başlığı girmelisiniz.',
'Error default language'		=>	'Seçilmiş varsayılan dil geçerli görünmüyor.',
'Error default style'			=>	'Seçilmiş varsayılan stil mevcut görünmüyor.',
'No DB extensions'				=>	'Bu PHP koşulları FluxBB\'yi destekleyen herhangi bir veritabınını desteklemiyor.PHP, FluxBB\'nin kurulumu için MySQL,PostgreSQL veya SQLite desteklemek zorundadır.',
'Administrator username'		=>	'Yönetici\'nin Kullanıcı Adı',
'Administrator password 1'		=>	'Yönetici şifre 1',
'Administrator password 2'		=>	'Yönetici şifre 2',
'Administrator email'			=>	'Yönetici e-mail',
'Board title'					=>	'Panel Başlığı',
'Base URL'						=>	'Temel URL',
'Required field'				=>	'bu formda istenilen alandır.',
'FluxBB Installation'			=>	'FluxBB Kurulumu',
'Welcome'						=>	'FluxBB kurmak üzeresiniz. FluxxBB kurmak için, Aşağıdaki form\'u doldurmalısınız. Eğer kurulum sırasında herhangi bir zorlukla karşılaşırsanız, lütfen belgelere göz atınız.',
'Install'						=>	'%s FluxBB kur',
'Errors'						=>	'Aşağıdaki ayarlar düzeltilmelidir:',
'Database setup'				=>	'Veritabanı kurulumu',
'Info 1'						=>	'FluxBB için veritabını kurmak için lutfen istenilen bilgileri giriniz.Kurulum işlemi için bütün bilgileri eksiksiz bilmelisiniz.',
'Select database'				=>	'Veritabanı türünü seçiniz',
'Info 2'						=>	'FluxBB, MySQL, PostgreSQL ve SQLite destekliyor.Eğer veritabanı seçimi aşağıdaki açılan menüde mevcut değil ise,PHP koşulları bu veritabını destelemek zorunda olmadığı anlamına gelir.Her bir veritabının versiyonlarını desteklemesi hakkında ki, daha fazla bilgi FAQ içinde bulunabilir.',
'Dual MySQL'					=>	'FluxBB,PHP ortamının MySQL ile birlikte iki farklı yolun desteklendiğini tespit etti. Bu 2 ayar Gelişmiş ve Standart olarak adlandırıldı. Eğer hangisini kullanıcağını bilmiyorsan, öncelikle Gelişmiş olarak dene. Eğer hata alırsan ,Standart\'ı dene.',
'InnoDB'						=>	'FluxBB MySQL sunucunuzun <a href="http://dev.mysql.com/doc/refman/5.0/en/innodb.html">InnoDB</a> desteklediğini tespit etti. Geniş bir forum çalıştırmak istiyorsanız, bu güzel bir seçim olabilir. eğer emin değilseniz,  InnoDB kullanmamanız tavsiye edilir.',
'Database type'					=>	'Veritabanı Türü',
'Required'						=>	'(İstekler)',
'Database hostname'				=>	'Veritabanınızın sunucu hostname\'ini giriniz',
'Info 3'						=>	'Veritabanı sunucu adresi (Örnek: localhost, db.myhost.com or 192.168.0.15).Eğer veritabınınız varsayılan port\'ta çalışmıyorsa, özel bir port belirtebilirsiniz(Örnek: localhost:3580). SQLite desteği için, boş  veya  \'localhost\' olarak bırakınız.',
'Database server hostname'		=>  'Veritabanı Sunucu Hostname\'i',
'Database enter name'			=>	'Veritabanınızın adını giriniz',
'Info 4'						=>	'FluxBB\'nin kurulmasını istediğiniz veritabınınızın adını giriniz. Veritabanı mevcut olmalıdır.SQLite için, bu veritabanı dosyasına bağlı yoldur. Güvenlik sebebi ile, SQLite veritabını mümkün olduğunca özel bir dizine yerleştirilmesi şiddetle tavsiye olunur.Eğer SQLite veritaban dosyası mevcut değil ise, FluxBB kurmayı deniyecekdir.',
'Database name'					=>	'Veritabanı Adı',
'Database enter informations'	=>	'Veritabanınızın Kullanıcı adı ve şifresini giriniz',
'Database username'				=>	'Veritabanı Kullanıcı Adı',
'Info 5'						=>	'Veritabanınıza bağlandığınız Kullanıcı adı ve şifresini giriniz.SQLite için yoksayınız.',
'Database password'				=>	'Veritabanı Şifresi',
'Database enter prefix'			=>	'Veritabanı önek\'i giriniz',
'Info 6'						=>	'Eğer isterseniz, bir önek belirtebilirsiniz. Böylece, aynı veritabanı içinde FluxBB\'nin birden fazla kopyasını çalıştırabilirsiniz.(Örnek: foo_).',
'Table prefix'					=>	'Önek',
'Administration setup'			=>	'Yönetici Kurulumu',
'Info 7'						=>	'FluxBB kurulumunuzda bir yönetici kurulumu gerçekleştirmek için istenilen bilgileri giriniz.',
'Admin enter username'			=>	'Yöneticinin kullanıcı adını giriniz',
'Info 8'						=>	'Forum yönetici kullanıcı adı. Daha sonra daha fazla denetmen ve yönetici kurabilirsiniz. Kullanıcı adı 2-25 karakter aralığında olmalıdır.',
'Admin enter password'			=>	'Yönetici şifresi girin ve onaylayın',
'Info 9'						=>	'Şifre en azından 4 karakter olmalıdır. Şifre seçiminde dikkatli ve hassas olunuz.',
'Password'						=>	'Şifre',
'Confirm password'				=>	'Şifre Onayı',
'Admin enter email'				=>	'Yönetici e-mail giriniz',
'Info 10'						=>	'Forum yönetici e-maili.',
'Board setup'					=>	'Panel Kurulumu',
'Info 11'						=>	'FluxBB paneli kurulumu için istenilen bilgileri giriniz.',
'Enter board title'				=>	'Panel başlığı giriniz',
'Info 12'						=>	'Panel pano başlığı (Her sayfanın en üstünde gösterilir).',
'Enter board description'		=>	'Panel açıklaması giriniz',
'Info 13'						=>	'Duyuru tahtası için kısa açıklama (Her sayfanın en üstünde gösterilir). Bu alan HTML içerebilir.',
'Board description'				=>	'Panel Açıklaması',
'Enter base URL'				=>	'FluxBB kurulumu için temel URL\'yi giriniz.',
'Info 14'						=>	'FluxB forumunuzun URL\si(slash kullanmaksızın) (Örnek: http://forum.myhost.com or http://myhost.com/~myuser). Bu <strong>must</strong> doğru olmalıdır, aksi takdirde, yöneticiler ve denetmenler herhangi bir forum kurmaya yetkili olmayacakdır.',
'Choose the default language'	=>	'Varsayılan dili seçiniz',
'Info 15'						=>	'Kullanıcı profilinden varsayılan dil ayarlarını değiştirmeyen kullanıcılar ve misafirler için varsayılan dil.',
'Default language'				=>	'Varsayılan Dil',
'Choose the default style'		=>	'Varsayılan tema ',
'Info 16'						=>	'Kullanıcı profilinden varsayılan tema ayarlarını değiştirmeyen kullanıcılar ve misafirler için varsayılan tema.',
'Default style'					=>	'Varsayılan Tema',
'Start install'					=>	'Kuruluma Başla',
'DB type not valid'				=>	'\'%s\' geçerli bir veritabanı türü değildir',
'Table prefix error'			=>	'\'%s\' önek\'i geçersiz veya uzun karakter içeriyor.. Önek a-z\'ye karakter, herhangi bir rakam ve altı çizili karakter içermelidir. Bir rakam ile başlamamalıdır. Maksimum uzunluk 40 karakterdir. Lütfen farklı bir önek seçiniz.',
'Prefix reserved'				=>	'\'sqlite_\' önek\'i SQLite motoru tarafından kullanılıyor.Lütfen farklı bir önek seçiniz.',
'Existing table error'			=>	'\'%susers\' önek\'i veritabanında zaten mevcut\'%s\'. Bunun anlamı; FluxBB zaten kurulmuş veya başka bir yazılım parçası kurulmuş.Farklı bir önek seçmelisiniz',
'InnoDB off'					=>	'InnoDB aktif görünmüyor.Lütfen MySQL  sunucunuzda InnoDB destekemeyen farklı bir veritabanı dizini seçiniz.',
'Administrators'				=>	'Yöneticiler',
'Administrator'					=>	'Yönetici',
'Moderators'					=>	'Denetmenler',
'Moderator'						=>	'Denetmen',
'Guests'						=>	'Misafirler',
'Guest'							=>	'Misafir',
'Members'						=>	'Üyeler',
'Announcement'					=>	'Açıklamanızı giriniz.',
'Rules'							=>	'Kurallarınızı giriniz',
'Maintenance message'			=>	'Forumlar onarım için geçiçi olarak kapatılmıştır. Lütfen birkaç dakika sonra tekrar deneyiniz.',
'Test post'						=>	'Başlık Deneme',
'Message'						=>	'Eğer FluxBB görünüm kurulumunun çalışıp çalışmadığına bakmak istiyorsanız, giriş yapınız ve forumunuzu yapılandırmak için yönetici kontrol paneline gidiniz.',
'Test category'					=>	'Kategori Deneme',
'Test forum'					=>	'Forum Deneme',
'This is just a test forum'		=>	'Bu sadece deneme forumudur',
'Alert cache'					=>	'<strong>Besmele dizini yazmaya karşı korumalıdır!</strong> FluxBB\'nin düzgün bir şekilde işlemesi için,  <em>%s</em> dizini PHP ile yazilabilir olmalıdır. Uygun dizin yetkilerini ayarlamak için chmod kullanınız. If in doubt, chmod to 0777.',
'Alert avatar'					=>	'<strong>Avatar dizini yazmaya karşı korumalıdır!</strong> Eğer kullanıcıların kendi avatarlarını yüklemesini istiyorsanız  <em>%s</em>dizininin PHP ile yazilabilir olduğunu kontrol ediniz. Daha sonra avatarların farklı bir dizine kayıt altına alınmasını seçebilirsiniz. (bknz Yönetici/Ayarlar). Uygun dizin yetkilerini ayarlamak için chmod kullanınız. If in doubt, chmod to 0777.',
'Alert upload'					=>	'<strong>Bu sunucuda dosya yüklemesi izinsiz gözüküyor!</strong> Eğer kullanıcıların kendi avatarlarını yüklemesini istiyorsanız, PHP içinde file_uploads yapılandırmasını aktif hale getirmelisiniz. file uploads aktif olur olmaz, Yönetici/Ayarlar/Özellikler içinde de aktif hale gelecekdir.',
'FluxBB has been installed'		=>	'FluxBB kurulumu gerçekleştirildi. Kurulumu bitirmek için aşağıdaki talimatları izleyiniz.',
'Final instructions'			=>	'Final Talimatları',
'Info 17'						=>	'Kurulumu bitirmek için, aşağıdaki config.php olarak adlandırılan dosya indirme butonuna tıklamalısınız. Dha sonra bu dosyayı FluxBB kurulumunuzda ki root dizinine yüklemelisiniz.',
'Info 18'						=>	'config.php\'yi yükler yüklemez, FluxBB tamamen kurulmuş olacakdır! Bu noktada, <a href="index.php"> forum anasayfasına gidebilirsiniz.</a>.',
'Download config.php file'		=>	'config.php dosyasını indir',
'FluxBB fully installed'		=>	'FluxBB tamamen kuruldu! Şimdi <a href="index.php">forum anasayfasına gidebilirsiniz. x</a>.',

);
