<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'Profil menüsü',
'Section essentials'			=>	'Temel Ayarlar',
'Section personal'				=>	'Kişisel Ayarlar',
'Section messaging'				=>	'Mesajlaşma Ayarları',
'Section personality'			=>	'Kimlik Ayarları',
'Section display'				=>	'Görünüm Ayarları',
'Section privacy'				=>	'Gizlilik Ayarları',
'Section admin'					=>	'Yönetim Ayarları',

// Miscellaneous
'Username and pass legend'		=>	'Kullanıcı adınız ve şifreniz',
'Personal details legend'		=>	'Kişisel bilgilerinizi giriniz',
'Contact details legend'		=>	'Mesaj tercihlerinizi giriniz',
'User activity'					=>	'Kullanıcı durumu',
'Paginate info'					=>	'Her sayfada kaç başlık ve mesaj görmek istiyorsunuz?',

// Password stuff
'Pass key bad'					=>	'Belirtilen şifre aktivasyon anahtarı hatalı veya süresi geçmiş. Lütfen yeniden şifre talebinde bulununuz. Sorun devam ederse aşağıdaki adresten yönetici ile iletişime geçeniz:',
'Pass updated'					=>	'Şifreniz güncellendi. Yeni şifrenizi kullanarak giriş yapabilirsiniz.',
'Pass updated redirect'			=>	'Şifreniz güncellendi. Yönlendiriliyorsunuz …',
'Wrong pass'					=>	'Hatalı eski şifre.',
'Change pass'					=>	'Şifre değiştir',
'Change pass legend'			=>	'Yeni şifrenizi giriniz ve onaylayınız',
'Old pass'						=>	'Eski şifre',
'New pass'						=>	'Yeni şifre',
'Confirm new pass'				=>	'Yeni şifrenizi onaylayınız',
'Pass info'						=>	'Şifreler en az 4 karakter uzunluğunda olmak zorunda olup büyük/küçük harflere duyarlıdır.',

// Email stuff
'Email key bad'					=>	'Belirtilen e-posta aktivasyon anahtarı hatalı veya süresi geçmiş. Lütfen e-posta adres değişikliği ile yeni bir talepte bulununuz. Sorun devam ederse aşağıdaki adresten yönetici ile iletişime geçiniz.',
'Email updated'					=>	'E-posta adresiniz başarıyla güncelledi.',
'Activate email sent'			=>	'Belirtilen adrese yeni e-posa adresinin nasıl aktif edileceği ile ilgili bir mesaj gönderildi. Mesajı alamazsanız lütfen aşağıdaki adresten yönetici ile iletişime geçiniz.',
'Email legend'					=>	'Yeni e-posta adresinizi giriniz',
'Email instructions'			=>	'Yeni e-posta adresinize aktivasyon bağlantısı içeren bir mesaj gönderildi. Mesaj size ulaştıktan sonra lütfen içerikteki bağlantıya tıklayarak aktivasyon işlemini tamamlayınız.',
'Change email'					=>	'E-posta değişikliği',
'New email'						=>	'Yeni e-posta',

// Avatar upload stuff
'Avatars disabled'				=>	'Avatar kullanımı yönetim tarafından devre dışı bırakıldı.',
'Too large ini'					=>	'Göndermeye çalıştığınız dosya çok büyük. Sunucu bu dosyayı kabul etmedi.',
'Partial upload'				=>	'Seçilen dosya tam olarak yüklenemedi. Lütfen yeniden deneyiniz.',
'No tmp directory'				=>	'Yüklenen dosya geçici bir klasöre kaydedilirken hata oluştu.',
'No file'						=>	'Yükleme için bir dosya seçmediniz.',
'Bad type'						=>	'Yüklemeye çalıştığınız dosya türüne izin verilmiyor. Sadece  gif, jpeg ve png uzantılı dosyaları seçebilirsiniz.',
'Too wide or high'				=>	'Yüklemeye çalıştığınız dosya ebat(lar)ı izin verilenden daha fazla.',
'Too large'						=>	'Yüklemeye çalıştığınız dosya izin verilenden daha büyük.',
'pixels'						=>	'piksel',
'bytes'							=>	'bayt',
'Move failed'					=>	'Sunucu, yüklemeye çalıştığınız dosyayı kaydedemedi. Forum yöneticisi ile iletişime geçiniz:',
'Unknown failure'				=>	'Bilinmeyen bir hata oluştu. Lütfen tekrar deneyiniz.',
'Avatar upload redirect'		=>	'Avatar başrıyla yüklendi. Yönlendiriliyorsunuz …',
'Avatar deleted redirect'		=>	'Avatar silindi. Yönlendiriliyorsunuz …',
'Avatar desc'					=>	'Avatarlar mesajlarda kullanıcı adının hemen altında gösterilen küçük resimlerdir. Avatar limitleri:',
'Upload avatar'					=>	'Avatar yükle',
'Upload avatar legend'			=>	'Yüklemek için bir avatar dosyası seçiniz',
'Delete avatar'					=>	'Avatar sil', // only for admins
'File'							=>	'Dosya',
'Upload'						=>	'Yükle', // submit button

// Form validation stuff
'Forbidden title'				=>	'Kullanmak istediğiniz başlık yasaklanmış bir kelime içeriyor. Lütfen gerekli değişiklikleri yaptıktan sonra tekrar deneyiniz.',
'Profile redirect'				=>	'Profil başarıyla güncellendi.  Yönlendiriliyorsunuz …',

// Profile display stuff
'Users profile'					=>	'%s\'s Profil',
'Username info'					=>	'Kullanıcı adı: %s',
'Email info'					=>	'E-Posta: %s',
'Posts info'					=>	'Mesajlar: %s',
'Registered info'				=>	'Kayıt: %s',
'Last post info'				=>	'Son mesaj: %s',
'Last visit info'				=>	'Son ziyaret: %s',
'Show posts'					=>	'Tüm mesajlarını göster',
'Show topics'					=>	'Tüm konularını göster',
'Show subscriptions'			=>	'Tüm aboneliklerini göster',
'Realname'						=>	'İsim',
'Location'						=>	'Şehir',
'Website'						=>	'Web sitesi',
'Invalid website URL'			=>	'Girdiğiniz web sitesi URL (bağlantısı) geçersiz.',
'Website not allowed'			=>	'Profilinize bir web sitesi eklemek için izin verilmedi.',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'MSN Messenger',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'Avatar',
'Signature'						=>	'İmza',
'Sig max size'					=>	'Maksimum uzunluk: %s karakter / Maksimum satır: %s',
'Avatar legend'					=>	'Avatar gösterim tercihleri',
'Avatar info'					=>	'Avatarlar mesajlarda kullanıcı adının hemen altında gösterilen küçük resimlerdir. Aşağıdaki bağlantıya tıklayarak avatar yükleyebilirsiniz.',
'Change avatar'					=>	'Avatar değiştir',
'Signature legend'				=>	'İmza düzenle',
'Signature info'				=>	'İmzalar mesajlarınızın sonuna otomatik olarak eklenen metinlerdir. İmza olarak sevdiğiniz bir cümleyi kullanabilirsiniz. Bu tamamen sizin zevkinize bırakılmıştır. Yönetim tarafından izn verilmişse BBCode larını da imzanız içinde kullanabilirsiniz. Aşağıdaki listede izin verilen/aktif olan özellikleri bulabilirsiniz.',
'Sig preview'					=>	'İmza önizlemesi:',
'No sig'						=>	'Bu profilde kayıtlı bir imza bulunmamaktadır.',
'Signature quote/code/list/h'	=>	'The quote, code, list, and heading BBCodes are not allowed in signatures.',
'Topics per page'				=>	'Sayfa başına gösterilecek konu sayısı',
'Posts per page'				=>	'Sayfa başına gösterilecek mesaj sayısı',
'Leave blank'					=>	'Forum\'un varsayılan ayarını kullanmak için boş bırakınız.',
'Subscription legend'			=>	'Abonelik seçenekleri',
'Notify full'					=>	'Abonelik bildirim e-postalarında yeni mesajların düz metin sürümünü ekle.',
'Auto notify full'				=>	'Otomatik olarak her mesaj yazdığınız konuya abone ol.',
'Show smilies'					=>	'Gülen yüzleri grafik olarak göster.',
'Show images'					=>	'Mesajlarda resimleri göster.',
'Show images sigs'				=>	'İmzalarda resimleri göster.',
'Show avatars'					=>	'Mesajlarda avatarları göster.',
'Show sigs'						=>	'İmzaları göster.',
'Style legend'					=>	'Stil Tercihi',
'Styles'						=>	'Stiller',
'Admin note'					=>	'Yönetici Notu:',
'Pagination legend'				=>	'Sayfalandırma tercihleri',
'Post display legend'			=>	'Mesaj görüntüleme tercihleri',
'Post display info'				=>	'Eğer yavaş bir bağlantınız varsa, özellikle imzaların ve resimlerin mesajlarda gösterimi devre dışı bırakılması sayfaların daha hızlı yüklenmesini sağlayacaktır.',
'Instructions'					=>	'Profiliniz güncellendikten sonra tekrar bu sayfaya yönlendirleceksiniz.',

// Administration stuff
'Group membership legend'		=>	'Kullanıcı grubu seçimi',
'Save'							=>	'Kaydet',
'Set mods legend'				=>	'Denetmen yap',
'Moderator in info'				=>	'Bu kullanıcının hangi forumları denetleyeceğini belirleyiniz. Not: Bu ayar sadece Denetmenleri kapsar. Yöneticiler tüm forumlarda her zaman tam yetkiye sahiptir.',
'Update forums'					=>	'Forumları güncelle',
'Delete ban legend'				=>	'Sil (Sadece yöneticiler) veya kullanıcıyı banla (yasakla)',
'Delete user'					=>	'Kullanıcı sil',
'Ban user'						=>	'Kullanıcıyı yasakla',
'Confirm delete legend'			=>	'Dikkat: Kullanıcıyı silmeden önce mutlaka okuyunuz.',
'Confirm delete user'			=>	'Kullanıcının silinmesini onaylıyorum',
'Confirmation info'				=>	'Lütfen bu kullanıcı silmek istediğinizi onaylayınız', // the username will be appended to this string
'Delete warning'				=>	'Dikkat! Silinen kullanıcılar ve/veya mesajlar geri getirilemez. Bu kullanıcı tarafından gönderilen mesajları şu anda silmek istemiyorsanız ilgili mesajları sonradan silebilirsiniz.',
'Delete posts'					=>	'Bu kullanıcının gönderdiği tüm mesaj ve konuları sil',
'Delete'						=>	'Sil', // submit button (confirm user delete)
'User delete redirect'			=>	'Kullanıcı başarıyla silindi.Yönlendiriliyorsunuz …',
'Group membership redirect'		=>	'Grup üyeliği kaydedildi. Yönlendiriliyorsunuz …',
'Update forums redirect'		=>	'Denetmen yetkileri güncellendi. Yönlendiriliyorsunuz  …',
'Ban redirect'					=>	'Yönlendiriliyorsunuz …',
'No delete admin message'		=>	'Yöneticiler silinemez. Bu kullanıcıyı silmek için, önce onu farklı bir kullanıcı grubuna taşımak gerekir.',

);
