<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Geçerli bir e-posta adresi giriniz.',
'Email legend 2'			=>	'Geçerli bir e-posta adresi girip onaylayınız.',
'Localisation legend'		=>	'Yerelleştirme tercihleriniz',
'Time zone'					=>	'Zaman dilimi:',
'Time zone info'			=>	'Forumun saati doğru gösterebilmesi için lütfen yerel saatinizi seçiniz. Yaz Saati uygulaması varsa, ayrıca sağlanan seçeneği kontrol etmelisiniz. ',
'DST'						=>	'Yaz Saati uygulaması var.',
'Time format'				=>	'Saat biçimi',
'Date format'				=>	'Tarih biçimi',
'Default'					=>	'Varsayılan',
'Language'					=>	'Forumu görüntülemek için hangi dili kullanacağınızı seçiniz',
'Email setting info'		=>	'E-posta adresinizin diğer kullanıcılar tarafından görüntülenmesine izin verip vermediğinizi belirleyebilir ve forum üzerinden e-posta almayla ilgili tercihinizi seçiniz.',
'Email setting 1'			=>	'E-posta adresimi göster.',
'Email setting 2'			=>	'E-posta adresimi gizle ve forumdan bana e-posta gönderilmesine izin ver',
'Email setting 3'			=>	'E-posta adresimi gizle ve forumdan bana e-posta gönderilmesine izin verme',
'Privacy options legend'	=>	'Gizlilik tercihlerinizi seçiniz',
'Confirm pass'				=>	'Şifrenizi onaylayın',

'Username too short'		=>	'Kullanıcı adı en az 2 karakter olmalıdır. Lütfen daha uzun bir kullanıcı adı seçiniz.',
'Username too long'			=>	'Kullanıcı adı en fazla 25 karakter olmalıdır. Lütfen daha kısa bir kullanıcı adı seçiniz.',
'Username guest'			=>	'Guest kullanıcı adı sistem tarafından ayrılmıştır. Lütfen farklı bir kullanıcı adı seçiniz.',
'Username IP'				=>	'Kullanıcı adı IP adresleri biçiminde olmamalıdır. Lütfen farklı bir kullanıcı adı seçiniz.',
'Username reserved chars'	=>	'Kullanıcı adı aşağıdaki karakterleri içeremez: \', " ve [ veya ]. Lütfen farklı bir kullanıcı adı seçiniz.',
'Username BBCode'			=>	'Kullanıcı adı forum tarafından kullanılan BBcode etiketlerini larını içeremez. Lütfen farklı bir kullanıcı adı seçiniz.',
'Banned username'			=>	'Seçmiş olduğunuz kullanıcı adı yasaklanmıştır. Lütfen farklı bir kullanıcı adı seçiniz.',
'Pass too short'			=>	'Şifreler en az 4 karakter olmalıdır. Lütfen daha uzun bir şifre seçiniz.',
'Pass not match'			=>	'Şifreler uyuşmuyor.',
'Banned email'				=>	'Girdiğiniz e-posta adresi forum yöneticisi tarafından yasaklanmıştır. Lütfen farklı bir e-posta adresi seçiniz veya yönetici ile irtibata geçiniz.',
'Dupe email'				=>	'Bu e-posta adresi başka bir kullanıcı tarafından kullanılmaktadır. Lütfen farklı bir e-posta adresi seçiniz.',
'Sig too long'				=>	'İmzalar %1$s karakterden uzun olamaz. Lütfen imzanızı %2$s karakterden düşürünüz.',
'Sig too many lines'		=>	'İmzalar %s satırdan fazla satır içeremez.',
'Bad ICQ'					=>	'Hatalı bir ICQ Numarası girdiniz. Lütfen geri giderek hatayı düzeltiniz.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Moscow, Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Yekaterinburg',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Krasnoyarsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita, Irkutsk',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Vladivostok',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Magadan',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands, Kamchatka',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
