<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'All forums'						=>	'Tüm Forumlar',
'Ascending'							=>	'Artan',
'Author search'						=>	'Yazar arama',
'Descending'						=>	'Azalan',
'Forum search'						=>	'Forum',
'Keyword search'					=>	'Kelime arama',
'Message and subject'				=>	'Mesaj metni ve konu başlığı',
'Message only'						=>	'Sadece mesaj metni',
'No search permission'				=>	'Arama yapmak için gerekli izne sahip değilsiniz.',
'Search criteria legend'			=>	'Aranacak sözcük(ler)',
'Search flood'						=>	'Aramlar arasında en az %s saniye geçmesi gerekiyor. Lütfen bir süre bekledikten sonra tekrar arama yapınız.',
'Search in info'					=>	'Hangi forumda arama yapılacağını ve aramanın konu başlıklarında  mı, mesaj metinlerinde mi ya da ikisinde birden mi yapılacağını seçiniz.',
'Search in legend'					=>	'Nerede arama yapılacağını seçiniz',
'Search in'							=>	'Burada ara',
'Search info'						=>	'Anahtar kelime ile arama yapmak için ilgili sözcük(ler) giriniz. Birden fazla kelime varsa kelimelerin aralarına birer boşluk bırakarak birbirinden ayırınız. Gelişmiş arama yapmak için AND, OR  veya NOT ifadelerini kullanabilirsiniz. Yazara göre arama yapmak için kullanıcı ismini yazarak arama yapınız. Kısmi eşleşme ye dayalı arama yapmak için  *  ibaresini kullabilirsiniz.',
'Search multiple forums info'		=>	'Eğer forum seçilmediyse tüm forumlarda arama yapılacaktır.',
'Search results info'				=>	'Sonuçların nasıl sıralanacağını ve gösterileceğini seçiniz.',
'Search results legend'				=>	'Arama sonuçlarını nasıl görmek istediğinizi seçiniz',
'Search'							=>	'Arama',
'Show as posts'						=>	'Mesajlar',
'Show as topics'					=>	'Konular',
'Show as'							=>	'Sonuçları şu şekilde göster',
'Sort by author'					=>	'Yazar',
'Sort by forum'						=>	'Forum',
'Sort by post time'					=>	'Mesaj saati',
'Sort by subject'					=>	'Başlık',
'Sort by'							=>	'Sıralama kriteri',
'Sort order'						=>	'Sıralama düzeni',
'Topic only'						=>	'Sadece konu başlığı',
'User search'						=>	'Kullanıcı arama',

// Results
'Search'							=>	'Arama',
'Search results'					=>	'Arama sonuçları',
'Quick search show_new'				=>	'Yeni',
'Quick search show_recent'			=>	'Aktif',
'Quick search show_unanswered'		=>	'Cevaplanmamış',
'Quick search show_replies'			=>	'Tarih',
'Quick search show_user_topics'		=>	'Topics by %s',
'Quick search show_user_posts'		=>	'Posts by %s',
'Quick search show_subscriptions'	=>	'Subscribed by %s',
'By keywords show as topics'		=>	'Topics with posts containing \'%s\'',
'By keywords show as posts'			=>	'Posts containing \'%s\'',
'By user show as topics'			=>	'Topics with posts by %s',
'By user show as posts'				=>	'Posts by %s',
'By both show as topics'			=>	'Topics with posts containing \'%s\', by %s',
'By both show as posts'				=>	'Posts containing \'%s\', by %s',
'No terms'							=>	'Arama yapmak için en az bir anahtar kelime ya da yazar adı seçmelisiniz.',
'No hits'							=>	'Sonuç bulunamadı.',
'No user posts'						=>	'Bu kullanıcı tarafından foruma hiç bir mesaj gönderilmedi.',
'No user topics'					=>	'There are no topics by this user in this forum.',
'No subscriptions'					=>	'This user is currently not subscribed to any topics.',
'No new posts'						=>	'Son ziyaretinizden bu yana yeni bir mesaj gönderilmedi.',
'No recent posts'					=>	'Son 24 saat içinde yeni bir konu açılmadı',
'No unanswered'						=>	'Bu forumda cevapsız ileti bulunmamaktadır.',
'Go to post'						=>	'Mesaja git',
'Go to topic'						=>	'Konuya git'

);
