<?php

// Language definitions used in admin-users.php
$lang_admin_users = array(

'Non numeric message'		=>	'数字のみ入力可能な項目に非数字が入力されています。',
'Invalid date time message'	=>	'不正な日付／時間が入力されています。',
'Not verified'				=>	'未確認',
'User search head'			=>	'ユーザーを検索',
'User search subhead'		=>	'検索条件',
'User search info'			=>	'データベース内のユーザーを検索します。１つまたは複数の検索条件を入力します。星印(*)でワイルドカードを指定することもできます。',
'Username label'			=>	'ユーザー名',
'E-mail address label'		=>	'メールアドレス',
'Title label'				=>	'タイトル',
'Real name label'			=>	'フルネーム',
'Website label'				=>	'ウェブサイト',
'Jabber label'				=>	'Jabber',
'ICQ label'					=>	'ICQ',
'MSN label'					=>	'MSN メッセンジャー',
'AOL label'					=>	'AOL IM',
'Yahoo label'				=>	'Yahoo メッセンジャー',
'Location label'			=>	'住所',
'Signature label'			=>	'署名',
'Admin note label'			=>	'管理人メモ',
'Posts more than label'		=>	'投稿数（以上）',
'Posts less than label'		=>	'投稿数（未満）',
'Last post after label'		=>	'最終投稿日（以後）',
'Date help'					=>	'(yyyy-mm-dd hh:mm:ss)',
'Last post before label'	=>	'最終投稿日（以前）',
'Registered after label'	=>	'登録日（以後）',
'Registered before label'	=>	'登録日（以前）',
'Order by label'			=>	'表示順',
'Order by username'			=>	'ユーザー名',
'Order by e-mail'			=>	'メールアドレス',
'Order by posts'			=>	'投稿数',
'Order by last post'		=>	'最終投稿日時',
'Order by registered'		=>	'登録日',
'Ascending'					=>	'昇順',
'Descending'				=>	'降順',
'User group label'			=>	'グループ',
'All groups'				=>	'すべてのグループ',
'Unverified users'			=>	'未確認ユーザー',
'Submit search'				=>	'検索',
'IP search head'			=>	'IPアドレスを検索',
'IP search subhead'			=>	'検索するIPアドレス',
'IP address label'			=>	'IPアドレス',
'IP address help'			=>	'投稿データベースを検索するIPアドレスを入力します。',
'Find IP address'			=>	'検索',

'Results head'				=>	'検索結果',
'Results username head'		=>	'ユーザー名',
'Results username head'		=>	'ユーザー名',
'Results e-mail head'		=>	'メール',
'Results title head'		=>	'タイトル/状態',
'Results posts head'		=>	'投稿数',
'Results admin note head'	=>	'管理人メモ',
'Results actions head'		=>	'アクション',
'Results IP address head'	=>	'IPアドレス',
'Results last used head'	=>	'最終アクセス',
'Results times found head'	=>	'ヒット回数',
'Results action head'		=>	'アクション',
'Results find more link'	=>	'このアドレスのユーザーを検索',
'Results no posts found'	=>	'このユーザーはまだフォーラムに投稿していません。',
'Bad IP message'			=>	'指定のIPアドレスは正しくありません。',
'Results view IP link'		=>	'IP情報を表示',
'Results show posts link'	=>	'投稿を表示',
'Results guest'				=>	'ゲスト',
'Results no IP found'		=>	'指定のIPアドレスはデータベースにありません。',
'No match'					=>	'一致するユーザーがいません。'

);
