<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'このサーバーでは \'allow_url_fopen\' がOFFのためアップグレードチェックができません。',
'Upgrade check failed message'		=>	'アップグレードチェックに失敗しました（原因は不明）。',
'Running latest version message'	=>	'FluxBBの最新バージョンが適用されています。',
'New version available message'		=>	'FluxBBの新しいバージョンがリリースされています。最新バージョンをダウンロード： %s',
'Not available'						=>	'利用不可',
'Forum admin head'					=>	'フォーラム管理',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'管理コントロールパネルにようこそ。ここではフォーラムに必要な情報を設定できます。管理者またはモデレータで操作できる項目が異なります。',
'Welcome 1'							=>	'カテゴリーとフォーラムの管理',
'Welcome 2'							=>	'フォーラムのオプション設定',
'Welcome 3'							=>	'ユーザーとゲストのパーミッション設定',
'Welcome 4'							=>	'ユーザーのIP情報の参照',
'Welcome 5'							=>	'ユーザーのアクセス制限',
'Welcome 6'							=>	'禁止用語の設定',
'Welcome 7'							=>	'ユーザーのランク設定',
'Welcome 8'							=>	'古い投稿の整理',
'Welcome 9'							=>	'通報処理',
'About head'						=>	'About FluxBB',
'FluxBB version label'				=>	'FluxBBのバージョン',
'Check for upgrade'					=>	'アップグレードをチェック',
'FluxBB version data'				=>	'v%s - %s',
'Server statistics label'			=>	'Server statistics',
'View server statistics'			=>	'View server statistics',
'Support label'						=>	'Support',
'Forum label'						=>	'Forum',
'IRC label'							=>	'IRC channel',

// Language definitions used in admin_statistics.php
'PHPinfo disabled message'			=>	'The PHP function phpinfo() has been disabled on this server.',
'Server statistics head'			=>	'Server statistics',
'Server load label'					=>	'サーバーの状態',
'Server load data'					=>	'%s - %s 人のユーザーがオンライン',
'Environment label'					=>	'環境',
'Environment data OS'				=>	'オペレーティングシステム: %s',
'Show info'							=>	'情報を見る',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'アクセラレータ: %s',
'Turck MMCache'						=>	'Turk MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'データベース',
'Database data rows'				=>	'レコード数: %s',
'Database data size'				=>	'サイズ: %s',
);
