<?php

// Language definitions used in admin-groups.php
$lang_admin_groups = array(

'Must enter title message'		=>	'グループ名を入力してください。',
'Title already exists message'	=>	'<strong>%s</strong> というグループは既に存在します。',
'Default group redirect'		=>	'デフォルトグループが設定されました。リダイレクト中 …',
'Cannot remove default message'	=>	'デフォルトグループは削除できません。このグループを削除する場合は、他のグループをデフォルトに設定してください。',
'Group removed redirect'		=>	'グループが削除されました。リダイレクト中 …',
'Group added redirect'			=>	'グループが追加されました。リダイレクト中 …',
'Group edited redirect'			=>	'グループが編集されました。リダイレクト中 …',

'Add groups head'				=>	'グループの追加・設定',
'Add group subhead'				=>	'追加',
'New group label'				=>	'複製元のグループ',
'New group help'				=>	'設定をコピーするグループを選択します。次のページで設定を変更できます。',
'Default group subhead'			=>	'デフォルトグループ',
'Default group label'			=>	'デフォルトグループ',
'Default group help'			=>	'登録ユーザーが最初に属するグループです。セキュリティ的な理由で、登録ユーザーは最初からモデレータや管理者グループには属せません。',
'Existing groups head'			=>	'グループの編集・削除',
'Edit groups subhead'			=>	'編集・削除',
'Edit groups info'				=>	'管理者、モデレータ、ゲスト、メンバーは削除できませんが編集は可能です。グループによっては設定できないオプションがあります（ゲストグループの<em>投稿の編集</em>など）。管理者は常にすべての権限を持ちます。',
'Edit link'						=>	'編集',
'Delete link'					=>	'削除',
'Group delete head'				=>	'グループの削除',
'Confirm delete subhead'		=>	'グループ削除の確認',
'Confirm delete info'			=>	'<strong>%s</strong> グループを削除します。よろしいですか？',
'Confirm delete warn'			=>	'警告！削除したグループは復旧できません。',
'Delete group head'				=>	'グループの削除',
'Move users subhead'			=>	'グループ内ユーザーの移動',
'Move users info'				=>	'<strong>%s</strong> グループには <strong>%s</strong> 人のメンバーがいます。メンバーを移動するグループを選んでください。',
'Move users label'				=>	'移動先のグループ',
'Delete group'					=>	'グループを削除',

'Group settings head'			=>	'グループ設定',
'Group settings subhead'		=>	'グループのオプションとパーミッション',
'Group settings info'			=>	'下のオプションとパーミッションはグループに属するユーザーのデフォルト権限です。これらのオプションは各フォーラムで特に制限されていない場合に適用されます。',
'Group title label'				=>	'グループ名',
'User title label'				=>	'ユーザー名',
'User title help'				=>	'この名前はランクより優先して表示されます。グループ名やランクを表示する場合はブランクのままにします。',
'Mod privileges label'			=>	'モデレータ権限',
'Mod privileges help'			=>	'グループユーザーにはモデレータ権限が与えられ、１つまたは複数のフォーラムをモデレートします。設定はユーザープロフィールの管理ページで行います。',
'Edit profile label'			=>	'プロフィールの編集',
'Edit profile help'				=>	'モデレータ権限がある場合、ユーザーのプロフィールを編集することを許可します。',
'Rename users label'			=>	'ユーザー名の変更',
'Rename users help'				=>	'モデレータ権限がある場合、ユーザーの名前を変更することを許可します。',
'Change passwords label'		=>	'パスワードの変更',
'Change passwords help'			=>	'モデレータ権限がある場合、ユーザーのパスワードを変更することを許可します。',
'Ban users label'				=>	'ユーザーの規制',
'Ban users help'				=>	'モデレータ権限がある場合、ユーザーを規制することを許可します。',
'Read board label'				=>	'フォーラムの閲覧',
'Read board help'				=>	'このグループのユーザーにフォーラムの閲覧を許可します。この設定はフォーラムごとの設定より優先されます。"いいえ"に設定した場合、このグループのユーザーは登録、ログイン、ログアウトしかできません。',
'View user info label'			=>	'ユーザーの閲覧',
'View user info help'			=>	'ユーザーリストと各ユーザーのプロフィールの閲覧を許可します。',
'Post replies label'			=>	'トピックの投稿',
'Post replies help'				=>	'既存トピックへの投稿を許可します。',
'Post topics label'				=>	'トピックの作成',
'Post topics help'				=>	'新しいトピックの作成を許可します。',
'Edit posts label'				=>	'投稿の編集',
'Edit posts help'				=>	'自分の投稿の編集を許可します。',
'Delete posts label'			=>	'投稿の削除',
'Delete posts help'				=>	'自分の投稿の削除を許可します。',
'Delete topics label'			=>	'トピックの削除',
'Delete topics help'			=>	'自分が作成したトピックの削除（すべての返信を含む）を許可します。',
'Set own title label'			=>	'ユーザータイトルの設定',
'Set own title help'			=>	'自分のユーザータイトルの設定を許可します。',
'User search label'				=>	'ユーザーの検索',
'User search help'				=>	'ユーザーの検索を許可します。',
'User list search label'		=>	'ユーザーリストでの検索',
'User list search help'			=>	'ユーザーリストでのフリーワード検索を許可します。',
'Send e-mails label'			=>	'メールの送信',
'Send e-mails help'				=>	'他のユーザーへのメールの送信を許可します。',
'Post flood label'				=>	'投稿間隔',
'Post flood help'				=>	'次の投稿ができるまでの待ち時間（単位：秒）。0（ゼロ）は無効。',
'Search flood label'			=>	'検索間隔',
'Search flood help'				=>	'次の検索ができるまでの待ち時間（単位：秒）。0（ゼロ）は無効。',
'E-mail flood label'			=>	'メール間隔',
'E-mail flood help'				=>	'次のメールが送信できるまでの待ち時間（単位：秒）。0（ゼロ）は無効。',
'Moderator info'				=>	' このグループのユーザーはモデレータ権限を持ちますが、１つまたは複数のフォーラムのモデレータに任命する必要があることに注意してください。モデレータへの任命はプロフィールの管理ページで設定できます。',

);
