<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'メールアドレスの設定',
'Email legend 2'			=>	'メールアドレスの入力と確認',
'Localisation legend'		=>	'ロケーションの設定',
'Time zone'					=>	'タイムゾーン',
'Time zone info'			=>	'正確な時間を表示するために、あなたの地域を選択してください。夏時間がある地域なら「夏時間を適用」をチェックしてください。',
'DST'						=>	'夏時間を適用',
'Time format'				=>	'時間の書式',
'Date format'				=>	'日付の書式',
'Default'					=>	'初期値',
'Language'					=>	'言語',
'Email setting info'		=>	'メールアドレスの扱いを選択します。',
'Email setting 1'			=>	'他のユーザーにメールアドレスを表示',
'Email setting 2'			=>	'メールアドレスを隠す（メールの受信は可）',
'Email setting 3'			=>	'メールアドレスを隠す（メールの受信も不可）',
'Privacy options legend'	=>	'プライバシーオプションの設定',
'Confirm pass'				=>	'パスワードの確認',

'Username too short'		=>	'ユーザー名は、最低でも２文字（半角）以上にしてください。',
'Username too long'			=>	'ユーザー名は、25文字（半角）より短くしてください。',
'Username guest'			=>	'ユーザー名に「guest」は使用できません。他のユーザー名を入力してください。',
'Username IP'				=>	'IPアドレス形式のユーザー名は指定できません。他のユーザー名を入力してください。',
'Username reserved chars'	=>	'ユーザー名に \'、" そして [ や ] は使えません。他のユーザー名を入力してください。',
'Username BBCode'			=>	'ユーザー名に BBCode タグは使えません。他のユーザー名を入力してください。',
'Banned username'			=>	'入力されたユーザー名はアクセス制限されています。他のユーザー名を入力してください。',
'Pass too short'			=>	'パスワードは、最低でも４文字（半角）以上で入力してください。',
'Pass not match'			=>	'パスワードが一致しません。',
'Banned email'				=>	'入力されたメールアドレスはアクセス制限されています。他のメールアドレスを入力してください。',
'Dupe email'				=>	'入力されたメールアドレスは既に登録されています。他のメールアドレスを入力してください。',
'Sig too long'				=>	'署名は%1$s文字以下で入力してください。%2$s文字短くしてください。',
'Sig too many lines'		=>	'署名は%s行以内で入力してください。',
'Bad ICQ'					=>	'IQC が不正です。修正してください。',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
