<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'ユーザー名で検索',
'No search permission'				=>	'あなたは検索機能を利用する権限がありません。',
'Search flood'						=>	'前の検索から %s 秒過ぎてから検索してください。',
'Search'							=>	'検索',
'Search criteria legend'			=>	'検索条件',
'Search info'						=>	'キーワードは複数の語句をスペースで区切って入力します。AND, OR, NOT も指定できます。投稿者は探したい投稿のユーザー名を入力します。ワイルドカード(*)も指定できます。',
'Keyword search'					=>	'キーワード',
'Author search'						=>	'投稿者',
'Search in legend'					=>	'検索対象',
'Search in info'					=>	'検索するフォーラムを選択します。検索範囲をトピックのタイトルや内容に絞り込めます。',
'Search multiple forums info'		=>	'If no forums are selected, all forums will be searched.',
'Forum search'						=>	'フォーラム',
'All forums'						=>	'すべてのフォーラム',
'Search in'							=>	'検索項目',
'Message and subject'				=>	'トピックの内容とタイトル',
'Message only'						=>	'トピックの内容のみ',
'Topic only'						=>	'トピックのタイトルのみ',
'Sort by'							=>	'ソート項目',
'Sort order'						=>	'ソート順',
'Search results legend'				=>	'検索結果',
'Search results info'				=>	'検索結果の並び替えと表示内容を指定します。',
'Sort by post time'					=>	'投稿時間',
'Sort by author'					=>	'投稿者',
'Sort by subject'					=>	'タイトル',
'Sort by forum'						=>	'フォーラム',
'Ascending'							=>	'昇順',
'Descending'						=>	'降順',
'Show as'							=>	'表示',
'Show as topics'					=>	'トピックを表示',
'Show as posts'						=>	'投稿を表示',

// Results
'Search'							=>	'Search',
'Search results'					=>	'検索結果',
'Quick search show_new'				=>	'新しいトピック',
'Quick search show_recent'			=>	'最近投稿されたトピック',
'Quick search show_unanswered'		=>	'返信のないトピック',
'Quick search show_replies'			=>	'あなたが投稿したトピック',
'Quick search show_user_topics'		=>	'%s のトピック',
'Quick search show_user_posts'		=>	'%s の投稿',
'Quick search show_subscriptions'	=>	'%s が購読中のトピック',
'By keywords show as topics'		=>	'キーワード \'%s\' に一致するトピック',
'By keywords show as posts'			=>	'Posts containing \'%s\'',
'By user show as topics'			=>	'%s の投稿',
'By user show as posts'				=>	'Posts by %s',
'By both show as topics'			=>	'キーワード \'%s\' に一致する %s が投稿したトピック',
'By both show as posts'				=>	'Posts containing \'%s\', by %s',
'No terms'							=>	'キーワードまたは投稿者を指定してください。',
'No hits'							=>	'一致する情報はありません。',
'No user posts'						=>	'指定ユーザーの投稿はありません。',
'No user topics'					=>	'ユーザーが立てたトピックはありません。',
'No subscriptions'					=>	'現在どのトピックも購読していません。',
'No new posts'						=>	'新しいトピックはありません。',
'No recent posts'					=>	'24時間以内の投稿はありません。',
'No unanswered'						=>	'返信のないトピックはありません。',
'Go to post'						=>	'投稿を見る',
'Go to topic'						=>	'トピックを見る'

);
