<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'			=>	'S’ka përdorues të regjistruar me atë emër përdoruesi. Nëse doni të shtohet një dëbim pa e lidhur me një emër përdoruesi specifik, thjesht lëreni emrin e përdoruesit të zbrazët.',
'No user ID message'		=>	'S’ka përdorues të regjistruar me atë ID.',
'User is admin message'		=>	'Përdoruesi %s është një përgjegjës dhe s’mund të dëbohet. Nëse doni të dëboni një përgjegjës, së pari duhet ta zhgradoni.',
'User is mod message'		=>	'Përdoruesi %s është moderator dhe s’mund të dëbohet. Nëse doni të dëboni një moderator, së pari duhet ta zhgradoni.',
'Must enter message'		=>	'Duhet të jepni ose një emër përdoruesi, një adresë IP, ose një adresë email (e pakta).',
'Cannot ban guest message'	=>	'Përdoruesi mysafir s’mund të dëbohet.',
'Invalid IP message'		=>	'Dhatë një IP/interval IP-sh të pavlefshëm.',
'Invalid e-mail message'	=>	'Adresa email (p.sh., përdorues@përkatësi.com) ose përkatësi adrese email (p.sh., përkatësi.com) që dhatë, është e pavlefshme.',
'Duplicate domain message'	=>	'Përkatësia %s është dëbuar tashmë.',
'Duplicate e-mail message'	=>	'Adresa email %s është dëbuar tashmë.',
'Invalid date message'		=>	'Dhatë një datë skadimi të pavlefshme.',
'Invalid date reasons'		=>	'Formati duhet të jetë VVVV-MM-DD dhe data duhet të jetë të paktën një ditë në të ardhmen.',
'Ban added redirect'		=>	'Dëbimi u shtua. Po bëhet ridrejtim…' ,
'Ban edited redirect'		=>	'Dëbimi u përpunua. Po bëhet ridrejtim…',
'Ban removed redirect'		=>	'Dëbimi u hoq. Po bëhet ridrejtim…',

'New ban head'				=>	'Dëbim i ri',
'Add ban subhead'			=>	'Shtoni dëbim',
'Username label'			=>	'Emër përdoruesi',
'Username help'				=>	'Emri i përdoruesit për t’u dëbuar (s’bëhet dallimi mes shkronjash të vogla dhe të mëdha).',
'Username advanced help'	=>	'Emri i përdoruesi për t’u dëbuar (s’bëhet dallimi mes shkronjash të vogla dhe të mëdha). Faqja pasuese do t’ju lejojë të jepni një IP dhe email sipas dëshirës. Nëse thjesht doni të dëboni një IP/interval IP-sh të dhënë, ose një email të dhënë, thjesht lëreni të zbrazët.',

'Ban search head'			=>	'Kërkim dëbimesh',
'Ban search subhead'		=>	'Jepni kriter kërkimi',
'Ban search info'			=>	'Kërkoni te baza e të dhënave për dëbime. Mund të jepni një ose më shumë terma për të cilët të kërkohet. Pranohen shenja të gjithëpushtetshme në formën e yllthesh (*). Që të shfaqen krejt dëbimet, lërini të zbrazëta krejt fushat.',
'Date help'					=>	'(vvvv-mm-dd)',
'Message label'				=>	'Mesazh',
'Expire after label'		=>	'Skadon pas',
'Expire before label'		=>	'Skadon para',
'Order by label'			=>	'Renditi sipas',
'Order by username'			=>	'Emër përdoruesi',
'Order by ip'				=>	'IP',
'Order by e-mail'			=>	'Email',
'Order by expire'			=>	'Datë skadimi',
'Ascending'					=>	'Rritës',
'Descending'				=>	'Zbritës',
'Submit search'				=>	'Parashtroje kërkimin',

'E-mail label'				=>	'Email',
'E-mail help'				=>	'Email-i ose përkatësia e email-it që doni të dëbohet (p.sh., dikush@diku.com ose diku.com). Për më tepër të dhëna, shihni “Lejo adresa email të dëbuara”, te Leje.',
'IP label'					=>	'Adresë IP/Intervale IP-sh',
'IP help'					=>	'Adresa IP ose intervale IP-sh që doni të dëbohen (p.sh., 150.11.110.1 ose 150.11.110). Adresat ndajini me hapësira. Nëse një IP është dhënë tashmë, është IP-ja e fundit e njohur e këtij përdoruesi në bazën e të dhënave.',
'IP help link'				=>	'Klikoni %s që të shihni statistika IP për këtë përdorues.',
'Ban advanced head'			=>	'Rregullime të thelluara dëbimi',
'Ban advanced subhead'		=>	'Shtojini dëbimit IP dhe email',
'Ban message label'			=>	'Mesazh dëbimi',
'Ban message help'			=>	'Një mesazh që do t’i shfaqet përdoruesit të dëbuar kur viziton forumin.',
'Message expiry subhead'	=>	'Mesazh dhe skadim dëbimi',
'Ban IP range info'			=>	'Duhet të jeni shumë i kujdesshëm, kur dëboni një interval IP-sh, për shkak të mundësisë që shumë përdorues të kenë përputhje me të njëjtën IP të pjesshme.',
'Expire date label'			=>	'Datë skadimi',
'Expire date help'			=>	'Data kur duhet të hiqet automatikisht ky dëbim (format: vvvv-mm-dd). Për ta hequr dorazi, lëreni të zbrazët.',

'Results head'				=>	'Përfundime Kërkimi',
'Results username head'		=>	'Emër përdoruesi',
'Results e-mail head'		=>	'Email',
'Results IP address head'	=>	'IP/intervale IP-sh',
'Results expire head'		=>	'Skadon më',
'Results message head'		=>	'Mesazh',
'Results banned by head'	=>	'Dëbuar nga',
'Results actions head'		=>	'Veprime',
'No match'					=>	'S’ka përputhje',
'Unknown'					=>	'E panjohur',

);
