<?php

// Language definitions used in admin_maintenance.php
$lang_admin_maintenance = array(

'Maintenance head'				=>	'Mirëmbajtje forumi',
'Rebuild index subhead'			=>	'Riformo tregues kërkimi',
'Rebuild index info'			=>	'Nëse shtuat, përpunuat ose hoqët postime dorazi te baza e të dhënave, ose nëse keni probleme me kërkimin, duhet të riformoni treguesin e kërkimit. Për funksionimin më të mirë, gjatë riformimit të tij, forumin duhet ta kaloni nën %s. <strong>Riformimi i treguesit të kërkimit mund të zgjasë shumë dhe do të shtojë ngarkesën e shërbyesit gjatë procesit të riformimit!</strong>',
'Posts per cycle label'			=>	'Postime për cikël',
'Posts per cycle help'			=>	'Numri i postimeve që duhen përpunuar për parje faqesh. P.sh., nëse do të jepnit 300, do të përpunohen treqind postime dhe pastaj faqja do të rifreskohej. Kjo bëhet për të penguar që programthit t’i mbarojë koha gjatë procesit të rindërtimit.',
'Starting post label'			=>	'ID postimi ku t’ia fillohet',
'Starting post help'			=>	'ID-ja e postimit ku të fillohet riformimi. Vlera parazgjedhje është ID-ja e parë që përmban baza e të dhënave. Normalisht s’do të donit ta ndryshonit këtë.',
'Empty index label'				=>	'Zbraze treguesin',
'Empty index help'				=>	'Këtë përzgjidheni nëse doni që treguesi juaj i kërkimit të zbrazet, përpara se të riformohet (shihni më poshtë).',
'Rebuild completed info'		=>	'Pasi të jetë plotësuar procesi, do të ridrejtoheni mbrapsht te kjo faqe. Nëse detyroheni ta ndërpritni procesin e riformimit, mbani shënim ID-në e postimit të fundit të përpunuar dhe jepni atë ID+1 te “ID postimi ku t’ia fillohet”, kur/nëse doni të vazhdoni (s’duhet përzgjedhur “Zbraze treguesin”.',
'Rebuild index'					=>	'Riformoje treguesin',
'Rebuilding search index'		=>	'Po riformohet treguesi i kërkimit',
'Rebuilding index info'			=>	'Po riformohet treguesi i kërkimit. Kjo mund jetë kohë e përshtatshme për të bërë një kafe :-)',
'Processing post'				=>	'Po përpunohet postimi <strong>%s</strong> …',
'Click here'					=>	'Klikoni këtu',
'Javascript redirect failed'	=>	'Ridrejtim i vetvetishëm pa sukses. %s që të vazhdohet …',
'Posts must be integer message'	=>	'Postime për cikël duhet të jetë një vlerë e plotë pozitive.',
'Days must be integer message'	=>	'Ditët për krasitje duhet të jenë një vlerë e plotë pozitive.',
'No old topics message'			=>	'S’ka tema që të jenë %s ditë të vjetra. Ju lutemi, zvogëloni vlerën për “Sa ditë të vjetër” dhe riprovoni.',
'Posts pruned redirect'			=>	'Postimet u krasitën. Po bëhet ridrejtim …',
'Prune head'					=>	'Krasiti',
'Prune subhead'					=>	'Krasit postime të vjetra',
'Days old label'				=>	'Sa ditë të vjetër',
'Days old help'					=>	'Numri i ditëve për “e vjetër” që një temë duhet të jetë për t’u krasitur. P.sh., nëse do të jepnit 30 ditë, çdo temë që s’përmbante një postim të një date më pak se 30 ditë do të krasitej.',
'Prune sticky label'			=>	'Krasit tema të fiksuara',
'Prune sticky help'				=>	'Kur aktivizohet, do të krasiten edhe tema që janë të fiksuara.',
'Prune from label'				=>	'Krasit prej forumit',
'All forums'					=>	'Krejt forumet',
'Prune from help'				=>	'Forumi prej të cilit dëshironi të krasiten postime.',
'Prune info'					=>	'Bëni kujdes kur përdorni këtë veçori. <strong>Postimet e krasitura s’mund të rikthehen.</strong> Për funksionimin më të mirë, gjatë krasitjesh, forumin duhet ta kaloni nën %s.',
'Confirm prune subhead'			=>	'Ripohoni krasitje postimesh',
'Confirm prune info'			=>	'Jeni i sigurt se doni të krasiten krejt temat më të vjetra se %s ditë nga %s (%s tema).',
'Confirm prune warn'			=>	'KUJDES! Krasitja e postimeve i fshin ato përgjithnjë.',

);
