<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'S’arrihet të kontrollohet për përmirësim, ngaqë \'allow_url_fopen\' është e çaktivizuar në këtë sistem.',
'Upgrade check failed message'		=>	'Kontrolli për përmirësim dështoi për arsye të panjohur.',
'Running latest version message'	=>	'Po xhironi versionin më të ri të FluxBB-së.',
'New version available message'		=>	'Është hedhur në qarkullim një version i ri i FluxBB-së. Versionin më të ri mund ta shkarkoni te %s.',
'Deleted install.php redirect'		=>	'Kartela u hoq me sukses. Po bëhet ridrejtim …',
'Delete install.php failed'			=>	'S’u hoq dot install.php. Ju lutemi, kryejeni dorazi.',
'Not available'						=>	'Jo i passhëm',
'Forum admin head'					=>	'Administrim forumi',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'Mirë se vini te paneli i kontrollit për administrim të FluxBB-së. Nga këtu, mund të kontrolloni aspekte jetike të platformës. Në varësi nga fakti se jeni një përgjegjës, apo moderator, mundeni:',
'Welcome 1'							=>	'Të sistemoni kategori dhe forume.',
'Welcome 2'							=>	'Të ujdisni mundësi dhe parapëlqime që vlejnë për krejt një forum.',
'Welcome 3'							=>	'Të kontrolloni leje për përdorues dhe mysafirë.',
'Welcome 4'							=>	'Të shihni statistika IP-sh për përdoruesit.',
'Welcome 5'							=>	'Të dëboni përdorues.',
'Welcome 6'							=>	'Të censuroni fjalë.',
'Welcome 7'							=>	'Të krijoni grupe përdoruesish dhe të bëni gradim të tyre.',
'Welcome 8'							=>	'Të krasitni postime të vjetra.',
'Welcome 9'							=>	'T’u jepni udhë raportimeve ndaj postimesh.',
'Alerts head'						=>	'Sinjalizime',
'Install file exists'				=>	'Kartela install.php ekziston akoma, por duhet hequr. %s.',
'Delete install file'				=>	'Fshijeni',
'About head'						=>	'Mbi FluxBB-në',
'FluxBB version label'				=>	'Version FluxBB-je',
'Check for upgrade'					=>	'Kontrollo për përmirësim',
'FluxBB version data'				=>	'v%s - %s',
'Server statistics label'			=>	'Statistika shërbyesi',
'View server statistics'			=>	'Shihni statistika shërbyesi',
'Support label'						=>	'Asistencë',
'Forum label'						=>	'Forum',
'IRC label'							=>	'Kanal IRC',

// Language definitions used in admin_statistics.php
'PHPinfo disabled message'			=>	'Funksioni PHP phpinfo() është çaktivizuar në këtë shërbyes.',
'Server statistics head'			=>	'Statistika shërbyesi',
'Server load label'					=>	'Ngarkesë shërbyesi',
'Server load data'					=>	'%s - %s përdorues në linjë',
'Environment label'					=>	'Mjedis',
'Environment data OS'				=>	'Sistem operativ: %s',
'Show info'							=>	'Shfaq të dhëna',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Përshpejtues: %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Bazë të dhënash',
'Database data rows'				=>	'Rreshta: %s',
'Database data size'				=>	'Madhësi: %s',
);
