<?php

// Language definitions used in admin_options.php
$lang_admin_options = array(

'Bad HTTP Referer message'			=>	'HTTP_REFERER i gabuar. Nëse këto forume i kaluat nga një vendndodhje në një tjetër, ose ndërruat përkatësi, duhet të përditësoni dorazi ULR-në Bazë te baza e të dhënave (shihni për o_base_url te tabela e formësimit) dhe të spastroni fshehtinën duke fshirë krejt kartelat .php te drejtoria /cache.',
'Must enter title message'			=>	'Duhet të jepni një titull platforme.',
'Invalid e-mail message'			=>	'Adresa email që dhatë është e pavlefshme.',
'Invalid webmaster e-mail message'	=>	'Adresa email që dhatë për webmaster-in është e pavlefshme.',
'SMTP passwords did not match'		=>	'Duhet ta jepni dy herë njësoj fjalëkalimin SMTP, që të ndryshohet.',
'Enter announcement here'			=>	'Jepni këtu njoftimin tuaj.',
'Enter rules here'					=>	'Jepni këtu rregullat tuaja.',
'Default maintenance message'		=>	'Forumet janë përkohësisht jashtë funksionimi, për mirëmbajtje. Ju lutemi, riprovoni pas pak minutash.',
'Timeout error message'				=>	'Vlera e “Mbarim kohe në linjë” duhet të jetë më e vogël se vlera e “Mbarim kohe vizite”.',
'Options updated redirect'			=>	'Mundësitë u përditësuan. Po bëhet ridrejtim …',
'Options head'						=>	'Mundësi',

// Essentials section
'Essentials subhead'				=>	'Thelbësore',
'Board title label'					=>	'Titull platforme',
'Board title help'					=>	'Titulli i kësaj platforme (shfaqur në krye të çdo faqeje). Kjo fushë <strong>nuk</strong> mund të përmbajë HTML.',
'Board desc label'					=>	'Përshkrim platforme',
'Board desc help'					=>	'Një përshkrim i shkurtër i kësaj platforme (shfaqur në krye të çdo faqeje). Kjo fushë mund të përmbajë HTML.',
'Base URL label'					=>	'URL Bazë',
'Base URL help'						=>	'URL-ja e plotë e platformës, pa pjerrake në fund (pra, http://www.përkatësiaime.com/forums). Kjo <strong>duhet</strong> të jetë e saktë, që të funksionojë për krejt veçoritë e përgjegjësve dhe moderatorëve. Nëse ju dalin gabime “Referues i gabuar”, gjasat janë që të jetë e pasaktë.',
'Base URL problem'          =>  'Instalimi juaj nuk mbulon shndërrim të automatizuar të emrave ndërkombëtarë të përkatësive. Ngaqë URL-ja juaj bazë përmban shenja speciale, <strong>duhet</strong> të përdorni një shndërrues nga interneti, që të shmangni gabime “Referues i gabuar”.',
'Timezone label'					=>	'Zonë kohore parazgjedhje',
'Timezone help'						=>	'Zona kohore parazgjedhje për mysafirë dhe përdorues që po përpiqen të regjistrohen te platforma.',
'DST label'							=>	'Ujdise për KKD',
'DST help'							=>	'Shihni nëse koha e kursimit të ditës është në fuqi (bën shtyrjen e kohës me 1 orë).',
'Language label'					=>	'Gjuhë parazgjedhje',
'Language help'						=>	'Gjuha parazgjedhje për mysafirë dhe përdorues që s’e kanë vënë ndryshe nga parazgjedhje në profilin e tyre. Nëse hiqni një paketë gjuhësore, kjo duhet përditësuar.',
'Default style label'				=>	'Stil parazgjedhje',
'Default style help'				=>	'Stili parazgjedhje për mysafirë dhe përdorues që s’e kanë vënë ndryshe nga parazgjedhja në profilin e tyre.',

// Essentials section timezone options
'UTC-12:00'							=>	'(UTC-12:00) Në Perëndim të Vijës Ndërkombëtare të Ndryshimit të Datës',
'UTC-11:00'							=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'							=>	'(UTC-10:00) Hauaji-Aleutinet, Ishulli Kuk',
'UTC-09:30'							=>	'(UTC-09:30) Ishujt Markeza',
'UTC-09:00'							=>	'(UTC-09:00) Alaska, Ishulli Gambie',
'UTC-08:30'							=>	'(UTC-08:30) Ishujt Pitkern',
'UTC-08:00'							=>	'(UTC-08:00) E Paqësorit',
'UTC-07:00'							=>	'(UTC-07:00) Malore',
'UTC-06:00'							=>	'(UTC-06:00) Qendrore',
'UTC-05:00'							=>	'(UTC-05:00) Lindore',
'UTC-04:00'							=>	'(UTC-04:00) E Atlantikut',
'UTC-03:30'							=>	'(UTC-03:30) Njufaundland',
'UTC-03:00'							=>	'(UTC-03:00) Amazonë, Groenlandë Qendrore',
'UTC-02:00'							=>	'(UTC-02:00) E Mesit e Atlantikut',
'UTC-01:00'							=>	'(UTC-01:00) Azore, Kepi i Gjelbër, Groenlandë Lindore',
'UTC'								=>	'(UTC) Evropiane Perëndimore, Grinuiç',
'UTC+01:00'							=>	'(UTC+01:00) Evropiane Qendrore, Afrikane Perëndimore',
'UTC+02:00'							=>	'(UTC+02:00) Evropiane Lindore, Afrikane Qendrore, Kaliningrad',
'UTC+03:00'							=>	'(UTC+03:00) Afrikane Lindore, Moskë',
'UTC+03:30'							=>	'(UTC+03:30) Iran',
'UTC+04:00'							=>	'(UTC+04:00) Gjiri, Samara',
'UTC+04:30'							=>	'(UTC+04:30) Afganistan',
'UTC+05:00'							=>	'(UTC+05:00) Pakistan, Jekaterinburg',
'UTC+05:30'							=>	'(UTC+05:30) Indi, Sri Lankë',
'UTC+05:45'							=>	'(UTC+05:45) Nepal',
'UTC+06:00'							=>	'(UTC+06:00) Bangladesh, Butan, Omsk',
'UTC+06:30'							=>	'(UTC+06:30) Ishujt Kokos, Mianmar',
'UTC+07:00'							=>	'(UTC+07:00) Indokinë, Novosibirsk, Krasnojarsk',
'UTC+08:00'							=>	'(UTC+08:00) Kina e Madhe, Australiane Perëndimore, Irkutsk',
'UTC+08:45'							=>	'(UTC+08:45) Australia Juglindore, Perëndimore',
'UTC+09:00'							=>	'(UTC+09:00) Japoni, Kore, Çita, Jakutsk',
'UTC+09:30'							=>	'(UTC+09:30) Australiane Qendrore',
'UTC+10:00'							=>	'(UTC+10:00) Australiane Lindore, Vladivostok',
'UTC+10:30'							=>	'(UTC+10:30) Lord Haue',
'UTC+11:00'							=>	'(UTC+11:00) Ishulli Solomon, Magadan',
'UTC+11:30'							=>	'(UTC+11:30) Ishulli Norfolk',
'UTC+12:00'							=>	'(UTC+12:00) Zelandë e Re, Fixhi, Kamçatka',
'UTC+12:45'							=>	'(UTC+12:45) Ishujt Çatëm',
'UTC+13:00'							=>	'(UTC+13:00) Tonga, Ishujt Feniks',
'UTC+14:00'							=>	'(UTC+14:00) Sporadet Ekuatoriale',

// Timeout Section
'Timeouts subhead'					=>	'Kohë dhe mbarime kohësh',
'Time format label'					=>	'Format kohe',
'PHP manual'						=>	'Doracaku i PHP-së',
'Time format help'					=>	'[Format i tanishëm: %s]. Për mundësi formatimi shihni te %s.',
'Date format label'					=>	'Format datash',
'Date format help'					=>	'[Formati i tanishëm: %s]. Për mundësi formatimi shihni te %s.',
'Visit timeout label'				=>	'Kohë mbarimi vizite',
'Visit timeout help'				=>	'Numër sekondash që një përdorues duhet të jetë i plogësht përpara se të përditësohen të dhënat e vizitës së fundit për të (prek së pari treguesit për mesazhe të reja).',
'Online timeout label'				=>	'Mbarim kohe në linjë',
'Online timeout help'				=>	'Numër sekondash që një përdorues duhet të jetë i plogësht, përpara se të hiqet nga lista e përdoruesve që janë në linjë.',
'Redirect time label'				=>	'Kohë ridrejtimi',
'Redirect time help'				=>	'Numër sekondash që duhet pritur kur bëhet ridrejtim. Në u vëntë 0, s’do të shfaqet faqe ridrejtimi (nuk këshillohet).',

// Display Section
'Display subhead'					=>	'Shfaqje',
'Version number label'				=>	'Numër versioni',
'Version number help'				=>	'Shfaq në fundfaqe numrin e versionit të FluxBB-së.',
'Info in posts label'				=>	'Të dhëna mbi përdoruesin në postime',
'Info in posts help'				=>	'Shfaq të dhëna rreth postuesit nën emrin e përdoruesit, te pamja e temës. Të dhënat që hyjnë këtu janë vendndodhje, datë regjistrimi, numër postimesh dhe lidhje kontakti (email dhe URL).',
'Post count label'					=>	'Numër postimesh përdoruesi',
'Post count help'					=>	'Shfaq numrin e postimeve që ka bërë një përdorues (prek pamjen e temës, profilin dhe listën e përdoruesve).',
'Smilies label'						=>	'Emotikone në postime',
'Smilies help'						=>	'Shndërro emotikonet në ikona të vogla grafike.',
'Smilies sigs label'				=>	'Emotikone në nënshkrime',
'Smilies sigs help'					=>	'Shndërro emotikonet në ikona të vogla grafike te nënshkrimet e përdoruesve.',
'Clickable links label'				=>	'Lidhjet bëji të klikueshme',
'Clickable links help'				=>	'Kur aktivizohet, FluxBB-ja do të pikasë automatikisht çfarëdo URL-sh në postime dhe do t’i bëjë ato tejlidhje të klikueshme.',
'Topic review label'				=>	'Shqyrtim teme',
'Topic review help'					=>	'Numër maksimum postimesh për t’u shfaqur kur postohet (më të rejat të parat). Vëreni 0 që të çaktivizohet.',
'Topics per page label'				=>	'Tema për faqe',
'Topics per page help'				=>	'Numri parazgjedhje i temave për t’u shfaqur për faqe, në një forum. Këtë rregullim përdoruesit mund ta vënë si duan.',
'Posts per page label'				=>	'Postime për faqe',
'Posts per page help'				=>	'Numër parazgjedhje postimesh për t’u shfaqur për faqe, në një temë. Këtë rregullim përdoruesit mund ta vënë si duan.',
'Indent label'						=>	'Madhësi kryeradhe',
'Indent help'						=>	'Në u vëntë 8, do të përdoret një shenjë e zakonshme tabulacioni, kur shfaqet tekst brenda etiketës [code][/code]. Për vlerë tjetër, teksti do të shtyhet në kryeradhë me aq hapësira sa vlera.',
'Quote depth label'					=>	'Maksimum thellësie për [quote]',
'Quote depth help'					=>	'Maksimumi i herëve që një etiketë [quote] mund të shkojë brenda një palë [quote] të tjera, çfarëdo etiketash më thellë se kaq, do të hidhen tej.',

// Features section
'Features subhead'					=>	'Veçori',
'Quick post label'					=>	'Përgjigje e shpejtë',
'Quick post help'					=>	'Kur aktivizohet, FluxBB-ja do të shtojë në fund të temave një formular përgjigjesh të shpejta. Në këtë mënyrë përdoruesit mund të postojnë drejt e nga parja e temës.',
'Users online label'				=>	'Përdorues në linjë',
'Users online help'					=>	'Shfaq te faqja e treguesit të dhëna mbi mysafirë dhe përdorues të regjistruar që janë duke shfletuar aktualisht në platformë.',
'Censor words label'				=>	'Fjalë të censuruara',
'Censor words help'					=>	'Aktivizojeni këtë që të censuroni fjalë specifike në platformë. Për më tepër të dhëna, shihni %s.',
'Signatures label'					=>	'Nënshkrime',
'Signatures help'					=>	'Lejoju përdoruesve t’u bashkëngjitin një nënshkrim postimeve të tyre.',
'User has posted label'				=>	'Përdoruesi ka postuar më herët',
'User has posted help'				=>	'Kjo veçori shfaq një pikë para temave te viewforum.php, në rast se përdoruesi aktualisht i futur në llogarinë e tij, ka postuar më herët në atë temë. Nëse ju del ngarkesë e lartë e shërbyesit, çaktivizojeni.',
'Topic views label'					=>	'Parje temash',
'Topic views help'					=>	'Ndiq numrin e parjeve të një teme. Nëse ju del ngarkesë e lartë e shërbyesit, në një forum me shumë trafik, çaktivizojeni.',
'Quick jump label'					=>	'Kalim i shpejtë',
'Quick jump help'					=>	'Aktivizoni listën hapmbyll të kalimit të shpejtë (kalo te forunm).',
'GZip label'						=>	'Përfundim si GZip',
'GZip help'							=>	'Nëse aktivizohet, FluxBB-ja do të paketojë si .gzip, ç’u jep shfletuesve. Kjo do të reduktojë sasinë e të dhënave të përdorura, por do të përdorë pakëz më tepër CPU. Kjo veçori lyp që PHP-ja të jetë formësuar me zlib (--with-zlib). Shënim: Nëse keni ujdisur tashmë një nga modulet Apache mod_gzip ose mod_deflate të ngjeshin programthet PHP, duhet ta çaktivizoni këtë veçori.',
'Search all label'					=>	'Kërkoni në krejt forumet',
'Search all help'					=>	'Po qe e çaktivizuar, kërkimet do të lejohen vetëm në një forum në herë. Çaktivizojeni, nëse ngarkesa në shërbyes është e lartë, për shkak kërkimesh të tepruara.',
'Menu items label'					=>	'Zëra shtesë menuje',
'Menu items help'					=>	'Duke dhënë tejlidhje HTML në këtë kuadrat teksti, mund të shtohet te menuja e lëvizjeve në krye të krejt faqeve, çfarëdo numri elementësh. Formati për shtim lidhjesh të reja është X = &lt;a href="URL"&gt;LIDHJE&lt;/a&gt;, ku X është pozicioni në të cilin duhet futur lidhja (p.sh., 0 për ta futur në fillim dhe 2 për ta futur pas “Listë përdoruesish”). Zërat ndajini me një ndërprerje rreshti.',

// Feeds section
'Feed subhead'						=>	'Marrje përmes prurjesh',
'Default feed label'				=>	'Lloj parazgjedhje prurjeje',
'Default feed help'					=>	'Përzgjidhni llojin e prurjes për t’u shfaqur. Shënim: Zgjedhja e asnjërës s’do të çaktivizojë prurjet, thjesht, si parazgjedhje, do t’i fshehë.',
'None'								=>	'Asnjë',
'RSS'								=>	'RSS',
'Atom'								=>	'Atom',
'Feed TTL label'					=>	'Kohëzgjatje ruajtjeje në fshehtinë',
'Feed TTL help'						=>	'Prurjet mund të ruhen në fshehtinë, për të ulur përdorimin e burimeve nga prurjet.',
'No cache'							=>	'Mos përdor fshehtinë',
'Minutes'							=>	'%d minuta',

// Reports section
'Reports subhead'					=>	'Raportime',
'Reporting method label'			=>	'Metodë raportimi',
'Internal'							=>	'Brendazi',
'By e-mail'							=>	'Email',
'Both'								=>	'Të dyja',
'Reporting method help'				=>	'Përzgjidhni metodën për trajtimin e raportimeve mbi tema/postime. Mund të zgjidhni nëse raportimet mbi tema/postime të trajtohen nga sistemi i brendshëm i raportimit, t’u dërgohen me email adresave në listën e postimeve (shihni më poshtë), ose që të dyja.',
'Mailing list label'				=>	'Listë postimesh',
'Mailing list help'					=>	'Një listë pajtimtarësh, ndarë me presje. Personat në këtë listë janë marrës të raportimeve.',

// Avatars section
'Avatars subhead'					=>	'Avatarë',
'Use avatars label'					=>	'Përdor avatarë',
'Use avatars help'					=>	'Po qe e aktivizuar, përdoruesit do të jenë në gjendje të ngarkojnë një avatar, i cili do të shfaqet nën titullin e tyre.',
'Upload directory label'			=>	'Drejtori ngarkimi',
'Upload directory help'				=>	'Drejtori ngarkimi për avatarë (relative ndaj drejtorisë rrënjë të FluxBB-së). PHP-ja duhet të ketë leje shkrimi mbi këtë drejtori.',
'Max width label'					=>	'Gjerësi maks.',
'Max width help'					=>	'Gjerësia maksimum e lejuar e avatarëve, në piksel (e këshilluara është 60).',
'Max height label'					=>	'Lartësi maks.',
'Max height help'					=>	'Lartësia maksimum e lejuar e avatarëve, në piksel (e këshilluara është 60).',
'Max size label'					=>	'Madhësi maks.',
'Max size help'						=>	'Madhësia maksimum e lejuar e avatarëve, në bajte (e këshilluara është 10240).',

// E-mail section
'E-mail subhead'					=>	'Email',
'Admin e-mail label'				=>	'Email përgjegjësi',
'Admin e-mail help'					=>	'Adresa email e përgjegjësit të platformës.',
'Webmaster e-mail label'			=>	'Email webmaster-i',
'Webmaster e-mail help'				=>	'Kjo është adresa nga e cila do të dërgohen krejt email-et e dërguar nga platforma.',
'Forum subscriptions label'			=>	'Pajtime në forum',
'Forum subscriptions help'			=>	'Bëjuni të mundur përdoruesve të pajtohen në forume (të marrin email, kur dikush krijon një temë të re).',
'Topic subscriptions label'			=>	'Pajtime në tema',
'Topic subscriptions help'			=>	'Bëjuni të mundur përdoruesve të pajtohen në temë (të marrin email, kur dikush përgjigjet).',
'SMTP address label'				=>	'Adresë shërbyesi SMTP',
'SMTP address help'					=>	'Adresa e një shërbyesi SMTP të jashtëm me të cilin të dërgohen email-et. Mund të specifikoni një numër vetjak porte, nëse shërbyesi SMTP nuk xhiron në portën parazgjedhje 25 (shembull: mail.smtp-ja_ime.com:3580). Që të përdoret programi vendor për postën, lëreni të zbrazët.',
'SMTP username label'				=>	'Emër përdoruesi SMTP',
'SMTP username help'				=>	'Emër përdoruesi për shërbyesin SMTP. Jepni një emër përdoruesi vetëm nëse kërkohet doemos nga shërbyesi SMTP (shumica e shërbyesve <strong>nuk</strong> kërkojnë mirëfilltësim).',
'SMTP password label'				=>	'Fjalëkalim SMTP',
'SMTP change password help'			=>	'I vini shenjë kësaj, nëse doni të ndryshoni ose fshini fjalëkalmin e depozituar aktualisht.',
'SMTP password help'				=>	'Fjalëkalim për shërbyesin SMTP. Jepni një fjalëkalim vetëm nëse kërkohet doemos nga shërbyesi SMTP (shumica e shërbyesve <strong>nuk</strong> kërkojnë mirëfilltësim). Ju lutemi, për ripohim, jepeni dy herë fjalëkalimin tuaj.',
'SMTP SSL label'					=>	'Fshehtëzo SMTP-në duke përdorur SSL',
'SMTP SSL help'						=>	'Fshehtëzon lidhje me shërbyesin SMTP duke përdorur SSL. Duhet përdorur vetëm nëse e kërkon shërbyesi juaj SMTP dhe versioni i PHP-së tuaj mbulon SSL.',

// Registration Section
'Registration subhead'				=>	'Regjistrim',
'Allow new label'					=>	'Lejo regjistrime të reja',
'Allow new help'					=>	'Kontrollon nëse kjo platformë pranon regjistrime të reja. Çaktivizojeni vetëm nën rrethana të posaçme.',
'Verify label'						=>	'Verifiko regjistrimet',
'Verify help'						=>	'Kur aktivizohet, përdoruesve u dërgohet me email një fjalëkalim kuturu, pasi regjistrohen. Ata mandej mund të bëjnë hyrjen dhe ta ndryshojnë fjalëkalimin në profilin e tyre, nëse shohin qar prej kësaj. Kjo veçori kërkon gjithashtu që përdoruesit të verifikojnë adresat e tyre të reja email, nëse vendosin të ndryshojnë atë me të cilën u regjistruan. Kjo është një rrugë e efektshme shmangieje abuzimesh me regjistrimin dhe për të garantuar që krejt përdoruesit kanë adresa email “të sakta” në profilet e tyre.',
'Report new label'					=>	'Raporto regjistrime të reja',
'Report new help'					=>	'Në u aktivizoftë, FluxBB-ja do të njoftojë përdoruesit në listën e postimeve (shihni më sipër), kur te forumet regjistrohet një përdorues i ri.',
'Use rules label'					=>	'Rregulla përdoruesi forumi',
'Use rules help'					=>	'Kur aktivizohet, përdoruesit duhet të pajtohen me një grup rregullash, kur regjistrohen (jepni tekst më poshtë). Rregullat do të mund të shihen përherë përmes një lidhjeje te pjesa e lëvizjes në krye te çdo faqeje.',
'Rules label'						=>	'Jepni këtu rregullat tuaja',
'Rules help'						=>	'Këtu mund të jepni çfarëdo rregullash apo informacion tjetër që përdoruesi duhet të shqyrtojë dhe të pranojë, kur regjistrohet. Nëse më sipër aktivizuat rregullat, duhet të jepni diçka këtu, përndryshe gjëja do të çaktivizohet. Ky tekst s’do të trajtohet si postimet e zakonshme, ndaj mund të përmbajë HTML.',
'E-mail default label'				=>	'Rregullime parazgjedhje email-i',
'E-mail default help'				=>	'Zgjidhni rregullimin parazgjedhje për privatësinë, për regjistrime përdoruesish të rinj.',
'Display e-mail label'				=>	'Shfaqu përdoruesve të tjerë adresë email.',
'Hide allow form label'				=>	'Fshihe adresën email, por lejo email nga formulari.',
'Hide both label'					=>	'Fshihe adresën email dhe mos lejo email nga formulari.',

// Announcement Section
'Announcement subhead'				=>	'Njoftime',
'Display announcement label'		=>	'Shfaq njoftime',
'Display announcement help'			=>	'Aktivizojeni këtë për të shfaqur te platforma mesazhin më poshtë.',
'Announcement message label'		=>	'Mesazh lajmërimi',
'Announcement message help'			=>	'Ky tekst s’do të trajtohet si postimet e rregullta, ndaj mund të përmbajë HTML.',

// Maintenance Section
'Maintenance subhead'				=>	'Mirëmbajtje',
'Maintenance mode label'			=>	'Mënyra mirëmbajtje',
'Maintenance mode help'				=>	'Kur aktivizohet, platforma do të jetë e përdorshme vetëm nga përgjegjësit. Kjo duhet përdorur në rast se platforma duhet nxjerrë jashtë funksionimi përkohësisht, për veprime mirëmbajtjeje. <strong>KUJDES! Mos dilni nga llogaria, kur platforma është nën mënyrën mirëmbajtje.</strong> S’do të jeni në gjendje të bëni më hyrje.',
'Maintenance message label'			=>	'Mesazh mirëmbajtjeje',
'Maintenance message help'			=>	'Mesazhi do t’u shfaqet përdoruesve, kur platforma gjendet nën mënyrën mirëmbajtje. Në u lëntë e zbrazët, do të përdoret një mesazh parazgjedhje. Ky tekst s’do të trajtohet si postimet e rregullta, ndaj mund të përmbajë HTML.',

);
