<?php

// Language definitions used in install.php, localized by adaur

$lang_install = array(

'Choose install language'		=>	'Zgjidhni gjuhën e programthit të instalimit',
'Choose install language info'	=>	'Gjuha e përdorur për këtë program instalimi. Gjuha parazgjedhje e përdorur për vetë platformën mund të caktohet më poshtë.',
'Install language'				=>	'Gjuhë instalimi',
'Change language'				=>	'Ndryshoni gjuhën',
'Already installed'				=>	'Duket se FluxBB është tashmë i instaluar. Në vend të kësaj, duhet të kaloni te <a href="index.php">këtu</a>.',
'You are running error'			=>	'Po xhironi %1$s version %2$s. Që të xhirojë si duhet, FluxBB %3$s ka nevojë për të paktën %1$s %4$s. Duhet të përmirësoni instalimin tuaj %1$s, përpara se të mund të vazhdoni.',
'My FluxBB Forum'				=>	'Forumi im FluxBB',
'Description'					=>	'Mjerisht, s’thotë dot njeri se ç’është FluxBB-ja - duhet ta shihni vetë.',
'Username 1'					=>	'Emrat e përdoruesve duhet të jenë të paktën 2 shenja të gjatë.',
'Username 2'					=>	'Emrat e përdoruesve s’duhet të jenë më të gjatë se 25 shenja.',
'Username 3'					=>	'Emri i përdoruesit mysafir është i rezervuar.',
'Username 4'					=>	'Emrat e përdoruesve s’mund të jenë në formën e një adrese IP.',
'Username 5'					=>	'Emrat e përdoruesve s’mund të përmbajnë njëherësh shenjat \’, " dhe [ ose ].',
'Username 6'					=>	'Emrat e përdoruesve s’mund të përmbajnë çfarëdo etiketash formatimi teksti (BBCode) që përdor forumi.',
'Short password'				=>	'Fjalëkalimet duhet të jenë të paktën 9 shenja të gjata.',
'Passwords not match'			=>	'Fjalëkalimet nuk përputhen.',
'Wrong email'					=>	'Adresa email e përgjegjësit që dhatë është e pavlefshme.',
'No board title'				=>	'Duhet të jepni një titull platforme.',
'Error default language'		=>	'Gjuha parazgjedhje që zgjodhët duket se nuk ekziston.',
'Error default style'			=>	'Stili parazgjedhje i zgjedhur duket se nuk ekziston.',
'No DB extensions'				=>	'Ky mjedis PHP nuk mbulon cilëndo bazë të dhënash që mbulon FluxBB-ja. PHP-ja duhet të ketë mbulim ose për MySQL, ose për PostgreSQL, ose për SQLite, që të mund të instalohet FluxBB-ja.',
'Administrator username'		=>	'Emër përdoruesi i përgjegjësit',
'Administrator email'			=>	'Email i përgjegjësit',
'Board title'					=>	'Titull platforme',
'Base URL'						=>	'URL-ja (pa pjerraken në fund) e forumit tuaj FluxBB. Kjo duhet të jetë e sakta.',
'Required field'				=>	'është një fushë e domosdoshme në këtë formular.',
'FluxBB Installation'			=>	'Instalim FluxBB-je',
'Welcome'						=>	'Ju ndan një hap nga instalimi i FluxBB-së. Që të instalohet FluxBB, duhet të plotësoni formularin e dhënë më poshtë. Nëse hasni çfarëdo vështirësish, me instalimin, ju lutemi, referojuni dokumentimit.',
'Install'						=>	'Instalo FluxBB %s',
'Errors'						=>	'Duhen ndrequr gabimet vijuese:',
'Database setup'				=>	'Ujdisje baze të dhënash',
'Info 1'						=>	'Krejt informacioni që na duhet për të krijuar një lidhje me bazën tuaj të të dhënave.',
'Select database'				=>	'Përzgjidhni llojin e bazës tuaj të të dhënave',
'Info 2'						=>	'Përzgjidhni një bazë të dhënash. Mbulojmë SQLite, MySQL dhe PostgreSQL.',
'Database type'					=>	'Lloj baze të dhënash',
'Required'						=>	'(E domosdoshme)',
'Database hostname'				=>	'Jepni strehëemër shërbyesi për bazën tuaj të të dhënave',
'Info 3'						=>	'Duhet të jeni në gjendje të keni këtë informacion nga streha juaj web, nëse s’funksionon <code>localhost</code>.',
'Database server hostname'		=>	'Strehëemër shërbyesi baze të dhënash',
'Database enter name'			=>	'Jepni emrin e bazës tuaj të të dhënave',
'Info 4'						=>	'Emri i bazës së të dhënave ku doni të instaloni bazën e të dhënave.',
'Database name'					=>	'Emër baze të dhënash',
'Database enter informations'	=>	'Jepni emër përdoruesi dhe fjalëkalimi për bazën tuaj të të dhënave',
'Database username'				=>	'Emër përdoruesi baze të dhënash',
'Info 5'						=>	'Emri i përdoruesit dhe fjalëkalimi juaj për MySQL (shpërfilleni për SQLite).',
'Database password'				=>	'Fjalëkalim baze të dhënash',
'Database enter prefix'			=>	'Jepni parashtesë tabelash baze të dhënash',
'Info 6'						=>	'Nëse doni të xhironi disa instalime FluxBB në një bazë të vetme të dhënash, ndryshojeni këtë.',
'Table prefix'					=>	'Parashtesë tabele',
'Administration setup'			=>	'Ujdisje administrimi',
'Info 7'						=>	'Krijoni llogarinë e parë fare në platformën tuaj.',
'Info 8'						=>	'Emri juaj i përdoruesi duhet të jetë nga 2 deri në 25 karaktere i gjatë. Fjalëkalimi juaj duhet të jetë të paktën 9 shenja i gjatë. Mos harroni që fjalëkalimet janë të ndjeshëm ndaj shkrimit me të madhe a me të vogël.',
'Password'						=>	'Fjalëkalim',
'Confirm password'				=>	'Ripohoni fjalëkalimin',
'Board setup'					=>	'Ujdisje platforme',
'Info 11'						=>	'Rregullime për platformën tuaj. Këtë mund ta ndryshoni më vonë.',
'General information'			=>	'Jepni titullin dhe përshkrimin e platformës tuaj.',
'Board description'				=>	'Përshkrim platforme (mbulohet HTML)',
'Appearance'					=>	'Dukje',
'Info 15'						=>	'Bëjini forumet tuaja si i doni. Zgjidhni një gjuhë dhe një stil për platformën tuaj.',
'Default language'				=>	'Gjuhë parazgjedhje',
'Default style'					=>	'Stil parazgjedhje',
'Start install'					=>	'Nis instalimin',
'DB type not valid'				=>	'\'%s\' s’është lloj i vlefshëm baze të dhënash',
'Table prefix error'			=>	'Parashtesa \'%s\' për tabela përmban shenja të paligjshme ose është shumë i gjatë. Parashtesa mund të përmbajë shkronjat nga a në z, çfarëdo numri dhe shenjën nënvijë. Por s’mund të fillojnë me një numër. Gjatësia maksimum është 40 shenja. Ju lutemi, zgjidhni një parashtesë tjetër',
'Prefix reserved'				=>	'Parashtesa \'sqlite_\' për tabela rezervohet për përdorim nga mekanizmi SQLite. Ju lutemi, zgjidhni një parashtesë tjetër',
'Existing table error'			=>	'Te baza e të dhënave \'%s\' ka tashmë të pranishme një tabelë të quajtur \'%susers\'. Kjo mund të dojë të thotë se FluxBB është tashmë i instaluar, ose se është instaluar një tjetër program dhe ky zë një ose më tepër emra tabelash që i duhen FluxBB. Nëse doni të instaloni disa kopje të FluxBB-it në të njëjtën bazë të dhënash, duhet të zgjidhni një tjetër parashtesë tabelash',
'InnoDB off'					=>	'InnoDB s’duket se është e aktivizuar. Ju lutemi, Zgjidhni një shtresë baze të dhënash që nuk mbulon InnoDB, ose aktivizoni InnoDB te shërbyesi juaj i MySQL-së',
'Administrators'				=>	'Përgjegjës',
'Administrator'					=>	'Përgjegjës',
'Moderators'					=>	'Moderatorë',
'Moderator'						=>	'Moderator',
'Guests'						=>	'Mysafirë',
'Guest'							=>	'Mysafir',
'Members'						=>	'Anëtarë',
'Announcement'					=>	'Jepni këtu lajmërimin tuaj.',
'Rules'							=>	'Jepni këtu rregullat tuaja',
'Maintenance message'			=>	'Forumet janë përkohësisht jashtë funksionimi, për arsye mirëmbajtjeje. Ju lutemi, riprovoni pas pak minutash.',
'Test post'						=>	'Provë teme',
'Message'						=>	'Nëse po shihni për këtë (që mendoj se    po shihni), instalimi i FluxBB-së duket se funksionoi! Tani bëni hyrjen dhe shkoni përpara te paneli i kontrolleve të administrimit, që të formësoni forumin tuaj.',
'Test category'					=>	'Të përgjithshme',
'Test forum'					=>	'Njoftime',
'This is just a test forum'		=>	'Lajme nga bashkësia',
'Alert cache'					=>	'<strong>Drejtoria e fshehtinës aktualisht është e pashkrueshme!</strong> Që FluxBB-ja të funksionojë si duhet, drejtoria <em>%s</em> duhet të jetë e shkrueshme nga PHP-ja. Përdorni urdhrin “chmod” që të caktoni lejet e duhura mbi drejtorinë. Në qofshi në mëdyshje, caktojini si 0777.',
'Alert avatar'					=>	'<strong>Drejtoria e avatarëve aktualisht s’është e shkrueshme!</strong> Nëse doni që përdoruesit të jenë në gjendje të ngarkojnë figura të tyret për avatarët, duhet të kujdeseni që drejtoria <em>%s</em> të jetë e shkrueshme nga PHP-ja. Më vonë mund të zgjidhni të ruani figurat e avatarëve në një drejtori tjetër (shihni Përgjegjës/Mundësi). Përdorni “chmod“ që të caktohen lejet e duhura mbi drejtorinë. Në qofshi në mëdyshje, caktojini si 0777.',
'Alert upload'					=>	'<strong>Duket se ngarkimet e kartelave janë çaktivizuar në këtë shërbyes!</strong> Nëse doni që përdoruesit të jenë në gjendje të ngarkojnë figurat e tyre për avatarë, duhet të aktivizoni rregullimin file_uploads te formësimi në PHP. Pasi të aktivizuar ngarkimi i kartelave, ngarkimi i avatarëve mund të aktivizohet te Administrim/Mundësi/Veçori.',
'FluxBB has been installed'		=>	'FluxBB-ja është instaluar. Që të finalizohet instalimi, ju lutemi, ndiqni udhëzimet më poshtë.',
'Final instructions'			=>	'Udhëzimet përfundimtare',
'Info 17'						=>	'Që të përfundohet instalimi, duhet të klikoni mbi butonin më poshtë që të shkarkohet një kartelë e quajtur config.php. Mandej duhet ta ngarkoni këtë kartelë te drejtoria rrënjë e instalimit tuaj të FluxBB-së.',
'Info 18'						=>	'Pasi të keni ngarkuar config.php, FluxBB-ja do të instalohet plotësisht! Pas asaj, mund të <a href="index.php">kaloni te treguesi i forumit</a>.',
'Download config.php file'		=>	'Shkarko kartelën config.php',
'FluxBB fully installed'		=>	'FluxBB-ja është instaluar plotësisht! Mund të <a href="index.php">kaloni te treguesi i forumeve</a>.',

);
