<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Jepni një adresë email të vlefshme',
'Email legend 2'			=>	'Jepni dhe ripohoni një adresë email të vlefshme',
'Localisation legend'		=>	'Ujdisni mundësitë tuaja për lokalizimin',
'Time zone'					=>	'Zonë kohore',
'Time zone info'			=>	'Që forumi të shfaqë saktë kohët, duhet të përzgjidhni një zonë kohore vendore. Nëse është në fuqi Kohë Kursimi Dite, duhet t’i vini shenjë edhe mundësisë përkatëse, çka do ta shpjerë kohën përpara me 1 orë.',
'DST'						=>	'Koha e Kursimit të Ditës është në fuqi (shpjere kohën përpara me 1 orë).',
'Time format'				=>	'Format kohe',
'Date format'				=>	'Format date',
'Default'					=>	'Parazgjedhje',
'Language'					=>	'Gjuhë',
'Email setting info'		=>	'Përzgjidhni nëse doni që adresa juaj email të jetë e dukshme për përdoruesit e tjerë ose jo dhe nëse doni që përdoruesit e tjerë të jenë në gjendje t’ju dërgojnë email përmes forumit (email nga formulari) ose jo.',
'Email setting 1'			=>	'Shfaquani adresën tuaj email përdoruesve të tjerë.',
'Email setting 2'			=>	'Fshiheni adresën tuaj email, por lejoni email nga formulari.',
'Email setting 3'			=>	'Fshiheni adresën tuaj email dhe mos lejoni email-e nga formulari.',
'Privacy options legend'	=>	'Caktoni mundësitë tuaja për privatësinë',
'Confirm pass'				=>	'Ripohoni fjalëkalimin',

'Username too short'		=>	'Emrat e përdoruesve duhet të jenë të paktën 2 shenja të gjatë. Ju lutemi, zgjidhni një tjetër emër përdoruesi (më të gjatë).',
'Username too long'			=>	'Emrat e përdoruesve s’duhet të jenë më të gjatë se 25 shenja. Ju lutemi, zgjidhni një tjetër emër përdoruesi (më të shkurtër).',
'Username guest'			=>	'Emri i përdoruesit mysafir është i rezervuar. Ju lutemi, zgjidhni një tjetër emër përdoruesi.',
'Username IP'				=>	'Emrat e përdoruesve s’mund të jenë në formën e një adresë IP. Ju lutemi, zgjidhni një tjetër emër përdoruesi.',
'Username reserved chars'	=>	'Emrat e përdoruesve s’mund të përmbajnë njëherësh krejt shenjat \', " dhe [ ose ]. Ju lutemi, zgjidhni një tjetër emër përdoruesi.',
'Username BBCode'			=>	'Emrat e përdoruesve s’mund të përmbajnë çfarëdo etikete formatimi teksti (BBCode) që i përdor forumi. Ju lutemi, zgjidhni një tjetër emër përdoruesi.',
'Banned username'			=>	'Emri i përdoruesit që dhatë është i dëbuar në këtë forum. Ju lutemi, zgjidhni një tjetër emër përdoruesi.',
'Pass too short'			=>	'Fjalëkalimet duhet të jenë të paktën 9 shenja të gjatë. Ju lutemi, zgjidhni një fjalëkalim tjetër (më të gjatë).',
'Pass not match'			=>	'Fjalëkalimet nuk përputhen.',
'Banned email'				=>	'Adresa email që dhatë është e dëbuar në këtë forum. Ju lutemi, zgjidhni një tjetër adresë email.',
'Dupe email'				=>	'Dikush tjetër është regjistruar tashmë me atë adresë email. Ju lutemi, zgjidhni një tjetër adresë email.',
'Sig too long'				=>	'Nënshkrimet s’mund të jenë më të gjata se %1$s shenja. Ju lutemi, reduktojeni nënshkrimin tuaj me %2$s shenja.',
'Sig too many lines'		=>	'Nënshkrimet s’mund të kenë më tepër se %s rreshta.',
'Bad ICQ'					=>	'Dhatë një ICQ UIN të pavlefshëm. Ju lutemi, kthehuni mbrapsht dhe ndreqeni.',

'UTC-12:00'					=>	'(UTC-12:00) Vija e Datave Ndërkombëtare Në Perëndim',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Havaji-Aleutianet, Ishulli Kuk',
'UTC-09:30'					=>	'(UTC-09:30) Ishujt Markeza',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Ishulli Gambie',
'UTC-08:30'					=>	'(UTC-08:30) Ishujt Pitkern',
'UTC-08:00'					=>	'(UTC-08:00) E Paqësorit',
'UTC-07:00'					=>	'(UTC-07:00) Malore',
'UTC-06:00'					=>	'(UTC-06:00) Qendrore',
'UTC-05:00'					=>	'(UTC-05:00) Lindore',
'UTC-04:00'					=>	'(UTC-04:00) E Atlantikut',
'UTC-03:30'					=>	'(UTC-03:30) Njufaundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazonë, Groenlanda Qendrore',
'UTC-02:00'					=>	'(UTC-02:00) Mes-Atlantike',
'UTC-01:00'					=>	'(UTC-01:00) Azore, Kepi i Gjelbër, Goenlanda Lindore',
'UTC'						=>	'(UTC) Evropiane Perëndimore, Grinuiç',
'UTC+01:00'					=>	'(UTC+01:00) Evropiane Qendrore, Afrikanoperëndimore',
'UTC+02:00'					=>	'(UTC+02:00) Evropiane Lindore, Afrikanoqendrore, Kaliningrad',
'UTC+03:00'					=>	'(UTC+03:00) Afrikanolindore, Moskë',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Gjiri, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afganistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan, Jekaterinburg',
'UTC+05:30'					=>	'(UTC+05:30) Indi, Sri Lankë',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Butan, Omsk',
'UTC+06:30'					=>	'(UTC+06:30) Ishujt Kokos, Mianmar',
'UTC+07:00'					=>	'(UTC+07:00) Indokinë, Novosibirsk, Krasnojarsk',
'UTC+08:00'					=>	'(UTC+08:00) Kina e Madhe, Australia Perëndimore, Irkutsk',
'UTC+08:45'					=>	'(UTC+08:45) Australia Juglindore Perëndimore',
'UTC+09:00'					=>	'(UTC+09:00) Japoni, Kore, Çita, Jakutsk',
'UTC+09:30'					=>	'(UTC+09:30) Australia Qendrore',
'UTC+10:00'					=>	'(UTC+10:00) Australia Lindore, Vladivostok',
'UTC+10:30'					=>	'(UTC+10:30) Lord Hoaue',
'UTC+11:00'					=>	'(UTC+11:00) Ishulli Solomon, Magadan',
'UTC+11:30'					=>	'(UTC+11:30) Ishulli Norfolk',
'UTC+12:00'					=>	'(UTC+12:00) Zelandë e Re, Fixhi, Kamçatka',
'UTC+12:45'					=>	'(UTC+12:45) Ishujt Çatëm',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Ishujt Feniks',
'UTC+14:00'					=>	'(UTC+14:00) Sporadet Ekuatoriale'

);
