<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'Menu profili',
'Section essentials'			=>	'Thelbësore',
'Section personal'				=>	'Personale',
'Section messaging'				=>	'Shkëmbim mesazhesh',
'Section personality'			=>	'Personalitet',
'Section display'				=>	'Shfaqje',
'Section privacy'				=>	'Privatësi',
'Section admin'					=>	'Administrim',

// Miscellaneous
'Username and pass legend'		=>	'Jepni emrin e përdoruesit dhe fjalëkalimin tuaj',
'Personal details legend'		=>	'Jepni hollësitë tuaja personale',
'Contact details legend'		=>	'Jepni hollësitë tuaja për shkëmbim mesazhesh',
'User activity'					=>	'Veprimtari përdoruesi',
'Paginate info'					=>	'Jepni numrin e temave dhe postimeve që doni të shihni në çdo faqe.',

// Password stuff
'Pass key bad'					=>	'Kyçi i dhënë i aktivizimit të fjalëkalimit qe i pasaktë ose ka skaduar. Ju lutemi, rikërkoni një fjalëkalim të ri. Nëse kjo s’bën punë, lidhuni me përgjegjësin e forumit në',
'Pass updated'					=>	'Fjalëkalimi juaj është përditësuar. Tani mund të hyni me fjalëkalimin tuaj të ri.',
'Pass updated redirect'			=>	'Fjalëkalimi u përditësua. Po bëhet ridrejtim …',
'Wrong pass'					=>	'Fjalëkalim i vjetër i gabuar.',
'Change pass'					=>	'Ndryshoni fjalëkalimin',
'Change pass legend'			=>	'Jepni dhe ripohoni fjalëkalimin tuaj të ri',
'Old pass'						=>	'Fjalëkalimi i vjetër',
'New pass'						=>	'Fjalëkalimi i ri',
'Confirm new pass'				=>	'Ripohoni fjalëkalimin e ri',
'Pass info'						=>	'Fjalëkalimet duhet të jenë të paktën 9 shenja të gjatë. Fjalëkalimet janë të ndjeshëm ndaj shkrimit me të madhe ose me të vogël.',

// Email stuff
'Email key bad'					=>	'Kyçi i dhënë i aktivizimit të email-it qe i pasaktë ose ka skaduar. Ju lutemi, rikërkoni ndryshimin e adresës email. Nëse kjo s’bën punë, lidhuni me përgjegjësin e forumit te',
'Email updated'					=>	'Adresa juaj email u përditësua.',
'Activate email sent'			=>	'Te adresa e specifikuar u dërgua një email me udhëzime se si të aktivizohet adresa e re email. Nëse nuk ju vjen, mund të lidheni me përgjegjësin e forumit te',
'Email legend'					=>	'Jepni adresën tuaj të re email',
'Email instructions'			=>	'Te adresa juaj e re do të dërgohet një email me një lidhje aktivizim. Për të aktivizuar adresën e re, duhet të klikoni mbi lidhjen te email që morët.',
'Change email'					=>	'Ndryshoni adresë email',
'New email'						=>	'Email i ri',

// Avatar upload stuff
'Avatars disabled'				=>	'Përgjegjësi e ka çaktivizuar mbulimin e avatarëve.',
'Too large ini'					=>	'Kartela e përzgjedhur është shumë e madhe për ngarkim. Shërbyesi nuk e lejoi ngarkimin.',
'Partial upload'				=>	'Kartela e përzgjedhur u ngarkua vetëm pjesërisht. Ju lutemi, riprovoni.',
'No tmp directory'				=>	'PHP-ja s’qe në gjendje të ruajë kartelën e ngarkuar te një vend i përkohshëm.',
'No file'						=>	'Nuk përzgjodhët kartelë për t’u ngarkuar.',
'Bad type'						=>	'Kartela që provuat të ngarkoni s’është e një lloji të lejuar. Lloje të lejuar janë gif, jpeg dhe png.',
'Too wide or high'				=>	'Kartela që provuat të ngarkoni është më e gjerë dhe/ose më e lartë se sa maksimumi i lejuar %d x %d piksela.',
'Too large'						=>	'Kartela që provuat të ngarkoni është më e madhe se sa maksimumi i lejuar prej %d bajtesh.',
'Move failed'					=>	'Shërbyesi s’qe në gjendje të ruajë kartelën e ngarkuar. Ju lutemi, lidhuni me përgjegjësin e forumit te',
'Unknown failure'				=>	'Ndodhi një gabim i panjohur. Ju lutemi, riprovoni.',
'Avatar upload redirect'		=>	'Avatari u ngarkua. Po bëhet ridrejtim …',
'Avatar deleted redirect'		=>	'Avatari u fshi. Po bëhet ridrejtim …',
'Avatar desc'					=>	'Një avatar është një figurë e vockël që do të shfaqet nën emrin tuaj të përdoruesit në postimet tuaja. S’duhet të jetë më e madhe se %d x %d piksel ose %s bajte (%s).',
'Upload avatar'					=>	'Ngarkoni avatar',
'Upload avatar legend'			=>	'Jepni një kartelë avatari për ngarkim',
'Delete avatar'					=>	'Fshini avatarin', // only for admins
'File'							=>	'Kartelë',
'Upload'						=>	'Ngarkoje', // submit button

// Form validation stuff
'Forbidden title'				=>	'Titulli që dhatë përmban një fjalë të ndaluar. Duhet të zgjidhni një titull tjetër.',
'Profile redirect'				=>	'Profili u përditësua. Po bëhet ridrejtim …',

// Profile display stuff
'Users profile'					=>	'Profili i %s',
'Username info'					=>	'Emër përdoruesi: %s',
'Email info'					=>	'Email: %s',
'Posts info'					=>	'Postime: %s',
'Registered info'				=>	'Regjistruar më: %s',
'Last post info'				=>	'Postimi i fundit: %s',
'Last visit info'				=>	'Vizita e fundit: %s',
'Show posts'					=>	'Shfaqi krejt postimet',
'Show topics'					=>	'Shfaqi krejt temat',
'Show subscriptions'			=>	'Shfaqi krejt pajtimet',
'Realname'						=>	'Emri i njëmendtë',
'Location'						=>	'Vendndodhja',
'Website'						=>	'Sajt',
'Invalid website URL'			=>	'URL-ja e sajtit që dhatë është e pavlefshme.',
'Website not allowed'			=>	'S’keni ende leje të shtoni një sajt te profili juaj.',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'Microsoft Account',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'Avatar',
'Signature'						=>	'Nënshkrim',
'Sig max size'					=>	'Gjatësi maks.: %s shenja / Maks. rreshtash: %s',
'Avatar legend'					=>	'Caktoni mundësi shfaqjeje të avatarit tuaj',
'Avatar info'					=>	'Një avatar është një figurë e vockël që do të shfaqet me krejt postimet tuaja. Mund të ngarkoni një avatar duke klikuar mbi lidhjen më poshtë.',
'Change avatar'					=>	'Ndryshoni avatar',
'Signature legend'				=>	'Hartoni nënshkrimin tuaj',
'Signature info'				=>	'Një nënshkrim është copëz tekst që i bashkëngjitet postimeve tuaja. Në të mund të futni thuajse çfarëdo gjëje që dëshironi. Ndoshta do të donit të vendosnit thënien tuaj të parapëlqyer ose shenjën tuaj të horoskopit. E keni vetë në dorë! Te nënshkrimi juaj mund të përdorni BBCode, nëse është e lejuar për këtë forum të dhënë. Veçoritë që janë lejuar/ndaluar mund t’i shihni të radhitura më poshtë, kurdo që përpunoni nënshkrimin tuaj.',
'Sig preview'					=>	'Paraparje e nënshkrimit të tanishëm:',
'No sig'						=>	'Aktualisht s’ka nënshkrim të depozituar në profil.',
'Signature quote/code/list/h'	=>	'Në nënshkrime nuk lejohen kodet BBCodes për citim, kod, lista dhe tituj.',
'Topics per page'				=>	'Tema',
'Posts per page'				=>	'Postime',
'Leave blank'					=>	'Që të përdoren parazgjedhje forumi lëreni të zbrazët.',
'Subscription legend'			=>	'Caktoni mundësitë tuaja për pajtimet',
'Notify full'					=>	'Përfshi një version thjesht tekst të postimeve të reja, te email-e njoftimesh pajtimi.',
'Auto notify full'				=>	'Pajtohuni automatikisht më çdo temë ku postoni.',
'Show smilies'					=>	'Shfaqi emotikonët si ikona grafike.',
'Show images'					=>	'Shfaqi figurat në postime.',
'Show images sigs'				=>	'Shfaqi figurat në nënshkrime përdoruesish.',
'Show avatars'					=>	'Shfaqi avataret e përdoruesve në postime.',
'Show sigs'						=>	'Shfaq nënshkrime përdoruesish.',
'Style legend'					=>	'Përzgjidhni stilin tuaj të parapëlqyer',
'Styles'						=>	'Stile',
'Admin note'					=>	'Shënim përgjegjësi',
'Pagination legend'				=>	'Jepni mundësitë tuaja për faqosjen',
'Post display legend'			=>	'Caktoni mundësitë tuaja për parje postimesh',
'Post display info'				=>	'Nëse gjendeni nën një lidhje të ngadaltë, çaktivizmi i këtyre mundësive, veçanërisht i shfaqjes së figurave në postime dhe nënshkrime, do të bëjë që faqet të ngarkohen më shpejt.',
'Instructions'					=>	'Kur përditësoni profilin tuaj, do të ridrejtoheni mbrapsht te kjo faqe.',

// Administration stuff
'Group membership legend'		=>	'Zgjidhni grup përdoruesi',
'Save'							=>	'Ruaje',
'Set mods legend'				=>	'Caktoni hyrje moderatori',
'Moderator in info'				=>	'Zgjidhni cilat forume do të lejohet të moderojë ky përdorues. Shënim: Kjo vlen vetëm për moderatorë. Përgjegjësit kanë përherë leje të plotë në krejt forumet.',
'Update forums'					=>	'Përditësoni forume',
'Delete ban legend'				=>	'Fshini (vetëm përgjegjësit) ose dëboni përdorues',
'Delete user'					=>	'Fshije përdoruesin',
'Ban user'						=>	'Dëboje përdoruesin',
'Confirm delete legend'			=>	'E rëndësishme: lexojeni, përpara se të fshini përdorues',
'Confirm delete user'			=>	'Ripohoni fshirje përdoruesi',
'Confirmation info'				=>	'Ju lutemi, ripohoni se doni të fshihet përdoruesi', // the username will be appended to this string
'Delete warning'				=>	'Kujdes! Përdoruesit dhe/ose postimet e fshira s’mund të rikthehen. Nëse zgjidhni të mos fshihen postimet e bëra nga ky përdorues, postimet mund të fshihen dorazi më vonë.',
'Delete posts'					=>	'Fshi çfarëdo postimesh dhe temash që ka bërë ky përdorues.',
'Delete'						=>	'Fshije', // submit button (confirm user delete)
'User delete redirect'			=>	'Përdoruesi u fshi. Po bëhet ridrejtim …',
'User promote redirect'			=>	'Përdoruesi u gradua. Po bëhet ridrejtim …',
'Group membership redirect'		=>	'U ruajt anëtarësimi në grup. Po bëhet ridrejtim …',
'Update forums redirect'		=>	'Të drejtat e moderimit të forumit u përditësuan. Po bëhet ridrejtim …',
'Ban redirect'					=>	'Po bëhet ridrejtim …',
'No delete admin message'		=>	'Përgjegjësit s’mund të fshihen. Që të mund të fshini këtë përdorues, duhet së pari të shpini atë te një grup tjetër përdoruesish.',

);
