<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'Kërkim nga përdoruesi',
'No search permission'				=>	'S’keni leje të përdorni veçorinë e kërkimeve.',
'Search flood'						=>	'Mes kërkimeve duhet të rrjedhin të paktën %s sekonda. Ju lutemi, pritni %s sekonda dhe riprovoni kërkimin.',
'Search'							=>	'Kërko',
'Search criteria legend'			=>	'Jepni për çfarë të kërkohet',
'Search info'						=>	'Për të kërkuar sipas fjalëkyçesh, jepni një ose disa terma për të cilët të kërkohet. Termat ndajini me hapësira. Që të përimtoni kërkimin tuaj, përdorni AND, OR dhe NOT. Që të kërkoni sipas emrash autorësh, jepni emrin e përdoruesit të autorit të postimeve te të cilat doni të kërkohet. Për përputhje të pjesshme përdorni shenjën e gjithëpushtetshme *.',
'Keyword search'					=>	'Kërkim fjalëkyçesh',
'Author search'						=>	'Kërkim autori',
'Search in legend'					=>	'Përzgjidhni ku të kërkohet',
'Search in info'					=>	'Zgjidhni në cilin forum do të donit të kërkohet dhe nëse doni të kërkohet te subjekte temash, tekst mesazhesh, apo në të dyja.',
'Search multiple forums info'		=>	'Nëse s’përzgjidhen forume, do të kërkohet në krejt forumet.',
'Forum search'						=>	'Forum',
'Search in'							=>	'Kërko te',
'Message and subject'				=>	'Tekst mesazhesh dhe subjekt teme',
'Message only'						=>	'Vetëm tekst mesazhesh',
'Topic only'						=>	'Vetëm temë subjekti',
'Sort by'							=>	'Renditi sipas',
'Sort order'						=>	'Kah renditjeje',
'Search results legend'				=>	'Përzgjidhni si të shihen përfundimet e kërkimit',
'Search results info'				=>	'Mund të zgjidhni se si doni të renditen dhe shfaqe përfundimet tuaja.',
'Sort by post time'					=>	'Kohë postimi',
'Sort by author'					=>	'Autor',
'Sort by subject'					=>	'Subjekt',
'Sort by forum'						=>	'Forum',
'Ascending'							=>	'Rritës',
'Descending'						=>	'Zbritës',
'Show as'							=>	'Shfaqi përfundimet si',
'Show as topics'					=>	'Tema',
'Show as posts'						=>	'Postime',

// Results
'Search'							=>	'Kërko',
'Search results'					=>	'Përfundime kërkimi',
'Quick search show_new'				=>	'Të rinj',
'Quick search show_recent'			=>	'Aktivë',
'Quick search show_unanswered'		=>	'Pa përgjigje',
'Quick search show_replies'			=>	'Postuar më',
'Quick search show_user_topics'		=>	'Tema nga %s',
'Quick search show_user_posts'		=>	'Postime nga %s',
'Quick search show_subscriptions'	=>	'Pajtuar nga %s',
'By keywords show as topics'		=>	'Tema me postime që përmbajnë \'%s\'',
'By keywords show as posts'			=>	'Postime që përmbajnë \'%s\'',
'By user show as topics'			=>	'Tema me postime nga %s',
'By user show as posts'				=>	'Postime nga %s',
'By both show as topics'			=>	'Tema me postime që përmbajnë \'%s\', nga %s',
'By both show as posts'				=>	'Postime që përmbajnë \'%s\', nga %s',
'No terms'							=>	'Duhet të jepni të paktën një fjalëkyç dhe/ose një autor për të cilët të kërkohet. Termat e kërkimit duhet të jenë të paktën tre shenja të gjatë.',
'No hits'							=>	'Kërkimi juaj s’gjeti ndonjë përfundim.',
'No user posts'						=>	'S’ka postime nga ky përdorues në këtë forum.',
'No user topics'					=>	'S’ka tema nga ky përdorues në këtë forum.',
'No subscriptions'					=>	'Ky përdorues aktualisht s’është i pajtuar në ndonjë temë.',
'No new posts'						=>	'S’ka tema me postime të reja që nga vizita juaj e fundit.',
'No recent posts'					=>	'S’janë bërë postime të reja brenda 24 orëve të fundit.',
'No unanswered'						=>	'S’ka postime pa përgjigje në këtë forum.',
'Go to post'						=>	'Kalo te postimi',
'Go to topic'						=>	'Kalo te tema'

);
