<?php

// Sprachdefinitionen, die in admin_index.php verwendet werden
$lang_admin_index = array(

'fopen disabled message'			=>	'Konnte nicht auf Aktualisierungen prüfen, da die Funktion \'allow_url_fopen\' auf diesem Server deaktiviert ist.',
'Upgrade check failed message'		=>	'Die Prüfung auf Aktualisierungen ist aus unbekannten Gründen fehlgeschlagen.',
'Running latest version message'	=>	'Du verwendest die aktuellste Version von FluxBB.',
'New version available message'		=>	'Es wurde eine neue Version von FluxBB veröffentlicht. Du kannst diese unter %s herunterladen.',
'Deleted install.php redirect'		=>	'Die Datei wurde erfolgreich entfernt. Leite weiter …',
'Delete install.php failed'			=>	'Konnte install.php nicht entfernen. Bitte manuell löschen.',
'Not available'						=>	'Nicht verfügbar',
'Forum admin head'					=>	'Foren-Administration',
'NA'								=>	'Keine Daten verfügbar',
'Welcome to admin'					=>	'Willkommen in der FluxBB-Administration. Von hier aus kannst Du alle wichtigen Aspekte des Forums kontrollieren. In Abhängigkeit, ob Sie Administrator oder Moderator sind, kannst Du',
'Welcome 1'							=>	'Kategorien und Foren verwalten.',
'Welcome 2'							=>	'Forenweite Optionen und Einstellungen festlegen.',
'Welcome 3'							=>	'Berechtigungen für Mitglieder und Gäste kontrollieren.',
'Welcome 4'							=>	'IP-Statistiken der Mitglieder anzeigen.',
'Welcome 5'							=>	'Mitglieder sperren',
'Welcome 6'							=>	'Wörter zensieren.',
'Welcome 7'							=>	'Mitgliedergruppen und Beförderungen festlegen.',
'Welcome 8'							=>	'Alte Beiträge bereinigen.',
'Welcome 9'							=>	'Eingesandte Meldungen bearbeiten.',
'Alerts head'						=>	'Warnungen',
'Install file exists'				=>	'Die Datei install.php existiert noch, sollte aber entfernt werden. %s.',
'Delete install file'				=>	'Datei löschen',
'About head'							=>      'Über FluxBB',
'FluxBB version label'				=>	'FluxBB-Version',
'Check for upgrade'					=>	'Auf Aktualisierung prüfen',
'FluxBB version data'				=>	'v%s - %s',
'Server statistics label'			=>	'Server-Statistiken',
'View server statistics'			=>	'Server-Statistiken anzeigen',
'Support label'						=>	'Support',
'Forum label'						=>	'Forum',
'IRC label'							=>	'IRC channel',

// Language definitions used in admin_statistics.php
'PHPinfo disabled message'			=>	'Die PHP-Funktion phpinfo() ist auf diesem Server deaktiviert.',
'Server statistics head'			=>	'Server-Statistiken',
'Server load label'					=>	'Server-Auslastung',
'Server load data'					=>	'%s - %s Besucher online',
'Environment label'					=>	'Umgebung',
'Environment data OS'				=>	'Betriebssystem: %s',
'Show info'							=>	'Informationen anzeigen',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Beschleuniger: %s',
'Turck MMCache'						=>	'Turk MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net',
'ionCube PHP Accelerator'			=>	'ionCube PHP-Beschleuniger',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternativer PHP-Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Datenbank',
'Database data rows'				=>	'Zeilen: %s',
'Database data size'				=>	'Größe: %s',

);
