<?php

// Sprachdefinitionen, die in admin_bans.php verwendet werden
$lang_admin_bans = array(

'No user message'			=>	'Es ist kein Mitglied mit diesem Namen registriert. Wenn Du eine Mitgliedssperre hinzufügen möchtest, der nicht mit einem bestimmten Mitgliedsnamen verbunden ist, lass das Namensfeld einfach leer.',
'No user ID message'		=>	'Es ist kein Mitglied mit dieser ID registriert.',
'User is admin message'		=>	'Das Mitglied %s ist ein Administrator und kann nicht gesperrt werden. Wenn Du einen Administrator sperren möchtest, musst Du diesen zunächst auf die Berechtigungen eines einfachen Mitglieds zurückstufen.',
'User is mod message'		=>	'Das Mitglied %s ist ein Moderator und kann nicht gesperrt werden. Wenn Du einen Moderator sperren möchtest, musst Du diesen zunächst auf die Berechtigungen eines einfachen Mitglieds zurückstufen.',
'Must enter message'		=>	'Du musst mindestens einen Mitgliedsnamen, eine IP-Adresse oder eine Email-Adresse eingeben.',
'Cannot ban guest message'	=>	'Gäste können nicht gesperrt werden.',
'Invalid IP message'		=>	'Du hast eine ungültige IP-Adresse bzw. ungültigen IP-Bereich eingegeben.',
'Invalid e-mail message'	=>	'Die eingegebene Email-Adresse (z.Bsp. mitglied@domain.de) oder ein Teil der Email-Domain (z.Bsp. domain.de) ist ungültig.',
'Duplicate domain message'	=>	'Die Domain %s wurde bereits gesperrt.',
'Duplicate e-mail message'	=>	'Die Email-Adresse %s wurde bereits gesperrt.',
'Invalid date message'		=>	'Du hast ein ungültiges Ablaufdatum eingegeben.',
'Invalid date reasons'		=>	'Das Datum muss im Format JJJJ-MM-TT angegeben werden und mindestens einen Tag in der Zukunft liegen.',
'Ban added redirect'		=>	'Mitgliedssperre hinzugefügt. Leite weiter …' ,
'Ban edited redirect'		=>	'Mitgliedssperre aktualisiert. Leite weiter …',
'Ban removed redirect'		=>	'Mitgliedssperre entfernt. Leite weiter …',

'New ban head'				=>	'Neue Mitgliedssperre',
'Add ban subhead'			=>	'Eine Mitgliedssperre hinzufügen',
'Username label'			=>	'Mitgliedsname',
'Username help'				=>	'Der Name des zu sperrenden Mitglieds (nicht zeichensensitiv).',
'Username advanced help'	=>	'Der zu sperrende Mitgliedsname (zeichensensitiv). Auf der nächsten Seite kannst Du eine IP sowie eine Email-Adresse festlegen. Wenn Du nur eine bestimmte IP bzw. IP-Bereich oder eine bestimmte Email-Adresse sperren willst, lass die anderen Felder leer.',

'Ban search head'			=>	'Mitgliedssperren-Suche',
'Ban search subhead'		=>	'Bitte gib die Suchkriterien ein',
'Ban search info'			=>	'Mitgliedssperren-Suche in der Datenbank. Für die Suche kannst Du einen oder mehrere Begriffe eingeben. Platzhalter in Form von Asterisks (*) sind auch möglich.',
'Date help'					=>	'(jjjj-mm-tt)',
'Message label'				=>	'Nachricht',
'Expire after label'		=>	'Ablauf nach',
'Expire before label'		=>	'Ablauf vor',
'Order by label'			=>	'Sortieren nach',
'Order by username'			=>	'Mitgliedsname',
'Order by ip'				=>	'IP',
'Order by e-mail'			=>	'Email',
'Order by expire'			=>	'Ablaufdatum',
'Ascending'					=>	'Aufsteigend',
'Descending'				=>	'Absteigend',
'Submit search'				=>	'Suche starten',

'E-mail label'				=>	'Email-Adresse',
'E-mail help'				=>	'Die Email-Adresse oder die Email-Domain, die gesperrt werden soll (z.Bsp. irgendjemand@domain.de oder domain.de). Weitere Informationen dazu finden Sie in den Berechtigungen unter "Email-Adresssperre erlauben".',
'IP label'					=>	'IP-Adresse/IP-Bereich',
'IP help'					=>	'Die IP-Adresse oder der IP-Bereich, der gesperrt werden soll (z.Bsp. 150.11.110.1 oder 150.11.110). Mehrere IP-Adressen können mit einem Leerzeichen getrennt eingegeben werden. Wenn in diesem Feld bereits eine IP-Adresse vorhanden ist, dann ist dies die letzte, in der Datenbank gespeicherte IP-Adresse des Mitglieds.',
'IP help link'				=>	'Klicke %s, um die IP-Statistik für dieses Mitglied anzuzeigen.',
'Ban advanced head'			=>	'Erweiterte Mitgliedssperren-Einstellungen',
'Ban advanced subhead'		=>	'Kombinierte Mitgliedssperre mit IP und Email-Adresse',
'Ban message label'			=>	'Sperr-Nachricht an das Mitglied',
'Ban message help'			=>	'Die Nachricht, die dem Mitglied angezeigt wird, wenn es die Foren besucht.',
'Message expiry subhead'	=>	'Sperr-Nachricht und Ablaufdatum',
'Ban IP range info'			=>	'Du solltest vorsichtig sein, wenn Du einen IP-Bereich sperrst, da andere Mitglieder möglicherweise den gleichen IP-Bereich verwenden.',
'Expire date label'			=>	'Ablaufdatum',
'Expire date help'			=>	'Das Datum, nachdem die Mitgliedssperre automatisch entfernt werden soll (Format: JJJJ-MM-TT). Lass dieses Feld leer, wenn die Mitgliedssperre manuell entfernt werden soll.',

'Results head'				=>	'Suchergebnisse',
'Results username head'		=>	'Mitgliedsname',
'Results e-mail head'		=>	'Email',
'Results IP address head'	=>	'IP/IP-Bereich',
'Results expire head'		=>	'Ablaufdatum',
'Results message head'		=>	'Nachricht',
'Results banned by head'	=>	'Gesperrt durch',
'Results actions head'		=>	'Aktionen',
'No match'					=>	'Keinen Eintrag gefunden',
'Unknown'					=>	'Unbekannt',

);
