<?php

// Sprachdefinitionen, die in admin-users.php verwendet werden
$lang_admin_users = array(

'Non numeric message'		=>	'Du hast einen nichtnumerischen Wert in eine Spalte für numerische Werte eingetragen.',
'Invalid date time message'	=>	'Du hast einen ungültigen Wert für Datum und/oder Zeit eingegeben.',
'Not verified'				=>	'Nicht geprüft',
'User search head'			=>	'Mitgliedersuche',
'User search subhead'		=>	'Gib Deine Suchkriterien ein',
'User search info'			=>	'Mitgliedersuche in der Datenbank. Du kannst einen oder mehrere Begriffe eingeben, nach denen Du suchen willst. Sternchen (*) werden als Wildcards akzeptiert.',
'Username label'			=>	'Mitgliedsname',
'E-mail address label'		=>	'Email-Adresse',
'Title label'				=>	'Titel',
'Real name label'			=>	'Realname',
'Website label'				=>	'Webseite',
'Jabber label'				=>	'Jabber',
'ICQ label'					=>	'ICQ',
'MSN label'					=>	'MSN Messenger',
'AOL label'					=>	'AOL IM',
'Yahoo label'				=>	'Yahoo Messenger',
'Location label'			=>	'Ort',
'Signature label'			=>	'Signatur',
'Admin note label'			=>	'Administratoren-Notiz',
'Posts more than label'		=>	'Anzahl der Beiträge größer als',
'Posts less than label'		=>	'Anzahl der Beiträge kleiner als',
'Last post after label'		=>	'Letzter Beitrag nach',
'Date help'					=>	'(jjjj-mm-tt hh:mm:ss)',
'Last post before label'	=>	'Letzter Beitrag vor',
'Registered after label'	=>	'Registriert nach',
'Registered before label'	=>	'Registriert vor',
'Order by label'			=>	'Sortieren nach',
'Order by username'			=>	'Mitgliedsname',
'Order by e-mail'			=>	'Email',
'Order by posts'			=>	'Anzahl der Beiträge',
'Order by last post'		=>	'Letztem Beitrag',
'Order by registered'		=>	'Registrierung',
'Ascending'					=>	'Aufsteigend',
'Descending'				=>	'Absteigend',
'User group label'			=>	'Mitgliedergruppe',
'All groups'				=>	'Alle Gruppen',
'Unverified users'			=>	'Ungeprüfte Mitglieder',
'Submit search'				=>	'Suche starten',
'IP search head'			=>	'IP-Suche',
'IP search subhead'			=>	'Gib die gesuchte IP ein',
'IP address label'			=>	'IP-Adresse',
'IP address help'			=>	'Die IP-Adresse, nach der in der Beitragsdatenbank gesucht werden soll.',
'Find IP address'			=>	'IP-Adresse finden',

'Results head'				=>	'Mitglieder',
'Results username head'		=>	'Mitgliedsname',
'Results e-mail head'		=>	'Email',
'Results title head'		=>	'Titel/Status',
'Results posts head'		=>	'Beiträge',
'Results admin note head'	=>	'Administratoren-Notiz',
'Results actions head'		=>	'Aktionen',
'Results IP address head'	=>	'IP-Adresse',
'Results last used head'	=>	'Zuletzt verwendet',
'Results times found head'	=>	'mal gefunden',
'Results action head'		=>	'Aktion',
'Results find more link'	=>	'Weitere Mitglieder mit dieser IP finden',
'Results no posts found'	=>	'Dieses Mitglied hat bislang noch keinen Beitrag im Forum hinterlassen.',
'Bad IP message'			=>	'Die eingegebene IP-Adresse ist nicht richtig formatiert.',
'Results view IP link'		=>	'IP-Statistiken anzeigen',
'Results show posts link'	=>	'Beiträge anzeigen',
'Results guest'				=>	'Gast',
'Results no IP found'		=>	'Die angegebene IP-Adresse wurde in der Datenbank nicht gefunden.',
'No match'					=>	'Keine Einträge gefunden'

);
