<?php

// Sprachdefinitionen, die in der install.php verwendet werden

$lang_install = array(

'Choose install language'		=>	'Wähle hier die Sprache für den Installationsassistenten',
'Choose install language info'	=>	'Die Sprache, die für den Installationsassistenten verwendet werden soll. Die voreingestellte Sprache für das Forum kann weiter unten festgelegt werden.',
'Install language'				=>	'Sprache installieren',
'Change language'				=>	'Sprache ändern',
'Next'							=>	'Weiter',
'Already installed'				=>	'Es scheint so, als ob FluxBB bereits installiert ist. Du sollstest daher anstatt dessen <a href="index.php">hier</a> weitermachen.',
'You are running error'			=>	'Du verwendest %1$s Version %2$s. FluxBB %3$s benötigt für seine volle Funktionsfähigkeit mindestens %1$s %4$s. Bevor du weitermachen kannst, musst du zunächst deine %1$s Installation aktualisieren.',
'My FluxBB Forum'				=>	'Mein FluxBB-Forum',
'Description'					=>	'FluxBB kann man nicht mit Worten beschreiben - man muss es selbst erlebt haben.',
'Username 1'					=>	'Mitgliedsnamen müssen mindestens 2 Zeichen lang sein.',
'Username 2'					=>	'Mitgliedsnamen dürfen nicht länger als 25 Zeichen sein.',
'Username 3'					=>	'Der Mitgliedsname Gast ist reserviert.',
'Username 4'					=>	'Mitgliedsnamen dürfen nicht die Form einer IP-Adresse haben.',
'Username 5'					=>	'Mitgliedsnamen dürfen nicht die Zeichen \', " und [ oder ] enthalten.',
'Username 6'					=>	'Mitgliedsnamen dürfen keine vom Forum verwendeten Formatierungs-Tags (BBCode) enthalten.',
'Short password'				=>	'Passwörter must be at least 4 characters long.',
'Passwords not match'			=>	'Die Passwörter stimmen nicht überein.',
'Wrong email'					=>	'Die für den Administrator eingegebene E-Mail-Adresse ist ungültig.',
'No board title'				=>	'Du musst einen Board-Titel eingeben.',
'Error default language'		=>	'Die voreingestellte Sprache scheint nicht zu existieren.',
'Error default style'			=>	'Der voreingestellte Style scheint nicht zu existieren.',
'No DB extensions'				=>	'Die PHP-Umgebung unterstützt keine der Datenbanken, die mit FluxBB verwendet werden können. Um FluxBB installieren zu können, muss PHP die Datenbanken MySQL, PostgreSQL oder SQLite unterstützen.',
'Administrator username'		=>	'Mitgliedsname des Administrators',
'Administrator password 1'		=>	'Passwort 1 des Administrators',
'Administrator password 2'		=>	'Passwort 2 des Administrators',
'Administrator email'			=>	'E-Mail des Administrators',
'Board title'					=>	'Board-Titel',
'Base URL'						=>	'Die URL (ohne abschließenden /) Deines FluxBB-Forums. Diese musst korrekt sein.',
'Required field'				=>	'ist in diesem Formular ein Pflichtfeld.',
'FluxBB Installation'			=>	'FluxBB-Installation',
'Welcome'						=>	'Du möchtest FluxBB installieren. Dafür musst du das nachfolgende Formular vollständig ausfüllen. Wenn bei der Installation irgendwelche Schwierigkeiten auftreten, lies bitte in der Dokumentation nach.',
'Install'						=>	'FluxBB %s installieren',
'Errors'						=>	'Die folgenden Fehler müssen korrigiert werden:',
'Database setup'				=>	'Datenbank-Einstellungen',
'Info 1'						=>	'Alle Informationen die für eine Datenbank-Verbindung benötigt werden.',
'Select database'				=>	'Wähle hier deinen Datenbank-Typ',
'Info 2'						=>	'Wähle eine Datenbank. Wir unterstützen SQLite, MySQL und PostgreSQL.',
'Dual MySQL'					=>	'FluxBB hat erkannt, dass deine PHP-Umgebung zwei verschiedene Wege unterstützt, mit MySQL zu kommunizieren. Diese beiden Optionen werden Standard und improved genannt. Wenn du unsicher bist, welche du verwenden sollst, versuche zunächst improved und falls es fehlschlägt, versuche Standard.',
'InnoDB'						=>	'FluxBB hat erkannt, dass dein MySQL-Server <a href="http://dev.mysql.com/doc/refman/5.0/en/innodb.html">InnoDB</a> unterstützt. Dies ist eine gute Wahl, wenn du ein großes Forum planst. Falls du dir noch unsicher bist, solltest du InnoDB besser nicht verwenden.',
'Database type'					=>	'Datenbank-Typ',
'Required'						=>	'(Pflichtfeld)',
'Database hostname'				=>	'Gib hier den Hostnamen deines Datenbank-Servers ein',
'Info 3'						=>	'Du solltest diese Information von Deinem Web Host bekommen, falls <code>localhost</code> nicht funktioniert.',
'Database server hostname'		=>	'Hostname des Datenbank-Servers',
'Database enter name'			=>	'Gib hier den Namen deiner Datenbank ein',
'Info 4'						=>	'Der Name der Datenbank, in die FluxBB installiert werden soll.',
'Database name'					=>	'Datenbank-Name',
'Database enter informations'	=>	'Gib hier den Benutzernamen und das Passwort deiner Datenbank ein',
'Database username'				=>	'Datenbank-Benutzername',
'Info 5'						=>	'Dein MySQL-Benutzernamen und Passwort (kann für SQLite ignoriert werden).',
'Database password'				=>	'Datenbank-Passwort',
'Database enter prefix'			=>	'Gib hier den Präfix für die Datenbank-Tabellen ein',
'Info 6'						=>	'Falls Du mehrere FluxBB-Instanzen mit nur einer Datenbank verwenden möchtest, ändere diese Einstellung.',
'Table prefix'					=>	'Tabellen-Präfix',
'Administration setup'			=>	'Administrations-Einstellung',
'Info 7'						=>	'Erstelle das allererste Konto Deines Forums.',
'Admin enter username'			=>	'Gib hier den Mitgliedsnamen des Administrators ein',
'Info 8'						=>	'Mitgliedsnamen können zwischen 2 und 25 Zeichen lang sein. Passwörter müssen mindestens 4 Zeichen lang sein. Außerdem sind die Passwörter zeichensensitiv (Groß-/Kleinschreibung).',
'Admin enter password'			=>	'Gib hier das Passwort des Administrators ein und bestätige es anschließend noch einmal',
'Password'						=>	'Passwort',
'Confirm password'				=>	'Passwort bestätigen',
'Board setup'					=>	'Board-Einstellung',
'Info 11'						=>	'Einstellungen für Dein Forum. Du kannst diese später ändern.',
'General information'				=>	'Gib hier den Board-Titel und die -Beschreibung ein',
'Board description'				=>	'Board-Beschreibung (unterstützt HTML)',
'Appearance'					=>	'Erscheinungsbild',
'Choose the default language'	=>	'Wähle hier die voreingestellte Sprache',
'Info 15'						=>	'Wähle Sprache und Erscheinungsbild für Dein Forum.',
'Default language'				=>	'Voreingestellt Sprache',
'Default style'					=>	'Voreingestellter Style',
'Start install'					=>	'Installation beginnen',
'DB type not valid'				=>	'\'%s\' ist kein gültiger Datenbank-Typ',
'Table prefix error'			=>	'Der Tabellen-Präfix \'%s\' enthält ungültige Zeichen oder ist zu lang. Der Präfix darf nur die Buchstaben a bis z, Ziffern und das Unterstrich-Zeichen enthalten. Er muss nicht mit einer Ziffer beginnen. Die maximale Länge ist 40 Zeichen. Bitte wähle einen anderen Präfix',
'Prefix reserved'				=>	'Der Tabellen-Präfix \'sqlite_\' ist für die Verwendung von SQLite-Datenbanken reserviert. Bitte wähle einen anderen Präfix',
'Existing table error'			=>	'Eine tabelle mit dem Namen \'%susers\' ist bereits in der Datenbank \'%s\' vorhanden. Entweder ist FluxBB bereits installiert oder eine andere Software ist installiert und verwendet die gleichen Tabellennamen wie FluxBB. Wenn mehrere Kopien von FluxBB in der gleichen Datenbank installiert werden sollen, musst du jeweils einen anderen Tabellen-Präfix wählen',
'InnoDB off'					=>	'InnoDB scheint nicht aktiviert zu sein. Bitte wähle einen Datenbank-Layer, der keine InnoDB-Unterstützung hat oder aktiviere InnoDB auf deinem MySQL-Server',
'Administrators'				=>	'Administratoren',
'Administrator'					=>	'Administrator',
'Moderators'					=>	'Moderatoren',
'Moderator'						=>	'Moderator',
'Guests'						=>	'Gäste',
'Guest'							=>	'Gast',
'Members'						=>	'Mitglieder',
'Announcement'					=>	'Gib hier den Text für Ankündigungen ein.',
'Rules'							=>	'Gib hier die Regeln für dein Forum ein',
'Maintenance message'			=>	'Das Forum ist aufgrund von Wartungsarbeiten vorübergehend geschlossen. Bitte probier es in ein paar Minuten noch einmal.<br />\\n<br />\\n/ Der Administrator',
'Test post'						=>	'Test-Thema',
'Message'						=>	'Wenn du dies lesen kannst (wovon ich mal ausgehe), scheint die Installation von FluxBB zu funktionieren! Du kannst dich jetzt einloggen und über die Administration dein Forum konfigurieren.',
'Test category'					=>	'Test-Kategorie',
'Test forum'					=>	'Test-Forum',
'This is just a test forum'		=>	'Dies ist nur ein Test-Forum',
'Alert cache'					=>	'<strong>Das cache-Verzeichnis ist derzeit nicht beschreibbar!</strong> Damit FluxBB richtig funktionieren kann, muss PHP Schreibzugriff auf das Verzeichnis <em>%s</em> haben. Du kannst chmod verwenden, um dem Verzeichnis die entsprechenden Berechtigungen zu geben. Falls du zweifelst, setze chmod auf 0777.',
'Alert avatar'					=>	'<strong>Das Avatar-verzeichnis ist derzeit nicht beschreibbar!</strong> Wenn du möchtest, dass deine Mitglieder ihr eigenes Avatar-Bild hochladen können, muss PHP Schreibberechtigung auf das Verzeichnis <em>%s</em> haben. Du kannst dann später noch in der Administration unter Optionen ein anderes Verzeichnis zum Speichern der Avatar-Bilder auswählen. Du kannst chmod verwenden, um dem Verzeichnis die entsprechenden Berechtigungen zu geben. Falls du zweifelst, setze chmod auf 0777.',
'Alert upload'					=>	'<strong>Das Hochladen von Dateien scheint auf diesem Server nicht erlaubt zu sein!</strong> Wenn du möchtest, dass deine Mitglieder ihre eigenen Avatar-Bilder hochladen können, musst du in der PHP-Konfiguration file_uploads aktivieren. Sobald das Hochladen von Dateien aktiviert wurde, kann das Hochladen von Avatar-Bildern in der Administration unter Optionen freigegeben werden.',
'FluxBB has been installed'		=>	'FluxBB wurde installiert. Um die Installation abzuschließen, folge den unten stehenden Instruktionen.',
'Final instructions'			=>	'Abschließende Hinweise',
'Info 17'						=>	'Um die Installation abzuschließen, musst du auf den nachfolgenden Button klicken, um die Datei config.php herunter zu laden. Diese Datei musst du anschließend ins Wurzelverzeichnis deiner FluxBB-Installation hochladen.',
'Info 18'						=>	'Nachdem du die Datei config.php hochgeladen hast, ist FluxBB vollständig einsatzbereit! Du kannst dann <a href="index.php">hier zur Forenübersicht gehen</a>.',
'Download config.php file'		=>	'Die Datei config.php herunter laden',
'FluxBB fully installed'		=>	'Die FluxBB-Installation ist vollständig abgeschlossen! Du kannst jetzt <a href="index.php">hier zur Forenübersicht gehen</a>.',

);
