<?php

// Sprachdefinitionen, die in profile.php verwendet werden
$lang_profile = array(

// Navigation und Sektionen
'Profile menu'					=>	'Profilmenü',
'Section essentials'			=>	'Grundlegendes',
'Section personal'				=>	'Persönliches',
'Section messaging'				=>	'Messenger',
'Section personality'			=>	'Personalisierung',
'Section display'				=>	'Anzeige',
'Section privacy'				=>	'Privatsphäre',
'Section admin'					=>	'Administration',

// Verschiedenes
'Username and pass legend'		=>	'Gib hier deinen Mitgliedsnamen und dein Passwort ein',
'Personal details legend'		=>	'Gib hier deine persönlichen Details ein',
'Contact details legend'		=>	'Ändere oder ergänze hier deine Daten für Instant Messaging',
'User activity'					=>	'Mitgliedsaktivität',
'Paginate info'					=>	'Gib hier die Anzahl von Themen und Beiträgen an, die pro Seite angezeigt werden sollen.',

// Passwort
'Pass key bad'					=>	'Der eingegebene Aktivierungscode war falsch oder ist abgelaufen. Bitte fordere ein neues Passwort an. Falls es weiterhin zu Problemen kommt, kontaktiere den Administrator unter',
'Pass updated'					=>	'Dein Passwort wurde aktualisiert. Du kannst dich jetzt mit deinem neuen Passwort anmelden.',
'Pass updated redirect'			=>	'Passwort wurde aktualisiert. Leite weiter …',
'Wrong pass'					=>	'Das alte Passwort ist falsch.',
'Change pass'					=>	'Passwort ändern',
'Change pass legend'			=>	'Gib dein neues Passwort ein und bestätige es',
'Old pass'						=>	'Altes Passwort',
'New pass'						=>	'Neues Passwort',
'Confirm new pass'				=>	'Neues Passwort bestätigen',
'Pass info'						=>	'Passwörter müssen mindestens 4 Zeichen lang sein. Groß-/Kleinschreibung wird unterschieden.',

// E-Mail
'Email key bad'					=>	'Der Aktivierungscode war falsch oder ist abgelaufen. Bitte fordere ein neues Passwort an. Falls es weiterhin zu Problemen kommt, kontaktiere den Administrator unter',
'Email updated'					=>	'Deine E-Mail-Adresse wurde aktualisiert.',
'Activate email sent'			=>	'Es wurde eine E-Mail mit Anweisungen, wie die neue E-Mail-Adresse zu aktivieren ist, an die angegebene E-Mail-Adresse gesandt. Falls keine E-Mail bei dir ankommt, kontaktiere bitte den Administrator unter',
'Email legend'					=>	'Gib deine neue E-Mail-Adresse ein',
'Email instructions'			=>	'Eine E-Mail mit einem Aktivierungs-Link wird an deine neue Adresse gesendet. Du musst den Link in dieser E-Mail anklicken, um die neue E-Mail-Adresse zu aktivieren.',
'Change email'					=>	'E-Mail-Adresse ändern',
'New email'						=>	'Neue E-Mail-Adresse',

// Avatar
'Avatars disabled'				=>	'Die Administratoren haben die Verwendung von Avataren deaktiviert.',
'Too large ini'					=>	'Die ausgewählte Datei war zum Hochladen zu groß.',
'Partial upload'				=>	'Die ausgewählte Datei wurde nur teilweise hochgeladen. Bitte versuche es noch einmal.',
'No tmp directory'				=>	'PHP konnte die hochgeladene Datei nicht speichern.',
'No file'						=>	'Du hast keine Datei zum Hochladen ausgewählt.',
'Bad type'						=>	'Die ausgewählte Datei hat ein falsches Format. Erlaubte Formate sind gif, jpeg und png.',
'Too wide or high'				=>	'Die ausgewählte Datei ist breiter und/oder höher als maximal erlaubt',
'Too large'						=>	'Die ausgewählte Datei ist größer als maximal erlaubt',
'pixels'						=>	'Pixel',
'bytes'							=>	'Bytes',
'Move failed'					=>	'Der Server konnte die hochgeladene Datei nicht speichern. Bitte kontaktiere den Administrator unter',
'Unknown failure'				=>	'Ein unbekannter Fehler ist aufgetreten. Bitte versuche es noch einmal.',
'Avatar upload redirect'		=>	'Der Avatar wurde hochgeladen. Leite weiter …',
'Avatar deleted redirect'		=>	'Der Avatar wurde gelöscht. Leite weiter …',
'Avatar desc'					=>	'Ein Avatar ist ein kleines Bild, das unter deinem Mitgliedsnamen in deinen Beiträgen angezeigt wird. Avatare dürfen nicht größer sein als',
'Upload avatar'					=>	'Avatar hochladen',
'Upload avatar legend'			=>	'Gib eine Avatar-Datei zum Hochladen an',
'Delete avatar'					=>	'Avatar löschen', // nur für Administratoren
'File'							=>	'Datei',
'Upload'						=>	'Hochladen', // Beschriftung des Absende-Buttons

// Formular-Prüfung
'Forbidden title'				=>	'Der eingegebene Titel enthält ein verbotenes Wort. Bitte korrigiere dies.',
'Profile redirect'				=>	'Profil aktualisiert. Leite weiter …',

// Profilanzeige
'Users profile'					=>	'%s\'s Profil',
'Username info'					=>	'Mitgliedsname: %s',
'Email info'					=>	'E-Mail: %s',
'Posts info'					=>	'Beiträge: %s',
'Registered info'				=>	'Registriert: %s',
'Last post info'				=>	'Letzter Beitrag: %s',
'Last visit info'				=>	'Letzter Besuch: %s',
'Show posts'					=>	'Alle Beiträge anzeigen',
'Show topics'					=>	'Alle Themen anzeigen',
'Show subscriptions'			=>	'Alle Abonnements anzeigen',
'Realname'						=>	'Dein Name',
'Location'						=>	'Wohnort',
'Website'						=>	'Webseite',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'MSN Messenger',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'Avatar',
'Signature'						=>	'Signatur',
'Sig max size'					=>	'Maximale Länge: %s Zeichen / Maximale Zeilen: %s',
'Avatar legend'					=>	'Lege hier die Optionen für die Anzeige deines Avatars fest',
'Avatar info'					=>	'Ein Avatar ist ein kleines Bild, das unter deinem Mitgliedsnamen in deinen Beiträgen angezeigt wird. Du kannst über den unten stehenden Link deinen eigenen Avatar hochladen.',
'Change avatar'					=>	'Avatar ändern',
'Signature legend'				=>	'Stelle hier deine Signatur zusammen',
'Signature info'				=>	'Eine Signatur ist ein kurzer Text, der an deine Beiträge angehängt wird. Du darfst fast alles eingeben, was du möchtest, z.B. dein Lieblingszitat oder dein Sternzeichen. Du kannst BBCode in der Signatur benutzen, wenn der Administrator es in diesem Forum erlaubt hat. Die erlaubten Möglichkeiten werden unterhalb der Eingabebox angezeigt.',
'Sig preview'					=>	'Aktuelle Signatur-Vorschau:',
'No sig'						=>	'Aktuell keine Signatur im Profil gespeichert.',
'Signature quote/code/list/h'	=>	'Die BBCodes für Zitate, Code, Listen und überschriften sind in den Signaturen nicht erlaubt.',
'Topics per page'				=>	'Themen pro Seite',
'Posts per page'				=>	'Beiträge pro Seite',
'Leave blank'					=>	'Um die Standardeinstellung zu verwenden, lasse die Eingabefelder leer.',
'Subscription legend'			=>	'Setze hier die Optionen für deine Abonnements',
'Notify full'					=>	'Den neuen Beitrag als einfachen Text mit der Benachrichtigungs-E-Mail versenden.',
'Auto notify full'				=>	'Automatisch per E-Mail benachrichtigen, wenn jemand zu einem Thema oder einem Beitrag von dir geantwortet hat.',
'Show smilies'					=>	'Smilies als Bilder anzeigen',
'Show images'					=>	'Bilder in Beiträgen anzeigen.',
'Show images sigs'				=>	'Bilder in den Mitglieder-Signaturen anzeigen.',
'Show avatars'					=>	'Avatare in Beiträgen anzeigen.',
'Show sigs'						=>	'Mitglieder-Signaturen anzeigen.',
'Style legend'					=>	'Stelle hier das gewünschte Forum-Design ein',
'Styles'						=>	'Styles',
'Admin note'					=>	'Administratoren-Notiz',
'Pagination legend'				=>	'Gib hier deine Optionen für die Seiten-Paginierung ein',
'Post display legend'			=>	'Lege deine Optionen für die Anzeige von Beiträgen fest',
'Post display info'				=>	'Wenn du eine langsame Internetverbindung hast, deaktiviere diese Optionen (insbesondere die Anzeige von Bildern in Beiträgen und Signaturen). Das macht das Laden der Seiten schneller.',
'Instructions'					=>	'Wenn du dein Profil änderst, wirst du auf diese Seite weitergeleitet.',

// Administration stuff
'Group membership legend'		=>	'Wähle eine Mitgliedergruppe',
'Save'							=>	'Speichern',
'Set mods legend'				=>	'Lege die Berechtigungen des Moderators fest',
'Moderator in info'				=>	'Wähle die Foren aus, die dieses Mitglied moderieren darf. Achtung: Dies hat nur Auswirkungen auf Moderatoren. Administratoren haben immer alle Berechtigungen in allen Foren.',
'Update forums'					=>	'Moderatoren-Berechtigungen aktualisieren',
'Delete ban legend'				=>	'Mitglieder löschen (nur Administratoren) oder sperren',
'Delete user'					=>	'Mitglied löschen',
'Ban user'						=>	'Mitglied sperren',
'Confirm delete legend'			=>	'Wichtig: Lies dies, bevor du ein Mitglied löschst',
'Confirm delete user'			=>	'Löschen des Mitglied bestätigen',
'Confirmation info'				=>	'Bitte bestätige, dass du das folgende Mitglied löschen willst:', // Der Name des Mitglieds wird dieser Zeichenkette angehangen
'Delete warning'				=>	'Warnung! Gelöschte Mitglieder und/oder Beiträge können NICHT wiederhergestellt werden. Wenn du die Beiträge dieses Mitglieds nicht löschst, können diese später nur noch manuell gelöscht werden.',
'Delete posts'					=>	'Alle Beiträge und Themen dieses Mitglieds löschen.',
'Delete'						=>	'Löschen', // Beschriftung des Absende-Buttons (Bestätigung der Mitgliederlöschung)
'User delete redirect'			=>	'Mitglied gelöscht. Leite weiter …',
'Group membership redirect'		=>	'Gruppenmitgliedschaft gespeichert. Leite weiter  …',
'Update forums redirect'		=>	'Moderatorenrechte aktualisiert. Leite weiter …',
'Ban redirect'					=>	'Leite weiter …',
'No delete admin message'		=>	'Administratoren können nicht gelöscht werden. Um dieses Mitlgied löschen zu können, muss es zunächst einer anderen Mitgliedergruppe zugeordnet werden.',

);
