<?php

// Sprachdefinitionen, die in profile.php und register.php verwendet werden
$lang_prof_reg = array(

'Email legend'				=>	'Gib eine gültige E-Mail-Adresse ein',
'Email legend 2'			=>	'Gib eine gültige E-Mail-Adresse ein und bestätige diese',
'Localisation legend'		=>	'Stelle hier deine Zeitzone und Sprache ein',
'Time zone'					=>	'Zeitzone',
'Time zone info'			=>	'Damit im Forum die Zeit korrekt anzeigt wird, musst du die Zeitzone deines Standortes wählen. Mit aktivierter Sommerzeit-Option wird die Uhrzeit um eine Stunde vorgestellt.',
'DST'						=>	'Sommerzeit (aktuelle Zeit + 1 Stunde).',
'Time format'				=>	'Zeitformat',
'Date format'				=>	'Datumsformat',
'Default'					=>	'Standard',
'Language'					=>	'Sprache',
'Email setting info'		=>	'Stelle hier ein, ob deine E-Mail-Adresse in deinem Mitgliedsprofil und deinen Beiträgen angezeigt werden soll. Stelle auch ein, ob du E-Mails über den Forum-Mailer (E-Mail-Formular) bekommen möchtest oder nicht.',
'Email setting 1'			=>	'E-Mail-Adresse öffentlich anzeigen.',
'Email setting 2'			=>	'E-Mail-Adresse verstecken und E-Mail-Formular aktivieren.',
'Email setting 3'			=>	'E-Mail-Adresse verstecken und E-Mail-Formular deaktivieren.',
'Privacy options legend'	=>	'Setze hier deine Optionen für die Privatsphäre',
'Confirm pass'				=>	'Passwort zur Bestätigung wiederholen',

'Username too short'		=>	'Der Mitgliedsname muss mindestens 2 Zeichen lang sein. Bitte wähle einen anderen (längeren) Mitgliedsnamen.',
'Username too long'			=>	'Der Mitgliedsname darf nicht länger als 25 Zeichen lang sein. Bitte wähle einen anderen (kürzeren) Mitgliedsnamen.',
'Username guest'			=>	'Der Mitgliedsname "Gast" ist reserviert. Bitte wähle einen anderen Mitgliedsnamen.',
'Username IP'				=>	'Der Mitgliedsname darf nicht das Format von IP-Adressen haben. Bitte wähle einen anderen Mitgliedsnamen.',
'Username reserved chars'	=>	'Der Mitgliedsname darf die Zeichen \', " und [ oder ] nicht enthalten. Bitte wähle einen anderen Mitgliedsnamen.',
'Username BBCode'			=>	'Der Mitgliedsname darf keinen BBCode enthalten. Bitte wähle einen anderen Mitgliedsnamen.',
'Banned username'			=>	'Der eingegebene Mitgliedsname ist in diesem Forum gesperrt. Bitte wähle einen anderen Mitgliedsnamen.',
'Pass too short'			=>	'Das Passwort muss mindestens 4 Zeichen lang sein. Bitte wähle ein anderes (längeres) Passwort.',
'Pass not match'			=>	'Die Passwörter stimmen nicht überein. Bitte geh zurück und korrigiere diese.',
'Banned email'				=>	'Die eingegebene E-Mail-Adresse ist in diesem Forum gesperrt, bitte gib eine andere E-Mail-Adresse an.',
'Dupe email'				=>	'Diese E-Mail-Adresse ist bereits vergeben, bitte gib eine andere E-Mail-Adresse an.',
'Sig too long'				=>	'Signaturen dürfen nicht länger als %1$s Zeichen sein. Bitte kürze die Signatur um %2$s Zeichen.',
'Sig too many lines'		=>	'Signaturen dürfen nicht mehr als %s Zeilen haben.',
'Bad ICQ'					=>	'Die angegebene ICQ Nummer ist ungültig, bitte gehe zurück und korrigiere es.',

'UTC-12:00'					=>	'(WEZ-12:00) Internationale Datumsgrenze West',
'UTC-11:00'					=>	'(WEZ-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(WEZ-10:00) Hawaii-Aleuten, Cook-Inseln',
'UTC-09:30'					=>	'(WEZ-09:30) Marquesas-Inseln',
'UTC-09:00'					=>	'(WEZ-09:00) Alaska, Gambier-Inseln',
'UTC-08:30'					=>	'(WEZ-08:30) Pitcairn-Inseln',
'UTC-08:00'					=>	'(WEZ-08:00) Pazifik',
'UTC-07:00'					=>	'(WEZ-07:00) Mountain',
'UTC-06:00'					=>	'(WEZ-06:00) Zentral',
'UTC-05:00'					=>	'(WEZ-05:00) Osten',
'UTC-04:00'					=>	'(WEZ-04:00) Atlantik',
'UTC-03:30'					=>	'(WEZ-03:30) Neufundland',
'UTC-03:00'					=>	'(WEZ-03:00) Amazonas, Zentral-Grönland',
'UTC-02:00'					=>	'(WEZ-02:00) Mittlerer Atlantik',
'UTC-01:00'					=>	'(WEZ-01:00) Azoren, Cape Verde, Östliches Grönland',
'UTC'						=>	'(WEZ) Westeuropäische Zeit, Greenwich',
'UTC+01:00'					=>	'(WEZ+01:00) Mitteleuropäische Zeit (MEZ), Westafrika',
'UTC+02:00'					=>	'(WEZ+02:00) Osteuropäische Zeit, Zentralafrika',
'UTC+03:00'					=>	'(WEZ+03:00) Moskau, Ostafrika',
'UTC+03:30'					=>	'(WEZ+03:30) Iran',
'UTC+04:00'					=>	'(WEZ+04:00) Gulf, Samara',
'UTC+04:30'					=>	'(WEZ+04:30) Afghanistan',
'UTC+05:00'					=>	'(WEZ+05:00) Pakistan, Jekaterinburg',
'UTC+05:30'					=>	'(WEZ+05:30) Indien, Sri Lanka',
'UTC+05:45'					=>	'(WEZ+05:45) Nepal',
'UTC+06:00'					=>	'(WEZ+06:00) Bangladesh, Bhutan, Nowosibirsk',
'UTC+06:30'					=>	'(WEZ+06:30) Cocos-Inseln, Myanmar',
'UTC+07:00'					=>	'(WEZ+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'					=>	'(WEZ+08:00) Groß-China, Westliches Australien, Irkutsk',
'UTC+08:45'					=>	'(WEZ+08:45) Südöstliches West-Australien',
'UTC+09:00'					=>	'(WEZ+09:00) Japan, Korea, Chita',
'UTC+09:30'					=>	'(WEZ+09:30) Zentral-Australian',
'UTC+10:00'					=>	'(WEZ+10:00) Ost-Australien, Wladiwostok',
'UTC+10:30'					=>	'(WEZ+10:30) Lord Howe',
'UTC+11:00'					=>	'(WEZ+11:00) Solomon-Inseln, Magadan',
'UTC+11:30'					=>	'(WEZ+11:30) Norfolk-Inseln',
'UTC+12:00'					=>	'(WEZ+12:00) Neuseeland, Fiji, Kamtschatka',
'UTC+12:45'					=>	'(WEZ+12:45) Chatham-Inseln',
'UTC+13:00'					=>	'(WEZ+13:00) Tonga, Phoenix-Inseln',
'UTC+14:00'					=>	'(WEZ+14:00) Grenz-Inseln'

);
