<?php

// Sprachdefinitionen, die in search.php verwendet werden
$lang_search = array(

// Das Suchformular
'User search'						=>	'Mitgliedersuche',
'No search permission'				=>	'Du hast keine Berechtigung, die Suchfunktion zu nutzen.',
'Search flood'						=>	'Zwischen 2 Suchvorgängen müssen mindestens %s Sekunden vergehen. Bitte warte etwas und versuche es dann noch einmal.',
'Search'							=>	'Suche',
'Search criteria legend'			=>	'Gib deine Suchkriterien ein',
'Search info'						=>	'<b>Einfache Suche:</b> Trenne deine Suchbegriffe mit Leerzeichen voneinander.<br><br><b>Erweiterte Suche:</b> Benutze AND, OR und NOT in Verbindung mit deinen Suchbegriffen, um detaillierter zu suchen.<br>Du kannst Sternchen (*) als Platzhalter für die Suche von Teilbegriffen verwenden. (eine Suche nach *ux* findet z.B. auch FluxBB etc.)',
'Keyword search'					=>	'Schlüsselwortsuche',
'Author search'						=>	'Autor suchen',
'Search in legend'					=>	'Wähle, wo gesucht werden soll',
'Search in info'					=>	'Wähle, in welchem Forum gesucht werden soll und ob sich die Suche nur auf Thementitel, Beitragstexte oder beides erstrecken soll.',
'Forum search'						=>	'Forum',
'All forums'						=>	'Alle Foren',
'Search in'							=>	'Suche in',
'Message and subject'				=>	'Beitragstext und Thementitel',
'Message only'						=>	'Nur im Beitragstext',
'Topic only'						=>	'Nur im Thementitel',
'Sort by'							=>	'Treffer sortieren nach',
'Sort order'						=>	'Sortierreihenfolge',
'Search results legend'				=>	'Wähle, wie die Suchergebnisse angezeigt werden sollen',
'Search results info'				=>	'Du kannst wählen, wie die Suchergebnisse sortiert und angezeigt werden sollen.',
'Sort by post time'					=>	'Beitragszeit',
'Sort by author'					=>	'Autor',
'Sort by subject'					=>	'Thema',
'Sort by forum'						=>	'Forum',
'Ascending'							=>	'Aufsteigend',
'Descending'						=>	'Absteigend',
'Show as'							=>	'Ergebnisse zeigen als',
'Show as topics'					=>	'Themen',
'Show as posts'						=>	'Beiträge',

// Ergebnisse
'Search results'					=>	'Suchergebnisse',
'Search topics'						=>	'Themen suchen',
'Search posts'						=>	'Beiträge suchen',
'Quick search show_new'				=>	'Neu',
'Quick search show_recent'			=>	'Aktiv',
'Quick search show_unanswered'		=>	'Unbeantwortet',
'Quick search show_replies'			=>	'Beantwortet',
'Quick search show_user_topics'		=>	'Von %s',
'Quick search show_user_posts'		=>	'Von %s',
'Quick search show_subscriptions'	=>	'Abonniert von %s',
'By keywords show as topics'		=>	'Mit Beiträgen mit den Schlüsselbegriffen \'%s\'',
'By keywords show as posts'			=>	'Mit den Schlüsselbegriffen \'%s\'',
'By user show as topics'			=>	'Mit Beiträgen von %s',
'By user show as posts'				=>	'Von %s',
'By both show as topics'			=>	'Mit den Schlüsselbegriffen \'%s\' in Beiträgen von %s',
'By both show as posts'				=>	'Mit den Schlüsselbegriffen \'%s\' von %s',
'No terms'							=>	'Du musst mindestens ein Schlüsselwort und/oder Autor für die Suche eingeben.',
'No hits'							=>	'Deine Suche ergab leider keine Treffer.',
'No user posts'						=>	'Es gibt keine Beiträge von diesem Mitglied in diesem Forum.',
'No user topics'					=>	'Es gibt keine Themen von diesem Mitglied in diesem Forum.',
'No subscriptions'					=>	'Du hast aktuell kein Thema abonniert.',
'No new posts'						=>	'Es gibt keine neuen Beiträge seit deinem letzten Besuch.',
'No recent posts'					=>	'Es gibt keine neuen Beiträge in den letzten 24 Stunden.',
'No unanswered'						=>	'Es gibt keine unbeantworteten Beiträge in diesem Forum.',
'Go to post'						=>	'Beitrag anzeigen',
'Go to topic'						=>	'Thema anzeigen'

);
