<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'جستجوی کاربر',
'No search permission'				=>	'شما اجازه استفاده از امکان جستجو را ندارید.',
'Search flood'						=>	'حداقل باید %s ثانیه بین هر جسجتو فاصله باشد. کمی کمنتظر بمانید و دوباره تلاش کنید.',
'Search'							=>	'جستجو',
'Search criteria legend'			=>	'ضوابط جستجوی خود را وارد کنید.',
'Search info'						=>	'برای جستجو به همراه کلمات کلیدی هر کلمه کلیدی را با یک فاصله از کلمه قلی وارد کنید.',
'Keyword search'					=>	'جستجو بر اساس کلمه کلیدی',
'Author search'						=>	'جستجو بر اساس نویسنده',
'Search in legend'					=>	'انتخاب جستجو در',
'Search in info'					=>	'انجمن مورد جستجوی خود را انتخاب کنید.',
'Search multiple forums info'		=>	'اگر انجمنی برای جستجو انتخاب نشود خودبه خود نتایج جستجو شامل تمام انجمن ها خواهد شد.',
'Forum search'						=>	'انجمن',
'All forums'						=>	'همه انجمن ها',
'Search in'							=>	'جسجتجو در',
'Message and subject'				=>	'متن ارسال و عنوان موضوع',
'Message only'						=>	'فقط متن ارسال',
'Topic only'						=>	'فقط عنوان موضوع',
'Sort by'							=>	'لیست کردن بر اساس',
'Sort order'						=>	'لیست کردن بر اساس',
'Search results legend'				=>	'انتخاب چگونگی نمایش نتایج جستجو',
'Search results info'				=>	'شما می توانید بر چه اساسی نتایج جستجوی شما نمایش داده شود.',
'Sort by post time'					=>	'زمان ارسال',
'Sort by author'					=>	'نویسنده',
'Sort by subject'					=>	'عنوان',
'Sort by forum'						=>	'انجمن',
'Ascending'							=>	'صعودی',
'Descending'						=>	'نزولی',
'Show as'							=>	'نمایش نتایج بر اساس',
'Show as topics'					=>	'موضوعات',
'Show as posts'						=>	'ارسال ها',

// Results
'Search'							=>	'جستجو',
'Search results'					=>	'نتایج جستجو',
'Quick search show_new'				=>	'جدید',
'Quick search show_recent'			=>	'فعال',
'Quick search show_unanswered'		=>	'بی پاسخ',
'Quick search show_replies'			=>	'ارسال شده',
'Quick search show_user_topics'		=>	'موضوعات ایجاد شده توسط %s',
'Quick search show_user_posts'		=>	'پست های ارسال شده توسط %s',
'Quick search show_subscriptions'	=>	'عضو شده توسط %s',
'By keywords show as topics'		=>	'موضوعات ارسال شده همراه با متون شامل \'%s\' ',
'By keywords show as posts'			=>	'ارسال های شامل \'%s\'',
'By user show as topics'			=>	'موضوعات همراه با ارسال توسط %s',
'By user show as posts'				=>	'ارسال شده توسط %s',
'By both show as topics'			=>	'موضوعات با ارسال های \'%s\' توسط %s',
'By both show as posts'				=>	'ارسال های شامل \'%s\' توسط %s',
'No terms'							=>	'شما برای جستجو حداقل باید یک نام نویسنده یا یک کلمه کلیدی را وارد کنید.',
'No hits'							=>	'جسجتجوی شما هیج نتیجه ای را به همراه نداشت.',
'No user posts'						=>	'ارسالی توسط این کاربر در انجمن وجود ندارد.',
'No user topics'					=>	'موضوع ایجاد شده ای توسط این کاربر در انجمن وجود ندارد.',
'No subscriptions'					=>	'این کاربر در هیچ موضوعی عضویت ندارد',
'No new posts'						=>	'از آخرین ورود شما به انجمن هیچ موضوعی با ارسال جدید وجود ندارد.',
'No recent posts'					=>	'هیچ پستی طی ۲۴ ساعت گذشته در انجمن ارسال نشده است..',
'No unanswered'						=>	'هیچ ارسال بدون پاسخی در انجمن وجود ندارد.',
'Go to post'						=>	'رفتن به ارسال',
'Go to topic'						=>	'رفتن به موضوع'

);
