<?php

// Language definitions used in admin-groups.php
$lang_admin_groups = array(

'Must enter title message'		=>	'Voc&#234; deve fornecer um t&#237;tulo de grupo.',
'Title already exists message'	=>	'J&#225; existe um grupo com o t&#237;tulo <strong>%s</strong>.',
'Default group redirect'		=>	'Grupo padr&#227;o definido. Redireccionando &#8230;',
'Cannot remove default message'	=>	'O grupo padr&#227;o n&#227;o pode ser removido. Para poder excluir este grupo voc&#234; precisa primeiro definir um outro grupo como padr&#227;o.',
'Group removed redirect'		=>	'Grupo removido. Redireccionando &#8230;',
'Group added redirect'			=>	'Grupo adicionado. Redireccionando &#8230;',
'Group edited redirect'			=>	'Grupo editado. Redireccionando &#8230;',

'Add groups head'				=>	'Adicionar/configurar grupos',
'Add group subhead'				=>	'Adicionar novo grupo',
'New group label'				=>	'Basear novo grupo em',
'New group help'				=>	'Seleccione um grupo de usu&#225;rios do qual o novo grupo herdar&#225; configura&#231;&#245;es de permiss&#245;es. A pr&#243;xima p&#225;gina permitir&#225; ajustar as configura&#231;&#245;es herdadas.',
'Default group subhead'			=>	'Definir grupo padr&#227;o',
'Default group label'			=>	'Grupo padr&#227;o',
'Default group help'			=>	'Este &#233; o grupo de usu&#225;rios padr&#227;o, ex. o grupo em que os usu&#225;rios s&#227;o colocados ao se registarem. Por raz&#245;es de seguran&#231;a, usu&#225;rios n&#227;o podem ser colocados nos grupos de moderadores e administradores por padr&#227;o.',
'Existing groups head'			=>	'Grupos existentes',
'Edit groups subhead'			=>	'Editar/excluir grupos',
'Edit groups info'				=>	'Os grupos pr&#233;-definidos Visitantes, Administradores, Moderadores e Membros n&#227;o podem ser removidos. Contudo, eles podem ser editados. Por favor, note que algumas op&#231;&#245;es n&#227;o est&#227;o dispon&#237;veis em alguns grupos (ex. a permiss&#227;o <em>editar mensagens</em> para visitantes). Administradores possuem sempre permiss&#245;es totais.',
'Edit link'						=>	'Editar',
'Delete link'					=>	'Excluir',
'Group delete head'				=>	'Apagar grupo',
'Confirm delete subhead'		=>	'Confirmar que deseja apagar o grupo',
'Confirm delete info'			=>	'Tem a certeza de que deseja apagar o grupo <strong>%s</strong>?',
'Confirm delete warn'			=>	'AVISO! N&#227;o &#233; poss&#237;vel restaurar o grupo ap&#243;s apagar.',
'Delete group head'				=>	'Apagar grupo',
'Move users subhead'			=>	'Mover usu&#225;rios actualmente no grupo',
'Move users info'				=>	'O grupo <strong>%s</strong> possui actualmente <strong>%s</strong> membros. Por favor, seleccione um grupo para o qual estes usu&#225;rios dever&#227;o ser movidos durante a exclus&#227;o.',
'Move users label'				=>	'Mover usu&#225;rios para',
'Delete group'					=>	'Apagar grupo',

'Group settings head'			=>	'Configura&#231;&#245;es de grupo',
'Group settings subhead'		=>	'Definir op&#231;&#245;es e permiss&#245;es do grupo',
'Group settings info'			=>	'As op&#231;&#245;es e permiss&#245;es abaixo s&#227;o as permiss&#245;es padr&#227;o para o grupo de usu&#225;rios. Estas op&#231;&#245;es aplicam-se caso nenhuma permiss&#227;o espec&#237;fica do f&#243;rum esteja em efeito.',
'Group title label'				=>	'T&#237;tulo do grupo',
'User title label'				=>	'T&#237;tulo do usu&#225;rio',
'User title help'				=>	'Este t&#237;tulo ir&#225; sobrescrever quaisquer classes que os usu&#225;rios deste grupo tenham conquistado. Deixe em branco para usar a classe ou t&#237;tulo padr&#227;o.',
'Mod privileges label'			=>	'Dar privil&#233;gios de modera&#231;&#227;o aos usu&#225;rios',
'Mod privileges help'			=>	'Para que um usu&#225;rio deste grupo possa ter habilidades de modera&#231;&#227;o, ele deve ser designado como moderador de um ou mais f&#243;runs. Isto &#233; feito atrav&#233;s da p&#225;gina de administra&#231;&#227;o de usu&#225;rio do perfil do usu&#225;rio.',
'Edit profile label'			=>	'Permitir que moderadores editem perfis dos usu&#225;rios',
'Edit profile help'				=>	'Se privil&#233;gios de moderador estiverem activos, permite que usu&#225;rios neste grupo editem perfis de usu&#225;rios.',
'Rename users label'			=>	'Permitir que moderadores alterem o nome de usu&#225;rios',
'Rename users help'				=>	'Se privil&#233;gios de moderador estiverem activos, permite que usu&#225;rios deste grupo alterem o nome de usu&#225;rios.',
'Change passwords label'		=>	'Permitir que moderadores alterem senhas',
'Change passwords help'			=>	'Se privil&#233;gios de moderador estiverem activos, permite que usu&#225;rios deste grupo alterem senhas dos usu&#225;rios.',
'Ban users label'				=>	'Permitir moderadores banirem usu&#225;rios',
'Ban users help'				=>	'Se privil&#233;gios de moderador estiverem activos, permite que usu&#225;rios deste grupo possam banir outros usu&#225;rios.',
'Read board label'				=>	'Ler site',
'Read board help'				=>	'Permitir que usu&#225;rios deste grupo vejam o site. Esta configura&#231;&#227;o se aplica a todos os aspectos do site e portanto n&#227;o podem ser sobrescritas por configura&#231;&#245;es espec&#237;ficas de f&#243;runs. Caso definido como "N&#227;o", usu&#225;rios deste grupo apenas conseguir&#227;o se registar e autenticar no site.',
'View user info label'			=>	'Visualizar informa&#231;&#245;es de usu&#225;rio',
'View user info help'			=>	'Permitir que usu&#225;rios visualizar a lista e perfis de usu&#225;rios.',
'Post replies label'			=>	'Responder',
'Post replies help'				=>	'Permitir que usu&#225;rios deste grupo respondam os t&#243;picos.',
'Post topics label'				=>	'Criar t&#243;picos',
'Post topics help'				=>	'Permitir que usu&#225;rios deste grupo criem novos t&#243;picos.',
'Edit posts label'				=>	'Editar mensagens',
'Edit posts help'				=>	'Permitir que usu&#225;rios deste grupo editem suas pr&#243;prias mensagens.',
'Delete posts label'			=>	'Excluir mensagens',
'Delete posts help'				=>	'Permitir que usu&#225;rios deste grupo excluam suas pr&#243;prias mensagens.',
'Delete topics label'			=>	'Excluir t&#243;picos',
'Delete topics help'			=>	'Permitir que usu&#225;rios deste grupo excluam seus pr&#243;prios t&#243;picos (incluindo as mensagens do t&#243;pico).',
'Set own title label'			=>	'Definir o pr&#243;prio t&#237;tulo de usu&#225;rio',
'Set own title help'			=>	'Permitir que usu&#225;rios deste grupo definam seu pr&#243;prio t&#237;tulo de usu&#225;rio.',
'User search label'				=>	'Usar a pesquisa',
'User search help'				=>	'Permitir que usu&#225;rios deste grupo utilizem a fun&#231;&#227;o de pesquisa.',
'User list search label'		=>	'Pesquisar lista de usu&#225;rios',
'User list search help'			=>	'Permitir que usu&#225;rios deste grupo pesquisem por usu&#225;rios na lista de usu&#225;rios.',
'Send e-mails label'			=>	'Enviar e-mails',
'Send e-mails help'				=>	'Permitir que usu&#225;rios deste grupo enviem e-mails para outros usu&#225;rios.',
'Post flood label'				=>	'Intervalo de excesso de mensagens',
'Post flood help'				=>	'N&#250;mero em segundos que os usu&#225;rios deste grupo precisam esperar entre mensagens. Use 0 para desabilitar.',
'Search flood label'			=>	'Intervalo de excesso de pesquisas',
'Search flood help'				=>	'N&#250;mero em segundos que os usu&#225;rios deste grupo precisam esperar entre pesquisas. Use 0 para desabilitar.',
'E-mail flood label'			=>	'Intervalo de excesso de e-mails',
'E-mail flood help'				=>	'N&#250;mero em segundos que os usu&#225;rios deste grupo precisam esperar entre e-mails. Use 0 para desabilitar.',
'Moderator info'				=>	'Por favor, note que para que um usu&#225;rio deste grupo tenha habilidade de modera&#231;&#227;o, ele deve ser designado como moderador de um ou mais f&#243;runs. Isto &#233; feito atrav&#233;s da p&#225;gina de administra&#231;&#227;o de usu&#225;rio do perfil do usu&#225;rio.',

);
