<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'N&#227;o foi poss&#237;vel procurar actualiza&#231;&#245;es j&#225; que \'allow_url_fopen\' est&#225; desactivado no sistema.',
'Upgrade check failed message'		=>	'Procura por actualiza&#231;&#245;es falhou por causas desconhecidas.',
'Running latest version message'	=>	'Voc&#234; est&#225; a usar a vers&#227;o mais recente do FluxBB.',
'New version available message'		=>	'Uma nova vers&#227;o do FluxBB foi lan&#231;ada. Voc&#234; pode descarregar a &#250;ltima vers&#227;o em %s.',
'Not available'						=>	'N&#227;o dispon&#237;vel',
'Forum admin head'					=>	'Administra&#231;&#227;o do f&#243;rum',
'NA'								=>	'N/D',
'Welcome to admin'					=>	'Bem-vindo ao painel de controlo administrativo do FluxBB. A partir daqui voc&#234; pode controlar aspectos vitais do f&#243;rum. Dependendo se voc&#234; &#233; um administrador ou um moderador voc&#234; pode:',
'Welcome 1'							=>	'Organizar categorias e f&#243;runs.',
'Welcome 2'							=>	'Definir op&#231;&#245;es e prefer&#234;ncias para todo o f&#243;rum.',
'Welcome 3'							=>	'Controle de permiss&#245;es para usu&#225;rios e visitantes.',
'Welcome 4'							=>	'Visualizar estat&#237;sticas de IP para usu&#225;rios.',
'Welcome 5'							=>	'Banir usu&#225;rios.',
'Welcome 6'							=>	'Censurar palavras.',
'Welcome 7'							=>	'Definir classes de usu&#225;rios.',
'Welcome 8'							=>	'Eliminar mensagens antigas.',
'Welcome 9'							=>	'Gerir relat&#243;rios de mensagens.',
'Statistics head'					=>	'Estat&#237;sticas',
'FluxBB version label'				=>	'FluxBB vers&#227;o',
'Check for upgrade'					=>	'Procurar por actualiza&#231;&#245;es',
'FluxBB version data'				=>	'v%s - %s',
'Server statistics label'			=>	'Estat&#237;sticas do servidor',
'View server statistics'			=>	'Ver as estat&#237;sticas do servidor',
'Support label'						=>	'Suporte',
'Forum label'						=>	'F&#243;rum',
'IRC label'							=>	'Canal de IRC',

// Language definitions used in admin_statistics.php
'PHPinfo disabled message'			=>	'A fun&#231;&#227;o PHP phpinfo() foi desabilitada neste servidor.',
'Server statistics head'			=>	'Estat&#237;sticas do servidor',
'Server load label'					=>	'Carga do servidor',
'Server load data'					=>	'%s - %s usu&#225;rio(s) online',
'Environment label'					=>	'Ambiente',
'Environment data OS'				=>	'Sistema operacional: %s',
'Show info'							=>	'Exibir informa&#231;&#245;es',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Acelerador: %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Cache PHP Alternativo (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Base de dados',
'Database data rows'				=>	'Tabelas: %s',
'Database data size'				=>	'Tamanho: %s',

);
