<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'			=>	'Nenhum membro registado com este nome de usu&#225;rio. Se voc&#234; deseja adicionar um banimento n&#227;o ligado a um nome de usu&#225;rio espec&#237;fico apenas deixe o nome de usu&#225;rio em branco.',
'No user ID message'		=>	'Nenhum usu&#225;rio registado com este ID.',
'User is admin message'		=>	'O usu&#225;rio %s &#233; um administrador e n&#227;o pode ser banido. Se voc&#234; deseja banir um administrador, precisa primeiro rebaix&#225;-lo para usu&#225;rio.',
'User is mod message'		=>	'O usu&#225;rio %s &#233; um moderador e n&#227;o pode ser banido. Se voc&#234; deseja banir um moderador, precisa primeiro rebaix&#225;-lo para usu&#225;rio.',
'Must enter message'		=>	'Voc&#234; deve fornecer um nome de usu&#225;rio, endere&#231;o IP ou endere&#231;o de e-mail (pelo menos).',
'Cannot ban guest message'	=>	'O usu&#225;rio visitante n&#227;o pode ser banido.',
'Invalid IP message'		=>	'Voc&#234; forneceu um endere&#231;o ou faixa de endere&#231;os IP inv&#225;lido.',
'Invalid e-mail message'	=>	'O endere&#231;o de e-mail (ex. membro@dom&#237;nio.pt) ou dom&#237;nio de endere&#231;o de e-mail (ex. dom&#237;nio.pt) fornecido &#233; inv&#225;lido.',
'Invalid date message'		=>	'Voc&#234; forneceu uma data de expira&#231;&#227;o inv&#225;lida.',
'Invalid date reasons'		=>	'O formato deve ser AAAA-MM-DD e a data deve ser de pelo menos um dia no futuro.',
'Ban added redirect'		=>	'Banimento adicionado. Redireccionando &#8230;' ,
'Ban edited redirect'		=>	'Banimento editado. Redireccionando &#8230;',
'Ban removed redirect'		=>	'Banimento removido. Redireccionando &#8230;',

'New ban head'				=>	'Novo banimento',
'Add ban subhead'			=>	'Adicionar banimento',
'Username label'			=>	'Nome de usu&#225;rio',
'Username help'				=>	'O nome de usu&#225;rio a ser banido (insens&#237;vel a letras mai&#250;sculas/min&#250;sculas).',
'Username advanced help'	=>	'O nome de usu&#225;rio a ser banido (insens&#237;vel a letras mai&#250;sculas/min&#250;sculas). A pr&#243;xima p&#225;gina permitir&#225; definir um IP e e-mail personalizados. Se deseja banir um e-mail ou endere&#231;o/faixa de endere&#231;os IP espec&#237;ficos apenas deixe em branco.',

'Ban search head'			=>	'Pesquisar banimento',
'Ban search subhead'		=>	'Forne&#231;a o crit&#233;rio de pesquisa',
'Ban search info'			=>	'Pesquisar por banimentos na base de dados. Voc&#234; pode fornecer um ou mais termos de pesquisa. Atalhos na forma de asteriscos (*) s&#227;o aceites. Para listar todos os banimentos deixe todos os campos em branco.',
'Date help'					=>	'(aaaa-mm-dd)',
'Message label'				=>	'Mensagem',
'Expire after label'		=>	'Expirar depois',
'Expire before label'		=>	'Expirar antes',
'Order by label'			=>	'Ordenar por',
'Order by username'			=>	'Nome de usu&#225;rio',
'Order by ip'				=>	'IP',
'Order by e-mail'			=>	'E-mail',
'Order by expire'			=>	'Data de expira&#231;&#227;o',
'Ascending'					=>	'Ascendente',
'Descending'				=>	'Descendente',
'Submit search'				=>	'Pesquisar',

'E-mail label'				=>	'E-mail',
'E-mail help'				=>	'O e-mail ou dom&#237;nio de e-mail que voc&#234; deseja banir (ex. alguem@algumlugar.pt ou algumlugar.com.pt). Veja "Permitir endere&#231;os de e-mail banidos" em Permiss&#245;es para obter mais informa&#231;&#245;es.',
'IP label'					=>	'Endere&#231;o IP/Faixa de endere&#231;os IP',
'IP help'					=>	'O endere&#231;o IP ou faixa de endere&#231;os IP que voc&#234; deseja banir (ex. 150.11.110.1 ou 150.11.110). Separe os endere&#231;os com espa&#231;os. Se um IP j&#225; estiver listado significa que &#233; o &#250;ltimo IP conhecido do usu&#225;rio registado na base de dados.',
'IP help link'				=>	'Clique %s para ver estat&#237;sticas de IP para este usu&#225;rio.',
'Ban advanced head'			=>	'Configura&#231;&#245;es avan&#231;adas de banimento',
'Ban advanced subhead'		=>	'Completar banimento com IP e e-mail',
'Ban message label'			=>	'Mensagem de banimento',
'Ban message help'			=>	'Uma mensagem que ser&#225; exibida ao usu&#225;rio banido quando visitar o f&#243;rum.',
'Message expiry subhead'	=>	'Mensagem e expira&#231;&#227;o do banimento',
'Ban IP range info'			=>	'Voc&#234; deve ser cuidadoso ao banir uma faixa de endere&#231;os IP devido a possibilidade de haver m&#250;ltiplos usu&#225;rios na faixa de IP definida.',
'Expire date label'			=>	'Data de expira&#231;&#227;o',
'Expire date help'			=>	'A data em que este banimento dever&#225; ser automaticamente removido (formato: aaaa-mm-dd). Deixe em branco para desactivar a remo&#231;&#227;o autom&#225;tica.',

'Results head'				=>	'Resultados da Pesquisa',
'Results username head'		=>	'Nome de usu&#225;rio',
'Results e-mail head'		=>	'E-mail',
'Results IP address head'	=>	'IP/Faixa de IP',
'Results expire head'		=>	'Expira',
'Results message head'		=>	'Mensagem',
'Results banned by head'	=>	'Banido por',
'Results actions head'		=>	'Ac&#231;&#245;es',
'No match'					=>	'Nenhum resultado',
'Unknown'					=>	'Desconhecido',

);
