<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'Menu do perfil',
'Section essentials'			=>	'Essenciais',
'Section personal'				=>	'Pessoal',
'Section messaging'				=>	'Comunica&#231;&#227;o',
'Section personality'			=>	'Personalidade',
'Section display'				=>	'Exibi&#231;&#227;o',
'Section privacy'				=>	'Privacidade',
'Section admin'					=>	'Administra&#231;&#227;o',

// Miscellaneous
'Username and pass legend'		=>	'Digite seu nome de usu&#225;rio e senha',
'Personal details legend'		=>	'Digite seus dados pessoais',
'Contact details legend'		=>	'Digite seus detalhes de comunica&#231;&#227;o',
'User activity'					=>	'Actividade do usu&#225;rio',
'Paginate info'					=>	'Digite o n&#250;mero de t&#243;picos e mensagens que deseja visualizar em cada p&#225;gina.',

// Password stuff
'Pass key bad'					=>	'A chave de activa&#231;&#227;o de senha especificada est&#225; incorrecta ou expirou. Por favor fa&#231;a outra solicita&#231;&#227;o de nova senha. Se isto falhar, contacte o administrador do f&#243;rum em',
'Pass updated'					=>	'A sua senha foi actualizada. Voc&#234; pode agora se autenticar usando a nova senha.',
'Pass updated redirect'			=>	'Senha actualizada. Redireccionando &#8230;',
'Wrong pass'					=>	'Senha antiga errada.',
'Change pass'					=>	'Alterar a senha',
'Change pass legend'			=>	'Digite e confirme a sua nova senha',
'Old pass'						=>	'Antiga senha',
'New pass'						=>	'Nova senha',
'Confirm new pass'				=>	'Confirmar nova senha',
'Pass info'						=>	'Senhas devem ter pelo menos 4 caracteres. Senhas s&#227;o sens&#237;veis a mai&#250;sculas/min&#250;sculas.',

// Email stuff
'Email key bad'					=>	'A chave de activa&#231;&#227;o de e-mail especificada est&#225; errada ou expirou. Por favor fa&#231;a outra solicita&#231;&#227;o de altera&#231;&#227;o de e-mail. Se isto falhar, contacte o administrador do f&#243;rum em',
'Email updated'					=>	'O seu endere&#231;o de e-mail foi actualizado.',
'Activate email sent'			=>	'Um e-mail foi enviado para o endere&#231;o especificado com instru&#231;&#245;es sobre como activar o seu novo endere&#231;o de e-mail. Caso n&#227;o o receba, voc&#234; pode contactar o administrador do f&#243;rum em',
'Email legend'					=>	'Digite o seu novo endere&#231;o de e-mail',
'Email instructions'			=>	'Um e-mail ser&#225; enviado ao seu novo endere&#231;o com um link de activa&#231;&#227;o. Voc&#234; deve clicar no link no e-mail para activar o seu novo endere&#231;o.',
'Change email'					=>	'Alterar endere&#231;o de e-mail',
'New email'						=>	'Novo e-mail',

// Avatar upload stuff
'Avatars disabled'				=>	'O administrador desactivou o suporte a avatares.',
'Too large ini'					=>	'O ficheiro seleccionado &#233; muito grande para ser enviado. O servidor n&#227;o permitiu o envio.',
'Partial upload'				=>	'O ficheiro seleccionado foi apenas parcialmente enviado. Por favor tente novamente.',
'No tmp directory'				=>	'O PHP n&#227;o pode guardar o ficheiro enviado num local tempor&#225;rio.',
'No file'						=>	'Voc&#234; n&#227;o seleccionou um ficheiro para enviar.',
'Bad type'						=>	'O ficheiro que voc&#234; tentou enviar &#233; de um formato n&#227;o permitido. Os formatos permitidos s&#227;o gif, jpeg e png.',
'Too wide or high'				=>	'O ficheiro que voc&#234; tentou enviar &#233; mais largo e/ou alto que o m&#225;ximo permitido',
'Too large'						=>	'O ficheiro que voc&#234; tentou enviar &#233; mais largo que o m&#225;ximo permitido',
'pixels'						=>	'pixeis',
'bytes'							=>	'bytes',
'Move failed'					=>	'O servidor n&#227;o pode guardar o ficheiro enviado. Por favor contacte o administrador do f&#243;rum em',
'Unknown failure'				=>	'Um erro desconhecido ocorreu. Por favor tente novamente.',
'Avatar upload redirect'		=>	'Avatar enviado. Redireccionando &#8230;',
'Avatar deleted redirect'		=>	'Avatar apagado. Redireccionando &#8230;',
'Avatar desc'					=>	'Um avatar &#233; uma pequena imagem que ser&#225; exibida abaixo do seu nome de usu&#225;rio nas suas mensagens. N&#227;o pode ser maior que',
'Upload avatar'					=>	'Enviar avatar',
'Upload avatar legend'			=>	'Escolha um ficheiro para enviar e usar como avatar',
'Delete avatar'					=>	'Apagar avatar', // only for admins
'File'							=>	'Ficheiro',
'Upload'						=>	'Enviar', // submit button

// Form validation stuff
'Forbidden title'				=>	'O t&#237;tulo que voc&#234; digitou cont&#233;m uma palavra proibida. Voc&#234; deve escolher um t&#237;tulo diferente.',
'Profile redirect'				=>	'Perfil actualizado. Redireccionando &#8230;',

// Profile display stuff
'Users profile'					=>	'Perfil de %s',
'Username info'					=>	'Nome de usu&#225;rio: %s',
'Email info'					=>	'E-mail: %s',
'Posts info'					=>	'Mensagens: %s',
'Registered info'				=>	'Registado: %s',
'Last post info'				=>	'&#218;ltima mensagem: %s',
'Last visit info'				=>	'&#218;ltima visita: %s',
'Show posts'					=>	'Exibir todas as mensagens',
'Show topics'					=>	'Exibir todos os t&#243;picos',
'Show subscriptions'			=>	'Exibir todas as subscri&#231;&#245;es',
'Realname'						=>	'Nome real',
'Location'						=>	'Localiza&#231;&#227;o',
'Website'						=>	'Website',
'Invalid website URL'			=>  'A URL do website que voc&#234; digitou &#233; inv&#225;lida.',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'MSN Messenger',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'Avatar',
'Signature'						=>	'Assinatura',
'Sig max size'					=>	'Comprimento m&#225;ximo: %s caracteres / M&#225;ximo de linhas: %s',
'Avatar legend'					=>	'Defina suas op&#231;&#245;es de exibi&#231;&#227;o de avatar',
'Avatar info'					=>	'Um avatar &#233; uma pequena imagem que ser&#225; exibida em todas as suas mensagens. Voc&#234; pode enviar um avatar clicando no link abaixo.',
'Change avatar'					=>	'Trocar avatar',
'Signature legend'				=>	'Componha a  sua assinatura',
'Signature info'				=>	'Uma assinatura &#233; um pequeno texto que &#233; anexado abaixo de suas mensagens. Nele, voc&#234; pode inserir qualquer coisa que desejar. Talvez voc&#234; queira inserir a sua cita&#231;&#227;o favorita ou seu signo. Voc&#234; decide! Na sua assinatura voc&#234; pode usar BBCode se for permitido pela administra&#231;&#227;o do f&#243;rum. Voc&#234; pode ver as fun&#231;&#245;es que s&#227;o permitidas listadas abaixo do campo de edi&#231;&#227;o da sua assinatura.',
'Sig preview'					=>	'Pr&#233;via da assinatura actual:',
'No sig'						=>	'N&#227;o h&#225; uma assinatura definida no seu perfil.',
'Signature quote/code/list/h'	=>	'As tags BBCode quote, code, list, e heading n&#227;o s&#227;o permitidos em assinaturas.',
'Topics per page'				=>	'T&#243;picos',
'Posts per page'				=>	'Mensagens',
'Leave blank'					=>	'Deixe em branco para usar o padr&#227;o do f&#243;rum.',
'Subscription legend'			=>	'Defina suas op&#231;&#245;es de subscri&#231;&#227;o',
'Notify full'					=>	'Inclua uma vers&#227;o em texto simples das novas mensagens em e-mails de notifica&#231;&#227;o de inscri&#231;&#245;es.',
'Auto notify full'				=>	'Subscrever automaticamente todos os t&#243;picos onde eu participar.',
'Show smilies'					=>	'Exibir emoticons em forma de &#237;cones gr&#225;ficos.',
'Show images'					=>	'Exibir imagens nas mensagens.',
'Show images sigs'				=>	'Exibir imagens nas assinaturas dos usu&#225;rios.',
'Show avatars'					=>	'Exibir avatares dos usu&#225;rios nas mensagens.',
'Show sigs'						=>	'Exibir assinaturas dos usu&#225;rios.',
'Style legend'					=>	'Seleccione o seu estilo preferido',
'Styles'						=>	'Estilos',
'Admin note'					=>	'Nota do administrador',
'Pagination legend'				=>	'Digite as suas op&#231;&#245;es de pagina&#231;&#227;o',
'Post display legend'			=>	'Defina as suas op&#231;&#245;es de visualiza&#231;&#227;o de mensagens',
'Post display info'				=>	'Se voc&#234; usa uma conex&#227;o lenta, desabilitar estas op&#231;&#245;es, principalmente a exibi&#231;&#227;o de imagens nas mensagens e assinaturas, far&#225; com que as p&#225;ginas carreguem mais rapidamente.',
'Instructions'					=>	'Quando actualizar o seu perfil, voc&#234; ser&#225; redireccionado para esta p&#225;gina.',

// Administration stuff
'Group membership legend'		=>	'Escolha o grupo de usu&#225;rio',
'Save'							=>	'Guardar',
'Set mods legend'				=>	'Definir acesso de moderador',
'Moderator in info'				=>	'Escolha os f&#243;runs que este usu&#225;rio poder&#225; moderar. Nota: Isto aplica-se apenas a moderadores. Administradores possuem sempre permiss&#245;es completas em todos os f&#243;runs.',
'Update forums'					=>	'Actualizar f&#243;runs',
'Delete ban legend'				=>	'Apagar (administradores apenas) ou banir usu&#225;rio',
'Delete user'					=>	'Apagar usu&#225;rio',
'Ban user'						=>	'Banir usu&#225;rio',
'Confirm delete legend'			=>	'Importante: leia antes de apagar o usu&#225;rio',
'Confirm delete user'			=>	'Confirmar exclus&#227;o do usu&#225;rio',
'Confirmation info'				=>	'Por favor confirma que deseja apagar o usu&#225;rio', // the username will be appended to this string
'Delete warning'				=>	'Aviso! Usu&#225;rios e/ou mensagens apagadas n&#227;o podem ser recuperados. Se voc&#234; escolher n&#227;o apagar as mensagens feitas por este usu&#225;rio, as mensagens s&#243; poder&#227;o ser apagadas manualmente mais tarde.',
'Delete posts'					=>	'Apagar quaisquer mensagens e t&#243;picos que este usu&#225;rio tenha criado.',
'Delete'						=>	'Apagar', // submit button (confirm user delete)
'User delete redirect'			=>	'Usu&#225;rio apagado. Redireccionando &#8230;',
'Group membership redirect'		=>	'Ades&#227;o ao grupo guardada. Redireccionando &#8230;',
'Update forums redirect'		=>	'Direitos de modera&#231;&#227;o do f&#243;rum actualizados. Redireccionando &#8230;',
'Ban redirect'					=>	'Redireccionando &#8230;',
'No delete admin message'		=>	'Administradores n&#227;o podem ser apagados. Para poder apagar este usu&#225;rio, voc&#234; primeiro dever&#225; mov&#234;-lo para outro grupo de usu&#225;rios.',

);
