<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'Pesquisa do usu&#225;rio',
'No search permission'				=>	'Voc&#234; n&#227;o possui permiss&#227;o para usar a fun&#231;&#227;o de pesquisa.',
'Search flood'						=>	'Voc&#234; deve esperar pelo menos %s segundos antes de fazer outra pesquisa. Por favor, espere um pouco e tente novamente.',
'Search'							=>	'Pesquisa',
'Search criteria legend'			=>	'Digite o seu termo de pesquisa',
'Search info'						=>	'Para pesquisar por uma palavra-chave, digite um ou mais termos de pesquisa. Separe os termos com espa&#231;os. Use AND (e), OR (ou) e NOT (n&#227;o) para refinar a sua pesquisa. Para pesquisar por autor digite o nome de usu&#225;rio autor das mensagens que deseja pesquisar. Use o caractere * para combina&#231;&#245;es parciais.',
'Keyword search'					=>	'Pesquisa por palavra-chave',
'Author search'						=>	'Pesquisa por autor',
'Search in legend'					=>	'Seleccione onde pesquisar',
'Search in info'					=>	'Escolha em qual f&#243;rum voc&#234; deseja fazer a pesquisa e se voc&#234; deseja pesquisar no t&#237;tulo dos t&#243;picos, texto da mensagem ou ambos.',
'Search multiple forums info'		=>  'Caso nenhum f&#243;rum seja seleccionado, todos os f&#243;runs ser&#227;o pesquisados.',
'Forum search'						=>	'F&#243;rum',
'All forums'						=>	'Todos os f&#243;runs',
'Search in'							=>	'Pesquisar em',
'Message and subject'				=>	'Texto da mensagem e t&#237;tulo do t&#243;pico',
'Message only'						=>	'Apenas no texto da mensagem',
'Topic only'						=>	'Apenas no t&#237;tulo do t&#243;pico',
'Sort by'							=>	'Ordenar por',
'Sort order'						=>	'Ordem',
'Search results legend'				=>	'Seleccione o modo de visualiza&#231;&#227;o dos resultados',
'Search results info'				=>	'Voc&#234; pode escolher como deseja ordenar e exibir seus resultados.',
'Sort by post time'					=>	'Hor&#225;rio da mensagem',
'Sort by author'					=>	'Autor',
'Sort by subject'					=>	'T&#237;tulo',
'Sort by forum'						=>	'F&#243;rum',
'Ascending'							=>	'Ascendente',
'Descending'						=>	'Descendente',
'Show as'							=>	'Exibir resultados como',
'Show as topics'					=>	'T&#243;picos',
'Show as posts'						=>	'Mensagens',

// Results
'Search'							=>  'Pesquisa',
'Search results'					=>	'Resultados da pesquisa',
'Quick search show_new'				=>	'Novo',
'Quick search show_recent'			=>	'Activo',
'Quick search show_unanswered'		=>	'Sem resposta',
'Quick search show_replies'			=>	'Publicado',
'Quick search show_user_topics'		=>	'T&#243;picos de %s',
'Quick search show_user_posts'		=>	'Mensagens de %s',
'Quick search show_subscriptions'	=>	'Subscrito por %s',
'By keywords show as topics'		=>	'T&#243;picos com mensagens contendo \'%s\'',
'By keywords show as posts'			=>	'Mensagens contendo \'%s\'',
'By user show as topics'			=>	'T&#243;picos com mensagens por %s',
'By user show as posts'				=>	'Mensagens por %s',
'By both show as topics'			=>	'T&#243;picos com mensagens contendo \'%s\', por %s',
'By both show as posts'				=>	'Mensagens contendo \'%s\', por %s',
'No terms'							=>	'Voc&#234; deve digitar ao menos uma palavra-chave e/ou um autor para pesquisar.',
'No hits'							=>	'Sua pesquisa n&#227;o retornou resultados.',
'No user posts'						=>	'N&#227;o h&#225; mensagens deste usu&#225;rio neste f&#243;rum.',
'No user topics'					=>	'N&#227;o existem t&#243;picos deste usu&#225;rio neste f&#243;rum.',
'No subscriptions'					=>	'Este usu&#225;rio n&#227;o est&#225; actualmente subscrito em nenhum t&#243;pico.',
'No new posts'						=>	'N&#227;o h&#225; t&#243;picos com novas mensagens desde sua &#250;ltima visita.',
'No recent posts'					=>	'N&#227;o houveram novas mensagens nas &#250;ltimas 24 horas.',
'No unanswered'						=>	'N&#227;o existem mensagens sem resposta neste f&#243;rum.',
'Go to post'						=>	'Ir &#224; mensagem',
'Go to topic'						=>	'Ir ao t&#243;pico'

);
