<?php

// Language definitions used in admin_maintenance.php
$lang_admin_maintenance = array(

'Maintenance head'				=>	'Foro-mantenimendua',
'Rebuild index subhead'			=>	'Berreraiki bilaketa-indizea',
'Rebuild index info'			=>	'Datu-baseko mezuak eskuz gehitu, editatu edo kendu badituzu edo bilaketak egitean arazoak badituzu, bilaketa-indizea berreraiki behar duzu. Performantzia hobetu nahi baduzu, foroa %sn jarri beharko zenuke berreraikitzean. <strong>Bilaketa-indizea berreraikitzeak denbora asko behar dezake eta zerbitzariaren karga handituko du berreraikitze-prozesuan zehar!</strong>',
'Posts per cycle label'			=>	'Mezuak zikloko',
'Posts per cycle help'			=>	'Orri-ikuspegi bakoitzeko prozesatuko den mezu-kopurua. Esaterako, 300 sartuz gero, hirurehun mezu prozesatuko dira eta orria freskatuko da. Berreraikitze-prozesuan script-ak denbora-muga gainditu dezan eragoztea da honen helburua.',
'Starting post label'			=>	'Hasierako mezuaren IDa',
'Starting post help'			=>	'Berreraikitzearen abio-puntua izango den mezuaren IDa. Balio lehenetsia datu-basean eskuragarri dagoen lehen IDa da. Normalean ez da beharrezkoa hau aldatzea.',
'Empty index label'				=>	'Hustu indizea',
'Empty index help'				=>	'Hautatu hau berreraikitzea baino lehen bilaketa-indizea hustu nahi baduzu (ikusi azpian).',
'Rebuild completed info'		=>	'Prozesua osatu ondoren, aplikazioak orri honetara berbideratuko zaitu. Oso gomendagarria da Javascript gaituta edukitzea nabigatzailean berreraikitzea egiten denean (berbideratze automatikoa gerta dadin ziklo bat osatu ondoren). Berreraikitze-prozesua abortatzen bada, prozesatu den azken mezuaren IDa hartu eta erabili ID horren hurrengoa "Hasierako mezuaren IDa" aukeran, berreraikitzeaz jarraitu nahi baduzu ("Hustu indizea" aukerak hautatu gabe egon behar du).',
'Rebuild index'					=>	'Berreraiki indizea',
'Rebuilding search index'		=>	'Bilaketa-indizea berreraikitzen',
'Rebuilding index info'			=>	'Indizea berreraikitzen. Hau une ona izan daiteke kafetxo bat hartzeko :-)',
'Processing post'				=>	'<strong>%s</strong> mezua prozesatzen …',
'Click here'					=>	'Egin klik hemen',
'Javascript redirect failed'	=>	'JavaScript berbideratzeak huts egin du. %s jarraitzeko …',
'Posts must be integer message'	=>	'Zikloko mezuak zenbaki positibo so bat izan behar du.',
'Days must be integer message'	=>	'Kimatzeko egunak zenbaki positibo oso bat izan behar du.',
'No old topics message'			=>	'Ez dago %s egun baino zaharragoa den gairik. Txikitu "Egun kopurua" balioa eta berriro saiatu.',
'Posts pruned redirect'			=>	'Mezuak kimatu dira. Berbideratzen …',
'Prune head'					=>	'Kimatu',
'Prune subhead'					=>	'Kimatu mezu zaharrak',
'Days old label'				=>	'Egun kopurua',
'Days old help'					=>	'Kimatuko diren gaien adina egunetan. Adib. 30 sartzen baduzu, 30 egun baino berriagoa den mezurik ez duten gai guztiak ezabatuko dira.',
'Prune sticky label'			=>	'Kimatsi gai itsaskorrak',
'Prune sticky help'				=>	'Gaitzean gai txaskorrak ere kimatuko dira.',
'Prune from label'				=>	'Kimatu foro honetatik',
'All forums'					=>	'Foro guztiak',
'Prune from help'				=>	'Kimatu nahi duzun foroa.',
'Prune info'					=>	'Erabili ezaugarri hau kontu handiz. <strong>Kimatutako mezuak ezin dira berreskuratu.</strong> Errendimendua hobetzeko, foroa %s egoeran jarri beharko zenuke kimatzean.',
'Confirm prune subhead'			=>	'Berretsi mezuak kimatzea',
'Confirm prune info'			=>	'Ziur %s egun baino zaharragoak diren gaiak kimatu nahi dituzula%s forotik (%s gai)?.',
'Confirm prune warn'			=>	'KONTUZ! Mezuak kimatzeak behin betiko ezabatuko ditu.',
);
