<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'Ezin izan da bertsio-berritzea egiaztatu, sistema honetan \'allow_url_fopen\' desgaituta baitago.',
'Upgrade check failed message'		=>	'Bertsio-berritzearen egiaztapenak huts egin du ezezagunak diren arrazoiengatik.',
'Running latest version message'	=>	'FluxBBren azken bertsioa erabiltzen ari zara.',
'New version available message'		=>	'FluxBBren bertsio bat argitaratu da. Azken bertsioa deskargatu dezakezu hemendik: %s.',
'Deleted install.php redirect'		=>	'Fitxategia ondo ezabatu da. Berbideratzen …',
'Delete install.php failed'			=>	'Ezin izan da install.php ezabatu. Mesedez eskuz ezabatu.',
'Not available'						=>	'Ez dago eskuragarri',
'Forum admin head'					=>	'Foro-administrazioa',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'Ongi etorri FluxBBren administraziorako kontrol-panelera. Hemendik ohar-taularen alderdi garrantzitsuenak kontrola ditzakezu. Administratzailea edo moderatzailea bazara, hurrengoak egin ditzakezu:',
'Welcome 1'							=>	'Kategoriak eta foroak antolatu.',
'Welcome 2'							=>	'Foro guztietako aukerak eta hobespenak ezarri.',
'Welcome 3'							=>	'Erabiltzaile eta gonbidatuen baimenak kontrolatu.',
'Welcome 4'							=>	'Erabiltzaileen IP estatistikak ikusi.',
'Welcome 5'							=>	'Erabiltzaileei debekuak jarri.',
'Welcome 6'							=>	'Hitzak zentsuratu.',
'Welcome 7'							=>	'Erabiltzaile-mailak konfiguratu.',
'Welcome 8'							=>	'Mezu zaharrak kimatu.',
'Welcome 9'							=>	'Mezu-txostenak kudeatu.',
'Alerts head'						=>	'Alertak',
'Install file exists'				=>	'install.php fitxategia oraindik dago, baina ezabatu beharko zenuke. %s.',
'Delete install file'				=>	'Ezabatu',
'About head'						=>	'FluxBBri buruz',
'FluxBB version label'				=>	'FluxBB bersioa',
'Check for upgrade'					=>	'Bilatu bertsio berria',
'FluxBB version data'				=>	'v%s - %s',
'Server statistics label'			=>	'Zerbitzariaren estatistikak',
'View server statistics'			=>	'Ikusi zerbitzariaren estatistikak',
'Support label'						=>	'Laguntza',
'Forum label'						=>	'Foroa',
'IRC label'							=>	'IRC kanala',

// Language definitions used in admin_statistics.php
'PHPinfo disabled message'			=>	'phpinfo() PHP funtzia ezgaituta dago zerbitzari honetan.',
'Server statistics head'			=>	'Zerbitzariaren estatistikak',
'Server load label'					=>	'Zerbitzari-karga',
'Server load data'					=>	'%s - %s erabiltzaile linean',
'Environment label'					=>	'Ingurunea',
'Environment data OS'				=>	'Sistema eragilea: %s',
'Show info'							=>	'Erakutsi informazioa',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Azeleratzailea: %s',
'Turck MMCache'						=>	'Turk MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Datu-basea',
'Database data rows'				=>	'Errenkadak: %s',
'Database data size'				=>	'Tamaina: %s',

);
