<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'			=>	'Ez dago erregistratuta izen hori duen erabiltzailerik. Erabiltzaile-izen jakin bati lotuta ez dagoen debeku bat gehitu nahi baduzu, utzi erabiltzaile-izena hutsik.',
'No user ID message'		=>	'Ez dago erregistratuta ID hori duen erabiltzailerik.',
'User is admin message'		=>	'%s erabiltzailea administratzailea da eta ezin zaio debekurik jarri. Administratzaile bati debekua jarri nahi badiozu, erabiltzaile mailara degradatu behar duzu.',
'User is mod message'		=>	'%s erabiltzailea moderatzailea da eta ezin zaio debekurik jarri. Moderatzaile bati debekua jarri nahi badiozu, erabiltzaile mailara degradatu behar duzu.',
'Must enter message'		=>	'Erabiltzaile-izen bat, IP helbide bat edo posta elektronikoko helbide bat sartu behar duzu (gutxienez).',
'Cannot ban guest message'	=>	'Gonbidatuei ezin zaie debekurik jarri.',
'Invalid IP message'		=>	'IP/IP-tarte baliogabea sartu duzu.',
'Invalid e-mail message'	=>	'Sartu duzun posta elektronikoko helbidea (adib. erabiltzailea@domeinua.com) edo posta elektronikoaren domeinu partziala (adib. domeinua.com) baliogabea da.',
'Invalid date message'		=>	'Iraungipen-data baliogabea sartu duzu.',
'Invalid date reasons'		=>	'Formatuak UUUU-HH-EE izan behar du eta datak gutxienez egun bat etorkizunean egon behar du.',
'Ban added redirect'		=>	'Debekua gehitu da. Berbideratzen …' ,
'Ban edited redirect'		=>	'Debekua editatu da. Berbideratzen …',
'Ban removed redirect'		=>	'Debekua kendu da. Berbideratzen …',

'New ban head'				=>	'Debeku berria',
'Add ban subhead'			=>	'Gehitu debekua',
'Username label'			=>	'Erabiltzaile-izena',
'Username help'				=>	'Debekatutako erabiltzaile-izena (maiuskulak/minuskulak bereizi gabe).',
'Username advanced help'	=>	'Debekatuko den erabiltzaile-izena (maiuskulak/minuskulak bereizi gabe). Hurrengo orrian IP bat eta posta elektronikoko helbide bat sartu ahalko dituzu. IP/IP-tarte edo helbide jakin bati jarri nahi badiozu debekua, utzi hutsik.',

'Ban search head'			=>	'Debeku-bilaketa',
'Ban search subhead'		=>	'Sartu bilaketa-irizpidea',
'Ban search info'			=>	'Bilatu debekuak datu-basean. Hitz bat edo gehiago sar ditzakezu bilaketak egiteko. Izartxoa (*) onartzen da komodin modura.',
'Date help'					=>	'(uuuu-hh-ee)',
'Message label'				=>	'Mezua',
'Expire after label'		=>	'Iraungi data honen ondoren',
'Expire before label'		=>	'Iraungi data hau baino lehen',
'Order by label'			=>	'Ordenatze-irizpidea',
'Order by username'			=>	'Erabiltzaile-izena',
'Order by ip'				=>	'IPa',
'Order by e-mail'			=>	'Posta elektronikoa',
'Order by expire'			=>	'Iraungipen-data',
'Ascending'					=>	'Gorantz',
'Descending'				=>	'Beherantz',
'Submit search'				=>	'Bidali bilaketa',

'E-mail label'				=>	'Posta elektronikoa',
'E-mail help'				=>	'Debekua jarri nahi diozun posta elektronikoa edo domeinua (esaterako, norbait@norbait.com edo norbait.com). Ikusi "Onartu debekatutako posta elektronikoko helbideak" Baimenak atalean informazio gehiago jasotzeko.',
'IP label'					=>	'IP helbidea/IP-tarteak',
'IP help'					=>	'Debekua jarri nahi diozun IP helbidea edo IP-tarteak (adib. 150.11.110.1 edo 150.11.110). Banatu helbideak zuriuneekin. IP bat sartuta badago, erabiltzaile horrek datu-basean duen azken IP ezaguna da.',
'IP help link'				=>	'Egin klik %s erabiltzaile horren IP estatistikak ikusteko.',
'Ban advanced head'			=>	'Debekuen ezarpen aurreratuak',
'Ban advanced subhead'		=>	'Jarri IPa eta posta elektronikoko helbidea debekuaren eranskin gisa',
'Ban message label'			=>	'Debeku-mezua',
'Ban message help'			=>	'Debekua duen erabiltzaileari erakutsiko zaion mezua foroa bisitatzen duenean.',
'Message expiry subhead'	=>	'Debeku-mezua eta iraungipen-data',
'Ban IP range info'			=>	'Arretaz jokatu beharko zenuke IP-tarte bati debekua jartzean, erabiltzaile anitzek egin baitezakete bat IP partzial berarekin.',
'Expire date label'			=>	'Iraungipen-data',
'Expire date help'			=>	'Debekua automatikoki kenduko den data (formatua: uuuu-hh-ee). Utzi hutsik debekua eskuz kentzeko.',

'Results head'				=>	'Bilaketaren emaitzak',
'Results username head'		=>	'Erabiltzaile-izena',
'Results e-mail head'		=>	'Posta elektronikoa',
'Results IP address head'	=>	'IP/IP-tarteak',
'Results expire head'		=>	'Iraungitzen da',
'Results message head'		=>	'Mezua',
'Results banned by head'	=>	'Debekuaren jatorria',
'Results actions head'		=>	'Ekintzak',
'No match'					=>	'Bat datorrenik ez',
'Unknown'					=>	'Ezezaguna',

);
