<?php

// Language definitions used in admin_options.php
$lang_admin_options = array(

'Bad HTTP Referer message'			=>	'HTTP_REFERER okerra. Foro hauek toki batetik beste batera mugitu badituzu edo domeinuz aldatu baduzu, Oinarrizko URLa eskuz aldatu behar duzu datu-basean (bilatu o_base_url konfigurazio-taulan) eta gero cache-a garbitu behar duzu /cache direktorioko .php fitxategi guztiak ezabatuta.',
'Must enter title message'			=>	'Ohar-taularako izenburu bat sartu behar duzu.',
'Invalid e-mail message'			=>	'Administratzaile izateko sartu duzun posta elektronikoko helbidea baliogabea da.',
'Invalid webmaster e-mail message'	=>	'Webmasterra izateko sartu duzun posta elektronikoko helbidea baliogabea da.',
'SMTP passwords did not match'		=>	'SMTP pasahitza birritan berdin idatzi behar duzu berau aldatzeko.',
'Enter announcement here'			=>	'Sartu zure iragarkia hemen.',
'Enter rules here'					=>	'Sartu zure arauak hemen.',
'Default maintenance message'		=>	'Foroak behin-behinean indargabetu dira mantenimendu-lanetarako. Saiatu berriro pixka bat geroago.',
'Timeout error message'				=>	'"Denbora-muga linean" ezarpenaren balioak "Bisitaren denbora-muga" ezarpenarenak baino txikiagoa izan behar du.',
'Options updated redirect'			=>	'Aukerak eguneratu dira. Berbideratzen …',
'Options head'						=>	'Aukerak',

// Essentials section
'Essentials subhead'				=>	'Funtsezkoak',
'Board title label'					=>	'Ohar-taularen izenburua',
'Board title help'					=>	'Ohar-taula honen izenburua (orri bakoitzaren goialdean erakusten dena). Eremu honek <strong>ez</strong> du HTMLrik eduki behar.',
'Board desc label'					=>	'Ohar-taularen deskribapena',
'Board desc help'					=>	'Ohar-taula honen deskribapen laburra (orri bakoitzaren goialdean erakusten dena). Eremu honek HTMLa eduki dezake.',
'Base URL label'					=>	'Oinarrizko URLa',
'Base URL help'						=>	'Ohar-taularen URL osoa, amaierako barrarik gabe (adib. http://www.niredomeinua.com/foroak). Honek zuzena izan <strong>behar</strong> du administratzaile- eta moderatzaile-ezaugarri guztiek ondo funtziona dezaten. "Referer okerra" motako akatsak jasotzen badituzu, seguru asko ez da zuzena.',
'Base URL problem'          =>  'Zure instalzioak ez du internazionalizatutako domeinuak automatikoki moldatzeko. Zure URL helbideak karaktere bereziak dituenez, <strong>nahitaezkoa</strong> duzu moldatzaile bat erabiltzea "Igorle okerra" erroreak sahiesteko.',
'Timezone label'					=>	'Ordu-zona lehenetsia',
'Timezone help'						=>	'Ohar-taulan erregistratu nahi duten gonbidatu eta erabiltzaileentzako ordu-zona lehenetsia.',
'DST label'							=>	'Doitu udako ordutegirako',
'DST help'							=>	'Egiaztatu udako ordutegia indarrean dagoen (denbora ordubetez aurreratzen du).',
'Language label'					=>	'Hizkuntza lehenetsia',
'Language help'						=>	'Gonbidatu eta erabiltzaileentzako hizkuntza lehenetsia, beren profilean balio hau aldatu ez badute. Hizkuntza-pakete bat kentzen baduzu, hau eguneratu egin behar da.',
'Default style label'				=>	'Estilo lehenetsia',
'Default style help'				=>	'Gonbidatu eta erabiltzaileentzako estilo lehenetsia, beren profilean balio hau aldatu ez badute.',

// Essentials section timezone options
'UTC-12:00'							=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'							=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'							=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'							=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'							=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'							=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'							=>	'(UTC-08:00) Pacific',
'UTC-07:00'							=>	'(UTC-07:00) Mountain',
'UTC-06:00'							=>	'(UTC-06:00) Central',
'UTC-05:00'							=>	'(UTC-05:00) Eastern',
'UTC-04:00'							=>	'(UTC-04:00) Atlantic',
'UTC-03:30'							=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'							=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'							=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'							=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'								=>	'(UTC) Western European, Greenwich',
'UTC+01:00'							=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'							=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'							=>	'(UTC+03:00) Eastern African',
'UTC+03:30'							=>	'(UTC+03:30) Iran',
'UTC+04:00'							=>	'(UTC+04:00) Moscow, Gulf, Samara',
'UTC+04:30'							=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'							=>	'(UTC+05:00) Pakistan',
'UTC+05:30'							=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'							=>	'(UTC+05:45) Nepal',
'UTC+06:00'							=>	'(UTC+06:00) Bangladesh, Bhutan, Yekaterinburg',
'UTC+06:30'							=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'							=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'							=>	'(UTC+08:00) Greater China, Australian Western, Krasnoyarsk',
'UTC+08:45'							=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'							=>	'(UTC+09:00) Japan, Korea, Chita, Irkutsk',
'UTC+09:30'							=>	'(UTC+09:30) Australian Central',
'UTC+10:00'							=>	'(UTC+10:00) Australian Eastern',
'UTC+10:30'							=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'							=>	'(UTC+11:00) Solomon Island, Vladivostok',
'UTC+11:30'							=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'							=>	'(UTC+12:00) New Zealand, Fiji, Magadan',
'UTC+12:45'							=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'							=>	'(UTC+13:00) Tonga, Phoenix Islands, Kamchatka',
'UTC+14:00'							=>	'(UTC+14:00) Line Islands',


// Timeout Section
'Timeouts subhead'					=>	'Denbora eta denbora-mugak',
'Time format label'					=>	'Denbora-formatua',
'PHP manual'						=>	'PHP eskuliburua',
'Time format help'					=>	'[Uneko formatua: %s]. Ikusi %s formatu-aukera gehiagorako.',
'Date format label'					=>	'Data-formatua',
'Date format help'					=>	'[Uneko formatua: %s]. Ikusi %s formatu-aukera gehiagorako.',
'Visit timeout label'				=>	'Bisiten denbora-muga',
'Visit timeout help'				=>	'Erabiltzaile batek inaktibo egon behar duen segundo-kopurua bere bisita-datuak eguneratuak izan baino lehen (batez ere mezu berrien adierazleari eragiten dio).',
'Online timeout label'				=>	'Denbora-muga linean',
'Online timeout help'				=>	'Erabiltzaile batek inaktibo egon behar duen segundo-kopurua linean dauden erabiltzaile-zerrendatik ezabatua izan baino lehen.',
'Redirect time label'				=>	'Berbideratze-denbora',
'Redirect time help'				=>	'Berbideratzean itxaron behar den segundo-kopurua. Zenbaki hau 0 bada, ez da erakutsiko berbideratze-orririk (ez da gomendagarria).',

// Display Section
'Display subhead'					=>	'Bistaratzea',
'Version number label'				=>	'Bertsio-zenbakia',
'Version number help'				=>	'Erakutsi FluxBBren bertsio-zenbakia orri-oinean.',
'Info in posts label'				=>	'Erabiltzaile-informazioa mezuetan',
'Info in posts help'				=>	'Erakutsi mezu-bidaltzaileari buruzko informazioa erabiltzaile-izenaren azpian gaien bistaratzean. Erakutsitako informazioa kokapena, erregistratze-data, bidalitako mezuen kopurua eta kontaktu-estekak (posta elektronikoa eta URLa) dira.',
'Post count label'					=>	'Erabiltzailearen mezu-kopurua',
'Post count help'					=>	'Erabiltzaile batek bidalitako mezu-kopurua erakusten du (gaien bistaratzean, profilean eta erabiltzaile-zerrendan erakusten da).',
'Smilies label'						=>	'Aurpegierak mezuetan',
'Smilies help'						=>	'Aurpegierak ikono grafiko txiki bihurtu.',
'Smilies sigs label'				=>	'Aurpegierak sinaduretan',
'Smilies sigs help'					=>	'Aurpegierak ikono grafiko txiki bihurtu erabiltzaile-sinaduretan.',
'Clickable links label'				=>	'Estekak klikagarri bihurtu',
'Clickable links help'				=>	'Gaituta dagoenean, FluxBBk automatikoki detektatuko ditu URLak mezuetan eta hiperesteka klikagarri bihurtuko ditu.',
'Topic review label'				=>	'Gaien berrikuspena',
'Topic review help'					=>	'Mezua bidaltzean bistaratuko den mezu-kopuru maximoa (berrienak lehenak). Ezarri 0 balioa aukera hau desgaitzeko.',
'Topics per page label'				=>	'Gaiak orriko',
'Topics per page help'				=>	'Foro batean erakutsiko den gai-kopuru lehenetsia orriko. Erabiltzaileek pertsonalizatu egin dezakete ezarpen hau.',
'Posts per page label'				=>	'Mezuak orriko',
'Posts per page help'				=>	'Gai batean erakutsiko den mezu-kopuru lehenetsia orriko. Erabiltzaileek pertsonalizatu egin dezakete ezarpen hau.',
'Indent label'						=>	'Koska-tamaina',
'Indent help'						=>	'Bere balioa 8 bada, fitxa erregular bat erabiliko da [code][/code] etiketa barruan dagoen testua erakusteko. Bestela, zuriuneak erabiliko dira testua koskatzeko.',
'Quote depth label'					=>	'[quote] etiketaren sakonera maximoa',
'Quote depth help'					=>	'[quote] etiketak bata bestearen barruan sar daitezkeen kopuru maximoa, balio hau baino sakonago dagoen edozein etiketa baztertu egingo da.',

// Features section
'Features subhead'					=>	'Ezaugarriak',
'Quick post label'					=>	'Mezu azkarra',
'Quick post help'					=>	'Gaituta dagoenean, FluxBBk mezu azkarrerako formularioa gehituko du gaien azpialdean. Honela, erabiltzaileek zuzenean gaien bistaratzetik bidal dezakete mezua.',
'Users online label'				=>	'Erabiltzaileak linean',
'Users online help'					=>	'Ohar-taulatik nabigatzen ari den gonbidatu- eta erregistratutako erabiltzaile-kopurua erakusten du indize-orrian.',
'Censor words label'				=>	'Zentsuratu hitzak',
'Censor words help'					=>	'Gaitu hau ohar-taulako hitz jakinak zentsuratzeko. Ikusi %s informazio gehiagorako.',
'Signatures label'					=>	'Sinadurak',
'Signatures help'					=>	'Onartu erabiltzaileek bere mezuei sinadura gehi diezaieten.',
'User has posted label'				=>	'Erabiltzaileak lehenago ere mezu bat bidali du',
'User has posted help'				=>	'Ezaugarri honek puntu bat erakusten du viewforum.php fitxategiko gaien aurrean saioa hasita duen erabiltzaileak lehenago ere mezu bat bidali badu gai horretan. Desgaitu aukera hau zerbitzaria karga handia jasaten ari bada.',
'Topic views label'					=>	'Gaien ikustaldiak',
'Topic views help'					=>	'Gai bat zenbat aldiz ikusi den gordetzen du. Desgaitu aukera hau zerbitzaria karga handia jasaten ari bada mugimendu handiko foro batean.',
'Quick jump label'					=>	'Jauzi azkarra',
'Quick jump help'					=>	'Gaitu jauzi azkarrrerako goitibeherako zerrenda ("Joan hona" aukera).',
'GZip label'						=>	'GZip irteera',
'GZip help'							=>	'Gaituta badago, FluxBBk gzip bihurtuko du nabigatzailera bidaltzen den irteera. Honek banada-zabaleraren erabilera murrizten du, baina PUZ pixka bat gehiago erabiltzen du. Ezaugarri hau erabiltzeko zlib (--with-zlib) aukera erabiliz konfiguratu behar da. Oharra: Apachek PHP script-ak trinkotzeko dituen mod_gzip edo mod_deflate moduluak konfiguratuta badituzu, ezaugarri hau desgaitu beharko zenuke.',
'Search all label'					=>	'Bilatu foro guztietan',
'Search all help'					=>	'Desgaituta dagoenean, bilaketak foro bakarrean egin ahal dira. Desgaitu zerbitzariaren karga gehiegizko bilaketen erruz handiegia bada.',
'Menu items label'					=>	'Menu-aukera gehigarriak',
'Menu items help'					=>	'Testu-kutxa honetan HTML hiperestekak sartzean, edozein elementu-kopuru gehi dakioke orri guztietako goialdean ageri den nabigazio-menuan. Esteka berriak gehitzeko formatua X = &lt;a href="URL"&gt;LINK&lt;/a&gt; da, non X esteka sartu beharko litzakeen kokapena den (adib. 0 hasieran sartzeko eta 2 "Erabiltzaile-zerrenda" ondoren sartzeko). Banatu sarrerak lerro-jauziak erabiliz.',

// Feeds section
'Feed subhead'						=>	'Sindikazioa',
'Default feed label'				=>	'Jario-mota lehenetsia',
'Default feed help'					=>	'Hautatu erakutsiko den jario-mota. Oharra: Bat ere ez hauatzeak ez ditu jarioak desgaitzen, modu lehenetsian ezkutatu soilik egiten ditu.',
'None'								=>	'Bat ere ez',
'RSS'								=>	'RSS',
'Atom'								=>	'Atom',
'Feed TTL label'					=>	'Jarioak katxeatzeko denbora',
'Feed TTL help'						=>	'Jarioak katxeatu daitezke errekurtsoen erabilera gutxiagotzeko.',
'No cache'							=>	'Ez katxeatu',
'Minutes'							=>	'%d minutu',


// Reports section
'Reports subhead'					=>	'Txostenak',
'Reporting method label'			=>	'Txostenaren berri emateko metodoa',
'Internal'							=>	'Barnekoa',
'By e-mail'							=>	'Posta elektronikoa',
'Both'								=>	'Biak',
'Reporting method help'				=>	'Gaien/mezuen txostenak kudeatzeko metodoa hautatzen du. Hautatu gaien/mezuen txostenak barneko jakinarazpen-sistemaren bidez jakinarazten den, posta-zerrendako helbideen bidez egiten den (ikusi azpian) ala bien bidez egiten den.',
'Mailing list label'				=>	'Posta-zerrenda',
'Mailing list help'					=>	'Komaz banandutako harpidedunen zerrenda. Zerrenda honetako helbideak txostenen jasotzaileak dira.',

// Avatars section
'Avatars subhead'					=>	'Avatarrak',
'Use avatars label'					=>	'Erabili avatarrak',
'Use avatars help'					=>	'Gaituta dagoenean, erabiltzaileek avatar bat igo ahal izango dute beren izenburuaren/mailaren azpian erakusteko.',
'Upload directory label'			=>	'Kargatze-direktorioa',
'Upload directory help'				=>	'Avatarrentzako kargatze-direktorioa (FluxBBren erro-direktorioarekiko erlatiboa). PHPk idazteko baimena eduki behar du direktorio honetan.',
'Max width label'					=>	'Zabalera maximoa',
'Max width help'					=>	'Avatarrentzat onartutako zabalera maximoa pixeletan (60 gomendatzen da).',
'Max height label'					=>	'Altuera maximoa',
'Max height help'					=>	'Avatarrentzat onartutako altuera maximoa pixeletan (60 gomendatzen da).',
'Max size label'					=>	'Tamaina maximoa',
'Max size help'						=>	'Avatarrentzat onartutako tamaina maximoa byte-tan (10240 gomendatzen da).',

// E-mail section
'E-mail subhead'					=>	'Posta',
'Admin e-mail label'				=>	'Administratzaile-posta',
'Admin e-mail help'					=>	'Ohar-taularen administratzailearen posta elektronikoko helbidea.',
'Webmaster e-mail label'			=>	'Web-arduradunaren posta',
'Webmaster e-mail help'				=>	'Ohar-taulatik bidalitako posta guztiak helbide hau eramango dute bidaltzaile-eremuan.',
'Forum subscriptions label'				=>	'Foroetara harpidetzak',
'Forum subscriptions help'				=>	'Gaitu erabiltzaileek foroetako harpidedun bihur daitezen (posta jaso dezaten norbaitek erantzuten duenean).',
'Topic subscriptions label'				=>	'Gaietara harpidetzak',
'Topic subscriptions help'				=>	'Gaitu erabiltzaileek gaietako harpidedun bihur daitezen (posta jaso dezaten norbaitek erantzuten duenean).',
'SMTP address label'				=>	'SMTP zerbitzariaren helbidea',
'SMTP address help'					=>	'Posta elektronikoak bidaltzeko erabiliko den kanpoko SMTP zerbitzari baten helbidea. Ataka-zenbaki pertsonalizatua ezar dezakezu zerbitzariak ez badu funtzionatzen 25 ataka lehenetsian (adibidez, mail.nireostalaria.com:3580). Utzi hutsik posta-aplikazio lokala erabili nahi izanez gero.',
'SMTP username label'				=>	'SMTP erabiltzaile-izena',
'SMTP username help'				=>	'SMTP zerbitzarirako erabiltzaile-izena. Erabiltzaile-izena sartu soilik SMTP zerbitzariak eskatzen badu (zerbitzari askok <strong>ez dute</strong> autentifikaziorik behar).',
'SMTP password label'				=>	'SMTP pasahitza',
'SMTP change password help'			=>	'Markatu hau orain gordetako pasahitza aldatu edo ezabatu nahi baduzu.',
'SMTP password help'				=>	'SMTP zerbitzarirako pasahitza. Pasahitza sartu soilik SMTP zerbitzariak eskatzen badu (zerbitzari askok <strong>ez dute</strong> autentifikaziorik behar).',
'SMTP SSL label'					=>	'Enkriptatu SMTP SSL erabiliz',
'SMTP SSL help'						=>	'SMTP zerbitzarirako konexioa enkriptatzen du SSL erabiliz. Hau erabiltzeko, SMTP zerbitzariak eskatu behar du eta PHPren zure bertsioak SSL onartu behar du.',

// Registration Section
'Registration subhead'				=>	'Erregistroa',
'Allow new label'					=>	'Onartu erregistro berriak',
'Allow new help'					=>	'Ohar-taula honek erregistro berriak onartzen dituen kontrolatzen du. Desgaitu egoera berezietan soilik.',
'Verify label'						=>	'Egiaztatu erregistroak',
'Verify help'						=>	'Gaituta dagoenean, erabiltzaileei ausazko pasahitza bidaltzen zaie erregistratzen direnean. Ondoren, saioa hasi dezakete eta pasahitza alda dezakete bere profilean, hala nahi izanez gero. Ezaugarri honetan erabiltzaileek posta elektronikoko helbide berriak egiaztatu behar dituzte hura aldatzea erabakitzen badute. Erregistro-abusuak saihesteko modu eraginkorra da eta erabiltzaile guztiek haien profilean posta elektronikoko helbide "zuzena" dutela egiaztatzeko balio du.',
'Report new label'					=>	'Jakinarazi erregistro berriak',
'Report new help'					=>	'Gaituta badago, FluxBBk posta-zerrendako erabiltzaileei (ikus goian) jakinaraziko diete erabiltzaile berria erregistratu dela foroan.',
'Use rules label'					=>	'Foroaren erabiltzaile-arauak',
'Use rules help'					=>	'Gaituta dagoenean, erabiltzaileek arau batzuk onartu behar dituzte erregistratzen direnean (sartu testua azpian). Arauak beti egongo dira atzigarri orri bakoitzeko goialdean ageri den nabigazio-taularen esteka baten bidez.',
'Rules label'						=>	'Sartu arauak',
'Rules help'						=>	'Hemen arauak sar ditzakezu, bai eta erabiltzaileek erregistratzean ikusi eta onartu behar duen beste edozein informazio ere. Goiko arauak gaitzen badituzu, zerbait sartu beharko duzu, bestela desgaitu egingo da. Testu hau ez da mezu normalak bezala prozesatuko eta beraz HTMLa eduki dezake.',
'E-mail default label'				=>	'Posta elektronikoko ezarpen lehenetsiak',
'E-mail default help'				=>	'Hautatu pribatutasun-ezarpen lehenetsiak erabiltzaile berrien erregistrorako.',
'Display e-mail label'				=>	'Erakutsi posta-helbidea gainerako erabiltzaileei.',
'Hide allow form label'				=>	'Ezkutatu posta-helbidea baina onartu formulario bidezko posta.',
'Hide both label'					=>	'Ezkutatu posta-helbidea eta desgaitu formulario bidezko posta.',

// Announcement Section
'Announcement subhead'				=>	'Abisuak',
'Display announcement label'		=>	'Erakutsi abisua',
'Display announcement help'			=>	'Gaitu hau azpiko mezua ohar-taulan erakusteko.',
'Announcement message label'		=>	'Abisu-mezua',
'Announcement message help'			=>	'Testu hau ez da prozesatuko mezu normalak bezala eta beraz HTMLa eduki dezake.',

// Maintenance Section
'Maintenance subhead'				=>	'Mantenimendua',
'Maintenance mode label'			=>	'Mantenimendu-modua',
'Maintenance mode help'				=>	'Gaituta dagoenean, administratzaileek soilik sartu ahal izango dute ohar-taulara. Ohar-taularen mantenimendu-lanak egiteko erabil daiteke aukera hau. <strong>KONTUZ! Ez amaitu saioa ohar-taula mantenimendu-moduan dagoenean.</strong> Ezingo duzu saioa berriro hasi.',
'Maintenance message label'			=>	'Mantenimendu-modua',
'Maintenance message help'			=>	'Erabiltzaileei erakutsiko zaien mezua ohar-taula mantenimendu-moduan dagoenean. Hutsik uzten bada, mezu lehenetsi bat erabiliko da. Testu hau ez da prozesatuko mezu normalak bezala eta beraz HTMLa eduki dezake.',

);
