<?php

// Language definitions used in install.php, localized by adaur

$lang_install = array(

'Choose install language'		=>	'Aukeratu instalazioaren hizkuntza',
'Choose install language info'	=>	'Instalazio script honek erabiliko duen hizkuntza, foroen lehenetsitako hizkuntza behean aukeratu dezakezu.',
'Install language'				=>	'Instalazioaren hizkuntza',
'Change language'				=>	'Aldatu hizkuntza',
'Already installed'				=>	'Badirudi FluxBB aurretik instalatuta dagoela jada. Zoaz <a href="index.php">hona</a>.',
'You are running error'			=>	'%1$s erabiltzen ari zara %2$s bertsioan. FluxBB %3$s behar bezala ibiltzeko gutxienez %1$s %4$s behar da. Ezinbestekoa duzu %1$s eguneratzea aurrera egin ahal izateko.',
'My FluxBB Forum'				=>	'Nire FluxBB Foroa',
'Description'					=>	'Zoritxarrez inork ezin dizu azaldu zer den FluxBB - zuk zeuk ikusi beharko duzu.',
'Username 1'					=>	'Erabiltzaile izenak gutxienez bi karaktere izan behar ditu.',
'Username 2'					=>	'Erabiltzaile izenak ezin ditu izan 25 karaktere baino gehiago.',
'Username 3'					=>	'guest erabiltzaile izena erreserbatuta dago.',
'Username 4'					=>	'Erabiltzaile izenek ezin dute IP helbide itxura izan.',
'Username 5'					=>	'Erabiltzaile izenek edozien karaktere izan dezakete \', " eta [ edo ] aldi berean ezik.',
'Username 6'					=>	'Erabiltzaile izenek ezin dituzte foroan erabiltzen diren formatu etiketak izan (BBCode).',
'Short password'				=>	'Pasahitzak gutxienez 6 karaktere izan behar ditu.',
'Passwords not match'			=>	'Pasahitzak ez datoz bat.',
'Wrong email'					=>	'Sartu duzun administratzailearen helbide elektronikoa baliogabea da.',
'No board title'				=>	'Foroen izena sartu behar duzu.',
'Error default language'		=>	'Aukeratu duzun lehenetsitako hizkuntza antza ez dago erabilgarri.',
'Error default style'			=>	'Aukeratu duzun lehenetsitako estiloa antza ez dago erabilgarri.',
'No DB extensions'				=>	'PHP ingurune honek ez du FluxBBek onartzen dituen datubaseentzat euskarririk. MySQL, PostgreSQL SQLite euskarria izan behar du PHPk FluxBB instalatzeko.',
'Administrator username'		=>	'Administratzailearen izena',
'Administrator email'			=>	'Administratzailearen helbide elektronikoa',
'Board title'					=>	'Foroen izenburua',
'Base URL'						=>	'Zure FluxBB foroaren URL helbidea (bukaerako barrarik gabe). Hau zuzena izan behar du.',
'Required field'				=>	'ezinbesteko eremua da formulario honetan.',
'FluxBB Installation'			=>	'FluxBB Instalazioa',
'Welcome'						=>	'FluxBB instalatzera zoaz. FluxBB instalatzeko, geheko formulario hau bete behar duzu. Instalazioarekin arazoren bat baduzu irakurri dokumentazioa mesedez.',
'Install'						=>	'Instalatu FluxBB %s',
'Errors'						=>	'Errore hauek zuzendu behaar dira:',
'Database setup'				=>	'Datu-basearen ezarpena',
'Info 1'						=>	'Zure datu-basearekin konexio bat sortzeko behar dugun informazio guztia.',
'Select database'				=>	'Aukeratu zure datu-base mota',
'Info 2'						=>	'Aukeratu datu-base bat. SQLite, MySQL eta PostgreSQL onartzen ditugu.',
'Database type'					=>	'Datu-base mota',
'Required'						=>	'(Ezinbestekoa)',
'Database hostname'				=>	'Idatzi zure datu-base zerbitzariaren izena',
'Info 3'						=>	'Informazio hau zure web ostalaritik jaso dezakezu, <code>localhost</code> ez badabil.',
'Database server hostname'		=>	'Datubase zerbitzariaren izena',
'Database enter name'			=>	'Idatzi zure datu-basearen izena',
'Info 4'						=>	'FluxBB instalatzeko erabiliko duzun datu-basea.',
'Database name'					=>	'Datu-basearen izena',
'Database enter informations'	=>	'Idatzi zure datu-baseko erabiltzaile izen eta pasahitza',
'Database username'				=>	'Datu-base erabiltzaile izena',
'Info 5'						=>	'Zure MySQL erabiltzaile izen eta pasahitza (ezikusi SQLite).',
'Database password'				=>	'Datu-baseko pasahitza',
'Database enter prefix'			=>	'Idatzi datu-baseko taulen aurrizkia',
'Info 6'						=>	'Datu-base berean hainbat FluXBB instalazio egin nahi badituzu aldatu hau.',
'Table prefix'					=>	'Taula aurrrizkia',
'Administration setup'			=>	'Administrazioaren ezarpena',
'Info 7'						=>	'Sortu foroetak lehen erabiltzaile kontua.',
'Info 8'						=>	'Zure erabiltzaile izenak 2 eta 25 bitrateko luzeera izan behar du. Zure pasahitzak gutxienez 6 karaktere izan behar ditu. Gogoratu pasahitzek letra larriak eta xeheak bereizten dituztela.',
'Password'						=>	'Pasahitza',
'Confirm password'				=>	'Berretsi pasahitza',
'Board setup'					=>	'Foroen ezarpena',
'Info 11'						=>	'Zure foroen ezarpenak. Gero aldatu ditzazkezu.',
'General information'			=>	'Idatzi dure foroen izenburu eta deskripzioa.',
'Board description'				=>	'Foroen deskripzioa (HTML onartzen du)',
'Appearance'					=>	'Itxura',
'Info 15'						=>	'Egin foroak zureak. Aukeratu hizkuntza eta estiloa zure foroentzat.',
'Default language'				=>	'Lehenetsitako hizkuntza',
'Default style'					=>	'Lehenetsitako estiloa',
'Start install'					=>	'Hasi instalazioa',
'DB type not valid'				=>	'\'%s\' ez da baliozko datu-base mota bat',
'Table prefix error'			=>	'\'%s\' taula aurrizkiak onartu gabeko karaktereak ditu edo luzeegia da. Aurrizkiak a eta z bitarteko letrak, zenbakiak eta azpimarra karakterea izan ditzake. Baina ezin da zenbaki batekin hasi. Gehieneko luzeera 40 karaktere dira. Aukeratu beste aurrizki bat',
'Prefix reserved'				=>	'\'sqlite_\' taula aurrizkia erreserbatuta dago SQLite motorrak erabili dezan. Aukeratu beste aurrizki bat',
'Existing table error'			=>	'\'%susers\' izeneko taula bat badago \'%s\' datubasean. FluxBB aurretik instalatuta dagoela edo beste programaren batek taula izen berberak erabiltzen dituela. Hainbat FLuxBB instalazio egin nahi badituzu beste taula aurrizki bat aukeratu behar duzu',
'InnoDB off'					=>	'InnoDB ez dago gaituta antza. Aukeratu InnoDB euskarria duen datu-base geruza bat, edo gaitu InnoDB zure MySQL zerbitzarian',
'Administrators'				=>	'Administratzaileak',
'Administrator'					=>	'Administratzailea',
'Moderators'					=>	'Moderatzaileak',
'Moderator'						=>	'Moderatzilea',
'Guests'						=>	'Gonbidatuak',
'Guest'							=>	'Gonbidatua',
'Members'						=>	'Kideak',
'Announcement'					=>	'Idatzi zure oharra hemen.',
'Rules'							=>	'Idatzi zure arauak hemen',
'Maintenance message'			=>	'Foroak mantentze lanetarako itxi dira momentuz. Saiatu berriro geroago mesedez.',
'Test post'						=>	'Froga gaia',
'Message'						=>	'Hau iksusten baduzu (ikusten duzulakoan nago), FluxBB ondo instalatu da itxuraz! Orain hasi saioa eta zoaz administrazio kontrol panelera foroa konfiguratzeko.',
'Test category'					=>	'Froga kategoria',
'Test forum'					=>	'Froga foroa',
'This is just a test forum'		=>	'Hau froga foro bat besterik ez da',
'Alert cache'					=>	'<strong>Ezin da cache direktorioan idatzi!</strong> FluxBB behar bezala ibili dadin, <em>%s</em> direktorian idazteko baimena izan behar du PHPk. Erabili chmod baimen egokiak ezartzeko, zalantzatan bazaude 0777 baimenak ezarri.',
'Alert avatar'					=>	'<strong>Ezin da avatar direktorioan idatzi!</strong> Erabiltzaileek personalizatutako avatar irudiak igotzea ahalbidetu nahi baduzu PHPk <em>%s</em> direktorioan idazteko baimena izan behar du. Gero avatar irudiak beste direktorio batean gordetzea aukeratu dezakezu (ikus Admin/Aukerak). Erabili chmod baimen egokiak ezartzeko, zalantzatan bazaude 0777 baimenak ezarri.',
'Alert upload'					=>	'<strong>Zerbitzariak ez ditu fitxaregiak kargatzea onartzen!</strong> Erabiltzaileak avatar irudi pertsonalizatuak igozea ahalbidetu nahi baduzu PHPko file_uploads konfigurazio ezarpena gaitu behar duzu. Fitxategiak igotzea ahalbidetu eta gero, avatarrak kargatzea gaitu dezakezu Administrazioa/Aukerak/Ezaugarriak atalean.',
'FluxBB has been installed'		=>	'FluxBB instalatu da. Instalazioarekin bukatzeko jarraitu beheko argibide hauek.',
'Final instructions'			=>	'Bukaerako argibideak',
'Info 17'						=>	'Instalazioa bukatzeko, beheko botoia sakatu behar duzu config.php deritzon fitxategi bat deskargatzeko. Orduan fitxategi hau zure FluxBB instalazioaren erro direktoriora igo behar duzu.',
'Info 18'						=>	'config.php igo eta gero, FluxBB guztiz instalatuta egongo da! Une horretan, <a href="index.php">zoaz foroaren hasierara</a>.',
'Download config.php file'		=>	'Deskargatu config.php fitxategia',
'FluxBB fully installed'		=>	'FluxBB erabat instalatu da! Orain <a href="index.php">zoaz foroaren hasierara</a>.',

);
