<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Sartu baliozko posta-helbidea',
'Email legend 2'			=>	'Sartu eta baieztatu baliozko posta-helbidea',
'Localisation legend'		=>	'Ezarri zure kokaleku-aukerak',
'Timezone'					=>	'Ordu-zona',
'Timezone info'				=>	'Zure ordu-zona hautatu behar duzu foroan orduak zuzen ager daitezen.',
'DST'						=>	'Doitu udako ordutegia: Kontrol-lauki hau markatu behar da foroan udako ordutegia ager dadin nahi baduzu.',
'Time format'				=>	'Denbora-formatua',
'Date format'				=>	'Data-formatua',
'Default'					=>	'Lehenetsia',
'Language'					=>	'Hizkuntza',
'Email setting info'		=>	'Hautatu beste erabiltzaileek zure posta-helbidea ikus dezaten nahi duzun ala ez eta beste erabiltzaileek foroaren bidez zuri posta elektronikoak bidaltzeko ahalmena (formulario bidezko posta) izan dezaten ala ez.',
'Email setting 1'			=>	'Erakutsi zure posta elektronikoaren helbidea.',
'Email setting 2'			=>	'Ezkutatu zure posta elektronikoaren helbidea baina baimendu formulario bidezko posta.',
'Email setting 3'			=>	'Ezkutatu zure posta elektronikoaren helbidea eta desgaitu formulario bidezko posta.',
'Privacy options legend'	=>	'Ezarri pribatutasun-aukerak',
'Confirm pass'				=>	'Baieztatu pasahitza',

'Username too short'		=>	'Erabiltzaile-izenek gutxienez 2 karaktere eduki behar dute. Hautatu beste izen (luzeago) bat.',
'Username too long'			=>	'Erabiltzaile-izenek  ez dute 25 karaktere baino gehiago eduki behar. Hautatu beste izen (laburrago) bat.',
'Username guest'			=>	'Gonbidatu erabiltzaile-izena erreserbatua dago. Hautatu beste izen bat.',
'Username IP'				=>	'Erabiltzaile-izenek ezin dute IP helbide baten forma eduki. Hautatu beste izen bat.',
'Username reserved chars'	=>	'Erabiltzaile-izenek ezin dute \', " karaktererik eduki, ezta [ edo ] aldi berean. Hautatu beste izen bat.',
'Username BBCode'			=>	'Erabiltzaile-izenek ezin dituzte eduki foroan erabilitako formatu-etiketak (BBCode). Hautatu beste izen bat.',
'Banned username'			=>	'Sartu duzun erabiltzaile-izena debekatu egin da foro honetan. Hautatu beste izen bat.',
'Pass too short'			=>	'Pasahitzek gutxienez 4 hitz eduki behar dute. Hautatu beste izen (luzeago) bat.',
'Pass not match'			=>	'Pasahitzek ez dute bat egiten.',
'Banned email'				=>	'Sartu duzun posta-helbidea debekatu egin da foro honetan. Hautatu beste posta-helbide bat.',
'Dupe email'				=>	'Beste norbait erregistratu da posta-helbide horrekin. Hautatu beste posta-helbide bat.',
'Sig too long'				=>	'Sinadurek ezin dituzte %1$s karaktere baino gehiago eduki',
'Sig too many lines'		=>	'Sinadurek ezin dute %s lerro baino gehiago eduki',
'Bad ICQ'					=>	'Baliogabeko ICQ UIN helbidea sartu duzu. Egin atzera eta zuzendu.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Moscow, Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Yekaterinburg',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Krasnoyarsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita, Irkutsk',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Vladivostok',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Magadan',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands, Kamchatka',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
