<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'				=>	'Profilaren menua',
'Section essentials'		=>	'Oinarrizkoak',
'Section personal'			=>	'Pertsonala',
'Section messaging'			=>	'Mezularitza',
'Section personality'		=>	'Pertsonalitatea',
'Section display'			=>	'Bistaratzea',
'Section privacy'			=>	'Pribatutasuna',
'Section admin'				=>	'Administrazioa',

// Miscellaneous
'Username and pass legend'	=>	'Sartu zure erabiltzaile-izena eta pasahitza',
'Personal details legend'	=>	'Sartu zure xehetasun pertsonalak',
'Contact details legend'	=>	'Sartu mezularitza-xehetasunak',
'User activity'				=>	'Erabiltzaile-jarduera',
'Paginate info'				=>	'Sartu zenbat gai eta mezu ikusi nahi dituzun orri bakoitzean.',

// Password stuff
'Pass key bad'				=>	'Pasahitza aktibatzeko zehaztutako gakoa ez da zuzena edo iraungi egin da. Eskatu pasahitz berria. Horrek huts egiten badu, jarri harremanetan foroaren administratzailearekin hurrengo helbidean:',
'Pass updated'				=>	'Zure pasahitza eguneratu egin da. Orain zure pasahitz berriarekin hasi behar duzu saioa.',
'Pass updated redirect'		=>	'Pasahitza eguneratu egin da. Berbideratzen &hellip;',
'Wrong pass'				=>	'Pasahitz zaharra okerra da.',
'Change pass'				=>	'Aldatu pasahitza',
'Change pass legend'		=>	'Sartu eta baieztatu zure pasahitz berria',
'Old pass'					=>	'Pasahitz zaharra',
'New pass'					=>	'Pasahitz berria',
'Confirm new pass'			=>	'Baieztatu pasahitz berria',
'Pass info'						=>	'Pasahitzek gutxienez 4 karaktere izan behar dituzte. Pasahitzek maiuskulak eta minuskulak bereizten dituzte.',

// Email stuff
'Email key bad'			=>	'Pasahitza aktibatzeko zehaztutako gakoa ez da zuzena edo iraungi egin da. Eskatu berriro posta-helbidearen aldaketa. Horrek huts egiten badu, jarri harremanetan foroaren administratzailearekin hurrengo helbidean:',
'Email updated'			=>	'Posta-helbidea eguneratu egin da.',
'Activate email sent'		=>	'Posta bat bidali da zehaztutako helbidera, posta-helbide berria aktibatzeko argibideekin. Iristen ez bada, jarri harremanetan foroaren administratzailearekin hurrengo helbidean:',
'Email legend'				=>	'Sartu zure posta-helbide berria',
'Email instructions'		=>	'Aktibazio-esteka bat duen posta bat bidaliko zaizu zure helbide berrira. Estekan klik egin behar duzu helbide berria aktibatzeko.',
'Change email'				=>	'Aldatu posta-helbidea',
'New email'				=>	'Posta berria',

// Avatar upload stuff
'Avatars disabled'			=>	'Adaministratzaileak avatarren euskarria desgaitu du.',
'Too large ini'				=>	'Hautatutako fitxategia handiegia da. Zerbitzariak ez du baimendu hura igotzea.',
'Partial upload'			=>	'Hautatutako fitxategia partzialki igo da. Saiatu berriro.',
'No tmp directory'			=>	'PHPk ezin izan du gorde igotako fitxategia behin-behineko kokaleku batean.',
'No file'					=>	'Ez duzu fitxategirik hautatu.',
'Bad type'					=>	'Igo nahi duzun fitxategiaren mota ez da onartzen. Onartutako motak gif, jpeg eta png dira.',
'Too wide or high'			=>	'Igo nahi duzun fitxategia onartzen den zabalera edo altuera maximoa baino handiagoa da',
'Too large'					=>	'Igo nahi duzun fitxategia onartzen den maximoa baino handiagoa da',
'pixels'					=>	'pixel',
'bytes'						=>	'byte',
'Move failed'				=>	'Zerbitzariak ezin izan du gorde igotako fitxategia. Jarri harremanetan foroaren administratzailearekin hurrengo helbidean:',
'Unknown failure'			=>	'Errore ezezaguna gertatu da. Saiatu berriro.',
'Avatar upload redirect'	=>	'Avatarra igo da. Berbideratzen &hellip;',
'Avatar deleted redirect'	=>	'Avatarra ezabatu da. Berbideratzen &hellip;',
'Avatar desc'				=>	'Avatar bat zure mezuetan erabiltzaile-izenaren azpian erakuts daitekeen irudi txiki bat da. Ez da hau baino handiagoa izan behar:',
'Upload avatar'				=>	'Igo avatarra',
'Upload avatar legend'		=>	'Sartu igoko den avatarraren fitxategia',
'Delete avatar'				=>	'Ezabatu avatarra',	// only for admins
'File'						=>	'Fitxategia',
'Upload'					=>	'Igo',	// submit button

// Form validation stuff
'Forbidden title'			=>	'Sartu duzun izenburuak hitz debekatua dauka. Beste izenburu bat hautatu behar duzu.',
'Profile redirect'			=>	'Profila eguneratu da. Berbideratzen &hellip;',

// Profile display stuff
'Users profile'					=>	'%s\'-(e)n profila',
'Username info'					=>	'Erabiltzaile-izena: %s',
'Email info'					=>	'Posta-helbidea: %s',
'Posts info'					=>	'Mezuak: %s',
'Registered info'				=>	'Erregistro-data: %s',
'Last post info'				=>	'Azken mezua: %s',
'Last visit info'				=>	'Azken bisita: %s',
'Show posts'				=>	'Erakutsi mezu guztiak',
'Show topics'					=>	'Erakutsi gai guztiak',
'Show subscriptions'			=>	'Erakutsi harpidetza guztiak',
'Realname'					=>	'Benetako izena',
'Location'					=>	'Kokapena',
'Website'					=>	'Webgunea',
'Jabber'					=>	'Jabber',
'ICQ'						=>	'ICQ',
'MSN'						=>	'Microsoft kontua',
'AOL IM'					=>	'AOL IM',
'Yahoo'						=>	'Yahoo! Messenger',
'Avatar'					=>	'Avatarra',
'Signature'					=>	'Sinadura',
'Sig max size'					=>	'Luzera maximoa: %s karaktere / Lerro-kopuru maximoa: %s',
'Avatar legend'				=>	'Ezarri zure avatarraren bistaratze-aukerak',
'Avatar info'				=>	'Avatar bat zure mezuetan erabiltzaile-izenaren azpian erakuts daitekeen irudi txiki bat da. Beheko estekan klik eginez avatar bat igo dezakezu.',
'Change avatar'				=>	'Aldatu avatarra',
'Signature legend'			=>	'Osatu zure sinadura',
'Signature info'			=>	'Sinadura zure mezuen azpian itsatsiko den testu-zati txiki bat da. Bertan zuk nahi duzuna idatz dezakezu. Agian zure aipurik gogokoena edo zure horoskopoko ikurra jarri nahi duzu. Zuk aukeratu! Sinaduran BBCode-a erabil dezakezu nahi izanez gero, foro honetan baimenduta badago. Foroan baimendutako/gaitutako ezaugarriak ikus ditzakezu behean, sinadura editatzen duzun bakoitzean.',
'Sig preview'				=>	'Uneko sinaduraren aurrebista:',
'No sig'					=>	'Unean ez dago sinadurarik gordeta profilean.',
'Signature quote/code/list/h'	=>	'Aipuen, kodearen eta zerrenden BBCode-ak ez dira onartzen sinaduretan.',
'Topics per page'			=>	'Gaiak',
'Posts per page'			=>	'Mezuak',
'Leave blank'				=>	'Utzi hutsik foroaren balio lehenetsia erabiltzeko.',
'Subscription legend'	                =>	'Ezarri zure harpidetze-aukerak',
'Notify full'				=>	'Txertatu mezua harpidetze-postetan.',
'Auto notify full'			=>	'Harpidetu automatikoki gaietara mezua bidaltzean.',
'Show smilies'				=>	'Erakutsi aurpegierak ikono grafiko gisa',
'Show images'				=>	'Erakutsi irudiak mezuetan.',
'Show images sigs'			=>	'Erakutsi irudiak erabiltzaile-sinaduretan.',
'Show avatars'				=>	'Erakutsi erabiltzaileen avatarrak mezuetan.',
'Show sigs'					=>	'Erakutsi erabiltzaile-sinadurak.',
'Style legend'				=>	'Hautatu erabili nahi duzun estiloa',
'Styles'				=>	'Estiloak',
'Admin note'				=>	'Admin oharra',
'Pagination legend'			=>	'Sartu orrialde-zenbaketaren aukerak',
'Post display legend'		=>	'Ezarri zure aukerak mezuak bistaratzeko',
'Post display info'			=>	'Konexio motela badaukazu, aukera hauek desgaituta (batez ere mezuetan eta sinaduretan irudiak erakustearena) azkarrago kargatuko dira orriak.',
'Instructions'				=>	'Zure profila eguneratzen duzunean, orri honetara itzuliko zara.',

// Administration stuff
'Group membership legend'	=>	'Hautatu erabiltzaile-taldea',
'Save'						=>	'Gorde',
'Set mods legend'			=>	'Ezarri moderatzaile-atzipena',
'Moderator in info'			=>	'Hautatu zein foro moderatuko duen erabiltzaile honek. Oharra: Moderatzaileei dagokie soilik, administratzaileek baimen osoa daukate foro guztietan.',
'Update forums'				=>	'Eguneratu foroak',
'Delete ban legend'			=>	'Ezabatu (administratzaileek soilik) edo debekatu erabiltzailea',
'Delete user'				=>	'Ezabatu erabiltzailea',
'Ban user'					=>	'Debekatu erabiltzailea',
'Confirm delete legend'		=>	'Garrantzitsua: irakurri erabiltzailea ezabatu baino lehen',
'Confirm delete user'		=>	'Baieztatu erabiltzailea ezabatuko dela',
'Confirmation info'			=>	'Baieztatu hurrengo erabiltzailea ezabatu nahi duzula:',	// the username will be appended to this string
'Delete warning'			=>	'Adi! Ezabatutako erabiltzaileak eta/edo mezuak ezin dira leheneratu. Erabiltzaile honen mezuak ez ezabatzea hautatzen baduzu, mezuak eskuz ezabatu beharko dira gero.',
'Delete posts'				=>	'Ezabatu erabiltzaile honen mezu eta gai guztiak.',
'Delete'					=>	'Ezabatu',		// submit button (confirm user delete)
'User delete redirect'		=>	'Erabiltzailea ezabatu da. Berbideratzen …',
'User promote redirect'			=>	'Erabiltzailea promozionatu da. Berbideratzen …',
'Group membership redirect'	=>	'Taldeko kide egitea gorde da. Berbideratzen …',
'Update forums redirect'	=>	'Foroaren moderatzailearen eskubideak eguneratu dira. Berbideratzen &hellip;',
'Ban redirect'				=>	'Berbideratzen &hellip;',
'No delete admin message'		=>	'Administratzaileak ezin dira ezabatu. Erabiltzaile hau ezabatzeko, lehenego beste erabiltzaile-talde batera mugitu behar duzu.',

);
