<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'				=>	'Erabiltzailearen bilaketa',
'No search permission'		=>	'Ez daukazu baimenik bilaketa-funtzioa erabiltzeko.',
'Search flood'				=>	'Gutxienez %s segundo igaro behar dira bilaketen artean. Itxaron pixka batean eta saiatu berriro.',
'Search'					=>	'Bilaketa',
'Search criteria legend'	=>	'Sartu bilaketa-irizpidea',
'Search info'				=>	'Gako-hitz bidez bilatzeko, sartu hitz bat edo gehiago. Banandu hitzak zuriuneekin. Erabili AND, OR eta NOT bilaketa fintzeko. Egile bidez bilatzeko sartu haren erabiltzaile-izena. Erabili * komodina parekatze partzialetarako.',
'Keyword search'			=>	'Gako-hitzen bidezko bilaketa',
'Author search'				=>	'Egileen bidezko bilaketa',
'Search in legend'			=>	'Hautatu non bilatuko den',
'Search in info'			=>	'Hautatu bilaketa zein forotan egin nahi duzun eta bilaketa gaien izenburuetan, mezuen testuetan edo bietan egin nahi duzun.',
'Search multiple forums info'		=>	'Fororik aukeratu ezean, foro guztietan bilatuko da.',
'Forum search'				=>	'Foroa',
'Search in'					=>	'Bilaketa-tokia',
'Message and subject'		=>	'Mezuen testuan eta gaien izenburuetan',
'Message only'				=>	'Mezuen testuan soilik',
'Topic only'				=>	'Gaien izenburuetan soilik',
'Sort by'					=>	'Ordenatze-irizpidea',
'Sort order'				=>	'Antolaketa',
'Search results legend'		=>	'Hautatu nola ikusiko diren bilaketaren emaitzak',
'Search results info'		=>	'Emaitzak nola ordenatu eta erakutsiko diren hauta dezakezu.',
'Sort by post time'			=>	'Ordua',
'Sort by author'			=>	'Egilea',
'Sort by subject'			=>	'Gaia',
'Sort by forum'				=>	'Foroa',
'Ascending'					=>	'Gorantz',
'Descending'				=>	'Beherantz',
'Show as'					=>	'Emaitzen bistaratzea',
'Show as topics'			=>	'Gaien arabera',
'Show as posts'				=>	'Mezuen arabera',

// Results
'Search'							=>	'Bilatu',
'Search results'			=>	'Bilaketa-emaitzak',
'Quick search show_new'				=>	'Berriak',
'Quick search show_recent'			=>	'Aktiboak',
'Quick search show_unanswered'		=>	'Erantzunik gabekoak',
'Quick search show_replies'			=>	'Bidalitakoak',
'Quick search show_user_topics'		=>	'%s(r)en gaiak',
'Quick search show_user_posts'		=>	'%s(r)en mezuak',
'Quick search show_subscriptions'	=>	'%s(r)en harpidetzak',
'By keywords show as topics'		=>	'\'%s\' duten mezuak dituzten gaiak',
'By keywords show as posts'			=>	'\'%s\' duten mezuak',
'By user show as topics'			=>	'%s(e)k idatzitako mezuak dituzten gaiak',
'By user show as posts'				=>	'%s(r)en gaiak',
'By both show as topics'			=>	'\'%s\' duten mezuak dituzten gaiak, %s(e)k idatzita',
'By both show as posts'				=>	'\'%s\' duten mezuak, %s(e)k idatzita',
'No terms'					=>	'Gutxienez gako-hitz bat eta/edo egile bat sartu behar duzu bilaketa egiteko.',
'No hits'					=>	'Zure bilaketak ez du emaitzarik izan.',
'No user posts'				=>	'Erabiltzaile honek ez dauka mezurik foro honetan.',
'No user topics'					=>	'Ez dago erabiltzaile honek hasitako gairik foro honetan.',
'No subscriptions'			=>	'Ez zaude harpidetuta gai batera ere.',
'No new posts'				=>	'Ez dago mezu berririk duen gairik zure azken bisitatik.',
'No recent posts'			=>	'Ez da mezu berririk bidali azken 24 orduetan.',
'No unanswered'				=>	'Ez dago erantzunik gabeko mezurik foro honetan.',
'Go to post'				=>	'Joan mezura',
'Go to topic'				=>	'Joan gaira',

);
