<?php

// Definizioni di lingua usate in admin-users.php
/* Traduzione di: Oscon.it */

$lang_admin_users = array(

'Non numeric message'		=>	'Il valore inserito non &egrave; un numero.',
'Invalid date time message'	=>	'La inserita non &egrave; valida.',
'Not verified'				=>	'Non verificato',

// Azione: cancellazion/interdizione di massa, ecc.
'No users selected'         =>  'Nessun utente selezionato.',
'No move admins message'    =>  'Per ragioni di sicurezza, non &egrave; permesso spostare pi&ugrave; amministratori a un altro gruppo. &Egrave; possibile effettuare l\'operazione singolarmente da cisacun rispettivo profilo.',
'No delete admins message'  =>  'Gli amministratori non possono essere cancellati. Per cancellare un amministratore &egrave; necessario prima modificarne i privilegi.',
'No ban admins message'     =>  'Gli amministratori non possono essere interdetti. Per interdire un amministratore &egrave; necessario prima modificarne i privilegi.',
'No ban mods message'       =>  'I moderatori non possono essere interdetti. Per interdire un moderatore &egrave; necessario prima modificarne i privilegi.',
'Move users'                =>  'Cambiare gruppo utente',
'Move users subhead'        =>  'Selezionare un nuovo gruppo utente',
'New group label'           =>  'Nuovo gruppo',
'New group help'            =>  'Selezionare il gruppo al quale assegnare l\'utente selezionato. Per ragioni di sicurezza, non &egrave; possibile spostare pi&ugrave, utenti al gruppo amministratori.',
'Invalid group message'     =>  'ID del gruppo errato.',
'Users move redirect'       =>  'Gruppo utente modificato. Reindirizzamento &hellip;',
'Delete users'              =>  'Cancellare utenti',
'Confirm delete legend'     =>  'Importante: leggere prima di proseguire',
'Confirm delete info'       =>  'Confermare la cancellazione degli utenti selezionati.',
'Delete posts'              =>  'Cancellare ogni discussione e messaggio pubblicato.',
'Delete warning'            =>  'Attenzione! Gli utenti e i rispettivi messaggi saranno cancellati in modo definitivo. Scegliendo invece di non cancellare i messaggi pubblicati, potranno poi essere cancellati manualmente.',
'Users delete redirect'     =>  'Utenti cancellati. Reindirizzamento &hellip;',
'Ban users'                 =>  'Interdire utenti',
'Message expiry subhead'    =>  'Messaggio per l\'utente e data di scadenza',
'Ban message label'         =>  'Messaggio',
'Ban message help'          =>  'Un messaggio sar&agrave; mostrato all\'utente quando tenta la connessione al forum.',
'Expire date label'         =>  'Data di scadenza',
'Expire date help'          =>  'La data nella qualle l\'interdizione terminer&agrave; automaticamente (formato: aaaa-mm-gg). Lasciare vuoto per interdire all\'infinito (&egrave; possibile comunque modificare l\'interdizione successivamente).',
'Ban IP label'              =>  'Indirizzo IP da interdire',
'Ban IP help'               =>  'Interdire anche gli indirizzi IP degli utenti interdetti per prevenire la registrazione di altri utenti.',
'Invalid date message'      =>  'La data inserita non &egrave; valida.',
'Invalid date reasons'      =>  'Il formato deve essere AAAA-MM-GG e deve terminare almeno un giorno nel futuro.',
'Users banned redirect'     =>  'Utenti interdetti. Reindirizzamento &hellip;',

'User search head'			=>	'Ricerca utenti',
'User search subhead'		=>	'Criteri di ricerca',
'User search info'			=>	'Ricerca utenti nell\'archivio. &Egrave; possibile inserire uno o pi&ugrave; termini. Il carattere jolly (*) &egrave; accettato.',
'Username label'			=>	'Nome utente',
'E-mail address label'		=>	'Indirizzo email',
'Title label'				=>	'Titolo',
'Real name label'			=>	'Nome reale',
'Website label'				=>	'Sito web',
'Jabber label'				=>	'Jabber',
'ICQ label'					=>	'ICQ',
'MSN label'					=>	'MSN Messenger',
'AOL label'					=>	'AOL IM',
'Yahoo label'				=>	'Yahoo Messenger',
'Location label'			=>	'Luogo',
'Signature label'			=>	'Firma',
'Admin note label'			=>	'Nota amministratore',
'Posts more than label'		=>	'Numero di messaggi maggiore di',
'Posts less than label'		=>	'Numero di messaggi minore di',
'Last post after label'		=>	'Ultimo messaggio in fondo',
'Date help'					=>	'(aaaa-mm-gg hh:mm:ss)',
'Last post before label'	=>	'Ultimo messaggio in cima',
'Last visit after label'    =>  'Ultima visita in fondo',
'Last visit before label'   =>  'Ultima visita in cima',
'Registered after label'	=>	'Registrato dopo',
'Registered before label'	=>	'Registrato prima',
'Order by label'			=>	'Ordina per',
'Order by username'			=>	'Nome utente',
'Order by e-mail'			=>	'Email',
'Order by posts'			=>	'Numero di messaggi',
'Order by last post'		=>	'Ultimo messaggio',
'Order by last visit'       =>  'Ultima visita',
'Order by registered'		=>	'Data di registrazione',
'Ascending'					=>	'Ascendente',
'Descending'				=>	'Discendente',
'User group label'			=>	'Gruppo utenti',
'All groups'				=>	'Tutti i gruppi',
'Unverified users'			=>	'Utente non verificato',
'Submit search'				=>	'Cerca',
'IP search head'			=>	'Cerca IP',
'IP search subhead'			=>	'Inserire indirizzo IP da ricercare',
'IP address label'			=>	'Indirizzo IP',
'IP address help'			=>	'L\'indirizzo IP da cercare nell\'archivio.',
'Find IP address'			=>	'Trova indirizzo IP',

'Results head'				=>	'Risultati',
'Results username head'		=>	'Nome utente',
'Results e-mail head'		=>	'Email',
'Results title head'		=>	'Titolo/Stato',
'Results posts head'		=>	'Messaggi',
'Results admin note head'	=>	'Nota amministratore',
'Results actions head'		=>	'Azioni',
'Results IP address head'	=>	'Indirizzo IP',
'Results last used head'	=>	'Ultimo utilizzo',
'Results times found head'	=>	'Occorrenze',
'Results action head'		=>	'Azione',
'Results find more link'	=>	'Trova altri utenti con questo IP',
'Results no posts found'	=>	'Non ci sono messaggi di questo utente nel forum.',

'Select'                    =>  'Seleziona',
'Select all'                =>  'Seleziona tutti',
'Unselect all'              =>  'Deseleziona tutti',
'Ban'                       =>  'Interdici',	
'Delete'                    =>  'Cancella',
'Change group'              =>  'Cambia gruppo',

'Bad IP message'			=>	'L\'indirizzo IP inserito non &egrave; corretto.',
'Results view IP link'		=>	'Statistiche IP',
'Results show posts link'	=>	'Messaggi',
'Results guest'				=>	'Ospite',
'Results no IP found'		=>	'L\'indirizzo IP inserito non &egrave; presente nell\'archivio.',
'No match'					=>	'Nessuna corrispondenza'

);
