<?php

// Definizioni di lingua usate in admin-users.php
/* Traduzione di: Oscon.it */

$lang_admin_users = array(

'Non numeric message'		=>	'Il valore inserito non &egrave; un numero.',
'Invalid date time message'	=>	'La inserita non &egrave; valida.',
'Not verified'				=>	'Non verificato',
'User search head'			=>	'Ricerca utenti',
'User search subhead'		=>	'Criteri di ricerca',
'User search info'			=>	'Ricerca utenti nell\'archivio. &Egrave; possibile inserire uno o pi&ugrave; termini. Il carattere jolly (*) &egrave; accettato.',
'Username label'			=>	'Nome utente',
'E-mail address label'		=>	'Indirizzo email',
'Title label'				=>	'Titolo',
'Real name label'			=>	'Nome reale',
'Website label'				=>	'Sito web',
'Jabber label'				=>	'Jabber',
'ICQ label'					=>	'ICQ',
'MSN label'					=>	'MSN Messenger',
'AOL label'					=>	'AOL IM',
'Yahoo label'				=>	'Yahoo Messenger',
'Location label'			=>	'Luogo',
'Signature label'			=>	'Firma',
'Admin note label'			=>	'Nota amministratore',
'Posts more than label'		=>	'Numero di messaggi maggiore di',
'Posts less than label'		=>	'Numero di messaggi minore di',
'Last post after label'		=>	'Ultimo messaggio in fondo',
'Date help'					=>	'(aaaa-mm-gg hh:mm:ss)',
'Last post before label'	=>	'Ultimo messaggio in cima',
'Registered after label'	=>	'Registrato dopo',
'Registered before label'	=>	'Registrato prima',
'Order by label'			=>	'Ordina per',
'Order by username'			=>	'Nome utente',
'Order by e-mail'			=>	'Email',
'Order by posts'			=>	'Numero di messaggi',
'Order by last post'		=>	'Ultimo messaggio',
'Order by registered'		=>	'Data di registrazione',
'Ascending'					=>	'Ascendente',
'Descending'				=>	'Discendente',
'User group label'			=>	'Gruppo utenti',
'All groups'				=>	'Tutti i gruppi',
'Unverified users'			=>	'Utente non verificato',
'Submit search'				=>	'Cerca',
'IP search head'			=>	'Cerca IP',
'IP search subhead'			=>	'Inserire indirizzo IP da ricercare',
'IP address label'			=>	'Indirizzo IP',
'IP address help'			=>	'L\'indirizzo IP da cercare nell\'archivio.',
'Find IP address'			=>	'Trova indirizzo IP',

'Results head'				=>	'Risultati',
'Results username head'		=>	'Nome utente',
'Results e-mail head'		=>	'Email',
'Results title head'		=>	'Titolo/Stato',
'Results posts head'		=>	'Messaggi',
'Results admin note head'	=>	'Nota amministratore',
'Results actions head'		=>	'Azioni',
'Results IP address head'	=>	'Indirizzo IP',
'Results last used head'	=>	'Ultimo utilizzo',
'Results times found head'	=>	'Occorrenze',
'Results action head'		=>	'Azione',
'Results find more link'	=>	'Trova altri utenti con questo IP',
'Results no posts found'	=>	'Non ci sono messaggi di questo utente nel forum.',
'Bad IP message'			=>	'L\'indirizzo IP inserito non &egrave; corretto.',
'Results view IP link'		=>	'Statistiche IP',
'Results show posts link'	=>	'Messaggi',
'Results guest'				=>	'Ospite',
'Results no IP found'		=>	'L\'indirizzo IP inserito non &egrave; presente nell\'archivio.',
'No match'					=>	'Nessuna corrispondenza'

);
