<?php

// Definizioni di lingua usate in admin_index.php
/* Traduzione di: Oscon.it */

$lang_admin_index = array(

'fopen disabled message'			=>	'Impossibile verificare la presenza di aggiornamenti. Abilitare la funzione <em>allow_url_fopen</em> all\'interno del documento di configurazione di PHP (PHP.ini).',
'Upgrade check failed message'		=>	'La ricerca di aggiornamenti non &egrave; andata a termine per ragioni sconosciute.',
'Running latest version message'	=>	'&Egrave; installata la versione pi&ugrave; recente di FluxBB.',
'New version available message'		=>	'&egrave; stata pubblicata una nuova versione di FluxBB. &Egrave; possibile scaricarla da %s.',
'PHPinfo disabled message'			=>	'La funzione PHP \"phpinfo()\" &egrave; disabilitata su questo server.',
'Not available'						=>	'Non disponibile',
'Forum admin head'					=>	'Amministrazione forum',
'NA'								=>	'Non applicabile',
'Welcome to admin'					=>	'Benvenuto nel pannello di amministrazione di FluxBB. Da qui &egrave; possibile controllare le impostazioni del sistema. A seconda che si sia amministratore o moderatore, &egrave; possibile:',
'Welcome 1'							=>	'Organizzare categorie e forum.',
'Welcome 2'							=>	'Impostare le opzioni e le preferenze.',
'Welcome 3'							=>	'Controllare i permessi per gli utenti e gli ospiti.',
'Welcome 4'							=>	'Visualizzare le statistiche IP.',
'Welcome 5'							=>	'Interdire gli utenti.',
'Welcome 6'							=>	'Oscurare testi o parole offensive.',
'Welcome 7'							=>	'Impostare il rango degli utenti.',
'Welcome 8'							=>	'Effettuare la pulizia dai messaggi pi&ugrave; vecchi non utilizzati.',
'Welcome 9'							=>	'Gestire le segnalazioni.',
'Statistics head'					=>	'Statistiche',
'FluxBB version label'				=>	'Versione di FluxBB',
'Check for upgrade'					=>	'Controlla aggiornamenti',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'Carico server',
'Server load data'					=>	'%s - %s utente/i online',
'Environment label'					=>	'Ambiente',
'Environment data OS'				=>	'Sistema operativo: %s',
'Show info'							=>	'Mostra informazioni',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Acceleratore: %s',
'Turck MMCache'						=>	'Turk MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Database',
'Database data rows'				=>	'Righe: %s',
'Database data size'				=>	'Dimensione: %s',

);
