<?php

// Definizioni di lingua usate in admin-options.php
/* Traduzione di: Oscon.it */

$lang_admin_options = array(

'Bad HTTP Referer message'			=>	'HTTP_REFERER non valido. Se il sistema &egrave; stato spostato da una cartella a un\'altra o il dominio &egrave; stato cambiato. Aggiornare manualmente il \"Base URL\" nel database (cambiando il valore di "o_base_url" nella tabella "config") e successivamente svuotare la cache eliminando tutti i documenti .php (solo quelli) nella cartella /cache.',
'Must enter title message'			=>	'Inserire un nome.',
'Invalid e-mail message'			=>	'L\'indirizzo email inserito &egrave; errato.',
'Invalid webmaster e-mail message'	=>	'L\'indirizzo email inserito &egrave; errato.',
'SMTP passwords did not match' 		=>  'Inserire la password SMTP due volte esattamente per mofificarla.',
'Enter announcement here'			=>	'Scrivere un annuncio.',
'Enter rules here'					=>	'Scrivere le regole di utilizzo.',
'Default maintenance message'		=>	'Il sistema &egrave; attualmente in manutenzione. Prova pi&ugrave; tardi, grazie.',
'Timeout error message'				=>	'Il valore "Timeout online" deve essere minore al valore "Timeout visit".',
'Options updated redirect'			=>	'Opzioni aggiornate. Reindirizzamento &hellip;',
'Options head'						=>	'Opzioni',

// Sezione "essenziali"
'Essentials subhead'				=>	'Dati essenziali',
'Board title label'					=>	'Titlo',
'Board title help'					=>	'Il titolo mostrato all\'inizio di ogni pagina (esempio: "Forum di Oscon"). Questo campo <strong>non pu&ograve;</strong> contenere HTML.',
'Board desc label'					=>	'Descrizione',
'Board desc help'					=>	'Una breve descrizione mostrata all\'inizio di ogni pagina (esempio: "Il contratto open source"). Questo campo <strong>pu&ograve;</strong> contenere HTML.',
'Base URL label'					=>	'Indirizzo base',
'Base URL help'						=>	'L\'indirizzo completo di installazione senza tralasciare le slash (esempio: http://www.dominio.est/forum). Questo campo <strong>deve essere corretto</strong> affinch&eacute; le funzioni di amministrazione e moderazione siano attive. Se compare il messaggio "Referer non valido" &egrave; probabilmente compilato in modo scorretto.',
'Timezone label'					=>	'Fuso orario predefinito',
'Timezone help'						=>	'Il fuso orario predefinito per gli ospiti e gli utenti che non hanno modificato l\'impostazione nel proprio profilo.',
'DST label'							=>	'Ora legale',
'DST help'							=>	'Impostare se l\'ora legale &egrave; attiva (avanza l\'orario di un\'ora).',
'Language label'					=>	'Lingua predefinita',
'Language help'						=>	'La lingua predefinita per gli ospiti e gli utenti che non hanno modificato l\'impostazione nel proprio profilo. Rimuovendo un pacchetto di lingua, questo campo deve essere aggiornato.',
'Default style label'				=>	'Stile predefinito',
'Default style help'				=>	'Lo stile grafico predefinito per gli ospiti e gli utenti che non hanno modificato l\'impostazione nel proprio profilo.',

// Sezione essenziali (fuso orario)
'UTC-12:00'							=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'							=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'							=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'							=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'							=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'							=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'							=>	'(UTC-08:00) Pacific',
'UTC-07:00'							=>	'(UTC-07:00) Mountain',
'UTC-06:00'							=>	'(UTC-06:00) Central',
'UTC-05:00'							=>	'(UTC-05:00) Eastern',
'UTC-04:00'							=>	'(UTC-04:00) Atlantic',
'UTC-03:30'							=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'							=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'							=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'							=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'								=>	'(UTC) Western European, Greenwich',
'UTC+01:00'							=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'							=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'							=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'							=>	'(UTC+03:30) Iran',
'UTC+04:00'							=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'							=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'							=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'							=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'							=>	'(UTC+05:45) Nepal',
'UTC+06:00'							=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'							=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'							=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'							=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'							=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'							=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'							=>	'(UTC+09:30) Australian Central',
'UTC+10:00'							=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'							=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'							=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'							=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'							=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'							=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'							=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'							=>	'(UTC+14:00) Line Islands',

// Sezione "Orario e scadenze"
'Timeouts subhead'					=>	'Orario e scadenze',
'Time format label'					=>	'Formato ora',
'PHP manual'						=>	'Manuale PHP',
'Time format help'					=>	'[Formato attuale: %s]. Si veda il %s per ulteriori opzioni di formattazione.',
'Date format label'					=>	'Formato data',
'Date format help'					=>	'[Formato attuale: %s]. Si veda il %s per ulteriori opzioni di formattazione.',
'Visit timeout label'				=>	'Scadenza di visita',
'Visit timeout help'				=>	'Secondi che devono trascorrere prima che i dati di ultima visita di un utente siano aggiornati (influenza prevalentemente l\'indicazione dei nuovi messaggi).',
'Online timeout label'				=>	'Scadenza attivit&agrave;',
'Online timeout help'				=>	'Secondi che devono trascorrere prima che un utente venga rimosso dalla lista degli utenti online.',
'Redirect time label'				=>	'Tempo di reindirizzamento',
'Redirect time help'				=>	'Secondi da attendere durante il reindirizzamento. Se impostato su 0 la pagina di reindirizzamento non sar&agrave; visualizzata.',

// Sezioni "Visualizzazioni"
'Display subhead'					=>	'Visualizzazioni',
'Version number label'				=>	'Numero versione',
'Version number help'				=>	'Mostrare il numero di versione di FluxBB nel pi&eacute; di pagina.',
'Info in posts label'				=>	'Informazioni utente nelle discussioni',
'Info in posts help'				=>	'Mostrare le informazioni dell\'autore sotto il nome utente nelle discussioni. Le informazioni mostrate sono: luogo, data di registrazione, numero di post e dati di contatto (email e URL).',
'Post count label'					=>	'Contatore di messaggi',
'Post count help'					=>	'Mostrare il numero di messaggi pubblicati dall\'utente nelle discussioni, nei profili e nella lista utenti.',
'Smilies label'						=>	'Emoticon nei messaggi',
'Smilies help'						=>	'Convertire le emoticon testuali in piccole icone grafiche.',
'Smilies sigs label'				=>	'Emoticon nelle firme',
'Smilies sigs help'					=>	'Convertire nelle firme le emoticon testuali in piccole icone grafiche.',
'Clickable links label'				=>	'Collegamenti',
'Clickable links help'				=>	'Convertire automaticamente gli indirizzi web nei messaggi trasformandoli in collegamenti.',
'Topic review label'				=>	'Revisione della discussione',
'Topic review help'					=>	'Numero massimo di messaggi da mostrare in coda alla pagina durante la composizione di un messaggio (dal pi&ugrave; recente). Impostare 0 per disabilitare.',
'Topics per page label'				=>	'Discussioni per pagina',
'Topics per page help'				=>	'Il numero predefinito di discussioni da visualizzare per ogni pagina in un forum. Gli utenti possono personalizzare questa impostazione nel proprio profilo.',
'Posts per page label'				=>	'Messaggi per pagina',
'Posts per page help'				=>	'Il numero predefinito di messaggi da visualizzare per ogni pagina in una discussione. Gli utenti possono personalizzare questa impostazione nel proprio profilo.',
'Indent label'						=>	'Dimensione di indentazione',
'Indent help'						=>	'Se impostato su 8, sar&agrave; utilizzata una tabella per visualizzare il testo contenuto nei marcatori [code][/code]. Altrimenti sar&agrave; utilizzata una spaziatura corrispondente.',
'Quote depth label'					=>	'Massima nidificazione del marcatore [quote]',
'Quote depth help'					=>	'Il numero massimo di marcatori [quote] che pu&ograve; essere nidificato. Ogni marcatore ulteriore sar&agrave; scartato.',

// Sezione "Funzionalità"
'Features subhead'					=>	'Funzionalit&agrave;',
'Quick post label'					=>	'Risposta celere',
'Quick post help'					=>	'Visualizza un modulo per la risposta veloce in fondo a ogni discussione. In questo modo gli utenti potranno rispondere direttamente dalla pagina corrente.',
'Users online label'				=>	'Utenti in linea',
'Users online help'					=>	'Visualizza nella prima pagina il numero di ospiti e utenti registrati attualmente in linea.',
'Censor words label'				=>	'Testo oscurato',
'Censor words help'					=>	'Abilita l\'oscuramento di specifici testi o parole nella pubblicazione. Si veda %s per ulteriori informazioni.',
'Signatures label'					=>	'Firme',
'Signatures help'					=>	'Permette agli utenti di allegare una firma ai proprio messaggi.',
'User ranks label'					=>	'Rango utenti',
'User ranks help'					=>	'Abilita un sistema di attribuzione rango a seconda del numero di messaggi pubblicati. Si veda %s per ulteriori informazioni.',
'User has posted label'				=>	'Utenti attivi di recente',
'User has posted help'				=>	'Mostra un piccolo segno grafico accanto alla discussione quando l\'utente attualmente connesso vi ha pubblicato un messaggio di recente. Disattivare in caso di alto carico del server.',
'Topic views label'					=>	'Visulizzazioni',
'Topic views help'					=>	'Mostra il numero di visite a ciascuna discussione. Disattivare in caso di alto carico del server.',
'Quick jump label'					=>	'Salto veloce',
'Quick jump help'					=>	'Visualizza un menu a cascata con reindirizzamento automatico al forum scelto.',
'GZip label'						=>	'Compressione Gzip',
'GZip help'							=>	'Comprime tramite Gzip le informazioni inviate al browser. Questa funzione riduce il consumo di banda ma impiega maggiori risorse di server. Per funzionare, richiede che PHP sia configurato con le zlib (--with-zlib). Nota: se il server Apache dispone gi&agrave; di mod_gzip o mod_deflate per la compressione di script PHP, non attivare questa funzione.',
'Search all label'					=>	'Ricerca globale',
'Search all help'					=>	'Abilita la ricerca in tutti i forum. Se disabilitato, le ricerche saranno permesse solo in un forum per volta. Disattivare in caso di alto carico del server.',
'Menu items label'					=>	'Collegamenti supplementari',
'Menu items help'					=>	'Aggiunge collegamenti al menu di navigazione presente in cima a ogni pagina. Il formato &egrave; X = &lt;a href="URL"&gt;LINK&lt;/a&gt; dove X &egrave; la posizione alla quale il collegamento deve essere inserito (esempio: 0 per inserirlo all\'inizio, 2 per inserirlo dopo "Lista utenti", ecc.). Scrivere un collegamento per ogni riga.',
'Default feed label'				=>	'Tipo di Feed predefinito',
'Default feed help'					=>	'&Egrave; possibile presentare i feed dei forum in due differenti formati (RSS o Atom) o nasconderli.',
'None'								=>	'Nascondi',
'RSS'								=>	'RSS',
'Atom'								=>	'Atom',

// Sezione "segnalazioni"
'Reports subhead'					=>	'Segnalazioni',
'Reporting method label'			=>	'Metodo di invio segnalazioni',
'Internal'							=>	'Interno',
'By e-mail'							=>	'Email',
'Both'								=>	'Entrambi',
'Reporting method help'				=>	'&Egrave; possibile scegliere se inviare le segnalazioni (sulle discussioni e i messaggi) tramite il sistema interno al forum, tramite l\'invio via email agli indirizzi nella mailing list (si veda sotto) o entrambi.',
'Mailing list label'				=>	'Mailing list',
'Mailing list help'					=>	'Separare ciascun indirizzo email con una virgola. Gli utenti in questa lista sono i destinatari delle segnalazioni.',

// Sezione "immagine personale"
'Avatars subhead'					=>	'Avatar',
'Use avatars label'					=>	'Uso avatar',
'Use avatars help'					=>	'Permette agli utenti di caricare un\'immagine personale (avatar) che sar&agrave; mostrata sotto il proprio rango o titolo.',
'Upload directory label'			=>	'Cartella di caricamento',
'Upload directory help'				=>	'La cartella di caricamento per gli avatar (con indirizzo relativo a quella madre di FluxBB). &Egrave; necessario abilitare i permessi di scrittura (CHMOD).',
'Max width label'					=>	'Larghezza massima',
'Max width help'					=>	'La larghezza massima consentita dell\'immagine personale (in pixel, si raccomanda 60).',
'Max height label'					=>	'Altezza massima',
'Max height help'					=>	'L\'altezza massima consentita dell\'immagine personale (in pixel, si raccomanda 60).',
'Max size label'					=>	'Peso massimo',
'Max size help'						=>	'Il peso massimo consentito dell\'immagine personale (in byte, si raccomanda 60).',

// Sezione "email"
'E-mail subhead'					=>	'Email',
'Admin e-mail label'				=>	'Email dell\'amministratore',
'Admin e-mail help'					=>	'L\'indirizzo email dell\'amministratore.',
'Webmaster e-mail label'			=>	'Email del webmaster',
'Webmaster e-mail help'				=>	'L\'indirizzo al quale verranno spediti i messaggi dal sistema.',
'Forum subscriptions label'     	=>  'Iscrizioni ai forum',
'Forum subscriptions help'      	=>  'Abilita l\'iscrizione ai forum (invio di un\'email quando qualcuno apre una nuova discussione).',
'Topic subscriptions label'      	=>  'Iscrizioni alle discussioni',
'Topic subscriptions help'      	=>  'Abilita l\'iscrizione alle discussioni (invio di un\'email quando qualcuno risponde).',
'SMTP address label'				=>	'Indirizzo server SMTP',
'SMTP address help'					=>	'L\'indirizzo di un server SMTP esterno col quale inviare email. Si pu&ograve; indicare una porta specifica se il server non usa automaticamente la porta 25 (esempio: mail.dominio.est:3580). Lasciare vuoto per utilizzare il programma di posta locale.',
'SMTP username label'				=>	'Nome utente SMTP',
'SMTP username help'				=>	'Nome utente per il server SMTP. Specificare un nome utente solo se richiesto dal server SMTP (la maggioranza <strong>non richiesde</strong> autenticazione).',
'SMTP password label'				=>	'Password SMTP',
'SMTP change password help'      	=>  'Selezionare per cambiare o cancellare l\'attuale password.',
'SMTP password help'				=>	'Password due volte la password per il server SMTP. Specificare un nome utente solo se richiesto dal server SMTP (la maggioranza <strong>non richiesde</strong> autenticazione).',
'SMTP SSL label'					=>	'Criptare SMTP tramite SSL',
'SMTP SSL help'						=>	'Cripta la connessione al server SMTP usando il protocollo SSL. Funzione da attivare solo se il server lo richiede e la versione in uso di PHP supporta SSL.',

// Sezione "registrazione"
'Registration subhead'				=>	'Registrazione',
'Allow new label'					=>	'Permetti nuove registrazioni',
'Allow new help'					=>	'Abilita la registrazione di nuovi utenti. Disabilitare solo in circostanze eccezionali.',
'Verify label'						=>	'Conferma registrazione',
'Verify help'						=>	'Abilita il sistema di conferma via email per i neoregistrati, generando una password casuale successivamente modificabile dall\'utente. Richiede inoltre una conferma agli utenti che cambiano indirizzo email.',
'Report new label'					=>	'Avviso nuove registrazioni',
'Report new help'					=>	'Abilita la notifica agli utenti presenti nella via miling list (si veda sopra) quando un nuovo utente si registra.',
'Use rules label'					=>	'Regole del forum',
'Use rules help'					=>	'Abilita l\'obbligo di accettare le regole del forum durante la registrazione (inserire il testo di seguito). Le regole saranno inoltre raggiungibili tramite un collegamento nella barra di navigazione in cima a ogni pagina.',
'Rules label'						=>	'Regole del forum',
'Rules help'						=>	'Inserire qui eventuali informazioni e regolamenti che gli utenti devono leggere e accettare per registrarsi. Abilitando la funzione &egrave; necessario scrivere un testo, altrimenti sar&agrave; disabilitata. Il testo pu&ograve; contenere HTML.',
'E-mail default label'				=>	'Impostazioni email',
'E-mail default help'				=>	'Impostazioni predefinite sulla riservatezza dei nuovi utenti.',
'Display e-mail label'				=>	'Mostra l\'indirizzo email agli altri utenti.',
'Hide allow form label'				=>	'Nascondi l\'indirizzo email ma abilita l\'invio di email tramite il forum.',
'Hide both label'					=>	'Nascondi l\'indirizzo email e disabilita l\'invio di email tramite forum.',

// Sezione "annunci"
'Announcement subhead'				=>	'Annunci',
'Display announcement label'		=>	'Mostra annuncio',
'Display announcement help'			=>	'Visualizza nei forum il seguente messaggio.',
'Announcement message label'		=>	'Messaggio',
'Announcement message help'			=>	'Il testo pu&ograve; contenere HTML.',

// Sezione "manutenzione"
'Maintenance subhead'				=>	'Manutenzione',
'Maintenance mode label'			=>	'Modo manutenzione',
'Maintenance mode help'				=>	'Se abilitato, il sistema sar&agrave; accessibile solo agli amministratori. &Egrave; da abilitare quando il sistema &egrave; irraggiungibile per qualisasi necessit&agrave; di amministrazione (aggiornamenti, gestione server, ecc.). <strong>ATTENZIONE! Non disconnettersi quando il modo manutenzione &egrave; attivo o non sar&agrave; possibile accedere nuovamente</strong>!',
'Maintenance message label'			=>	'Messaggio di manutenzione',
'Maintenance message help'			=>	'Questo messaggio sar&agrave; visualizzato dagli utenti quando &egrave; attivo il modo manutenzione. Se lasciato vuoto, sarr&agrave; utilizzato un messaggio predefinito. Il testo pu&ograve; contenere HTML.',

);
