<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Inserisci un indirizzo email valido',
'Email legend 2'			=>	'Inserisci e conferma un indirizzo email valido',
'Localisation legend'		=>	'Imposta le tue opzioni di localizzazione',
'Time zone'					=>	'Fuso orario',
'Time zone info'				=>	'Devi scegliere il tuo fuso orario in modo da visualizzare correttamente gli orari nel forum.',
'DST'						=>	'Utilizza l\'ora solare (incrementa l\'orario di un\'ora).',
'Time format'				=>	'Formato dell\'ora',
'Date format'				=>	'Formato della data',
'Default'					=>	'Default',
'Language'					=>	'Linguaggio',
'Email setting info'		=>	'Scegli se vuoi che il tuo indirizzo email sia visibile agli altri utenti o meno e se vuoi che gli altri utenti possano mandarti email tramite il forum (modulo email) o meno.',
'Email setting 1'			=>	'Mostra il tuo indirizzo email.',
'Email setting 2'			=>	'Nascondi il tuo indirizzo email ma consenti l\'invio tramite modulo.',
'Email setting 3'			=>	'Nascondi il tuo indirizzo email e vieta l\'invio tramite modulo.',
'Privacy options legend'	=>	'Imposta le tue opzioni di privacy',
'Confirm pass'				=>	'Conferma password',

'Username too short'		=>	'Il nome utente deve essere composto da almeno 2 caratteri. Per favore scegli un altro nome utente.',
'Username too long'			=>	'Il nome utente deve essere composto da al massimo 25 caratteri. Per favore scegli un altro nome utente (più corto).',
'Username guest'			=>	'Il nome utente ospite è riservato. Per favore scegli un altro nome utente.',
'Username IP'				=>	'Il nome utente non può avere forma di indirizzi IP. Per favore scegli un\'altro nome utente.',
'Username reserved chars'	=>	'Il nome utente non può contenere i caratteri \', " e [ oppure ]. Per favore scegli un nome utente differente.',
'Username BBCode'			=>	'Il nome utente non può contenere testi formattati ((BBCode) che il forum utilizza. Per favore scegli un altro nome utente.',
'Banned username'			=>	'Il nome utente che hai inserito è bannato dal forum. Per favore scegli un nome utente differente.',
'Pass too short'			=>	'Le password devono essere composte da almeno 4 caratteri. Per favore scegli un\'altra password.',
'Pass not match'			=>	'Le password non coincidono. Per favore torna indietro e correggi.',
'Banned email'				=>	'L\'indirizzo email che hai inserito è interdetto dal forum. Per favore scegli un altro indirizzo email.',
'Dupe email'				=>	'Qualcun altro è già registrato con quell\'indirizzo email. Per favore scegli un altro indirizzo email.',
'Sig too long'				=>	'Le firme non possono essere più lunghe di',
'Sig too many lines'		=>	'Le firme non possono avere più di',
'Bad ICQ'					=>	'Hai inserito un UIN di ICQ non valido. Per favore torna indietro e correggi.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
