<?php

// Definizioni di lingua usate in profile.php e register.php
/* Traduzione di: Oscon.it */

$lang_prof_reg = array(

'Email legend'				=>	'Indirizzo email valido',
'Email legend 2'			=>	'Inserire e confermare un indirizzo email valido',
'Localisation legend'		=>	'Opzioni di localizzazione',
'Time zone'					=>	'Fuso orario',
'Time zone info'			=>	'Per visualizzare correttamente le date selezionare il proprio fuso orario. Se l\'ora legale &egrave; attiva (avanzamento di un\'ora), indicarlo nell\'apposito campo.',
'DST'						=>	'Ora legale (avanzamento di un\'ora).',
'Time format'				=>	'Formato ora',
'Date format'				=>	'Formato data',
'Default'					=>	'Predefinito',
'Language'					=>	'Lingua',
'Email setting info'		=>	'Visibilit&agrave; del proprio indirizzo email e disponibilit&agrave; al contatto.',
'Email setting 1'			=>	'Mostra indirizzo email.',
'Email setting 2'			=>	'Nascondi indirizzo email ma abilita ricezione email dal forum.',
'Email setting 3'			=>	'Nascondi indirizzo email e disabilita ricezione email dal forum.',
'Privacy options legend'	=>	'Opzioni di riservatezza',
'Confirm pass'				=>	'Conferma password',

'Username too short'		=>	'Il nome utente deve essere composto da almeno 2 caratteri. Scegline un altro, grazie.',
'Username too long'			=>	'Il nome utente non pu&ograve; eccedere i 25 caratteri. Scegline un altro, grazie.',
'Username guest'			=>	'Il nome utente ospite è riservato. Scegline un altro, grazie.',
'Username IP'				=>	'Il nome utente non pu&ograve; essere un indirizzo IP. Scegline un altro, grazie.',
'Username reserved chars'	=>	'Il nome utente non pu&ograve; contenere i caratteri \', ", [, ]. Scegline un altro, grazie.',
'Username BBCode'			=>	'Il nome utente non pu&ograve; contenere BBCode. Scegline un altro, grazie.',
'Banned username'			=>	'Il nome utente scelto &egrave; interdetto. Scegline un altro, grazie.',
'Pass too short'			=>	'La password deve essere composta da almeno 4 caratteri. Scegline un\'altra, grazie.',
'Pass not match'			=>	'Le password indicate non coincidono.',
'Banned email'				=>	'L\'indirizzo email scelto &egrave; interdetto. Scegline un altro, grazie.',
'Dupe email'				=>	'L\'indirizzo email scelto &egrave; gi&agrave; in uso. Se l\'hai persa, richiedi la password smarrita.',
'Sig too long'				=>	'Le firme non possono eccedere i %1$ caratteri. Riduci la firma di %2$ caratteri e riprova, grazie.',
'Sig too many lines'		=>	'Le firme non possono eccedere le %s linee. Riducine il numero e riprova, grazie.',
'Bad ICQ'					=>	'L\'ICQ UIN inserito &egrave; errato. Correggilo e riprova, grazie.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
