<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'				=>	'Menu profilo',
'Section essentials'		=>	'Essenziali',
'Section personal'			=>	'Personali',
'Section messaging'			=>	'Messaggi',
'Section personality'		=>	'Personalità',
'Section display'			=>	'Visualizzazione',
'Section privacy'			=>	'Privacy',
'Section admin'				=>	'Amministrazione',

// Miscellaneous
'Username and pass legend'	=>	'Inserisci il tuo nome utente e la tua password',
'Personal details legend'	=>	'Inserisci i tuoi dettagli personali',
'Contact details legend'	=>	'Inserisci i tuoi dettagli dei messaggi',
'User activity'				=>	'Attività dell\'utente',
'Paginate info'				=>	'Inserisci il numero di discussioni e messaggi che vuoi visualizzare in ogni pagina.',

// Password stuff
'Pass key bad'				=>	'La chiave di attivazione per la password è incorretta o è scaduta. Per favore richiedi una nuova password. Se non è possibile contatta l\'amministratore del forum a',
'Pass updated'				=>	'La tua password è stata cambiata. Ora puoi accedere con la nuova password.',
'Pass updated redirect'		=>	'Password aggiornata. Reindirizzamento …',
'Wrong pass'				=>	'Password vecchia errata.',
'Change pass'				=>	'Cambia password',
'Change pass legend'		=>	'Inserisci e conferma la tua nuova password',
'Old pass'					=>	'Password vecchia',
'New pass'					=>	'Password nuova',
'Confirm new pass'			=>	'Conferma la nuova password',
'Pass info'						=>	'Le password dovrebbero essere lunghe almeno 4 caratteri. Le password sono case sensitive.',

// Email stuff
'Email key bad'			=>	'La chiave di attivazione dell\'email non è corretto. Per favore richiedi il cambio dell\'indirizzo email. Se non è possibile contatta l\'amministratore del forum a',
'Email updated'			=>	'Il tuo indirizzo email è stato aggiornato.',
'Activate email sent'		=>	'Una email è state inviata all\'indirizzo specificato con le istruzioni su come attivare il nuovo indirizzo email. Se non ti arriva puoi contattare l\'amministratore del forum a',
'Email legend'				=>	'Inserisci il tuo nuovo indirizzo email',
'Email instructions'		=>	'Una email ti sarà inviata al tuo nuovo indirizzo email con il link per l\'attivazione. Clicca sul link che ricevi per email per attivare il nuovo indirizzo.',
'Change email'				=>	'Cambia indirizzo email',
'New email'				=>	'Nuova email',

// Avatar upload stuff
'Avatars disabled'			=>	'L\'amministratore ha disattivato il supporto per gli avatar.',
'Too large ini'				=>	'Il file selezionato è troppo grave da inviare. Il server non consente l\'invio.',
'Partial upload'			=>	'Il file selezionato è stato inviato solo parzialmente. Per favore riprova.',
'No tmp directory'				=>	'PHP was unable to save the uploaded file to a temporary location.',
'No file'					=>	'Non hai scelto un file da inviare.',
'Bad type'					=>	'Il file che hai cercato di inviare non è del tipo consentito. I tipi consentiti sono gif, jpeg and png.',
'Too wide or high'			=>	'Il file che hai cercato di inviare è più largo e/o alto del massimo consentito',
'Too large'					=>	'Il file che hai cercato di inviare è più del massimo consentito',
'pixels'					=>	'pixel',
'bytes'						=>	'byte',
'Move failed'				=>	'Il server non è stato in grado di salvare il file inviato. Per favore contatta l\'amministratore del server a',
'Unknown failure'			=>	'Si è verificato un errore sconosciuto. Per favore riprova.',
'Avatar upload redirect'	=>	'Avatar inviato. Reindirizzamento …',
'Avatar deleted redirect'	=>	'Avatar eliminato. Reindirizzamento …',
'Avatar desc'				=>	'Un avatar è una piccola immagine che viene visualizzata sotto il tuo nome utente nei tuoi messaggi. Non può essere più grande di',
'Upload avatar'				=>	'Invia avatar',
'Upload avatar legend'		=>	'Inserisci un avatar da inviare',
'Delete avatar'				=>	'Elimina avatar',	// only for admins
'File'						=>	'File',
'Upload'					=>	'Invia',	// submit button

// Form validation stuff
'Forbidden title'			=>	'Il titolo che hai inserito contiene parole non consentite. Devi scegliere un titolo differente.',
'Profile redirect'			=>	'Profilo aggiornato. Reindirizzamento …',

// Profile display stuff
'Users profile'					=>	'Profilo di %s',
'Username info'					=>	'Nome utente: %s',
'Email info'					=>	'Email: %s',
'Posts info'					=>	'Messaggi: %s',
'Registered info'				=>	'Registrato: %s',
'Last post info'				=>	'Ultimo messaggio: %s',
'Show posts'					=>	'Mostra tutti i messaggi',
'Realname'						=>	'Nome reale',
'Location'						=>	'Luogo',
'Website'						=>	'Sito web',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'MSN Messenger',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'Avatar',
'Signature'						=>	'Firma',
'Sig max size'					=>	'Lunghezza massima: %s caratteri / Numero massimo di linee: %s',
'Avatar legend'				=>	'Imposta le opzioni di visualizzazione degli avatar',
'Avatar info'				=>	'Un avatar è una piccola immagine che viene visualizzata in tutti i tuoi messaggi. Puoi inviare un avatar cliccando il link sottostante.',
'Change avatar'				=>	'Cambia avatar',
'Signature legend'			=>	'Imposta la tua firma',
'Signature info'			=>	'La firma è un piccolo testo che viene inserito nei tuoi messaggi. In esso puoi inserire quello che desideri. Forse ti piacerebbe inserire la tua citazione preferita o il tuo segno zodiacale. A te la scelta! Nella tua firma puoi usare i tag BBCode se è permesso in questo forum. Puoi visualizzare le opzioni che sono attivate/disattivate listate in basso ogni volta che modifichi la tua firma.',
'Sig preview'				=>	'Anteprima della firma attuale:',
'No sig'					=>	'Nessuna firma registrata nel profilo.',
'Signature quote/code/list/h'	=>	'The quote, code, list, and heading BBCodes are not allowed in signatures.',
'Topics per page'			=>	'Discussioni',
'Posts per page'			=>	'Messaggi',
'Leave blank'				=>	'Lascia vuoto per utilizzare le impostazioni predefinite del forum.',
'Subscription legend'			=>	'Imposta le tue opzioni per le sottoscrizioni',
'Notify full'				=>	'Includi il messaggio nelle email per le sottoscrizioni.',
'Auto notify full'				=>	'Sottoscrivi automaticamente tutti le discussioni in cui scrivi',
'Show smilies'				=>	'Mostra le faccine come icone',
'Show images'				=>	'Visualizza le immagini nei messaggi.',
'Show images sigs'			=>	'Visualizza le immagini nella firma degli utenti.',
'Show avatars'				=>	'Visualizza gli avatar degli utenti nei messaggi.',
'Show sigs'					=>	'Mostra la firma degli utenti.',
'Style legend'				=>	'Scegli il tuo stile preferito',
'Styles'						=>	'Stili',
'Admin note'				=>	'Nota dell\'amministratore',
'Pagination legend'			=>	'Inserisci le opzioni di impaginazione',
'Post display legend'		=>	'Imposta le opzioni per la visualizzazione dei messaggi',
'Post display info'			=>	'Se hai una connessione ad internet lenta, disattivando questa opzioni in particolare su immagini nei messaggi e nelle firme le pagine caricheranno più velocemente.',
'Instructions'				=>	'Quando aggiorni il profilo sarai reindirizzato a questa pagina.',

// Administration stuff
'Group membership legend'	=>	'Scegli gruppo utenti',
'Save'						=>	'Salva',
'Set mods legend'			=>	'Imposta gli accessi da moderatore',
'Moderator in info'			=>	'Scegli quali categorie questo utente può moderare. Nota: questo si riferisce solo ai moderatori. Gli amministratori hanno pieni permessi in tutte le categorie.',
'Update forums'				=>	'Aggiorna categorie',
'Delete ban legend'			=>	'Elimina (solo amministratori) o interdici utente',
'Delete user'				=>	'Elimina utente',
'Ban user'					=>	'Interdici utente',
'Confirm delete legend'		=>	'Importante: leggi prima di eliminare un utente',
'Confirm delete user'		=>	'Conferma l\'eliminazione dell\'utente',
'Confirmation info'			=>	'Per favore conferma l\'eliminazione dell\'utente',	// the username will be appended to this string
'Delete warning'			=>	'Attenzione! Utenti e/o messaggi eliminati non possono essere ripristinati. Se scegli di non cancellare  i messaggi fatti da questo utente, i messaggi potranno essere cancellati manualmente in un secondo momento.',
'Delete posts'				=>	'Elimina ogni messaggio e discussione di questo utente.',
'Delete'					=>	'Elimina',		// submit button (confirm user delete)
'User delete redirect'		=>	'Utente eliminato. Reindirizzamento …',
'Group membership redirect'	=>	'Iscrizione al gruppo salvata. Reindirizzamento …',
'Update forums redirect'	=>	'Diritti di moderatore della categoria salvati. Reindirizzamento …',
'Ban redirect'				=>	'Reindirizzamento …',
'No delete admin message'		=>	'L\'amministratore non può essere cancellato.',

);
