<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'ناتوانرێت نوێبکرێتەوە لەو کاتەوە  \'allow_url_fopen\' ناچالاکە لەسەر ئەم سیستەمە.',
'Upgrade check failed message'		=>	'بەهۆکارێکی نەزانراو پشکنینی نوێکردنەوە شکستی هێنا.',
'Running latest version message'	=>	' تۆ دواهەمین وەشاندنی FluxBB بەکاردەبەیت.',
'New version available message'		=>	'وەشاندنێکی نوێی  FluxBB وەشێندرا، دەتوانیت دایگریت لێرەوە %s.',
'Deleted install.php redirect'		=>	'پەڕگەکە بە سەرکەوتوویی سڕدڕایەوە. گەڕانەوە ...',
'Delete install.php failed'			=>	'نەتوانرا پەڕگەی  install.php. ــی بسڕدرێتەوە. تکایە خۆت بیسڕەوە.',
'Not available'						=>	'بەردەست نییە',
'Forum admin head'					=>	'بەڕێوبەرایەتی مەکۆ',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'بەخێرهاتی بۆ بەڕێوبەرایتی  FluxBB لێرەوە دەتوانیت تەختی سەرەکی بەڕێوەببەیت بەدەسەڵاتی بەڕێوبەرەوە و بەچاودێریشەوە:',
'Welcome 1'							=>	'ڕێکخستنی مەکۆ و هاوپۆلەکان.',
'Welcome 2'							=>	'دانانی هەڵبژاردن و وردەکاری مەکۆکان.',
'Welcome 3'							=>	'بەڕێوەبردنی دەسەڵاتەکانی بەکارهێنەران و میوانان.',
'Welcome 4'							=>	'نیشاندانی ئایپییە جێگیرەکان بۆ بەکارهێنەران.',
'Welcome 5'							=>	'ڕاگرتنی ئەندامان.',
'Welcome 6'							=>	'چاودێریکردنی وشەکان.',
'Welcome 7'							=>	'دانانی پلەی بەکارهێنەران.',
'Welcome 8'							=>	'بەشکردنی پەیامە کۆنەکان.',
'Welcome 9'							=>	'چارەسەری ڕێپۆرتەکان.',
'Alerts head'						=>	'ئاگادارییەکان',
'Install file exists'				=>	'پەڕگەی install.php هێشتا ماوە, بەڵام دەبێت بسڕدرێتەوە. %s.',
'Delete install file'				=>	'بیسڕەوە',
'About head'					=>	'دۆخ و سەرژمێرییەکان',
'FluxBB version label'				=>	'وەشاندنی FluxBB ',
'Check for upgrade'					=>	'پشکنین بۆ نوێکردنەوە',
'FluxBB version data'				=>	'v%s - %s',
'Server statistics label'			=>	'دۆخی ڕاژە',
'View server statistics'			=>	'دۆخی ڕاژە نیشان بدە',
'Support label'						=>	'پشتگیریی',
'Forum label'						=>	'مەکۆ',
'IRC label'							=>	'IRC کەناڵ',

// Language definitions used in admin_statistics.php
'PHPinfo disabled message'			=>	'خەسڵەتی  phpinfo() ناچالاککراوە لەسەر ئەم ڕاژەیە.',
'Server statistics head'			=>	'دۆخی ڕاژە',
'Server load label'					=>	'بارکردنی ڕاژە',
'Server load data'					=>	'%s - %s ئەندام سەرهێڵن',
'Environment label'					=>	'دەوروبەر',
'Environment data OS'				=>	'سیستەمی کارگێڕی: %s',
'Show info'							=>	'نیشاندانی زانیاری',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Accelerator: %s',
'Turck MMCache'						=>	'Turk MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'بنکەدراوە',
'Database data rows'				=>	'ڕیزەکان: %s',
'Database data size'				=>	'قەبارە: %s',
);
