<?php

// Language definitions used in admin-users.php
$lang_admin_users = array(

'Non numeric message'		=>	'تۆ نرخێکی نا-ژمارەییت نووسی لەناو ستوونی تەنها ژمارەیی.',
'Invalid date time message'	=>	'تۆ بەروار/کاتێکی نادروستت نووسی.',
'Not verified'				=>	'دڵنیا نەکراوەتەوە',
'User search head'			=>	'گەڕانی بەکارهێنەر',
'User search subhead'		=>	'پێوانەیی گەڕان بنووسە',
'User search info'			=>	'بگەڕێ بۆ بەکارهێنەران لە بنکەدراوەکە. دەتوانی مەرجێک یان زیاتر بنووسی بۆ گەڕان بۆی. Wildcards لە فۆرمەکە بە (*) وەرگیراوە.',
'Username label'			=>	'ناوی بەکارهێنەر',
'E-mail address label'		=>	'ناونیشانی ئیمەیڵ',
'Title label'				=>	'ناونیشان',
'Real name label'			=>	'ناوی تەواو',
'Website label'				=>	'وێبگە',
'Jabber label'				=>	'جابەر',
'ICQ label'					=>	'ICQ',
'MSN label'					=>	'پەیامبەری مسن',
'AOL label'					=>	'پەیامبەری خێرای AOL',
'Yahoo label'				=>	'پەیامبەر یاهوو',
'Location label'			=>	'شوێن',
'Signature label'			=>	'واژۆ',
'Admin note label'			=>	'سەرنجی بەڕێوەبەر',
'Posts more than label'		=>	'ژمارەی پەیامەکان مەزنترە لە',
'Posts less than label'		=>	'ژمارەی پەیامەکان کەمترە لە',
'Last post after label'		=>	'دوا پەیام لەدوای',
'Date help'					=>	'(yyyy-mm-dd hh:mm:ss)',
'Last post before label'	=>	'دوا پەیام لەپێش',
'Registered after label'	=>	'تۆماربوو لەدوای',
'Registered before label'	=>	'تۆماربوو لەپێش',
'Order by label'			=>	'ڕیزکردن بەپێی',
'Order by username'			=>	'ناوی بەکارهێنەر',
'Order by e-mail'			=>	'ئیمەیڵ',
'Order by posts'			=>	'ژمارەی پەیامەکان',
'Order by last post'		=>	'دوا پەیام',
'Order by registered'		=>	'تۆماربوو',
'Ascending'					=>	'چوونەسەر',
'Descending'				=>	'هاتنەخوار',
'User group label'			=>	'گرووپی بەکارهێنەر',
'All groups'				=>	'هەموو گرووپەکان',
'Unverified users'			=>	'بەکارهێنەرە دڵنیانەکراوەکان',
'Submit search'				=>	'گەڕان بنێرە',
'IP search head'			=>	'گەڕانی IP',
'IP search subhead'			=>	'IP بنووسە بۆ گەڕان بۆی',
'IP address label'			=>	'ناونیشانی IP',
'IP address help'			=>	'ناونیشانی IP بۆ گەڕان بۆ لە پەیامی بنکەدراوەکە.',
'Find IP address'			=>	'ناونیشانی IP بدۆزەوە',

'Results head'				=>	'ئەنجامەکانی گەڕان',
'Results username head'		=>	'ناوی بەکارهێنەر',
'Results e-mail head'		=>	'ئیمەیڵ',
'Results title head'		=>	'ناونیشان/بار',
'Results posts head'		=>	'پەیامەکان',
'Results admin note head'	=>	'سەرنجی بەڕێوەبەر',
'Results actions head'		=>	'کردارەکان',
'Results IP address head'	=>	'ناونیشانی IP',
'Results last used head'	=>	'دوا بەکارهێنان',
'Results times found head'	=>	'کاتە دۆزراوەکان',
'Results action head'		=>	'کردار',
'Results find more link'	=>	'بەکارهێنەری زیاتر بدۆزیەوە بەم IP ــیە',
'Results no posts found'	=>	'لە ئێستادا هیچ پەیامێک نییە لەلایەن ئەو بەکارهێنەرە لە مەکۆکە.',
'Bad IP message'			=>	'ناونیشانی IP دانراو ناتوانراوە بە دروستی فۆرمات بکرێت.',
'Results view IP link'		=>	'بینینی دۆخی IP',
'Results show posts link'	=>	'پەیامەکان نیشانبدە',
'Results guest'				=>	'میوان',
'Results no IP found'		=>	'ناونیشانی IP دانراو ناتوانرێت بدۆزرێتەوە لە بنکەدراوەکە.',
'No match'					=>	'گونجان نییە'

);
