<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'			=>	'No user by that username registered. If you want to add a ban not tied to a specific username just leave the username blank.',
'No user ID message'		=>	'No user by that ID registered.',
'User is admin message'		=>	'The user %s is an administrator and can\'t be banned. If you want to ban an administrator, you must first demote him/her to moderator or user.',
'Must enter message'		=>	'You must enter either a username, an IP address or an email address (at least).',
'Cannot ban guest message'	=>	'The guest user cannot be banned.',
'Invalid IP message'		=>	'You entered an invalid IP/IP-range.',
'Invalid e-mail message'	=>	'The email address (e.g. user@domain.com) or partial email address domain (e.g. domain.com) you entered is invalid.',
'Invalid date message'		=>	'You entered an invalid expire date.',
'Invalid date reasons'		=>	'The format should be YYYY-MM-DD and the date must be at least one day in the future.',
'Ban added redirect'		=>	'Ban added. Redirecting …' ,
'Ban edited redirect'		=>	'Ban edited. Redirecting …',
'Ban removed redirect'		=>	'Ban removed. Redirecting …',

'New ban head'				=>	'قەدەغەکردنی نوێ',
'Add ban subhead'			=>	'زۆرکردنی قەدەغەکردن',
'Username label'			=>	'Username',
'Username help'				=>	'The username to ban (case-insensitive).',
'Username advanced help'	=>	'The username to ban (case-insensitive). The next page will let you enter a custom IP and email. If you just want to ban a specific IP/IP-range or email just leave it blank.',

'Ban search head'			=>	'Ban search',
'Ban search subhead'		=>	'Enter search criteria',
'Ban search info'			=>	'Search for bans in the database. You can enter one or more terms to search for. Wildcards in the form of asterisks (*) are accepted. To show all bans leave all fields empty.',
'Date help'					=>	'(yyyy-mm-dd)',
'Message label'				=>	'پەیام',
'Expire after label'		=>	'بەسەربچێت پاش',
'Expire before label'		=>	'بەسەربچێت پێش',
'Order by label'			=>	'بەگوێرەی',
'Order by username'			=>	'ناویبەکارهێنەر',
'Order by ip'				=>	'ئایپی',
'Order by e-mail'			=>	'ئیمەیڵ',
'Order by expire'			=>	'ڕێکەوتی بەسەرچوو',
'Ascending'					=>	'بەرەوسەر',
'Descending'				=>	'بەرەوخوار',
'Submit search'				=>	'دەسپێکردنی گەڕان',

'E-mail label'				=>	'ئیمەیڵ',
'E-mail help'				=>	'ئیمەیڵێک یان دۆمەینی ئیمەیڵێک بۆ قەدەغەکردن بەنمونە (e.g. someone@somewhere.com or somewhere.com). تەماشای "ڕێگەدانی قەدەغەکردنی ئیمەیڵ"  بکە لە بەشی دەسەڵاتەکان.',
'IP label'					=>	'IP address/IP-ranges',
'IP help'					=>	'The IP address or IP-ranges you wish to ban (e.g. 150.11.110.1 or 150.11.110). Separate addresses with spaces. If an IP is entered already it is the last known IP of this user in the database.',
'IP help link'				=>	'کرتەی  %s بکە بۆ نیشاندانی دۆزی ئایپی.',
'Ban advanced head'			=>	'هەڵبژاردنی پێشکەوتوی قەدەغەکردن',
'Ban advanced subhead'		=>	'قەدەغەکردن بەڕێگای ئایپی یان ئیمەیڵ',
'Ban message label'			=>	'پەیامی قەدەغەکردن',
'Ban message help'			=>	'ئەو پەیامەی نیشانی بەکارهێنەر دەدرێت ئەگەر بێتە مەکۆکان.',
'Message expiry subhead'	=>	'قەدەغەکردنی ئایپی و کاتی بەسەرچوونی',
'Ban IP range info'			=>	'زۆزۆر وریابە لە کاتی قەدەغەکردنی ئایپیدا کە هەموو کەس دەگرێتەوە کە لەهەمان ئایپیەوە دێن',
'Expire date label'			=>	'ڕێکەوتی بەسەرچوون',
'Expire date help'			=>	'ئەو ڕێکەوتەی کە قەدەغەکردنی لەسەر لادەبرێت، بەم جۆرە فۆرماتەیە (format: yyyy-mm-dd). بەبەتاڵی جێبهێڵە بۆ دەستکاریکردنی بەئارەزوومەندانە.',

'Results head'				=>	'ئەنجامی گەڕان',
'Results username head'		=>	'ناویبەکارهێنەر',
'Results e-mail head'		=>	'ئیمەیڵ',
'Results IP address head'	=>	'IP/IP-ranges',
'Results expire head'		=>	'بەسەرچووەکان',
'Results message head'		=>	'پەیام',
'Results banned by head'	=>	'قەدەغەکراوە لەلایەن',
'Results actions head'		=>	'فرمانەکان',
'No match'					=>	'هیچ ئەنجامێک',
'Unknown'					=>	'نەزانراو',

);
