<?php

// Language definitions used in admin-users.php
$lang_admin_users = array(

'Non numeric message' => 'تۆ نرخێکی نا ژمارەیەت نووسیوە لە ستوونێک کە دەبێت لە ژمارە بنووسرێت.',
'Invalid date time message' => 'تۆ رۆژ/کات ی هەڵەت نووسیوە .',
'Not verified' => 'نەسەلمێنراوە',
'User search head' => 'گەڕانی بەکارهێنەر',
'User search subhead' => 'ناوچەی گەڕانەکە بنووسە',
'User search info' => 'بگەڕی بۆ بەکارهێنەران لە ناو بنکەی دراو . دەتوانی یەک برگە یازیاتر بنووسی بۆ گەڕان بە دووای . ویڵد کارد لە شێوەی (*) ڕێگە پێدراوە.',
'Username label' => 'ناوی بەکارهێنەر',
'E-mail address label' => 'پۆستی ئەلکترۆنی',
'Title label' => 'سەردێڕ',
'Real name label' => 'ناوی راستی',
'Website label' => 'وێبگە',
'Jabber label' => 'جابەر',
'ICQ label' => 'ICQ',
'MSN label' => 'MSN Messenger',
'AOL label' => 'AOL IM',
'Yahoo label' => 'Yahoo Messenger',
'Location label' => 'شوێن',
'Signature label' => 'ئیمزا',
'Admin note label' => 'تێبینیەکانی بەڕیوەبەر',
'Posts more than label' => 'ژمارەی پەیماکەن زیاتر لە ',
'Posts less than label' => 'ژمارەی پەیامەکان کەمتر لە ',
'Last post after label' => 'دووا پەیام لە دووای',
'Date help' => '(yyyy-mm-dd hh:mm:ss)',
'Last post before label' => 'دووا پەیام پێشتر بوو',
'Registered after label' => 'تۆماربووە لە دووای',
'Registered before label' => 'تۆماربووە لە پێش',
'Order by label' => 'ڕیز بووە بە پێی',
'Order by username' => 'ناوی بەکارهێنەر',
'Order by e-mail' => 'پۆستی ئەلکترۆنی',
'Order by posts' => 'ژمارەی پەیامەکان',
'Order by last post' => 'دووا پەیام',
'Order by registered' => 'تۆماربوویت',
'Ascending' => 'سەربەرەوژوور',
'Descending' => 'سەربەرەوخووار',
'User group label' => 'گرووپی بەکارهێنەران',
'All groups' => 'هەموو گروپەکان',
'Unverified users' => 'بەکارهێنەرە نە سەلمێنراوەکان',
'Submit search' => 'بگەڕێ',
'IP search head' => 'گەڕان بە ئای پی',
'IP search subhead' => 'ئای پی بنووسە بۆ گەڕا بە دووای',
'IP address label' => 'ناونیشانی ئای پی',
'IP address help' => 'ئای پی بنووسە بۆ گەڕان لە ناو بنکەی دراوە.',
'Find IP address' => 'ئای پی بدۆزەرەوە',

'Results head' => 'ئەنجامی گەڕان',
'Results username head' => 'ناوی بەکارهێنەر',
'Results e-mail head' => 'پۆستی ئەلکترۆنی',
'Results title head' => 'سەردێڕ/دۆخ',
'Results posts head' => 'پەیامەکان',
'Results admin note head' => 'تێبینی بەڕێوەبەر',
'Results actions head' => 'کردەوە',
'Results IP address head' => 'ناونیشانی ئا پی',
'Results last used head' => 'دووا جار بەکارهێنراوە',
'Results times found head' => 'کاتی دۆزراوە',
'Results action head' => 'کردەوەکان',
'Results find more link' => 'بەکارهێنەری زیاتر بدۆزەرەوە بەم ئای پی ـیە',
'Results no posts found' => 'ئێستا ئەم بەکارهێنەرە هیچ پەیامێکی نیە لەم مەکۆیە.',
'Bad IP message' => 'ئای پێ نووسراو هێشتا ڕێک نەخراوە.',
'Results view IP link' => 'دۆخی ئای پی ببینە',
'Results show posts link' => 'پەیامەکان پیشان بدەم',
'Results guest' => 'میوان',
'Results no IP found' => 'ئەم ناونیشانی ئای پی ـیە نادۆزرێتەوە لە ناو بنکەی دراوە..',
'No match' => 'هیچ نەدۆزرایەوە'

);

