<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'ناتوانرێت نوێبکرێتەوە لەو کاتەوە  \'allow_url_fopen\' ناچالاکە لەسەر ئەم سیستەمە.',
'Upgrade check failed message'		=>	'بەهۆکارێکی نەزانراو پشکنینی نوێکردنەوە شکستی هێنا.',
'Running latest version message'	=>	' تۆ دواهەمین وەشاندنی FluxBB بەکاردەبەیت.',
'New version available message'		=>	'وەشاندنێکی نوێی  FluxBB وەشێندرا، دەتوانیت دایگریت لێرەوە %s.',
'PHPinfo disabled message'			=>	'کرداری  phpinfo() لەسەر ئەم ڕاژەیە ناچالاکە.',
'Not available'						=>	'بەردەست نییە',
'Forum admin head'					=>	'بەڕێوبەرایەتی مەکۆ',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'بەخێرهاتی بۆ بەڕێوبەرایتی  FluxBB لێرەوە دەتوانیت تەختی سەرەکی بەڕێوەببەیت بەدەسەڵاتی بەڕێوبەرەوە و بەچاودێریشەوە:',
'Welcome 1'							=>	'ڕێکخستنی مەکۆ و هاوپۆلەکان.',
'Welcome 2'							=>	'دانانی هەڵبژاردن و وردەکاری مەکۆکان.',
'Welcome 3'							=>	'بەڕێوەبردنی دەسەڵاتەکانی بەکارهێنەران و میوانان.',
'Welcome 4'							=>	'نیشاندانی ئایۆییە جێگیرەکان بۆ بەکارهێنەران.',
'Welcome 5'							=>	'ڕاگرتنی ئەندامان.',
'Welcome 6'							=>	'چاودێریکردنی وشەکان.',
'Welcome 7'							=>	'دانانی پلەی بەکارهێنەران.',
'Welcome 8'							=>	'Prune old posts.',
'Welcome 9'							=>	'Handle post reports.',
'Statistics head'					=>	'Statistics',
'FluxBB version label'				=>	'FluxBB version',
'Check for upgrade'					=>	'Check for upgrade',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'Server load',
'Server load data'					=>	'%s - %s user(s) online',
'Environment label'					=>	'Environment',
'Environment data OS'				=>	'Operating system: %s',
'Show info'							=>	'Show info',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Accelerator: %s',
'Turck MMCache'						=>	'Turk MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Database',
'Database data rows'				=>	'Rows: %s',
'Database data size'				=>	'Size: %s',

);
