<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'پۆستی ئەلیکترۆنی دروست بنووسە',
'Email legend 2'			=>	'پۆستی ئەلیکترۆنی دروست دووبارە بنووسە',
'Localisation legend'		=>	'هەڵبژاردەکانی جێگەدیاریکردن دابنێ',
'Time zone'					=>	'هەرێمی کات',
'Time zone info'			=>	'بۆ نیشاندانی کاتەکانی مەکۆکە بەدروستی دەبێت کاتی خۆجێیی دیاریبکەی ،ئەگەر کاتی هاوینە لەژێر کاریگەردایە ،دەبێت هەڵبژاردە دراوەکان بپشکنی کە ١ کاتژمێر پێش دەکەوێ',
'DST'						=>	'کاتی هاوینە (بە پێشخستنی ١ کاتژمێر) لەژێر کاریگەردایە',
'Time format'				=>	'جۆری کات',
'Date format'				=>	'جۆری بەروار',
'Default'					=>	'گوێنەدان',
'Language'					=>	'زمان',
'Email setting info'		=>	'دەستنیشانبکە ئەگەر دەتەوێ پۆستی ئەلیکترۆنیت دیاربێت لە بەکارهێنەران یان نا ،وە ئەگەر دەتەوێ بەکارهێنەران پەیوەندیت لەگەڵ بگرن لە ڕێگای فۆرمی پەیوەندی یان نا',
'Email setting 1'			=>	'پۆستی ئەلیکترۆنیت نیشانبدە.',
'Email setting 2'			=>	'پۆستی ئەلیکترۆنی بشارەوە بەڵام ڕێگابدە بە فۆرمی پەیوەندی',
'Email setting 3'			=>	'پۆستی ئەلیکترۆنی بشارەوە ،ڕێگامەدە بە فۆرمی پەیوەندی',
'Privacy options legend'	=>	'ڕێکخستنە تایبەتییەکانت دابنێ',
'Confirm pass'				=>	'دووبارەکردنەوەی تێپەڕەووشە',

'Username too short'		=>	'ناوی بەکارهێنەر بەلایەنی کەم دەبێت ٢ تیپ درێژی بێت ،تکایە ناوێکی (درێژتر) هەڵبژێرە',
'Username too long'			=>	'ناوی بەکارهێنەر نابێ درێژی زیاتر بێت لە ٢٥ تیپ ،تکایە ناوێکی (کورتر) هەڵبژێرە',
'Username guest'			=>	'ناوی بەکارهێنەری میوانەکە گیراوە ،تکایە ناوێکی تر هەڵبژێرە',
'Username IP'				=>	'ناوی بەکارهێنەر نابێت لە  فۆرمەکە بێت بە ناونیشانی ئایپی ،تکایە ناوێکی تر هەڵبژێرە',
'Username reserved chars'	=>	'ناوی بەکارهێنەر نابێت گشت تیپەکان لەخۆبگرێت \', " لەگەڵ [ یان ] بەیەکجار ،تکایە ناوێکی تر هەڵبژێرە',
'Username BBCode'			=>	'ناوی بەکارهێنەر نابێت تاگەکانی جۆرایەتی نووسینی تێدابێت کە مەکۆکە بەکاریدەبات ،تکایە ناوێکی تر هەڵبژێرە',
'Banned username'			=>	'ئەو ناوی بەکارهێنەرەی نووسیوتە ڕاگیراوە لەو مەکۆیە ،تکایە ناوێکی تر هەڵبژێرە',
'Pass too short'			=>	'تێپەڕەووشە بەلایەنی کەم دەبێت درێژی ٤ تیپ بێت ،تکایە تێپەڕەووشەیەکی (درێژتر) هەڵبژێر',
'Pass not match'			=>	'تێپەڕەووشەکان ناگونجێن',
'Banned email'				=>	'ئەو پۆستی ئەلیکترۆنییەکی نووسیوتە لەو مەکۆیە ڕاگیراوە ،تکایە پۆستی ئەلیکترۆنییەکی تر هەڵبژێرە',
'Dupe email'				=>	'کەسێکی تر پێشتر بەو پۆستی ئەلیکترۆنییە تۆماربووە ،تکایە پۆستی ئەلیکترۆنییەکی تر هەڵبژێرە',
'Sig too long'				=>	'تیپ تکایە واژۆکەت کەمبکەوە بە %2$s %1$s واژۆ ناتوانرێ درێژتر بێت لە',
'Sig too many lines'		=>	'دێڕی هەبێت %s واژۆ ناتوانرێ زیاتر لە',
'Bad ICQ'					=>	'کە نووسیوتە بەردەست نییە ،تکایە بگەڕێوە و ڕاستیبکەوە ICQ UIN',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
