<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'زانیاری تاکەکەسی',
'Section essentials'			=>	'بنچینەییەکان',
'Section personal'				=>	'تاکەکەسی',
'Section messaging'				=>	'پەیامکردن',
'Section personality'			=>	'کەسێتی',
'Section display'				=>	'نیشاندان',
'Section privacy'				=>	'تایبەتمەندی',
'Section admin'					=>	'بەڕێوەبەرایەتی',

// Miscellaneous
'Username and pass legend'		=>	'ناوی بەکارهێنەر و تێپەڕەووشە بنووسە',
'Personal details legend'		=>	'وردەکارییە تاکەکەسییەکانت بنووسە',
'Contact details legend'		=>	'وردەکاری پەیامکردنت بنووسە',
'User activity'					=>	'چالاکی بەکارهێنەر',
'Paginate info'					=>	'ژمارەی ئەو پەیام و بابەتانە بنووسە کە ئارەزووتە لە پەڕێکدا دەرکەون',

// Password stuff
'Pass key bad'					=>	':کلیلی تایبەتی چالاکردنی تێپەڕەووشە ڕاست نییە یان بەسەرچووە ،تکایە دوبارە داوای بکەوە یان پەیوەندی بکە بە بەڕێوەبەرایەتیەوە لە',
'Pass updated'					=>	'تێپەڕەووشەی تۆ نوێکرایەوە ،دەتوانی بە تێپەڕەووشە نوێیەکەت بچیتە ژوورەوە',
'Pass updated redirect'			=>	'..تێپەڕەووشە نوێکرایەوە ،گەڕاندنەوە',
'Wrong pass'					=>	'تێپەڕەووشەی کۆنی هەڵە',
'Change pass'					=>	'گۆڕینی تێپەڕەووشە',
'Change pass legend'			=>	'تێپەڕەووشەی نوێت بنووسە و دڵنیای بکەوە',
'Old pass'						=>	'تێپەڕەووشەی کۆن',
'New pass'						=>	'تێپەڕەووشەی نوێ',
'Confirm new pass'				=>	'دووبارە تێپەڕەووشەی نوێ',
'Pass info'						=>	'تێپەڕەووشەکان پێویست بەلایەنی کەم ٤ تیپ درێژیان بێت ،تێپەڕەووشەکان هەستیارن',

// Email stuff
'Email key bad'					=>	':کلیلی تایبەتی چالاککردنی ئیمەیڵ ڕاست نییە یان بەسەرچووە تکایە دووبارە داوای بکەوە ،یان پەیوەندی بکەوە بە بەڕێوەبەرایەتیەوە لە',
'Email updated'					=>	'پۆستی ئەلیکترۆنیت نوێکرایەوە',
'Activate email sent'			=>	':ئیمەیڵێک نێردرا بۆ ناونیشانی دراو لەگەڵ ڕێنمایی چۆنیەتی چالاککردن ،ئەگەر نەگەیشت تکایە پەیوەندی بکە بە بەڕێوەبەرایەتییەوە',
'Email legend'					=>	'پۆستە ئەلیکترۆنییە نوێیەکەت بنووسە',
'Email instructions'			=>	'ئیمەیڵێک دەنێردرێ بۆ ناونیشانە نوێیەکەت لەگەڵ بەستەرێکی چالاککردن ،کرتە لەسەر بەستەری چالاککردن بکە بۆ چالاککردنی ئیمەیڵە نوێیەکەت',
'Change email'					=>	'پۆستی ئەلیکترۆنی بگۆڕە',
'New email'						=>	'ئیمەیڵی نوێ',

// Avatar upload stuff
'Avatars disabled'				=>	'بەڕێوەبەرایەتی پاڵپشتی وێنۆچکەی ڕاگرتووە',
'Too large ini'					=>	'پەڕگەی دەستنیشانکراو زۆر گەورە بوو بۆ بارکردن ،ڕاژە ڕێگا بەو پەڕگانە نادات',
'Partial upload'				=>	'پەڕگەی دەستنیشانکراو تەنها بەشێکی بارکرا ،تکایە هەوڵبدوە',
'No tmp directory'				=>	'نەیتوانی پەڕگەی بارکراو پاشکەوتبکات بۆ شوێنی کاتی PHP',
'No file'						=>	'پەڕگەیەکت هەڵنەبژاردووە بۆ بارکردن',
'Bad type'						=>	'ئەو پەڕگەیەی هەوڵتدا باریبکەیت لە جۆرە ڕێگەپێدراوەکان نییە',
'Too wide or high'				=>	'ئەو پەڕگەیەی هەوڵتدا باریبکەیت لە قەبارەی فراوانی ڕێپێدراو گەورەتر بوو',
'Too large'						=>	'ئەو پەڕگەیەی هەوڵتدا باریبکەیت لە قەبارەی ڕێپێدراو گەورەتر بوو',
'pixels'						=>	'پێکسل',
'bytes'							=>	'بایت',
'Move failed'					=>	':ڕاژەکە نەیتوانی پەڕگەی بارکراو پاشکەوتبکات ،تکایە پەیوەندی بکە بە بەڕێوەبەرایەتی مەکۆ لەt',
'Unknown failure'				=>	'هەڵەی نەناسراو ڕوویدا ،تکایە دووبارە هەوڵبدەوە',
'Avatar upload redirect'		=>	'..وێنۆچکە بارکرا ،گەڕاندنەوە',
'Avatar deleted redirect'		=>	'..وێنۆچکە سڕایەوە ،گەڕاندنەوە',
'Avatar desc'					=>	':وێنۆچکە وێنەیەکی بچووکە لەژێر ناوەکەت نیشاندەدرێت لە پەیامەکانتدا ،نابێت گەورەتر بێت لە',
'Upload avatar'					=>	'وێنۆچکە باربکە',
'Upload avatar legend'			=>	'وێنۆچکەیەک دەستنیشانبکە بۆ بارکردن',
'Delete avatar'					=>	'وێنۆچکە بسڕەوە', // only for admins
'File'							=>	'پەڕگە',
'Upload'						=>	'بارکردن', // submit button

// Form validation stuff
'Forbidden title'				=>	'The title you entered contains a forbidden word. You must choose a different title.',
'Profile redirect'				=>	'..پرۆفایل نوێکرایەوە ،گەڕاندنەوە',

// Profile display stuff
'Users profile'					=>	'%s\' پرۆفایلی',
'Username info'					=>	'%s :بەکارهێنەر',
'Email info'					=>	'%s :ئیمەیڵ',
'Posts info'					=>	'%s :پەیامەکان',
'Registered info'				=>	'%s :تۆماربووە',
'Last post info'				=>	'%s :دوایین پەیام',
'Show posts'					=>	'نیشاندانی سەرجەم پەیامەکان',
'Show topics'					=>	'نیشاندانی سەرجەم بابەتەکان',
'Show subscriptions'			=>	'نیشاندانی سەرجەم بەشداریکردنەکان',
'Realname'						=>	'ناوی تەواو',
'Location'						=>	'شوێن',
'Website'						=>	'وێبگە',
'Jabber'						=>	'جابەر',
'ICQ'							=>	'ICQ ژمارەی',
'MSN'							=>	'MSN پەیامبەر',
'AOL IM'						=>	'AOL پەیامبەری خێرای',
'Yahoo'							=>	'پەیامبەری یاهوو',
'Avatar'						=>	'وێنۆچکە',
'Signature'						=>	'واژۆ',
'Sig max size'					=>	'%s تیپ ،زۆرترین هێڵ %s درێترین',
'Avatar legend'					=>	'هەڵبژاردنەکانی وێنۆچکە دابنێ',
'Avatar info'					=>	'وێنۆچکە وێنەیەکی بووکە لەژێر ناوەکەت دەردەکەوێت لە پەیامەکانتدا',
'Change avatar'					=>	'گۆڕینی وێنۆچکە',
'Signature legend'				=>	'پێکهێنانی واژۆکەت',
'Signature info'				=>	'واژۆ ،پارچەیەکی بچووک لە دەقە کە لکاوە بە پەیامەکانت',
'Sig preview'					=>	':واژۆی ئێستات',
'No sig'						=>	'هیچ واژۆیەک لە پرۆفایلدا نییە',
'Signature quote/code/list/h'	=>	'چوارچێوە ،لیستەکان ،سەری کۆدەکانی بیبی ڕێگەپێدراو نییە لە واژۆکان',
'Topics per page'				=>	'بابەتەکان',
'Posts per page'				=>	'پەیامەکان',
'Leave blank'					=>	'بە بەتاڵی جێیبێڵە بۆ بەکاربردنی ڕێکخستنی بنچینەیی',
'Subscription legend'			=>	'هەڵبژاردنەکانی بەشداریکردنت دابنێ',
'Notify full'					=>	'وەشانی دەقی نەخشەی پەیامە نوێیەکان لە بەشداریکردن بۆ ئاگاداکردنەوەی ئیمەیڵ',
'Auto notify full'				=>	'خۆکارانە بەشدارمبکە لە هەر بابەتێک کە پەیامم تێدا نارد',
'Show smilies'					=>	'خەندەکان نیشانبدە',
'Show images'					=>	'وێنە لە پەیامەکان نیشانبدە',
'Show images sigs'				=>	'وێنە لە واژۆی بەکارهێنەران نیشانبدە',
'Show avatars'					=>	'وێنۆچکەی بەکارهێنەران نیشانبدە',
'Show sigs'						=>	'واژۆی بەکارهێنەران نیشانبدە',
'Style legend'					=>	'شوازی خوازراوت هەڵبژێرە',
'Styles'						=>	'شێوازەکان',
'Admin note'					=>	'تێبینی بەڕێوەبەر',
'Pagination legend'				=>	'هەڵبژاردنەکانی پەڕگەکردن دابنێ',
'Post display legend'			=>	'هەڵبژاردنەکانی نیشاندانی پەیامەکان دابنێ',
'Post display info'				=>	'ئەگەر هێڵەکەت خاوە ،ناچالاککردنی ئەو هەڵبژاردنانە بە تایبەتی نیشاندانی وێنە لە واژۆ و پەیامەکان بارکردنی پەڕەکان خێراتر دەکات',
'Instructions'					=>	'کاتێک پرۆفایلەکەت نوێدەکەیتەوە ،بۆ ئەو پەڕە دەگەڕێندرێیتەوە',

// Administration stuff
'Group membership legend'		=>	'Choose user group',
'Save'							=>	'Save',
'Set mods legend'				=>	'Set moderator access',
'Moderator in info'				=>	'Choose which forums this user should be allowed to moderate. Note: This only applies to moderators. Administrators always have full permissions in all forums.',
'Update forums'					=>	'Update forums',
'Delete ban legend'				=>	'Delete (administrators only) or ban user',
'Delete user'					=>	'Delete user',
'Ban user'						=>	'Ban user',
'Confirm delete legend'			=>	'Important: read before deleting user',
'Confirm delete user'			=>	'Confirm delete user',
'Confirmation info'				=>	'Please confirm that you want to delete the user', // the username will be appended to this string
'Delete warning'				=>	'Warning! Deleted users and/or posts cannot be restored. If you choose not to delete the posts made by this user, the posts can only be deleted manually at a later time.',
'Delete posts'					=>	'Delete any posts and topics this user has made.',
'Delete'						=>	'Delete', // submit button (confirm user delete)
'User delete redirect'			=>	'User deleted. Redirecting …',
'Group membership redirect'		=>	'Group membership saved. Redirecting …',
'Update forums redirect'		=>	'Forum moderator rights updated. Redirecting …',
'Ban redirect'					=>	'Redirecting …',
'No delete admin message'		=>	'Administrators cannot be deleted. In order to delete this user, you must first move him/her to a different user group.',

);
