<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'گەڕانی بەکارهێنەر',
'No search permission'				=>	'تۆ ناتوانیت گەڕان بەکاربهینیت',
'Search flood'						=>	'چرکە چاوەڕوان بیت لەنێوان گەڕانەکان %s بەلایەنی کەم دەبێ',
'Search'							=>	'گەڕان',
'Search criteria legend'			=>	'بنچیەنەکانی گەڕان بنووسە',
'Search info'						=>	'بۆ گەڕان بە تەختەکلیل ،مەرجێک بنووسە بۆ گەڕان ،مەرجەکان بە مێرگول جیابکەوە',
'Keyword search'					=>	'گەڕانی کلیلەوشە',
'Author search'						=>	'گەڕانی نووسەر',
'Search in legend'					=>	'دەستنیشانبکە لەکوێ بگەڕێ',
'Search in info'					=>	'هەڵبژێرە لەکام مەکۆ ئارەزوو دەکەیت بگەڕێی',
'Search multiple forums info'		=>	'ئەگەر هیچ مەکۆیەکت دیاری نەکردبێت، ئەوە هەموو مەکۆکان دەگەڕێت.',
'Forum search'						=>	'مەکۆ',
'Search in'							=>	'گەڕان لە',
'Message and subject'				=>	'سەردێڕی بابەت و دەقی پەیام',
'Message only'						=>	'تەنها دەقی پەیام',
'Topic only'						=>	'تەنها سەردێڕی بابەت',
'Sort by'							=>	'ڕیزکردن بەپێی',
'Sort order'						=>	'ڕیزکردن فەمانی',
'Search results legend'				=>	'دەستنیشانبکە چۆن ئەنجامەکانی گەڕان نیشانبدرێت',
'Search results info'				=>	'دەتوانی هەڵیبژێری چۆن ئەنجامەکانی گەڕان دەرکەون',
'Sort by post time'					=>	'کاتی ناردن',
'Sort by author'					=>	'نووسەر',
'Sort by subject'					=>	'سەردێڕ',
'Sort by forum'						=>	'مەکۆ',
'Ascending'							=>	'بەرەوژوور',
'Descending'						=>	'بەرەوخوار',
'Show as'							=>	'ئەنجامەکان نیشانبدە وەکو',
'Show as topics'					=>	'بابەتەکان',
'Show as posts'						=>	'پەیامەکان',

// Results
'Search'							=>	'گەڕان',
'Search results'					=>	'ئەنجامی گەڕان',
'Quick search show_new'				=>	'نوێ',
'Quick search show_recent'			=>	'چالاک',
'Quick search show_unanswered'		=>	'وەڵامنەدراو',
'Quick search show_replies'			=>	'نێردراو',
'Quick search show_user_topics'		=>	'%s لەلایەن',
'Quick search show_user_posts'		=>	'%s لەلایەن',
'Quick search show_subscriptions'	=>	'%s بەشداریکراو لەلایەن',
'By keywords show as topics'		=>	'\'%s\' لەگەڵ ئەو پەیامەکانی بە کلیلەووشەی',
'By keywords show as posts'			=>	'\'%s\' لەگەڵ کلیلەووشەی',
'By user show as topics'			=>	'%s لەگەڵ پەیامەکان لەلایەن',
'By user show as posts'				=>	'%s لەلایەن',
'By both show as topics'			=>	'%s لە بابەتەکان لەلایەن \'%s\' لەگەڵ کلیلەووشەی',
'By both show as posts'				=>	'%s لە پەیامەکان لەلایەن \'%s\' لەگەڵ کلیلەووشەی',
'No terms'							=>	'پێویستە بە لایەنی کەم کلیلەووشەیەک بنووسیت یان نووسرێک بۆ گەڕان',
'No hits'							=>	'گەڕانەکەت گەڕایەوە بێ لێدان',
'No user posts'						=>	'هیچ پەیامیک نییە لەلایەن ئەو بەکارهێنەرە',
'No user topics'					=>	'هیچ بابەتیک نییە لەلایەن ئەو بەکارهێنەرە',
'No subscriptions'					=>	'ئەو بەکارهێنەرە لە هیچ بابەتێک بەشدارینەکراوە',
'No new posts'						=>	'هیچ پەیامێکی نوێ نییە لەدوا سەردانتەوە',
'No recent posts'					=>	'هیچ پەیامی نوێ نەنێردراوە لەماوەی ٢٤ کاتژمێری ڕابردوو',
'No unanswered'						=>	'هیچ پەیامێکی وەڵامندەراو نییە لەو مەکۆیە',
'Go to post'						=>	'بڕۆ بۆ پەیام',
'Go to topic'						=>	'بڕۆ بۆ بابەت'

);
