<?php

// Sprachdefinitionen, die in profile.php verwendet werden
$lang_profile = array(

// Navigation und Sektionen
'Profile menu'					=>	'Profilmenü',
'Section essentials'			=>	'Grundlegendes',
'Section personal'				=>	'Persönliches',
'Section messaging'				=>	'Messenger',
'Section personality'			=>	'Personalisierung',
'Section display'				=>	'Anzeige',
'Section privacy'				=>	'Privatsphäre',
'Section admin'					=>	'Administration',

// Verschiedenes
'Username and pass legend'		=>	'Geben Sie hier Ihren Mitgliedsnamen und Ihr Passwort ein',
'Personal details legend'		=>	'Geben Sie hier Ihre persönlichen Angaben ein',
'Contact details legend'		=>	'Ändern oder ergänzen Sie hier Ihre Daten für Instant Messaging',
'User activity'					=>	'Mitgliedsaktivität',
'Paginate info'					=>	'Geben Sie hier die Anzahl von Themen und Beiträgen an, die pro Seite angezeigt werden sollen.',

// Passwort
'Pass key bad'					=>	'Der eingegebene Aktivierungscode war falsch oder ist abgelaufen. Bitte fordern Sie ein neues Passwort an. Falls es weiterhin zu Problemen kommt, kontaktieren Sie bitte die Administration unter',
'Pass updated'					=>	'Ihr Passwort wurde aktualisiert. Sie können sich jetzt mit dem neuen Passwort anmelden.',
'Pass updated redirect'			=>	'Passwort wurde aktualisiert. Leite weiter …',
'Wrong pass'					=>	'Das alte Passwort ist falsch.',
'Change pass'					=>	'Passwort ändern',
'Change pass legend'			=>	'Geben Sie Ihr neues Passwort ein und bestätigen Sie es',
'Old pass'						=>	'Altes Passwort',
'New pass'						=>	'Neues Passwort',
'Confirm new pass'				=>	'Neues Passwort bestätigen',
'Pass info'						=>	'Passwörter müssen mindestens vier Zeichen lang sein. Die Groß-/Kleinschreibung wird unterschieden.',

// E-Mail
'E-Mail key bad'					=>	'Der Aktivierungscode war falsch oder ist abgelaufen. Bitte fordern Sie ein neues Passwort an. Falls es weiterhin zu Problemen kommt, kontaktieren Sie bitte die Administration unter',
'E-Mail updated'					=>	'Ihre E-Mail-Adresse wurde aktualisiert.',
'Activate email sent'			=>	'Es wurde eine E-Mail mit Anweisungen, wie die neue E-Mail-Adresse zu aktivieren ist, an die angegebene E-Mail-Adresse gesandt. Falls keine E-Mail bei Ihnen ankommt, kontaktieren Sie bitte die Administration unter',
'E-Mail legend'					=>	'Geben Sie Ihre neue E-Mail-Adresse ein',
'E-Mail instructions'			=>	'Eine E-Mail mit einem Aktivierungs-Link wird an Ihre neue Adresse gesendet. Sie müssen den Link in dieser E-Mail anklicken, um die neue E-Mail-Adresse zu aktivieren.',
'Change email'					=>	'E-Mail-Adresse ändern',
'New email'						=>	'Neue E-Mail-Adresse',

// Avatar
'Avatars disabled'				=>	'Die Administratoren haben die Verwendung von Avataren deaktiviert.',
'Too large ini'					=>	'Die ausgewählte Datei war zu groß zum Hochladen.',
'Partial upload'				=>	'Die ausgewählte Datei wurde nur teilweise hochgeladen. Bitte versuchen Sie es noch einmal.',
'No tmp directory'				=>	'PHP konnte die hochgeladene Datei nicht speichern.',
'No file'						=>	'Sie haben keine Datei zum Hochladen ausgewählt.',
'Bad type'						=>	'Die ausgewählte Datei hat ein falsches Format. Erlaubte Formate sind gif, jpeg und png.',
'Too wide or high'				=>	'Die ausgewählte Datei ist breiter und/oder höher als maximal erlaubt',
'Too large'						=>	'Die ausgewählte Datei ist größer als maximal erlaubt',
'pixels'						=>	'Pixel',
'bytes'							=>	'Bytes',
'Move failed'					=>	'Der Server konnte die hochgeladene Datei nicht speichern. Bitte benachrichtigen Sie die Administration unter',
'Unknown failure'				=>	'Ein unbekannter Fehler ist aufgetreten. Bitte versuchen Sie es noch einmal.',
'Avatar upload redirect'		=>	'Das Avatar-Bild wurde hochgeladen. Leite weiter …',
'Avatar deleted redirect'		=>	'Das Avatar-Bild wurde gelöscht. Leite weiter …',
'Avatar desc'					=>	'Ein Avatar ist ein kleines Bild, das unter dem Mitgliedsnamen in den Beiträgen angezeigt wird. Avatare dürfen nicht größer sein als',
'Upload avatar'					=>	'Avatar-Bild hochladen',
'Upload avatar legend'			=>	'Geben Sie eine Avatar-Datei zum Hochladen an',
'Delete avatar'					=>	'Avatar-Bild löschen', // nur für Administratoren
'File'							=>	'Datei',
'Upload'						=>	'Hochladen', // Beschriftung des Absende-Buttons

// Formular-Prüfung
'Forbidden title'				=>	'Der eingegebene Titel enthält ein verbotenes Wort. Bitte korrigieren Sie dies.',
'Profile redirect'				=>	'Profil aktualisiert. Leite weiter …',

// Profilanzeige
'Users profile'					=>	'%s\'s Profil',
'Username info'					=>	'Mitgliedsname: %s',
'E-Mail info'					=>	'E-Mail: %s',
'Posts info'					=>	'Beiträge: %s',
'Registered info'				=>	'Registriert: %s',
'Last post info'				=>	'Letzter Beitrag: %s',
'Last visit info'				=>	'Letzter Besuch: %s',
'Show posts'					=>	'Alle Beiträge anzeigen',
'Show topics'					=>	'Alle Themen anzeigen',
'Show subscriptions'			=>	'Alle Abonnements anzeigen',
'Realname'						=>	'Ihr Name',
'Location'						=>	'Wohnort',
'Website'						=>	'Webseite',
'Invalid website URL'			=>	'Die eingetragene Webseiten-Adresse ist ungültig.',
'Website not allowed'  		=>	'Sie dürfen Ihrem Profil noch keine Webseiten-Adresse hinzufügen.',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'MSN Messenger',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'Avatar',
'Signature'						=>	'Signatur',
'Sig max size'					=>	'Maximale Länge: %s Zeichen / Maximale Zeilen: %s',
'Avatar legend'					=>	'Legen Sie hier die Optionen für die Anzeige des Avatar-Bildes fest',
'Avatar info'					=>	'Ein Avatar ist ein kleines Bild, das unter dem Mitgliedsnamen in den Beiträgen angezeigt wird. Sie können über den unten stehenden Link ein eigenes Avatar-Bild hochladen.',
'Change avatar'					=>	'Avatar-Bild ändern',
'Signature legend'				=>	'Stellen Sie hier Ihre Signatur zusammen',
'Signature info'				=>	'Eine Signatur ist ein kurzer Text, der an die Beiträge angehängt wird. Sie dürfen fast alles eingeben, was Sie möchten, z.B. ein Lieblingszitat oder ein Sternzeichen. Sie können BBCode in der Signatur benutzen, wenn die Administration es in diesem Forum erlaubt hat. Die erlaubten Möglichkeiten werden unterhalb der Eingabebox angezeigt.',
'Sig preview'					=>	'Aktuelle Signatur-Vorschau:',
'No sig'						=>	'Derzeit keine Signatur im Profil gespeichert.',
'Signature quote/code/list/h'	=>	'Die BBCodes für Zitate, Code, Listen und überschriften sind in den Signaturen nicht erlaubt.',
'Topics per page'				=>	'Themen pro Seite',
'Posts per page'				=>	'Beiträge pro Seite',
'Leave blank'					=>	'Um die Standardeinstellung zu verwenden, lassen Sie die Eingabefelder leer.',
'Subscription legend'			=>	'Setzen Sie hier die Optionen für Ihre Abonnements',
'Notify full'					=>	'Den neuen Beitrag als einfachen Text mit der Benachrichtigungs-E-Mail versenden.',
'Auto notify full'				=>	'Automatisch per E-Mail benachrichtigen, wenn jemand auf ein Thema oder einen Beitrag von Ihnen geantwortet hat.',
'Show smilies'					=>	'Smilies als Bilder anzeigen',
'Show images'					=>	'Bilder in Beiträgen anzeigen.',
'Show images sigs'				=>	'Bilder in den Mitglieder-Signaturen anzeigen.',
'Show avatars'					=>	'Avatar-Bilder in Beiträgen anzeigen.',
'Show sigs'						=>	'Mitglieder-Signaturen anzeigen.',
'Style legend'					=>	'Stellen Sie hier das gewünschte Forum-Design ein',
'Styles'						=>	'Styles',
'Admin note'					=>	'Administratoren-Notiz',
'Pagination legend'				=>	'Geben Sie hier Ihre Optionen für die Seiten-Paginierung ein',
'Post display legend'			=>	'Legen Sie Ihre Optionen für die Anzeige von Beiträgen fest',
'Post display info'				=>	'Wenn Sie eine langsame Internetverbindung haben, deaktivieren Sie diese Optionen (insbesondere die Anzeige von Bildern in Beiträgen und Signaturen). Das macht das Laden der Seiten schneller.',
'Instructions'					=>	'Wenn Sie Ihr Profil ändern, werden Sie auf diese Seite weitergeleitet.',

// Administration stuff
'Group membership legend'		=>	'Wählen Sie eine Mitgliedergruppe',
'Save'							=>	'Speichern',
'Set mods legend'				=>	'Legen Sie die Moderatoren-Berechtigungen fest',
'Moderator in info'				=>	'Wählen Sie die Foren aus, die dieses Mitglied moderieren darf. Achtung: Dies hat nur Auswirkungen auf Moderatoren. Administratoren haben immer alle Berechtigungen in allen Foren.',
'Update forums'					=>	'Moderatoren-Berechtigungen aktualisieren',
'Delete ban legend'				=>	'Mitglieder löschen (nur Administratoren) oder sperren',
'Delete user'					=>	'Mitglied löschen',
'Ban user'						=>	'Mitglied sperren',
'Confirm delete legend'			=>	'Wichtig: Lesen Sie das, bevor Sie ein Mitglied löschen',
'Confirm delete user'			=>	'Löschen des Mitglied bestätigen',
'Confirmation info'				=>	'Bitte bestätigen Sie, dass Sie das folgende Mitglied löschen wollen:', // Der Name des Mitglieds wird dieser Zeichenkette angehangen
'Delete warning'				=>	'Warnung! Gelöschte Mitglieder und/oder Beiträge können NICHT wieder hergestellt werden. Wenn Sie die Beiträge dieses Mitglieds nicht löschen, können diese später nur noch manuell gelöscht werden.',
'Delete posts'					=>	'Alle Beiträge und Themen dieses Mitglieds löschen.',
'Delete'						=>	'Löschen', // Beschriftung des Absende-Buttons (Bestätigung der Mitgliederlöschung)
'User delete redirect'			=>	'Mitglied gelöscht. Leite weiter …',
'Group membership redirect'		=>	'Gruppenmitgliedschaft gespeichert. Leite weiter  …',
'Update forums redirect'		=>	'Moderatorenrechte aktualisiert. Leite weiter …',
'Ban redirect'					=>	'Leite weiter …',
'No delete admin message'		=>	'Administratoren können nicht gelöscht werden. Um dieses Mitlgied löschen zu können, muss es zunächst einer anderen Mitgliedergruppe zugeordnet werden.',

);
