<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'سیستم قادر به بررسی بروزرسانی نمیباشد زیرا \'allow_url_fopen\' بر روی این سیستم غیرفعال میباشد.',
'Upgrade check failed message'		=>	'بدلایل نامشخصی بررسی جهت بروزرسانی با شکست روبرو شد.',
'Running latest version message'	=>	'شما در حال اجرای آخرین نسخه FluxBB میباشید.',
'New version available message'		=>	'نسخه جدیدی از FluxBB منتشر شده است . شما میتوانید جدیدترین نسخه را از %s دانلود کنید.',
'Deleted install.php redirect'		=>	'فایل با موفقیت حذف شد. درحال تغییر مسیر …',
'Delete install.php failed'			=>	'سیستم قادر به حذف install.php نمیباشد . لطفاً بصورت دستی اینکار را انجام دهید.',
'Not available'						=>	'در دسترس نیست',
'Forum admin head'					=>	'مدیریت انجمن',
'NA'								=>	'در دسترس نیست',
'Welcome to admin'					=>	'به کنترل پنل مدیریت FluxBB خوش آمدید . از اینجا میتوانید جنبه های اساسی تالارگفتگو را کنترل کنید . بسته به اینکه آیا شما مدیراصلی و یا مدیرانجمن هستید کنترل ها متفاوت میباشند:',
'Welcome 1'							=>	'سازماندهی مجموعه و انجمن ها.',
'Welcome 2'							=>	'تنظیم گزینه ها و اولویت های انجمن.',
'Welcome 3'							=>	'کنترل مجوزها برای کاربران انجمن و کاربران مهمان.',
'Welcome 4'							=>	'مشاهده آمار IP برای کاربران مهمان.',
'Welcome 5'							=>	'کاربران محروم.',
'Welcome 6'							=>	'سانسور کلمات.',
'Welcome 7'							=>	'تنظیم کردن گروه های کاربری و ارتقاء کاربران.',
'Welcome 8'							=>	'هرس ارسال های قدیمی.',
'Welcome 9'							=>	'رسیدگی به ارسال گزارش ها.',
'Alerts head'						=>	'هشدارها',
'Install file exists'				=>	'فایل install.php هنوز وجود دارد ، ولی باید آن را حذف کنید. %s.',
'Delete install file'				=>	'حذف شود',
'About head'						=>	'درباره FluxBB',
'FluxBB version label'				=>	'نسخه FluxBB',
'Check for upgrade'					=>	'بررسی جهت بروزرسانی',
'FluxBB version data'				=>	'نسخه %s - %s',
'Server statistics label'			=>	'آمار سرور',
'View server statistics'			=>	'مشاهده آمار سرور',
'Support label'						=>	'پشتیبانی',
'Forum label'						=>	'انجمن',
'IRC label'							=>	'کانال IRC',

// Language definitions used in admin_statistics.php
'PHPinfo disabled message'			=>	'تابع phpinfo() در PHP بر روی این سرور غیرفعال میباشد.',
'Server statistics head'			=>	'آمار سرور',
'Server load label'					=>	'بار سرور',
'Server load data'					=>	'%s - %s کاربر آنلاین',
'Environment label'					=>	'محیط',
'Environment data OS'				=>	'سیستم عامل: %s',
'Show info'							=>	'نمایش اطلاعات',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'شتبا دهنده: %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'شتاب دهنده ionCube PHP',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'بهینه ساز Zend',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'پایگاه داده',
'Database data rows'				=>	'ردیف: %s',
'Database data size'				=>	'حجم: %s',
);
