<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'سیستم تا زمان فعال بودن \'allow_url_fopen\'قادر به چک کردن برای نسخه جدید برای به روزآوری انجمن نمی باشد.',
'Upgrade check failed message'		=>	'چک کردن برای به روز کردن نرم افزار انجمن به دلیل نامعلوم با شکست مواجه شد.',
'Running latest version message'	=>	'شما در حال استفاده از آخرین نسخه FluxBB می‌باشید.',
'New version available message'		=>	'نسخه جدید FluxBB منتشر شده است. شما می توانید آنرا از %s دانلود کنید.',
'PHPinfo disabled message'			=>	'تابع phpinfo() در مفسر PHP بر روی سرور غیر فعال است.',
'Not available'						=>	'در دسترس نیست',
'Forum admin head'					=>	'مدیریت انجمن',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'به بخش مدیریت انجمن FluxBB خوش آمدید. از طریق این پنل شما قادر خواهید به تمامی بخش‌های انجمن و زیر مجموعه‌های آن دسترسی داشته باشید و هر آنچه که می خواهید را مدیریت کنید. تنها کافیست نگاهی به منوی کنار صفحه بیاندازید.',
'Welcome 1'							=>	'مدیریت بخش‌ها و انجمن‌ها.',
'Welcome 2'							=>	'تنظیمات و گزینه های کلی انجمن.',
'Welcome 3'							=>	'کنترل دسترسی ها برای کاربران و میهمانان.',
'Welcome 4'							=>	'نمایش گزارشات IP برای کاربران.',
'Welcome 5'							=>	'مسدود کردن کاربران.',
'Welcome 6'							=>	'سانسور کلمات.',
'Welcome 7'							=>	'تنظیم امتیاز کاربران.',
'Welcome 8'							=>	'هرس کردن ارسال های قدیمی.',
'Welcome 9'							=>	'هندل کردن گزارشات ارسال ها.',
'Statistics head'					=>	'آمار و گزارشات',
'FluxBB version label'				=>	'نسخه FluxBB',
'Check for upgrade'					=>	'چک کردن برای به روز رسانی',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'لود سرور',
'Server load data'					=>	'%s - %s کاربر آنلاین',
'Environment label'					=>	'محیط',
'Environment data OS'				=>	'سیستم عامل: %s',
'Show info'							=>	'نمایش مشخصات',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'شتاب دهنده: %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'پایگاه داده',
'Database data rows'				=>	'ردیف: %s',
'Database data size'				=>	'سایز: %s',

);
