<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'		=>	'کاربری با این نام ثبت نام نکرده است.',
'No user ID message'		=>	'کاربری با این ID به ثبت نرسیده است.',
'User is admin message'		=>	'کاربر %s مدیریت انجمن را بر عهده دارد و نمی توان آنرا مسدود کرد. اگر می خواهید یک مدیر را مسدود کنید ابتدا باید دسترسی های مدیریتی او را حذف کنید.',
'User is mod message'		=>	'کاربر %s مدیریت انجمن را بر عهده دارد و نمی توان آنرا مسدود کرد. اگر می خواهید یک مدیر را مسدود کنید ابتدا باید دسترسی های مدیریتی او را حذف کنید',
'Must enter message'		=>	'شما باید هم نام کاربری و هم آدرس IP را وارد کنید. در غیر این صورت حداقل باید آدرس پست الکترونیکی کاربر را وارد کنید',
'Cannot ban guest message'	=>	'کاربر میهمان قابل مسدود کردن نمی باشد.',
'Invalid IP message'		=>	'آدرس IP یا بازه IP وارد شده معتبر نمی باشد.',
'Invalid e-mail message'	=>	'شما باید آدرس ایمیل کامل یا بخشی از آدرس ایمیل کاربر را وارد کنید. اینی که شما وارد کرده اید اشتباه است.',
'Invalid date message'		=>	'شما تاریخ انقضای اشتباه وارد کرده اید.',
'Invalid date reasons'		=>	'ساختار تاریخ باید به صورت YYYY-MM-DD باشد و همچنین تاریخ وارد شده باید حداقل ۱ روز از تاریخ فعلی جلوتر باشد.',
'Ban added redirect'		=>	'درخواست انسداد ارسال شد. در حال انتقال …' ,
'Ban edited redirect'		=>	'درخواست انسداد ویرایش شد. در حال انتقال …',
'Ban removed redirect'		=>	'درخواست انسداد حذف شذ. در حال انتقال …',

'New ban head'				=>	'درخواست جدید انسداد',
'Add ban subhead'			=>	'ایجاد انسداد',
'Username label'			=>	'نام کاربری',
'Username help'				=>	'مسدود کردن کاربر.',
'Username advanced help'	=>	'نام کاربری برای مسدود کردن. در صفحه بعدی به شما اجازه داده خواهد شد که آدرس ایمیل یا IP خاص را وارد کنید. اگر می خواهید IP خاص یا بازه ای از IP را وارد کنید فیلد را خالی بگذارید..',
'Ban search head'			=>	'جستجوی مسدود شده ها',
'Ban search subhead'		=>	'مورد قابل جستجو را وارد کنید',
'Ban search info'			=>	'جستجو برای کاربران مسدود شده در بانک اطلاعاتی.',
'Date help'					=>	'(yyyy-mm-dd)',
'Message label'				=>	'پیام',
'Expire after label'		=>	'منقضی بعد از',
'Expire before label'		=>	'منقضی قبل از',
'Order by label'			=>	'سفارش شده توسط',
'Order by username'			=>	'نام کاربری',
'Order by ip'				=>	'آدرس IP',
'Order by e-mail'			=>	'ایمیل',
'Order by expire'			=>	'تاریخ مسدود کردن',
'Ascending'					=>	'صعودی',
'Descending'				=>	'نزولی',
'Submit search'				=>	'ثبت جستجو',

'E-mail label'				=>	'آدرس ایمیل',
'E-mail help'				=>	'مسدود کردن آدرس ایمیل یا آدرس ایمیل های یک دامین (مثلا someone@somewhere.com یا somewhere.com).',
'IP label'					=>	'آدرس IP/ بازه IP',
'IP help'					=>	'آدرس IP یا بازه ای از IP هایی که می خواهید مسدود کنید. (مثلا 150.11.110.1 یا 150.11.110). آدرسهارا با فاصله از هم جدا کنید.',
'IP help link'				=>	'Click %s to see IP statistics for this user.',
'Ban advanced head'			=>	'تنظیمات پیشرفته مسدود کردن کاربر',
'Ban advanced subhead'		=>	'اضافه کردن IP و آدرس ایمیل برای مسدود کردن کاربر',
'Ban message label'			=>	'پیام برای کاربر مسدود شده',
'Ban message help'			=>	'پیامی که به کاربر پس از مسدود شدن حساب کاربری و بعد از ورودبه انجمن برای او نمایش داده خواهد شد.',
'Message expiry subhead'	=>	'پیام انسداد و انقاضای آن برای کاربر',
'Ban IP range info'			=>	'شما باید با دقت زیاد بازه ای از ّIPها را مسدود کنید. چون ممکن است ناخواسته کاربران دیگری هم مسدود کنید.',
'Expire date label'			=>	'تاریخ انقضا',
'Expire date help'			=>	'تاریخی که انسداد کاربر از انجمن حذف خواهد شد (قالب: yyyy-mm-dd). اگر می خواهید انسداد کاربر را دستی حدف کنید این فیلد را خالی بگذارید.',

'Results head'				=>	'نتایج جستجو',
'Results username head'		=>	'نام کاربری',
'Results e-mail head'		=>	'آدرس ایمیل',
'Results IP address head'	=>	'آدرس IP/ بازه IP',
'Results expire head'		=>	'منقضی می‌شود',
'Results message head'		=>	'پیام',
'Results banned by head'	=>	'مسدود شده توسط',
'Results actions head'		=>	'اقدامات',
'No match'					=>	'چیزی با انتخاب های شما پیدا نشد',
'Unknown'					=>	'ناشناس/نامشخص',

);
