<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'آدرس ایمیل معتبری را وارد کنید',
'Email legend 2'			=>	'آدرس ایمیل معتبری را وارد و تائید کنید',
'Localisation legend'		=>	'گزینه های بومی سازی خود را تنظیم کنید',
'Time zone'					=>	'منطقه زمانی',
'Time zone info'			=>	'برای اینکه انجمن زمان را بدرستی نمایش دهد شما باید منطقه زمانی محلی خود را به درستی انتخاب کنید . اگر ساعت تابستانی در زمان شما تاثیر دارد شما باید گزینه ارائه شده برای پیشرفت 1 ساعته زمان را تیک بزنید.',
'DST'						=>	'ساعت تابستانی تاثیرگذار است ( پیبشرفت زمان 1 ساعت ).',
'Time format'				=>	'فرمت زمان',
'Date format'				=>	'فرمت تاریخ',
'Default'					=>	'پیش‌فرض',
'Language'					=>	'زبان',
'Email setting info'		=>	'انتخاب کنید آیا آدرس ایمیل شما قابل مشاهده توسط دیگر کاربران باشید یا خیر و همچنین آیا مایل هستید دیگر کاربران قادر باشند از طریق انجمن ( فرم ایمیل ) برای شما ایمیل ارسال کنند یا خیر.',
'Email setting 1'			=>	'نمایش ایمیل شما به کاربران دیگر.',
'Email setting 2'			=>	'عدم نمایش آدرس ایمیل ولی اجازه برای ارسال ایمیل از طریق انجمن.',
'Email setting 3'			=>	'عدم نمایش آدرس ایمیل واجازه ندادن برای ارسال ایمیل از طریق انجمن.',
'Privacy options legend'	=>	'گزینه های حریم خصوصی خود را تنظیم کنید',
'Confirm pass'				=>	'تائید کلمه عبور',

'Username too short'		=>	'نام کاربری باید حداقل بیشتر از 2 کاراکتر باشد . لطفاً نام کاربری (بلندتر) دیگری انتخاب کنید.',
'Username too long'			=>	'نام کاربری نباید بیشتر از 25 کاراکتر باشد . لطفاً نام کاربری (کوتاهتر) دیگری انتخاب کنید.',
'Username guest'			=>	'نام کاربری guest رزرو شده است . لطفاً نام کاربری دیگری انتخاب کنید.',
'Username IP'				=>	'نام کاربری نباید شبیه یک آدرس IP باشد . لطفاً نام کاربری دیگری انتخاب کنید.',
'Username reserved chars'	=>	'نام کاربری نمیتواند شامل کاراکترهای \'، " و ] یا   [ باشد. لطفاً نام کاربری دیگری انتخاب کنید.',
'Username BBCode'			=>	'نام کاربری نباید شامل هر یک از فرمتهای تگ (BBCode) که انجمن از آن استفاده میکند باشد . لطفاً نام کاربری دیگری انتخاب کنید.',
'Banned username'			=>	'نام کاربری که وارد کرده اید در این انجمن مسدود میباشد . لطفاً نام کاربری دیگری را انتخاب کنید.',
'Pass too short'			=>	'کلمه عبور باید حداقل 6 کاراکتر باشد . لطفاً کلمه عبور (بلندتر) دیگری را انتخاب کنید.',
'Pass not match'			=>	'کلمه عبور ها با هم مطابقت ندارند.',
'Banned email'				=>	'آدرس ایمیلی که شما وارد کرده اید در این انجمن مسدود میباشد . لطفاً آدرس ایمیل دیگری را انتخاب کنید.',
'Dupe email'				=>	'شخص دیگری هم اکنون با این آدرس ایمیل ثبت نام کرده است . لطفاً آدرس ایمیل دیگری را انتخاب کنید.',
'Sig too long'				=>	'متن امضاء نمیتواند بیشتر از %1$s کاراکتر طولانی تر باشد . لطفاً %2$s کاراکتر از متن امضاء خود کاهش دهید.',
'Sig too many lines'		=>	'امضاء نیمتواند بیشتر از %s خط داشته باشد.',
'Bad ICQ'					=>	'شما ICQ UIN نامعتبری را وارد کرده اید . لطفاً بازگشته و آن را تصحیح کنید.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Moscow, Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Yekaterinburg',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Krasnoyarsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita, Irkutsk',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Vladivostok',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Magadan',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands, Kamchatka',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
