<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'یک آدرس ایمیل معتبر وارد کنید',
'Email legend 2'			=>	'یک ایمیل معتبر وارد و تایید کنید',
'Localisation legend'		=>	'تنظیمات محلی خود را تنظیم کنید',
'Time zone'					=>	'منطقه زمانی',
'Time zone info'			=>	'جهت نمایش صحیح زمان ها در تالار، شما باید منطقه زمانی محلی خود را انتخاب کنید. اگر تغییر یک ساعته مبتنی بر آفتاب در جریان است، شما باید گزینه مربوط به آن را علامت بزنید که موجب می شود ساعت ها یک ساعت به جلو کشیده شوند.',
'DST'						=>	'تغییر یک ساعته مبتنی بر آفتاب فعال است( زمان یک ساعت به جلو برده می شود)',
'Time format'				=>	'قالب زمان',
'Date format'				=>	'قالب تاریخ',
'Default'					=>	'پیش فرض',
'Language'					=>	'زبان',
'Email setting info'		=>	'انتخاب اینکه ایمیل شما برای دیگر کاربران قابل مشاهده باشد یا نه و همچنین اینکه دیگر کاربران بتوانند برای شما ایمیل بفرستند یا خیر؟.',
'Email setting 1'			=>	'آدرس ایمیل من را نشان بده.',
'Email setting 2'			=>	'آدرس من را مخفی کن اما اجازه بده برایم ایمیل بفرستند.',
'Email setting 3'			=>	'آدرس من را مخفی کن و اجازه نده برایم ایمیل بفرستند.',
'Privacy options legend'	=>	'گزینه های امنیتی خود را تنظیم کنید',
'Confirm pass'				=>	'تکرار رمزعبور',

'Username too short'		=>	'طول نام کاربری بایستی حداقل 2 نویسه باشد. لطفا نام کاربری  دیگری(طولانی تر) انتخاب کنید.',
'Username too long'			=>	'Usernames must not be more than 25 characters long. Please choose another (shorter) username.',
'Username guest'			=>	'The username guest is reserved. Please choose another username.',
'Username IP'				=>	'Usernames may not be in the form of an IP address. Please choose another username.',
'Username reserved chars'	=>	'Usernames may not contain all the characters \', " and [ or ] at once. Please choose another username.',
'Username BBCode'			=>	'Usernames may not contain any of the text formatting tags (BBCode) that the forum uses. Please choose another username.',
'Banned username'			=>	'The username you entered is banned in this forum. Please choose another username.',
'Pass too short'			=>	'Passwords must be at least 4 characters long. Please choose another (longer) password.',
'Pass not match'			=>	'رمزهای عبور با هم مطابق نیستند.',
'Banned email'				=>	'The email address you entered is banned in this forum. Please choose another email address.',
'Dupe email'				=>	'Someone else is already registered with that email address. Please choose another email address.',
'Sig too long'				=>	'Signatures cannot be longer than %1$s characters. Please reduce your signature by %2$s characters.',
'Sig too many lines'		=>	'Signatures cannot have more than %s lines.',
'Bad ICQ'					=>	'You entered an invalid ICQ UIN. Please go back and correct.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Moscow, Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Yekaterinburg',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Krasnoyarsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita, Irkutsk',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Vladivostok',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Magadan',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands, Kamchatka',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
