<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'منوی پروفایل',
'Section essentials'			=>	'Essentials',
'Section personal'				=>	'شخصی',
'Section messaging'				=>	'پیام رسانی',
'Section personality'			=>	'Personality',
'Section display'				=>	'نمایش',
'Section privacy'				=>	'امنیت',
'Section admin'					=>	'مدیریت',

// Miscellaneous
'Username and pass legend'		=>	'نام کاربری و رمزعبور خود را وارد کنید',
'Personal details legend'		=>	'جزییات شخصی خود را وارد کنید',
'Contact details legend'		=>	'جزییات پیام رسانی خود را مشخص کنید',
'User activity'					=>	'فعالیت کاربر',
'Paginate info'					=>	'تعداد مباحث و مطالبی که دوست دارید در هر صفحه مشاهده کنید را وارد کنید.',

// Password stuff
'Pass key bad'					=>	'The specified password activation key was incorrect or has expired. Please re-request a new password. If that fails, contact the forum administrator at',
'Pass updated'					=>	'رمز عبور شما به روزرسانی شده است. اکنون می توانید با رمز عبور جدید وارد شوید.',
'Pass updated redirect'			=>	'رمز عبور به روزرسانی شد. در حال هدایت به صفحه مورد نظر …',
'Wrong pass'					=>	'رمز قبلی اشتباه است.',
'Change pass'					=>	'تغییر رمزعبور',
'Change pass legend'			=>	'رمزعبور جدید خود را وارد و تایید(تکرار) کنید',
'Old pass'						=>	'رمزعبور قبلی',
'New pass'						=>	'رمزعبور جدید',
'Confirm new pass'				=>	'تکرار رمزعبور جدید',
'Pass info'						=>	'طول رمزعبور بایستی حداقل 4 نویسه باشد. رمز عبور برای حروف کوچک و بزرگ تفاوت قائل است .',

// Email stuff
'Email key bad'					=>	'The specified email activation key was incorrect or has expired. Please re-request change of email address. If that fails, contact the forum administrator at',
'Email updated'					=>	'Your email address has been updated.',
'Activate email sent'			=>	'An email has been sent to the specified address with instructions on how to activate the new email address. If it doesn\'t arrive you can contact the forum administrator at',
'Email legend'					=>	'آدرس ایمیل جدید خود را وارد کنید',
'Email instructions'			=>	'An email will be sent to your new address with an activation link. You must click the link in the email you receive to activate the new address.',
'Change email'					=>	'تغییر آدرس جدید',
'New email'						=>	'ایمیل جدید',

// Avatar upload stuff
'Avatars disabled'				=>	'The administrator has disabled avatar support.',
'Too large ini'					=>	'The selected file was too large to upload. The server didn\'t allow the upload.',
'Partial upload'				=>	'The selected file was only partially uploaded. Please try again.',
'No tmp directory'				=>	'PHP was unable to save the uploaded file to a temporary location.',
'No file'						=>	'You did not select a file for upload.',
'Bad type'						=>	'The file you tried to upload is not of an allowed type. Allowed types are gif, jpeg and png.',
'Too wide or high'				=>	'The file you tried to upload is wider and/or higher than the maximum allowed',
'Too large'						=>	'The file you tried to upload is larger than the maximum allowed',
'pixels'						=>	'پیکسل',
'bytes'							=>	'بایت',
'Move failed'					=>	'The server was unable to save the uploaded file. Please contact the forum administrator at',
'Unknown failure'				=>	'An unknown error occurred. Please try again.',
'Avatar upload redirect'		=>	'Avatar uploaded. Redirecting …',
'Avatar deleted redirect'		=>	'Avatar deleted. Redirecting …',
'Avatar desc'					=>	'An avatar is a small image that will be displayed under your username in your posts. It must not be any bigger than',
'Upload avatar'					=>	'ارسال نمایه',
'Upload avatar legend'			=>	'یک فایل نمایه را جهت ارسال مشخص کنید',
'Delete avatar'					=>	'حذف نمایه', // only for admins
'File'							=>	'فایل',
'Upload'						=>	'ارسال', // submit button

// Form validation stuff
'Forbidden title'				=>	'The title you entered contains a forbidden word. You must choose a different title.',
'Profile redirect'				=>	'Profile updated. Redirecting …',

// Profile display stuff
'Users profile'					=>	'%s\'s profile',
'Username info'					=>	'نام کاربری: %s',
'Email info'					=>	'ایمیل: %s',
'Posts info'					=>	'مطالب: %s',
'Registered info'				=>	'ثبت نام شده: %s',
'Last post info'				=>	'آخرین مطلب: %s',
'Last visit info'				=>	'آخرین مراجعه: %s',
'Show posts'					=>	'نمایش همه مطالب',
'Show topics'					=>	'نمایش همه مباحث',
'Show subscriptions'			=>	'نمایش همه اشتراک ها',
'Realname'						=>	'نام واقعی',
'Location'						=>	'موقعیت',
'Website'						=>	'سایت',
'Invalid website URL'			=>	'The website URL you entered is invalid.',
'Website not allowed'			=>	'You are not allowed to add a website to your profile yet.',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'MSN Messenger',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'نمایه',
'Signature'						=>	'امضا',
'Sig max size'					=>	'حداکثر طول: %s نویسه / حداکثر خطوط: %s',
'Avatar legend'					=>	'گزینه های نمایش نمایه خود را تنظیم کنید',
'Avatar info'					=>	'An avatar is a small image that will be displayed with all your posts. You can upload an avatar by clicking the link below.',
'Change avatar'					=>	'تغییر نمایه',
'Signature legend'				=>	'ساختن امضای شما',
'Signature info'				=>	'A signature is a small piece of text that is attached to your posts. In it, you can enter just about anything you like. Perhaps you would like to enter your favourite quote or your star sign. It\'s up to you! In your signature you can use BBCode if it is allowed in this particular forum. You can see the features that are allowed/enabled listed below whenever you edit your signature.',
'Sig preview'					=>	'پیش نمایش امضای فعلی:',
'No sig'						=>	'No signature currently stored in profile.',
'Signature quote/code/list/h'	=>	'The quote, code, list, and heading BBCodes are not allowed in signatures.',
'Topics per page'				=>	'مباحث',
'Posts per page'				=>	'مطالب',
'Leave blank'					=>	'Leave blank to use forum default.',
'Subscription legend'			=>	'Set your subscription options',
'Notify full'					=>	'Include a plain text version of new posts in subscription notification emails.',
'Auto notify full'				=>	'Automatically subscribe to every topic you post in.',
'Show smilies'					=>	'Show smilies as graphic icons.',
'Show images'					=>	'Show images in posts.',
'Show images sigs'				=>	'Show images in user signatures.',
'Show avatars'					=>	'Show user avatars in posts.',
'Show sigs'						=>	'Show user signatures.',
'Style legend'					=>	'Select your preferred style',
'Styles'						=>	'سبک ها',
'Admin note'					=>	'یادداشت مدیر',
'Pagination legend'				=>	'Enter your pagination options',
'Post display legend'			=>	'Set your options for viewing posts',
'Post display info'				=>	'If you are on a slow connection, disabling these options, particularly showing images in posts and signatures, will make pages load faster.',
'Instructions'					=>	'When you update your profile, you will be redirected back to this page.',

// Administration stuff
'Group membership legend'		=>	'گروه کاربری را انتخاب کنید',
'Save'							=>	'ذخیره',
'Set mods legend'				=>	'Set moderator access',
'Moderator in info'				=>	'Choose which forums this user should be allowed to moderate. Note: This only applies to moderators. Administrators always have full permissions in all forums.',
'Update forums'					=>	'به روزرسانی تالارها',
'Delete ban legend'				=>	'Delete (administrators only) or ban user',
'Delete user'					=>	'حذف کاربر',
'Ban user'						=>	'قطع دسترسی کاربر',
'Confirm delete legend'			=>	'Important: read before deleting user',
'Confirm delete user'			=>	'تایید حذف کاربر',
'Confirmation info'				=>	'Please confirm that you want to delete the user', // the username will be appended to this string
'Delete warning'				=>	'Warning! Deleted users and/or posts cannot be restored. If you choose not to delete the posts made by this user, the posts can only be deleted manually at a later time.',
'Delete posts'					=>	'Delete any posts and topics this user has made.',
'Delete'						=>	'حذف', // submit button (confirm user delete)
'User delete redirect'			=>	'User deleted. Redirecting …',
'Group membership redirect'		=>	'Group membership saved. Redirecting …',
'Update forums redirect'		=>	'Forum moderator rights updated. Redirecting …',
'Ban redirect'					=>	'در حال انتقال …',
'No delete admin message'		=>	'Administrators cannot be deleted. In order to delete this user, you must first move him/her to a different user group.',

);
