<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'جستجوی کاربران',
'No search permission'				=>	'You do not have permission to use the search feature.',
'Search flood'						=>	'At least %s seconds have to pass between searches. Please wait a while and try searching again.',
'Search'							=>	'جستجو',
'Search criteria legend'			=>	'معیار جستجوی خود را وارد کنید',
'Search info'						=>	'To search by keyword, enter a term or terms to search for. Separate terms with spaces. Use AND, OR and NOT to refine your search. To search by author enter the username of the author whose posts you wish to search for. Use wildcard character * for partial matches.',
'Keyword search'					=>	'جستجوی کلمات کلیدی',
'Author search'						=>	'جستجوی نویسنده',
'Search in legend'					=>	'انتخاب محل جستجو',
'Search in info'					=>	'Choose in which forum you would like to search and if you want to search in topic subjects, message text or both.',
'Search multiple forums info'		=>	'If no forums are selected, all forums will be searched.',
'Forum search'						=>	'تالار',
'All forums'						=>	'همه تالارها',
'Search in'							=>	'جستجو در',
'Message and subject'				=>	'Message text and topic subject',
'Message only'						=>	'Message text only',
'Topic only'						=>	'Topic subject only',
'Sort by'							=>	'مرتب کردن با',
'Sort order'						=>	'Sort order',
'Search results legend'				=>	'Select how to view search results',
'Search results info'				=>	'You can choose how you wish to sort and show your results.',
'Sort by post time'					=>	'Post time',
'Sort by author'					=>	'نویسنده',
'Sort by subject'					=>	'موضوع',
'Sort by forum'						=>	'تالار',
'Ascending'							=>	'صعودی',
'Descending'						=>	'نزولی',
'Show as'							=>	'نمایش نتایج به عنوان',
'Show as topics'					=>	'مباحث',
'Show as posts'						=>	'مطالب',

// Results
'Search'							=>	'جستجو',
'Search results'					=>	'نتایج جستجو',
'Quick search show_new'				=>	'جدید',
'Quick search show_recent'			=>	'فعال',
'Quick search show_unanswered'		=>	'بی پاسخ',
'Quick search show_replies'			=>	'ارسال شده',
'Quick search show_user_topics'		=>	'مباحث مطرح شده توسط %s',
'Quick search show_user_posts'		=>	'مطالب ارسال شده توسط %s',
'Quick search show_subscriptions'	=>	'مطالب تحت نظر گرفته شده توسط %s',
'By keywords show as topics'		=>	'مباحث شامل مطالبی حاوی \'%s\'',
'By keywords show as posts'			=>	'مطالب حاوی \'%s\'',
'By user show as topics'			=>	'Topics with posts by %s',
'By user show as posts'				=>	'مطالب ارسالی توسط %s',
'By both show as topics'			=>	'Topics with posts containing \'%s\', by %s',
'By both show as posts'				=>	'Posts containing \'%s\', by %s',
'No terms'							=>	'You have to enter at least one keyword and/or an author to search for.',
'No hits'							=>	'Your search returned no hits.',
'No user posts'						=>	'There are no posts by this user in this forum.',
'No user topics'					=>	'There are no topics by this user in this forum.',
'No subscriptions'					=>	'This user is currently not subscribed to any topics.',
'No new posts'						=>	'There are no topics with new posts since your last visit.',
'No recent posts'					=>	'No new posts have been made within the last 24 hours.',
'No unanswered'						=>	'There are no unanswered posts in this forum.',
'Go to post'						=>	'Go to post',
'Go to topic'						=>	'Go to topic'

);
