<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'جستجوی کاربر',
'No search permission'				=>	'شما مجوز استفاده از ویژگی جستجو را ندارید.',
'Search flood'						=>	'حداقل باید %s ثانیه بین جستجو ها گذشته باشد . لطفاً %s ثانیه صبر کرده و دوباره تلاش کرد.',
'Search'							=>	'جستجو',
'Search criteria legend'			=>	'کلمات برای جستجو را وارد کنید',
'Search info'						=>	'برای جستجو بر اساس کلمات . یک شرط یا چند شرط را برای جستجو وارد کنید . آنها را با فضای خالی از هم جدا کنید . از "و" ، "یا" برای فیلتر کردن جستجوی خود استفاده کنید . برای جستجو بر اساس نویسنده نام کاربری نویسنده ای که به دنبال ارسال هایش هستید را وارد کنید . برای مطابقت جزئی از کلمات میتوانید از کاراکتر <strong>*</strong> ستاره استفاده کنید.',
'Keyword search'					=>	'جستجوی کلمات',
'Author search'						=>	'جستجوی نویسنده',
'Search in legend'					=>	'انتخاب کنید کجا جستجو شود',
'Search in info'					=>	'انتخاب کرده در چه انجمنی مایل هستید جستجو انجام شود و آیا جستجو بین عنوان موضوع، متن ارسال و یا هر دو مورد انجام گردد .',
'Search multiple forums info'		=>	'اگر هیچ انجمنی انتخاب نشود ، تمام انجمن ها جستجو خواهند شد.',
'Forum search'						=>	'انجمن',
'Search in'							=>	'جستجو در',
'Message and subject'				=>	'عنوان موضوع و متن ارسال',
'Message only'						=>	'فقط متن ارسال',
'Topic only'						=>	'فقط عنوان موضوع',
'Sort by'							=>	'مرتب سازی براساس',
'Sort order'						=>	'ترتیب مرتب سازی',
'Search results legend'				=>	'انتخاب چگونگی نمایش نتایج جستجو',
'Search results info'				=>	'انتخاب چگونگی مرتب سازی و نمایش نتایج جستجوی شما',
'Sort by post time'					=>	'زمان ارسال',
'Sort by author'					=>	'نویسنده',
'Sort by subject'					=>	'عنوان',
'Sort by forum'						=>	'انجمن',
'Ascending'							=>	'صعودی',
'Descending'						=>	'نزولی',
'Show as'							=>	'نمایش نتایج براساس',
'Show as topics'					=>	'موضوع ها',
'Show as posts'						=>	'ارسال ها',

// Results
'Search'							=>	'جستجو',
'Search results'					=>	'نتایج جستجو',
'Quick search show_new'				=>	'جدید',
'Quick search show_recent'			=>	'فعال',
'Quick search show_unanswered'		=>	'بدون پاسخ',
'Quick search show_replies'			=>	'ارسال شده',
'Quick search show_user_topics'		=>	'موضوع توسط %s',
'Quick search show_user_posts'		=>	'ارسال توسط %s',
'Quick search show_subscriptions'	=>	'اشتراک توسط %s',
'By keywords show as topics'		=>	'موضوع ها با ارسال ها شامل \'%s\'',
'By keywords show as posts'			=>	'ارسال ها شامل \'%s\'',
'By user show as topics'			=>	'موضوع ها با ارسال ها توسط %s',
'By user show as posts'				=>	'ارسال توسط %s',
'By both show as topics'			=>	'موضوع ها با ارسال ها شامل \'%s\'، توسط %s',
'By both show as posts'				=>	'ارسال ها شامل \'%s\'، توسط %s',
'No terms'							=>	'شما حداقل باید یک کلمه و یا نام یک نویسنده را برای جستجو وارد کنید.',
'No hits'							=>	'جستجوی شما نتیجه ای نداشت.',
'No user posts'						=>	'ارسالی توسط این کاربر در این انجمن وجود ندارد.',
'No user topics'					=>	'موضوعی توسط این کاربر در این انجمن وجود ندارد.',
'No subscriptions'					=>	'این کاربر هم اکنون مشترک هیچ موضوعی نمیباشد.',
'No new posts'						=>	'از آخرین بازدید شما هیچ موضوع با ارسال جدیدی وجود ندارد.',
'No recent posts'					=>	'در 24 ساعت گذشته هیچ ارسال جدیدی ایجاد نشده است.',
'No unanswered'						=>	'در این انجمن هیچ ارسال بدون پاسخی وجود ندارد.',
'Go to post'						=>	'برو به ارسال',
'Go to topic'						=>	'برو به موضوع'

);
