<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'جستجوی کاربران',
'No search permission'				=>	'شما مجوز استفاده از مزیت جستجو را ندارید.',
'Search flood'						=>	'حداقل %s باید بین جستجوها زمان بگذرد. لطفا چند لحظه صبر کنید و مجددا تلاش کنید.',
'Search'							=>	'جستجو',
'Search criteria legend'			=>	'معیار جستجوی خود را وارد کنید',
'Search info'						=>	'جهت جستجو با کلمه کلیدی، عبارت یا عبارت هایی که به دنبالشان می گردید را وارد کنید. عبارات را با فاصله از هم جداکنید. از AND, OR و NOT جهت تنظیم دقیق تر جستجو استفاده کنید. برای جستجوی براساس نویسنده، نام کاربری نویسنده را وارد کنید. از نویسه عمومی * جهت انطباق با بخشی از نتایج استفاده کنید.',
'Keyword search'					=>	'جستجوی کلمات کلیدی',
'Author search'						=>	'جستجوی نویسنده',
'Search in legend'					=>	'انتخاب محل جستجو',
'Search in info'					=>	'انتخاب کنید که در چه تالاری جستجو انجام شود و اینکه آیا جستجو در عناوین مطالب، متن آنها یا هردو انجام شود.',
'Search multiple forums info'		=>	'اگر هیچ تالاری انتخاب نشود، همه تالارها جستجو خواهند شد.',
'Forum search'						=>	'تالار',
'All forums'						=>	'همه تالارها',
'Search in'							=>	'جستجو در',
'Message and subject'				=>	'متن و عنوان مبحث',
'Message only'						=>	'فقط متن مطلب',
'Topic only'						=>	'فقط عنوان مبحث',
'Sort by'							=>	'مرتب کردن با',
'Sort order'						=>	'نحو مرتب سازی',
'Search results legend'				=>	'انتخاب کنید که نتایج جستجو نمایش داده شوند',
'Search results info'				=>	'شما می توانید انتخاب کنید که نتایج بر چه اساسی مرتب و چگونه نمایش داده شوند.',
'Sort by post time'					=>	'زمان ارسال',
'Sort by author'					=>	'نویسنده',
'Sort by subject'					=>	'موضوع',
'Sort by forum'						=>	'تالار',
'Ascending'							=>	'صعودی',
'Descending'						=>	'نزولی',
'Show as'							=>	'نمایش نتایج به عنوان',
'Show as topics'					=>	'مباحث',
'Show as posts'						=>	'مطالب',

// Results
'Search'							=>	'جستجو',
'Search results'					=>	'نتایج جستجو',
'Quick search show_new'				=>	'جدید',
'Quick search show_recent'			=>	'فعال',
'Quick search show_unanswered'		=>	'بی پاسخ',
'Quick search show_replies'			=>	'ارسال شده',
'Quick search show_user_topics'		=>	'مباحث مطرح شده توسط %s',
'Quick search show_user_posts'		=>	'مطالب ارسال شده توسط %s',
'Quick search show_subscriptions'	=>	'مطالب تحت نظر گرفته شده توسط %s',
'By keywords show as topics'		=>	'مباحث شامل مطالبی حاوی \'%s\'',
'By keywords show as posts'			=>	'مطالب حاوی \'%s\'',
'By user show as topics'			=>	'مبحث با مطالبی توسط %s',
'By user show as posts'				=>	'مطالب ارسالی توسط %s',
'By both show as topics'			=>	'مبحث با مطالبی حاوی \'%s\', j,sx %s',
'By both show as posts'				=>	'مطلب حاوی \'%s\', توسط %s',
'No terms'							=>	'شما باید حداقل یک کلمه کلیدی و/یا نام یک نویسنده را برای جستجو وارد کنید.',
'No hits'							=>	'جستجوی شما نتیجه ای در بر نداشت.',
'No user posts'						=>	'هیچ مطلبی توسط این کاربر در این تالار نوشته نشده است.',
'No user topics'					=>	'هیچ مبحثی توسط این کاربر در این تالار ساخته نشده است.',
'No subscriptions'					=>	'این کاربر در حال حاضر مشترک هیچ مبحثی نیست',
'No new posts'						=>	'هیچ مبحثی با مطالب جدید بعد زمان آخرین بازدید شما وجود ندارد.',
'No recent posts'					=>	'هیچ مطلب جدیدی در 24 ساعت گذشته ارسال نشده است.',
'No unanswered'						=>	'هیچ مطلب بی پاسخی در این تالار وجود ندارد.',
'Go to post'						=>	'برو به مطلب',
'Go to topic'						=>	'برو به مبحث'

);
