<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'Δεν είναι δυνατός ο έλεγχος για αναβάθμιση, διότι το \'allow_url_fopen\' είναι απενεργοποιημένο σε αυτό το σύστημα.',
'Upgrade check failed message'		=>	'Ο έλεγχος για αναβάθμιση απέτυχε για άγνωστους λόγους.',
'Running latest version message'	=>	'Έχετε την τελευταία έκδοση του FluxBB.',
'New version available message'		=>	'Μια νέα έκδοση του FluxBB είναι διαθέσιμη. Μπορείτε να κανετε λήψη της τελευταίας έκδοσης από %s.',
'Not available'						=>	'Μη διαθέσιμο',
'Forum admin head'					=>	'Διαχείριση φόρουμ',
'NA'								=>	'Μη διαθέσιμο',
'Welcome to admin'					=>	'Καλώς ήλθατε στον πίνακα ελέγχου διαχείρισης του FluxBB. Από εδώ μπορείτε να ελέγξετε ζωτικής σημασίας πτυχές του φόρουμ. Ανάλογα με το αν είστε διαχειριστής ή συντονιστής μπορείτε να:',
'Welcome 1'							=>	'Οργανώσετε κατηγορίες και δημόσιες συζητήσεις.',
'Welcome 2'							=>	'Ορίσετε επιλογές και προτιμήσεις του ευρύτερου φόρουμ.',
'Welcome 3'							=>	'Ελέγχετε τα δικαιώματα για χρήστες κι επισκέπτες.',
'Welcome 4'							=>	'Βλέπετε στατιστικά στοιχεία των IP για τους χρήστες.',
'Welcome 5'							=>	'Αποκλείσετε χρήστες.',
'Welcome 6'							=>	'Λογοκρίνετε λέξεις.',
'Welcome 7'							=>	'Δημιουργήσετε ομάδες χρηστών και προαγωγές.',
'Welcome 8'							=>	'Διαγράψετε παλιές δημοσιεύσεις.',
'Welcome 9'							=>	'Χειριστείτε αναφορές δημοσιεύσεων.',
'About head'						=>	'Σχετικά με FluxBB',
'FluxBB version label'				=>	'Έκδοση FluxBB',
'Check for upgrade'					=>	'Έλεγχος για αναβάθμιση',
'FluxBB version data'				=>	'v%s - %s',
'Server statistics label'			=>	'Στατιστικά διακομιστή',
'View server statistics'			=>	'Προβολή στατιστικών διακομιστή',
'Support label'						=>	'Υποστήριξη',
'Forum label'						=>	'Φόρουμ',
'IRC label'							=>	'Κανάλι IRC',

// Language definitions used in admin_statistics.php
'PHPinfo disabled message'			=>	'Η PHP λειτουργία phpinfo() έχει απενεργοποιηθεί σε αυτόν τον διακομιστή.',
'Server statistics head'			=>	'Στατιστικά διακομιστή',
'Server load label'					=>	'Κίνηση διακομιστή',
'Server load data'					=>	'%s - %s χρήστες σε σύνδεση',
'Environment label'					=>	'Περιβάλλον',
'Environment data OS'				=>	'Λειτουργικό σύστημα: %s',
'Show info'							=>	'Προβολή πληροφοριών',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Επιταχυντής: %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Βάση δεδομένων',
'Database data rows'				=>	'Εγγραφές: %s',
'Database data size'				=>	'Μέγεθος: %s',
);
