<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'Невозможно проверить систему на наличие обновления, так как нет доступа к \'allow_url_fopen\'.',
'Upgrade check failed message'		=>	'Проверка наличия обновлений не удалась по неизвестным причинам.',
'Running latest version message'	=>	'Вы используете последнюю версию FluxBB.',
'New version available message'		=>	'Доступна новая версия FluxBB. Вы можете сказать ее с %s.',
'PHPinfo disabled message'			=>	'PHP функция phpinfo() отключена.',
'Not available'						=>	'Недоступно',
'Forum admin head'					=>	'Управление форумом',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'Добро пожаловать в панель управления форума FluxBB! Отсюда осуществляется управление многочисленными параметрами. В зависимости от того, к какой группе вы относитесь, зависит количество доступных инструментов управления. Например, вы можете:',
'Welcome 1'							=>	'Настраивать категории и форумы.',
'Welcome 2'							=>	'Выбирать и настраивать общие параметры.',
'Welcome 3'							=>	'Контролировать доступ пользователей.',
'Welcome 4'							=>	'Просматривать IP-статистику пользователей.',
'Welcome 5'							=>	'Блокировать пользователей.',
'Welcome 6'							=>	'Контролировать поведение.',
'Welcome 7'							=>	'Устанавливать ранги и звания.',
'Welcome 8'							=>	'Избавляться от старых тем.',
'Welcome 9'							=>	'Получать жалобы от пользователей.',
'Statistics head'					=>	'Статистика',
'FluxBB version label'				=>	'Версия FluxBB',
'Check for upgrade'					=>	'Проверить обновления',
'FluxBB version data'				=>	'v%s &#8212; %s',
'Server load label'					=>	'Загруженность сервера',
'Server load data'					=>	'%s &#8212; %s пользователь(ей) online',
'Environment label'					=>	'Окружение',
'Environment data OS'				=>	'Операционная система: %s',
'Show info'							=>	'Просмотреть информацию',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Accelerator: %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'База данных',
'Database data rows'				=>	'Строк: %s',
'Database data size'				=>	'Размер: %s',

);
