<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(
    'fopen disabled message'           => 'Невозможно проверить обновления, т.к. \'allow_url_fopen\' недоступен в этой системе.',
    'Upgrade check failed message'     => 'Проверка обновлений завершилась неудачей по неизвестным причинам.',
    'Running latest version message'   => 'Вы работаете на самой новой версии FluxBB.',
    'New version available message'    => 'Новая версия FluxBB обнаружена. Вы можете загрузить ее по адресу %s.',
    'Deleted install.php redirect'     => 'Файл был успешно удалён. Перенаправление …',
    'Delete install.php failed'        => 'Невозможно удалить файл install.php. Пожалуйста, сделайте это вручную.',
    'Not available'                    => 'Недоступно',
    'Forum admin head'                 => 'Администрирование форума',
    'NA'                               => 'N/A',
    'Welcome to admin'                 => 'Добро пожаловать в панель управления FluxBB! Здесь вы можете настроить ключевые параметры вашего форума. В зависимости от того, Администратор вы или Модератор, вы можете:',
    'Welcome 1'                        => 'Настроить категории и разделы.',
    'Welcome 2'                        => 'Установить параметры по умолчанию для форума в целом.',
    'Welcome 3'                        => 'Контролировать права пользователей и гостей.',
    'Welcome 4'                        => 'Смотреть статистику пользователей по IP.',
    'Welcome 5'                        => 'Банить пользователей.',
    'Welcome 6'                        => 'Настроить список цензурируемых слов.',
    'Welcome 7'                        => 'Установить ранги пользователей.',
    'Welcome 8'                        => 'Очистить старые сообщения.',
    'Welcome 9'                        => 'Реагировать на жалобы пользователей.',
    'Alerts head'                      => 'Внимание',
    'Install file exists'              => 'Файл install.php до сих пор существует. Он должен быть удалён. %s.',
    'Delete install file'              => 'Удалить его',
    'About head'                       => 'О FluxBB',
    'FluxBB version label'             => 'Версия FluxBB',
    'Check for upgrade'                => 'Искать обновления',
    'FluxBB version data'              => 'v%s - %s',
    'Server statistics label'          => 'Серверная статистика',
    'View server statistics'           => 'Показать серверную статистику',
    'Support label'                    => 'Поддержка',
    'Forum label'                      => 'Форум',
    'IRC label'                        => 'Канал IRC',

// Language definitions used in admin_statistics.php
    'PHPinfo disabled message'         => 'Функция phpinfo() недоступна на этом сервере.',
    'Server statistics head'           => 'Серверная статистика',
    'Server load label'                => 'Загрузка сервера',
    'Server load data'                 => '%s - %s пользователей online',
    'Environment label'                => 'Окружение',
    'Environment data OS'              => 'Операционная система: %s',
    'Show info'                        => 'Смотреть подробности',
    'Environment data version'         => 'PHP: %s - %s',
    'Environment data acc'             => 'Accelerator: %s',
    'Turck MMCache'                    => 'Turk MMCache',
    'Turck MMCache link'               => 'turck-mmcache.sourceforge.net',
    'ionCube PHP Accelerator'          => 'ionCube PHP Accelerator',
    'ionCube PHP Accelerator link'     => 'www.php-accelerator.co.uk/',
    'Alternative PHP Cache (APC)'      => 'Alternative PHP Cache (APC)',
    'Alternative PHP Cache (APC) link' => 'www.php.net/apc/',
    'Zend Optimizer'                   => 'Zend Optimizer',
    'Zend Optimizer link'              => 'www.zend.com/products/guard/zend-optimizer',
    'eAccelerator'                     => 'eAccelerator',
    'eAccelerator link'                => 'www.eaccelerator.net/',
    'XCache'                           => 'XCache',
    'XCache link'                      => 'xcache.lighttpd.net/',
    'Database label'                   => 'База данных',
    'Database data rows'               => 'Строк: %s',
    'Database data size'               => 'Размер: %s'
);
