<?php

// Language definitions used in admin-users.php
$lang_admin_users = array(

'Non numeric message'		=>	'You entered a non-numeric value into a numeric only column.',
'Invalid date time message'	=>	'You entered an invalid date/time.',
'Not verified'				=>	'Not verified',
'User search head'			=>	'Поиск пользователей',
'User search subhead'		=>	'Enter search criteria',
'User search info'			=>	'Поиск пользователей в базе. Вы можете указать сразу несколько условий. Маски в виде звёздочек (*) допускаются.',
'Username label'			=>	'Имя пользователя',
'E-mail address label'		=>	'Email адрес',
'Title label'				=>	'Титул',
'Real name label'			=>	'Настоящее имя',
'Website label'				=>	'Вебсайт',
'Jabber label'				=>	'Jabber',
'ICQ label'					=>	'ICQ',
'MSN label'					=>	'MSN Messenger',
'AOL label'					=>	'AOL IM',
'Yahoo label'				=>	'Yahoo Messenger',
'Location label'			=>	'Откуда',
'Signature label'			=>	'Подпись',
'Admin note label'			=>	'Примечание админа',
'Posts more than label'		=>	'Сообщений больше чем',
'Posts less than label'		=>	'Сообщений меньше чем',
'Last post after label'		=>	'Последнее сообщение позднее',
'Date help'					=>	'(yyyy-mm-dd hh:mm:ss)',
'Last post before label'	=>	'Последнее сообщение ранее',
'Registered after label'	=>	'Зарегистрирован позднее',
'Registered before label'	=>	'Зарегистрирован ранее',
'Order by label'			=>	'Сортировать по',
'Order by username'			=>	'Имени',
'Order by e-mail'			=>	'Email',
'Order by posts'			=>	'Количествуву сообщений',
'Order by last post'		=>	'Последнему сообщению',
'Order by registered'		=>	'Регистрации',
'Ascending'					=>	'По возрастанию',
'Descending'				=>	'По убыванию',
'User group label'			=>	'Группа',
'All groups'				=>	'Все группы',
'Unverified users'			=>	'Неподтверждённый',
'Submit search'				=>	'Начать поиск',
'IP search head'			=>	'Поиск по IP',
'IP search subhead'			=>	'Введите IP для поиска',
'IP address label'			=>	'IP адрес',
'IP address help'			=>	'IP адрес который будем искать в базе сообщений.',
'Find IP address'			=>	'Найти IP адрес',

'Results head'				=>	'Результаты поиска',
'Results username head'		=>	'Имя пользователя',
'Results e-mail head'		=>	'Email',
'Results title head'		=>	'Титул/Статус',
'Results posts head'		=>	'Сообщений',
'Results admin note head'	=>	'Примечание',
'Results actions head'		=>	'Действия',
'Results IP address head'	=>	'IP адрес',
'Results last used head'	=>	'Посл. использование',
'Results times found head'	=>	'Встречается раз',
'Results action head'		=>	'Действие',
'Results find more link'	=>	'Найти других пользователей с этим ip',
'Results no posts found'	=>	'У этого пользователя нет ни одного сообщения.',
'Bad IP message'			=>	'Указанный IP имеет неправильный формат.',
'Results view IP link'		=>	'Показать IP статистику',
'Results show posts link'	=>	'Показать сообщения',
'Results guest'				=>	'Гость',
'Results no IP found'		=>	'Указанный IP не найден в базе.',
'No match'					=>	'Ничего'

);
