<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Настройки почтового адреса',
'Email legend 2'			=>	'Ввод и подтверждение почтового адреса',
'Localisation legend'		=>	'Настройка опций местоположения',
'Time zone'					=>	'Часовой пояс',
'Time zone info'			=>	'Чтобы форум выводил корректно время, установите настройки часового пояса. Если вы хотите автоматически переходить на летнее время, отметьте соответствующую опцию, время увеличится на 1 час.',
'DST'						=>	'Переходить на летнее время (время увеличится на 1 час).',
'Time format'				=>	'Формат времени',
'Date format'				=>	'Формат даты',
'Default'					=>	'По умолчанию',
'Language'					=>	'Язык',
'Email setting info'		=>	'Укажите, хотели бы вы получать письма от других участников, и выберите одну из настроек.',
'Email setting 1'			=>	'Показывать почтовый адрес всем пользователям.',
'Email setting 2'			=>	'Скрывать почтовый адрес, но разрешать отправлять письма.',
'Email setting 3'			=>	'Скрывать почтовый адрес и запрещать отправлять письма.',
'Privacy options legend'	=>	'Настройка приватных опций',
'Confirm pass'				=>	'Подтверждение пароля',

'Username too short'		=>	'Имена пользователей должны состоять минимум из 2 символов. Пожалуйста, выберите другое (более длинное) имя.',
'Username too long'			=>	'Имена пользователей не должны превышать 25 символов. Пожалуйста, выберите другое (более короткое) имя.',
'Username guest'			=>	'Имя пользователя <strong>guest</strong> занято. Пожалуйста, выберите другое имя.',
'Username IP'				=>	'Имена пользователей не должны быть похожи на IP адреса. Пожалуйста, выберите другое имя.',
'Username reserved chars'	=>	'Имена пользователей не могут содержать символов \', ", [ или ]. Пожалуйста, выберите другое имя.',
'Username BBCode'			=>	'Имена не могут содержать теги форматирования, используемые на форуме. Пожалуйста, выберите другое имя.',
'Banned username'			=>	'Введенное имя пользователя заблокировано. Пожалуйста, выберите другое имя.',
'Pass too short'			=>	'Пароль должен состоять минимум из 4 символов. Пожалуйста, выберите другой (более длинный) пароль.',
'Pass not match'			=>	'Пароли не совпадают',
'Banned email'				=>	'Введенный почтовый адрес заблокирован. Пожалуйста, выберите другой.',
'Dupe email'				=>	'Введенный почтовый адрес используется кем-то другим. Пожалуйста, выберите другой.',
'Sig too long'				=>	'Подпись не должна превышать %1$s символов. Количество лишних символов на текущий момент %2$s.',
'Sig too many lines'		=>	'Подпись не должна превышать %s строк.',
'Bad ICQ'					=>	'Введенный ICQ UIN неверен. Вернитесь и исправьте.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
