<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'Поиск участника',
'No search permission'				=>	'У вас нет доступа к использованию поиска.',
'Search flood'						=>	'Должно пройти как минимум %s секунд между повторными попытками поиска информации. Пожалуйста, подождите, и повторите попытку вновь.',
'Search'							=>	'Поиск',
'Search criteria legend'			=>	'Ввод условий поиска',
'Search info'						=>	'Для начала поиска введите включевое слово, фразу или условие. Условия разделяйте пробелами. Используйте служебные слова AND, OR и NOT для получения более точных результатов. Для проведения поиска среди сообщений конкретного участника, укажите его имя в соответствующем поле. В запросах разрешено использовать символ звездочки (*).',
'Keyword search'					=>	'Ключевое слово или фраза для поиска',
'Author search'						=>	'Автор',
'Search in legend'					=>	'Укажите, где искать',
'Search in info'					=>	'Выберите форум и место, по которым будет происходить поиск.',
'Search multiple forums info'		=>	'Если не выбрано ни одного форума, то поиск будет происходить во всех.',
'Forum search'						=>	'Форум',
'All forums'						=>	'Все форумы',
'Search in'							=>	'Искать в',
'Message and subject'				=>	'Тексте сообщений и названиях тем',
'Message only'						=>	'Только в тексте сообщений',
'Topic only'						=>	'Только в названиях тем',
'Sort by'							=>	'Сортировать по',
'Sort order'						=>	'Порядок сортировки',
'Search results legend'				=>	'Настройка параметров вывода результатов',
'Search results info'				=>	'Вы можете выбрать, как будут сортироваться, и выводиться результаты поиска.',
'Sort by post time'					=>	'Дате публикации',
'Sort by author'					=>	'Автору',
'Sort by subject'					=>	'Названию',
'Sort by forum'						=>	'Форуму',
'Ascending'							=>	'По возрастанию',
'Descending'						=>	'По убыванию',
'Show as'							=>	'Вывод в виде',
'Show as topics'					=>	'Тем',
'Show as posts'						=>	'Сообщений',

// Results
'Search'							=>	'Поиск',
'Search results'					=>	'Результаты поиска',
'Quick search show_new'				=>	'Новые темы',
'Quick search show_recent'			=>	'Активные темы',
'Quick search show_unanswered'		=>	'Темы без ответов',
'Quick search show_replies'			=>	'Темы с вашим участием',
'Quick search show_user_topics'		=>	'Темы от %s',
'Quick search show_user_posts'		=>	'Сообщения от %s',
'Quick search show_subscriptions'	=>	'Подписки участника %s',
'By keywords show as topics'		=>	'Темы и сообщения содержащие \'%s\'',
'By keywords show as posts'			=>	'Сообщения содержащие \'%s\'',
'By user show as topics'			=>	'Темы с сообщениями от %s',
'By user show as posts'				=>	'Сообщения от %s',
'By both show as topics'			=>	'Темы и сообщения содержащие \'%s\', автор %s',
'By both show as posts'				=>	'Сообщения содержащие \'%s\', автор %s',
'No terms'							=>	'Необходимо ввести хотя бы одно ключевое слово или автора для проведения поиска.',
'No hits'							=>	'Ничего не найдено.',
'No user posts'						=>	'На форуме нет сообщений от выбранного участника.',
'No user topics'					=>	'На форуме нет тем от выбранного участника.',
'No subscriptions'					=>	'Участник не подписан ни на одну из тем.',
'No new posts'						=>	'С вашего последнего визита новых сообщений в темах не появилось.',
'No recent posts'					=>	'За последние сутки новых сообщений нет.',
'No unanswered'						=>	'В этом форуме нет сообщений без ответа. There are no unanswered posts in this forum.',
'Go to post'						=>	'Перейти к сообщению',
'Go to topic'						=>	'Перейти в тему'

);
