<?php
// Language definitions used in search.php
$lang_search = array(
// The search form
    'User search'                     => 'Поиск пользователей',
    'No search permission'            => 'У вас не хватает прав для поиска.',
    'Search flood'                    => 'Хотя бы %s сек. должно пройти до следующего поиска. Пожалуйста, подождите и попробуйте снова.',
    'Search'                          => 'Поиск',
    'Search criteria legend'          => 'Введите условия поиска',
    'Search info'                     => 'Введите одно или несколько слов для поиска. Отделяйте слова пробелами. Используйте условия AND, OR и NOT. Вы можете дополнить условие, указав автора сообщения. Используйте символ * для поиска по части слова.',
    'Keyword search'                  => 'Ключевые слова',
    'Author search'                   => 'Автор',
    'Search in legend'                => 'Где искать',
    'Search in info'                  => 'Выберите в каком форуме искать и где искать: в заголовке, сообщении или и там и там.',
    'Search multiple forums info'     => 'Если не выбран ни один, будем искать по всем.',
    'Forum search'                    => 'Форум',
    'Search in'                       => 'Искать в',
    'Message and subject'             => 'сообщении и заголовке темы',
    'Message only'                    => 'только в сообщении',
    'Topic only'                      => 'только в заголовке темы',
    'Sort by'                         => 'Сортировка',
    'Sort order'                      => 'Порядок сортировки',
    'Search results legend'           => 'Выберите как выводить результаты поиска',
    'Search results info'             => 'Вы можете указать как сортировать и показывать результаты.',
    'Sort by post time'               => 'время сообщения',
    'Sort by author'                  => 'автор',
    'Sort by subject'                 => 'тема',
    'Sort by forum'                   => 'форум',
    'Ascending'                       => 'по возрастанию',
    'Descending'                      => 'по убыванию',
    'Show as'                         => 'Показать как',
    'Show as topics'                  => 'темы',
    'Show as posts'                   => 'сообщения',

// Results
    'Search results'                  => 'Результаты поиска',
    'Quick search show_new'           => 'Новые',
    'Quick search show_recent'        => 'Активные',
    'Quick search show_unanswered'    => 'Без ответов',
    'Quick search show_replies'       => 'Ваши',
    'Quick search show_user_topics'   => 'От %s',
    'Quick search show_user_posts'    => 'От %s',
    'Quick search show_subscriptions' => 'Подписка %s',
    'By keywords show as topics'      => 'С сообщениями со словами \'%s\'',
    'By keywords show as posts'       => 'Со словами \'%s\'',
    'By user show as topics'          => 'С сообщениями от %s',
    'By user show as posts'           => 'Написано %s',
    'By both show as topics'          => 'Со словами \'%s\' в сообщениях, написанных %s',
    'By both show as posts'           => 'Со словами \'%s\' написано %s',
    'No terms'                        => 'Вам следует ввести хотябы одно слово для поиска и/или автора.',
    'No hits'                         => 'Ничего не найдено.',
    'No user posts'                   => 'Нет ни одного сообщения у данного пользователя.',
    'No user topics'                  => 'Нет ни одной темы у данного пользователя.',
    'No subscriptions'                => 'Вы пока не подписаны ни на одну тему.',
    'No new posts'                    => 'Нет ни одного нового сообщения с вашего последнего визита.',
    'No recent posts'                 => 'Ни одного сообщения за последние 24 часа.',
    'No unanswered'                   => 'Нет ни одной темы без ответа.',
    'Go to post'                      => 'Перейти к сообщению',
    'Go to topic'                     => 'Перейти к теме'
);
