<?php

// Language definitions used in admin_index.php
// Finnish translation by Pauligrinder
$lang_admin_index = array(

'fopen disabled message'			=>	'Päivitysten etsiminen epäonnistui, koska \'allow_url_fopen\' ei ole käytössä tässä järjestelmässä.',
'Upgrade check failed message'		=>	'Päivitysten etsiminen epäonnistui tuntemattomasta syystä.',
'Running latest version message'	=>	'Tämä on FluxBB:n uusin versio.',
'New version available message'		=>	'FluxBB:stä on julkaistu uusi versio. Voit ladata uusimman version osoitteesta %s.',
'PHPinfo disabled message'			=>	'PHP funktio phpinfo() ei ole käytössä tällä palvelimella.',
'Not available'						=>	'Ei saatavilla',
'Forum admin head'					=>	'Forumin ylläpito',
'NA'								=>	'Ei saatavilla',
'Welcome to admin'					=>	'Tervetuloa FluxBB:n ylläpitovalikkoon. Täältä voit muokata laudan tärkeimpiä asetuksia. Riippuen siitä, oletko ylläpitäjä vai moderaattori, voit:',
'Welcome 1'							=>	'Järjestellä luokkia ja forumeita.',
'Welcome 2'							=>	'Muokata forumeiden asetuksia.',
'Welcome 3'							=>	'Säädellä käyttäjien ja vieraiden oikeuksia.',
'Welcome 4'							=>	'Tutkia käyttäjien IP-tietoja.',
'Welcome 5'							=>	'Bannata käyttäjiä.',
'Welcome 6'							=>	'Sensuroida sanoja.',
'Welcome 7'							=>	'Asettaa käyttäjille arvonimiä.',
'Welcome 8'							=>	'Karsia vanhoja kirjoituksia.',
'Welcome 9'							=>	'Käsitellä raportteja.',
'Statistics head'					=>	'Statistiikka',
'FluxBB version label'				=>	'FluxBB:n versio',
'Check for upgrade'					=>	'Etsi päivityksiä',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'Palvelimen käyttöaste',
'Server load data'					=>	'%s - %s käyttäjä(ä) kirjautuneena',
'Environment label'					=>	'Ympäristö',
'Environment data OS'				=>	'Käyttöjärjestelmä: %s',
'Show info'							=>	'Näytä tiedot',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Kiihdytin: %s',
'Turck MMCache'						=>	'Turk MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Tietokanta',
'Database data rows'				=>	'Rivejä: %s',
'Database data size'				=>	'Koko: %s',

);
