<?php

// Language definitions used in admin-groups.php
// Finnish translation by Pauligrinder
$lang_admin_groups = array(

'Must enter title message'		=>	'Sinun täytyy antaa ryhmälle nimi.',
'Title already exists message'	=>	'Ryhmä nimeltään <strong>%s</strong> on jo olemassa.',
'Default group redirect'		=>	'Oletusryhmä asetettu. Siirrytään …',
'Cannot remove default message'	=>	'Oletusryhmää ei voi poistaa.  Poistaaksesi tämän ryhmän, sinun täytyy asettaa joku muu ryhmä oletuksryhmäksi.',
'Group removed redirect'		=>	'Ryhmä poistettu. Siirrytään …',
'Group added redirect'			=>	'Ryhmä lisätty. Siirrytään …',
'Group edited redirect'			=>	'Ryhmää muokattu. Siirrytään …',

'Add groups head'				=>	'Lisää/aseta uusia luokkia',
'Add group subhead'				=>	'Lisää uusi ryhmä',
'New group label'				=>	'Uusi ryhmä perustuu ryhmään',
'New group help'				=>	'Valitse käyttäjäryhmä josta uusi ryhmä perii oikeutensa. Seuraavalla sivulla voit hienosäätää sen asetuksia.',
'Default group subhead'			=>	'Aseta oletusryhmä',
'Default group label'			=>	'Oletusryhmä',
'Default group help'			=>	'Tämä on oletusryhmä, eli käyttäjät päätyvät tähän ryhmään kun he rekisteröityvät. Turvallisuussyistä, käyttäjiä ei voi asettaa oletuksena moderaattoriksi tai ylläpitäjäksi.',
'Existing groups head'			=>	'Olemassaolevat ryhmät',
'Edit groups subhead'			=>	'Muokkaa/poista ryhmiä',
'Edit groups info'				=>	'Ennaltamäärättyjä ryhmiä Vieraat, Ylläpitäjät, Moderaattorit ja Jäsenet ei voi poistaa. Niitä voi kuitenkin muokata. Huomaa kuitenkin, että joissain ryhmissä, jotkut asetukset ovat pois käytöstä (esim. <em>muokkaa kirjoituksia</em> asetus vierailla). Administraattoreilla on aina täydet oikeudet.',
'Edit link'						=>	'Muokkaa',
'Delete link'					=>	'Poista',
'Group delete head'				=>	'Poista ryhmä',
'Confirm delete subhead'		=>	'Vahvista ryhmän poistaminen',
'Confirm delete info'			=>	'Oletko varma että haluat poistaa ryhmän <strong>%s</strong>?',
'Confirm delete warn'			=>	'VAROITUS! Ryhmää ei voi palauttaa kun se on poistettu.',
'Delete group head'				=>	'Poista ryhmä',
'Move users subhead'			=>	'Siirrä käyttäjät ryhmästä',
'Move users info'				=>	'Ryhmässä <strong>%s</strong> on tällä hetkellä <strong>%s</strong> jäsentä. Valitse ryhmä johon käyttäjät siirretään kun ryhmä poistetaan.',
'Move users label'				=>	'Siirrä käyttäjät ryhmään',
'Delete group'					=>	'Poista ryhmä',

'Group settings head'			=>	'Ryhmäasetukset',
'Group settings subhead'		=>	'Aseta ryhmän asetukset ja oikeudet',
'Group settings info'			=>	'Alla näkyvät asetukset ja oikeudet ovat käyttäjäryhmän oletusasetukset. Nämä asetukset ovat voimassa jos forumilla ei ole erillisiä asetuksia.',
'Group title label'				=>	'Ryhmän titteli',
'User title label'				=>	'Käyttäjän titteli',
'User title help'				=>	'Tämä ohittaa ryhmän käyttäjän mahdollisen arvonimen. Jätä tyhjäksi käyttääksesi oletustitteliä tai -arvonimeä.',
'Mod privileges label'			=>	'Annan käyttäjille moderaattorin oikeudet',
'Mod privileges help'			=>	'Saadaksen moderaattorin toiminnot käyttöön, käyttäjä pitää asettaa ainakin yhden forumin moderaattoriksi. Tämä hoituu käyttäjäadministraatio sivulta, käyttäjän profiilista.',
'Edit profile label'			=>	'Anna moderaattorin muokatta käyttäjien profiileja',
'Edit profile help'				=>	'Jos moderaattorioikeudet ovat päällä, käyttäjä saa muokata toisten käyttäjien profiileja.',
'Rename users label'			=>	'Anna moderaattorin vaihtaa käyttäjien nimiä',
'Rename users help'				=>	'Jos moderaattorioikeudet ovat päällä, käyttäjä saa muokata toisten käyttäjien nimiä.',
'Change passwords label'		=>	'Anna moderaattorin vaihtaa salasanoja',
'Change passwords help'			=>	'Jos moderaattorioikeudet ovat päällä, käyttäjä saa muokata toisten käyttäjien salasanoja.',
'Ban users label'				=>	'Anna moderaattorin bannata käyttäjiä',
'Ban users help'				=>	'Jos moderaattorioikeudet ovat päällä, käyttäjä saa bannata toisia käyttäjiä.',
'Read board label'				=>	'Laudan lukeminen',
'Read board help'				=>	'Anna käyttäjälle lukuoikeus. Tämä asetus vaikuttaa jokaiseen laudan osa-alueeseen, ja näin ollen sitä ei voi ohittaa forumikohtaisilla asetuksilla. Jos tässä kohdassa on "Ei", niin tämän ryhmän käyttäjät voivat ainoastaan kirjautua sisään/ulos tai rekisteröityä.',
'View user info label'			=>	'Näytä käyttäjän tiedot',
'View user info help'			=>	'Anna käyttäjän katsoa käyttäjälistaa ja muiden käyttäjien profiilisivuja.',
'Post replies label'			=>	'Vastausten lähettäminen',
'Post replies help'				=>	'Anna ryhmän käyttäjien vastata kirjoituksiin.',
'Post topics label'				=>	'Uusien aiheiden luominen',
'Post topics help'				=>	'Anna ryhmän käyttäjien luoda uusia viestiketjuja.',
'Edit posts label'				=>	'Kirjoitusten muokkaaminen',
'Edit posts help'				=>	'Anna ryhmän käyttäjien muokata omia kirjoituksiaan.',
'Delete posts label'			=>	'Kirjoitusten poistaminen',
'Delete posts help'				=>	'Anna ryhmän käyttäjien poistaa omia kirjoituksiaan.',
'Delete topics label'			=>	'Aiheiden poistaminen',
'Delete topics help'			=>	'Anna ryhmän käyttäjien poistaa omia viestiketjujaan (ja niiden vastauksia).',
'Set own title label'			=>	'Oman tittelin asettaminen',
'Set own title help'			=>	'Anna ryhmän käyttäjien muokata omaa titteliään.',
'User search label'				=>	'Haun käyttäminen',
'User search help'				=>	'Anna ryhmän käyttäjien käyttää hakutoimintoa.',
'User list search label'		=>	'Käyttäjälistahaku',
'User list search help'			=>	'Anna ryhmän käyttäjien käyttää jäsenhakua.',
'Send e-mails label'			=>	'Sähköpostin lähettäminen',
'Send e-mails help'				=>	'Anna ryhmän käyttäjien lähettää sähköposteja muille käyttäjille.',
'Post flood label'				=>	'Kirjoitusten välinen minimiaika',
'Post flood help'				=>	'Näin monta sekunttia käyttäjän täytyy odottaa ennen kuin voi lähettää uuden kirjoituksen. 0 = pois käytöstä.',
'Search flood label'			=>	'Hakujen välinen minimiaika',
'Search flood help'				=>	'Näin monta sekunttia käyttäjän täytyy odottaa ennen kuin voi etsiä uudelleen. 0 = pois käytöstä.',
'E-mail flood label'			=>	'Sähköpostejen välinen minimiaika',
'E-mail flood help'				=>	'Näin monta sekunttia käyttäjän täytyy odottaa ennen kuin voi lähettää uuden sähköpostin. 0 = pois käytöstä.',
'Moderator info'				=>	'Huomaa että käyttäjä ei saa moderaattorin toiminto käyttöön ennen kuin hänet on asetettu ainakin yhden forumin moderaattoriksi. Tämä hoituu käyttäjäadministraatiosivulta, käyttäjän profiilista.',

);
