<?php

// Language definitions used in admin_bans.php
// Finnish translation by Pauligrinder
$lang_admin_bans = array(

'No user message'           =>	'Tuon nimistä käyttäjää ei ole rekisteröity. Jos haluat bannata jonkun ilmoittamatta nimeä, jätä tämä kenttä tyhjäksi.',
'No user ID message'		=>	'Tällä ID:llä ei ole rekisteröity ketään.',
'User is admin message'		=>	'Käyttäjä %s on ylläpitäjä. Bannataksesi hänet, sinun täytyy ensin poistaa oikeudet.',
'User is mod message'		=>	'Käyttäjä %s on moderaattori. Bannataksesi hänet, sinun täytyy ensin poistaa oikeudet.',
'Must enter message'		=>	'Sinun pitää antaa joko käyttäjänimi, IP-osoite tai sähköpostiosoite.',
'Cannot ban guest message'	=>	'Vieraita ei voi bannata.',
'Invalid IP message'		=>	'Ilmoitit virheellisen IP:n',
'Invalid e-mail message'	=>	'Antamasi sähköpostiosoite ei kelpaa.',
'Invalid date message'		=>	'Ilmoitit menneen päivämäärän.',
'Invalid date reasons'		=>	'Päivämäärän tulee olla muodossa YYYY-MM-DD ja päivän täytyy olla tulevaisuudessa.',
'Ban added redirect'		=>	'Bannaus suoritettu. Siirrytään …' ,
'Ban edited redirect'		=>	'Bannausta muokattu. Siirrytään …',
'Ban removed redirect'		=>	'Bannaus poistettu. Siirrytään …',

'New ban head'				=>	'Uusi banni',
'Add ban subhead'			=>	'Lisää banni',
'Username label'			=>	'Käyttäjänimi',
'Username help'				=>	'Bannattava käyttäjä (merkkikokoriippuvainen).',
'Username advanced help'	=>	'Bannattava käyttäjänimi (merkkikokoriippumaton). Seuraavalla sivulla sinulta kysytään sähköpostiosoite tai IP. Jätä käyttämättömät kentät tyhjiksi.',

'Ban search head'			=>	'Bannihaku',
'Ban search subhead'		=>	'Syötä hakukriteeri',
'Ban search info'			=>	'Etsi tietokannasta banneja.',
'Date help'                 =>	'(yyyy-mm-dd)',
'Message label'				=>	'Viesti',
'Expire after label'		=>	'Menee umpeen jälkeen',
'Expire before label'		=>	'Menee umpeen ennen',
'Order by label'			=>	'Järjestä',
'Order by username'			=>	'Käyttäjän mukaan',
'Order by ip'				=>	'IP:n mukaan',
'Order by e-mail'			=>	'Sähköpostin mukaan',
'Order by expire'			=>	'Päivämäärän mukaan',
'Ascending'                 =>	'Nousevassa järjestyksessä',
'Descending'				=>	'Laskevassa järjestyksessä',
'Submit search'				=>	'Suorita haku',

'E-mail label'				=>	'Sähköposti',
'E-mail help'				=>	'Sähköpostiosoite tai domaini jonka haluat bannata (esim. joku@jossain.fi tai jossain.fi). Enemmän tietoja löytyy kohdasa "Oikeudet->Salli bannatut sähköpostiosoitteet"',
'IP label'                  =>	'IP osoite/IP alue',
'IP help'                   =>	'IP osoite tai IP alue jonka haluat bannata (esim. 150.11.110.1 tai 150.11.110). Erottele osoitteet välilyönneillä. Jos IP-kenttä on valmiiksi täytetty, se on käyttäjän viimeisin tietokannasta löytyvä osoite.',
'IP help link'				=>	'Napsauta nähdäksesi käyttäjän IP-tiedot.',
'Ban advanced head'			=>	'Bannauksen lisäasetukset',
'Ban advanced subhead'		=>	'Lisää banniin IP- ja sähköpostiosoite',
'Ban message label'			=>	'Bannausviesti',
'Ban message help'			=>	'Viesti joka näkyy kun bannattu käyttäjä yrittää kirjautua forumille.',
'Message expiry subhead'	=>	'Bannausviesti ja voimassaoloaika',
'Ban IP range info'			=>	'IP-alueella bannattaessa kannattaa olla varovainen, saatat vahingossa bannata useampia käyttäjiä joiden IP on samalla alueella.',
'Expire date label'			=>	'Erääntymispäivä',
'Expire date help'			=>	'Päivä jolloin banni menee umpeen (muodossa: vvvv-kk-pp). Jätä tyjäksi poistaaksesi manuaalisesti.',

'Results head'				=>	'Hakutulokset',
'Results username head'		=>	'Käyttäjänimi',
'Results e-mail head'		=>	'Sähköposti',
'Results IP address head'	=>	'IP/IP-alue',
'Results expire head'		=>	'Menee umpeen',
'Results message head'		=>	'Viesti',
'Results banned by head'	=>	'Bannanut',
'Results actions head'		=>	'Toiminnot',
'No match'					=>	'Ei tuloksia',
'Unknown'					=>	'Tuntematon',

);
