<?php

// Language definitions used in admin-options.php
// Finnish translation by Pauligrinder
$lang_admin_options = array(

'Bad HTTP Referer message'			=>	'Virheellinen HTTP_REFERER. Jos olet siirtänyt forumit paikasta toiseen tai vaihtanut domainia, sinun täytyy päivittää "Pää URL" manuaalisesti tietokantaan. (etsi kohta o_base_url config-taulusta) ja tyhjennä sitten välimuisti poistamalla kaikki .php tiedostot /cache kansiosta.',
'Must enter title message'			=>	'Sinun täytyy antaa laudalle nimi.',
'Invalid e-mail message'			=>	'Antamasia ylläpito-sähköpostiosoite on virheellinen.',
'Invalid webmaster e-mail message'	=>	'Antamasia webmaster-sähköpostiosoite on virheellinen.',
'SMTP passwords did not match'		=>	'Sinun täytyy syöttää SMTP-salasana kahteen kertaan tasan samanlaisena muuttaaksesi sitä.',
'Enter announcement here'			=>	'Syötä tiedoituksesi tähän.',
'Enter rules here'					=>	'Syötä sääntösi tähän.',
'Default maintenance message'		=>	'Forumit ovat väliaikasesti pois käytöstä huollon takia. Kokeile uudelleen hetken kuluttua.',
'Timeout error message'				=>	'"Paikalla-aikakatkaisu":n arvon täytyy olla pienempi kuin "Vierailun aikakatkaisu":n arvo.',
'Options updated redirect'			=>	'Asetukset päivitetty. Siirrytään …',
'Options head'						=>	'Asetukset',

// Essentials section
'Essentials subhead'				=>	'Oleellisimmat',
'Board title label'					=>	'Laudan nimi',
'Board title help'					=>	'Tämän laudan nimi (näkyy joka sivun ylälaidassa). Tämä kenttä <strong>EI</strong> saa sisältää HTML-koodia.',
'Board desc label'					=>	'Laudan kuvaus',
'Board desc help'					=>	'Lyhyt kuvaus tästä laudasta (näkyy laudan nimen alla, joka sivun ylälaidassa). Tämä kenttä saa sisältää HTML-koodia.',
'Base URL label'					=>	'Pää URL',
'Base URL help'						=>	'Laudan täysi URL ilman päättävää "/"-merkkiä (esim. http://www.mundomaini.fi/forkka). Tämän <strong>täytyy</strong> olla oikea jotta ylläpito- ja moderointitoiminnot toimisivat. Jos lauta palauttaa "Virheellinen HTTP_REFERER"-virheitä, asetus on luultavasti väärä.',
'Timezone label'					=>	'Oletus aikavyöhyke',
'Timezone help'						=>	'Oletus aikavyöhyke vieraille ja rekisteröiville käyttäjille.',
'DST label'							=>	'Kesäaika',
'DST help'							=>	'Aseta jos kesäaika on voimassa (Siirtää kellon tunnin eteenpäin).',
'Language label'					=>	'Oletuskieli',
'Language help'						=>	'Kieli, joka näkyy vieraille ja käyttäjille jotka eivät ole muuttaneet asetusta profiilistaan. Tämä täytyy päivittää, jos poistat kielipaketin.',
'Default style label'				=>	'Oletustyyli',
'Default style help'				=>	'Tyyli, joka näkyy vieraille ja käyttäjille jotka eivät ole muuttaneet asetusta profiilistaan.',

// Essentials section timezone options (finnish translations grabbed from Wikipedia)
'UTC-12:00'							=>	'(UTC-12:00) Yhdysvallat (Baker, Howland)',
'UTC-11:00'							=>	'(UTC-11:00) Samoa, Uusi-Seelanti (Niue), Yhdysvallat (Amerikan Samoa, Midwaysaaret)',
'UTC-10:00'							=>	'(UTC-10:00) Havaijin-Aleuttien normaaliaika, HST',
'UTC-09:30'							=>	'(UTC-09:30) Ranskan Polynesia (Marquesassaaret)',
'UTC-09:00'							=>	'(UTC-09:00) Alaskan normaaliaika, AKST',
'UTC-08:30'							=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'							=>	'(UTC-08:00) Tyynenmeren normaaliaika, PST',
'UTC-07:00'							=>	'(UTC-07:00) Vuoriston normaaliaika, MST',
'UTC-06:00'							=>	'(UTC-06:00) Keskinen normaaliaika, CST',
'UTC-05:00'							=>	'(UTC-05:00) Itäinen normaaliaika, EST',
'UTC-04:00'							=>	'(UTC-04:00) Atlantin normaaliaika, AST',
'UTC-03:30'							=>	'(UTC-03:30) Newfoundlandin aika, NT',
'UTC-03:00'							=>	'(UTC-03:00) Argentiina, Brasilia, Suriname, Grönlanti, Uruguay',
'UTC-02:00'							=>	'(UTC-02:00) Brasilia',
'UTC-01:00'							=>	'(UTC-01:00) Azorit, Kap Verde, Gröönlanti',
'UTC'								=>	'(UTC) Länsi-Euroopan aika, WET',
'UTC+01:00'							=>	'(UTC+01:00) Keski-Euroopan aika, CET',
'UTC+02:00'							=>	'(UTC+02:00) Itä-Euroopan aika, EET',
'UTC+03:00'							=>	'(UTC+03:00) Moskova, Itä-Afrikka',
'UTC+03:30'							=>	'(UTC+03:30) Iran',
'UTC+04:00'							=>	'(UTC+04:00) Arabiemiraatit, Georgia, Mauritius',
'UTC+04:30'							=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'							=>	'(UTC+05:00) Kazakstan, Paktistan',
'UTC+05:30'							=>	'(UTC+05:30) Intia, Sri Lanka',
'UTC+05:45'							=>	'(UTC+05:45) Nepal',
'UTC+06:00'							=>	'(UTC+06:00) Bangladesh, Bhutan, Kirgistan',
'UTC+06:30'							=>	'(UTC+06:30) Kookossaaret, Myanmar',
'UTC+07:00'							=>	'(UTC+07:00) Indonesia, Kiina, Malesia',
'UTC+08:00'							=>	'(UTC+08:00) Australia, Kiina, Malesia, Singapore',
'UTC+08:45'							=>	'(UTC+08:45) Australia',
'UTC+09:00'							=>	'(UTC+09:00) Japano, Korean tasavalta, Ita-Timor',
'UTC+09:30'							=>	'(UTC+09:30) Australia',
'UTC+10:00'							=>	'(UTC+10:00) Australia, Pohjois-Mariaanit',
'UTC+10:30'							=>	'(UTC+10:30) Australia',
'UTC+11:00'							=>	'(UTC+11:00) Salomonsaaret, Mikronesia',
'UTC+11:30'							=>	'(UTC+11:30) Norfolkinsaari',
'UTC+12:00'							=>	'(UTC+12:00) Uusi-Sland, Fidzi, Kamzathka',
'UTC+12:45'							=>	'(UTC+12:45) Chathamsaaret',
'UTC+13:00'							=>	'(UTC+13:00) Tonga, Phoenixsaaret',
'UTC+14:00'							=>	'(UTC+14:00) Linesaaret',

// Timeout Section
'Timeouts subhead'					=>	'Aika ja aikakatkaisut',
'Time format label'					=>	'Ajan muoto',
'PHP manual'						=>	'PHP-käyttöohjeesta',
'Time format help'					=>	'[Nykyinen muoto: %s]. %s löydät ohjeita.',
'Date format label'					=>	'Päivämäärän muoto',
'Date format help'					=>	'[Nykyinen muoto: %s]. %s löydät ohjeita.',
'Visit timeout label'				=>	'Vieralun aikakatkaisu',
'Visit timeout help'				=>	'Näin monta sekunttia käyttäjän täytyy olla toimeton jotta hänen "viime vierailu"-tietonsa päivittyisivät (vaikuttaa lähinnä uusien viestejen ilmoituksiin).',
'Online timeout label'				=>	'Paikalla-aikakatkaisu',
'Online timeout help'				=>	'Näin monen sekunnin jälkeen käyttäjä poistetaan paikallaolevien listalta.',
'Redirect time label'				=>	'Siirtymisaika',
'Redirect time help'				=>	'Näin monta sekunttia odotetaan, kun siirrytään. Jos arvo on 0, siirtymissivua ei näytetä (ei suositella).',

// Display Section
'Display subhead'					=>	'Näytä',
'Version number label'				=>	'Versionumero',
'Version number help'				=>	'Näytä FluxBB:n versinumero alalaidassa.',
'Info in posts label'				=>	'Käyttäjän tiedot kirjoituksissa',
'Info in posts help'				=>	'Näytä käyttäjän tietoja käyttäjän nimen alla otsikkonäkymässä. Asetus koskee paikka-, rekisteröintipäivä-, kirjoitusten määrä-, ja linkki- (sähköposti ja URL) tietoja.',
'Post count label'					=>	'Käyttäjän kirjoitusten määrä',
'Post count help'					=>	'Näytä montako kertaa käyttäjä on kirjoittanut laudalle (koskee otsikko-, profiili-, ja käyttäjälistanäkymiä.',
'Smilies label'						=>	'Hymiöt kirjoituksissa',
'Smilies help'						=>	'Muuta hymiöt pieniksi graaffisiksi kuvakkeiksi.',
'Smilies sigs label'				=>	'Hymiöt allekirjoituksissa',
'Smilies sigs help'					=>	'Muuta hymiöt pieniksi graaffisiksi kuvakkeiksi allekirjoituksissa.',
'Clickable links label'				=>	'Luo avattavia linkkejä',
'Clickable links help'				=>	'Kun tämä on asetettu, FluxBB tunnistaa URLit automaattisesti ja tekee niistä napsautettavia hyperlinkkejä.',
'Topic review label'				=>	'Aiheen tarkistus',
'Topic review help'					=>	'Näytettävien kirjoitusten maksimimäärä kirjoitettaessa (uusin ensin). Aseta 0 poistaaksesi käytöstä.',
'Topics per page label'				=>	'Otsikoita per sivu',
'Topics per page help'				=>	'Otsikoiden oletusmäärä per sivu forumilla. Käyttäjät voivat mukauttaa tätä asetusta.',
'Posts per page label'				=>	'Kirjoitusta per sivu',
'Posts per page help'				=>	'Kirjoitusten oletusmäärä per sivu otsikossa. Käyttäjät voivat mukauttaa tätä asetusta.',
'Indent label'						=>	'Sisennyksen koko',
'Indent help'						=>	'Jos tämä on 8, tavallista tabulaattoria käytetään [code][/code] tageissa. Muuten sisennyksissä käytetään näin monta välilyöntiä.',
'Quote depth label'					=>	'[quote]-lainauksen maksimisyvyys',
'Quote depth help'					=>	'[quote]-tagejen maksimimäärä toisten [quote]-tagejen sisällä, tästä syvemmällä olevat lainaukset jäävät pois.',

// Features section
'Features subhead'					=>	'Ominaisuudet',
'Quick post label'					=>	'Pikakirjoitus',
'Quick post help'					=>	'Kun tämä on käytössä, FluxBB näyttää pikakirjoituslomakkeen otsikoiden alareunassa. Näin käyttäjät voivat lähettää kirjoituksia suoraan otsikkonäkymästä.',
'Users online label'				=>	'Käyttäjiä paikalla',
'Users online help'					=>	'Näytä pääsivulla tietoja siitä, montako vierasta ja rekisteröitynyttä käyttäjää selaa lautaa tällä hetkellä.',
'Censor words label'				=>	'Sanojen sensurointi',
'Censor words help'					=>	'Aseta tämä käyttöön sensuroidaksesi valittuja sanoja. %s-kohdasta löytyy lisätietoja.',
'Signatures label'					=>	'Allekirjoitukset',
'Signatures help'					=>	'Salli käyttäjien lisätä allekirjoitus kirjoituksiinsa.',
'User ranks label'					=>	'Käyttäjien arvonimet',
'User ranks help'					=>	'Aseta tämä käyttöön ottaaksesi käyttäjien arvonimet käyttöön. %s-kohdasta löytyy lisätietoja.',
'User has posted label'				=>	'Käyttäjä on kirjoittanut aiemmin',
'User has posted help'				=>	'Tämä toiminto näyttää pisteen otsikoiden edessä viewforum.php:ssä jos kirjautunut käyttäjät on kirjoittanut sinne aiemmin. Poista tämä käytöstä jos palvelimen käyttöaste nousee liikaa.',
'Topic views label'					=>	'Otsikoiden lukumäärä',
'Topic views help'					=>	'Pidä silmällä montako kertaa otsikkoa on selattu. Poista tämä käytöstä jos palvelimen käyttöaste nousee liikaa kiireisellä forumilla.',
'Quick jump label'					=>	'Pikahyppy.',
'Quick jump help'					=>	'Ota käyttöön pikahyppyvalikko laudan alareunassa.',
'GZip label'						=>	'GZip ulostulo.',
'GZip help'							=>	'Jos tämä on päällä, FluxBB pakkaa gzip:llä selaimelle lähetettävän datan. Tämä vähentää kaistan käyttöä, mutta käyttää vähän enemmän prosessoritehoja. Tämä vaatii että PHP on configuroitu zlibin kanssa (--with-zlib). Huom: Jos sinulla on jo mod_gzip tai mod_deflate moduuli Apachessa käytössä pakkaamassa PHP-scriptejä, sinun kannattaa poistaa tämä käytöstä..',
'Search all label'					=>	'Etsi kaikista forumeista',
'Search all help'					=>	'Kun tämä on pois käytöstä, haku tehdään yhteen forumin kerrallaan. Poista käytöstä jos palvelin käyttöaste on korkea etsinnän takia.',
'Menu items label'					=>	'Ylimääräiset valikkonappulat',
'Menu items help'					=>	'Tästä voit lisätä rajattoman määrän ylimääräisiä valikkonappuloita, lisäämä HTML hyperlinkkejä tekstikenttään. Linkkejen muoto on X = &lt;a href="URL"&gt;LINK&lt;/a&gt; missä X on linkin sijainti (esim. 0 asettaa linkin alkuun ja 2 asettaa linkin "käyttäjälista":n jälkeen). Linkit erotetaan välilyönneillä.',

// Feeds section
'Feed subhead'						=>	'Syötteet',
'Default feed label'				=>	'Syötteen oletustyyppi',
'Default feed help'					=>	'Valitse näytettävän syötteen tyyppi. Huom: Valitsemalla "ei mitään" syötteet eivät poistu käytöstä, ne vain eivät näy oletuksena.',
'None'								=>	'ei mitään',
'RSS'								=>	'RSS',
'Atom'								=>	'Atom',
'Feed TTL label'					=>	'Syötteiden aika välimuistissa',
'Feed TTL help'						=>	'Syötteet voidaan tallentaa välimuistiin resurssejen säästämiseksi.',
'No cache'							=>	'Älä tallenna välimuistiin',
'Minutes'							=>	'%d minuuttia',

// Reports section
'Reports subhead'					=>	'Raportit',
'Reporting method label'			=>	'Raportointimenetelmä',
'Internal'							=>	'Sisäinen',
'By e-mail'							=>	'Sähköposti',
'Both'								=>	'Molemmat',
'Reporting method help'				=>	'Valitse miten raportit käsitellään. Voit valita sisäisen raporttijärjestelmän, sähköpostit alla olevaan sähköpostilistaan, tai molemmat.',
'Mailing list label'				=>	'Sähköpostilista',
'Mailing list help'					=>	'Pilkuilla eroteltu lista vastaanottajista. Listan henkilöt ovat raporttejen vastaanottajia.',

// Avatars section
'Avatars subhead'					=>	'Avatarit',
'Use avatars label'					=>	'Käytä avatareja',
'Use avatars help'					=>	'Kun tämä on päällä, käyttäjät voivat valita itselleen kuvan joka näkyy arvonimen alapuolella.',
'Upload directory label'			=>	'Lähetyskansio',
'Upload directory help'				=>	'Kansio johon avatarit tallennetaan (FluxBB:n juurihakemiston alla). PHP:lla täytyy olla kirjoitusoikeus tähän kansioon.',
'Max width label'					=>	'Maksimileveys',
'Max width help'					=>	'Avatarin korkein sallittu leveys pikseleinä (60 on suositeltu).',
'Max height label'					=>	'Maksimikorkeus',
'Max height help'					=>	'Avatarin korkein sallittu korkeus pikseleinä (60 on suositeltu).',
'Max size label'					=>	'Maksimikoko',
'Max size help'						=>	'Avatarin korkein sallittu koko tavuina (10240 on suositeltu).',

// E-mail section
'E-mail subhead'					=>	'Sähköposti',
'Admin e-mail label'				=>	'Ylläpidon sähköpostiosoite',
'Admin e-mail help'					=>	'Ylläpitäjän sähköpostiosoite.',
'Webmaster e-mail label'			=>	'Webmasterin sähköpostiosoite',
'Webmaster e-mail help'				=>	'Kaikki laudan lähettämät sähköpostit tulevat tästä osoitteesta.',
'Forum subscriptions label'			=>	'Forumin seuranta',
'Forum subscriptions help'			=>	'Käyttäjät voivat seurata forumia (käyttäjälle lähetetään sähköposti kun joku luo uuden otsikon).',
'Topic subscriptions label'			=>	'Otsikon seuranta',
'Topic subscriptions help'			=>	'Käyttäjät voivat seurata otsikoita (käyttäjälle lähetetään sähköposti kun joku vastaa).',
'SMTP address label'				=>	'SMTP palvelimen osoite',
'SMTP address help'					=>	'Ulkoisen SMTP palvelimen osoite jolla sähköpostit lähetetän. Voit antaa myös porttinumeron, mikäli SMTP palvelin ei käytä oletusporttia 25. (esim: posti.mundomaini.fi:3580). Jätä tyhjäksi käyttääksesi paikallista sähköpostiohjelmaa.',
'SMTP username label'				=>	'SMTP käyttäjänimi',
'SMTP username help'				=>	'SMTP palvelimen käyttäjänimi. Jätä tyhjäksi jos SMTP palvelin ei vaadi käyttäjänimeä (useimmat palvelimet <strong>eivät</strong> vaadi kirjautumista).',
'SMTP password label'				=>	'SMTP salasana',
'SMTP change password help'			=>	'Valitse tämä jos haluat muuttaa tai poistaa tallennetun salasanan.',
'SMTP password help'				=>	'SMTP palvelimen salasana. Jätä tyhjäksi jos SMTP palvelin ei vaadi salasanaa (useimmat palvelimet <strong>eivät</strong> vaadi kirjautumista). Kirjoita kahteen kertaan varmistaaksesi salasana.',
'SMTP SSL label'					=>	'Salaa SMTP SSL-tekniikalla',
'SMTP SSL help'						=>	'Salaa yhteyden SMTP palvelimen SSL:n avulla. Kannattaa käyttää vain jos SMTP palvelin vaatii sen ja jos PHP versiosi tukee SSL:ää.',

// Registration Section
'Registration subhead'				=>	'Rekisteröinti',
'Allow new label'					=>	'Salli uudet rekisteröinnit',
'Allow new help'					=>	'Määrää, salliiko lauta uusien käyttäjien rekisteröinnin. Poista käytöstä ainoastaan erityistapauksissa.',
'Verify label'						=>	'Vahvista rekisteröinnit',
'Verify help'						=>	'Kun tämä on päällä, käyttäjälle lähetetään sattumanvarainen salasana sähköpostitse kun hän rekisteröityy. Salasanan voi halutessaan vaihtaa profiilista, kun on kirjautunut sisään ensimmäistä kertaa. Tämä toiminto vaatii käyttäjän myös vahvistamaan uuden sähköpostiosoitteen jos hän päättää vaihtaa sen myöhemmin. Näin vältetään tehokkaasti rekisteröinnin väärinkäyttö, ja varmistetaan että kaikilla käyttäjillä on profiilissaan "oikea" sähköpostiosoite.',
'Report new label'					=>	'Raportoi uusista rekisteröinneistä',
'Report new help'					=>	'Kun tämä on päällä, FluxBB ilmoittaa aiemmin määritetyn sähköpostilistan jäsenille uusista rekisteröinneistä.',
'Use rules label'					=>	'Forumin säännöt',
'Use rules help'					=>	'Kun tämä on päällä, käyttäjän täytyy hyväksyä alempana määritetyt säännöt ennen kuin hän voi rekisteröityä. Säännöt voi aina lukea joka sivulla näkyvän navigointipalkissa olevan linkin kautta.',
'Rules label'						=>	'Kirjoita sääntösi tähän',
'Rules help'						=>	'Tähän voit kirjoittaa säännöt tai muut tiedot jotka käyttäjän täytyy lukea ja hyväksyä ennen rekisteröintiä. Jos asetit aiemmin säännöt käyttöön, sinun täytyy kirjoittaa tähän jotain, muuten säännöt poistetaan käytöstä. Tekstiä ei käsitellä kuten tavallisia kirjoituksia, ja näin ollen se saa sisältää HTML-koodia.',
'E-mail default label'				=>	'Sähköpostin oletusasetukset',
'E-mail default help'				=>	'Valitse oletuksena käytettävät tietoturva-asetukset.',
'Display e-mail label'				=>	'Näytä sähköpostiosoite muilla käyttäjille.',
'Hide allow form label'				=>	'Piiloita sähköpostiosoite mutta salli sähköpostin lähetys lomakkeen kautta.',
'Hide both label'					=>	'Piiloita sähköpostiosoite äläkä salli sähköpostin lähetystä lomakkeen kautta.',

// Announcement Section
'Announcement subhead'				=>	'Tiedoitukset',
'Display announcement label'		=>	'Näytä tiedoitus',
'Display announcement help'			=>	'Aseta tämä käyttöön näyttääksesi alla oleva tietoditus laudalla.',
'Announcement message label'		=>	'Tiedoitusviesti',
'Announcement message help'			=>	'Tätä tekstiä ei käsitellä kuten tavallisia kirjoituksia, ja näin ollen se saa sisältää HTML-koodia.',

// Maintenance Section
'Maintenance subhead'				=>	'Huolto',
'Maintenance mode label'			=>	'Huoltotila',
'Maintenance mode help'				=>	'Kun tämä on päällä, vain ylläpitäjät pääsevät lautaan käsiksi. Tätä tulee käyttää, jos lauta täytyy poistaa käytössä huollon ajaksi. <strong>VAROITUS! Älä kirjaudu ulos kun lauta on huoltotilassa.</strong> Et pysty kirjautumaan sisään uudelleen.',
'Maintenance message label'			=>	'Huoltoviesti',
'Maintenance message help'			=>	'Tämä viesti näytetään käyttäjille kun lauta on huoltotilassa. Jos tämä on tyhjä, näytetään oletusviesti. Tätä tekstiä ei käsitellä kuten tavallisia kirjoituksia, ja näin ollen se saa sisältää HTML-koodia.',

);
