<?php

// Language definitions used in admin-users.php
// Finnish translation by Pauligrinder
$lang_admin_users = array(

'Non numeric message'		=>	'Syötit ei-numeerisen arvon numeeriseen kenttään.',
'Invalid date time message'	=>	'Syötit virheellisen ajan/päivämäärän.',
'Not verified'				=>	'Ei vahvistettu',

// Actions: mass delete/ban etc.
'No users selected'			=>	'Käyttäjiä ei valittu.',
'No move admins message'	=>	'Turvallisuussyistä et voi siirtää montaa ylläpitäjää kerralla toiseen ryhmään. Jos haluat siirtää nämä ylläpitäjät, voit tehdä sen heidän käyttäjäprofiilejensa kautta.',
'No delete admins message'	=>	'Ylläpitäjiä ei voi poistaa. Poistaaksesi ylläpitäjiä, sinun täytyy ensin siirtää heidät eri käyttäjäryhmään.',
'No ban admins message'		=>	'Ylläpitäjiä ei voi bannata. Bannataksesi ylläpitäjiä, sinun täytyy ensin siirtää heidät eri käyttäjäryhmään.',
'No ban mods message'		=>	'Moderaattoreita ei voi bannata. Bannataksesi moderaattoreita, sinun täytyy ensin siirtää heidät eri käyttäjäryhmään.',
'Move users'				=>	'Vaihda käyttäjän ryhmää',
'Move users subhead'		=>	'Valitsen käyttäjän uusi ryhmä',
'New group label'			=>	'Uusi ryhmä',
'New group help'			=>	'Valitse ryhmä, johon valitut käyttäjät siirretään. Turvallisuussyistä, et voi siirtää montaa käyttäjää kerralla ylläpitäjät-ryhmään.',
'Invalid group message'		=>	'Virheellinen ryhmä ID.',
'Users move redirect'		=>	'Käyttäjäryhmiä muokattu. Siirrytään …',
'Delete users'				=>	'Poista käyttäjiä',
'Confirm delete legend'		=>	'Tärkeää: lue tämä ennen kuin poistat käyttäjiä',
'Confirm delete info'		=>	'Vahvista että haluat poistaa nämä käyttäjät.',
'Delete posts'				=>	'Poista kaikki näiden käyttäjien kirjoitukset ja otsikot.',
'Delete warning'			=>	'Varoitus! Poistettuja käyttäjiä ja/tai kirjoituksia ei voi palauttaa. Jos päätät olla poistamatta näiden käyttäjien kirjoituksia, ne voidaan ainoastaan poistaa yksitellen myöhemmin.',
'Users delete redirect'		=>	'Käyttäjät poistettu. Siirrytään …',
'Ban users'					=>	'Bannaa käyttäjiä',
'Message expiry subhead'	=>	'Bannausviesti ja voimassaoloaika',
'Ban message label'			=>	'Bannausviesti',
'Ban message help'			=>	'Viesti jonka bannattu käyttäjä näkee saapuessaan laudalle.',
'Expire date label'			=>	'Vanhenemispäivä',
'Expire date help'			=>	'Päivä, jolloin banni poistetaan automaattiseti (muodossa vvvv-kk-pp). Jätä tyhjäksi poistaaksesi manuaalisesti',
'Ban IP label'				=>	'Bannaa IP-osoitteita',
'Ban IP help'				=>	'Bannaa myös käyttäjien IP-osoitteet jotta uuden käyttäjätilin rekisteröiminen vaikeutuisi.',
'Invalid date message'		=>	'Syötit virheellisen vanhenemispäivän.',
'Invalid date reasons'		=>	'Päivämäärän täytyy olla muodossa VVVV-KK-PP ja vähintään päivän verran tulevaisuudessa.',
'Users banned redirect'		=>	'Käyttäjät bannattu. Siirrytään …',

'User search head'			=>	'Käyttäjähaku',
'User search subhead'		=>	'Syötä hakusanat',
'User search info'			=>	'Etsi käyttäjiä tietokannasta. Voit antaa yhden tai useampia hakusanoja. Jokerimerkit tähden muodossa (*) ovat sallittuja.',
'Username label'			=>	'Käyttäjänimi',
'E-mail address label'		=>	'Sähköpostiosoite',
'Title label'				=>	'Titteli',
'Real name label'			=>	'Oikea nimi',
'Website label'				=>	'Nettiosoite',
'Jabber label'				=>	'Jabber',
'ICQ label'					=>	'ICQ',
'MSN label'					=>	'MSN Messenger',
'AOL label'					=>	'AOL IM',
'Yahoo label'				=>	'Yahoo Messenger',
'Location label'			=>	'Sijainti',
'Signature label'			=>	'Allekirjoitus',
'Admin note label'			=>	'Ylläpitäjän huomautus',
'Posts more than label'		=>	'Kirjoittanut yli _ kertaa',
'Posts less than label'		=>	'Kirjoittanut alle _ kertaa',
'Last post after label'		=>	'Viimeisin kirjoitus jälkeen',
'Date help'					=>	'(vvvv-kk-pp tt:mm:ss)',
'Last post before label'	=>	'Viimeisin kirjoitus ennen',
'Registered after label'	=>	'Rekisteröitynyt jälkeen',
'Registered before label'	=>	'Rekisteröitynyt ennen',
'Order by label'			=>	'Järjestä',
'Order by username'			=>	'Käyttäjänimen mukaan',
'Order by e-mail'			=>	'Sähköpostiosoitteen mukaan',
'Order by posts'			=>	'Kirjoitusten määrän mukaan',
'Order by last post'		=>	'Viimeisimmän kirjoituksen mukaan',
'Order by registered'		=>	'Rekisteröinnin mukaan',
'Ascending'					=>	'Nousevassa järjestyksessä',
'Descending'				=>	'Laksevassa järjestyksessä',
'User group label'			=>	'Käyttäjäryhmä',
'All groups'				=>	'Kaikki ryhmät',
'Unverified users'			=>	'Vahvistamattomat käyttäjät',
'Submit search'				=>	'Suorita haku',
'IP search head'			=>	'IP haku',
'IP search subhead'			=>	'Syötä etsittävä IP',
'IP address label'			=>	'IP-osoite',
'IP address help'			=>	'IP-osoite jota etsitään kirjoitustietokannasta.',
'Find IP address'			=>	'Etsi IP-osoite',

'Results head'				=>	'Hakutulokset',
'Results username head'		=>	'Käyttäjänimi',
'Results e-mail head'		=>	'Sähköpostiosoite',
'Results title head'		=>	'Titteli/Tila',
'Results posts head'		=>	'Kirjoituksia',
'Results admin note head'	=>	'Ylläpitäjän huomautus',
'Results actions head'		=>	'Toiminnot',
'Results IP address head'	=>	'IP-osoite',
'Results last used head'	=>	'Viimeksi käytetyt',
'Results times found head'	=>	'Kertaa löytynyt',
'Results action head'		=>	'Toiminto',
'Results find more link'	=>	'Etsi lisää käyttäjiä tästä IP:stä',
'Results no posts found'	=>	'Tässä forumissa ei tällä hetkellä ole yhtään tämän käyttäjän kirjoituksia.',
'Select'					=>	'Valitse',
'Select all'				=>	'Valitse kaikki',
'Unselect all'				=>	'Poista kaikki valinnat',
'Ban'						=>	'Bannaa',
'Delete'					=>	'Poista',
'Change group'				=>	'Vaihda ryhmää',
'Bad IP message'			=>	'Annettu IP-osoite ei ole oikeassa muodossa.',
'Results view IP link'		=>	'Näytä IP:n tiedot',
'Results show posts link'	=>	'Näytä kirjoitukset',
'Results guest'				=>	'Vieras',
'Results no IP found'		=>	'Annettua IP:tä ei löytynyt tietokannasta.',
'No match'					=>	'Ei tuloksia.'

);
