<?php

// Language definitions used in install.php, localized by adaur
// Finnish translation by Pauligrinder

$lang_install = array(

'Install message'				=>	'Tiedostoa \'config.php\' ei ole, tai se on vioittunut. Tämän perusteella näyttää siltä ettei FluxBB:tä ole vielä asennettu..',
'Choose install language'		=>	'Valitse asennusscriptin kieli',
'Choose install language info'	=>	'Asennusscriptin käyttämä kieli. Itse laudan oletuskielen voit valita alempaa.',
'Install language'				=>	'Asennuskieli',
'Change language'				=>	'Vaihda kieli',
'Next'							=>	'Seuraava',
'Already installed'				=>	'Vaikuttaa siltä että FluxBB on jo asennettu. Mene osoitteeseen <a href="index.php">here</a>.',
'You are running error'			=>	'Käytössä on %1$s versio %2$s. FluxBB %3$s vaatii ainakin %1$s %4$s toimiakseen kunnolla. Sinun täytyy päivittää %1$s asennuksesi ennen kuin voit jatkaa asennusta.',
'My FluxBB Forum'				=>	'Minun FluxBB Forumini',
'Description'					=>	'Ikävä kyllä sanat eivät riitä FluxBB:n kuvaamiseen - se täytyy kokea henkilökohtaisesti.',
'Username 1'					=>	'Käyttäjänimien täytyy olla ainakin 2 merkkiä pitkiä.',
'Username 2'					=>	'Käyttäjänimet eivät saa olla yli 25 merkkiä pitkiä.',
'Username 3'					=>	'Käyttäjänimi guest on varattu vieraille.',
'Username 4'					=>	'Käyttäjänimet eivät saa olla IP-osoitteen muodossa.',
'Username 5'					=>	'Käyttäjänimet eivät saa sisältää merkkejä \', " ja [ tai ] samanaikaisesti.',
'Username 6'					=>	'Käyttäjänimet eivät saa sisältää forumin käyttämiä BBCode-tageja.',
'Short password'				=>	'Salasanojen täytyy olla vähintään 4 merkkiä pitkiä.',
'Passwords not match'			=>	'Salasanat eivät olleet samat.',
'Wrong email'					=>	'Syöttämäsi ylläpitäjän sähköpostiosoite on virheellinen.',
'No board title'				=>	'Laudalle täytyy antaa nimi.',
'Error default language'		=>	'Valittua oletuskieltä ei näytä olevan olemassa.',
'Error default style'			=>	'Valittua oletustyyliä ei näytä olevan olemassa.',
'No DB extensions'				=>	'Tämä PHP-ympäristö ei näytä tukevan mitään tietokantatyyppiä mitä FluxBB tukee. PHP:n täytyy tukea joko MySQL:ää, PostgreSQL:ää tai SQLitea jotta FluxBB voitaisiin asentaa.',
'Administrator username'		=>	'Ylläpitäjän käyttäjänimi',
'Administrator password 1'		=>	'Ylläpitäjän salasana 1',
'Administrator password 2'		=>	'Ylläpitäjän salasana 2',
'Administrator email'			=>	'Ylläpitäjän sähköpostiosoite',
'Board title'					=>	'Laudan otsikko',
'Base URL'						=>	'Pää URL',
'Required field'				=>	'on pakollinen kenttä tässä lomakkeessa.',
'FluxBB Installation'			=>	'FluxBB:n asennus',
'Welcome'						=>	'Olet asentamassa FluxBB:n. Asentaaksesi FluxBB:n, sinun täytyy täyttää alla oleva lomake. Mikäli asennuksen aikana tulee vaikeuksia, voit etsiä apua FluxBB:n dokumentaatiosta.',
'Install'						=>	'Asenna FluxBB 1.4',
'Errors'						=>	'Seuraavat virheet täytyy korjata:',
'Database setup'				=>	'Tietokannan asennus',
'Info 1'						=>	'Ole hyvä ja syötä pyydetyt tiedot asentaaksesi FluxBB:n tietokannan. Sinulla täytyy olla kaikki tarvittavat tiedot hallussasi ennen kuin asennusta voi jatkaa.',
'Select database'				=>	'Valitse tietokannan tyyppi',
'Info 2'						=>	'FluxBB tukee tällä hetkellä MySQL:ää, PostgreSQL:ää ja SQLitea. Jos haluamasi tietokantatyyppi puuttuu listalta, se tarkoittaa että PHP-ympäristö ei tue kyseistä tietokantatyyppiä. Lisää tietoa jokaisen tietokantatyypin tuetuista versioista löytyy FluxBB:n FAQ:sta.',
'Dual MySQL'					=>	'FluxBB on tunnistanut että PHP-ympäristösi tukee kahta tapaa kommunikoida MySQL:n kanssa. Vaihtoehdot ovat tavallinen ja paranneltu. Jos olet epävarma kumpaa tulisi käyttää, kokeile ensin paranneltua, ja jos se ei toimi, niin kokeile sitten tavallista.',
'InnoDB'						=>	'FluxBB on tunnistanut että MySQL palvelin saattaa tukea<a href="http://dev.mysql.com/doc/refman/5.0/en/innodb.html">InnoDB:tä</a>. Tämä on hyvä valinta jos aiot pyörittää isoa forumia. Jos olet epävarma, on suositeltavaa olla käyttämättä InnoDB:tä.',
'Database type'					=>	'Tietokannan tyyppi',
'Required'						=>	'(Pakollinen)',
'Database hostname'				=>	'Syötä tietokantapalvelimen osoite',
'Info 3'						=>	'Tietokantapalvelimen osoite (esimerkiksi: localhost, db.myhost.com tai 192.168.0.15). Voit ilmoittaa myös porttinumeron jos tietokantasi ei käytä oletusporttia (esim: localhost:3580). Jos käytössä on SQLite, syötä tähän mitä tahansa tai jätä muotoon \'localhost\'.',
'Database server hostname'		=>  'Tietokantapalvelimen osoite',
'Database enter name'			=>	'Anna tietokannan nimi',
'Info 4'						=>	'Tietokannan nimi, johon FluxBB asennetaan. Tietokannan täytyy olla olemassa. Jos kyseessä on SQLite, tämä on suhteellinen polku tietokantatiedostoon. Turvallisuussyistä, SQLite-tietokanta kannattaa laittaa yksityiseen kansioon (johon ei pääse verkon kautta käsiksi) jos se on mahdollista. Jos SQLite-tietokantaa ei ole olemassa, FluxBB yrittää luoda sen.',
'Database name'					=>	'Tietokannan nimi',
'Database enter informations'	=>	'Ilmoita tietokannan käyttäjänimi ja salasana',
'Database username'				=>	'Tietokannan käyttäjänimi',
'Info 5'						=>	'Anna käyttäjänimi ja salasana joilla kirjaudutaan tietokantaan. Jätä huomioimatta jos kyseessä on SQLite.',
'Database password'				=>	'Tietokannan salasana',
'Database enter prefix'			=>	'Syötä tietokannan taulukon etuliite',
'Info 6'						=>	'Jos haluat, voit antaa tietokannan taulukolle oman etuliitten. Tällä tavalla voit asentaa monta eri FluxBB:tä samaan tietokantaan (esim: foo_).',
'Table prefix'					=>	'Taulukon etuliite',
'Administration setup'			=>	'Ylläpitoasetukset',
'Info 7'						=>	'Ole hyvä ja ilmoita pyydetyt tiedot asettaaksesi FluxBB-asennuksellesi ylläpitäjä.',
'Admin enter username'			=>	'Anna ylläpitäjän käyttäjänimi',
'Info 8'						=>	'Forumin ylläpitäjän käyttäjänimi. Voit luoda lisää ylläpitäjiä ja moderaattoreita myöhemmin. Käyttäjänimet voivat olla 2-25 merkkiä pitkiä.',
'Admin enter password'			=>	'Syötä ja vahvista ylläpitäjän salasana.',
'Info 9'						=>	'Salasanojen täytyy olla vähintään 4 merkkiä pitkä, ja ne ovat kirjainkokoriippuvaisia.',
'Password'						=>	'Salasana',
'Confirm password'				=>	'Vahvista salasana',
'Admin enter email'				=>	'Syötä ylläpitäjän sähköpostiosoite',
'Info 10'						=>	'Forumin ylläpitäjän sähköpostiosoite.',
'Board setup'					=>	'Laudan asetukset',
'Info 11'						=>	'Syötä pyydetyt tiedot ottaaksesi FluxBB-lautasi käyttöön.',
'Enter board title'				=>	'Syötä laudan nimi',
'Info 12'						=>	'Tämän laudan nimi (näkyy joka sivun ylälaidassa).',
'Enter board description'		=>	'Syötä laudan kuvaus',
'Info 13'						=>	'Lyhyt kuvaus tästä laudasta (näkyy joka sivun ylälaidassa, laudan nimen alla). Tämä kenttä saa sisältää HTML-koodia.',
'Board description'				=>	'Laudan kuvaus',
'Enter base URL'				=>	'Syötä FluxBB-asennuksen pää URL',
'Info 14'						=>	'FluxBB forumin URL, ilman päättävää "/"-merkkiä (esim: http://forum.munservu.fi tai http://munservu.com/~munkayttaja). Tämän <strong>täytyy</strong> olla kunnossa, muuten ylläpitäjät ja moderaattorit eivät pysty lähettämään lomakkeiden tietoja. Huomaa että oletusarvo on vain FluxBB:n arvaus.',
'Choose the default language'	=>	'Valitse oletuskieli',
'Info 15'						=>	'Oletuskieli, joka näkyy vieraille ja käyttäjille jotka eivät ole vaihtaneet kieltä profiilistaan.',
'Default language'				=>	'Oletuskieli',
'Choose the default style'		=>	'Valitse oletustyyli',
'Info 16'						=>	'Oletustyyli, joka näkyy vieraille ja käyttäjille jotka eivät ole vaihtaneet kieltä profiilistaan.',
'Default style'					=>	'Oletustyyli',
'Start install'					=>	'Aloita asennus',
'DB type not valid'				=>	'\'%s\' ei ole kelvollinen tietokantatyyppi',
'Table prefix error'			=>	'Taulukon etuliite \'%s\' sisältää kiellettyjä merkkejä tai on liian pitkä. Etuliite saa sisältää kirjaimia a:sta z:aanm numeroita, ja alaviivoja. Se ei kuitenkaan saa alkaa numerolla. Maksimipituus on 40 merkkiä. Valitse jokin muu Etuliite.',
'Prefix reserved'				=>	'Taulukon etuliite \'sqlite_\' on vaarattu SQLiten moottorin käyttöön. Valitse toinen etuliite',
'Existing table error'			=>	'Taulukko nimeltään \'%susers\' on jo olemassa tietokannassa \'%s\'. Tämä saattaa tarkoittaa, että FluxBB on jo asennettu, tai toinen ohjelmisto joka käyttää FluxBB:n vaatimia taulukon nimiä on asennettu samaan tietokantaan. Jos haluat asentaa monta FluxBB-kopiota samaan tietokantaan, niissä täytyy olla eri taulukon etuliitteet',
'InnoDB off'					=>	'InnoDB ei näytä olevan käytössä. Valitse tietokantatyyppi joka ei käytä InnoDB:tä, tai ota InnoDB käyttöön MySQL-palvelimestasi',
'Administrators'				=>	'Ylläpitäjät',
'Administrator'					=>	'Ylläpitäjä',
'Moderators'					=>	'Moderaattorit',
'Moderator'						=>	'Moderaattori',
'Guests'						=>	'Vieraat',
'Guest'							=>	'Vieras',
'New member'					=>	'Uusi jäsen',
'Members'						=>	'Jäsenet',
'Member'						=>	'Jäsen',
'Announcement'					=>	'Syötä tiedoituksesi tähän.',
'Rules'							=>	'Syötä sääntösi tähän',
'Maintenance message'			=>	'Forumit ovat väliaikaisesti pois käytöstä huollon takia. Kokeile uudelleen hetken kuluttua.',
'Test post'						=>	'Testikirjoitus',
'Message'						=>	'Jos näet tämän (ja niinhän sinä näet), niin FluxBB:n asennus näyttää onnistuneen! Kirjaudu sisään ja mene ylläpitovalikkoon configuroidaksesi forumiasi.',
'Test category'					=>	'Testiluokka',
'Test forum'					=>	'Testiforumi',
'This is just a test forum'		=>	'Tämä on vain testiforumi',
'Alert cache'					=>	'<strong>Välimuistikansioon ei ole kirjoitusoikeuksia!</strong> FluxBB ei toimi kunnolla jos PHP ei pysty kirjoittamaan kansioon <em>%s</em>. Käytä chmodia asettaaksesi kansion oikeudet kuntoon. Jos olet epävarma, chmodaa arvoon 0777.',
'Alert avatar'					=>	'<strong>Avatarikansioon ei ole kirjoitusoikeuksia!</strong> Jos haluat että käyttäjät voivat lähettää omia avatareja forumille, PHP:lla täytyy olla kirjoitusoikeus kansioon <em>%s</em>. Voit vaihtaa avatarejen tallennuskansiota myöhemmin (kts. Ylläpito/Asetukset). Käytä chmodia asettaaksesi kansion oikeudet kuntoon. Jos olet epävarma, chmodaa arvoon 0777.',
'Alert upload'					=>	'<strong>Palvelin ei näytä hyväksyvän tiedostojen lähettämistä!</strong> Jos haluat että käyttäjät voivat lähettää omia avatareja forumille, "file_uploads" PHP-asetuksen täytyy olla päällä. Kun tiedostojen lähetys on otettu käyttöön, avatarit voi ottaa käyttöön kohdasta Ylläpito/Asetukset/Avatarit.',
'FluxBB has been installed'		=>	'FluxBB on asennettu. Seuraa alla olevia ohjeita valmistellaksesi asennus.',
'Final instructions'			=>	'Viimeiset ohjeet',
'Info 17'						=>	'Valmistellaksesi asennus, sinun pitää napsauttaa alla olevaa nappulaa ladataksesi tiedosto nimeltään config.php. Sinun pitää lähettää tämä tiedosto FluxBB-asennuksesi juurihakemistoon.',
'Info 18'						=>	'Kun olet lähettänyt config.php-tiedoston, FluxBB on täysin asennettu! Tässä vaiheessa voit <a href="index.php">siirtyä forumin pääsivulle</a>.',
'Download config.php file'		=>	'Lataa config.php-tiedosto',
'FluxBB fully installed'		=>	'FluxBB on täysin asennettu! Nyt voit <a href="index.php">siirtyä forumin pääsivulle</a>.',

);
