<?php

// Language definitions used in profile.php
// Finnish translation by Pauligrinder
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'Profiilivalikko',
'Section essentials'			=>	'Oleellisimmat',
'Section personal'				=>	'Henkilökohtaiset',
'Section messaging'				=>	'Viestintä',
'Section personality'			=>	'Persoonallisuus',
'Section display'				=>	'Ulkoasu',
'Section privacy'				=>	'Suojaus',
'Section admin'					=>	'Ylläpitovalikko',

// Miscellaneous
'Username and pass legend'			=>	'Syötä käyttäjänimi ja salasana',
'Personal details legend'			=>	'Syötä henkilökohtaisia tietoja',
'Contact details legend'			=>	'Syötä viestintätiedot',
'User activity'                     =>	'Käyttäjän aktiivisuus',
'Paginate info'                     =>	'Montako aihetta tai kirjoitusta haluat nähdä joka sivulla?',

// Password stuff
'Pass key bad'					=>	'Aikaa on kulunut liikaa. Yritä uudelleen. Jos ei onnistu niin ota yhteyttä ylläpitoon @',
'Pass updated'					=>	'Salasana päivitetty. Voit nyt kirjautua uudella passullasi.',
'Pass updated redirect'			=>	'Salasana päivitetty. Siirrytään …',
'Wrong pass'					=>	'Vanha salasana oli väärä.',
'Change pass'					=>	'Muuta salasanaa',
'Change pass legend'				=>	'Syötä ja vahvista uusi salasana',
'Old pass'					=>	'Vanha salasana',
'New pass'					=>	'Uusi salasana',
'Confirm new pass'				=>	'Vahvista uusi salasana',
'Pass info'					=>	'Salasanan täytyy olla vähintään 4 merkkiä pitkä ja se on kirjainkokoriippuvainen.',

// Email stuff
'Email key bad'					=>	'Aikaa on kulunut liikaa. Yritä uudelleen. Jos ei onnistu niin ota yhteyttä ylläpitoon @',
'Email updated'					=>	'Osoite päivitetty.',
'Activate email sent'				=>	'Sinulle on lähetetty sähköposti josta löytyy lisätietoja. Jos se ei saavu, ota yhteys ylläpitoon @',
'Email legend'					=>	'Syötä uusi sähköpostiosoite',
'Email instructions'				=>	'Sinulle lähetetään sähköposti jossa on aktivointilinkki. Sinun täytyy avata linkki vaihtaaksesi salasanaa.',
'Change email'					=>	'Vaihda säköpostiosoitetta',
'New email'					=>	'Uusi sähköpostiosoite',

// Avatar upload stuff
'Avatars disabled'				=>	'Ylläpito on poistanut avatarit käytöstä.',
'Too large ini'					=>	'Liian iso tiedosto.',
'Partial upload'				=>	'Tiedosto lähetettiin vain osittain. Kokeile uudelleen.',
'No tmp directory'				=>	'PHP ei kyennyt tallentamaan tiedostoa tilapäiseen paikkaan.',
'No file'					=>	'Et valinnut tiedostoa.',
'Bad type'					=>	'Väärän tyyppinen tiedosto. Ainoastaan gif, jpeg ja png ovat sallittuja.',
'Too wide or high'				=>	'Liian iso tiedosto (pikseleinä).',
'Too large'					=>	'Liian iso tiedosto (tavuina)',
'pixels'					=>	'pikseliä',
'bytes'						=>	'tavua',
'Move failed'					=>	'Tiedostoa ei voitu tallentaa. ota yhteyttä ylläpitoon @',
'Unknown failure'				=>	'Tuntematon virhe. Kokeile uudelleen.',
'Avatar upload redirect'			=>	'Avatari lähetetty. Siirrytään …',
'Avatar deleted redirect'			=>	'Avatari poistettu. Siirrytään …',
'Avatar desc'					=>	'Avatari on pieni kuva joka näkyy kirjoituksesi vieressä. Se ei saa olla isompi kuin',
'Upload avatar'					=>	'Lähetä avatari.',
'Upload avatar legend'				=>	'Valitse lähetettävä kuva',
'Delete avatar'					=>	'Poista avatari', // only for admins
'File'						=>	'Tiedosto',
'Upload'					=>	'Lähetä', // submit button

// Form validation stuff
'Forbidden title'				=>	'Käytit kiellettyä sanaa.',
'Profile redirect'				=>	'Profiili päivitetty. Siirrytään …',

// Profile display stuff
'Users profile'					=>	'%s\n profiili',
'Username info'					=>	'Käyttäjänimi: %s',
'Email info'					=>	'Säköposti: %s',
'Posts info'					=>	'Kirjoituksia: %s',
'Registered info'				=>	'Rekisteröityi: %s',
'Last post info'				=>	'Viimeisin kirjoitus: %s',
'Last visit info'				=>	'Viimeisin vierailu: %s',
'Show posts'					=>	'Näytä kaikki kirjoitukset',
'Show topics'					=>	'Näytä kaikki aiheet',
'Show subscriptions'				=>	'Näytä kaikki seuraukset',
'Realname'					=>	'Oikea nimi',
'Location'					=>	'Sijainti',
'Website'					=>	'Nettiosoite',
'Jabber'					=>	'Jabber',
'ICQ'						=>	'ICQ',
'MSN'						=>	'MSM Messenger',
'AOL IM'					=>	'AOL IM',
'Yahoo'						=>	'Yahoo! Messenger',
'Avatar'					=>	'Avatari',
'Signature'					=>	'Allekirjoitus',
'Sig max size'					=>	'Pituus: korkeintaan %s merkkiä / %s riviä',
'Avatar legend'					=>	'Avatarin näyttöasetukset',
'Avatar info'					=>	'Avatari on pieni kuva joka näkyy kirjoitustesi vieressä. Voit lähettää avatarin täältä.',
'Change avatar'					=>	'Vaihda avataria',
'Signature legend'				=>	'Luo allekirjoitus',
'Signature info'				=>	'Allekirjoitus näkyy kirjoitustesi alalaidassa.',
'Sig preview'					=>	'Nykyisen allekirjoituksen esikatselu:',
'No sig'					=>	'Ei allekirjoitusta tallennettuna.',
'Signature quote/code/list/h'			=>	'quote, code, list, ja heading BBCodeja ei saa käyttää allekirjoituksessa .',
'Topics per page'				=>	'Aiheet',
'Posts per page'				=>	'Kirjoitukset',
'Leave blank'					=>	'Tyhjä = Forumin oletusasetus käytössä.',
'Subscription legend'				=>	'Seurausasetukset',
'Notify full'					=>	'Liitä vastaus plaintextinä sähköpostitiedotukseen.',
'Auto notify full'				=>	'Seuraa automaattisesti kaikkia aiheita joihin kirjoitat.',
'Show smilies'					=>	'Näytä hymiöt kuvina.',
'Show images'					=>	'Näytä kuvat kirjoituksissa.',
'Show images sigs'				=>	'Näytä kuvat käyttäjien allekirjoituksissa.',
'Show avatars'					=>	'Näytä käyttäjien avatarit.',
'Show sigs'					=>	'Näytä käyttäjien allekirjoitukset.',
'Style legend'					=>	'Valitse tyyli',
'Styles'					=>	'Tyylit',
'Admin note'					=>	'Ylläpitäjän huomautus',
'Pagination legend'				=>	'Syötä sivutusasetukset',
'Post display legend'				=>	'Säädä näkyvyyteen liittyviä asetuksia',
'Post display info'				=>	'Jos yhteytesi on hidas, kannattaa poistaa kuvat käytöstä.',
'Instructions'					=>	'Päädyt takaisin tänne kun päivität asetuksesi.',

// Administration stuff
'Group membership legend'			=>	'Valitse käyttäjäryhmä',
'Save'                              =>	'Tallenna',
'Set mods legend'				=>	'Anna moderaattorioikeudet',
'Moderator in info'				=>	'Tämä koskee vain moderaattoreita. Ylläpitäjällä on muutenkin täydet oikeudet.',
'Update forums'					=>	'Päivitä forumit',
'Delete ban legend'				=>	'Poista tai bannaa käyttäjiä.',
'Delete user'					=>	'Poista käyttäjä',
'Ban user'                      =>	'Bannaa käyttäjä',
'Confirm delete legend'				=>	'Tärkeää... Lue ennenkuin poistat käyttäjän.',
'Confirm delete user'				=>	'Vahvista käyttäjän poistaminen.',
'Confirmation info'				=>	'Vahvista että haluat poistaa käyttäjän', // the username will be appended to this string
'Delete warning'				=>	'Varoitus! Poistettuja kirjoituksia ei voi palauttaa.',
'Delete posts'					=>	'Poista kaikki tämän käyttäjän kirjoitukset ja aiheet.',
'Delete'                        =>	'Poista', // submit button (confirm user delete)
'User delete redirect'				=>	'Käyttäjä poistettu. Siirrytään …',
'Group membership redirect'			=>	'Ryhmän jäsenyys tallennettu. Siirrytään …',
'Update forums redirect'			=>	'Oikeudet päivitetty. Siirrytään …',
'Ban redirect'                      =>	'Siirrytään …',
'No delete admin message'			=>	'Ylläpitäjää ei voi poistaa.',

);
