<?php

// Language definitions used in both profile.php and register.php
// Finnish translation by Pauligrinder
$lang_prof_reg = array(

'Email legend'				=>	'Syötä kelvollinen sähköpostiosoite',
'Email legend 2'			=>	'Syötä ja varmista kelvollinen sähköpostiosoite',
'Localisation legend'		=>	'Paikka ja aika -asetukset',
'Time zone'                 =>	'Aikavyöhyke',
'Time zone info'			=>	'Jotta aika näkyisi oikein, kannattaa valita oikea aikavyöhyke.',
'DST'                       =>	'Kello on kesäajassa (tunnin edellä).',
'Time format'				=>	'Ajan muoto',
'Date format'				=>	'Päivämäärän muoto',
'Default'                   =>	'Oletus',
'Language'                  =>	'Kieli',
'Email setting info'		=>	'Valitse, haluatko että muut näkevät sähköpostiosoitteesi.',
'Email setting 1'			=>	'Näytä sähköpostiosoitteesi.',
'Email setting 2'			=>	'Piilota sähköpostiosoite, mutta hyväksy lomakkeen kautta lähetetyt viestit.',
'Email setting 3'			=>	'Piilota sähköpostiosoite, äläkä hyväksy lomakkeen kautta lähetettyjä viestejä.',
'Privacy options legend'	=>	'Aseta suojausasetukset',
'Confirm pass'				=>	'Vahvista salasana',

'Username too short'		=>	'Nimen pitää olla vähintään 2 merkkiä pitkä.',
'Username too long'			=>	'Nimi ei saa olla yli 25 merkkiä pitkä.',
'Username guest'			=>	'guest-nimeä ei voi käyttää.',
'Username IP'				=>	'IP-osoitteita ei saa käyttää nimissä.',
'Username reserved chars'	=>	'Nimi ei saa sisältää \', " ja [ tai ] samanaikaisesti.',
'Username BBCode'			=>	'Nimi ei saa sisältää forumin käyttämiä (BBCode) tageja.',
'Banned username'			=>	'Tämä nimi on bannattu.',
'Pass too short'			=>	'Salasana ei täytä forumin tietoturvavaatimuksia (liian lyhyt)',
'Pass not match'			=>	'Et kirjoittanut samaa salasanaa molempiin kenttiin.',
'Banned email'				=>	'Sähköpostiosoite on bannattu.',
'Dupe email'				=>	'Sähköpostiosoite on jo käytössä.',
'Sig too long'				=>	'Allekirjoitus ei saa olla pidempi kuin %1$s merkkiä. Lyhennä %2$s merkin verran.',
'Sig too many lines'		=>	'Allekirjoituksessa ei saa olla yli %s riviä.',
'Bad ICQ'                   =>	'Virheellinen ICQ UIN.',

'UTC-12:00'							=>	'(UTC-12:00) Yhdysvallat (Baker, Howland)',
'UTC-11:00'							=>	'(UTC-11:00) Samoa, Uusi-Seelanti (Niue), Yhdysvallat (Amerikan Samoa, Midwaysaaret)',
'UTC-10:00'							=>	'(UTC-10:00) Havaijin-Aleuttien normaaliaika, HST',
'UTC-09:30'							=>	'(UTC-09:30) Ranskan Polynesia (Marquesassaaret)',
'UTC-09:00'							=>	'(UTC-09:00) Alaskan normaaliaika, AKST',
'UTC-08:30'							=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'							=>	'(UTC-08:00) Tyynenmeren normaaliaika, PST',
'UTC-07:00'							=>	'(UTC-07:00) Vuoriston normaaliaika, MST',
'UTC-06:00'							=>	'(UTC-06:00) Keskinen normaaliaika, CST',
'UTC-05:00'							=>	'(UTC-05:00) Itäinen normaaliaika, EST',
'UTC-04:00'							=>	'(UTC-04:00) Atlantin normaaliaika, AST',
'UTC-03:30'							=>	'(UTC-03:30) Newfoundlandin aika, NT',
'UTC-03:00'							=>	'(UTC-03:00) Argentiina, Brasilia, Suriname, Grönlanti, Uruguay',
'UTC-02:00'							=>	'(UTC-02:00) Brasilia',
'UTC-01:00'							=>	'(UTC-01:00) Azorit, Kap Verde, Gröönlanti',
'UTC'								=>	'(UTC) Länsi-Euroopan aika, WET',
'UTC+01:00'							=>	'(UTC+01:00) Keski-Euroopan aika, CET',
'UTC+02:00'							=>	'(UTC+02:00) Itä-Euroopan aika, EET',
'UTC+03:00'							=>	'(UTC+03:00) Moskova, Itä-Afrikka',
'UTC+03:30'							=>	'(UTC+03:30) Iran',
'UTC+04:00'							=>	'(UTC+04:00) Arabiemiraatit, Georgia, Mauritius',
'UTC+04:30'							=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'							=>	'(UTC+05:00) Kazakstan, Paktistan',
'UTC+05:30'							=>	'(UTC+05:30) Intia, Sri Lanka',
'UTC+05:45'							=>	'(UTC+05:45) Nepal',
'UTC+06:00'							=>	'(UTC+06:00) Bangladesh, Bhutan, Kirgistan',
'UTC+06:30'							=>	'(UTC+06:30) Kookossaaret, Myanmar',
'UTC+07:00'							=>	'(UTC+07:00) Indonesia, Kiina, Malesia',
'UTC+08:00'							=>	'(UTC+08:00) Australia, Kiina, Malesia, Singapore',
'UTC+08:45'							=>	'(UTC+08:45) Australia',
'UTC+09:00'							=>	'(UTC+09:00) Japano, Korean tasavalta, Ita-Timor',
'UTC+09:30'							=>	'(UTC+09:30) Australia',
'UTC+10:00'							=>	'(UTC+10:00) Australia, Pohjois-Mariaanit',
'UTC+10:30'							=>	'(UTC+10:30) Australia',
'UTC+11:00'							=>	'(UTC+11:00) Salomonsaaret, Mikronesia',
'UTC+11:30'							=>	'(UTC+11:30) Norfolkinsaari',
'UTC+12:00'							=>	'(UTC+12:00) Uusi-Sland, Fidzi, Kamzathka',
'UTC+12:45'							=>	'(UTC+12:45) Chathamsaaret',
'UTC+13:00'							=>	'(UTC+13:00) Tonga, Phoenixsaaret',
'UTC+14:00'							=>	'(UTC+14:00) Linesaaret'

);
