<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'ไม่สามารถตรวจสอบการปรับรุ่นได้ เนื่องจาก \'allow_url_fopen\' ถูกปิดใช้งานบนระบบนี้',
'Upgrade check failed message'		=>	'การตรวจสอบการปรับรุ่นล้มเหลวเนื่องจากสาเหตุที่ไม่รู้จัก',
'Running latest version message'	=>	'คุณกําลังเรียกใช้ FluxBB เวอร์ชันล่าสุด',
'New version available message'		=>	'FluxBB รุ่นใหม่ได้รับการปล่อยตัวแล้ว คุณสามารถดาวน์โหลดรุ่นล่าสุดได้ที่ %s',
'Deleted install.php redirect'		=>	'แฟ้มถูกเอาออกเรียบร้อยแล้ว กําลังเปลี่ยนเส้นทาง ...',
'Delete install.php failed'			=>	'ไม่สามารถเอา install.php ออกได้ โปรดทําด้วยมือ',
'Not available'						=>	'ไม่พร้อมใช้งาน',
'Forum admin head'					=>	'การจัดการฟอรั่ม',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'ยินดีต้อนรับสู่แผงควบคุมการจัดการ FluxBB จากที่นี่คุณสามารถควบคุมแง่มุมที่บอร์ด ขึ้นอยู่กับว่าคุณเป็นผู้ดูแลระบบหรือผู้ควบคุมคุณสามารถทําสิ่งต่อไปนี้',
'Welcome 1'							=>	'จัดระเบียบหมวดหมู่และฟอรัม',
'Welcome 2'							=>	'ตั้งค่าตัวเลือกและการกําหนดลักษณะทั่วทั้งฟอรัม',
'Welcome 3'							=>	'ควบคุมสิทธิ์สําหรับผู้ใช้และแขก',
'Welcome 4'							=>	'ดูสถิติ IP สําหรับผู้ใช้',
'Welcome 5'							=>	'แบนผู้ใช้',
'Welcome 6'							=>	'คําเซ็นเซอร์',
'Welcome 7'							=>	'ตั้งค่ากลุ่มผู้ใช้และโปรโมชัน',
'Welcome 8'							=>	'พรุนโพสต์เก่า',
'Welcome 9'							=>	'จัดการรายงานโพสต์ที่๔ูกโพสต์อีกครั้ง',
'Alerts head'						=>	'แจ้ง เตือน',
'Install file exists'				=>	'install.php ยังมีอยู่ แต่ควรเอาออก %s',
'Delete install file'				=>	'ลบออก',
'About head'						=>	'เกี่ยวกับฟลักซ์บีบี',
'FluxBB version label'				=>	'รุ่น FluxBB',
'Check for upgrade'					=>	'ตรวจหาการปรับรุ่น',
'FluxBB version data'				=>	'v%s - %s',
'Server statistics label'			=>	'สถิติเซิร์ฟเวอร์',
'View server statistics'			=>	'ดูสถิติของเซิร์ฟเวอร์',
'Support label'						=>	'สนับสนุน',
'Forum label'						=>	'ฟอรั่ม',
'IRC label'							=>	'ช่อง IRC',

// Language definitions used in admin_statistics.php
'PHPinfo disabled message'			=>	'ฟังก์ชัน PHP phpinfo() ถูกปิดใช้งานบนเซิร์ฟเวอร์นี้',
'Server statistics head'			=>	'สถิติเซิร์ฟเวอร์',
'Server load label'					=>	'โหลดเซิร์ฟเวอร์',
'Server load data'					=>	'%s - %s ผู้ใช้ออนไลน์',
'Environment label'					=>	'สภาพ แวด ล้อม',
'Environment data OS'				=>	'ระบบปฏิบัติการ: %s',
'Show info'							=>	'แสดงข้อมูล',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'ส่วนช่วยดําเนินการ: %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ตัวเร่งความเร็ว IonCube PHP',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'แคช PHP ทางเลือก (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'เครื่องมือเพิ่มประสิทธิภาพ Zend',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'ฐาน ข้อมูล',
'Database data rows'				=>	'แถว: %s',
'Database data size'				=>	'ขนาด: %s',
);
