<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'การค้นหาผู้ใช้',
'No search permission'				=>	'คุณไม่มีสิทธิ์ในการใช้คุณลักษณะการค้นหา',
'Search flood'						=>	'อย่างน้อย %s วินาทีต้องผ่านระหว่างการค้นหา กรุณารอ %s วินาที แล้วลองค้นหาอีกครั้ง',
'Search'							=>	'ค้น หา',
'Search criteria legend'			=>	'ป้อนเกณฑ์การค้นหาของคุณ',
'Search info'						=>	'เมื่อต้องการค้นหาตามคําสําคัญ ให้ใส่คําหรือคําที่จะค้นหา แยกคําด้วยช่องว่าง ใช้ AND, OR และ NOT เพื่อปรับแต่งการค้นหาของคุณ ในการค้นหาโดยผู้เขียนป้อนชื่อผู้ใช้ของผู้เขียนที่มีโพสต์ที่คุณต้องการค้นหา ใช้อักขระตัวแทน * สําหรับการจับคู่บางส่วน',
'Keyword search'					=>	'การค้นหาคําสําคัญ',
'Author search'						=>	'ค้นหาผู้เขียน',
'Search in legend'					=>	'เลือกตําแหน่งที่จะค้นหา',
'Search in info'					=>	'เลือกฟอรัมที่คุณต้องการค้นหาและหากคุณต้องการค้นหาในหัวข้อข้อความหรือทั้งสองอย่าง',
'Search multiple forums info'		=>	'หากไม่มีการเลือกฟอรัมฟอรัมทั้งหมดจะถูกค้นหา',
'Forum search'						=>	'ฟอรั่ม',
'Search in'							=>	'ค้นหาใน',
'Message and subject'				=>	'ข้อความและหัวข้อ',
'Message only'						=>	'ข้อความเท่านั้น',
'Topic only'						=>	'ชื่อเรื่องหัวข้อเท่านั้น',
'Sort by'							=>	'เรียงลําดับตาม',
'Sort order'						=>	'ลําดับการจัดเรียง',
'Search results legend'				=>	'เลือกวิธีการดูผลลัพธ์การค้นหา',
'Search results info'				=>	'คุณสามารถเลือกวิธีที่คุณต้องการเรียงลําดับและแสดงผลลัพธ์ของคุณ',
'Sort by post time'					=>	'เวลาโพสต์',
'Sort by author'					=>	'สร้าง',
'Sort by subject'					=>	'ชื่อเรื่อง',
'Sort by forum'						=>	'ฟอรั่ม',
'Ascending'							=>	'จากน้อยไปหามาก',
'Descending'						=>	'จากมากไปหาน้อย',
'Show as'							=>	'แสดงผลลัพธ์เป็น',
'Show as topics'					=>	'หัว ข้อ',
'Show as posts'						=>	'โพสต์',

// Results
'Search'							=>	'ค้น หา',
'Search results'					=>	'ผลลัพธ์การค้นหา',
'Quick search show_new'				=>	'ใหม่',
'Quick search show_recent'			=>	'ใช้งานอยู่',
'Quick search show_unanswered'		=>	'ยังไม่ได้ตอบ',
'Quick search show_replies'			=>	'โพสต์แล้ว',
'Quick search show_user_topics'		=>	'หัวข้อตาม %s',
'Quick search show_user_posts'		=>	'โพสต์ตาม %s',
'Quick search show_subscriptions'	=>	'สมัครสมาชิกโดย %s',
'By keywords show as topics'		=>	'หัวข้อที่มีข้อความติดโพสต์ที่มี \'%s\'',
'By keywords show as posts'			=>	'โพสต์ที่มี \'%s\'',
'By user show as topics'			=>	'หัวข้อที่มีข้อความติดโพสต์โดย %s',
'By user show as posts'				=>	'โพสต์ตาม %s',
'By both show as topics'			=>	'หัวข้อที่มีข้อความติดโพสต์ที่มี \'%s\' โดย %s',
'By both show as posts'				=>	'โพสต์ที่มี \'%s\' โดย %s',
'No terms'							=>	'คุณต้องใส่คําสําคัญและ/หรือผู้สร้างอย่างน้อยหนึ่งคําที่จะค้นหา คําที่ใช้ค้นหาต้องมีความยาวอย่างน้อยสามอักขระ',
'No hits'							=>	'การค้นหาของคุณไม่ส่งคืนการเข้าชม',
'No user posts'						=>	'ไม่มีโพสต์โดยผู้ใช้นี้ในฟอรัมนี้',
'No user topics'					=>	'ไม่มีหัวข้อโดยผู้ใช้นี้ในฟอรั่มนี้',
'No subscriptions'					=>	'ผู้ใช้นี้ไม่ได้สมัครสมาชิกในหัวข้อใดๆ',
'No new posts'						=>	'ไม่มีหัวข้อที่มีโพสต์ใหม่ตั้งแต่การเยี่ยมชมครั้งล่าสุดของคุณ',
'No recent posts'					=>	'ไม่มีการโพสต์ใหม่ภายใน 24 ชั่วโมงที่ผ่านมา',
'No unanswered'						=>	'ไม่มีโพสต์ที่ไม่ได้รับคําตอบในฟอรัมนี้',
'Go to post'						=>	'ไปที่โพสต์',
'Go to topic'						=>	'ไปที่หัวข้อ'

);
