<?php

// Language definitions used in admin_options.php
$lang_admin_options = array(

'Bad HTTP Referer message'			=>	'Feil HTTP_REFERER. Hvis du har flyttet tavla fra ett sted til et annet, eller byttet domene, må du oppdatere Base URL manuelt i databasen (se etter o_base_url i config tabellen) og deretter tømme bufferen ved å slette alle php-filer i /cache katalogen.',
'Must enter title message'			=>	'Du må angi en tittel for tavla.',
'Invalid e-mail message'				=>	'E-postadressen du har oppgitt for administrator er ugyldig.',
'Invalid webmaster e-mail message'	=>	'E-postadressen du har oppgitt for nettansvarlig er ugyldig.',
'SMTP passwords did not match'		=>	'Du må oppgi identisk SMTP-passord 2 ganger for å endre passord.',
'Enter announcement here'			=>	'Angi din kunngjøring her.',
'Enter rules here'					=>	'Angi dine regler her.',
'Default maintenance message'		=>	'Tavla er nede midlertidig for vedlikehold. Vennligst, prøv igjen om noen minutter.',
'Timeout error message'				=>	'Verdien for "Online status" må være mindre enn verdien for "Besøkstid".',
'Options updated redirect'			=>	'Valg oppdateres. Omdirigerer …',
'Options head'						=>	'Valg',

// Essentials section
'Essentials subhead'					=>	'Generelt',
'Board title label'					=>	'Tittel på tavla',
'Board title help'					=>	'Tittel på tavla (vises på toppen hver side). Dette feltet må <strong>ikke</strong> inneholde HTML.',
'Board desc label'					=>	'Beskrivelse av tavla',
'Board desc help'					=>	'En kort beskrivelse av tavla (vises på toppen av hver side). Feltet kan inneholde HTML.',
'Base URL label'						=>	'Base URL',
'Base URL help'						=>	'Komplett URL til tavla uten skråstrek (dvs. http://www.mittdomene.com/forum). Adressen <strong> må </strong> være riktig for at alle administrasjons- og moderatorfunksjoner skal fungere. Hvis du får opplever "Bad referer" feil, er sannsynligvis URL\'en feil.',
'Timezone label'						=>	'Standard tidssone',
'Timezone help'						=>	'Standard tidssone for brukere som registrerer seg på tavla.',
'DST label'							=>	'Juster for DST',
'DST help'							=>	'En sjekk på om \'sommertid\' er påslått (øker tidsangivelsen med 1 time).',
'Language label'						=>	'Standard språk',
'Language help'						=>	'Standardspråket for gjester og brukere som ikke har endret språk fra standard i sin profil. Hvis du fjerner en språkpakke, må dette oppdateres.',
'Default style label'				=>	'Standard utseende',
'Default style help'					=>	'Standard utseende for gjester og brukere som ikke har endret utseende fra standard i sin profil.',

// Essentials section timezone options
'UTC-12:00'							=>	'(UTC-12:00) Internasjonal datolinje - Vest',
'UTC-11:00'							=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'							=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'							=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'							=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'							=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'							=>	'(UTC-08:00) Pacific',
'UTC-07:00'							=>	'(UTC-07:00) Mountain',
'UTC-06:00'							=>	'(UTC-06:00) Central',
'UTC-05:00'							=>	'(UTC-05:00) Eastern',
'UTC-04:00'							=>	'(UTC-04:00) Atlantic',
'UTC-03:30'							=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'							=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'							=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'							=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'								=>	'(UTC) Western European, Greenwich',
'UTC+01:00'							=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'							=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'							=>	'(UTC+03:00) Eastern African',
'UTC+03:30'							=>	'(UTC+03:30) Iran',
'UTC+04:00'							=>	'(UTC+04:00) Moscow, Gulf, Samara',
'UTC+04:30'							=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'							=>	'(UTC+05:00) Pakistan',
'UTC+05:30'							=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'							=>	'(UTC+05:45) Nepal',
'UTC+06:00'							=>	'(UTC+06:00) Bangladesh, Bhutan, Yekaterinburg',
'UTC+06:30'							=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'							=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'							=>	'(UTC+08:00) Greater China, Australian Western, Krasnoyarsk',
'UTC+08:45'							=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'							=>	'(UTC+09:00) Japan, Korea, Chita, Irkutsk',
'UTC+09:30'							=>	'(UTC+09:30) Australian Central',
'UTC+10:00'							=>	'(UTC+10:00) Australian Eastern',
'UTC+10:30'							=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'							=>	'(UTC+11:00) Solomon Island, Vladivostok',
'UTC+11:30'							=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'							=>	'(UTC+12:00) New Zealand, Fiji, Magadan',
'UTC+12:45'							=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'							=>	'(UTC+13:00) Tonga, Phoenix Islands, Kamchatka',
'UTC+14:00'							=>	'(UTC+14:00) Line Islands',

// Timeout Section
'Timeouts subhead'					=>	'Tid og tidsavbrudd',
'Time format label'					=>	'Tidsformat',
'PHP manual'							=>	'PHP-manualen',
'Time format help'					=>	'[Nåværende format: %s]. Sjekk %s for andre formater.',
'Date format label'					=>	'Datoformat',
'Date format help'					=>	'[Nåværende format: %s]. Sjekk %s for andre formater.',
'Visit timeout label'				=>	'Besøkstid',
'Visit timeout help'					=>	'Antall sekunder en bruker må være inaktiv før hans/hennes siste besøksdata blir oppdatert (rammer først og fremst indikatorer for ny melding).',
'Online timeout label'				=>	'Online status',
'Online timeout help'				=>	'Antall sekunder en bruker må være inaktiv før vedkommende fjernes fra brukerlisten som viser \'online\' status.',
'Redirect time label'				=>	'Tid for omdirigering',
'Redirect time help'					=>	'Antall sekunder som må avventes ved omdirigering. Dersom dette settes til 0, vil ikke \'omdirigeringssiden\' bli vist (abefales ikke)',

// Display Section
'Display subhead'					=>	'Vis',
'Version number label'				=>	'Versjon',
'Version number help'				=>	'Vis versjonsnummer for FluxBB-utgaven i footer.',
'Info in posts label'				=>	'Brukerinformasjon på innleggssiden',
'Info in posts help'					=>	'Vis informasjon for innleggets forfatter. Informasjon som kan vises er hjemsted, dato for registrering, antall innlegg og kontaktlinker (e-post og URL).',
'Post count label'					=>	'Antall innlegg fra bruker',
'Post count help'					=>	'Vis antall innlegg en bruker har opprettet (gjelder emnevisning, profil og brukerliste).',
'Smilies label'						=>	'Smilefjes i innlegg',
'Smilies help'						=>	'Gjør om smilefjes til icon.',
'Smilies sigs label'					=>	'Smilefjes i signaturer',
'Smilies sigs help'					=>	'Gjør om smilefjes til icon i brukersignaturer.',
'Clickable links label'				=>	'Lag klikkbare linker',
'Clickable links help'				=>	'Dersom aktivert, vil FluxBB detektere automatisk URL\' i innlegg og gjøre de om til klikkbare linker.',
'Topic review label'					=>	'Visning av emner',
'Topic review help'					=>	'Maksimum antall innlegg som vises ved posting (nyeste først). Sett til 0 for å deaktivere.',
'Topics per page label'				=>	'Tråder per side',
'Topics per page help'				=>	'Standard antall tråder som vises på en forumside. Brukere kan endre dette for egen visning.',
'Posts per page label'				=>	'Innlegg per side',
'Posts per page help'				=>	'Standard antall innlegg per side i en tråd. Brukere kan endre dette for egen visning.',
'Indent label'						=>	'Størrelse på innrykk',
'Indent help'						=>	'Dersom verdien settes til 8, vil et vanlig tab-innrykk brukes ved visning av tekst i [code] [/ code] formatet. Ellers vil tilsvarende mellomrom bli brukt for å rykke inn teksten.',
'Quote depth label'					=>	'Maksimum dybde for sitering',
'Quote depth help'					=>	'Maksimum antall ganger en [quote] tag kan settes inn i en annen [quote] tag. Tagger dypere enn dette vil bli filtrert bort.',

// Features section
'Features subhead'					=>	'Tillegg',
'Quick post label'					=>	'Hurtigposting',
'Quick post help'					=>	'Dersom aktivert vil FluxBB legge til et skjema for hurtigposting i bunnen av innlegget. På denne måten kan brukere opprette svar direkte på innleggets side.',
'Users online label'					=>	'Brukere online',
'Users online help'					=>	'Vis informasjon på forsiden om gjester og registrerte brukere som leser innlegg på tavla.',
'Censor words label'					=>	'Sensurering av ord og uttrykk',
'Censor words help'					=>	'Aktiver denne funksjonen for å sensurere spesielle ord og uttrykk på tavla. Se %s for mer informasjon.',
'Signatures label'					=>	'Signaturer',
'Signatures help'					=>	'Tillat brukere å legge ved en signatur på innlegg som opprettes.',
'User has posted label'				=>	'Bruker har publisert innlegg tidligere',
'User has posted help'				=>	'Denne funksjonen viser en prikk foran emner i \'viewforum.php\' i tilfelle den påloggede brukeren har postet i dette emnet tidligere. Deaktiver hvis du opplever høy belastning på serveren.',
'Topic views label'					=>	'Visning av tråder',
'Topic views help'					=>	'Hold orden på antall ganger en tråd er vist. Deaktiver dersom du opplever høy belastning på serveren ved høy forumaktivitet.',
'Quick jump label'					=>	'Gå til',
'Quick jump help'					=>	'Aktiver \'Gå til\' (hopp til forum) nedtrekksmeny.',
'GZip label'							=>	'GZip output',
'GZip help'							=>	'Dersom aktivert vil FluxBB\'s output bli komprimert når det sendes til nettleseren. Dette vil redusere båndbredde, men bruke litt mer CPU. Denne funksjonen krever at PHP er konfigurert med zlib. Hvis du allerede har en av Apache-modulene \'mod_gzip\' eller \'mod_deflate\' satt opp til å komprimere PHP-skript, bør du deaktivere denne funksjonen.',
'Search all label'					=>	'Søk alle forum',
'Search all help'					=>	'Dersom deaktivert, vil søk kun bli tillatt i ett forum om gangen. Deaktiver hvis lasten på tjeneren er høy på grunn av overdrevent søk.',
'Menu items label'					=>	'Ekstra menyelementer',
'Menu items help'					=>	'Ved å sette inn HTML-hyperkoblinger i denne tekstboksen kan en rekke elementer legges til navigasjonsmenyen på toppen av alle sider. Formatet for å legge til nye linker er X = &lt;a href="URL"&gt;LINK&lt;/a&gt;, der X er posisjonen der linken skal settes inn (for eks., 0 for å sette inn ved begynnelsen og 2 for å sette inn etter \'Brukerlisten\'). Skill elementer ved hjelp av linjeskift',

// Feeds section
'Feed subhead'						=>	'Syndikat',
'Default feed label'					=>	'Standard syndikatmating (Feed)',
'Default feed help'					=>	'Velg type syndikatmating som skal vises. NB! Ønskes ikke syndikatmating må alternativet \'Ingen\' velges.',
'None'								=>	'Ingen',
'RSS'								=>	'RSS',
'Atom'								=>	'Atom',
'Feed TTL label'						=>	'Lengde for syndikatmating i hurtigbuffer',
'Feed TTL help'						=>	'Syndikatmating kan legges til hurtigminne for å redusere ressursbruken.',
'No cache'							=>	'Ikke bruk hurtigminne',
'Minutes'							=>	'%d minutter',

// Reports section
'Reports subhead'					=>	'Rapporter',
'Reporting method label'				=>	'Metode for rapportering',
'Internal'							=>	'Intern',
'By e-mail'							=>	'E-post',
'Both'								=>	'Begge',
'Reporting method help'				=>	'Velg metode for å håndtere rapporter fra tråder og innlegg. Du kan velge om rapportene skal håndteres av det interne rapportsystemet, sendes til adresser på e-postlisten (se nedenfor) eller begge deler.',
'Mailing list label'					=>	'E-postliste',
'Mailing list help'					=>	'Liste med abonnenter, skilt med komma. Personene på denne listen vil motta rapporter fra tråder/innlegg sendt av brukerne av tavla.',

// Avatars section
'Avatars subhead'					=>	'Avatarer',
'Use avatars label'					=>	'Bruk avatarer',
'Use avatars help'					=>	'Dersom ja, vil brukere kunne laste opp en avatar som vil vises under tittelen deres.',
'Upload directory label'				=>	'Mappe for opplasting',
'Upload directory help'				=>	'Opplastingsmappe for avatarer (relativ til FluxBB\'s rot-mappe). PHP må ha skriverettigheter til denne mappen.',
'Max width label'					=>	'Maks bredde',
'Max width help'						=>	'Maksimum bredde på avatarer i piksler (60 px anbefales).',
'Max height label'					=>	'Maks høyde',
'Max height help'					=>	'Maksimum tillatt høyde på avatarer i piksler (60 px anbefales).',
'Max size label'						=>	'Maks størrelse',
'Max size help'						=>	'Maksimum størrelse på avaterer i bytes (10240 bytes anbefales).',

// E-mail section
'E-mail subhead'						=>	'E-post',
'Admin e-mail label'					=>	'E-post til admin',
'Admin e-mail help'					=>	'E-postadressen til tavlas administrator.',
'Webmaster e-mail label'				=>	'E-post til webansvarlig',
'Webmaster e-mail help'				=>	'Dette er adressen som alle e-poster sendt fra nettstedets tavle vil bli adressert fra.',
'Forum subscriptions label'			=>	'Abonnering',
'Forum subscriptions help'			=>	'Aktiver mulighet for brukere til å abonnere (motta e-post når noen oppretter en tråd).',
'Topic subscriptions label'			=>	'Abonnering på tråd',
'Topic subscriptions help'			=>	'Aktiver mulighet for brukere til å abonnere på tråder (motta e-post når noen poster et svar).',
'SMTP address label'					=>	'Adresse til SMTP-server',
'SMTP address help'					=>	'Adressen til en ekstern SMTP server for å sende e-poster med. Du kan angi en port dersom SMTP-serveren ikke kjører på standard port 25 (eksempel: mail.myhost.com: 3580). La stå tomt for å bruke lokalt e-postprogram.',
'SMTP username label'				=>	'SMTP brukernavn',
'SMTP username help'					=>	'Brukernavn for SMTP-server. Oppgi kun brukernavn dersom dette kreves av SMTP-serveren (de fleste servere krever <strong>ikke</strong> autentisering).',
'SMTP password label'				=>	'SMTP passord',
'SMTP change password help'			=>	'Kryss av dersom du ønsker å endre eller slette eksisterende passord.',
'SMTP password help'					=>	'Passord for SMTP server. Oppgi kun passord dersom dette kreves av SMTP-serveren (de fleste servere krever <strong>ikke</strong> autentisering). Vennligst, angi passordet 2 ganger for å bekrefte.',
'SMTP SSL label'						=>	'Krypter SMTP ved hjelp av SSL',
'SMTP SSL help'						=>	'Kypterer forbindelsen til SMTP-serveren ved hjelp av SSL. Skal kun benyttes dersom SMTP-serveren krever dette og din versjon av PHP støtter SSL.',

// Registration Section
'Registration subhead'				=>	'Registrering',
'Allow new label'					=>	'Tillat nye registreringer',
'Allow new help'						=>	'Kontrollerer om dette forumet aksepterer nye registreringer. Deaktiver bare under spesielle omstendigheter.',
'Verify label'						=>	'Bekreft registreringer',
'Verify help'						=>	'Dersom aktivert, blir brukeren tilsendt et tilfeldig valgt passord når de registrerer seg. De kan deretter logge inn og endre passordet i profilen sin hvis de ønsker dette. Denne funksjonen krever også at brukeren bekrefter ny e-postadresser, dersom han/hun velger å bytte fra en de registrerte seg med. Dette er en effektiv måte å unngå registreringsmisbruk og sørge for at alle brukere har "riktige" e-postadresser i sine profiler.',
'Report new label'					=>	'Rapporter nye registreringer',
'Report new help'					=>	'Dersom aktivert, vil FluxBB varsle brukerne på mailinglisten (se ovenfor) når en ny bruker registrerer i forumet.',
'Use rules label'					=>	'Regler for bruk av forum',
'Use rules help'						=>	'Dersom aktivert, må brukeren godta et sett av regler ved registrering (se teksten nedenfor). Reglene vil alltid være tilgjengelig via en lenke i navigasjonen tabellen øverst på hver side.',
'Rules label'						=>	'Angi regler her',
'Rules help'							=>	'Her kan du legge inn regler eller annen informasjon som brukeren må godta ved registrering. Hvis du har aktivert regler ovenfor må du skrive inn noe her, ellers vil det bli deaktivert. Denne teksten vil ikke bli filtrert som vanlige innlegg, og kan dermed inneholde HTML.',
'E-mail default label'				=>	'Standard oppsett for e-poster',
'E-mail default help'				=>	'Velg standard personvern for ny brukerregistrering.',
'Display e-mail label'				=>	'Vis epostadresse til andre brukere',
'Hide allow form label'				=>	'Skjul e-postadresse men tillat e-post sendt fra forum.',
'Hide both label'					=>	'Skjul e-postadresse og blokker e-post fra forum',

// Announcement Section
'Announcement subhead'				=>	'Kunngjøringer',
'Display announcement label'			=>	'Vis kunngjøringer',
'Display announcement help'			=>	'Aktiver for å vise kunngjøringer øverst på tavla (alle sider).',
'Announcement message label'			=>	'Kunngjøring',
'Announcement message help'			=>	'Denne teksten vil ikke bli filtrert som vanlige innlegg og kan derfor inneholde HTML.',

// Maintenance Section
'Maintenance subhead'				=>	'Vedlikehold',
'Maintenance mode label'				=>	'Vedlikeholdsmodus',
'Maintenance mode help'				=>	'Dersom aktivert, vil tavla kun være tilgjengelig for administratorer. Dette bør brukes dersom tavla må tas ned midlertidig for vedlikehold. <strong>ADVARSEL! Ikke logg ut når tavla er under vedlikehold.</strong> Du vil ikke kunne logge inn igjen.',
'Maintenance message label'			=>	'Melding ved vedlikehold',
'Maintenance message help'			=>	'Melding som vises til brukere når tavla er under vedlikehold. Hvis tomt, vil en standard melding vises. Denne teksten vil ikke bli filtrert som vanlige innlegg, og kan derfor inneholde HTML.',

);
