<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'			=>	'Ingen bruker med dette brukernavnet er registrert. Hvis du ønsker å legge til et forbud som ikke er knyttet til et bestemt brukernavn lar du brukernavn være tomt.',
'No user ID message'			=>	'Ingen bruker med dette ID er registrert.',
'User is admin message'		=>	'Bruker %s er an administrator og kan ikke utestenges. Hvis du ønsker å utestenge en administrator, må du først endre hans/henens brukerstatus.',
'User is mod message'		=>	'Bruker %s er an moderator og kan ikke utestenges. Hvis du ønsker å utestenge en moderator, må du først endre hans/henens brukerstatus.',
'Must enter message'			=>	'Du må angi enten et brukernavn, en IP-adresse eller en e-postadresse (minst).',
'Cannot ban guest message'	=>	'Gjesten kan ikke utestenges.',
'Invalid IP message'			=>	'Du har angitt ugyldig IP/IP-område.',
'Invalid e-mail message'		=>	'E-postadressen (for eks. bruker@domain.com) eller partiell e-postadresse (for eks. domain.com) som er angitt er ugyldig.',
'Invalid date message'		=>	'Du har angitt ugyldig utløpsdato.',
'Invalid date reasons'		=>	'Formatet må være yyyy-mm-dd og datoen må være minst en dag fram i tiden.',
'Ban added redirect'			=>	'Utestengelse lagt til. Omdirigerer …' ,
'Ban edited redirect'		=>	'Utestengelse redigert. Omdirigerer …',
'Ban removed redirect'		=>	'Utestengelse fjernet. Omdirigerer …',

'New ban head'				=>	'Ny utestengelse',
'Add ban subhead'			=>	'Legg til utestengelse',
'Username label'				=>	'Brukernavn',
'Username help'				=>	'Brukernavnet som skal utestenges (store eller små bokstaver).',
'Username advanced help'		=>	'Brukernavnet som skal utestenges (store eller små bokstaver). Den neste siden vil la deg angi en egendefinert IP-adresse og e-post. Hvis du bare ønsker å forby et bestemt IP/IP-område eller e-post, lar du feltene stå tomme.',

'Ban search head'			=>	'Søk på utestengte',
'Ban search subhead'			=>	'Angi søkekriterier',
'Ban search info'			=>	'Søk på utestengte i databasen. Du kan angi en eller flere søkekriterier. Jokertegn i form av stjerner (*) er akseptert. La feltene stå tomme for å vise alle utestengelser.',
'Date help'					=>	'(yyyy-mm-dd)',
'Message label'				=>	'Melding',
'Expire after label'			=>	'Utløper etter',
'Expire before label'		=>	'Utløper før',
'Order by label'				=>	'Sorter etter',
'Order by username'			=>	'Brukernavn',
'Order by ip'				=>	'IP',
'Order by e-mail'			=>	'E-post',
'Order by expire'			=>	'Utløpsdato',
'Ascending'					=>	'Stigende',
'Descending'					=>	'Synkende',
'Submit search'				=>	'Foreta søk',

'E-mail label'				=>	'E-post',
'E-mail help'				=>	'E-post eller e-domenet du ønsker å forby (f.eks someone@somewhere.com eller somewhere.com). Se "Tillat utestengelse av e-postadresser" Under Tillatelser for mer informasjon.',
'IP label'					=>	'IP-adresser/IP-områder',
'IP help'					=>	'IP-adressen eller IP-området du ønsker å stenge ute (for eks. 150.11.110.1 or 150.11.110). Skill adressr med mellomrom. Dersom en IP allerede er angitt er dette den siste IP\'en som er kjent for denne brukeren i databasen.',
'IP help link'				=>	'Klikk %s for å vise IP-statistikk for denne brukeren.',
'Ban advanced head'			=>	'Utvidete innstillinger for utestengelse',
'Ban advanced subhead'		=>	'Suppler utestengelse med IP og e-post',
'Ban message label'			=>	'Melding ved utestengelse',
'Ban message help'			=>	'En melding som blir vist til bruker som er utestengt når han/hun når han/hun besøker tavla.',
'Message expiry subhead'		=>	'Melding ved utestengelse og utløp',
'Ban IP range info'			=>	'Du bør være svært forsiktig når du benytter IP-område for utestengelse på grunn av muligheten for at andre brukere har partielle IP-adresser som matcher det utestengte IP-området.',
'Expire date label'			=>	'Utløpsdato',
'Expire date help'			=>	'Dato når utestengelse fjernes automatisk (format: yyyy-mm-dd). La stå tomt dersom du ønsker å fjerne utestengelse manuelt.',

'Results head'				=>	'Søkeresultater',
'Results username head'		=>	'Brukernavn',
'Results e-mail head'		=>	'E-post',
'Results IP address head'	=>	'IP/IP-område',
'Results expire head'		=>	'Utløper',
'Results message head'		=>	'Melding',
'Results banned by head'		=>	'Utestengt av',
'Results actions head'		=>	'Handlinger',
'No match'					=>	'Ingen match',
'Unknown'					=>	'Ukjent',

);
