<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'				=>	'Kunne ikke sjekke for oppgradering fordi \'allow_url_fopen\' er deaktivert i dette systemet.',
'Upgrade check failed message'		=>	'Sjekk for oppgradering feilet av ukjente årsaker.',
'Running latest version message'		=>	'Du har siste versjon av FluxBB.',
'New version available message'		=>	'En ny versjon av FluxBB er tilgjengelig. Du kan laste ned den siste versjonen fra %s.',
'Not available'						=>	'Ikke tilgjengelig',
'Forum admin head'					=>	'Administrering av forum',
'NA'									=>	'Ikke tilgjengelig',
'Welcome to admin'					=>	'Velkommen til administrasjonssiden for FluxBB. Herfra kan du styre viktige sider ved tavla. Avhengig av om du er administrator eller moderator kan du:',
'Welcome 1'							=>	'Organisere kategorier og forum.',
'Welcome 2'							=>	'Opprette forum-vide alternativer og preferanser.',
'Welcome 3'							=>	'Kontrollere tillatelser for brukere og gjester.',
'Welcome 4'							=>	'Vise IP statistikk for brukere.',
'Welcome 5'							=>	'Utestenge brukere.',
'Welcome 6'							=>	'Sensurere uttrykk.',
'Welcome 7'							=>	'Sette opp brukergrupper og promoteringer.',
'Welcome 8'							=>	'Rydde opp i gamle poster.',
'Welcome 9'							=>	'Håndtere rapporter.',
'About head'							=>	'Om FluxBB',
'FluxBB version label'				=>	'FluxBB-versjon',
'Check for upgrade'					=>	'Se etter oppgradering',
'FluxBB version data'				=>	'v%s - %s',
'Server statistics label'			=>	'Server-statistikk',
'View server statistics'				=>	'Vis server-statistikk',
'Support label'						=>	'Støtte',
'Forum label'						=>	'Forum',
'IRC label'							=>	'IRC channel',

// Language definitions used in admin_statistics.php
'PHPinfo disabled message'			=>	'PHP funksjonen phpinfo() er deaktivert på denne serveren.',
'Server statistics head'				=>	'Server-statistikk',
'Server load label'					=>	'Serverbelastning',
'Server load data'					=>	'%s - %s user(s) online',
'Environment label'					=>	'Miljø',
'Environment data OS'				=>	'Plattform: %s',
'Show info'							=>	'Vis info',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Accelerator: %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'					=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'						=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'								=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'						=>	'Database',
'Database data rows'					=>	'Rekker: %s',
'Database data size'					=>	'Størrelse: %s',
);
