<?php

// Language definitions used in install.php, localized by adaur

$lang_install = array(

'Install message'				=>	'Filen \'config.php\' eksisterer ikke eller ødelagt. Dette innebærer at FluxBB ennå ikke er installert.',
'Choose install language'		=>	'Velg språk for installeringsskript',
'Choose install language info'	=>	'Språket som benyttes for installeringsskriptet. Standard språk som skal benyttes for tavla i seg selv angis nedenfor.',
'Install language'				=>	'Installeringsspråk',
'Change language'				=>	'Bytt språk',
'Next'							=>	'Neste',
'Already installed'				=>	'Det virker som FluxBB allerede er installert. Du skal gå <a href="index.php">hit</a> istedet.',
'You are running error'			=>	'Du kjører %1$s versjon %2$s. FluxBB %3$s krever minst %1$s %4$s for å fungere tilfredsstillende. Du må oppgradere din %1$s installasjon før du kan fortsette.',
'My FluxBB Forum'				=>	'Mitt FluxBB Forum',
'Description'					=>	'Desverre er det ingen som kan fortelle hvordan FluxBB egentlig er - du må prøve selv.',
'Username 1'						=>	'Brukernavn må ha minst 2 tegn.',
'Username 2'						=>	'Brukernavn kan ikke være over 25 tegn.',
'Username 3'						=>	'Brukernavnet "Gjest" er reservert.',
'Username 4'						=>	'Brukernavn kan ikke ha format som en IP-adresse.',
'Username 5'						=>	'Brukernavn kan ikke innholde tegnene \', " og [ eller ] på en gang.',
'Username 6'						=>	'Brukernavn kan ikke innholde noen av formatteringstaggene (BBCode) som forumet benytter.',
'Short password'					=>	'Passord må inneholde minst 4 tegn.',
'Passwords not match'			=>	'Passordene matcher ikke.',
'Wrong email'					=>	'Administrator-e-postadressen du tastet inn er ugyldig.',
'No board title'					=>	'Du må angi en tittel for tavla.',
'Error default language'			=>	'Standard-språket du har valgt synes ikke å eksistere.',
'Error default style'			=>	'Standard-utseende du har valgt synes ikke å eksistere.',
'No DB extensions'				=>	'Dette PHP-miljøet har ikke støtte for noen av databasene som FluxBB støtter. PHP må ha støtte for enten MySQL, PostgreSQL eller SQLite for at FluxBB skal bli installert.',
'Administrator username'			=>	'Administrator\'s brukernavn',
'Administrator password 1'		=>	'Administrator passord 1',
'Administrator password 2'		=>	'Administrator passord 2',
'Administrator email'			=>	'Administrator\'s e-post',
'Board title'					=>	'Tittel på tavle',
'Base URL'						=>	'Base URL',
'Required field'					=>	'er et påkrvd felt i dette skjemaet.',
'FluxBB Installation'			=>	'FluxBB Installasjon',
'Welcome'						=>	'Du er i ferd med å installere FluxBB. For å installere FluxBB, må du fylle ut skjemaet angitt nedenfor. Hvis det oppstår problemer med installeringen, bør du sjekke dokumentasjonen.',
'Install'						=>	'Installer FluxBB %s',
'Errors'							=>	'Følgende feil må korrigeres:',
'Database setup'					=>	'Oppsett av database',
'Info 1'							=>	'Vennligst fyll inn nødvendig informasjon for å sette opp databasen for FluxBB. Du må ha all informasjon du blir bedt om tilgjengelig, før du fortsetter med installeringen.',
'Select database'				=>	'Velg type databasee',
'Info 2'							=>	'FluxBB støtter i øyeblikket MySQL, PostgreSQL og SQLite. Hvis databasen du ønsker å kople opp mot FluxBB mangler i nedtrekksmenyen nedenfor, innebærer dette at PHP miljøet ikke har støtte for denne bestemte databasen. Mer informasjon om støtte for bestemte versjoner av hver database finner du i FAQ.',
'Dual MySQL'						=>	'FluxBB har oppdaget at PHP-miljøet støtter to forskjellige måter å kommunisere med MySQL på. De to alternativene er kalt standard og forbedret (MySQLi). Hvis du er usikker på hvilken du skal bruke, begynn med å prøve forbedret, og hvis det ikke hjelper, kan du prøve standard.',
'InnoDB'							=>	'FluxBB har oppdaget at MySQL server kan støtte <a href="http://dev.mysql.com/doc/refman/5.0/en/innodb.html"> InnoDB </ a>. Dette ville være et godt valg hvis du planlegger å kjøre et stort forum. Hvis du er usikker, anbefales det at du ikke bruker InnoDB.',
'Database type'					=>	'Type database',
'Required'						=>	'(Påkrevd)',
'Database hostname'				=>	'Skriv inn din servers domenenavn',
'Info 3'							=>	'Adressen til databaseserveren (eksempel: localhost, db.myhost.com eller 192.168.0.15). Du kan angi et egendefinert portnummer hvis databasen ikke kjører på standard port (eksempel: localhost: 3580). For SQLite-støtte, kan du bare fylle inn noe eller la det stå som \'localhost\'.',
'Database server hostname'		=>	'Database-serverens vertsnavn',
'Database enter name'			=>	'Fyll inn databasens navn',
'Info 4'							=>	'Navnet på databasen som FluxBB vil bli installert til. Databasen må eksistere og må derfor være opprettet på forhånd. For SQLite er dette den relative banen til databasefilen. Av sikkerhetsmessige grunner er det sterkt anbefalt å plassere SQLite-databasen i en privat (ikke tilgjengelig på Internett) katalog når det er mulig. Hvis SQLite-databasefilen ikke eksisterer, vil FluxBB forsøke å opprette den.',
'Database name'					=>	'Navn på database',
'Database enter informations'	=>	'Fyll inn brukernavn og passord for databasen',
'Database username'				=>	'Brukernavn for database',
'Info 5'							=>	'Skriv inn brukernavn og passord koblet til databasen. Ignorer dette om du benytter SQLite.',
'Database password'				=>	'Passord for database',
'Database enter prefix'			=>	'Fyll inn tabell-prefix for databasen',
'Info 6'							=>	'Dersom du ønsker det, kan du angi et tabell-prefix. På denne måten kan du kjøre flere kopier av FluxBB i samme database (eksempel: foo_).',
'Table prefix'					=>	'Tabell prefix',
'Administration setup'			=>	'Oppsett av administrasjon',
'Info 7'							=>	'Vennligst fyll inn nødvendig informasjon for å opprette en administrator for din FluxBB-installasjon.',
'Admin enter username'			=>	'Fyll inn Administrators brukernavn',
'Info 8'							=>	'Brukernavn for forumets administrator. Du kan senere opprette flere administratorer og moderatorer. Brukernavn må være mellom 2 og 25 tegn langt.',
'Admin enter password'			=>	'Fyll inn og bekreft Administrators passord',
'Info 9'							=>	'Passord må inneholde minst 4 tegn. Det skilles på små og store bokstaver.',
'Password'						=>	'Passord',
'Confirm password'				=>	'Bekreft passord',
'Admin enter email'				=>	'Fyll inn Administrators e-postadresse',
'Info 10'						=>	'E-postadressen til forumets administrator.',
'Board setup'					=>	'Opprette tavle',
'Info 11'						=>	'Vennligst fyll inn nødvendig informasjon for å opprette din FluxBB tavle.',
'Enter board title'				=>	'Angi tittel på tavla',
'Info 12'						=>	'Tittelen på denne tavla (vises øverst på hver side).',
'Enter board description'		=>	'Fyll inn beskrivelse av tavla',
'Info 13'						=>	'En kort beskrivelse av tavla (vises øverst på hver side). Dette feltet kan inneholde HTML.',
'Board description'				=>	'Beskrivelse av tavla',
'Enter base URL'					=>	'Fyll inn Base URL for din FluxBB installasjon',
'Info 14'						=>	'URL\'n for din FluxBB tavle (eksempel: http://forum.myhost.com or http://myhost.com/~myuser). Dette <strong>må</strong> være korrekt, ellers vil ikke administratorer and moderatorer være i stand til å sende skjemaer. Vær oppmerksom på at forhåndsinnstilt verdi nedenfor bare er en kvalifisert gjetning.',
'Choose the default language'	=>	'Velg standard språk',
'Info 15'						=>	'Standardspråket som brukes av gjester og brukere som ikke har tilpasset språk i sin profil.',
'Default language'				=>	'Standard språk',
'Choose the default style'		=>	'Velg standard utseende',
'Info 16'						=>	'Standard utseende som brukes av gjester og brukere som ikke har tilpasset utseende i sin profil.',
'Default style'					=>	'Standard utseende',
'Start install'					=>	'Start installering',
'DB type not valid'				=>	'\'%s\' er ikke en gyldig databasetype',
'Table prefix error'				=>	'Tabellprefikset \'%s\' inneholder ulovlige tegn eller er for langt. Prefikset kan inneholde bokstavene a til z, noen tall og understrekingstegnet. Det må imidlertid ikke starte med et tall. Maksimal lengde er 40 tegn. Velg et annet prefiks.',
'Prefix reserved'				=>	'Tabellprefikset \'sqlite_\' er reservert for bruk av SQLite-motoren. Velg et annet prefiks.',
'Existing table error'			=>	'En tabell som kalles \'%susers\' er allerede til stede i databasen \'%s\'. Dette kan bety at FluxBB allerede er installert, eller at en annen programvare er installert og opptar ett eller flere av tabellnavnene FluxBB krever. Hvis du ønsker å installere flere kopier av FluxBB i samme database, må du velge et annet tabellprefix.',
'InnoDB off'						=>	'InnoDB synes ikke å være aktivert. Velg et database-lag som ikke har InnoDB støtte, eller aktiver InnoDB på MySQL serveren.',
'Administrators'					=>	'Administratorer',
'Administrator'					=>	'Administrator',
'Moderators'						=>	'Moderatorer',
'Moderator'						=>	'Moderator',
'Guests'							=>	'Gjester',
'Guest'							=>	'Gjest',
'Members'						=>	'Medlemmer',
'Announcement'					=>	'Fyll inn din kunngjøring her',
'Rules'							=>	'yll inn dine regler her',
'Maintenance message'			=>	'Forumene er midlertidig nede på grunn av vedlikehold. Vennligst prøv senere.',
'Test post'						=>	'Test-tråd',
'Message'						=>	'Hvis du leser på dette (som jeg antar du gjør), ser installasjonen av FluxBB ut til å være vellykket! Nå kan du logge inn og navigere over til administrasjonens kontrollpanel for å konfigurere ditt forum.',
'Test category'					=>	'Test-kategori',
'Test forum'						=>	'Test-forum',
'This is just a test forum'		=>	'Dette er bare et test-forum',
'Alert cache'					=>	'<strong> Cache katalogen (hurtigminne) er for øyeblikket ikke skrivbar!</strong> For at FluxBB skal fungere tilfredsstillende, må katalogen <em>%s</em> være skrivbar for PHP. Bruk eventuelt chmod til å sette riktige mapperettigheter. Hvis du er i tvil, chmod til 0777.',
'Alert avatar'					=>	'<strong>Avatar-katalogen er for øyeblikket ikke skrivbar! </strong> Hvis du vil at brukerne skal kunne laste opp egne avatar-bilder må du gjøre katalogen <em>%s</em> skrivbar for PHP. Du kan senere velge å lagre avatar bilde i en annen katalog (se Admin/Alternativer). Bruk chmod til å sette riktige mapperettigheter. Hvis du er i tvil, chmod til 0777.',
'Alert upload'					=>	'<strong>Opplasting av filer synes å være blokkert på denne serveren! </strong>Hvis du vil at brukerne skal kunne laste opp sine egne avatar-bilder du må aktivere "file_upload" innstillingen i PHP. Når filopplastinger er aktivert, kan opplasting av avatarer aktiveres i Administrasjon/Valg/Avatarer.',
'FluxBB has been installed'		=>	'FluxBB er installert. Følg instruksjonene nedenfor for å full føre installeringen.',
'Final instructions'				=>	'Instruksjoner til slutt',
'Info 17'						=>	'For å fullføre installasjonen, må du klikke på knappen nedenfor for å laste ned en fil som heter config.php. Du må deretter laste opp denne filen til rotkatalogen for din FluxBB-installasjon.',
'Info 18'						=>	'Når du har lastet opp filen "config.php"", er FluxBB ferdig installert! Du kan deretter <a href="index.php"> gå til forumet </a>.',
'Download config.php file'		=>	'Last ned config.php filen',
'FluxBB fully installed'			=>	'FluxBB er ferdig installert! Du kan nå <a href="index.php">gå til forumet</a>.',

);
