<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Oppgi gyldig e-postadresse',
'Email legend 2'				=>	'Oppgi gyldig e-postadresse og bekreft',
'Localisation legend'		=>	'Instillinger for språk og tid',
'Time zone'					=>	'Tidssone',
'Time zone info'				=>	'For at forumet til å vise riktig tid må du velge din lokale tidssone. Hvis sommertid er aktuelt, bør du også velge dette (flytter tiden fram 1 time).',
'DST'						=>	'Sommertid er i kraft (forskyver tiden 1 time fram) ..',
'Time format'				=>	'Tidsformat',
'Date format'				=>	'Datoformat',
'Default'					=>	'Standard',
'Language'					=>	'Språk',
'Email setting info'			=>	'Velg om du vil at e-postadressen din skal være synlig for andre brukere eller ikke, og om du vil at andre brukere skal kunne sende deg e-post fra forumsidene eller ikke.',
'Email setting 1'			=>	'Vis din e-postadresse.',
'Email setting 2'			=>	'Skjul din e-postadresse, men tillat e-post fra forumsidene.',
'Email setting 3'			=>	'Skjul din e-postadresse og tillat ikke e-post fra forumsidene.',
'Privacy options legend'		=>	'Visning av e-postadresse',
'Confirm pass'				=>	'Bekreft passord',

'Username too short'			=>	'Brukernavn må inneholde minst 2 tegn. Vennligst velg et annet (lengre) brukernavn.',
'Username too long'			=>	'Brukernavn må ikke inneholde mer enn 25 tegn. Vennligst velg et annet (kortere) brukernavn.',
'Username guest'				=>	'Brukernavnet "Gjest" er reservert. Vennligst velg et annet brukernavn.',
'Username IP'				=>	'Brukernavn kan ikke ha format som en IP-adresse. Velg et annet brukernavn.',
'Username reserved chars'	=>	'Brukernavn kan ikke inneholde alle tegnene \', " og [ eller ] samtidig. Velg et annet brukernavn.',
'Username BBCode'			=>	'Brukernavn kan ikke inneholde noen av de tekstformateringstaggene (BBCode) som forumet bruker. Velg et annet brukernavn.',
'Banned username'			=>	'Brukernavnet du skrev er forbudt i dette forumet. Velg et annet brukernavn.',
'Pass too short'				=>	'Passord må inneholde minst 4 tegn. Vennligst velg et annet (lengre) passord.',
'Pass not match'				=>	'Passordene matcher ikke.',
'Banned email'				=>	'E-postadressen du oppga er forbudt i dette forumet. Velg en annen e-postadresse.',
'Dupe email'					=>	'Noen andre er allerede registrert med denne e-postadressen. Velg en annen e-postadresse.',
'Sig too long'				=>	'Signaturer kan ikke være lenger enn %1$s tegn. Vennligst reduser signaturen med %2$s tegn.',
'Sig too many lines'			=>	'Signaturer kan ikke ha mer enn %s linjer.',
'Bad ICQ'					=>	'Du oppga en ugyldig ICQ UIN. Vennligst gå tilbake og korriger.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Moscow, Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Yekaterinburg',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Krasnoyarsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita, Irkutsk',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Vladivostok',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Magadan',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands, Kamchatka',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
