<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'Profilmeny',
'Section essentials'				=>	'Generelt',
'Section personal'				=>	'Personlig',
'Section messaging'				=>	'Meldinger',
'Section personality'			=>	'Personlig informasjon',
'Section display'				=>	'Visning',
'Section privacy'				=>	'Privat',
'Section admin'					=>	'Administrasjon',

// Miscellaneous
'Username and pass legend'		=>	'Fyll inn brukernavn og passord ',
'Personal details legend'		=>	'Fyll inn personlige detaljer',
'Contact details legend'			=>	'Fyll inn dine kontaktdetaljer',
'User activity'					=>	'Brukeraktivitet',
'Paginate info'					=>	'Sett antall tråder og innlegg du ønsker skal vises på hver forumside.',

// Password stuff
'Pass key bad'					=>	'Nøkkelen for passord-aktivering er feil eller har utløpt. Vennligst gjenta prosedyren for å få tilsendt nytt passord. Dersom det mislykkes, ta kontakt med forumets administrator ved',
'Pass updated'					=>	'Passordet er oppdatert.Du kan nå logge inn med ditt nye passord.',
'Pass updated redirect'			=>	'Passord oppdatert. Omdirigerer …',
'Wrong pass'						=>	'Gammelt passord er feil.',
'Change pass'					=>	'Endre passord',
'Change pass legend'				=>	'Oppgi og bekreft ditt nye passord',
'Old pass'						=>	'Gammelt passord',
'New pass'						=>	'Nytt passord',
'Confirm new pass'				=>	'Bekreft nytt passord',
'Pass info'						=>	'Passord må inneholde minst 4 tegn. Det skilles mellom små og store bokstaver.',

// Email stuff
'Email key bad'					=>	'Nøkkelen for passord-aktivering er feil eller har utløpt. Vennligst gjenta prosedyren for å endre e-postadresse. Dersom det mislykkes, ta kontakt med forumets administrator ved',
'Email updated'					=>	'Din epostadresse er oppdatert.',
'Activate email sent'			=>	'En e-post har blitt sendt til den oppgitte adressen med instruksjoner om hvordan du aktiverer den nye e-postadressen. Dersom du ikke har fått denne e-posten kan kontakte forumets administrator ved',
'Email legend'					=>	'Fyll inn din nye e-postadresse',
'Email instructions'				=>	'En e-post vil bli sendt til din nye adresse med en aktiverings-link. Du må klikke på linken i e-posten du mottar for å aktivere den nye adressen.',
'Change email'					=>	'Endre e-postadresse',
'New email'						=>	'Ny epost',

// Avatar upload stuff
'Avatars disabled'				=>	'Administrator har deaktivert avatar-støtte.',
'Too large ini'					=>	'Den valgte filen er for stor til å lastes opp. Serveren tillot ikke opplasting.',
'Partial upload'					=>	'Den valgte filen ble bare delvis lastet opp. Vennligst prøv igjen.',
'No tmp directory'				=>	'PHP kunne ikke lagre filen til en midlertidig mappe.',
'No file'						=>	'Du har ikke valgt fil som skal lastes opp.',
'Bad type'						=>	'Filen du prøvde å laste opp er ikke av en godkjent type. Tillatte filtyper er gif, jpeg and png.',
'Too wide or high'				=>	'Filen du prøvde å laste opp er bredere og/eller høyere enn det som er tillatt',
'Too large'						=>	'Filen du prøvde å laste opp er større enn det som er tillatt',
'pixels'							=>	'piksler',
'bytes'							=>	'bytes',
'Move failed'					=>	'Serveren kunne lagre den opplastede filen. Vennligst kontak forumets administrator ved',
'Unknown failure'				=>	'En ukjent feil oppstod. Vennligst prøv igjen.',
'Avatar upload redirect'			=>	'Avatar lastet opp. Omdirigerer …',
'Avatar deleted redirect'		=>	'Avatar slettet. Omdirigerer …',
'Avatar desc'					=>	'En avatar er et lite bilde som vises under ditt brukernavn i dine innlegg. Det må ikke være større enn',
'Upload avatar'					=>	'Last opp avatar',
'Upload avatar legend'			=>	'Velg en avatarfil som skal lastes opp',
'Delete avatar'					=>	'Slett avatar', // only for admins
'File'							=>	'Fil',
'Upload'							=>	'Last opp', // submit button

// Form validation stuff
'Forbidden title'				=>	'Tittelen du har oppgitt inneholder et forbudt ord. Velg en annen tittel.',
'Profile redirect'				=>	'Profil lastet opp. Omdirigerer …',

// Profile display stuff
'Users profile'					=>	'%s\'s profil',
'Username info'					=>	'Brukernavn: %s',
'Email info'						=>	'E-post: %s',
'Posts info'						=>	'Innlegg: %s',
'Registered info'				=>	'Registrert: %s',
'Last post info'					=>	'Siste innlegg: %s',
'Last visit info'				=>	'Siste besøk: %s',
'Show posts'						=>	'Vis alle innlegg',
'Show topics'					=>	'Vis alle tråder',
'Show subscriptions'				=>	'Vis alle abonnement',
'Realname'						=>	'Virkelig navn',
'Location'						=>	'Sted',
'Website'						=>	'Nettside',
'Invalid website URL'			=>	'Nettadressen du oppgav er ugyldig.',
'Website not allowed'			=>	'Du har ikke tillatelse til å legge til et nettsted til profilen din enda.',
'Jabber'							=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'MSN Messenger',
'AOL IM'							=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'							=>	'Avatar',
'Signature'						=>	'Signatur',
'Sig max size'					=>	'Maks lengde: %s tegn/maks antall linjer: %s',
'Avatar legend'					=>	'Angi visningsalternativer for din avatar',
'Avatar info'					=>	'En avatar er et lite bilde som blir vist i alle dine innlegg. Du kan laste opp en avatar ved å klikke på lenken under.',
'Change avatar'					=>	'Endre avatar',
'Signature legend'				=>	'Lag din signatur',
'Signature info'					=>	'En signatur er en kort tekst knyttet til dine innlegg. I den kan du skrive inn det du ønsker. Du kan for eksempel legge inn ditt favorittsitat eller ditt stjernetegn. Det er opp til deg! I signaturen din kan du bruke BBCode om det er tillatt i det aktuelle forumet. Du kan se hvilke funksjoner som er tillatt/aktivert i listen nedenfor når du redigerer signaturen din.',
'Sig preview'					=>	'Forhåndsvisning av nåværende signatur:',
'No sig'							=>	'Ingen signatur er for øyeblikket lagret i din profil.',
'Signature quote/code/list/h'	=>	'BBCoder for sitat, kode, liste, og overskrift er ikke tillatt i signaturer.',
'Topics per page'				=>	'Tråder',
'Posts per page'					=>	'Innlegg',
'Leave blank'					=>	'La stå tomt for å bruke forumets standardverdi.',
'Subscription legend'			=>	'Angi dine abonnementsalternativer',
'Notify full'					=>	'Ta med en ren tekstversjon av nye innlegg i varslingsmeldinger sendt med e-post.',
'Auto notify full'				=>	'Abonner automatisk på alle tråder du har opprettet innlegg i.',
'Show smilies'					=>	'Vis smilefjes som ikoner.',
'Show images'					=>	'Vis bilder i innlegg.',
'Show images sigs'				=>	'Vis bilder i brukersignaturer.',
'Show avatars'					=>	'Vis brukeravatarer i innlegg.',
'Show sigs'						=>	'Vis brukersignaturer.',
'Style legend'					=>	'Velg foretrukket utseende på forumsidene',
'Styles'							=>	'Utseende',
'Admin note'						=>	'Administrators notater',
'Pagination legend'				=>	'Angi sidevisningsalternativer',
'Post display legend'			=>	'Angi valg for visning av innlegg',
'Post display info'				=>	'Hvis du har en treg tilkobling vil deaktivering av disse alternativene, spesielt bildevisning i innlegg og signaturer, gjøre at sidene lastes raskere.',
'Instructions'					=>	'Når du har oppdatert profilen din, vil du bli sendt tilbake til denne siden.',

// Administration stuff
'Group membership legend'		=>	'Velg brukergruppe',
'Save'							=>	'Lagre',
'Set mods legend'				=>	'Angi moderatortilgang',
'Moderator in info'				=>	'Velg hvilke forum denne brukeren skal få lov til å moderere. Merk: Dette gjelder bare moderatorer. Administratorer har alltid alle tillatelser i alle forum.',
'Update forums'					=>	'Oppdater forumer',
'Delete ban legend'				=>	'Slett eller utesteng bruker (kan kun utføres av administrator)',
'Delete user'					=>	'Slett bruker',
'Delete spammer'					=>	'Slett bruker og rapportér spam',
'Delete spammer note'			=>	'Etter sletting vil denne brukeren bli rapportert som spammer. Dette er ment for rapportering av spam-programmer og <strong>ikke</strong> for å irritere brukere!',
'Spammer delete redirect'		=>	'Bruker slettet og rapportert. Omdirigerer &hellip;',

'Ban user'						=>	'Utesteng bruker',
'Confirm delete legend'			=>	'Viktig: les før du sletter bruker',
'Confirm delete user'			=>	'Bekreft sletting av bruker',
'Confirmation info'				=>	'Vennligst bekreft at du ønsker å slette bruker', // the username will be appended to this string
'Delete warning'					=>	'Advarsel! Slettede bruker og/eller innlegg kan ike gjenoppbygges. Hvis du velger å ikke slette innlegg laget av denne brukeren, kan innleggene slettes manuelt på et senere tidspunkt.',
'Delete posts'					=>	'Slett alle innlegg og tråder som denne brukeren har opprettet.',
'Delete'							=>	'Slett', // submit button (confirm user delete)
'User delete redirect'			=>	'Bruker slettet. Omdirigerer …',
'Group membership redirect'		=>	'Gruppemedlemskap lagret. Omdirigerer …',
'Update forums redirect'			=>	'Forumets moderator-rettigheter oppdatert. Omdirigerer …',
'Ban redirect'					=>	'Omdirigerer …',
'No delete admin message'		=>	'Administratorer kan ikke slettes. For å slette denne brukeren, må du først flytte ham/henne til en annen brukergruppe.',

);
