<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'Brukersøk',
'No search permission'				=>	'Du har ikke tillatelse til å benytte brukersøk.',
'Search flood'						=>	'Minst %s sekunder må passere mellom hvert søk. Vennligst vent %s sekunder og søk på nytt.',
'Search'								=>	'Søk',
'Search criteria legend'				=>	'Angi dine søkekriterier',
'Search info'						=>	'Fyll inn ett eller flere søkeord og skill ordene med mellomrom. Bruk <strong>AND</strong>, <strong>OR</strong> og <strong>NOT</strong> for å avgrense søket. For å søke på forfatter må du fylle inn forfatterens brukernavn i søkefeltet. Bruk jokertegn (*) for delvis treff.',
'Keyword search'						=>	'Søk med nøkkelord',
'Author search'						=>	'Forfattersøk',
'Search in legend'					=>	'Forum det skal søkes i',
'Search in info'						=>	'Velg hvilke(t) forum du vil søke i og om du vil søke i titler, innleggstekst eller begge.',
'Search multiple forums info'		=>	'Dersom ingen forum er valgt, vil søket gjennomføres i alle forum',
'Forum search'						=>	'Forum',
'All forums'							=>	'Alle forum',
'Search in'							=>	'Søk i',
'Message and subject'				=>	'Tekst og tittel',
'Message only'						=>	'Kun tekst',
'Topic only'							=>	'Kun tittel',
'Sort by'							=>	'Sorter etter',
'Sort order'							=>	'Sorteringsrekkefølge',
'Search results legend'				=>	'Velg hvordan du vil vise dine søkeresultater',
'Search results info'				=>	'Du kan velge hvordan du vil sortere og vise resultatene.',
'Sort by post time'					=>	'Tidspunkt for innlegg',
'Sort by author'						=>	'Forfatter',
'Sort by subject'					=>	'Tittel',
'Sort by forum'						=>	'Forum',
'Ascending'							=>	'Stigende',
'Descending'							=>	'Synkende',
'Show as'							=>	'Vis resultater som',
'Show as topics'						=>	'Tråder',
'Show as posts'						=>	'Innlegg',

// Results
'Search'								=>	'Søk',
'Search results'						=>	'Søkeresultater',
'Quick search show_new'				=>	'Ny',
'Quick search show_recent'			=>	'Aktiv',
'Quick search show_unanswered'		=>	'Ubesvarte',
'Quick search show_replies'			=>	'Publisert',
'Quick search show_user_topics'		=>	'Tråder av %s',
'Quick search show_user_posts'		=>	'Innlegg av %s',
'Quick search show_subscriptions'	=>	'Abonnert av %s',
'By keywords show as topics'			=>	'Tråder som inneholder \'%s\'',
'By keywords show as posts'			=>	'Innlegg som inneholder \'%s\'',
'By user show as topics'				=>	'Tråder med innlegg fra %s',
'By user show as posts'				=>	'Innlegg fra %s',
'By both show as topics'				=>	'Tråder med innlegg som inneholder \'%s\', fra %s',
'By both show as posts'				=>	'Innlegg som inneholder \'%s\', fra %s',
'No terms'							=>	'Du må skrive inn minst ett søkeord og/eller en forfatter å søke etter.',
'No hits'							=>	'Ditt søk ga ingen treff.',
'No user posts'						=>	'Det er ingen innlegg opprettet av denne brukeren i dette forumet.',
'No user topics'						=>	'Det er ingen tråder opprettet av denne brukeren i dette forumet.',
'No subscriptions'					=>	'Denne brukeren abonnerer for tiden ikke på noen tråder.',
'No new posts'						=>	'Det er ingen tråder med nye innlegg siden ditt siste besøk.',
'No recent posts'					=>	'Ingen nye innlegg er opprettet i løpet av de siste 24 timene.',
'No unanswered'						=>	'Det er ingen ubesvarte innlegg i noen forum.',
'Go to post'							=>	'Gå til innlegg',
'Go to topic'						=>	'Gå til tråd'

);
